### ISSUE TITLE
[Cauldron] Fails to load configuration

### ISSUE THREAD

**Issue by thisischrys** [dmulloy2/ProtocolLib#10]
I have tried a whole bunch of builds, from http://ci.shadowvolt.com/job/ProtocolLib/, https://github.com/aadnk/ProtocolLib and http://assets.comphenix.net/job/ProtocolLib/ and the bukkit page. None of them seem to load. They all give the message disabling protocollib.
This is from the build herehttp://ci.shadowvolt.com/job/ProtocolLib/10/

http://pastebin.com/XSLUPQ0e

Is there just no current cauldron build or am I missing something?

**Comment by Nentify** [comment]
Not having this issue with ProtocolLib 3.4.1-SNAPSHOT

**Comment by dmulloy2** [comment]
Regardless of the status of this issue, we can no longer feasibly support Cauldron (all downloads and source are completely removed)
