### ISSUE TITLE
Cannot find NetworkManager

### ISSUE THREAD

**Issue by LewUwU** [dmulloy2/ProtocolLib#1002]
**Describe the bug**
Cannot find NetworkManager (Spams the console)

**To Reproduce**
1. Install ProtocolLib (Latest version, 4.5.1 from SpigotMC)
2. Join the Server

**Expected behavior**
I dont know, really. but my SportPaper fork have the latest netty version

**Screenshots**
None

**Version Info**
Protocol Dump: https://pastebin.com/rXMDi2Dk

**Additional context**
Full error: https://pastebin.com/sQbTUkDZ

**Comment by kristupas098** [comment]
same

**Comment by ethsmith** [comment]
This is also a problem with nachospigot

**Comment by MacacoLew** [comment]
https://github.com/aadnk/ProtocolLib/pull/175/commits/2e213338ecba4383ec28ac9f48d54e3d624cf3d5

This pull request fix's the issue, im not getting the spam in console with that patch

**Comment by MacacoLew** [comment]
#1067
