### ISSUE TITLE
How to get minecraft sound name instead of bukkit Sound enum

### ISSUE THREAD

**Issue by Epicnicity322** [dmulloy2/ProtocolLib#1019]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
When checking for the packet NAMED_SOUND_EFFECT, I can get the bukkit Sound enum with #getSoundEffects(), however, is there a way to get the minecraft sound name, instead of the enum?

**API method(s) used**
ProtocolLibrary#getProtocolManager()
ProtocolManager#addPacketListener()
PacketAdapter#onPacketSending()
PacketEvent#getSoundEffects()

**Expected behavior**
The sound name from minecraft sound list, instead of bukkit Sound enum.

**Code**
```JAVA
protocolManager.addPacketListener(
  new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.NAMED_SOUND_EFFECT) {
    @Override
    public void onPacketSending(PacketEvent event) {
        // Prints bukkit Sound enum
        System.out.println(event.getPacket().getSoundEffects().read(0).name());
    }
});
```

**Comment by patrick-mc** [comment]
You can use CraftSound#getSound to get a minecraft keyed sound
