### ISSUE TITLE
PacketListener unloading the plugin

### ISSUE THREAD

**Issue by ofirtim** [dmulloy2/ProtocolLib#102]
soo.. i am working on network plugin that standed on Spigot/bukkit and for some reason when i am using the packetlistener (that i REALLY NEED) is failing the plugin from load...

http://pastebin.com/V7L2tssS

could you might help me with that? please

**Comment by dmulloy2** [comment]
Do you have ProtocolLib installed? Is it listed as a dependency in your plugin.yml?

**Comment by ofirtim** [comment]
i did'nt really used it as dependency... but i have installed it yes

**Comment by dmulloy2** [comment]
You have to list it as a dependency: ````depend: [ProtocolLib]````

**Comment by ofirtim** [comment]
thanks fixed!
