### ISSUE TITLE
Getting SoundEffect no longer works

### ISSUE THREAD

**Issue by SoSeDiK** [dmulloy2/ProtocolLib#1023]
**Describe the bug**
Using code `String sound = event.getPacket().getSoundEffects().read(0).toString();` will produce the following error: https://pastebin.com/wB1LmVZP

**Additional context**
I believe that is caused by a recent change in CraftSound: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/424598d2943c6d787dafcfd60251fe9fadcc9d70#src/main/java/org/bukkit/craftbukkit/CraftSound.java

**Comment by TauCubed** [comment]
Same issue

**Comment by sgdc3** [comment]
I have the same issue

**Comment by stonar96** [comment]
https://github.com/PaperMC/Paper/pull/4901
