### ISSUE TITLE
Error Armorstand

### ISSUE THREAD

**Issue by kiltzor** [dmulloy2/ProtocolLib#1026]
Hello , 

I have a problem with protocolib, every time I’m in front of a hologram, I see armorstands every time; I’d like to stop seeing them! On the other hand if I delete the plugin I do not have the problem. How to solve the problem? 

Protocolib latest version
Server : 1.16.3 latest bjuild

**Comment by dmulloy2** [comment]
This is an issue with Holographic Displays, not ProtocolLib
