### ISSUE TITLE
Java v15 not working propperly

### ISSUE THREAD

**Issue by donvdp** [dmulloy2/ProtocolLib#1028]
hmm protocollib is kinda important to allot of my plugins... unfortunatly upgrading to java v 15 there are some issues that stop my server from running propperly. Any suggestions how to fix this ?

Startup log: [https://hastebin.com/raw/ulabucukeq](https://hastebin.com/raw/ulabucukeq)

Running papermc build 312

**Comment by DarkSavci** [comment]
same issue

**Comment by CrystallDEV** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/pull/1025
