### ISSUE TITLE
[Question] Convert json to plain string

### ISSUE THREAD

**Issue by kangarko** [dmulloy2/ProtocolLib#103]
I am listening to the CHAT packet that is sent out of the server and I would like to edit it before it's sent. Since it is in Json format, is there any way how to convert it back to plain string? Like {"text":"Hello World", "color":"red"} to "&cHello World"?

I know there is a way to convert plain message to json in: 

>com.comphenix.protocol.wrappers.WrappedChatComponent.fromChatMessage()

Also, I noticed there is a way in bungee: 

>net.md_5.bungee.chat.ComponentSerializer.parse()

but since that package was added only recently I would like to use it from ProtocolLib to provide backward compatibility.

**Comment by dmulloy2** [comment]
There isn't a way to do this in ProtocolLib, but using the Bungee Chat API is a pretty safe bet. According to mcstats, it is included in ~75% of servers. You can convert back and forth between ProtocolLib and the Bungee Chat API using the ComponentConverter, but that was added fairly recently. You could use the same logic if you want to maximize compatibility.

**Comment by kangarko** [comment]
Thank you. I think bungee chat api will be sufficient.
