### ISSUE TITLE
Send packet PacketPlayOutEntityMetadata invisibility?

### ISSUE THREAD

**Issue by RMrenex** [dmulloy2/ProtocolLib#1031]
Hello everyone,

I'm trying to send a PacketPlayOutEntityMetadata to mask  entity but it doesn't work. I must certainly go wrong.
My code -> https://hastebin.com/eyifubezir.java

Thank you for your answers.

**Comment by dmulloy2** [comment]
That's plain nms, you aren't using ProtocolLib

**Comment by RMrenex** [comment]
Yes, sorry.
