### ISSUE TITLE
CI build server down. 

### ISSUE THREAD

**Issue by NocFA** [dmulloy2/ProtocolLib#1033]
**Describe the bug**
Your CI server is down.

**To Reproduce**
1. Go to https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
2. See error

**Expected behavior**
A direct download of the latest build.

**Comment by pianoman911** [comment]
Same Issue here

**Comment by dmulloy2** [comment]
should be fixed now
