### ISSUE TITLE
1.16 Protocllib link problems

### ISSUE THREAD

**Issue by Sanictr** [dmulloy2/ProtocolLib#1035]
hello protocollib 1.16 I want to download the latest development but when I click the link you gave in spigot, I cannot reach the site. Can you help me?
![protocollib1](https://user-images.githubusercontent.com/76136339/102562155-86e96d80-40e7-11eb-9766-549998c1cf53.png)
![protocollib2](https://user-images.githubusercontent.com/76136339/102562163-894bc780-40e7-11eb-95a0-1d6e9670e22c.png)

**Comment by owlman5126** [comment]
As far as I know the website is down

**Comment by owlman5126** [comment]
#1033
