### ISSUE TITLE
DMULLOY2 NEXUS SERVER 404 NOT FOUND

### ISSUE THREAD

**Issue by Apple6050** [dmulloy2/ProtocolLib#1037]
**Describe the bug**
Currently, dmulloy2's server has a problem, so a 404 NOT FOUND error appears in the https://repo.dmulloy2.net/nexus server. Accordingly, an error occurs in the project using ProtocolLib. I hope you can fix the server quickly.

**Comment by realteusu** [comment]
Same issue #1033.

**Comment by Apple6050** [comment]
@realteusu nexus and Jenkins is Different.

**Comment by dmulloy2** [comment]
should be fixed now
