### ISSUE TITLE
Time Out for Players

### ISSUE THREAD

**Issue by XragonX147** [dmulloy2/ProtocolLib#1038]
**Describe the bug**
A Player (not OP) gets Time Outed after 15-30 Seconds after Joining the Server.

**Version Info**
ProtocolLib Dump
Timestamp: 12/20/20 21:24:34

ProtocolLib Version: ProtocolLib v4.6.0-SNAPSHOT-b483
Bukkit Version: 1.16.4-R0.1-SNAPSHOT
Server Version: git-Paper-337 (MC: 1.16.4)
Java Version: 11.0.9

ProtocolLib: com.comphenix.protocol.ProtocolLib@6abb598e[
  statistics=com.comphenix.protocol.metrics.Statistics@21d5bc81
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2228287a
  packetTask=8
  tickCounter=8137
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6818bb43
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@58dfe8e7
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@546276c9
  commandProtocol=com.comphenix.protocol.CommandProtocol@37eaefc7
  commandPacket=com.comphenix.protocol.CommandPacket@1a8598da
  commandFilter=com.comphenix.protocol.CommandFilter@3d3ad3bd
  packetLogging=com.comphenix.protocol.PacketLogging@7aa93eed
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@1add72a8
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-337,minecraftVersion=1.16.4}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@47e4e372
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b483, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@5b0973e
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@6aa40e8b[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6818bb43
  packetListeners=[PacketAdapter[plugin=MessageEditor, sending=ListeningWhitelist[priority=HIGHEST, packets=[SCOREBOARD_SCORE[class=PacketPlayOutScoreboardScore, id=77], DISCONNECT[class=PacketLoginOutDisconnect, id=0], BOSS[class=PacketPlayOutBoss, id=12], CHAT[class=PacketPlayOutChat, id=14], KICK_DISCONNECT[class=PacketPlayOutKickDisconnect, id=25], SCOREBOARD_OBJECTIVE[class=PacketPlayOutScoreboardObjective, id=74]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Negativity, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PING[class=PacketStatusInPing, id=1], START[class=PacketStatusInStart, id=0], START[class=PacketLoginInStart, id=0], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], CHAT[class=PacketPlayInChat, id=3], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=15], USE_ENTITY[class=PacketPlayInUseEntity, id=14], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=17], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=11], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=13], B_EDIT[class=PacketPlayInBEdit, id=12], TRANSACTION[class=PacketPlayInTransaction, id=7], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=8], TR_SEL[class=PacketPlayInTrSel, id=35], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], BEACON[class=PacketPlayInBeacon, id=36], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ITEM_NAME[class=PacketPlayInItemName, id=32], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BOAT_MOVE[class=PacketPlayInBoatMove, id=23], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=25], PICK_ITEM[class=PacketPlayInPickItem, id=24], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], STRUCT[class=PacketPlayInStruct, id=42], SPECTATE[class=PacketPlayInSpectate, id=45], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Negativity, sending=ListeningWhitelist[priority=LOWEST, packets=[MAP[class=PacketPlayOutMap, id=37], LOGIN[class=PacketPlayOutLogin, id=36], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], OPEN_WINDOW_MERCHANT[class=PacketPlayOutOpenWindowMerchant, id=38], WORLD_EVENT[class=PacketPlayOutWorldEvent, id=33], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], LIGHT_UPDATE[class=PacketPlayOutLightUpdate, id=35], WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=34], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=45], OPEN_BOOK[class=PacketPlayOutOpenBook, id=44], AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=47], OPEN_SIGN_EDITOR[class=PacketPlayOutOpenSignEditor, id=46], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], VEHICLE_MOVE[class=PacketPlayOutVehicleMove, id=43], ENTITY[class=PacketPlayOutEntity, id=42], RECIPES[class=PacketPlayOutRecipes, id=53], POSITION[class=PacketPlayOutPosition, id=52], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55], ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=54], COMBAT_EVENT[class=PacketPlayOutCombatEvent, id=49], ABILITIES[class=PacketPlayOutAbilities, id=48], LOOK_AT[class=PacketPlayOutLookAt, id=51], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50], WORLD_BORDER[class=PacketPlayOutWorldBorder, id=61], SELECT_ADVANCEMENT_TAB[class=PacketPlayOutSelectAdvancementTab, id=60], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=63], CAMERA[class=PacketPlayOutCamera, id=62], RESPAWN[class=PacketPlayOutRespawn, id=57], RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=56], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ANIMATION[class=PacketPlayOutAnimation, id=5], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], BLOCK_BREAK[class=PacketPlayOutBlockBreak, id=7], STATISTIC[class=PacketPlayOutStatistic, id=6], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=3], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SERVER_DIFFICULTY[class=PacketPlayOutServerDifficulty, id=13], BOSS[class=PacketPlayOutBoss, id=12], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=15], CHAT[class=PacketPlayOutChat, id=14], TILE_ENTITY_DATA[class=PacketPlayOutTileEntityData, id=9], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=8], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_ACTION[class=PacketPlayOutBlockAction, id=10], SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_DATA[class=PacketPlayOutWindowData, id=20], CUSTOM_PAYLOAD[class=PacketPlayOutCustomPayload, id=23], SET_COOLDOWN[class=PacketPlayOutSetCooldown, id=22], TRANSACTION[class=PacketPlayOutTransaction, id=17], COMMANDS[class=PacketPlayOutCommands, id=16], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=18], GAME_STATE_CHANGE[class=PacketPlayOutGameStateChange, id=29], UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], OPEN_WINDOW_HORSE[class=PacketPlayOutOpenWindowHorse, id=30], KICK_DISCONNECT[class=PacketPlayOutKickDisconnect, id=25], CUSTOM_SOUND_EFFECT[class=PacketPlayOutCustomSoundEffect, id=24], EXPLOSION[class=PacketPlayOutExplosion, id=27], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], VIEW_DISTANCE[class=PacketPlayOutViewDistance, id=65], VIEW_CENTRE[class=PacketPlayOutViewCentre, id=64], SCOREBOARD_DISPLAY_OBJECTIVE[class=PacketPlayOutScoreboardDisplayObjective, id=67], SPAWN_POSITION[class=PacketPlayOutSpawnPosition, id=66], SCOREBOARD_SCORE[class=PacketPlayOutScoreboardScore, id=77], SCOREBOARD_TEAM[class=PacketPlayOutScoreboardTeam, id=76], TITLE[class=PacketPlayOutTitle, id=79], UPDATE_TIME[class=PacketPlayOutUpdateTime, id=78], UPDATE_HEALTH[class=PacketPlayOutUpdateHealth, id=73], EXPERIENCE[class=PacketPlayOutExperience, id=72], MOUNT[class=PacketPlayOutMount, id=75], SCOREBOARD_OBJECTIVE[class=PacketPlayOutScoreboardObjective, id=74], COLLECT[class=PacketPlayOutCollect, id=85], NBT_QUERY[class=PacketPlayOutNBTQuery, id=84], ADVANCEMENTS[class=PacketPlayOutAdvancements, id=87], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_SOUND[class=PacketPlayOutEntitySound, id=80], PLAYER_LIST_HEADER_FOOTER[class=PacketPlayOutPlayerListHeaderFooter, id=83], STOP_SOUND[class=PacketPlayOutStopSound, id=82], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], TAGS[class=PacketPlayOutTags, id=91], RECIPE_UPDATE[class=PacketPlayOutRecipeUpdate, id=90]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@a3b9fde
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@319055e7
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@30182d8c
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a02ad52
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b483, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@2c9118a3
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-337,minecraftVersion=1.16.4}
  library=ProtocolLib v4.6.0-SNAPSHOT-b483
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1f9d5fbb
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=2
  phasePlayingCount=5
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@50fa9a34
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7de3099f
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.16.4)
  debug=false
]

Listeners:
dev.jaqobb.messageeditor.listener.MessageEditorPacketListener@7d24e3f2[
  plugin=MessageEditor v2.0.1
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[SCOREBOARD_SCORE[class=PacketPlayOutScoreboardScore, id=77], DISCONNECT[class=PacketLoginOutDisconnect, id=0], BOSS[class=PacketPlayOutBoss, id=12], CHAT[class=PacketPlayOutChat, id=14], KICK_DISCONNECT[class=PacketPlayOutKickDisconnect, id=25], SCOREBOARD_OBJECTIVE[class=PacketPlayOutScoreboardObjective, id=74]], gamephase=PLAYING, options=[]]
]
com.bencodez.votingplugin.advancedcore.api.valuerequest.sign.SignMenu$1@22d35beb[
  plugin=VotingPlugin v6.0.3
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.elikill58.negativity.spigot.packets.protocollib.ProtocollibPacketManager$1@59bcfcd5[
  plugin=Negativity v1.9.6
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[PING[class=PacketStatusInPing, id=1], START[class=PacketStatusInStart, id=0], START[class=PacketLoginInStart, id=0], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], CHAT[class=PacketPlayInChat, id=3], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=15], USE_ENTITY[class=PacketPlayInUseEntity, id=14], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=17], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=11], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=13], B_EDIT[class=PacketPlayInBEdit, id=12], TRANSACTION[class=PacketPlayInTransaction, id=7], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=8], TR_SEL[class=PacketPlayInTrSel, id=35], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], BEACON[class=PacketPlayInBeacon, id=36], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ITEM_NAME[class=PacketPlayInItemName, id=32], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BOAT_MOVE[class=PacketPlayInBoatMove, id=23], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=25], PICK_ITEM[class=PacketPlayInPickItem, id=24], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], STRUCT[class=PacketPlayInStruct, id=42], SPECTATE[class=PacketPlayInSpectate, id=45], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.elikill58.negativity.spigot.packets.protocollib.ProtocollibPacketManager$2@20b85bc2[
  plugin=Negativity v1.9.6
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[MAP[class=PacketPlayOutMap, id=37], LOGIN[class=PacketPlayOutLogin, id=36], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], OPEN_WINDOW_MERCHANT[class=PacketPlayOutOpenWindowMerchant, id=38], WORLD_EVENT[class=PacketPlayOutWorldEvent, id=33], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], LIGHT_UPDATE[class=PacketPlayOutLightUpdate, id=35], WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=34], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=45], OPEN_BOOK[class=PacketPlayOutOpenBook, id=44], AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=47], OPEN_SIGN_EDITOR[class=PacketPlayOutOpenSignEditor, id=46], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], VEHICLE_MOVE[class=PacketPlayOutVehicleMove, id=43], ENTITY[class=PacketPlayOutEntity, id=42], RECIPES[class=PacketPlayOutRecipes, id=53], POSITION[class=PacketPlayOutPosition, id=52], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55], ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=54], COMBAT_EVENT[class=PacketPlayOutCombatEvent, id=49], ABILITIES[class=PacketPlayOutAbilities, id=48], LOOK_AT[class=PacketPlayOutLookAt, id=51], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50], WORLD_BORDER[class=PacketPlayOutWorldBorder, id=61], SELECT_ADVANCEMENT_TAB[class=PacketPlayOutSelectAdvancementTab, id=60], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=63], CAMERA[class=PacketPlayOutCamera, id=62], RESPAWN[class=PacketPlayOutRespawn, id=57], RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=56], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ANIMATION[class=PacketPlayOutAnimation, id=5], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], BLOCK_BREAK[class=PacketPlayOutBlockBreak, id=7], STATISTIC[class=PacketPlayOutStatistic, id=6], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=3], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SERVER_DIFFICULTY[class=PacketPlayOutServerDifficulty, id=13], BOSS[class=PacketPlayOutBoss, id=12], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=15], CHAT[class=PacketPlayOutChat, id=14], TILE_ENTITY_DATA[class=PacketPlayOutTileEntityData, id=9], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=8], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_ACTION[class=PacketPlayOutBlockAction, id=10], SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_DATA[class=PacketPlayOutWindowData, id=20], CUSTOM_PAYLOAD[class=PacketPlayOutCustomPayload, id=23], SET_COOLDOWN[class=PacketPlayOutSetCooldown, id=22], TRANSACTION[class=PacketPlayOutTransaction, id=17], COMMANDS[class=PacketPlayOutCommands, id=16], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=18], GAME_STATE_CHANGE[class=PacketPlayOutGameStateChange, id=29], UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], OPEN_WINDOW_HORSE[class=PacketPlayOutOpenWindowHorse, id=30], KICK_DISCONNECT[class=PacketPlayOutKickDisconnect, id=25], CUSTOM_SOUND_EFFECT[class=PacketPlayOutCustomSoundEffect, id=24], EXPLOSION[class=PacketPlayOutExplosion, id=27], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], VIEW_DISTANCE[class=PacketPlayOutViewDistance, id=65], VIEW_CENTRE[class=PacketPlayOutViewCentre, id=64], SCOREBOARD_DISPLAY_OBJECTIVE[class=PacketPlayOutScoreboardDisplayObjective, id=67], SPAWN_POSITION[class=PacketPlayOutSpawnPosition, id=66], SCOREBOARD_SCORE[class=PacketPlayOutScoreboardScore, id=77], SCOREBOARD_TEAM[class=PacketPlayOutScoreboardTeam, id=76], TITLE[class=PacketPlayOutTitle, id=79], UPDATE_TIME[class=PacketPlayOutUpdateTime, id=78], UPDATE_HEALTH[class=PacketPlayOutUpdateHealth, id=73], EXPERIENCE[class=PacketPlayOutExperience, id=72], MOUNT[class=PacketPlayOutMount, id=75], SCOREBOARD_OBJECTIVE[class=PacketPlayOutScoreboardObjective, id=74], COLLECT[class=PacketPlayOutCollect, id=85], NBT_QUERY[class=PacketPlayOutNBTQuery, id=84], ADVANCEMENTS[class=PacketPlayOutAdvancements, id=87], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_SOUND[class=PacketPlayOutEntitySound, id=80], PLAYER_LIST_HEADER_FOOTER[class=PacketPlayOutPlayerListHeaderFooter, id=83], STOP_SOUND[class=PacketPlayOutStopSound, id=82], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], TAGS[class=PacketPlayOutTags, id=91], RECIPE_UPDATE[class=PacketPlayOutRecipeUpdate, id=90]], gamephase=PLAYING, options=[]]
]
me.dniym.listeners.pLisbListener$2@1ce00c9b[
  plugin=IllegalStack v2.2.0e
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
MessageEditor by [jaqobb]
VotingPlugin by [BenCodez]
IllegalStack by [dNiym]
Negativity by [[Elikill58, RedNesto]]

**Additional context**

**Comment by dmulloy2** [comment]
Are you sure it's ProtocolLib?

**Comment by XragonX147** [comment]
Yes 100%. I removed every Plugin and it only Stops when I remove ProtocolLib.

**Comment by XragonX147** [comment]
Sorry I miss checked...
... Another Plugin isn't compatible.
Wither Anti Cheat was the Problem, the issue is closed.
