### ISSUE TITLE
equipment packet have an error with .getPacket()

### ISSUE THREAD

**Issue by Anarchick** [dmulloy2/ProtocolLib#1039]
**Describe the bug**
Get this error when I use on the equipment packet and not others : `packetEvent.getPacket()`
http://pastebin.fr/78722
but I can use `packetEvent.getPacket().toString()` or `packetEvent.getPacket().getClass() // return PacketContainer`

**To Reproduce**
using skript + java + reflection. You can't reproduce with the same method as me.

**Expected behavior**
not throwing an error on console like other packets

**Version Info**
ProtocolLib - build 383

**Comment by dmulloy2** [comment]
Can you provide some code? If not this might be an issue with Skript
