### ISSUE TITLE
Holographic Extension

### ISSUE THREAD

**Issue by arttwart** [dmulloy2/ProtocolLib#1040]
Hello, when I use the Hologhraphic Extension plugin, my server is crashing.
I'm using Paper 1.16.4 and the latest versions of both. Also I'm using latest version of Protocol Lib too. I reported the crash bug to Holographic Extension's developer, and he had a brief look to the error. And he said " This is ProtocolLib error I believe". Then I wanted to report this issue to you.

Error: https://srcb.in/3r9dKeN9tA

**Steps to reproduce the behavior:**
1. Download and install ProtocolLib, HolographicExtensions and Paper 1.16.4
2. Start the server
3. Type /holo create abc abc

**Expected behavior**
Sorry, I don't know what is that means.

**Version Info**
Latest version, build #483

**Comment by arttwart** [comment]
Also you need to download HolographicDisplays too. If you won't, HolographicExtension is useless. You cannot do anything.

**Comment by dmulloy2** [comment]
Give the latest dev build a try. This looks like an issue we just fixed

**Comment by arttwart** [comment]
It is working, thank you so much!
