### ISSUE TITLE
Plugin crashes with Java 15

### ISSUE THREAD

**Issue by Halflove1** [dmulloy2/ProtocolLib#1043]
**Describe the bug**
Upgraded from java 8 to java 15 and my server would crash every time I loaded in or created a hologram using HolographicDisplays, did some reading, and noticed it was an issue with ProtocolLib according to the crash report. I then downgraded from java 15 to java 11 and everything works fine again.

**To Reproduce**
1. Run your server on java 15
2. Load a hologram in a chunk
3. Server crashes

**Expected behavior**
Well... I wasn't really expecting the server to crash...

**Screenshots**
I don't really think screenshots apply here, but here is the crash report: https://pastebin.com/rHuxVvKE

**Version Info**
Here's my protocol dump: https://pastebin.com/bSfeNt0M
FYI, this dump was after I downgraded back to java 11

**Additional context**
N/A

**Comment by dmulloy2** [comment]
Fixed in the latest dev build
