### ISSUE TITLE
For all repository issues

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#1047]
My self-hosted repo (repo.dmulloy2.net) has had some issues in the past. I've rehosted it in a (hopefully) more stable way but if for whatever reason it's unavailable, you can use Jitpack as a backup.

Maven: 

````xml
<repositories>
  <repository>
    <id>jitpack</id>
    <url>https://jitpack.io/</url>
  </repository>
  ...
</repositories>

<dependencies>
  <dependency>
    <groupId>com.github.dmulloy2</groupId>
    <artifactId>ProtocolLib</artifactId>
    <version>4.6.0</version>
  </dependency>
  ...
</dependencies>
````

Gradle:

```gradle
repositories {
    maven { url "https://jitpack.io/" }
}

dependencies {
    compileOnly group: "com.github.dmulloy2", name: "ProtocolLib", version: "4.6.0";
}
```

You can also use `master-SNAPSHOT` as your dependency version to get the latest builds, but YMMV as far as how stable that will be

**Comment by Xierip** [comment]
Gradle when use jitpack.io

`Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.comphenix.executors:BukkitExecutors:1.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/patry/.m2/repository/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/patry/.m2/repository/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - file:/C:/Users/patry/.m2/repository/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
       - https://repo.destroystokyo.com/repository/maven-public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - https://repo.destroystokyo.com/repository/maven-public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - https://repo.destroystokyo.com/repository/maven-public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
       - http://nexus.hc.to/content/repositories/pub_releases/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - http://nexus.hc.to/content/repositories/pub_releases/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - http://nexus.hc.to/content/repositories/pub_releases/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
       - https://oss.sonatype.org/content/repositories/snapshots/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
       - https://jitpack.io/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.pom
       - https://jitpack.io/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-SNAPSHOT.jar
     Required by:
         project : > com.github.dmulloy2:ProtocolLib:4.5.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`
