### ISSUE TITLE
1.16.4 PacketPlayOutRecipes field not found

### ISSUE THREAD

**Issue by DevJoey** [dmulloy2/ProtocolLib#1049]
**Describe the bug**

In The packet class there are that fields 

private Action a;
  
private List<MinecraftKey> b;
  
private List<MinecraftKey> c;
  
private RecipeBookSettings d;

but if in try this using plib using this code https://pastebin.com/YsYBZdmw it says no fields exists with minecraftkey

Stacktrace https://pastebin.com/H7vGNrtb

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by dmulloy2** [comment]
None of those fields seems to be a minecraft key
