### ISSUE TITLE
'An illegal reflective access operation has occurred' error.

### ISSUE THREAD

**Issue by CroaBeast** [dmulloy2/ProtocolLib#1050]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [Yes] You're using the latest build for your server version
- [Tecnically Yes] This isn't an issue caused by another plugin
- [Yes] You've checked for duplicate issues
- [Yes] You didn't use `/reload`

Debug paste link:
https://pastebin.com/9RiwTr7B

Description and relevant errors:
When I try to join my server using ProtocolLib, this warning shows up and I can't enter to the server.
I tried to use the last version of ProtocolLib in Spigot and the last dev build, but I cannot fix that.
What can I do?
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/C:/Users/Master/Desktop/Neccesary%20Files/1.16.4%20server/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by dmulloy2** [comment]
Should be safe to ignore for now. We're working on a fix for the future though
