### ISSUE TITLE
Strange console message

### ISSUE THREAD

**Issue by ToxicPeople** [dmulloy2/ProtocolLib#1052]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Debug paste link: https://pastebin.com/QhFXwkM2

Strange console message:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/home/Network/Survival/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Description and relevant errors:

Hello, good evening, I hope you are well, I wanted to comment that my console is indicating the following message and I do not know why. It would be of great help if you could guide me to solve it in case it is an error. I currently have 2 plugins, ProtocolLib and TCPShield. Beforehand thank you very much

**Comment by dmulloy2** [comment]
Should be safe to ignore for now. We're working on a fix for the future though
