### ISSUE TITLE
Incompatibility with HolographicDisplays

### ISSUE THREAD

**Issue by LucidAPs** [dmulloy2/ProtocolLib#1053]
HolographicDisplays #1​62
Protocolib #4​91
Minecraft 1.16.4 Tuinity
https://mcpaste.io/a6f4d1552a5bb8a4

**Comment by PimvanderLoos** [comment]
As of #984, ProtocolLib replaced CGLib with ByteBuddy.

HolographicDisplays uses the (as of now) [old](https://github.com/filoghost/HolographicDisplays/blob/af038ac93f7a0d5c1d5a7abfa4a08176b9765d16/Plugin/src/main/java/com/gmail/filoghost/holographicdisplays/bridge/protocollib/current/ProtocolLibHookImpl.java#L87) method of checking if a player is from a generated class, which should be updated to [this](https://github.com/PimvanderLoos/ProtocolLib/blob/25383e711ecc741f01eb86a617d7078631686f3a/src/main/java/com/comphenix/protocol/injector/netty/ChannelInjector.java#L695). So `player instanceof Factory` should now be `player instanceof ByteBuddyGenerated`.
