### ISSUE TITLE
Cannot add packet listener

### ISSUE THREAD

**Issue by PatrickMSM** [dmulloy2/ProtocolLib#1056]
Can not add packet listener for Play.Server.MAP_CHUNK with highest priority.

Create a plugin and try to add a packet listener as described above.

**Expected behavior**
The listener is added and the packet is cancelled.

**Screenshots**
![image](https://user-images.githubusercontent.com/45915226/103698874-b125a100-4faa-11eb-816d-fb1aee1230fa.png)

**Version Info**
[dump-2021-01-05_23.13.15.txt](https://github.com/dmulloy2/ProtocolLib/files/5772630/dump-2021-01-05_23.13.15.txt)

**Comment by TheLimeGlass** [comment]
Present in 4.6.0 still
