### ISSUE TITLE
Can't get ProtocolLib to install on bungeecord.

### ISSUE THREAD

**Issue by Zacymacy** [dmulloy2/ProtocolLib#1060]
I'm having trouble installing ProtocolLib on my 1.16.4 bungeecord server. I have used the latest dev build recommended for 1.16 and also tried the latest release build and neither have worked. I get this error in my logs on startup https://pastebin.com/9gwDbKYX

**Comment by dmulloy2** [comment]
ProtocolLib is a Bukit plugin, not a Bungee plugin. Put it on the individual servers you need it on
