### ISSUE TITLE
Holograms plugin error to protocollib

### ISSUE THREAD

**Issue by supermem99** [dmulloy2/ProtocolLib#1064]
**Describe the bug**
I updated to the latest version and this was sent to me.
I get this on join 

**Screenshots**
[click](https://pastebin.com/XvSmQxnM)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
[click](https://pastebin.com/LnWe6LMg)

**Additional context**
i use paper 1.16.4 latest

**Comment by PimvanderLoos** [comment]
Duplicate of #1053
Duplicate of #1055
Duplicate of #1062

Fixed by Holographic Displays in their [build 163](https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/).
