### ISSUE TITLE
A weird error spamming the console 

### ISSUE THREAD

**Issue by JustJP2K** [dmulloy2/ProtocolLib#1068]
Error thats spamming the console:
No idea what it is
https://pastebin.com/LvSEujWw
Protocol Lib dump:
https://pastebin.com/XYLskvHA

**Comment by dmulloy2** [comment]
Sounds like one of your plugins (my guess is HoloMobHealth) is sending metadata for non-existent entities

**Comment by JustJP2K** [comment]
ok thx
