### ISSUE TITLE
"Illegal reflective access" error in console

### ISSUE THREAD

**Issue by brobie1kanobi** [dmulloy2/ProtocolLib#1069]
**Describe the bug**
Error in console saying to report this bug

**To Reproduce**
1. Use latest build of everything (server, bungee, protocol lib, etc)
2. Start server

**Expected behavior**
Server starts without errors.

**Version Info**
https://pastebin.com/AK5HqvfV

**Additional context**
This is the error I get in console:

>....WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/home/container/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by PimvanderLoos** [comment]
This warning was removed in build 491. So just [update ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) and it'll go away.

**Comment by brobie1kanobi** [comment]
I realized that just now, thought I was on the most recent build. Marking closed. Thanks!
