### ISSUE TITLE
Error with libs diguises

### ISSUE THREAD

**Issue by PhanaticD** [dmulloy2/ProtocolLib#107]
I am getting this error: http://pastebin.com/bhpFKZSd

this is with build 191

**Comment by PhanaticD** [comment]
this is with hunger games: http://pastebin.com/rTqLKY9u

**Comment by dmulloy2** [comment]
Try 190, I think this is a problem with backwards compatibility

**Comment by PhanaticD** [comment]
same error

**Comment by PhanaticD** [comment]
it was a problem with the custom spigot jar I was using, sorry

**Comment by Techcable** [comment]
Sorry about this, I added a configuration option to make the DataWatcher non blocking, but when the option is true, the lock is set to null. This messes with your stuff :cry:
