### ISSUE TITLE
1.16.4 Player Join Error

### ISSUE THREAD

**Issue by Favorlock** [dmulloy2/ProtocolLib#1070]
**Describe the bug**
The first time a player joins the server an IllegalArgumentException error is thrown.

**To Reproduce**
1. Start server and join as player

**Expected behavior**
I expect no error to be thrown.

**Version Info**
https://pastebin.com/wus2Vb7t

**Additional context**
https://pastebin.com/qppKCPWn

**Comment by dmulloy2** [comment]
Can you share the error?

**Comment by Favorlock** [comment]
> Can you share the error?

I already included that in the second pastebin link under additional context.
