### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xipsaaahoy** [dmulloy2/ProtocolLib#1071]
**Describe the bug**
It happers randomly and everytime I join my server!

**To Reproduce**
1. Join the server or wait.
**Expected behavior**
Not show bugs
**Screenshots**

**Version Info**
https://pastebin.com/AW8kq89G

**Additional context**
![imagem](https://user-images.githubusercontent.com/74424349/105468552-03471180-5c8f-11eb-8eb7-b65e48c96f67.png)

**Comment by PimvanderLoos** [comment]
Duplicate of #1053
Duplicate of #1055
Duplicate of #1062
Duplicate of #1064

Fixed by Holographic Displays in their [build 163](https://ci.codemc.io/job/filoghost/job/HolographicDisplays/163/).
