### ISSUE TITLE
FATAL ERROR: Internal Server Error

### ISSUE THREAD

**Issue by DaZeNuk3r** [dmulloy2/ProtocolLib#1074]
**Describe the bug**
Unable to connect to server: Internal Server error

**To Reproduce**
1. Install ProtocolLib
2. Start server
3. connect to server

**Expected behavior**
A clear connection to the server

**Screenshots**
![Screenshot_17](https://user-images.githubusercontent.com/63490802/106154678-d93d9580-614d-11eb-9e46-3afc8f10fb46.png)

**Version Info**
[dump-2021-01-28_09.46.23.txt](https://github.com/dmulloy2/ProtocolLib/files/5888086/dump-2021-01-28_09.46.23.txt)

**Additional context**

Spigot Latest build

![image](https://user-images.githubusercontent.com/63490802/106155029-39ccd280-614e-11eb-84e0-9b098780e4ec.png)

**Comment by dmulloy2** [comment]
Try updating to the latest dev build: https://ci.dmulloy2.net/job/ProtocolLib/
