### ISSUE TITLE
I Have No Idea

### ISSUE THREAD

**Issue by arttwart** [dmulloy2/ProtocolLib#1079]
**Describe the bug**
I am using Debian GNU/Linux 10 (Buster) for my server. When I connected my Paper 1.8.8 #443 server to Waterfall 1.16 #391 proxy server, server started to kicking me. It kicks me every 15 seconds.

**To Reproduce**
1. Use Debian GNU/Linux 10 (Buster)
2. Install 'Waterfall proxy server'
3. Install 'Paper 1.8.8 server'
4. Connect them to each other
5. Disable "use-native-transport" in server.properties (Paper 1.8.8 does not support Java 15, thus I had to disable it.)
6. Disable "disable_tab_list_rewrite" and "disable_entity_metadata_rewrite" in waterfall.yml
6. Install ProtocolLib #493 or 4.5.1 (Recommended version for 1.8)
7. Connect to the server and try to walk or fly for one minute
8. Get kicked

**Expected behavior**
It shouldn't kick me.

**Version Info**
https://srcb.in/dxAbjH61Vf

**Additional context**
It don't kick me in Paper 1.16 but I need Paper 1.8.8 for some servers.

I made research about that situation. A person said "Disable 'disable_tab_list_rewrite' and 'disable_entity_metadata_rewrite' in waterfall.yml", then I tried it. But it didn't fix my problem.

Then I deleted the ProtocolLib #483 (dev build) and it stopped kicking me. Thus problem is solved. But I need ProtocolLib for lots of my plugins. They need it. I tried ProtocolLib 4.5.1 and ProtocolLib #493 but they are still not working.

There are the error logs when I get kicked:
Waterfall: https://srcb.in/wOBJePbw5O
Paper: https://srcb.in/cKZQheozJN

I am really not sure if it is not about ProtocolLib, but when I delete it, problem is solving.

**Comment by dmulloy2** [comment]
What error are you kicked with?

**Comment by arttwart** [comment]
There are the CONSOLE error logs when I get kicked:
Waterfall: https://srcb.in/wOBJePbw5O
Paper: https://srcb.in/cKZQheozJN

Unfortunately I am not in my home. I couldn't remember which error did I get in Minecraft screen when I kicked without closing Netty options...

But I found this one, this is in Minecraft kick message and this happens when I use Java 8 directory with Netty options enabled: io.netty.channel.AbstractChannel$AnnotatedConnectException

This is not about IP addresses, everything was normal but it broked when I change Java directory.

I'll go to home 24~ hours later, I'll send the other error in screen when I go. Sorry so much.

Also, I would be happy if anything happened, can you tell me anything about situation? Can you inform me please sir?

**Comment by arttwart** [comment]
This is the Minecraft screen one: https://prnt.sc/yafg0q
And this one is proxy (Waterfall) error: https://srcb.in/BpWTY8wse6
This one is normal (Paper) server error: https://srcb.in/cfSuNqfJYX

The one when I close Netty options and using ProtocolLib.
I just noticed now, I already sent every error to you.

**Comment by arttwart** [comment]
Why did you close this? Without no response?
