### ISSUE TITLE
IndexOutOfBoundsExeption on join

### ISSUE THREAD

**Issue by Immercooler** [dmulloy2/ProtocolLib#1080]
**Describe the bug**
Basically, when i try to join the server with protocollib, it kicks me for this error: 
https://user-images.githubusercontent.com/78306220/106385428-8b848f80-63d0-11eb-9937-1d2f1b85fcae.jpeg

**To Reproduce**
Basically load it on a spigot 1.8.8 on a bungeecord server and then join a 1.8.8 subserver that has protocollib latest on it

**Expected behavior**
I want it to work without kicking me

**Screenshots**
https://user-images.githubusercontent.com/78306220/106385428-8b848f80-63d0-11eb-9937-1d2f1b85fcae.jpeg

**Version Info**
https://pastebin.com/r3FcXzfc

**Additional context**
Hope you can fix it <3.

**Comment by dmulloy2** [comment]
One of your plugins (either Reflex or AdvancedGUI) is sending/modifying a bad packet
