### ISSUE TITLE
ci server down

### ISSUE THREAD

**Issue by seokle1** [dmulloy2/ProtocolLib#1084]
**Describe the bug**

cant download the latest dev build

**To Reproduce**
1. Go to 'https://ci.dmulloy2.net/job/ProtocolLib'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78600594/107037063-e74e7e80-67fd-11eb-87b9-631c886a6daf.png)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by EliteAspect21** [comment]
Still down

**Comment by Kqmu** [comment]
Still Down

**Comment by Ashesh3** [comment]
Hey, I had this similar issue and it seems we can use jitpack to download the snapshot version,

Here: https://jitpack.io/com/github/dmulloy2/ProtocolLib/master-SNAPSHOT

For latest snapshot as of today: https://javadoc.jitpack.io/com/github/dmulloy2/ProtocolLib/master-1.5.0-g765fd9e-1236/ProtocolLib-master-1.5.0-g765fd9e-1236.jar

If this helps.

**Comment by JasonHorkles** [comment]
CI appears to be back up now
