### ISSUE TITLE
Protocollib 4.6.0 Site Down

### ISSUE THREAD

**Issue by Kqmu** [dmulloy2/ProtocolLib#1086]
Sorry to Be a bother, But I run a 1.16.4 Java Minecraft Server and our server needs Protocollib 4.6.0 but the only website to get it from is currently down, was wondering if you can look into it,, or link a way to actually download it easier. :/ Thank you, and have a great night! 

Site => https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
Error Message =>
![image](https://user-images.githubusercontent.com/70139586/107109394-166cec00-680e-11eb-942a-485322e4b0b6.png)

**Comment by Ashesh3** [comment]
Hey, I had this similar issue and it seems we can use jitpack to download the snapshot version,

Here: https://jitpack.io/com/github/dmulloy2/ProtocolLib/master-SNAPSHOT

For latest snapshot as of today: https://javadoc.jitpack.io/com/github/dmulloy2/ProtocolLib/master-1.5.0-g765fd9e-1236/ProtocolLib-master-1.5.0-g765fd9e-1236.jar

**Comment by mamytema** [comment]
> Hey, I had this similar issue and it seems we can use jitpack to download the snapshot version,
> 
> Here: https://jitpack.io/com/github/dmulloy2/ProtocolLib/master-SNAPSHOT
> 
> For latest snapshot as of today: https://javadoc.jitpack.io/com/github/dmulloy2/ProtocolLib/master-1.5.0-g765fd9e-1236/ProtocolLib-master-1.5.0-g765fd9e-1236.jar

The link doesnt seem to work, you can get the same version of it from spigot but we need 4.6.0

**Comment by Ashesh3** [comment]
> > Hey, I had this similar issue and it seems we can use jitpack to download the snapshot version,
> > Here: https://jitpack.io/com/github/dmulloy2/ProtocolLib/master-SNAPSHOT
> > For latest snapshot as of today: https://javadoc.jitpack.io/com/github/dmulloy2/ProtocolLib/master-1.5.0-g765fd9e-1236/ProtocolLib-master-1.5.0-g765fd9e-1236.jar
> 
> The link doesnt seem to work, you can get the same version of it from spigot but we need 4.6.0

Hey, not sure but those link seem to work fine here, and i get `v4.6.0-SNAPSHOT` from the second URL i mentioned. Maybe the URLs are not working on your end?

![image](https://user-images.githubusercontent.com/3626859/107117638-bb84d480-68a1-11eb-9021-18c8d2a603f9.png)
![image](https://user-images.githubusercontent.com/3626859/107117642-c0498880-68a1-11eb-9271-bf14093e5fcc.png)

**Comment by mamytema** [comment]
> > > Hey, I had this similar issue and it seems we can use jitpack to download the snapshot version,
> > > Here: https://jitpack.io/com/github/dmulloy2/ProtocolLib/master-SNAPSHOT
> > > For latest snapshot as of today: https://javadoc.jitpack.io/com/github/dmulloy2/ProtocolLib/master-1.5.0-g765fd9e-1236/ProtocolLib-master-1.5.0-g765fd9e-1236.jar
> > 
> > 
> > The link doesnt seem to work, you can get the same version of it from spigot but we need 4.6.0
> 
> Hey, not sure but those link seem to work fine here, and i get `v4.6.0-SNAPSHOT` from the second URL i mentioned. Maybe the URLs are not working on your end?
> 
> ![image](https://user-images.githubusercontent.com/3626859/107117638-bb84d480-68a1-11eb-9021-18c8d2a603f9.png)
> ![image](https://user-images.githubusercontent.com/3626859/107117642-c0498880-68a1-11eb-9271-bf14093e5fcc.png)

Alright i got a bit confused. All seems working now! Thanks 😄

**Comment by hetile1** [comment]
+1

The linked site is currently down
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by dmulloy2** [comment]
Working on recreating it now.  For now downloading from Jitpack is the recommended way.

**Comment by dmulloy2** [comment]
Hi all, the CI server is back up and running. Still working on the repository, but Jitpack should be preferred for maven anyways
