### ISSUE TITLE
Random error after restart (java.lang.LinkageError)

### ISSUE THREAD

**Issue by kunpapa** [dmulloy2/ProtocolLib#109]
Hi,

Im using latest update from ProtocolLib (http://ci.shadowvolt.com/job/ProtocolLib/191/), with latest version of Spigot (Compiled yesterday 14/08). At random restarts, players get disconnected with this error:

- http://pastebin.com/7D3ugTPJ

I have LibsDisguises (latest version) and AntiAura(latest version). Its a bug? Or its a problem?

Thanks.

Regards.

**Comment by dmulloy2** [comment]
Does this happen when you replace the ProtocolLib jar and use /reload?

**Comment by kunpapa** [comment]
Nope, I never use /reload. It happens at first connected, then for everyone.

**Comment by dmulloy2** [comment]
Try build 193: http://ci.shadowvolt.com/job/ProtocolLib/193/

Sometimes errors like this are caused by weird building quirks.

**Comment by dmulloy2** [comment]
Is this still an issue?

**Comment by kunpapa** [comment]
Hi,

Its something between 2 plugins (AntiAura and LibDisguises) that use protocollib, I made a "temp-fix" if it fails link the library, the server restart automatically. I updated 2 days ago to latest PLib version and it still happening.

Ty anyway.

**Comment by dmulloy2** [comment]
Pinging @NavidK0 and @joehot200, hopefully we can figure something out.

**Comment by NavidK0** [comment]
I'm not quite sure what it would be, Linkage Errors are annoying to deal with. I do believe LibsDisguises goes off of 3.6.5, so maybe try using the latest dev build?

**Comment by themazim** [comment]
Had to deal with the same error for quite a while now. I don't think it's necessarily linked with libsdisguises or antiaura. 

The exception also occurs without libsdisguises / antiaura. Mainly when sending lots of packets through protocollib (in my case, custom scoreboard) and very randomly. Less than 1% of the servers have this bug after restart (~500 server restarts a day)

I haven't tried the newest protocollib version yet (23.10.2015). Will give some feedback after checking.

**Comment by themazim** [comment]
Newest Build (#201) has the issues too.

Users are disconnected with reason:

Username lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer

exception:

http://pastebin.com/khkx5qbK

**Comment by dmulloy2** [comment]
I haven't been able to reproduce this, but I added some debug info in the last commit. If anyone could set ````debug: true```` and provide the info, that would be great.

**Comment by themazim** [comment]
Going to debug today with newest build (#204)

**Comment by themazim** [comment]
Here is the error:

http://pastebin.com/raw.php?i=njdupneR

Hope this helps.

**Comment by dmulloy2** [comment]
@themazim How are you getting the error? I'd like to reproduce this on my end, it's much easier to fix it that way.

**Comment by themazim** [comment]
I can't really tell. It's happening very randomly. Maybe 1 out of 100 restarts. 

Here is a (stupid) guess:

try starting the server with a very high nice level (nice -n 10 or sth like that) while running prime / sysbench cpu on all cores with normal nice level.

I honestly have no idea what's causing the error.

**Comment by JhoniSilva** [comment]
I'm having the same issue. Someone found a solution?

**Comment by dmulloy2** [comment]
@JhoniSilva I haven't had any success reproducing it on my end. If I could reproduce it, it would be significantly easier to fix. How are you getting the error?

**Comment by JhoniSilva** [comment]
@dmulloy2 I have some Hardcore games rooms(20) that restart automatically after game finish.
This bug occurs very randomly. When a server start, all the peoples who try to join, gets "Internal Error"(Consol show the protocollib error), and the error persist until I manually restart  the server.

**Comment by dmulloy2** [comment]
@JhoniSilva Nothing is truly random (even java.util.Random isn't _really_ random). There has to be something that triggers it, a set of circumstances that causes it. What plugins do you have that use ProtocolLib?

**Comment by JhoniSilva** [comment]
@dmulloy2 I think I found the problem. I have checked all my plugins with no results.
I have 20 Hardcore Games rooms that runs with the same plugins folder. I tried to run one of these rooms with a own plugins folder and the error was gone(for now).

**Comment by dmulloy2** [comment]
@JhoniSilva That's pretty consistent with the causes of linkage errors. Let me know if the issue comes back, but this seems to be the solution.

**Comment by JhoniSilva** [comment]
@dmulloy2 Hey, after some hours, the problem was back. So, I have spend some time searching, and I discovered that the plugin NoCheatPlus use ProtocolLib to do some checks.  I just updated it and disabled the checks that use packets, and finally the error was gone.

**Comment by dmulloy2** [comment]
@JhoniSilva You should probably report this to @asofold, there's not much I can do on PL's end.

**Comment by asofold** [comment]
Maybe NCP is built vs. an older API, but not sending any extra packets, instead packets may be cancelled. Disabling listeners/adapters would lead to the packets not getting decoded at all?
