### ISSUE TITLE
Please just add the latest dev version to SpigotMC, I cannot use disguise in Aternos server because of this

### ISSUE THREAD

**Issue by WhiteDevil2006** [dmulloy2/ProtocolLib#1091]
**Is your feature request related to a problem? Please describe.**

Please just add the latest dev version to SpigotMC, I cannot use disguise in Aternos server because of this. It needs 4.60 and i have no way to upload the .jar file to aternos. Thank you so much for your support

**Comment by JasonHorkles** [comment]
Dev builds are called that for a reason; They're in development and may not be stable. Pushing a potentially unstable build to Spigot would be unwise. Just don't use a free host.
