### ISSUE TITLE
ProtocolLib can't create a folder

### ISSUE THREAD

**Issue by apelsin222** [dmulloy2/ProtocolLib#1096]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
I have downloaded the plugin ProtocolLib but the console just says: 
18.02 18:32:31 [Server] Server thread/ERROR Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'
18.02 18:32:31 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
18.02 18:32:31 [Server] INFO Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:199) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at com.comphenix.protocol.ProtocolLib.<init>(ProtocolLib.java:65) ~[?:?]
18.02 18:32:31 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO ... 7 more
18.02 18:32:31 [Server] INFO Caused by: java.lang.IllegalStateException: Initial initialization
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:202) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at unet.Holograms.Main.<init>(Main.java:27) ~[?:?]
18.02 18:32:31 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_211]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot_Latest.jar:3013-Spigot-73fb609-0cd8f19]
18.02 18:32:31 [Server] INFO ... 7 more

**API method(s) used**
List what API method(s) you're using
I do not know what that is.
**Expected behavior**
I expected the plugin to work like normal and just pop up when I write /plugins
**Code**
If applicable, add relevant code from your project

**Additional context**
I am using Placeholder-API too
And I am using ProtocolLib for Interactivechat

**Comment by ostinostin** [comment]
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Failed to find CraftBukkit class: entity.CraftPlayer
  	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getCraftBukkitClass$0(MinecraftReflection.java:2014)
  	at java.util.Optional.orElseThrow(Optional.java:290)
  	at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:2014)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEntityPlayerClass(MinecraftReflection.java:588)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1047)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:375)
  	at net.minecraft.class_3176.handler$zza000$init(class_3176.java:741)
  	at net.minecraft.class_3176.method_3823(class_3176.java:155)
  	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
  	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@23ae5905[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@b464ea1
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@35bdfc65
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@3a80f012
      server=CraftServer{serverName=CardboardPowered.org,serverVersion=git-Bukkit4Fabric-3cb2109,minecraftVersion=1.16.4}
      file=plugins\ProtocolLib (7).jar
      description=org.bukkit.plugin.PluginDescriptionFile@52bd98a7
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins\ProtocolLib (7).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.javazilla.bukkitfabric.BukkitLogger@35846934
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    1.8.0_281
  Server:
    git-Bukkit4Fabric-3cb2109 (MC: 1.16.4)

[18:57:52] [Server thread/INFO]: Enabling ProtocolLib v4.6.0
[18:57:52] [Server thread/INFO]: Disabling ProtocolLib v4.6.0

**Comment by dmulloy2** [comment]
Looks like two separate issues but @apelsin222 it looks like you have two versions of PL in your plugin folder.

@ostinostin We don't currently support `Bukkit4Fabric`
