### ISSUE TITLE
conflict protocollib and buycraft

### ISSUE THREAD

**Issue by ANRTV** [dmulloy2/ProtocolLib#110]
a few days ago installed protocolLib because a plugin used it to their dependence, but try to put /buy and give some package did not come out to me the message to buy the package, you could only if the user had access to all permits, look the video here, https://www.youtube.com/watch?v=H42W3kNPagg

**Comment by dmulloy2** [comment]
Are you sure this is an issue with ProtocolLib? There doesn't appear to be anything that would indicate that it is.

**Comment by ANRTV** [comment]
if it is protocolLib as removing the plugin folder server, the buycraft working properly to give chests everything works.

**Comment by ANRTV** [comment]
conflict repair thanks
