### ISSUE TITLE
[ProtocolLib] [Debug] Exception registering converter

### ISSUE THREAD

**Issue by MG141** [dmulloy2/ProtocolLib#1100]
**Describe the bug**
[ProtocolLib] [Debug] Exception registering converter

Whenever I join the "Play" server via "Lobby" server, I get disconnected from the "Play" server in few seconds. The console output is here: [https://pastebin.com/fGz6NXnY](https://pastebin.com/fGz6NXnY)

**To Reproduce**
1. Lunch bungeecord, lobby and play server (lobby and play server use ProtocolLib)
2. Join the server via bungeecord
3. Join the play server
4. Wait few seconds

**Expected behavior**
Normal transfer from lobby to playing server without any issues.

**Screenshots**
Not needed

**Version Info**
4.6.0 [https://pastebin.com/A9mN1RWV](https://pastebin.com/A9mN1RWV)

**Additional context**
Nothing

**Comment by dmulloy2** [comment]
that exception is fine (PL is gracefully failing in the absence of an old enum, which is why it's in debug). try this: https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#plugins
