### ISSUE TITLE
Latest ProtocolLib Update Breaks Some Plugins

### ISSUE THREAD

**Issue by Lizardz** [dmulloy2/ProtocolLib#1101]
Logs: https://paste.helpch.at/uxanifadur.bash

java.lang.NoClassDefFoundError: com/comphenix/net/sf/cglib/proxy/Factory

**Comment by leviem1** [comment]
Hey, sorry to revive this, but what ended up fixing this? I have the same errors in other plugins

**Comment by dmulloy2** [comment]
Plugins that relied on an implementation detail of ours needed to update

**Comment by leviem1** [comment]
That makes sense, thanks!
