### ISSUE TITLE
Error whenever a player joins

### ISSUE THREAD

**Issue by EthanChamps** [dmulloy2/ProtocolLib#1104]
**Describe the bug**
when ever I join the server it spams it with the error code below Server is using nachoSpigot

**Expected behavior**
https://pastebin.com/z7auXbcs

**Version Info**
https://pastebin.com/y6bGwzHH

**Comment by dmulloy2** [comment]
Does nachoSpigot do something weird with the network manager? @heathlogancampbell

**Comment by HeathLoganCampbell** [comment]
Yeah, quite a bit, probably just gonna make a fork of protocollib for just nachoSpigot
