### ISSUE TITLE
Error with data - plugins dont work now

### ISSUE THREAD

**Issue by RMalfroid** [dmulloy2/ProtocolLib#1105]
**Describe the bug**
Server crashed last night, and now luckperms, warp, core inspect, holographic displays are unable to be used through commands on the server.

**To Reproduce**
Use coreprotect, votingplugin, luckperms, holographic displays with commands while on the server.

**Expected behavior**
Commands to work.

**Screenshots**
I have absolutely no clue how to add an image here.

**Version Info**
https://pastebin.com/hNMEkjFg

**Additional context**
My server host said the error im getting: (https://pastebin.com/cRrX23B2) this error due to ProtocolLib or Luckperms. I just wanted to touch base with you to confirm/deny this. I have never gotten this error before, and it started last night from what I can tell. Half the plugins on my server are not functional right now due to this. How do I fix it, short of removing the plugin? Two of them depend on this to run.

**Comment by dmulloy2** [comment]
Unfortunately that log cuts out a lot of useful info: `[Multicraft] Skipped 25 lines due to rate limit (30/s)`
