### ISSUE TITLE
Getting BlockPosition on block place in 1.14+?

### ISSUE THREAD

**Issue by MeGysssTaa** [dmulloy2/ProtocolLib#1107]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
In MC prior to 1.14x, I can listen for `PacketType.Play.Client.USE_ITEM` packets to handle block placements. And I can use this to retrieve the position of the block placed:
```java
BlockPosition pos = e.getPacket().getBlockPositionModifier().readSafely(0);
```
However, in MC 1.14 and newer `pos` is always `null`. Is there any alternative (whatever way to get the same functionality, **with packets, without using Bukkit events**)?

**API method(s) used**
- `onPacketReceiving` (`USE_ITEM`)
- `PacketContainer#getBlockPositionModifier` (works before 1.14, `null`s in 1.14+)

**Expected behavior**
I'd like to get the coordinates of the block placed (behavior as in versions prior to 1.14, but in 1.14+).

**Code**
*(above)*

**Additional context**
ProtocolLib 4.6.1-SNAPSHOT-b498 (freshly downloaded version from Jenkins, tested right before opening this issue)

**Comment by MeGysssTaa** [comment]
Hi! Any response to this? (Is this an issue that was fixed, or ...?)

**Comment by NotRealPaz** [comment]
@MeGysssTaa 
try this on latest version of ProtocolLib
``BlockPosition pos = e.getPacket().getMovingBlockPositions().read(0).getBlockPosition()``

**Comment by MeGysssTaa** [comment]
Thank you! I confirm this **works on MC 1.14 and newer**.

However, `e.getPacket().getMovingBlockPositions().read(0)` is always `null` in versions before 1.14 (tested 1.8.8, 1.9.4, and 1.13.2). Having some backwards compatibility in ProtocolLib would be nice, I think (just like in case with #1242)
