### ISSUE TITLE
Wierd problems

### ISSUE THREAD

**Issue by Unpluggeddk** [dmulloy2/ProtocolLib#112]
Im very new to this, so im sry if i dont get all the info needed.

So i had this problem i spend all day dealing with.
I could break a block without problems, but it said i had no permission (see picture)

I recently downloaded this: https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/
Wich told me i needed both FurnitureLib Free
and ProtocolLib

Everytime put ProtocolLib in plugins folder the mentioned error occurs, but i get second thoughts if its really this plugin bugging og just the dicefurniture plugin?
Though even with the errors mentioned below, the plugin works (dice furniture) works great.

It could also be that the error mentioned below have nothing to do with the problem im having,
Hope someone can answer my question. 

I tried with latest ProtocolLib to, still the same

I get this message:
<
23:27:08 [INFO] [FurnitureLib] Furniture start load
23:27:08 [INFO] [FurnitureLib] FurnitureLib load 3924 ArmorStandPackets from: SQLite Database
23:27:11 [WARNING] java.lang.IllegalArgumentException: Invalid UUID string:
23:27:11 [WARNING] 	at java.util.UUID.fromString(Unknown Source)
23:27:11 [WARNING] 	at de.Ste3et_C0st.FurnitureLib.Database.Serialize.getUUIDList(Serialize.java:247)
23:27:11 [WARNING] 	at de.Ste3et_C0st.FurnitureLib.Database.Serialize.fromArmorObjectString(Serialize.java:238)
23:27:11 [WARNING] 	at de.Ste3et_C0st.FurnitureLib.Database.Database.loadAllObjIDs(Database.java:163)
23:27:11 [WARNING] 	at de.Ste3et_C0st.FurnitureLib.Database.SQLManager.loadALL(SQLManager.java:53)
23:27:11 [WARNING] 	at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.java:111)
23:27:11 [WARNING] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
23:27:11 [WARNING] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
23:27:11 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
23:27:11 [WARNING] 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
23:27:11 [WARNING] 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
23:27:11 [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
23:27:11 [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
23:27:11 [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
23:27:11 [WARNING] 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
23:27:11 [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
23:27:11 [WARNING] 	at java.lang.Thread.run(Unknown Source)
23:27:11 [INFO] [FurnitureLib] Furniture load finish
23:27:11 [INFO] [FurnitureLib] ==========================================
>

![2015-08-24_23 28 30](https://cloud.githubusercontent.com/assets/13952065/9453023/ec5f77e4-4ab7-11e5-94d2-91e7c240c3c0.png)

**Comment by dmulloy2** [comment]
This is an issue with the furniture plugin. ProtocolLib isn't mentioned in the stacktrace.
