### ISSUE TITLE
zz

### ISSUE THREAD

**Issue by ThisVanilla** [dmulloy2/ProtocolLib#1126]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5023d3b0
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@7608f30c[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=float
      data=[public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@36773e65[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@393a3f71
        packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@81b2bc9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@e246612
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@12ff5a5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@69869346
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3812a8dc
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-576,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6b5710e7
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7e186a7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46761c1
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@62af97bb[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@da5d2a3d=[com.comphenix.protocol.injector.StructureCache$1@252d8a4e], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@cd59befd=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@2e72e4f2], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@176fd559=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@1124f194], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@3da1400=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@fa8be44]}
      listenerLock=java.lang.Object@469e3a05
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@7ff21350
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@49ece56b
      reporter=com.comphenix.protocol.ProtocolLib$1@3812a8dc
      unknownPermGenBean=java.lang.Object@3fc388c
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16
  Server:
    git-Paper-576 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
Which version of Java are you using?

**Comment by ThisVanilla** [comment]
> Which version of Java are you using?

Java Version:
16
