### ISSUE TITLE
TextComponentImpl wrapper

### ISSUE THREAD

**Issue by kangarko** [dmulloy2/ProtocolLib#1129]
When listening to PacketType.Play.Server.CHAT Paper introduced their Adventure library which returns "net.kyori.adventure.text.TextComponentImpl" instead of the md_5's class which doesn't support the 'event.getPacket().getChatComponents()' method returning a WrappedChatComponent.

I am therefore suggesting you add support for Adventure into WrappedChatComponent so that calling the read(0) method for that given chat component will properly return an object we can easily work with, and write later.

Thank you. Let me know if you need any more information.

**Comment by kaonashi97** [comment]
Seems that this is already implemented (#1103) but was not in release version 4.6.0 as it was build earlier.

**Comment by kangarko** [comment]
Thanks!
