### ISSUE TITLE
Error with TacoSpigot/NachoSpigot

### ISSUE THREAD

**Issue by EzWzs** [dmulloy2/ProtocolLib#1130]
Version: 
NachoSpigot 1.8.8 (Optimized PaperSpigot Fork)
Protocollib 4.6 (Latest) Not a Dev Build

Issue: Spams this in console;
[ProtocolLib] [DetailedErrorReporter] Internal exception count: 32!
Error Unable to inject incoming channel [id: 0x3804f8c2, L:/127.0.0.1:25568 - R:/127.0.0.1:54956] (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x3804f8c2, L:/127.0.0.1:25568 - R:/127.0.0.1:54956]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@1d3a237c.

NoTeS:
Only happens in forks like this glowstone, tacospigot, and nachospigot are tested and the same thing happens.
In glowstone it doesn't even allow the server to startup but in the other two it spams that error.
This issue does not happen in regular paperspigot or spigot

**Comment by MacacoLew** [comment]
This is fixed by my Pull request (see it on Pull requests)
