### ISSUE TITLE
Players Not Able To Hit Animals

### ISSUE THREAD

**Issue by Blxrio** [dmulloy2/ProtocolLib#1136]
Hi there, Im writing to report a bug issue, Im running this plugin on my server and players aren't able to hit mobs or animals, i've done a binary search and disabled plugins one by one, And I disabled ProtocolLib, and suddenly they could hit mobs and animals, So Im just wondering if there's a fix for it? Thank you

**Comment by taka1945** [comment]
it's same to me trouble 2 days lol

try this version , dmulloy2 released this on 16 Feb

https://github.com/dmulloy2/ProtocolLib/releases
