### ISSUE TITLE
Console Error with VentureChat

### ISSUE THREAD

**Issue by Frunace** [dmulloy2/ProtocolLib#1139]
**Describe the bug**
Error message in console when starting server with VentureChat.

Copy-paste from console:
[console_error.txt](https://github.com/dmulloy2/ProtocolLib/files/6329062/console_error.txt)

**To Reproduce**
1. Download Paper Server 1.16.5 Build 597
2. Add VentureChat 2.22.5 and required plugins to folder (Vault, ProtocolLib, PlaceholderAPI)
3. Run server
4. Error message in console on startup

**Expected behavior**
No error message.

**Version Info**
ProtocolLib v4.6.0
[dump-2021-04-17_12.37.39.txt](https://github.com/dmulloy2/ProtocolLib/files/6329068/dump-2021-04-17_12.37.39.txt)

**Additional context**
Not sure if this goes to here or VentureChat but the error message said to post here.

**Comment by PimvanderLoos** [comment]
This issue was resolved in build 499 of ProtocolLib, so just get the latest dev build and it will work.

**Comment by Frunace** [comment]
Ah I see, I'm using a hosting site that only allows to pick plugins off some kinda list, so it didn't have that version in there. Worked when I made a local server with the dev build. Thanks for the quick response!
