### ISSUE TITLE
Are packets sent asynchronously guaranteed to be sent to the player in the correct order?

### ISSUE THREAD

**Issue by LOOHP** [dmulloy2/ProtocolLib#1140]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
Quick question, are packets sent using the method below **asynchronously** guaranteed to be sent to the player in the correct order?
Namely entity packets, like LivingEntity spawn packets or Entity Metadata, as well as Chat Packets.

**API method(s) used**
ProtocolManager.sendServerPacket(Player player, PacketContainer packet, boolean filter);

**Comment by dmulloy2** [comment]
you might be able to ensure the order by scheduling them all on the channel thread. but order is very much not guaranteed async

**Comment by LOOHP** [comment]
Like if I send all my packets on the same async thread, the order is still not guaranteed?

**Comment by dmulloy2** [comment]
if they're all sent on the same thread, they should arrive in the same order relative to each other. can't make any guarantees about other packets though
