### ISSUE TITLE
Disguising a snowball to an ItemStack

### ISSUE THREAD

**Issue by InfiniteV** [dmulloy2/ProtocolLib#115]
Hey, it's not really an issue but I couldn't find an IRC or anything so I think this is the right place. How would I disguise a snowball to a itemstack? I've followed the tutorial that disguises a zombie as a chicken but I can't set the item type or anything. Help? (I set the EntityType though)

**Comment by dmulloy2** [comment]
You would set the Entity's type to EntityType.ITEM, then set the entity's ItemStack to whatever item stack you want to use.
