### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by nnaem** [dmulloy2/ProtocolLib#1160]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @baea30a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@77ca0f80[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@663f2d09[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@64c75f4
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@215dccb2
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4bd50b7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1b75624c
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7ef34703
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5f52fa5c
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-652,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@baa0d44
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4b6d5732
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2e3a9104
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@47e0bb54[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@c6bcc8b5=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@6271077d], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@89f9ccc2=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@438418c6]}
      listenerLock=java.lang.Object@39cc1303
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@7b342575
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@11948f81
      reporter=com.comphenix.protocol.ProtocolLib$1@5f52fa5c
      unknownPermGenBean=java.lang.Object@72b5f75d
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-652 (MC: 1.16.5)

**Comment by stumper66** [comment]
I was coming here to report this issue as well.  I suspect many people are going to run into this since Minecraft and Paper have announced that starting with version 1.17 java 16 will be required.

**Comment by PimvanderLoos** [comment]
This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by kooldamian28** [comment]
Same here, I have also been experiencing this error. Please fix it ASAP!

**Comment by bonn2** [comment]
@kooldamian28 See the comment directly above yours

**Comment by nnaem** [comment]
Check @PimvanderLoos comment for fix, thanks
