### ISSUE TITLE
EffectID weird error

### ISSUE THREAD

**Issue by leChapelierFou-D** [dmulloy2/ProtocolLib#1161]
**Describe the bug**
It's a weird issue.
For EffectID:
in Play.Server.ENTITY_EFFECT I can't use getEffectTypes
and in Play.Server.REMOVE_ENTITY_EFFECT I can't use getBytes.

**Expected behavior**
I should capable to use getEffectTypes or getBytes indifferently.

**Version Info**
 [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b498

**Comment by dmulloy2** [comment]
The packets are structured differently; entity effect has a bunch of bytes and ints, remove entity effect has the effect type. PL just shows you what's in NMS
