### ISSUE TITLE
Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.)

### ISSUE THREAD

**Issue by Saabertooth1** [dmulloy2/ProtocolLib#1163]
**Describe the bug**
Error Unable to intercept a read client packet.

**To Reproduce**
Happened when client left the server

**Expected behavior**

**Screenshots**

**Version Info**
https://pastebin.com/pGkuJ5Bt

**Additional context**
Stack trace https://pastebin.com/26T3eJ10

**Comment by dmulloy2** [comment]
Based on that exception, the latest dev build may work
