### ISSUE TITLE
ProtocolLib-StructureCompiler 0/ERROR

### ISSUE THREAD

**Issue by rkfsociety** [dmulloy2/ProtocolLib#1164]
[15:36:54] [ProtocolLib-StructureCompiler 0/INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @54faa119) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5f8218d8.
[15:36:54] [ProtocolLib-StructureCompiler 0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @54faa119
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@5f4de4b3[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={boolean=StructureModifier[fieldType=boolean, data=[protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]], double=StructureModifier[fieldType=double, data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z]], float=StructureModifier[fieldType=float, data=[public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@352c5fd7[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1813c7aa
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicPlaceholders, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[FLYING[class=PacketPlayInFlying, id=21], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20], POSITION[class=PacketPlayInPosition, id=18], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@4e039b22
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@698dd0bf
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3e88e8be
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@38204652
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@6aa810ff
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-703,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1493e52f
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=12
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5b155720
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2c409580
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5f8218d8[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@38e02c80=[com.comphenix.protocol.injector.StructureCache$1@2c81a9f4], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@add34b02=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@5d5c5713], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@70cf629c=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@751825ad], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@bd634640=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@3a93a70e], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@47d8218e=[com.comphenix.protocol.injector.StructureCache$1@1b7c67a1], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@89d106ab=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@24274f12], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@93e65c7d=[com.comphenix.protocol.injector.StructureCache$1@10262376], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@60867adb=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@372a4dab], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@625d1643=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@4f936580]}
      listenerLock=java.lang.Object@5152fcbf
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@70ce5870
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@15ec14d7
      reporter=com.comphenix.protocol.ProtocolLib$1@6aa810ff
      unknownPermGenBean=java.lang.Object@4107dc8f
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-703 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment]
This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
