### ISSUE TITLE
NoSuchMethodException: MapIcon hasn't an empty constructor!

### ISSUE THREAD

**Issue by SoKnight** [dmulloy2/ProtocolLib#1165]
**Describe the bug**
Hi! Just now i work on my plugin using ProtocolLib. I use `MapData` packet (clientbound) and the PacketWrapper repository has wrapper for this packet. This wrapper has a method for adding `MapIcon`'s array, but this method throws an exception after trying to construct the MapIcon NMS handle (see screenshot below).

**To Reproduce**
1. Try to use `#setMapIcons()` in [this](https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerMap.java) wrapper class.

**Expected behavior**
This method must set an array of MapIcon handles in the packet container, but actually fails.

**Screenshots**
[The exception in console](https://i.imgur.com/hZ7Sbho.png).

**Version Info**
[Pastebin](https://pastebin.com/CZVcksSH).

**Comment by dmulloy2** [comment]
thank you for the report! i'll go look into this now

**Comment by UniverseCraft** [comment]
I had the exact same issue and found that I was accidentally shading ProtocolLib into my plugin. If you use the Maven shade plugin as part of your build process (I checked your public repositories and you do use this at times), make sure you specify the scope as `provided` in your `pom.xml`. (If you don't specify anything, it defaults to `compile`)
