### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by HAG0S** [dmulloy2/ProtocolLib#1177]
I'm getting this warning
![Screen Shot 2021-05-25 at 6 23 43 pm](https://user-images.githubusercontent.com/77733753/119482348-58527b80-bd86-11eb-9fb6-734a854dd6e3.png)

**Comment by PimvanderLoos** [comment]
Duplicate of #1167 

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
