### ISSUE TITLE
ProtocolLibrary.getProtocolManager() returns null

### ISSUE THREAD

**Issue by stovan12** [dmulloy2/ProtocolLib#1178]
**Describe the bug**

**To Reproduce**
I have no idea, all my other plugins work fine with protocol lib, one specific one its calls to Protocollibrary are just dead, all null returns.

**Expected behavior**
Should return a real instance, not null

**Screenshots**

**Version Info**
https://pastebin.com/a0CWUwtS

**Additional context**
How can I get an alive instance of protocollib? the static protocollibrary in this plugin is not loaded.

**Comment by gemmycoder** [comment]
I have the same issue

**Comment by dmulloy2** [comment]
Which plugin?

**Comment by UniverseCraft** [comment]
I had the exact same issue and found that I was accidentally shading ProtocolLib into my plugin. If you use the Maven shade plugin as part of your build process, make sure you specify the scope as `provided` in your `pom.xml`. (If you don't specify anything, it defaults to `compile`)
