### ISSUE TITLE
No disconnect reason by invoking event.getPlayer().kickPlayer(String)

### ISSUE THREAD

**Issue by games647** [dmulloy2/ProtocolLib#118]
If I try to kick a player in a packet event during **Login** state, ~~the plugin~~ Minecraft appears to ignore the reason I specified. It just displays "disconnect".

I found out that if I manually create disconnect packet (PacketType.Login.Server.DISCONNECT) and send it to the client, it displays the reason correctly to the client. Invoking the method during Play state also works fine as it should.

**Comment by dmulloy2** [comment]
This is an issue with Minecraft, not ProtocolLib. event.getPlayer() returns a Bukkit player, which then passes the kickPlayer call to Minecraft.
