### ISSUE TITLE
Mohist Fatal error

### ISSUE THREAD

**Issue by toastontoast** [dmulloy2/ProtocolLib#1183]
**Describe the bug**
Roughly every couple of ticks the console will spit out this error. ProtocalLib will also block any command from functioning including commands in the console.

**To Reproduce**
1. Start a Mohist-1.16.5-603 server
2. Add ProtocalLib and Create Mod
3. Join and move around. Error will occur in console

**Expected behavior**
A huge fatal error and all commands to stop functioning.

**Logs**
[https://pastebin.com/tpBZg1W3](https://pastebin.com/tpBZg1W3)

**Version Info**
[https://pastebin.com/ZTupF6pQ](https://pastebin.com/ZTupF6pQ)

**Additional context**
This may just be a error because protocallib isn't compatible with Mohist so oh well.

**Comment by dmulloy2** [comment]
Currently not planning on supporting mohist
