### ISSUE TITLE
INTERNAL ERROR: Cannot compile structure

### ISSUE THREAD

**Issue by KolakZ** [dmulloy2/ProtocolLib#1192]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3e55879d
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@3d9f5fff[
      targetType=class net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]
      defaultFields={public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname=1, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d=3}
      subtypeCache={class net.minecraft.server.v1_16_R3.EnumProtocol=StructureModifier[fieldType=class net.minecraft.server.v1_16_R3.EnumProtocol, data=[private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]], class java.lang.String=StructureModifier[fieldType=class java.lang.String, data=[public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname]], int=StructureModifier[fieldType=int, data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@217001af[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3e1449c4
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3d42cdfa
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@651cfedd
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4440f6a8
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5886cd8d
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@7300e67a
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1151,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@32de49e2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5933929f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@55e14fb0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@154e0464[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@280995ee=[com.comphenix.protocol.injector.StructureCache$1@1e6f355c]}
      listenerLock=java.lang.Object@5b8dfb64
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@44ea36a
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@61c6eaa3
      reporter=com.comphenix.protocol.ProtocolLib$1@7300e67a
      unknownPermGenBean=java.lang.Object@664e612
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Purpur-1151 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment]
Duplicate of #1162

This issue was resolved in [build 499+](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).

**Comment by KolakZ** [comment]
Alright, thanks.
