### ISSUE TITLE
Error: INTERNAL ERROR: Cannot compile structure. Disabing compiler.

### ISSUE THREAD

**Issue by DriveLive** [dmulloy2/ProtocolLib#1194]
This came up on my survival world this morning: 

Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @b9fa1e
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@7d7b4ef6[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@22ba8556[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1ec10bbd
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ABILITIES[class=PacketPlayOutAbilities, id=48], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@396aea6d
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@68dcf22e
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1eba4a56
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@8b036df
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@66e79c26
        server=CraftServer{serverName=Tuinity,serverVersion=git-Tuinity-"f7c4249",minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@258140ce
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=5
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1ae6ac40
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4253b687
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@257d743a[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@ceef2ad=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@609e7327]}
      listenerLock=java.lang.Object@4f3557d8
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@100d3737
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@5e1f5da8
      reporter=com.comphenix.protocol.ProtocolLib$1@66e79c26
      unknownPermGenBean=java.lang.Object@4d8b1a07
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Tuinity-"f7c4249" (MC: 1.16.5)

-------------------------------------------------------------
No Idea what it means but it said to report it here.

**Comment by Schneidertm** [comment]
#1190

**Comment by CloudeLecaw** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/505/
