### ISSUE TITLE
Internal error crashes the server

### ISSUE THREAD

**Issue by Villmarksjenta** [dmulloy2/ProtocolLib#1195]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ x] You're using the latest build for your server version
- [ x] This isn't an issue caused by another plugin
- [ x] You've checked for duplicate issues
- [ x] You didn't use `/reload`

Debug paste link:

[10:28:42] [ProtocolLib-StructureCompiler 0/INFO]:&nbsp;Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @17ab2e64) occured in&nbsp;com.comphenix.protocol.reflect.compiler.BackgroundCompiler@66d58c6a.
--
436 | [10:28:42] [ProtocolLib-StructureCompiler 0/ERROR]:&nbsp;[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
437 | If this problem hasn't already been reported, please open a ticket
438 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
439 | Stack Trace:
440 | java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @17ab2e64
441 | at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
442 | at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
443 | at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
444 | at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
445 | at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
446 | at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
447 | at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
448 | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
449 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
450 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
451 | at java.base/java.lang.Thread.run(Thread.java:831)
452 | Dump:
453 | Parameters:
454 | com.comphenix.protocol.reflect.StructureModifier@1b274780[
455 | targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
456 | target=&lt;null&gt;
457 | converter=&lt;null&gt;
458 | fieldType=class java.lang.Object
459 | data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
460 | defaultFields={}
461 | subtypeCache={}
462 | customConvertHandling=false
463 | useStructureCompiler=true
464 | ]
465 | manager:
466 | com.comphenix.protocol.injector.PacketFilterManager@28021cba[
467 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@121bd767
468 | packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayOutPosition, id=52], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayOutPosition, id=52], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
469 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@61300348
470 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@400a43a9
471 | inputBufferedPackets=[]
472 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@785570de
473 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3439305c
474 | hasClosed=false
475 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
476 | reporter=com.comphenix.protocol.ProtocolLib$1@55724fd0
477 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-768,minecraftVersion=1.16.5}
478 | library=ProtocolLib v4.6.0
479 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@14f7127c
480 | knowsServerPackets=true
481 | knowsClientPackets=true
482 | phaseLoginCount=0
483 | phasePlayingCount=6
484 | packetCreation=false
485 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7f762c04
486 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1d7e529f
487 | hasRecycleDistance=true
488 | minecraftVersion=(MC: 1.16.5)
489 | debug=false
490 | ]
491 | Sender:
492 | com.comphenix.protocol.reflect.compiler.BackgroundCompiler@66d58c6a[
493 | listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@a122bda1=[com.comphenix.protocol.injector.StructureCache$1@40cae185]}
494 | listenerLock=java.lang.Object@e12e394
495 | compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@6117a263
496 | enabled=false
497 | shuttingDown=false
498 | executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@2b6bd4f7
499 | reporter=com.comphenix.protocol.ProtocolLib$1@55724fd0
500 | unknownPermGenBean=java.lang.Object@3c3aded6
501 | permGenBean=&lt;null&gt;
502 | disablePermGenFraction=0.65
503 | ]
504 | Version:
505 | ProtocolLib v4.6.0
506 | Java Version:
507 | 16.0.1
508 | Server:
509 | git-Paper-768 (MC: 1.16.5)

**Comment by Schneidertm** [comment]
See #1190
