### ISSUE TITLE
Should all be clean install?!

### ISSUE THREAD

**Issue by DerVillion** [dmulloy2/ProtocolLib#1196]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1ca934d2
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@5f523a0b[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@c919863[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5fdf5fac
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1113b43e
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@fa69640
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@ff44557
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2a73593a
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@264dba0e
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-771,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@30111c17
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7f0a1cf6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@26055cb8
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@61b00ff[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@b1578e50=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@5b88f738], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@241eb086=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@74caad13]}
      listenerLock=java.lang.Object@78a6dfae
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@266424bd
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@3ac9267e
      reporter=com.comphenix.protocol.ProtocolLib$1@264dba0e
      unknownPermGenBean=java.lang.Object@1b4aa601
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-771 (MC: 1.16.5)

**Comment by Schneidertm** [comment]
See #1190
