### ISSUE TITLE
Boat and minecart does not work

### ISSUE THREAD

**Issue by Feierr** [dmulloy2/ProtocolLib#120]
v3.6.5-snapshot-b199, spigot 1.8.8. After install the plugin, player won't able to ride boats.

**Comment by dmulloy2** [comment]
What plugins do you have that use ProtocolLib? More than likely it's them at fault.

**Comment by Feierr** [comment]
Seemingly it's not ProtocolLib's fault, weird. I ran a test yesterday, I deleted all the plugins except ProtocolLib and I assumed the plugin caused it, but now I don't think ProtocolLib caused it. Here is my plugins. Thank you for your time, i will be appreaited if you can help me solve it.
plugins: http://i.imgur.com/YpwOZPq.png

**Comment by Feierr** [comment]
Again, thank you for your responses. Here is my problem: http://i.imgur.com/fcMDs8n.gif. I will definitely go over plugins again.

**Comment by dmulloy2** [comment]
Try the latest build and use /protocol dump. That'll give a list of plugins that have packet listeners, which should help.

**Comment by Feierr** [comment]
I ran a test and i am 100% protocol caused it. Uploading video.

**Comment by dmulloy2** [comment]
It's a plugin that uses ProtocolLib, not ProtocolLib. Use /protocol dump and paste the output on pastebin.com.

**Comment by Feierr** [comment]
I see what you mean, but however I used /protocol dump, it does not work. Only showed up 4 options as, config|timings|listeners|version

**Comment by dmulloy2** [comment]
The command was added in 3.6.5, grab it from my jenkins: http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by Feierr** [comment]
http://pastebin.com/z8sFns2z

**Comment by dmulloy2** [comment]
My best guess is uCars, try removing it and see if that fixes the issue.

**Comment by Feierr** [comment]
It happened before I added uCars, and even I remove uCars it still not working. uCars will not work too, because the minecarts got stuck too.

**Comment by dmulloy2** [comment]
Just for the sake of debugging, try it without LibsDisguises.

**Comment by Feierr** [comment]
At the first I thought it was LibsDisguises because it is the only plugin that I saw which depends on ProtocolLib, but unfortunately LibsDisguises was not the plugin caused this. I ran several tests but still no results.

**Comment by dmulloy2** [comment]
Just did a little bit of testing, it's Anti Damage Indicators. I added it and boats stopped working.

**Comment by Feierr** [comment]
Solved, thank you soooo much <3333
