### ISSUE TITLE
Internal Error Message In Console

### ISSUE THREAD

**Issue by JIMSAM2** [dmulloy2/ProtocolLib#1204]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @649b6b52
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@3aea97a7[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4c0a9ed6[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@30a1ac4f
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1d6c1721
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7355fc84
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6b313016
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@564f2aeb
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@778a9228
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-776,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3a6ed56d
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1997a652
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5ce6de09
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@7c2b230b[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@fc0ba22b=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@5f375f73]}
      listenerLock=java.lang.Object@7b36c7f1
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@114a5808
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@34dc0251
      reporter=com.comphenix.protocol.ProtocolLib$1@778a9228
      unknownPermGenBean=java.lang.Object@51f50f7e
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-776 (MC: 1.16.5)

**Comment by CloudeLecaw** [comment]
Your using the wrong version
There is a version for java 16
https://ci.dmulloy2.net/job/ProtocolLib/505/
