### ISSUE TITLE
Hiding Tile Entities from certain players.

### ISSUE THREAD

**Issue by Darkfield** [dmulloy2/ProtocolLib#121]
Hello, I want to hide all tile entities in cells area (prison server), because it's causing massive client side fps drop, players could see it if they wish by typing command.

I found http://dev.bukkit.org/bukkit-plugins/protocollib/forum/65150-hide-blocks-from-player/
(last message, last words https://github.com/aadnk/BlockPatcher)

Is this, what do I need? But it hasn't been updated for 3 years.

"Qoute from aadnk
The only problem is that right-clicking on these blocks will reset them to their actual type on the server. If you want to make this a bit more persistent, you could try intercepting packets."

And I don't care about right-clicking. So there should be more efficient way.

Is there just simple TileEntitySpawn packet? I was able to find WrapperPlayServerSpawnEntity, but it doesn't include all tile entities. Missing: chests, furnaces (http://minecraft.gamepedia.com/Block_entity)

**Comment by dmulloy2** [comment]
I've updated BlockPatcher here: https://github.com/dmulloy2/BlockPatcher

There isn't a "tile entity spawn" packet, tile entities are basically blocks with extra data (like items for chests, potions for brewing stands, etc.)
