### ISSUE TITLE
Error Appears on Paper MC 1.16.5-777 (ProtocolLib 4.6.0)

### ISSUE THREAD

**Issue by rudipratm** [dmulloy2/ProtocolLib#1210]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @eba916f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@36865193[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a, public long net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.timestamp]
      defaultFields={private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@548526c2[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@50d80bef
        packetListeners=[PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@21ad6988
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@25a3bee7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@586d2fa7
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@48fac036
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2d11188
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-777,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@b9cd344
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=8
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2631d3d6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@795cb4b0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@14a7d2f3[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@dbbda27f=[com.comphenix.protocol.injector.StructureCache$1@e9f1d92]}
      listenerLock=java.lang.Object@2698d0f4
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@3a7d09a3
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@10676455
      reporter=com.comphenix.protocol.ProtocolLib$1@2d11188
      unknownPermGenBean=java.lang.Object@66e28846
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-777 (MC: 1.16.5)

**Comment by derklaro** [comment]
This has already been fixed in [4.6.1](https://ci.dmulloy2.net/job/ProtocolLib/505/).
