### ISSUE TITLE
Console/ ingame error message

### ISSUE THREAD

**Issue by ChloeTheFox** [dmulloy2/ProtocolLib#1211]
**Describe the bug**
Console/ingame error message

**To Reproduce**
No idea only happened once

**Expected behavior**
No errors

**Version Info**
https://pastebin.com/E43S1LJ5

**Additional context**
Console log/message: 
https://pastebin.com/x8q3qr4F

**Comment by derklaro** [comment]
I assume you use Java 16, so please upgrade to [4.6.1](https://ci.dmulloy2.net/job/ProtocolLib/505/).
