### ISSUE TITLE
Exception with SlotStackPairs

### ISSUE THREAD

**Issue by MCMDEV** [dmulloy2/ProtocolLib#1213]
**Describe the bug**
When trying to use pairs of SlotStackPairs using packet.getSlotStackPairLists(), the server throws ClassCastExceptions.

**To Reproduce**
1. Create ProtocolListener which listens to every outgoing packet
2. Modify every field of the type, I did it this way:
```java
    @Override
    public void onPacketSending(PacketEvent event) {
        PacketContainer packet = event.getPacket();
        for (int i = 0; i < packet.getSlotStackPairLists().getFields().size(); i++) {
            packet.getSlotStackPairLists().modify(i, input -> input);
        }
    }
3. Watch it break
```

**Expected behavior**
Nothing

**Logs**
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/6644025/latest.log)

**Version Info**
https://pastebin.com/GCMWG4NY

**Comment by derklaro** [comment]
The method `getSlotStackPairLists` will return all fields of type `List` which does not mean that a slot pair is in it (applies to all modifiers with a generic parameter). You have to verify yourself which fields you are modifying. 

Btw in the MapChunk packet is never a SlotStack List :)
