### ISSUE TITLE
ProtocolLib-StructureCompiler 0/ERROR

### ISSUE THREAD

**Issue by Illustive** [dmulloy2/ProtocolLib#1214]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6187559e
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@39c92d5b[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={float=StructureModifier[fieldType=float, data=[public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch]], double=StructureModifier[fieldType=double, data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7d84edb2[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@d57a4ac
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AAC5, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], POSITION[class=PacketPlayOutPosition, id=52], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=LOW, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], POSITION[class=PacketPlayOutPosition, id=52], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ABILITIES[class=PacketPlayOutAbilities, id=48]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6d20339a
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@b0f7331
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@513cf69f
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@617e4ad0
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@dae1986
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-777,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4bf6ecd1
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=8
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@67e76e39
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5727addf
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=true
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@60fa82e7[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@5278b59c=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@27f9bb74], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@68aa3873=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@7bb38f14], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@8533088f=[com.comphenix.protocol.injector.StructureCache$1@11908ce8]}
      listenerLock=java.lang.Object@25c9c987
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@4f01f451
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@28ad098a
      reporter=com.comphenix.protocol.ProtocolLib$1@dae1986
      unknownPermGenBean=java.lang.Object@3d4f27bb
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-777 (MC: 1.16.5)
- [ ] You didn't use `/reload`

Debug paste link:

Description and relevant errors:

**Comment by zhenghanlee** [comment]
use the latest build of java 16
https://ci.dmulloy2.net/job/ProtocolLib/505/
