### ISSUE TITLE
ProtocolLib Errors

### ISSUE THREAD

**Issue by Downlqad** [dmulloy2/ProtocolLib#1215]
**Describe the bug**
Whenever we're rebooting our OP Prison mode, We're sending people back in, and we get the following errors on multiple plugins:

https://pastebin.com/EeD81KeS
https://pastebin.com/u4pWrNV6
https://pastebin.com/9rg4sK4h

**To Reproduce**
We're just sending people, thats what happends..

**Expected behavior**
Not get errors about "Temporary Players"?

**Screenshots**
I've sent the Pastebins Above

**Version Info**
ProtocolLib v4.5.1, https://pastebin.com/tWy7KZsX

**Additional context**
Also, possible to add me on discord Shanny#0001

**Comment by Downlqad** [comment]
https://pastebin.com/7yWC80SV

Throwing an error in a class that doesn't exist..

**Comment by CloudeLecaw** [comment]
The pluginsite sais:
[If you're running 1.8 through 1.16, use the latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.6.0)
