### ISSUE TITLE
Listen PacketPlayOutSpawnEntity instead of Title

### ISSUE THREAD

**Issue by Rothes** [dmulloy2/ProtocolLib#1218]
**Describe the bug**
PacketAdapter will listen PacketPlayOutSpawnEntity instead of PacketType.Play.Server.TITLE

**To Reproduce**
1. Use ProtocolLib v4.7.0-SNAPSHOT-b507
2. Use the same plugins that runs in 1.16 with no exception and listens on PacketType.Play.Server.TITLE
3. See error

**Expected behavior**
Listen PacketType.Play.Server.TITLE, what plugins delimited.

**Screenshots**
N/A

**Version Info**
https://paste.ubuntu.com/p/JcKdHmkN6v/

**Additional context**

**Comment by dmulloy2** [comment]
I think TITLE got split out into multiple separate packets. Double check wiki.vg

**Comment by Rothes** [comment]
Should have checked them... So this might be a backward issue

**Comment by dmulloy2** [comment]
since you're running 1.17, the mappings in packettype reflect nms. you'll need to update your plugin for the new 1.17 packets

**Comment by Rothes** [comment]
Thanks. Already got it solved.
