### ISSUE TITLE
Getting an error, console SPAM. Spigot MC 1.8.2 version

### ISSUE THREAD

**Issue by NickFirenzo** [dmulloy2/ProtocolLib#122]
Hi,
I need help about plugin ProtocolLib, when starting server getting spam consolse errors, 150+ lines skipped. I need ProtocolLib for 1.8.2 spigot server version. On 1.8.3+ work fine without error but on 1.8.2 getting an errors. Where can I find ProtocolLib for 1.8.2 version without errors and workt fine how on 1.8.3?
Error: http://pastebin.com/LJKmDa2n

**Comment by dmulloy2** [comment]
Where are people getting 3.4.x jars? Use 3.6.4 for 1.8.x.

**Comment by NickFirenzo** [comment]
I'll try, thanks 
Please don't close topic, thanks :)

**Comment by dmulloy2** [comment]
Any more info on this?
