### ISSUE TITLE
Performing a clone on a movement packet throws a no packet type associated exception

### ISSUE THREAD

**Issue by libraryaddict** [dmulloy2/ProtocolLib#1222]
**Describe the bug**

Cloners for the teleport and move packets appear to fail. Other cloners may also fail, but spammy errors doesn't really let me check this.

**To Reproduce**

Perform a shallow clone on the packet.

**Expected behavior**

No errors to be thrown

**Error Logs**

https://gist.github.com/a1db734051bfb50435b8b9986d49c0a1

**Version Info**

Build https://github.com/dmulloy2/ProtocolLib/commit/fa317c116752432da21e18c662d95178a9d2b835 downloaded through jenkins

**Comment by dmulloy2** [comment]
@libraryaddict hopefully the latest dev build will fix this

**Comment by libraryaddict** [comment]
Has seemingly been fixed!
