### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#1223]
I broke some backwards compat trying to quickly update to 1.17. This means the latest dev builds don't support 1.8-1.16, but they hopefully will with these fixes

- [ ] Legacy packet types
- [ ] Random uses of NMS imports instead of reflection
- [ ] Probably other things

**Comment by derklaro** [comment]
If it's ok i will take a look to nuke all usages of net.minecraft and craftbukkit
