### ISSUE TITLE
I have something like that

### ISSUE THREAD

**Issue by Gryffin78** [dmulloy2/ProtocolLib#1226]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [\/ ] You're using the latest build for your server version
- [x ] This isn't an issue caused by another plugin
- [\/ ] You've checked for duplicate issues
- [x ] You didn't use `/reload`

Debug paste link:

https://pastebin.com/KEjjBRz7

Server Name: RpgZone
Version: 1.17
IP: RpgZonePL.fmcs.cf
Owner Username: Gryffin
Discord: https://discord.gg/JWGApWH

**Comment by Noneatme** [comment]
Yeah I get the same error too. Will disable the plugin for now.
