### ISSUE TITLE
Unable to make protected final java.lang.Class

### ISSUE THREAD

**Issue by ALufkin24** [dmulloy2/ProtocolLib#1231]
I'm getting this in console after I updated the plugin to 1.17. I am still using 1.16. 
This is the error:
17.06 19:23:43 [Server] INFO Stack Trace:
17.06 19:23:43 [Server] INFO java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3ed869f9

**Version Info**
4.6.0
Dump Pastebin link: https://pastebin.pl/view/8de343bf

**Comment by derklaro** [comment]
This has already been fixed in [4.6.1](https://ci.dmulloy2.net/job/ProtocolLib/505/).
