### ISSUE TITLE
PL will not compile when trying to create a portal with BetterPortals

### ISSUE THREAD

**Issue by Snolune** [dmulloy2/ProtocolLib#1237]
**Describe the bug**
Error Cannot compile structure. Disabing compiler.

**To Reproduce**
1. Created a portal with BetterPortals

**Expected behavior**
A portal to be generated between two points.

**Screenshots**
![error](https://user-images.githubusercontent.com/86166557/122652547-11e20980-d105-11eb-88ed-c994b8ca49bf.png)

**Version Info**
[dump-2021-06-19_14.38.14.txt](https://github.com/dmulloy2/ProtocolLib/files/6681186/dump-2021-06-19_14.38.14.txt)

**Additional context**
1. Created a portal between two point next to each other. 
2. Portal worked and then I removed it.
3. Created a new portal between two different worlds.
4. Portal worked and then I removed it.
5. Went to create the actual portal that players would use, and PL disabled itself.
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/6681185/latest.log)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
