### ISSUE TITLE
1.17 Run error

### ISSUE THREAD

**Issue by Comhrai-McNicholl** [dmulloy2/ProtocolLib#1239]
**Describe the bug**
Crash on start-up, the plugin will instantly breakdown when your server starts and will print out an error on console & in-game chat.

**Version Info**
Latest (ProtocolLib 4.6.0)

**Error Log**
https://pastebin.com/9D3ELRgp

**Comment by derklaro** [comment]
For 1.17 please use 4.7-SNAPSHOT from [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by srnyx** [comment]
This is an issue with using Java 16 in general. It's happening to me when using Paper 1.16.5 with Java 16.
Using Java 11 didn't have this happen.

**Comment by derklaro** [comment]
In this case can you please provide the code you are using so i can try to reproduce it?

**Comment by srnyx** [comment]
> In this case can you please provide the code you are using so i can try to reproduce it?

I didn't see the `If you're running Java 16 or Paper dev builds, use 4.6.1.` on the plugin's Spigot page, so I'm gonna try that and see if it works.

**Comment by derklaro** [comment]
You have to use 4.7 for 1.17, 4.6.1 is only up to 1.16
