### ISSUE TITLE
ProtocolLib don't start on Paper 1.17

### ISSUE THREAD

**Issue by SofianeLasri** [dmulloy2/ProtocolLib#1244]
**Describe the bug**
ProtocolLib can't start on paper 1.17 build 16

**Version Info**
Can't run the dump command but here is the log: https://pastebin.com/jHZAfAa0

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
