### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by lcswolf** [dmulloy2/ProtocolLib#1245]
In the server log Minecraft spigot 1.16.5 I get this error 

[14:47:39] [ProtocolLib-StructureCompiler 0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @52cafe76
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@5a89bc0d[
      targetType=class net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]
      defaultFields={public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname=1, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d=3}
      subtypeCache={class net.minecraft.server.v1_16_R3.EnumProtocol=StructureModifier[fieldType=class net.minecraft.server.v1_16_R3.EnumProtocol, data=[private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]], class java.lang.String=StructureModifier[fieldType=class java.lang.String, data=[public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname]], int=StructureModifier[fieldType=int, data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@f9b438b[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@63a50e75
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MobHunting, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@79336af8
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4e0bf71d
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1b59724c
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50c401f4
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@5bb9d172
        reporter=com.comphenix.protocol.ProtocolLib$1@32c2c5be
        server=CraftServer{serverName=CraftBukkit,serverVersion=3096-Spigot-9fb885e-296df56,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@73fba2c6
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29f7a7f7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2c857383
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@53917978[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@9cff67ee=[com.comphenix.protocol.injector.StructureCache$1@7246e53f]}
      listenerLock=java.lang.Object@661a3c9f
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@610452b4
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@3986ad55
      reporter=com.comphenix.protocol.ProtocolLib$1@32c2c5be
      unknownPermGenBean=java.lang.Object@7cacd847
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    3096-Spigot-9fb885e-296df56 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
