### ISSUE TITLE
Unable to load ProtocolLib

### ISSUE THREAD

**Issue by Fran2985** [dmulloy2/ProtocolLib#1246]
**Bug description**
Error Cannot enable ProtocolLib. (java.lang.RuntimeException: Unable to inject channel futures.) occured in ProtocolLib

**To Reproduce**
1. Load plugin

**Screenshots**
![1](https://user-images.githubusercontent.com/69062690/122687200-973fe980-d1eb-11eb-86d9-32b3fc6832a7.PNG)
![2](https://user-images.githubusercontent.com/69062690/122687207-9c049d80-d1eb-11eb-82ce-5dbb58074475.PNG)

**Version Info**
1.17 papermc | ProtocolLib 4.6.0

**Comment by derklaro** [comment]
Please use the latest build from the ci for 1.17 compat

**Comment by Fran2985** [comment]
oh okay
