### ISSUE TITLE
How i can read channels of custom_payload packets

### ISSUE THREAD

**Issue by KaffinPX** [dmulloy2/ProtocolLib#1252]
How to read custom_payload channels to string?

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/threads/using-protocollib-for-custom-payload-packets.214663/

search on google

**Comment by dmulloy2** [comment]
You should be able to access the byte buffer in the packet as is done in the wrapper: https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayClientCustomPayload.java

As for reading it to a string, see this constructor: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#String-byte:A-

**Comment by KaffinPX** [comment]
Thanks, ill try asap

21 Haz 2021 Pzt 23:04 tarihinde Dan Mulloy ***@***.***> şunu
yazdı:

**Comment by KaffinPX** [comment]
Can u give me an example?

**Comment by KaffinPX** [comment]
Ok made it thanks lol
