### ISSUE TITLE
paper-1.16.5, 4.6.1-SNAPSHOT, WORLD_PARTICLES, "this.j is null" 

### ISSUE THREAD

**Issue by NicoStraube** [dmulloy2/ProtocolLib#1254]
Hi, I want to create a particle, but an exception is thrown instead and I'm getting kicked. There is no reference to my code in the exception, just from PLib. 

Here are some useful informations: 

- PaperMC is the latest release for 1.16.5 and PLib is running 4.6.1-SNAPSHOT-b505 (Using 4.6.0 didn't work neither.)

- The current dump [https://pastebin.com/5t7W2WEF](https://pastebin.com/5t7W2WEF)
- A snippet of the code I'm using [https://pastebin.com/RQwJM5A3](https://pastebin.com/RQwJM5A3)
- And the exceptions [https://pastebin.com/tMgkmhwR](https://pastebin.com/tMgkmhwR)

----- 22.06.2021
Hi, a quick update: I had tomatoes on my eyes and took the field with the index 12 for the coordinates, but it should be 2. After that was fixed, the error persisted.

Thank you, greetings
Nico Straube ~ StringArray

**Comment by NicoStraube** [comment]
Hi, a quick update: I had tomatoes on my eyes and took the field with the index 12 for the coordinates, but it should be 2. After that was fixed, the error persisted.

**Comment by dmulloy2** [comment]
Try using `packet.getNewParticles()` instead of `getParticles()`

**Comment by NicoStraube** [comment]
Cool, it's woking now. Thank you! :)
