### ISSUE TITLE
Async PacketListener

### ISSUE THREAD

**Issue by MrLolok** [dmulloy2/ProtocolLib#1256]
Is there a way to use PacketListeners in async? I tried the option ListenerOptions.ASYNC but when I receive a packet is on the main thread

**Comment by games647** [comment]
We also have `registerAsyncHandler` ([here](https://github.com/dmulloy2/ProtocolLib/blob/9b6603e2ebc358a02719a3bd2c500906d0606fd8/src/main/java/com/comphenix/protocol/AsynchronousManager.java#L45)). Remember to call `.start()`. AFAIK, this processes the packet async.

**Comment by MrLolok** [comment]
Thanks, I also tried this but I didn't called start()
