### ISSUE TITLE
ProtocolLIB Cannot compile structure

### ISSUE THREAD

**Issue by ariestortle** [dmulloy2/ProtocolLib#1257]
**Describe the bug**
[10:53:06 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

https://pastebin.com/5FU4yXuG

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
