### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

### ISSUE THREAD

**Issue by imJouU** [dmulloy2/ProtocolLib#1259]
**Describe the bug**
When I click on my custom item in hand with ItemJoin I got this error.
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @63000207
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@ecb7f5e[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a, public long net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.timestamp]
      defaultFields={private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2fdef123[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6bd3d021
        packetListeners=[PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], TRANSACTION[class=PacketPlayInTransaction, id=7], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2000bc81
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@75641650
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2d6bb636
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@584c2962
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ZProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@7d0d625e
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-778,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5824e408
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@515679ef
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@66710afb
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@b8a909d[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@92dc9080=[com.comphenix.protocol.injector.StructureCache$1@4b03b486]}
      listenerLock=java.lang.Object@29782508
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@47b0c40e
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@18e1ba1d
      reporter=com.comphenix.protocol.ProtocolLib$1@7d0d625e
      unknownPermGenBean=java.lang.Object@4e109a03
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-778 (MC: 1.16.5)

**To Reproduce**
I just click on my item in hand, no more.

**Screenshots**
![image](https://user-images.githubusercontent.com/68825157/122987659-73ed7980-d366-11eb-9620-7b1962fafa91.png)

**Version Info**
https://pastebin.com/gPi952y1

**Comment by CloudeLecaw** [comment]
[You may wnne try the latest jenkins Build 521 of Version 4.7](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)
