### ISSUE TITLE
Skins not working

### ISSUE THREAD

**Issue by xXAmyLouiseXx** [dmulloy2/ProtocolLib#126]
Hi I installed this plugin and my skins dont work :( im running 3.6.4 and spigot 1.8.8

**Comment by dmulloy2** [comment]
Just an FYI: triple-posting issues (especially those with extremely little information) doesn't help with visibility. Posting once on GitHub is enough.

Can you provide some more information other than they don't work? What do players look like? What plugins do you have that use ProtocolLib?

**Comment by xXAmyLouiseXx** [comment]
I fixed it by deleting the config
