### ISSUE TITLE
 INTERNAL ERROR: Cannot compile structure.

### ISSUE THREAD

**Issue by typecek123** [dmulloy2/ProtocolLib#1260]
https://pastebin.com/kG999K0W

Protocollib ver: latest

**Comment by happylizard20** [comment]
I have the same issue please fix it

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
