### ISSUE TITLE
getProtocolManager null 1.17 build.

### ISSUE THREAD

**Issue by TheLimeGlass** [dmulloy2/ProtocolLib#1265]
**Describe the bug**
ProtocolLibrary.getProtocolManager() returns null.

**To Reproduce**
1. Use ProtocolLibrary.getProtocolManager() on plugin onEnable()
2. See error when trying to add a listener because ProtocolLibrary.getProtocolManager() is null.
`Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null`

Yes the plugin has ProtocolLib as a dependency and loads after ProtocolLib.

**Expected behavior**
ProtocolLib setup the protocol manager.

**Version Info**
Paper-"28aacb4" (MC: 1.17) 
ProtocolLib v4.7.0-SNAPSHOT-b521
https://pastebin.com/raw/xJm1G3Fd

**Comment by ham1255** [comment]
add scope provided in depends at your pom file
