### ISSUE TITLE
[ProtocolLib-StructureCompiler 0/INFO]: Error Cannot compile structure. Disabing compiler

### ISSUE THREAD

**Issue by HarshitMittali** [dmulloy2/ProtocolLib#1267]
**Describe the bug**

https://pastebin.com/fYXB2eP8

1. I really do not know

**Expected behavior**
Working without erros

**Version Info**
https://pastebin.com/sui2zqVA

**Additional context**
Happened suddenly after i restarted the server one day

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
