### ISSUE TITLE
Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by Aladalar** [dmulloy2/ProtocolLib#127]
Hi, I have this problem: http://pastebin.com/31cA81Th

It spam console and even mc chat...

**Comment by dmulloy2** [comment]
What version of Cauldron are you using? I tried googling it but I couldn't find anything.

**Comment by Aladalar** [comment]
I'm using Cauldron 1.7.10 dev ver 1334

**Comment by dmulloy2** [comment]
Is it the official MCPC Cauldron or a fork of it?

**Comment by Aladalar** [comment]
I'm sorry cant tell you this becouse IDont know origin if cauldron, I just have packs of plugins to deal with that... I ts really important... And why?

**Comment by dmulloy2** [comment]
This is an issue specific to your version of Cauldron, so it's important.

**Comment by Aladalar** [comment]
Ok... I ask him and he says it downloaded it from git hub, than I think is forked one

**Comment by dmulloy2** [comment]
Is this it? https://github.com/linkinkov/Cauldron-Reloaded

**Comment by Aladalar** [comment]
http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10/ this is link which send me
