### ISSUE TITLE
1.17 get type of PacketPlayInUseEntity

### ISSUE THREAD

**Issue by Photon-GitHub** [dmulloy2/ProtocolLib#1270]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
In PacketPlayInUseEntity I was able to get the action type enum by using handle.getEntityUseActions().read(0);
On 1.17 this throws a FieldAccessException: No field with type net.minecraft.network.protocol.game.PacketPlayInUseEntity$b exists in class PacketPlayInUseEntity.

Given that according to https://wiki.vg/Protocol#Interact_Entity there should still be the enum in 1.17, I would like to know whether this is a bug or I need to use a different method.

**API method(s) used**
handle.getEntityUseActions().read(0);

**Expected behavior**
Return the enum as it does on versions prior to 1.17

**Code**
handle.getEntityUseActions().read(0);

**Comment by Photon-GitHub** [comment]
I was able to fix the issue by using

handle.getEnumEntityUseActions().read(0).getAction();

I am not sure if that change was intentional but maybe make the old version return that for backwards compatibility?

**Comment by Chasewhip8** [comment]
The fix below does work, running into getHands() is not working correctly on this packet, the data is there in the structured modified.

**Comment by dmulloy2** [comment]
Looks like the enum entity use actions are slightly different; interact has a hand field and interact_at has both a hand and position. I could add backwards compatibility pretty easily, but it might lead to some weird behavior.

**Comment by Chasewhip8** [comment]
Mmm, backward compatibility there would be simple because the hand is still available in the same packets as last time, weird how the wiki missed this change, do you know what the position is for?

**Comment by dmulloy2** [comment]
it's possible it's not sent; i know the wiki bases it off of the data that's actually serialized
