### ISSUE TITLE
Non-whitelisted players joining a whitelisted server throws a debug warning

### ISSUE THREAD

**Issue by bigfinfrank** [dmulloy2/ProtocolLib#1271]
**Describe the bug**
A debug warning gets thrown when a player who is not whitelisted tries to join a whitelisted server.

**To Reproduce**
1. Turn on ProtocolLib's debug logging
2. Start up a server with ProtocolLib
3. Turn on the vanilla whitelist **without adding yourself**
4. Attempt to join the server
5. Check console

**Expected behavior**
No warning in console.

**Screenshots**
N/A

**Version Info**
https://pastebin.com/uTNWtg99

**Additional context**
A full server log is available [here](https://mclo.gs/bZTqzxp). I'm aware this isn't a breaking bug although it may indicative of an underlying issue that could cause problems elsewhere.

**Comment by dmulloy2** [comment]
Good catch! Forgot to change that in the 1.17 update
