### ISSUE TITLE
ProtocolLIb Not enabling because of an internal error

### ISSUE THREAD

**Issue by NeonLuke** [dmulloy2/ProtocolLib#1277]
Debug paste link: https://pastebin.com/8YbsPEiv

Description and relevant errors:
ProtocolLib Won't load up On the 1.17 spigot server. also cant use /protocol dump command since it doesn't let me

**Comment by crafter23456** [comment]
> Version:
> ProtocolLib v4.6.0
update to latest dev build https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/artifact/target/ProtocolLib.jar
