### ISSUE TITLE
nullpointer exception in thread x (x can be anything)

### ISSUE THREAD

**Issue by CillerYoutube** [dmulloy2/ProtocolLib#1278]
Having some troubles and I'm getting this issue when running viaversion. Please let me know fixes!

**Comment by dmulloy2** [comment]
Can you provide the stack traces?

**Comment by CillerYoutube** [comment]
> Can you provide the stack traces?

There is none, that is the issue.

**Comment by dmulloy2** [comment]
Can't really do anything without a stack trace. Maybe try turning debug logging on in your server properties?
