### ISSUE TITLE
FieldAccessException with packet GAME_STATE_CHANGE

### ISSUE THREAD

**Issue by PrinceBunBun981** [dmulloy2/ProtocolLib#1279]
**Describe the bug**
When attempting to set the bytes for the packet `GAME_STATE_CHANGE` it returns a FieldAccessException.

I've tried using:
```
PacketContainer packet = new PacketContainer(PacketType.Play.Server.GAME_STATE_CHANGE);
packet.getBytes().write(0, (byte) 4);
packet.getFloat().write(0, 1F);
```
To set the bytes for the GameState.

**Screenshots**
![image](https://user-images.githubusercontent.com/29809309/123560694-d6cd7f00-d771-11eb-8440-7b5c84da004e.png)
![image](https://user-images.githubusercontent.com/29809309/123560684-c3baaf00-d771-11eb-9f93-60064bf55a49.png)

**Version Info**
ProtocolLib build 524
Dump: https://paste.helpch.at/epotetaqis.pl

**Comment by dmulloy2** [comment]
Looks like Mojang made an internal pseudo-enum for this. The packet is encoded to/from a byte, which is why it's represented that way on wiki.vg. I'll look into a good way to read those

**Comment by dmulloy2** [comment]
Actually you should be able to access it with `packet.getGameStateIDs()`

**Comment by PrinceBunBun981** [comment]
> Actually you should be able to access it with `packet.getGameStateIDs()`

How exactly would it be done with that?

**Comment by dmulloy2** [comment]
`int stateId packet.getGameStateIDs().read(0);`
`packet.getGameStateIDs().write(0, stateId);`
