### ISSUE TITLE
[11:56:58 ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by MusicMakerOwO** [dmulloy2/ProtocolLib#1282]
**Describe the bug**
Start the Minecraft server with Paper (paper 1.17 build #55). A repeated error will be thrown everytime (only thrown on server startup) which reads: "[11:56:58 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib."

**To Reproduce**
1. Create a Minecraft server
2. Start the server with Paper (paper-1.17-55.jar)
3. The error, and stack trace, will appear shortly after starting

**Expected behavior**
Start the server, no error. I'm not entirely sure what this is supposed to do, I just know there's an error .-.

**Screenshots**
https://drive.google.com/file/d/1xWe05NrmZ7SiOEzdUojDYwc5pczfAvl2/view?usp=sharing

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
Command errored out - [https://pastebin.com/uYghEXrh](url)

**Additional context**

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
