### ISSUE TITLE
Error Cannot compile structure.

### ISSUE THREAD

**Issue by cjdheffron** [dmulloy2/ProtocolLib#1285]
Debug paste link:
https://pastebin.com/fKtfSz6D

Description and relevant errors:

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
