### ISSUE TITLE
Players instanly kicked on join 1.17 

### ISSUE THREAD

**Issue by ImHumbug** [dmulloy2/ProtocolLib#1287]
**Describe the bug**
The bug have a pretty random behaviour so I can't find an exact way to reproduce it but is definetly protocolib fault, tested multipled times with and without. Players join and get instantly kicked wit the following error: 

"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 54out of bounds for lenght 5"

Using the server.properties debug tool I found these messages at the moment of players getting kicked:
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer

Also I found this stracktace in one of the kicks:
https://paste.gg/p/anonymous/27c91c113f1d44f9a56acf8a3b495837

**To Reproduce**
Just joining the server, not all users have the problem but most of them yes. I couldn't find any common pattern between people with the issue and the people that can join.

**Expected behavior**
Not getting kicked when joining.

**Screenshots**

**Version Info**
https://paste.gg/p/anonymous/3033f64882044e8984da23e1cec3b712

**Additional context**
git-paper-63 1.17.

**Comment by dmulloy2** [comment]
Does this happen with Paper or Spigot? Wondering if it's a Tuinity thing

**Comment by ImHumbug** [comment]
> Does this happen with Paper or Spigot? Wondering if it's a Tuinity thing

Yes, paper aswell

**Comment by dmulloy2** [comment]
which plugins are you using with PL? the dump shows no listeners

**Comment by ImHumbug** [comment]
PremiumVanish, MyCommands, AdvancedEnchantments, PremiumVanish, McMmmoAction, ServerListPlus, Quickshop

**Comment by bloodycoffin** [comment]
hi ImHumbug, my problem was solved by putting the "DisablePush" in the PremiumVanish config.yml to "false"
Maybe this also solves your problem?

**Comment by dmulloy2** [comment]
Sounds like a PremiumVanish issue then
