### ISSUE TITLE
Create Use-Totem Packet

### ISSUE THREAD

**Issue by JamesWHomer** [dmulloy2/ProtocolLib#1288]
How would I create a use totem packet? I'm a newb to protocollib (tonight) and I need to know how I would send a packet to a player that shows a visual of a totem being used (But not actually being used). How would I do this?

Thanks!

**Comment by dmulloy2** [comment]
A good place to start is the protocol wiki: https://wiki.vg/Protocol

Once you find your packet, you can send it with ProtocolLib: https://github.com/dmulloy2/ProtocolLib/wiki/Packet-listeners-and-adapters
