### ISSUE TITLE
BlockPosition structure modifier too slow

### ISSUE THREAD

**Issue by ItsHarry** [dmulloy2/ProtocolLib#129]
Reading BlockPositions (from for example SIGN_UPDATE and BLOCK_CHANGE packets) seems much slower than reading other types. Any chance this could be optimized?

See screenshot of CPU profiler below:
![screenshot_3](https://cloud.githubusercontent.com/assets/914835/11164054/9e95b758-8ae5-11e5-9e27-ec51911607e0.png)

The call to sendBlockChange() above the highlighted one is also very slow, because it sends a BLOCK_CHANGE packet, and my plugin also reads BlockPosition for that packet as well.

This is hurting the performance of my server, but reading BlockPositions is unfortunately necessary for my plugin to function correctly.

Or should I be looking into using an asynchronous listener?

**Comment by ItsHarry** [comment]
Okay, well I guess the comment on line StructureCompiler:178 explains a lot:

```java
// This causes a ton of lag and doesn't seem to work
```

**Comment by ItsHarry** [comment]
Okay, after some reading, I see now from Issue #124 that the class loader was disabled in later builds. I'm still using the latest recommended build, hence why I did not notice. I will try to see if the dev build fixes this issue.

**Comment by ItsHarry** [comment]
Well, my TPS just went from 8 to 20. That made quite the difference. I think this update is worth uploading to BukkitDev and Spigot in my opinion. =)

**Comment by dmulloy2** [comment]
I'm going to release it soon, I'd just like to get a [few more fixes](https://github.com/dmulloy2/ProtocolLib/milestones/3.6.5) in beforehand.

**Comment by ItsHarry** [comment]
Ah okay, thanks
