### ISSUE TITLE
Some Random Bug

### ISSUE THREAD

**Issue by Cornona** [dmulloy2/ProtocolLib#1290]
# Stack Trace
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7577278d
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@728babf3[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutChat
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a, public net.kyori.adventure.text.Component net.minecraft.server.v1_16_R3.PacketPlayOutChat.adventure$message, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]
      defaultFields={public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components=2, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b=3, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c=4}
      subtypeCache={interface net.minecraft.server.v1_16_R3.IChatBaseComponent=StructureModifier[fieldType=interface net.minecraft.server.v1_16_R3.IChatBaseComponent, data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a]], class java.util.UUID=StructureModifier[fieldType=class java.util.UUID, data=[private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@21a923c7[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@e52d032
        packetListeners=[PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=PacketPlayOutChat, id=14]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=MONITOR, packets=[OPEN_WINDOW_MERCHANT[class=PacketPlayOutOpenWindowMerchant, id=38]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=47]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@63888a3
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3e159190
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@564a2a8e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4e81b335
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib (4).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@c3e57d6
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-777,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@19ac99d2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@696515fd
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@fba60d9
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@64f5004d[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@dc40f704=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@232d27ce], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@384205d7=[com.comphenix.protocol.injector.StructureCache$1@62a604ab], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@e933b7e4=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@3ec60c8e]}
      listenerLock=java.lang.Object@727d9473
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@38a4dea5
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@6af51646
      reporter=com.comphenix.protocol.ProtocolLib$1@c3e57d6
      unknownPermGenBean=java.lang.Object@6459c5ea
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-777 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
