### ISSUE TITLE
No temporary players

### ISSUE THREAD

**Issue by MatsG23** [dmulloy2/ProtocolLib#1292]
When I join the Minecraft server from a Bedrock device via [Geyser](https://github.com/GeyserMC/Geyser) and [floodgate](https://github.com/GeyserMC/Floodgate), I find this error in the console:
` The method hasPermission is not supported for temporary players. (thrown in a PacketAdapter#onPacketSending method from my plugin)`

Is it possible to make temporary players more like normal players? PacketInterceptors are like EventListeners with wider possibilities and I'd really like to use functions like `Player#hasPermission` within.
**Related to [225](https://github.com/dmulloy2/ProtocolLib/issues/225) but this was 5 years ago already**

I'm using the development version of ProtocolLib already.

**Comment by dmulloy2** [comment]
We pretty much only use temporary players when they're absolutely required as-is. There have been attempts in the past to expand this, but it didn't really work.

**Comment by LockedThread** [comment]
This is still happening.

**Comment by MatsG23** [comment]
> This is still happening.

Did you even read what the project's maintainer responded on this issue? 
**Closing this now.**
