### ISSUE TITLE
ProtocoILib Bug Report

### ISSUE THREAD

**Issue by E3Anr** [dmulloy2/ProtocolLib#1293]
Error message shows up whenever i start server

[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

[ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @518eed6f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@5c6794b2[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2065014d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@278f04ab
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@472dc6ec
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1a791973
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@129e0c18
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d6bf8bc
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@36b87222
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-670,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4618ea11
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@627afd9d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@605c607b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@758bd447[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@df4d1305=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@899aee5], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@882abca1=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@3dba3c7e]}
      listenerLock=java.lang.Object@3e66dc0a
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@15640e6d
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@50cf74a2
      reporter=com.comphenix.protocol.ProtocolLib$1@36b87222
      unknownPermGenBean=java.lang.Object@3c7afb09
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-670 (MC: 1.16.5)

**Expected behavior**
Not for this to show up

**Version Info**
[dump-2021-06-30_19.45.05.txt](https://github.com/dmulloy2/ProtocolLib/files/6744502/dump-2021-06-30_19.45.05.txt)

**Comment by tienthanh23423** [comment]
Agreed. Looks like the newest version made it. I also have this error. Gonna change to the older version.

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
