### ISSUE TITLE
ProtocolLib Error

### ISSUE THREAD

**Issue by Olzie-12** [dmulloy2/ProtocolLib#1294]
**Unexpected behavior**
An error pops up into the console when accessing the ProtocolLibrary API (I'm not having the issue, one of my clients are)

**Version Info**
https://haste.olziedev.com/jigoxahahu

**Additional context**
Here is the error that is thrown. https://haste.olziedev.com/ovexoxihuy.apache 
Here is the line of code which is causing the error.
![image](https://user-images.githubusercontent.com/45238401/124147340-86626400-da86-11eb-8fd5-4a316050be82.png)

**Comment by Olzie-12** [comment]
It could also be an issue with Paper too.

**Comment by dmulloy2** [comment]
PL isn't in the stack anywhere. maybe the jar is corrupt?

**Comment by Olzie-12** [comment]
Yeah but multiple people are having this issue only with ProtocolLib on 1.17 with paper
