### ISSUE TITLE
1.17 Server Load Error

### ISSUE THREAD

**Issue by Lucky7s** [dmulloy2/ProtocolLib#1297]
**Describe the bug**
Currently Getting this error on MC 1.17 on server boot.

**To Reproduce**
1. Load Server
2. See error

**Version Info**
ProtocolLib v4.6.1-SNAPSHOT-b505
Spigot: 3164-Spigot-f773da8-b069f22 (MC: 1.17)

[https://pastebin.com/jFTq8q5S](https://pastebin.com/jFTq8q5S)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
