### ISSUE TITLE
1.17 with 4.6.1 and Paper

### ISSUE THREAD

**Issue by Nostigo** [dmulloy2/ProtocolLib#1300]
Stack Trace:
03.07 16:16:49 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
03.07 16:16:49 [Server] INFO fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
03.07 16:16:49 [Server] INFO methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
03.07 16:16:49 [Server] INFO constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
03.07 16:16:49 [Server] INFO }}
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
03.07 16:16:49 [Server] INFO at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
03.07 16:16:49 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
03.07 16:16:49 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:275)
03.07 16:16:49 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
03.07 16:16:49 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
03.07 16:16:49 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:831)
03.07 16:16:49 [Server] INFO Dump:
03.07 16:16:49 [Server] INFO Parameters: 
03.07 16:16:49 [Server] INFO [NULL]
03.07 16:16:49 [Server] INFO Sender:
03.07 16:16:50 [Multicraft] Skipped 55 lines due to rate limit (30/s)

**Comment by noyarth** [comment]
Hey ! You can find the last version here : https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
It works with 1.17
