### ISSUE TITLE
1.16.5 Dumping Errors when spawning in

### ISSUE THREAD

**Issue by RicePerson** [dmulloy2/ProtocolLib#1304]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:
https://pastebin.com/uzfNxqXb
Description and relevant errors:
At one point, an Enderman got stuck in a portal, and when the server restarted, it disappeared, so that may be part of it? I dont know

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
