### ISSUE TITLE
Update ProtocolLib to 1.17 in Aternos

### ISSUE THREAD

**Issue by GianLucky08** [dmulloy2/ProtocolLib#1309]
Hello, I have an Aternos server and the ProtocolLib plugin is not updated for 1.17 in Aternos and neither are the dev builds in Aternos

When I try to download version 4.6.0 in Aternos it gives me a lot of errors, because this version which is the last one found in Aternos is not updated to 1.17

My request is to add the ProtocolLib for 1.17 in Aternos

*Aternos (aternos.org) is a free server host*

@dmulloy2

**Comment by Day-Hawk** [comment]
This is not the task of the developer, contact Aternos directly
