### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Dooleylabs** [dmulloy2/ProtocolLib#131]
25.11 21:19:22 [Server] INFO Post-enable finished.
25.11 21:19:21 [Server] INFO ]
25.11 21:19:21 [Server] INFO d=STATUS
25.11 21:19:21 [Server] INFO port=**REMOVED**
25.11 21:19:21 [Server] INFO hostname=**REMOVED**
25.11 21:19:21 [Server] INFO a=47
25.11 21:19:21 [Server] INFO net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol@83b19eb[
25.11 21:19:21 [Server] ERROR Parameters: 
25.11 21:19:21 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
25.11 21:19:21 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [custom18.jar:git-Spigot-db6de12-18fbb24]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:546) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:297) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:332) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:607) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:640) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:61) ~[ServerListPlusBukkit-%23805.jar:?]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.events.PacketContainer.getProtocols(PacketContainer.java:701) ~[ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:455) ~[ProtocolLib-%23209.jar:3.6.5-SNAPSHOT-b209]
25.11 21:19:21 [Server] INFO at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_45]
25.11 21:19:21 [Server] INFO java.lang.NullPointerException
25.11 21:19:21 [Server] ERROR Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
25.11 21:19:21 [Server] INFO Post-enable running...
25.11 21:19:21 [Server] INFO Using epoll channel type
25.11 21:19:21 [Server] INFO RCON running on **REMOVED**
25.11 21:19:21 [Server] INFO Query running on **REMOVED**
25.11 21:19:21 [Server] INFO Starting remote control listener
25.11 21:19:21 [Server] INFO Starting GS4 status listener

**Comment by dmulloy2** [comment]
Took me a minute to figure out what the error was, seriously people use pastebin.

This shouldn't happen under normal circumstances. Maybe its because you're using a custom jar?

**Comment by Dooleylabs** [comment]
Sorry about not using pastebin (xD), but I found out it was an error with our server host. This plugin is written beautifully, and so it only throws an error when our node throws one first. I'm leaving our host soon to host it on my own, but this isn't an issue with ProtocolLib. Also, after our server host updated our instance to Java 8, they renamed our Spigot1.8.8.jar file to custom18.jar for some ungodly reason.
