### ISSUE TITLE
Sender UUID is being stripped from PacketPlayOutChat packet

### ISSUE THREAD

**Issue by Artuto** [dmulloy2/ProtocolLib#1310]
**Describe the bug**
ProtocolLib is stripping the `sender` UUID from server-sent chat packets. This is important because it prevents chat formatting plugins from using Minecraft's 1.16 social interaction menu where players can ignore other players.

**To Reproduce**
- Using [pakkit ](https://github.com/Heath123/pakkit) (or something similar) to see the packet content:
   1. Download the test plugin from [here](https://cdn.discordapp.com/attachments/323954859713888256/861815479377985556/protocolexample-1.0-SNAPSHOT.jar) (source is available [here](https://gist.github.com/Artuto/46a0b0f1a3c74411b60c99eb21ab3d68#file-protocolexample-java))
   2. Join the server and send a chat message.
   3. Observe on the pakkit window the structure of the clientbound server chat packet and notice the sender UUID is 0 (even though it was set on the code);
![image](https://user-images.githubusercontent.com/9273973/124540284-b726fe00-dde4-11eb-8ebe-689c2541f34b.png)
   4. Use /reload to make the plugin remove the ProtocolLib packet listener.
   5. Send the chat message again and look at pakkit again (the UUID is present!):
![image](https://user-images.githubusercontent.com/9273973/124540315-ce65eb80-dde4-11eb-9ce6-540417079f65.png)

- Running another Minecraft instance and ignoring the player that will send the message (using "P")
Notice how after you do /reload the message will get properly filtered.

**Expected behavior**
The set sender UUID should be present in the packet.

**Version Info**
[dump-2021-07-05_23.04.52.txt](https://gist.github.com/Artuto/46a0b0f1a3c74411b60c99eb21ab3d68#file-dump-txt)

**Comment by Artuto** [comment]
Bump

**Comment by dmulloy2** [comment]
Thank you for looking into this! It's refreshing to see a real issue in the sea of "i refuse to read the description and get the right version for my server" issues haha

I think I have a fix in mind for this
