### ISSUE TITLE
ERROR CONSOLE

### ISSUE THREAD

**Issue by MaxiiARG** [dmulloy2/ProtocolLib#1314]
6.07 16:51:44 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
06.07 16:51:44 [Server] INFO If this problem hasn't already been reported, please open a ticket
06.07 16:51:44 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
06.07 16:51:44 [Server] INFO Stack Trace:
06.07 16:51:44 [Server] INFO java.lang.RuntimeException: Error occured while instancing generated class.
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:237)
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:312)
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
06.07 16:51:44 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
06.07 16:51:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
06.07 16:51:44 [Server] INFO at net.minecraft.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:84)
06.07 16:51:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)

**Comment by Redev837** [comment]
same problem

**Comment by IllusionTheDev** [comment]
Seems like you ran out of RAM while reading data.

**Comment by Xotwot** [comment]
same problem

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).
