### ISSUE TITLE
Not starting up

### ISSUE THREAD

**Issue by MasterDev16** [dmulloy2/ProtocolLib#1318]
**Describe the bug**
Does not start on 1.17.1

**To Reproduce**
1. Install paper 1.17.1
2. Install protocollib
3. See an error

**Expected behavior**
I wanted it to enable

**Screenshots**
See attached pastebin

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
4.6.0

**Additional context**
https://pastebin.com/iX4suys0

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
