### ISSUE TITLE
clients crash when joining server

### ISSUE THREAD

**Issue by SilBoydens** [dmulloy2/ProtocolLib#132]
when we join our server, the client crash and the crashreports sad something about trying to turn a intiger into a byte and something about a whitherskull with a horse riding on it with location (x=0,y=154,z=0) where we haven't come for a long time, our spawn is arround x~1000 z~-4000. we kinde need it to let other plugins works so I hope it will be fixed soon
[crash-protocollib-client.txt](https://github.com/dmulloy2/ProtocolLib/files/46423/crash-protocollib-client.txt)

**Comment by dmulloy2** [comment]
I don't see ProtocolLib anywhere in that crash. Is there something server-side that mentions it?

**Comment by SilBoydens** [comment]
the crash only happens when protocollib is installed, otherwise there is no crash, after some experimenting i found that when we startour server with protocollib and disabling protocollib(using plugman) before joining the server, we don't crash but some function of the plugins using protocollib won't work. if we start our server without protocollib, join our server and than load protocollib(again using plugman) we can use all the plugins that use protocollib but when someone lost connection and have to join again, he crash if we don't dissable protocollib. the server never gives a error when the clients crash. the file in the attachment is a list of the other plugins, with those it work but when we add protocollib, we can't join anymore.
![list of plugins](https://cloud.githubusercontent.com/assets/9578499/11460208/0f42a272-96e9-11e5-8774-56da5a7016a2.JPG)

**Comment by dmulloy2** [comment]
I can't really help you without an error. Try enabling debug settings (debug=true in the server.properties, debug: true in the PL config.yml).

**Comment by SilBoydens** [comment]
I made a new server and copy all the plugins to it, i started it try to join it and crashed.
after unloading protocollib(time in server log: 17:07:17) i was able to join that server.

https://www.dropbox.com/sh/bp49yzraeqom0ks/AAD1LgW9gEqv_wz6rxveGJ8aa?dl=0
here is the server and client log and the crash of the client that came in the minecraft launcher, in the server log I can't find a error of protocollib in the server log.
(I recompile craftbukkit before doing all this so it's the latest version of craftbukkit)
in case you need it here is the server for testing: https://www.dropbox.com/s/s2ou6q52wnrhwma/protocollib%20temp%20server.zip?dl=0

**Comment by themazim** [comment]
Seems you are using an old version of DisguiseCraft (R2 instead of R3) 

Try the newest build: http://build.yu8.me:8080/job/DisguiseCraft/116/

**Comment by SilBoydens** [comment]
+themazin thanks for telling me that I had to update that plugin, to bad the same crash happen again.

**Comment by themazim** [comment]
holoapi seems to be outdated too.

you have version 1.2.3 which only support 1.7.x server

>HoloAPI v1.2.3 is known to be compatible with the following server versions:
>
>CB 1.6.4
>CB 1.7.2/1.7.4
>CB 1.7.5
>MCPC+ 1.6

**Comment by themazim** [comment]
I don't think this is an issue with protocollib. Seems your plugins are having issues finding several classes, This indicates some plugins are not up to date.

**Comment by SilBoydens** [comment]
"This indicates some plugins are not up to date." a month ago is started creating this server and I download all my plugins then, if they are not up to date it's either an older version that was on bukkitdev or on curse, or they where update in the last month. thanks for saying that their where more outdated plugins, i will now try a plugins called 'ultimate plugin updater'. after it has updated all my plugins i will tell if it worked or not

**Comment by SilBoydens** [comment]
to be honnest, i didn'tt expected that so many plugins where outdated, but updating them all didn't work. the specifix error come when the client try to convert intiger to byte 
(java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte)
this error only come when joining the server with protocollib enabled

**Comment by dmulloy2** [comment]
More than likely this is an issue with a plugin that uses ProtocolLib. A few things you can try:

- Remove DisguiseCraft (it's pretty broken, plus you already have LibsDisguises)
- Remove HoloAPI and Holographic (these are most likely the source)

Personally, I recommend [HolographicDisplays](http://dev.bukkit.org/bukkit-plugins/holographic-displays/), it's pretty solid and updated regularly.
