### ISSUE TITLE
I got a bug

### ISSUE THREAD

**Issue by blackhole8753** [dmulloy2/ProtocolLib#1321]
[06:58:37 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7c147cda
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@79ed9011[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5d8e344d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@652f49c8
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@70572064
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5f21855d
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7321eea8
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6cdf980d
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@761aa37a
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-744,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1a3da914
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65f41ede
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@55b04036
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@55dffc08[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@5355f077=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@748c8ca6], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@43e2fdb8=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@314b7e07]}
      listenerLock=java.lang.Object@66ad39e8
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@4c38b689
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@5c41fa14
      reporter=com.comphenix.protocol.ProtocolLib$1@761aa37a
      unknownPermGenBean=java.lang.Object@36900cdd
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-744 (MC: 1.16.5)

**Comment by JNachow** [comment]
same as https://github.com/dmulloy2/ProtocolLib/issues/1319

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
