### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AccioAce** [dmulloy2/ProtocolLib#1322]
**Describe the bug**
When every I join the server this message pops out of no where every once a while: https://gyazo.com/d5ebb580cb79ea185cdaa428665452cb

Here is the console error: https://bin.birdflop.com/etehobodic.rb

**Expected behavior**
I expect it to work fine, without any console error.

**Screenshots**
Above ^^

**Version Info**
Paper 1.17.1

**Comment by Brokkonaut** [comment]
Update PremiumVanish, that packed changed in 1.17.1.

But the message to the client is somewhat strange..
