### ISSUE TITLE
java.lang.IllegalArgumentException - Purpur-1260 1.17.1

### ISSUE THREAD

**Issue by Stixil** [dmulloy2/ProtocolLib#1323]
**Describe the bug**
java.lang.IllegalArgumentException on startup of Purpur 1.17.1 server.
https://mcpaste.io/febd19f15b13b6d6

Server Version Info:
[04:36:08 INFO]: Checking version, please wait...
[04:36:09 INFO]: This server is running Purpur version git-Purpur-1260 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 444413b on HEAD)

**To Reproduce**
1. Install ProtocolLib on 1.17.1 server (Purpur-1260)
2. Observe console on startup

**Expected behavior**
Expected to load without issues

**Version Info**
https://mcpaste.io/cb1f0489a68c8605

**Comment by yannicklamprecht** [comment]
Yeah Protocollib is not updated to 1.17.1 at the moment.

**Comment by dmulloy2** [comment]
That specific error is fixed in the dev builds: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
