### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

### ISSUE THREAD

**Issue by heraqu** [dmulloy2/ProtocolLib#1324]
Latest version
java 16

![obraz](https://user-images.githubusercontent.com/46068203/124973116-6bb26100-e02b-11eb-8a99-80af2310e4a0.png)

**Comment by heraqu** [comment]
I downloaded latest dev builds https://ci.dmulloy2.net/job/ProtocolLib/ and have the same problem

**Comment by Samaine** [comment]
Can confirm. Experiencing this error.

**Comment by Brokkonaut** [comment]
You have to use an older java version (before java 16), use the start parameter "--illegal-access=permit" for your jvm or try the v4.7.0-SNAPSHOT builds (don't know if the last option will work with Minecraft < 1.17)

**Comment by dmulloy2** [comment]
That screenshot shows your version is 4.6.0, which isn't a dev build

**Comment by braceyourself07** [comment]
I'm using 4.6.1 from https://ci.dmulloy2.net/job/ProtocolLib/505/ and I'm running Tuinity 1.16.5 on Java 16 and I don't get this error, so maybe give that a try.
