### ISSUE TITLE
Console Error ProtocolLib 1.17

### ISSUE THREAD

**Issue by AbhayRojas** [dmulloy2/ProtocolLib#1325]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [+] You're using the latest build for your server version
- [+] This isn't an issue caused by another plugin
- [+] You've checked for duplicate issues
- [+] You didn't use `/reload`

Error paste:
https://pastebin.com/qhHGp6Gx
Description and relevant errors:

I was trying to update it but I got an console error

**Comment by Brokkonaut** [comment]
You should currently try the latest snapshot from here for 1.17.1: https://ci.dmulloy2.net/job/ProtocolLib/ 

 ProtocolLib v4.6.0 does not work with Minecraft 1.17.1
