### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by AccioAce** [dmulloy2/ProtocolLib#1328]
**Describe the bug**
This error keeps pop up in-game and console: https://gyazo.com/60edbd70e91e12254ceb292cbba24e57
I am using the latest updated protocolib.

**To Reproduce**

**Expected behavior**
That the error doesn't pop up. 

**Screenshots**
Screenshot is above ^^

**Version Info**
https://bin.birdflop.com/ihaqucefey.kotlin

**Comment by sketrick** [comment]
+1 Have the same spam in console.

**Comment by dmulloy2** [comment]
Should be fixed in the latest LD dev builds
