### ISSUE TITLE
massive error on console, it says to report here

### ISSUE THREAD

**Issue by oOBetaOo** [dmulloy2/ProtocolLib#1329]
**Version Info**
Airplane 1.16.5

Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4f8151a0
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@53717bb2[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@17f15155[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4f280ae
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], SET_SLOT[class=PacketPlayOutSetSlot, id=21], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5c86d769
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3a39800a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@275f15e1
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@37b80654
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5defb255
        server=CraftServer{serverName=Airplane,serverVersion=git-Airplane-8,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@740fb8ba
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3643be9
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@14d75d8e
         hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@484ba2d1[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@4e0f4648=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@7e99bfd7], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@f7225328=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@5c00689e]}
      listenerLock=java.lang.Object@729565bd
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@67dd1c14
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@5489703f
      reporter=com.comphenix.protocol.ProtocolLib$1@5defb255
      unknownPermGenBean=java.lang.Object@b12a6a8
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Airplane-8 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
