### ISSUE TITLE
Server offline in Server Lists

### ISSUE THREAD

**Issue by brandonHD** [dmulloy2/ProtocolLib#133]
I have a few plugins on my server that require Protocol Lib, but whenever we add it, either votifier stops working or we go offline in server lists such as Minecraft Server List. If you know anyway to fix this, or can update so this doesn't happen, I'd really like it!

Thanks,
Brandon

**Comment by themazim** [comment]
Probably not a protocollib error. The used plugins are probably broken. If you still think it's protocollib related please provide more information (logs, exceptions, used plugins etc)

**Comment by brandonHD** [comment]
It only happens when we add Protocol Lib, before we add plugins that require it, nothing comes up in console, but here is a full list of plugins:
- AdminChatChannel
- AdvancedBan
- AntiAdvertizer
- BetterShops
- BiomeTP
- BringBackTheEnd
- Category Warps
- Chairs
- ChatMaster
- ChatWarn
- Citizens
- CommandSpy
- CoreProtect
- CustomDeathMessages
- EnjinMinecraftPlugin
- Essentials
- EssentialsChat
- EssentialsGroupManager
- EssentialsSpawn
- EZRanksLite
- GAListener
- GriefPrevention
- GroupManagerPromote
- MagicSpells
- MakeYourOwnCommands
- Multiverse
- NetherKiller
- PlayerJoinMessages
- PlayerVaults
- PvPManager
- ServerListPlus (Disabled everything as of now that requires ProtocolLib)
- Signs
- SilkSpawners
- SimpleBroadcast
- SuperVanish
- Tablist
- TicketMaster
- Vault
- Votifier
- WarpPortals
- WatchDog
- WorldEdit
- WorldGuard

**Comment by dmulloy2** [comment]
This actually was a ProtocolLib error for a change. It was fixed fairly recently, so grab the latest development build and you should be good to go.

**Comment by brandonHD** [comment]
Ok! Thank you so much!
