### ISSUE TITLE
List converter not compatible with singleton lists

### ISSUE THREAD

**Issue by games647** [dmulloy2/ProtocolLib#1331]
Original ticket at: https://github.com/games647/ChangeSkin/issues/227

**Describe the bug**
List converter at 
https://github.com/dmulloy2/ProtocolLib/blob/8175443da0f639d4d41c41c85ffa3a3ce2b52ffc/src/main/java/com/comphenix/protocol/wrappers/BukkitConverters.java#L277
cannot find available constructors for singleton lists, because there are no empty constructors.

**To Reproduce**
```java
            removeInfo = new PacketContainer(PLAYER_INFO);
            removeInfo.getPlayerInfoAction().write(0, PlayerInfoAction.REMOVE_PLAYER);
            removeInfo.getPlayerInfoDataLists().write(0, Collections.singletonList(playerInfoData));
```

**Error**
https://pastebin.com/vyYt4j8x

Should singleton lists be forbidden or is it just an bug? Earlier < 4.7 seemed to work fine. Potential problematic commit: 153dd619946cc944f8796cf28ae16540991179a2.

**Comment by dmulloy2** [comment]
Yeah that's just a debug message I accidentally left in. You should be good to keep using it, but fwiw I would recommend using an array list instead because it'll be slightly more efficient. There's not going to be any functional difference

**Comment by games647** [comment]
Thanks for the information. Then I'm going to use an `ArrayList` from now on.

**Comment by Andre601** [comment]
Few questions:

1. The paste is no longer accesible. Is it by any chance something similar to this? https://paste.helpch.at/ufufixugox.md
2. Does the commit https://github.com/dmulloy2/ProtocolLib/commit/4c0c18d7c61b0471cfbfd7a0017a170dd2264e50 "fix" this issue or will plugins still need to apply a workaround?
   My guess is the later because I encounter those exact issues here with a plugin while using latest dev build.

**Comment by games647** [comment]
@Andre601 

1) It appears so
2) It was only a debug message. If ProtocolLib fails to create the list object it will fallback to create a new ArrayList instead. At this step the exception got printed. No changes are required here, because of the fallback. However, by passing an already working type, you don't have the overhead of the exception.
