### ISSUE TITLE
Displaying Hologram Issue (Please Read)

### ISSUE THREAD

**Issue by kiloRs** [dmulloy2/ProtocolLib#1332]
Using MMOItems:

![image](https://user-images.githubusercontent.com/48230591/125180421-8289bc80-e1bf-11eb-8177-83e68066ba2c.png)

This event is erroring, causing holograms from HolographicDisplays to bug out.

It is a protocol issue it seems?

**Comment by libraryaddict** [comment]
The author of that plugin needs to update for 1.17.1
