### ISSUE TITLE
getProtocolManager() is null

### ISSUE THREAD

**Issue by UsainSrht** [dmulloy2/ProtocolLib#1335]
Is `getProtocolManager() is null` issue because of ProtocolLib or not?
I asked this to author of skacket and he said "ProtocolLib doesn't work in 1.17 currently. Waiting on a fix I reported then it will be updated." Protocollibs latest build was 526 when he said this.

[error.txt](https://github.com/dmulloy2/ProtocolLib/files/6802858/error.txt)

**Comment by Ste3et** [comment]
Same issue, with my ProtocolLib Plugins

**Comment by Eilux** [comment]
Yep, same here

**Comment by Ste3et** [comment]
I get these error code https://paste.gg/p/anonymous/8a256a47ea4e4e4f8703767ba453eb63

**Comment by MatsG23** [comment]
The v2.7.0 released 5 days ago implemented support for Minecraft 1.17.

It probably is a problem that [Skacket seems to implement API _4.6.1-SNAPSHOT_](https://github.com/TheLimeGlass/Skacket/blob/master/build.gradle) (not sure)

**Comment by Ste3et** [comment]
These make no sense, thats not Plugins work like, it make no differents if you compile a plugin with v4.7.0 or v4.6.0
It looks like your plugins didn't use getProtocolManager() to register events what hear about incoming/outcoming packets.

**Comment by Ste3et** [comment]
Ok i figure it out for my self, that reason because the getProtocolManager() was null, i shade ProtocolLib to my FurnitureLib plugins what was the mistake i do. Sorry for that.
