### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 9dolanla** [dmulloy2/ProtocolLib#1336]
BUG
https://pastebin.com/uJfMNzdp
This error appears after running for a while

dump
https://pastebin.com/SzH24xLE

**Comment by repeater64** [comment]
That error is your server not responding for 10 seconds (so it crashed, basically). ProtocolLib is not mentioned in the error anywhere so it has nothing to do with it. In fact, I don't see a single plugin in the thread dump, only internal server stuff. So your server probably doesn't have enough RAM or not enough processing power or you tried to make it do too much.

**Comment by 9dolanla** [comment]
OK
