### ISSUE TITLE
Error with PacketPlayOutEntityMetadata on 1.17

### ISSUE THREAD

**Issue by iGabyTM** [dmulloy2/ProtocolLib#1337]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/hTGQcRWb

Description and relevant errors: [This](https://pastebin.com/qJMYJ3rk) error happens randomly, that's all the info I got =/

**Comment by Rothes** [comment]
Steps to reproduce the behavior for me:
1. Install HoloDropsX and any plugin listens on ENTITY_METADATA.
2. Drop a item.
3. The item *may* won't be displayed for players, and there's a stacktrace in console.
