### ISSUE TITLE
NBTFactory.readBlockState(block) return null

### ISSUE THREAD

**Issue by Anarchick** [dmulloy2/ProtocolLib#1339]
**Describe the bug**
Trying to get NBT from a Tile Entity Block return null.

**To Reproduce**
```java
    public static Object toNMSNBTTagCompound(Block block) {
        if (block != null) return null;
        NbtCompound nbt = NbtFactory.readBlockState(block); // null every time
        return (nbt != null) ? nbt.getHandle() : null;
    }
```

**Expected behavior**
Get the nms NBT for a tile entity (chest, sign, ...)

**Version Info**
mc 1.16.5 , protocolLib 4.6.0
https://pastebin.com/QkVXzemJ

**Additional context**
the class of variable `block` is `CraftBlock`

**Comment by TerraMiner** [comment]
got the same problem

**Comment by lukalt** [comment]
This if statement is probably wrong:

`if (block != null) return null;`

it should be

`if (block == null) return null;`

**Comment by TerraMiner** [comment]
> This if statement is probably wrong:
> 
> `if (block != null) return null;`
> 
> it should be
> 
> `if (block == null) return null;`

Correctly noted, but the author indicated a comment next to a specific line of code that returns null. I think he debugged it to point to a specific line. In addition, I also always have null, but it is the NbtFactory#readBlockState function that returns it.
