### ISSUE TITLE
Error: Player lost connection

### ISSUE THREAD

**Issue by TeCoGenie** [dmulloy2/ProtocolLib#134]
At some server starts every player gets kicked, because of an Error:
http://pastebin.com/paDYH0fF

**Comment by dmulloy2** [comment]
Are you using NoCheatPlus?

**Comment by TeCoGenie** [comment]
Yes

**Comment by dmulloy2** [comment]
What version of it are you using?

**Comment by TeCoGenie** [comment]
Spigot: git-Spigot-5f38d38-18fbb24 (MC: 1.8.8)
NoCheatPlus: 3.13.2-SNAPSHOT-sMD5NET-b884
ProtocolLib: v3.6.5-SNAPSHOT-b209

**Comment by dmulloy2** [comment]
Well it's definitely an issue with ProtocolLib and NoCheatPlus, but I have no idea how. It certainly doesn't help that the error is super unhelpful.

**Comment by themazim** [comment]
Not sure, what was in the pastebin. But if this was a linkage error, this is 100% a NCP problem. Update NCP and the error is gone. had the issue for several months now, updated ncp. error gone.
