### ISSUE TITLE
getEntityTrackers and updateEntity not working on 1.17

### ISSUE THREAD

**Issue by LeonMangler** [dmulloy2/ProtocolLib#1340]
Hello, there have been a few issues since the 1.17 update.
- Since 1.17, when using ProtocolLibrary.getProtocolManager().getEntityTrackers(entity); an empty list is returned, regardless of whether the entity is being tracked by players. I tested it with a player as the entity. There are no errors in the console. As a workaround one can use the entity tracking-related NMS code in CraftPlayer#hidePlayer0 which works as expected on 1.17.
- Similarly ProtocolLibrary.getProtocolManager().updateEntity(entity, players); is broken since 1.17. It doesn't actually update the entity. There are no errors in the console. Some more context: I'm developing a vanish plugin and cancelling all player-related packets while a player is in vanish (I'm not only using Player#hidePlayer/showPlayer, since it doesn't support hiding players only in-game or only in tab). Then when the player reappears I'm using the updateEntity method to show the player to all other players who are in range. So far the only workaround is using Player#showPlayer instead.

I'd be glad if you could look into it! Please tell me if you need more information.

**Version Info**
ProtocolLib dump: https://pastebin.com/w78iB1DU

**Comment by Symphonic3** [comment]
I'm also having the issue with updateEntity. Code that should be otherwise 100% working from previous versions is not working as expected because updateEntity doesn't do anything.

**Comment by Symphonic3** [comment]
Any progress with a solution to this issue?
