### ISSUE TITLE
MOJANG MAPPINGS SUPPORT

### ISSUE THREAD

**Issue by DoubleNico** [dmulloy2/ProtocolLib#1343]
So my feature request is because I found a problem with paper, or any other spigot fork that has mojang mappings.So the mojang mappings change the name of many many many classes, so is always a problem while getting a reflection class:
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutBoss., the class exists in obj minecraft code, but with mojang mappings it exists as Component, in net.minecraft.network.chat

`    public static Class<?> getComponentMappingClass() {
        try {
            return getMinecraftClass("network.chat.Component", "Component");
        } catch (RuntimeException var1) {
            return setMinecraftClass("Component", Accessors.getMethodAccessor(getCraftChatMessage(), "fromString", new Class[]{String.class}).getMethod().getReturnType().getComponentType());
        }
    }`

**Comment by games647** [comment]
So what exactly is your feature request? ProtocolLib 4.7 already supports Mojang mappings. If you need the `IChatbaseComponent` class, you could use https://github.com/dmulloy2/ProtocolLib/blob/4c0c18d7c61b0471cfbfd7a0017a170dd2264e50/src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java#L779

and then use FuzzyReflection for finding the field with a specific class type.
