### ISSUE TITLE
Removing Players from Tablist not working Properly

### ISSUE THREAD

**Issue by DerSimeon** [dmulloy2/ProtocolLib#1344]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
Hey, so for our Roleplay server we want to remove all Players from the Tablist, including name, their skin, and ping.
After trying a few Plugins and noticed that none of them worked I started making my own Solution.
It consists of the following, a JoinHandler that send the Player_Info Packet with the Remove_player action.
And a PacketListener on priority highest listening for the Named_entity_spawn packet, once the Packet is received it sends the Player_Info Packet with the Add_Player action waits 10 secs and sends the Remove_Player action again.

That Solution works 85% of the Time, in 15% of the Time the Players have no skin, aka Alex or Steve skin.

**API method(s) used**
Using the Wrapper classes found at https://github.com/dmulloy2/PacketWrapper
ProtocolManager

**Expected behavior**
Players removed from Tablist, and when they are supposed to be visible (their skin) it should be visible and not be Steve or Alex

**Code**
https://paste.sentinalcoding.eu/0945D2Kk4w

**Additional context**
the PosePlugin has a /lay command, which when used fixes the Skin bug. Thats our current workaround for the Players

**Comment by FCKJohni** [comment]
Sorry for the bump But this is very important and we havent found a fix yet

**Comment by FCKJohni** [comment]
Any help?

**Comment by FCKJohni** [comment]
Bump
