### ISSUE TITLE
Accessor tries to create a list from invalid constructor

### ISSUE THREAD

**Issue by libraryaddict** [dmulloy2/ProtocolLib#1345]
https://github.com/dmulloy2/ProtocolLib/blob/4c0c18d7c61b0471cfbfd7a0017a170dd2264e50/src/main/java/com/comphenix/protocol/wrappers/BukkitConverters.java#L277

https://gist.github.com/f41614b699b3b9537a0b945dded7d22d

You forgot to suppress an error

**Comment by games647** [comment]
This seems to be a duplicate of #1331

**Comment by libraryaddict** [comment]
Mb. Forgot to verify if this is a new or old error.
