### ISSUE TITLE
ProtocolLib enables after my plugin

### ISSUE THREAD

**Issue by Doge4** [dmulloy2/ProtocolLib#135]
Hi,

I created a plugin for Spigot & Bukkit and it needs ProtocolLib as dependency.
The problem appears when I'm turning on my server. Every start/restart/reload my plugin loads before ProtocolLib and creates a stack trace: [Click](http://pastebin.com/PLg0Nnfz).
Thank You in advance.

Regards 
Doge4

**Comment by dmulloy2** [comment]
You have to add it as a dependency or soft dependency in your plugin.yml.
