### ISSUE TITLE
Error in console / In game

### ISSUE THREAD

**Issue by Kouveyl** [dmulloy2/ProtocolLib#1350]
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @66f2d70
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@3d389684[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutChat
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a, public net.kyori.adventure.text.Component net.minecraft.server.v1_16_R3.PacketPlayOutChat.adventure$message, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]
      defaultFields={public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components=2, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b=3, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c=4}
      subtypeCache={class net.minecraft.server.v1_16_R3.ChatMessageType=StructureModifier[fieldType=class net.minecraft.server.v1_16_R3.ChatMessageType, data=[private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b]], class java.util.UUID=StructureModifier[fieldType=class java.util.UUID, data=[private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]], interface net.minecraft.server.v1_16_R3.IChatBaseComponent=StructureModifier[fieldType=interface net.minecraft.server.v1_16_R3.IChatBaseComponent, data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6dd72e73[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@713f194
        packetListeners=[PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=HIGH, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=HIGH, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], COLLECT[class=PacketPlayOutCollect, id=85], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=54], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55], ANIMATION[class=PacketPlayOutAnimation, id=5], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=8], ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=HIGH, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=34]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=LOW, packets=[GAME_STATE_CHANGE[class=PacketPlayOutGameStateChange, id=29], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=50], ABILITIES[class=PacketPlayOutAbilities, id=48], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PremiumVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@44b896e7
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@40a8a40b
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@14d8aedb
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@cdf6285
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@c50d257
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1171,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@58226eac
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=12
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@aca8f56
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@52afffb4
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@45236f49[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@81551607=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@32f4799d], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@cd7e7b9d=[com.comphenix.protocol.injector.StructureCache$1@6c9af0aa], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@a52dc481=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@41e5e0d2], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@7963513e=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@1fe28680]}
      listenerLock=java.lang.Object@e4b3c70
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@356f82b3
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@5b6217bc
      reporter=com.comphenix.protocol.ProtocolLib$1@c50d257
      unknownPermGenBean=java.lang.Object@503f5cd6
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Purpur-1171 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
