### ISSUE TITLE
IChatBaseComponent doesn't exist in PacketPlayOutScoreboardTeam

### ISSUE THREAD

**Issue by Nononitas** [dmulloy2/ProtocolLib#1355]
**Describe the bug**
" com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam."

**To Reproduce**
Send a PacketPlayOutScoreboardTeam in Mode 0 with prefix, suffix and displayname

**Expected behavior**
The error should occur

**Version Info**
https://pastebin.com/V9t2yTfm

**Additional context**
Version and fork is visible in the protocoldump

**Comment by jiangdashao** [comment]
The data of the scoreboard in 1.17 needs to be written into the subclass of the scoreboard, you cannot write directly:
![image](https://user-images.githubusercontent.com/21152113/127182244-7eeddb5b-9bfc-4548-804b-be64f72bd6d0.png)

**Comment by Nononitas** [comment]
I don't understand.
According to the [PacketWrapper ](https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerScoreboardTeam.java) and [wiki.vg](https://wiki.vg/Protocol#Teams) it should work ?

**Comment by jiangdashao** [comment]
wiki.vg is always outdated and inaccurate, you should be more inclined to read the Minecraft source code. ProtocolLib currently does not seem to provide a wrapper for this team packet subclass

**Comment by Nononitas** [comment]
Ok thank you

**Comment by dmulloy2** [comment]
> wiki.vg is always outdated and inaccurate

_[citation needed]_

The wiki shows the packets _as they're serialized_, which is often different from how they're represented in the NMS source. So the wiki is a good place to start -- and is especially useful for entity metadata -- but you are correct in that ProtocolLib bases the modifiers on the source.

As for the initial question, @Nononitas, use `packet.getStructures()` to access the `b` inner class. From there, you can access the chat components.

**Comment by Nononitas** [comment]
Could you explain a bit more how I work with that or give an example, because I don't understand how to use it.
My intention would be doing it like that
`WrappedChatComponent chatComponent = WrappedChatComponent.fromText(value);
        StructureModifier<WrappedChatComponent> structureModifier = new StructureModifier<>(WrappedChatComponent.class);
        InternalStructure internalStructure = ;
//setting the prefix
        packet.getStructures().write(1, internalStructure);`
but this doesn't seems right

**Comment by jiangdashao** [comment]
If you know kotlin, you can check my code, it works well:
https://github.com/jiangdashao/VirtualTag/blob/master/src/main/kotlin/me/rerere/virtualtag/tag/VirtualTeam.kt#L44

**Comment by Nononitas** [comment]
Thank you seems to work now
