### ISSUE TITLE
Plead to consider supporting running in mojang mapped environment

### ISSUE THREAD

**Issue by Flo0** [dmulloy2/ProtocolLib#1359]
As many other devs im currently struggeling with NMS in 1.17
I would gladly just develop with the moj mapped files and also run my server with them.

The problem is that using this marvelous library is sadly not possible with moj mapped jars.
I have met other devs who also think that this would make development with 1.17 servers
way easier as they wouldnt need to reobfuscate and deal with all the bugs that come with it.

Please consider looking into this if its not too much work

**Comment by dmulloy2** [comment]
You'd probably only need TinyProtocol or similar if you used the mappings
