### ISSUE TITLE
Bug of protocol lib with plugin oreobfuscator

### ISSUE THREAD

**Issue by Disk-MTH** [dmulloy2/ProtocolLib#1364]
Sorry for my bad English but i'm french.
I have the last version of protocol lib and the last version of orebfuscator.
In the console I have this error but I can't find the origin of the problem. Help please because I really need orebfuscator plugin.

[ERROR] [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
[ERROR] 	If this problem hasn't already been reported, please open a ticket
[ERROR] 	at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[ERROR] 	Stack Trace:
[ERROR] 	java.lang.RuntimeException: Error occured while instancing generated class.
[ERROR] 	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
[ERROR] 	at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
[ERROR] 	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
[ERROR] 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
[ERROR] 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[ERROR] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[ERROR] 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[ERROR] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[ERROR] 	playerConnection=net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@1986260b
[ERROR] 	networkManager=net.minecraft.network.NetworkManager@16c6be7a
[ERROR] 	originalChannel=[id: 0xbb61a95e, L:/192.168.0.112:60565 - R:/88.127.69.138:28855]
[ERROR] 	channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@16c6be7a, previous=[id: 0xbb61a95e, L:/192.168.0.112:60565 - R:/88.127.69.138:28855], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7db32e81, previousLoaded=true, currentSet=true, forceAccess=true]
[ERROR] 	packetMarker={}
[ERROR] 	currentEvent=<null>
[ERROR] 	finalEvent=<null>
[ERROR] 	unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@55ade942
[ERROR] 	vanillaDecoder=net.minecraft.network.NettyPacketDecoder@76bba8e3
[ERROR] 	vanillaEncoder=net.minecraft.network.NettyPacketEncoder@17a9442b
[ERROR] 	finishQueue=[]
[ERROR] 	channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@64f85f3f
[ERROR] 	processor=com.comphenix.protocol.injector.NetworkProcessor@49d7a7b3
[ERROR] 	injected=true
[ERROR] 	closed=false
[ERROR] 	cumulation=PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2)
[ERROR] 	cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@59e8c607
[ERROR] 	singleDecode=false
[ERROR] 	decodeWasNull=false
[ERROR] 	first=true
[ERROR] 	decodeState=1
[ERROR] 	discardAfterReads=16
[ERROR] 	numReads=0
[ERROR] 	added=true
[ERROR] 	]
[ERROR] 	Version:
[ERROR] 	ProtocolLib v4.7.0
[ERROR] 	Java Version:
[ERROR] 	1.8.0_252
[ERROR] 	Server:
[ERROR] 	git-Mohist-1.12.2-244 (MC: 1.12.2)
[INFO] fr6226 lost connection: Disconnected
[INFO] [-] fr6226

**Comment by dmulloy2** [comment]
There are currently no plans to support Mohist
