### ISSUE TITLE
A 'suppressed reports' option to suppress/hide "Unable to intercept a read client packet"

### ISSUE THREAD

**Issue by DisplayPort** [dmulloy2/ProtocolLib#1365]
**Is your feature request related to a problem? Please describe.**
While using the latest dev build of *ServerListPlus* (at the time build 3.5.0) on a server running *Mohist 1.16.5* (build 735) I constantly get the following error *"Error Unable to intercept a read client packet."*

**Describe the solution you'd like**
A flag for the configs 'suppressed reports:' feature that stops these messages from appearing in the console and chat of OP players.

Example name for flag: REPORT_UNABLE_INTERCEPT_READ_CLIENT_PACKET

**Describe alternatives you've considered**
Finding and fixing whatever is causing the issue. (Very unreasonable for this edge case)

**Additional context**
From what I have read you guys don't support Mohist so a flag to give users with edge cases like myself a way to mute these very spammy messages.

In-game example: https://user-images.githubusercontent.com/44052080/128016349-8dbfd5c5-3ff6-4eaa-926e-f86c60dceb8e.mp4
Console error: https://pastebin.com/Fv1j13z6 (Password: 7gz4VKBunh)

**Comment by dmulloy2** [comment]
There are currently no plans to support Mohist
