### ISSUE TITLE
How to not use PacketDataSerializer?

### ISSUE THREAD

**Issue by Th0rgal** [dmulloy2/ProtocolLib#1367]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
Hey,

For a CustomPayload packet I am using PacketDataSerializer class from NMS:
```java
        packetContainer.getModifier().write(1,
                new PacketDataSerializer(Unpooled.wrappedBuffer(out.toByteArray())));
```
Is there a way to do it without NMS?

**API method(s) used**
List what API method(s) you're using
I'm not, I would like to.

**Expected behavior**
Be able to Serialize a packet without NMS.

**Code**
If applicable, add relevant code from your project
```java
        packetContainer.getModifier().write(1,
                new PacketDataSerializer(Unpooled.wrappedBuffer(out.toByteArray())));
```

**Additional context**
This is not a normal CustomPayload containing message for bungee, it's a packet sent for forge. The current way with PacketDataSerializer works well but requires NMS.

**Comment by dmulloy2** [comment]
See if StreamSerializer works for what you need: https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/utility/StreamSerializer.html

**Comment by Th0rgal** [comment]
Thank you
