### ISSUE TITLE
I am getting errors in console

### ISSUE THREAD

**Issue by bolib945** [dmulloy2/ProtocolLib#1369]
Hello, I am encountering such errors in the console, can you help?

**ERROR:** https://paste.ubuntu.com/p/v6692ZsVpp/

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
