### ISSUE TITLE
WrappedDataWatcher not working the same on 1.17 as it did on 1.16

### ISSUE THREAD

**Issue by Jaimss** [dmulloy2/ProtocolLib#1370]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`
![image](https://user-images.githubusercontent.com/53633325/128640189-cd343ce5-0965-47a5-a422-046816c8fa6c.png)

**Describe the question**
What is the new way to create a WrappedDataWatcher for the `PacketType.Play.Server.ENTITY_METADATA` packet. In 1.16.x I was using `WrappedDataWatcher(metaDataPacket#watchableCollectionModifier#read(0))` and it was working fine. In 1.17.1, I am getting an error that `metaDataPacket#watchableCollectionModifier#read(0)` is returning null:
[Error Pastebin](https://paste.jaims.dev/gepagihidu.bash)
[Code Pastebin(`Protocol.kt`)](https://paste.jaims.dev/ayaqegicab.cpp) 

**API method(s) used**
See the `Protocol.kt` file linked above for more detail, but the issue I'm having is with `WrappedDataWatcher(List<WrappedWatchableObject>)`

**Expected behavior**
No error, the wrapped data watcher works as it did in 1.16.

**Code**
Error & Code linked above.
Full project on [github](https://github.com/jaimss/hololib)

**Additional context**
My code is for a library that sends spawn and destroy packets for armor stands. It is a packet based hologram library.  I have tried just using `WrappedDataWatcher()` with no constructor args, but that doesn't work because the entity id is the same every time, so only one of the Hologram Lines (entityies) shows up.

**Comment by Anarchick** [comment]
Did you try with `WrappedWatchableObject` instead of `WrappedDataWatcher`. Works for me (client side glowing), but sorry, can't give you a code cause it's in Skript

**Comment by dmulloy2** [comment]
Looks like per the source it can be null

**Comment by Jaimss** [comment]
> Looks like per the source it can be null

Yes, that is what the error is saying, and what I noticed that `metaDataPacket#watchableCollectionModifier#read(0)` is returning null, so when I do `WrappedDataWatcher(that)`, `that` is null which means it can't do whatever it needs to do.

This what not an issue in 1.16, so I'm asking what the solution might be in 1.17.

**Comment by dmulloy2** [comment]
What I meant was that it's valid for the server to give you a null watchable collection, so you have to handle that case. You may have to create your own fake entities somehow. I know holographic displays does more or less what you're after: https://github.com/filoghost/HolographicDisplays
