### ISSUE TITLE
Bungeecord Console Error... cannot connect to server at all.

### ISSUE THREAD

**Issue by Niccckkkk** [dmulloy2/ProtocolLib#1373]
**Describe the bug**
When joining, I get this error:  https://paste.helpch.at/ejerelovon.bash
https://i.imgur.com/DPLbM9r.png

**To Reproduce**
1. Just install ProtocolLib

**Expected behavior**
Allowing me to join the server

**Screenshots**
https://i.imgur.com/DPLbM9r.png

**Version Info**
I cannot even get on the server, I am on 4.7.0

**Additional context**
Thats all

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

One of your plugins is doing bad things with scoreboards
