### ISSUE TITLE
ProtocolLib 4.6.0+ breaks VentureChat on Mohist 1.12.2.

### ISSUE THREAD

**Issue by Agrrox** [dmulloy2/ProtocolLib#1383]
ProtocolLib version 4.6.0 or higher breaks enabling process of the VentureChat on Mohist 1.12.2.

**to reproduce:**
download Mohist 1.12.2 from [Mohist website](https://mohistmc.com/) or [Jenkins build server](https://ci.codemc.io/job/MohistMC/job/Mohist-1.12.2/)
install the latest compatible version of [Vault 1.6.7](https://www.spigotmc.org/resources/vault.34315/history) for 1.12.2 
install [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) (version doesn't matter)
install [ProtocolLib 4.6.0+](https://www.spigotmc.org/resources/protocollib.1997/history)
install [VentureChat](https://www.spigotmc.org/resources/venturechat.771/) (version doesn't matter)

**plugin list:**
```
Name : Vault
Version : 1.6.7-b${env.TRAVIS_BUILD_NUMBER} (1.5.7 from bukkit also works)
---------
Name : PlaceholderAPI
Version : 2.10.9
---------
Name : ProtocolLib
Version : 4.7.0
---------
Name : VentureChat
Version : 3.0.4
---------
```

**mod list:**
```
none
```

**logs:**
runtime:
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/7064009/latest.log)

protocollib dump:
[dump-2021-08-27_05.41.01.txt](https://github.com/dmulloy2/ProtocolLib/files/7063995/dump-2021-08-27_05.41.01.txt)

**Comment by dmulloy2** [comment]
There are currently no plans to support Mohist.
