### ISSUE TITLE
ProtocolLib and Alice Error when right clicking player with shield in Airplane 1.17.1 and Java 16

### ISSUE THREAD

**Issue by avimuh** [dmulloy2/ProtocolLib#1390]
**Describe the bug**
When i using Alice and ProtocolLib V4.7.0, i right click my friend with Shield and this error came out, but when i use v4.6.0 on 1.16.5 nothing error

**To Reproduce**
1. Install ProtocolLib v4.7.0 (v4.6.0 does not support 1.17.1)
2. Install [Alice](https://discord.gg/wFJXBSK84a) latest loader (Currently not for sale, so i gave the discord link)
3. Restart the server and login, and equip shield and then right click player
4. See the error

**Expected behavior**
Nothing error to the console, just like as using the 1.16.5 ProtocolLib

**Version Info**
https://pastebin.com/tAjUvBct

**Comment by dmulloy2** [comment]
Can you provide the error?

**Comment by NikV2** [comment]
Developer of Alice here, This has to do with this issue: https://github.com/dmulloy2/ProtocolLib/issues/1270

It's most likely a mistake with my wrapper on how im getting the action, You may close this.
