### ISSUE TITLE
Event for player teleport?

### ISSUE THREAD

**Issue by soshimee** [dmulloy2/ProtocolLib#1393]
**Make sure you're doing the following**
- [o] You're using the latest build for your server version
- [o] This isn't an issue caused by another plugin
- [o] You've checked for duplicate issues
- [o] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
What is the event for player teleport? I am trying to cancel a teleport seamlessly which spigot doesn't let me do, it makes the player teleport to the original position.

**API method(s) used**
List what API method(s) you're using
ENTITY_TELEPORT

**Expected behavior**
ENTITY_TELEPORT would affect players but it doesn't.

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by dmulloy2** [comment]
What do you mean by cancel a teleport?

**Comment by soshimee** [comment]
I want to make canceling teleports seamless.
