### ISSUE TITLE
Looking for packet to trick client that he has opened a chest

### ISSUE THREAD

**Issue by wellnesscookie** [dmulloy2/ProtocolLib#1394]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
I am searching for a way to trick the client/player that he has right clicked on a chest, even when he did not. I am using Optifine Textures. Optifine detects whether you opened a certain container (example, filters it by name) and if it matches the one in configuration, it will open a chest inventory with a speciffic design. Now... Chests are a bit ugly and I am using a Crates plugin that allows me to make any block behave as a crate. If I right click it with a key, the crate will open (double chest GUI). The thing is that the OptiFine does not load it's textures unless it is sure that the player right clicked a real double chest and not opened one by bukkit's API.

I tried using OpenWindow packet already, even if it loads the double chest inventory, the textures don't. Is there some packet that could help me do this? 

**API method(s) used**
PacketType.Play.Server.OPEN_WINDOW, but still nope

**Expected behavior**
Not expected, just curious, a question.

**Code**
It's not actually. I edited the Title in the PacketType.Play.Server.OPEN_WINDOW and it does what it says, but still, no textures.

**Additional context**
I am aware this is apparently an OptiFine issue, and it's already reported on their github, but I am wondering if there's is a way around it :)

**Comment by dmulloy2** [comment]
Can you post a screenshot of what it looks like?

**Comment by wellnesscookie** [comment]
Of what exactly, I'm sorry. A code? A GUI?
