### ISSUE TITLE
Console error when starting server

### ISSUE THREAD

**Issue by Anyelo120** [dmulloy2/ProtocolLib#1398]
When starting my minecraft server this big error appears on the console, and it came out that it should be reported, here I don't know what it might be due to.
https://pastebin.com/9nVKX3FB

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
