### ISSUE TITLE
Title Action

### ISSUE THREAD

**Issue by SkyBeastMC** [dmulloy2/ProtocolLib#141]
Hi ! It's me again, I am still creating my plugin, but I found an issue:
packetDelays.getTitleActions() returns this error: http://pastebin.com/ZnGeSrsy
(PacketContener is not null, and packetDelays.getTitleActions() is line n°53)
I need to send Titles (& others 1.8 stuff) to 1.8 users only with an api which I am creating.

And yes, I am an old man who is still using the 1.7-1.8 protocolhack!

**Comment by dmulloy2** [comment]
Title actions don't exist in 1.7, which is what the protocol hack is based on.

**Comment by SkyBeastMC** [comment]
Oh, ok. Is there a way to send titles to 1.8 players on 1.7 server?
This doesn't work with packet-id, or wih int (for titleaction)...
Do I need to inject into minecraftserver without your plugin?

(Also: Is there a way to send packets to an IP and not a player?)

**Comment by dmulloy2** [comment]
I've only seen this done somewhat successfully with Carbon, which created the packet classes and injected them into the server.

**Comment by SkyBeastMC** [comment]
I found a solution with the ugly IChatBaseComponent class.
And ProtocolInjector.PacketTitle.Action.TIMES works in the protocolhack.
I found that: https://www.spigotmc.org/resources/titleapi.1325/ (use Java Decompiler). I don't like how it's coded but this has helped me.

Thanks a lot!
