### ISSUE TITLE
Unable to get the original chat content

### ISSUE THREAD

**Issue by myunco** [dmulloy2/ProtocolLib#1411]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
The chat content is normalized spaces
This problem will occur in the latest 1.16.5 and 1.17.1

![image](https://user-images.githubusercontent.com/26001944/136688807-0fcf923d-a084-44cf-af3f-926908dbd573.gif)

**API method(s) used**
PacketType.Play.Client.CHAT
event.getPacket().getStrings().read(0)

**Expected behavior**
Expected  Don't normalized space

**Code**

ProtocolManager manager = ProtocolLibrary.getProtocolManager();
manager.addPacketListener(new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Client.CHAT) {
  public void onPacketReceiving(PacketEvent event) {
    System.out.println("event.getPacket().getStrings().read(0) = " + event.getPacket().getStrings().read(0));
  }
});

**Additional context**
After repeated testing, I found that there was no such problem before paper-1.16.5-769
The old version of spigot-1.16.5 does not have this problem either

**Comment by Rothes** [comment]
This reproduces even without Protocollib. It seems to be caused by a patch from Paper.
