### ISSUE TITLE
1.17 Teams Packet - Chat Component Writing

### ISSUE THREAD

**Issue by linsaftw** [dmulloy2/ProtocolLib#1413]
**Describe the question**
Can't write Chat Components or Strings in 1.17 Teams packet. Writing safely is like writing nothing.

**Expected behavior**
To be able to write the 3 strings/chatcomponents, prefix, suffix and displayname.

**Code**
```
final StructureModifier<String> strings = packet.getStrings();
final StructureModifier<WrappedChatComponent> chatComponents = packet.getChatComponents();

strings.writeSafely(1, teamDisplayName);
strings.writeSafely(2, prefix);
strings.writeSafely(3, suffix);
chatComponents.writeSafely(0, teamDisplayName);
chatComponents.writeSafely(1, prefix);
chatComponents.writeSafely(2, suffix);
```

**Comment by Janmm14** [comment]
#1388

**Comment by linsaftw** [comment]
Okay now its working. How do I set an empty color? Because in 1.17 is setting colors to the team players and I don't want any.

**Comment by linsaftw** [comment]
The only thing I know is that on 1.8/1.16 if you don't write anything into the packet "color" integer it just doesn't display any colors.

**Comment by Janmm14** [comment]
> 
> 
> The only thing I know is that on 1.8/1.16 if you don't write anything into the packet "color" integer it just doesn't display any colors.

default for 1.16 is reset, check yourself maybe with /packet command
