### ISSUE TITLE
When I join my server is spams error in console and i get teleported to lobby which is what is supossed to happen but spam

### ISSUE THREAD

**Issue by Lavamate786** [dmulloy2/ProtocolLib#1416]
Stack trace: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @43aa4aa7 
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by PimvanderLoos** [comment]
You'll have to update to 4.7.0: https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0
