### ISSUE TITLE
ProtocolManager.updateEntity​ method doesn't work in Spigot 1.17.1

### ISSUE THREAD

**Issue by Lori3f6** [dmulloy2/ProtocolLib#1417]
**Describe the bug**
Hello, I am using ProtocolLib to make a entity vanish from a player's client, so I send a ENTITY_DESTROY packet to a player. It works properly. Then I am going to use `updateEntity​(org.bukkit.entity.Entity entity, List<org.bukkit.entity.Player> observers)` method to make the entity appear on the player client again, but it changes nothing on client.

**To Reproduce**
I made a plug-in and run the following code.  These code are expected to make all LivingEntities except Player vanishing and presenting in player's client alternatively.

``` Java
import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.PacketContainer;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

public class TwinkleEntities extends JavaPlugin {
    @Override
    public void onEnable() {
        var protocolManager = ProtocolLibrary.getProtocolManager();
        AtomicBoolean flag = new AtomicBoolean(false);
        getServer().getScheduler().runTaskTimer(this, () -> {
            if (getServer().getOnlinePlayers().isEmpty())
                return;

            var player = (Player) getServer().getOnlinePlayers().toArray()[0];

            if (flag.get()) {
                var vanishPacket = new PacketContainer(PacketType.Play.Server.ENTITY_DESTROY);
                var entityIDList = new ArrayList<Integer>();

                for (var entity : player.getWorld().getLivingEntities()) {
                    if (!(entity instanceof Player)) {
                        entityIDList.add(entity.getEntityId());
                    }
                }
                vanishPacket.getIntLists().write(
                        0, entityIDList
                );
                try {
                    protocolManager.sendServerPacket(player, vanishPacket);
                } catch (InvocationTargetException e) {
                    e.printStackTrace();
                }
                player.sendMessage("Entities vanished!");
            } else {
                for (var entity : player.getWorld().getLivingEntities()) {
                    if (!(entity instanceof Player)) {
                        protocolManager.updateEntity(entity, List.of(player));
                    }
                }
                player.sendMessage("Entities shown!");
            }

            flag.set(!flag.get());
        }, 0L, 20L);
    }
}

```

**Expected behavior**
The entity around the player twinkles between appearance and disappearance every second. But entities don't present again after vanished.

**Screenshots**
![image.gif](https://global.cdn.blingwang.cn/2021/10/17/9233d3d691502.gif)
This gif may shorternd by github automatically, you could see a longer version here if you want: https://global.cdn.blingwang.cn/2021/10/17/9233d3d691502.gif

**Version Info**
https://pastebin.mozilla.org/asyh7mqC/raw

**Additional context**
I don't know why the entity don't presents after disappearing.  If the problem is caused by incorrect API call in my code, please don't hesitate to correct me. Thanks a lot.

_Empty below._

**Comment by joehot200** [comment]
I have also duplicated this problem with effectively the same code.

**Comment by Sentropic** [comment]
Having the same issue, also in 1.17.1

**Comment by derklaro** [comment]
Hey, 

sorry for the late response on this issue; thanks for the report! As we're changing quite a lot of code in v5.0 (see #1524 for now) I will keep this issue in mind and take a look into it when testing the new version. Might be that the issue is already resolved, will see.
