### ISSUE TITLE
Not sure what's the issue so i can't tell

### ISSUE THREAD

**Issue by Bakayarouz** [dmulloy2/ProtocolLib#1419]
https://hastebin.com/ulijadokiw.properties

I'm not sure how to reproduce nor what's the issue, it doesn't really break anything or make anything go bad from what i can recall
[dump-2021-10-17_19.55.22.txt](https://github.com/dmulloy2/ProtocolLib/files/7360734/dump-2021-10-17_19.55.22.txt)

**Comment by dmulloy2** [comment]
Looks like the paste expired
