### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by LordDWT** [dmulloy2/ProtocolLib#142]
https://ghostbin.com/paste/etjqc

This server is running CraftBukkit version git-Spigot-db6de12-930a59c (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**Comment by dmulloy2** [comment]
I've emailed Spigot support about this, awaiting a response.

**Comment by dmulloy2** [comment]
Right now the solution is to disable update notifications in the config: https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/resources/config.yml#L4

**Comment by LordDWT** [comment]
Thank you.
