### ISSUE TITLE
I am not able to use placeholder api to holographic displays

### ISSUE THREAD

**Issue by vedantjain8** [dmulloy2/ProtocolLib#1423]
I am not able to use placeholder api in holographic display, please see to this problem

**Comment by Rothes** [comment]
You should go holographic display, not here.

**Comment by vedantjain8** [comment]
> You should go holographic display, not here.

but i am able to use the holographic display placeholders but not the placeholders from place holder api

**Comment by dmulloy2** [comment]
yeah your best bet is either placeholder api or holographic displays
