### ISSUE TITLE
Unable to disable all sound effects

### ISSUE THREAD

**Issue by davidjpfeiffer** [dmulloy2/ProtocolLib#1424]
**Describe the bug**
I am unable to disable all sound effects when following the README setup.

**To Reproduce**
1. Install ProtocolLib
2. Indicate ProtocolLib as a depend in the plugin.yml
3. Get the ProtocolManager
4. Use the ProtocolManager to add a packet listener
5. PacketEvent never fires

**Expected behavior**
I expect the PacketEvent to fire

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/BB8zrmuu

**Additional context**
I am not getting any errors in my console. Everything seems to be setup properly. But the PacketEvent is not firing.

UPDATE: The packet is firing for certain sounds, such as a rabbit jumping, but I am trying to detect the sound that is played when a player is near a nether portal and for that sound (and many others) this event is not firing.

**Comment by dmulloy2** [comment]
Your best bet is to browse the protocol (https://wiki.vg/Protocol) and see if there are any other places where sound events are called. Looks like there are 3 different packets you're after (you can thank mojang for splitting it up lol)

**Comment by davidjpfeiffer** [comment]
Hey, thank you for the reply! So there are 3 different packets I'm after, but I am listening to the PacketEvent and that event is not firing when I hear the portal sound. Am I listening to the wrong event? If so, what are the other packet events that I can listen for? Sorry, I'm a bit of a ProtocolLib noob.
