### ISSUE TITLE
NachoSpigot ```Cannot find NetworkManager```

### ISSUE THREAD

**Issue by DreamVoid** [dmulloy2/ProtocolLib#1429]
**Describe the bug**
Like #1002 

**To Reproduce**
1. Start server.
2. Wait a few seconds and it will happened.

**Expected behavior**
Not any error log.

**Screenshots**
None

**Version Info**
https://pastebin.com/tzjMXkdh

**Additional context**
Error: https://pastebin.com/AEYtbjh7
I am using BungeeCord, ```127.0.0.1:10001``` is spigot server internal ip.
When the server is started, it will spam for a period of time, about 1 time per second. After a period of time, the frequency will decrease.
All server and plugins are latest version.

**Comment by LewUwU** [comment]
Caused by Netty 4.1.69
