### ISSUE TITLE
Maven repository not working! 

### ISSUE THREAD

**Issue by Xtremegamor** [dmulloy2/ProtocolLib#143]
Hi, I'm trying to add ProtocolLib as a dependency to my maven project, the problem is that my pom doesn't find the dependency, even though I have the repository! 

http://imgur.com/a/8hrOi

**Comment by dmulloy2** [comment]
You must provide the version, in this case 3.6.4.

**Comment by Xtremegamor** [comment]
It worked! Thanks!
