### ISSUE TITLE
Error "because "this.wrapped" is null"

### ISSUE THREAD

**Issue by Bronzwar** [dmulloy2/ProtocolLib#1433]
**To Reproduce**
The player flew on elytra and was kicked with this error

**Expected behavior**
Not any error log.

**Screenshots**
none

**Version Info**
https://paste.helpch.at/yofepamexa.java

**Additional context**
https://paste.helpch.at/bocoyofega.rb

**Comment by Bronzwar** [comment]
on another fork o have same error https://paste.helpch.at/lojebeboxe.rb

**Comment by dmulloy2** [comment]
Looks like the `eco` plugin is not encoding all the data it should

**Comment by WillFP** [comment]
@dmulloy2 @Bronzwar eco dev here - that issue only occurs if you have async-display enabled. It looks like PacketContainer#deepClone doesn't play nicely with ItemStacks when not on the main thread sometimes.
First, for @Bronzwar - if you go into config.yml and disable async-display, (including ratelimit and emergency, which are enabled by default), then it will fix itself
And for @dmulloy2 - I can't find the documentation between deepClone and shallowClone, if I just want to clone the packet to be able to send a modified version later, is shallowClone any better?
