### ISSUE TITLE
Wiki Page Outdated

### ISSUE THREAD

**Issue by sexnine** [dmulloy2/ProtocolLib#1435]
The wiki page [here](https://github.com/dmulloy2/ProtocolLib/wiki/Adding-ProtocolLib-as-a-Dependency) has the wrong repo url and/or version which does not work.

The wiki should be updated with the updated url and version that is in the [README](https://github.com/dmulloy2/ProtocolLib/blob/master/Readme.md) on line 41.

I'm not sure how to submit a pull request for a wiki edit, so this was the best that I can do, thanks :)

**Comment by dmulloy2** [comment]
Good catch, updated!
