### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException: Unable to make protected final

### ISSUE THREAD

**Issue by RainOfPain125** [dmulloy2/ProtocolLib#1436]
**Describe the bug**
Its just a console error. Not sure what negative effect it could lead to.

**To Reproduce**
All I did was start my server and log in.

**Expected behavior**
N/A

**Screenshots**
N/A

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://www.toptal.com/developers/hastebin/pabepeyexi.properties

**Additional context**
N/A

**Comment by dmulloy2** [comment]
This is fixed in the 4.7.0 release. Find it here: [https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0)
