### ISSUE TITLE
My server crashin

### ISSUE THREAD

**Issue by UnnamedWarrior** [dmulloy2/ProtocolLib#1440]
Protocol dump:
https://pastebin.com/S2s4gtYx

Make sure you've done the following:
- [✔️ ] You're using the latest build for your server version
- [ ✔️] This isn't an issue caused by another plugin
- [idk ] You've checked for duplicate issues
- [ ✔️] You didn't use `/reload`

Debug paste link:

[debug protocollib.log](https://github.com/dmulloy2/ProtocolLib/files/7536697/debug.protocollib.log)

Description and relevant errors:
After i online the server its smooth then after 2 - 5 mins server cpu usage goes to its limit and the ram goes away really fast like 1000mb usage then after 10 seconds its now on 3000mb+ and players cant join

Timings report:
https://timings.aikar.co/?id=8f324340487a45fd9706ac28bc4ffa9f

Spark profiler:
https://spark.lucko.me/qihjHovTmP

**Comment by dmulloy2** [comment]
That log honestly looks like some kind of (D)DoS attack given all the junk packets that are sent
