### ISSUE TITLE
A release would be nice 🙏 

### ISSUE THREAD

**Issue by SaltyAimbOtter** [dmulloy2/ProtocolLib#1444]
**Is your feature request related to a problem? Please describe.**
Our users keep running into problems because of a bug (#1354 ) that was fixed a while ago. We keep telling them to update to ProtocolLib devbuilds and even added a warning on startup. However, they just can't seem to find the download 😂 
We get these questions daily, it's starting to get annoying.. 😆 

**Describe the solution you'd like**
Release any version of b531 or above.

**Additional context**
![grafik](https://user-images.githubusercontent.com/40303883/142258657-68cf8a65-b35c-47a5-b0b4-1cb0f9e1b9ff.png)

Thanks for the nice work on this project! ❤️

**Comment by Esronn** [comment]
This would be amazing <3

**Comment by quiquelhappy** [comment]
I'm hoping for a spigot release WITH support for 1.18 :)

**Comment by mja00** [comment]
You guys know the dev builds are available [here](https://ci.dmulloy2.net/job/ProtocolLib/) right?

**Comment by Wolf2323** [comment]
@mja00 yes, sure, but "normal" users don't find them, and wen need to tell every single person, that he need a dev version. And even if we send them this link, they do still not find the download. The most users are not devs and they have no clue of Jenkins and so on. They are just like DAU (dumbest assumable user)

**Comment by SaltyAimbOtter** [comment]
4.8.0 has been released 😁
