### ISSUE TITLE
NBTCompound returning null

### ISSUE THREAD

**Issue by Olzie-12** [dmulloy2/ProtocolLib#1454]
**Describe the bug**
I'm getting an error on 1.18 saying that NbtCompound is null, i'm honestly not sure if this is a 1.18 issue or a ProtocolLib issue but i cannot get it to work with this error.

**To Reproduce**
Check screenshots

**Expected behavior**
It shouldn't return null 

**Screenshots**
https://img.olziedev.com/D381UbWLZ381383811U.png

**Version Info**
https://haste.olziedev.com/lofidebexi.kotlin

**Additional context**

**Comment by derklaro** [comment]
Can you please share more code? Can you give us the information from which packet you are trying to read?

**Comment by Olzie-12** [comment]
I'm using the UPDATE_SIGN packet, i just realized its deprecated. Is there not anyway i can use another packet and how to?

**Comment by derklaro** [comment]
As described you should use `TILE_ENTITY_DATA`. UpdateSign doesn't contain a Tag, only the lines and the position of the sign:

```java
public class PacketPlayInUpdateSign implements Packet<PacketListenerPlayIn> {
  private static final int a = 384;
  
  private final BlockPosition b;
  
  private final String[] c;
  ```

**Comment by Rothes** [comment]
I just noticed NBTBase#getTypeId() is Obfuscated to NBTBase#a()

**Comment by derklaro** [comment]
> I just noticed NBTBase#getTypeId() is Obfuscated to NBTBase#a()

This is relevant, because...?

**Comment by Rothes** [comment]
> > I just noticed NBTBase#getTypeId() is Obfuscated to NBTBase#a()
> 
> This is relevant, because...?

[com/comphenix/protocol/wrappers/nbt/WrappedElement.java](https://github.com/dmulloy2/ProtocolLib/blob/4bc9e8b7b78196c99d95330005171ced8ed5b73d/src/main/java/com/comphenix/protocol/wrappers/nbt/WrappedElement.java#L144)
ProtocolLib use this method to convert it.

**Comment by derklaro** [comment]
Not really. The actual implementation will only use the name when it's unable to retreive the method by the given paramters:
```java
		List<Method> methods = getMethodListByParameters(returnType, args);
		
		if (methods.size() > 0) {
			return methods.get(0);
		} else {
			// That sucks
			throw new IllegalArgumentException("Unable to find " + name + " in " + source.getName());
		}

**Comment by Rothes** [comment]
> Not really. The actual implementation will only use the name when it's unable to retreive the method by the given paramters:
> 
> ```java
> 		List<Method> methods = getMethodListByParameters(returnType, args);
> 		
> 		if (methods.size() > 0) {
> 			return methods.get(0);
> 		} else {
> 			// That sucks
> 			throw new IllegalArgumentException("Unable to find " + name + " in " + source.getName());
> 		}
> ```

Um yeah I was wrong. Not really took into that.

**Comment by Olzie-12** [comment]
So I should use TILE_ENTITY_DATA?

**Comment by Rothes** [comment]
> So I should use TILE_ENTITY_DATA?

on Spigot 1.8-1.9, use UPDATE_SIGN
else, use MAP_CHUNK + TILE_ENTITY_DATA
You can check my codes, just finished them: https://github.com/Rothes/ProtocolStringReplacer/tree/master/src/main/java/me/rothes/protocolstringreplacer/packetlisteners/server/sign

**Comment by Olzie-12** [comment]
> > So I should use TILE_ENTITY_DATA?
> 
> on Spigot 1.8-1.9, use UPDATE_SIGN else, use MAP_CHUNK + TILE_ENTITY_DATA You should realize that on 1.18 these packets have been changed. You can check my codes, just finished them: https://github.com/Rothes/ProtocolStringReplacer/tree/master/src/main/java/me/rothes/protocolstringreplacer/packetlisteners/server/sign

alrighty, i will look into it when i can

**Comment by LoneDev6** [comment]
Seems now the NBTTagCompound field is not initialized by default when `createPacket(PacketType.Play.Server.TILE_ENTITY_DATA)` is called.

I had to initialize it by myself: `NbtFactory.ofCompound("")`

**Comment by Olzie-12** [comment]
I'm getting this issue when trying to write the packet type to tile entity data.
Any alternatives?
```
[17:33:20 WARN]: [ProtocolLib] Loaded class com.olziedev.playerwarps.f.d$_b from PlayerWarps v6.12.0-pre6 which is not a depend, softdepend or loadbefore of this plugin.
[17:33:20 WARN]: FieldAccessException: No field with type int exists in class PacketPlayOutTileEntityData.
[17:33:20 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365)
[17:33:20 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
```

https://img.olziedev.com/J886486464oNe864_.png
