### ISSUE TITLE
console flood, but server still work without problems

### ISSUE THREAD

**Issue by BooMBeRcs** [dmulloy2/ProtocolLib#146]
http://pastebin.com/FWgDEBBW
http://pastebin.com/CJQNM8uG

version 3.6.4

**Comment by dmulloy2** [comment]
Try using the 3.6.5 release and see if this still happens.

**Comment by BooMBeRcs** [comment]
im sorry, but i cant find a download link 3.6.5 
can you help me?

**Comment by games647** [comment]
http://ci.dmulloy2.net/job/ProtocolLib

**Comment by dmulloy2** [comment]
Is this still an issue in 3.6.5?
