### ISSUE TITLE
PacketPlayOutMapChunk is no more exists

### ISSUE THREAD

**Issue by oNLog1c** [dmulloy2/ProtocolLib#1463]
**Describe the bug**
PacketType.Play.Server.MAP_CHUNK is not working anymore. In 1.18 an NMS class **PacketPlayOutMapChunk** was removed (or renamed?), and after that, this packet cannot be manipulated. I tried to spoof biome IDs by faking a package, but got **FieldAccessException**. This suggests that the field I'm looking for no longer exists. However, on 1.17.1, the same code works without any problems.

**To Reproduce**
Just use the code below. After trying to connect to the server, exceptions will be thrown.

**Expected behavior**
If everything worked as it should, then the biomes would faking, and there would be no errors in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/53514252/146695993-2354380c-5bc0-4dcc-a560-41418fd2cc84.png)
![image](https://user-images.githubusercontent.com/53514252/146696128-b18d1128-ea6f-43ab-b800-65feb954e1ca.png)

**Version Info**
4.8.0-SNAPSHOT-b538, paper 1.18.1

ps. Sorry if this is my mistake, I just started learning ProtocolLib yesterday.

**Comment by derklaro** [comment]
The packet still exists, it just doesn't contain an int[] anymore. I suggest looking into the server code to find out how to read the packet correctly. This is not a protocollib issue. (A bit of help might be #1469 )

**Comment by ThereIsNoLogic** [comment]
Thanks for the advice, but it didn't work for me. All night I tried to figure out which field contains information about biomes, but I did not understand..

**Comment by derklaro** [comment]
The data is in the first byte array in the first internal structure in the packet. See [here](https://wiki.vg/Chunk_Format#Data_structure) for information how the data is structered in there.

**Comment by ThereIsNoLogic** [comment]
Understood. But, as I see, that byte array stores not only values ​​with biome IDs, but also most of the another useful data for the chunk. My programming skills do not yet allow me to understand how this works, so I could not find a solution to my problem and almost gave up. I do not have much time to figure out how it works.. Anyway, thanks for the help.
