### ISSUE TITLE
Unable to retrieve current Minecraft version

### ISSUE THREAD

**Issue by ryanguy426** [dmulloy2/ProtocolLib#147]
Although this definitely isn't a problem, it's just a slight annoyance. It always catches my eye when I'm looking for errors on startup, I see this and everytime I go back to check to make sure there's no issue which needs resolving.

**Error:**
`[17:53:24 WARN]: [ProtocolLib] [ProtocolLibrary] Unable to retrieve current Minecraft version. Assuming (MC: 1.8.8)java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String	at com.comphenix.protocol.ProtocolConfig.getIgnoreVersionCheck(ProtocolConfig.java:343) ~[ProtocolLib.jar:3.6.5-b222]	at com.comphenix.protocol.ProtocolLibrary.verifyMinecraftVersion(ProtocolLibrary.java:474) [ProtocolLib.jar:3.6.5-b222]	at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216) [ProtocolLib.jar:3.6.5-b222]	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]>`

**ProtocolLib version:** Build #222, version 3.6.5

**Spigot version** (output from /version): This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT

**Java Version** (output from java -version):

openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by dmulloy2** [comment]
Try deleting and regenerating your config.yml

**Comment by ryanguy426** [comment]
That worked, thanks!
