### ISSUE TITLE
API representation for packet fields of type BlockEntityType

### ISSUE THREAD

**Issue by blablubbabc** [dmulloy2/ProtocolLib#1470]
For example, in MC 1.18.x, the TILE_ENTITY_DATA packet (ClientboundBlockEntityDataPacket) stores a field of type BlockEntityType. I am not sure how I can analyze this field via ProtocolLib, for example to conditionally only modify packets that affect a specific type of tile entity.

Possible solutions I can think of:
* Add a new converter to [BukkitConverters](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/BukkitConverters.java) that converts objects of type BlockEntityType to something NMS-unspecific, such as: The corresponding Bukkit BlockState class, ProtocolLib's MinecraftKey, Bukkit's NamespacedKey, the String key, ..
* Expose a wrapper for Minecraft's BlockEntityType registry in [WrappedRegistry](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/wrappers/WrappedRegistry.java). This would then allow the lookup of the key for a given BlockEntityType instance.

**Comment by derklaro** [comment]
See #1469 - you can use `container.getStructures().read(0)` for this.

**Comment by blablubbabc** [comment]
> See #1469 - you can use `container.getStructures().read(0)` for this.

I am not sure how I would use that to for example check whether the BlockEntityType is `minecraft:sign`. As far as I can tell, these ids are not actually stored by the BlockEntityType instance itself, but only by the registry they are stored in.  
I could maybe inspect the `com.mojang.datafixers.types.Type` stored by the BlockEntityType instance to derive whether it is a particular BlockEntityType. I have not tried that yet. But even if this datafixer type happens to store the id, it seems like quite an involved/non-ideal workaround to use that for identification purposes.
