### ISSUE TITLE
EnumPlayerTeleportFlags Reflection Error

### ISSUE THREAD

**Issue by MCD4U** [dmulloy2/ProtocolLib#1472]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

I am using PacketWrapper, however the error comes from a method that belongs to this library so I think it should be appropriate to put this here. The problematic code is the following:

```java
MinecraftReflection.getMinecraftClass("EnumPlayerTeleportFlags","PacketPlayOutPosition$EnumPlayerTeleportFlags")
```

When this is run, it throws the following error:

```
Caused by: java.lang.RuntimeException: Unable to find EnumPlayerTeleportFlags (PacketPlayOutPosition$EnumPlayerTeleportFlags)
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2143) ~[ProtocolLib(5).jar:?]
```

**Comment by derklaro** [comment]
I don't see the issue your tbh. The class does not exists and it throws an exception because of that. Maybe you should use the obfuscated name instead?
