### ISSUE TITLE
Server crash with ProtocolLib

### ISSUE THREAD

**Issue by SteveTheDog** [dmulloy2/ProtocolLib#148]
Crash dump: http://pastebin.com/j6UU61ua
Spigot version: git-Spigot-db6de12-3f3c65f (MC: 1.8.8)
ProtocolLib version: #222 (3.6.5 release)
BungeeCord version: #1116

**Comment by dmulloy2** [comment]
Was there a stack trace before this?

**Comment by SteveTheDog** [comment]
Nope.

**Comment by dmulloy2** [comment]
I can't reproduce this. How did this crash come about?

**Comment by SteveTheDog** [comment]
I'm not really sure, it just crashed.  I have LibsDisguises version #62 (latest) from the jenkins server if that could have something to do with it.

**Comment by SteveTheDog** [comment]
Crashed today again: http://pastebin.com/7HwX3PEf

**Comment by dmulloy2** [comment]
How many players does your server usually get? It looks like it's timing out doing pretty standard stuff.

**Comment by SteveTheDog** [comment]
At this time we had about 50 online.

**Comment by dmulloy2** [comment]
Any more information on this issue?

**Comment by SteveTheDog** [comment]
Nope, haven't had this issue in a while.
