### ISSUE TITLE
Consider making MojangMapped jar's available.

### ISSUE THREAD

**Issue by ryantheleach** [dmulloy2/ProtocolLib#1482]
**Is your feature request related to a problem? Please describe.**
When debugging plugins that are in a MojangMapped environment, depending on protocollib means that you cannot debug without additional steps.

**Describe the solution you'd like**
I would like to see ProtocolLib publish jars with MojangMaps, for development purposes.

**Describe alternatives you've considered**
Using TinyRemapper to reverse the mappings of ProtocolLib and create these jars myself (I do not have this knowledge yet).

**Comment by derklaro** [comment]
This is a good idea, however there is no tool which can make that for us - we need to make this by hand as we need to update all constants on our own (especially packet class names and some older field accesses are still using a name accessor over better filtering methods)

**Comment by dmulloy2** [comment]
i would accept a PR for this functionality, but i don't currently have the bandwidth to go through and manually remap PL
