### ISSUE TITLE
This error keeps showing

### ISSUE THREAD

**Issue by CJRed1** [dmulloy2/ProtocolLib#1483]
Hello, I have an Aternos Server with Mohist as Software, when I join, this message keeps coming up in the chat and the console, the server is in 1.16.5 and ProtocolLib is in 4.7.0 with the Simple Chat Plugin

How do I fix this?

(This was taken from the server log)
[01:56:19] [Netty Epoll Server IO #2/ERROR] [Minecraft/]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
4011 | If this problem hasn't already been reported, please open a ticket
4012 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
4013 | Stack Trace:
4014 | java.lang.RuntimeException: Error occured while instancing generated class.
4015 | at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
4016 | at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
4017 | at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
4018 | at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
4019 | at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
4020 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
4021 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
4022 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
4023 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4024 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4025 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
4026 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
4027 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
4028 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4029 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4030 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
4031 | at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
4032 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4033 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4034 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
4035 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
4036 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
4037 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4038 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4039 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
4040 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
4041 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4042 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4043 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
4044 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
4045 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
4046 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
4047 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
4048 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
4049 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
4050 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
4051 | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
4052 | at java.base/java.lang.Thread.run(Thread.java:829)
4053 | Caused by: java.lang.reflect.InvocationTargetException
4054 | at jdk.internal.reflect.GeneratedConstructorAccessor67.newInstance(Unknown Source)
4055 | at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
4056 | at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
4057 | at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
4058 | ... 37 more
4059 | Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInCustomPayload
4060 | at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CCustomPayloadPacket$java_lang_Object.<init>(Unknown Source)
4061 | ... 41 more
4062 | Dump:
4063 | Parameters:
4064 | io.netty.buffer.PooledUnsafeDirectByteBuf@b200f3c[
4065 | memoryAddress=140363675283472
4066 | recyclerHandle=io.netty.util.Recycler$DefaultHandle@6af588d9
4067 | chunk=Chunk(184e61c4: 2%, 286720/16777216)
4068 | handle=4611686018427389962
4069 | memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
4070 | offset=81920
4071 | length=32
4072 | maxLength=32
4073 | cache=io.netty.buffer.PoolThreadCache@52e279ce
4074 | tmpNioBuf=<null>
4075 | allocator=PooledByteBufAllocator(directByDefault: true)
4076 | refCnt=1
4077 | readerIndex=32
4078 | writerIndex=32
4079 | markedReaderIndex=0
4080 | markedWriterIndex=0
4081 | maxCapacity=2147483647
4082 | ]
4083 | manager:
4084 | com.comphenix.protocol.injector.PacketFilterManager@360d2f8e[
4085 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77600c88
4086 | packetListeners=[PacketAdapter[plugin=voicechat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[START[class=PacketLoginInStart, id=0], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10]], gamephase=PLAYING, options=[]]]]
4087 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@73cb6760
4088 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1f2caf6b
4089 | inputBufferedPackets=[]
4090 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4002925f
4091 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3771c29b
4092 | hasClosed=false
4093 | classLoader=org.bukkit.plugin.java.PluginClassLoader@2eb3f735
4094 | reporter=com.comphenix.protocol.ProtocolLib$1@1fa94372
4095 | server=CraftServer{serverName=Mohist,serverVersion=1.16.5-907,minecraftVersion=1.16.5}
4096 | library=ProtocolLib v4.7.0
4097 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3140068e
4098 | knowsServerPackets=true
4099 | knowsClientPackets=true
4100 | phaseLoginCount=1
4101 | phasePlayingCount=2
4102 | packetCreation=true
4103 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2e78b916
4104 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@45769ea9
4105 | hasRecycleDistance=true
4106 | minecraftVersion=(MC: 1.16.5)
4107 | debug=false
4108 | ]
4109 | Sender:
4110 | com.comphenix.protocol.injector.netty.ChannelInjector@407436b5[
4111 | decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
4112 | encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
4113 | factory=com.comphenix.protocol.injector.netty.InjectionFactory@32fb33d2
4114 | player=CraftPlayer{name=CJRed}
4115 | updated=CraftPlayer{name=CJRed}
4116 | playerName=CJRed
4117 | playerConnection=net.minecraft.network.play.ServerPlayNetHandler@3c562891
4118 | networkManager=net.minecraft.network.NetworkManager@59209c92
4119 | originalChannel=[id: 0xaa1afcec, L:/172.20.0.28:44999 - R:/190.120.248.110:62463]
4120 | channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@59209c92, previous=[id: 0xaa1afcec, L:/172.20.0.28:44999 - R:/190.120.248.110:62463], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@419f5ad9, previousLoaded=true, currentSet=true, forceAccess=true]
4121 | packetMarker={}
4122 | currentEvent=<null>
4123 | finalEvent=<null>
4124 | unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1c772f4a
4125 | vanillaDecoder=net.minecraft.network.NettyPacketDecoder@5cf6829c
4126 | vanillaEncoder=net.minecraft.network.NettyPacketEncoder@f1b8c5f
4127 | finishQueue=[]
4128 | channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2e78b916
4129 | processor=com.comphenix.protocol.injector.NetworkProcessor@11c1224f
4130 | injected=true
4131 | closed=false
4132 | cumulation=PooledUnsafeDirectByteBuf(ridx: 32, widx: 32, cap: 32)
4133 | cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@794bb089
4134 | singleDecode=false
4135 | decodeWasNull=false
4136 | first=true
4137 | decodeState=1
4138 | discardAfterReads=16
4139 | numReads=0
4140 | added=true
4141 | ]
4142 | Version:
4143 | ProtocolLib v4.7.0
4144 | Java Version:
4145 | 11.0.12
4146 | Server:
4147 | 1.16.5-907 (MC: 1.16.5)
4148

sorry if my english is bad

**Comment by dmulloy2** [comment]
The official stance of ProtocolLib is to not use Mohist. They've done some shady stuff with plugin jars which you can read more about here: https://essentialsx.net/do-not-use-mohist.html
