### ISSUE TITLE
Doesnt work with mohist

### ISSUE THREAD

**Issue by Dev4lexG** [dmulloy2/ProtocolLib#1485]
Doesnt work on lastest versions

**Comment by lokka30** [comment]
Not surprising that a forge-bukkit hack breaks yet another plugin

**Comment by dmulloy2** [comment]
The official stance of ProtocolLib is to not use Mohist. They've done some shady stuff with plugin jars which you can read more about here: https://essentialsx.net/do-not-use-mohist.html
