### ISSUE TITLE
Internal error cannot perform automatic updates

### ISSUE THREAD

**Issue by moreni57800** [dmulloy2/ProtocolLib#1488]
[Wed, 12. Jan 2022 11:59:24 CET ERROR] [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
[Wed, 12. Jan 2022 11:59:24 CET ERROR] If this problem hasn't already been reported, please open a ticket
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[Wed, 12. Jan 2022 11:59:24 CET ERROR] Stack Trace:
[Wed, 12. Jan 2022 11:59:24 CET ERROR] java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at com.comphenix.protocol.ProtocolConfig.isAutoDownload(ProtocolConfig.java:263)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:587)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:59)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:555)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[Wed, 12. Jan 2022 11:59:24 CET ERROR] at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by derklaro** [comment]
Looks like your protocollib config is corrupted. Set the auto update setting to `false` not a string
