### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by FabiusHaselnuss** [dmulloy2/ProtocolLib#1492]
ProtocolLib v4.6.0
Mohist-1.16.5-917-server

[Wed, 19. Jan 2022 19:36:16 CET ERROR] [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
[Wed, 19. Jan 2022 19:36:16 CET ERROR] If this problem hasn't already been reported, please open a ticket
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[Wed, 19. Jan 2022 19:36:16 CET ERROR] Stack Trace:
[Wed, 19. Jan 2022 19:36:16 CET ERROR] java.lang.RuntimeException: Error occured while instancing generated class.
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:237)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:312)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:16 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at
[Wed, 19. Jan 2022 19:36:21 CET ERROR] io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at net.minecraft.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:85)
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:36]
[Wed, 19. Jan 2022 19:36:21 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at
[Wed, 19. Jan 2022 19:36:26 CET ERROR] io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
[19:36]
[Wed, 19. Jan 2022 19:36:26 CET ERROR] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at java.base/java.lang.Thread.run(Thread.java:834)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] Caused by: java.lang.reflect.InvocationTargetException
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:221)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] ... 40 more
[Wed, 19. Jan 2022 19:36:31 CET ERROR] Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
[Wed, 19. Jan 2022 19:36:31 CET ERROR] at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_CHandshakePacket$java_lang_Object.<init>(Unknown Source)
[Wed, 19. Jan 2022 19:36:31 CET ERROR] ... 45 more
[Wed, 19. Jan 2022 19:36:31 CET ERROR] Dump:
[Wed, 19. Jan 2022 19:36:31 CET ERROR] Parameters:
[Wed, 19. Jan 2022 19:36:31 CET ERROR] io.netty.buffer.PooledUnsafeDirectByteBuf@8a591ee[
[Wed, 19. Jan 2022 19:36:31 CET ERROR] memoryAddress=1928358232128
[Wed, 19. Jan 2022 19:36:31 CET ERROR] recyclerHandle=io.netty.util.Recycler$DefaultHandle@47db22ad
[19:36]
[Wed, 19. Jan 2022 19:36:31 CET ERROR] chunk=Chunk(46174374: 1%, 16384/16777216)
[Wed, 19. Jan 2022 19:36:36 CET ERROR] handle=4611686018427389953
[Wed, 19. Jan 2022 19:36:36 CET ERROR] memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
[Wed, 19. Jan 2022 19:36:36 CET ERROR] offset=8192
[Wed, 19. Jan 2022 19:36:36 CET ERROR] length=24
[Wed, 19. Jan 2022 19:36:36 CET ERROR] maxLength=32
[Wed, 19. Jan 2022 19:36:36 CET ERROR] cache=io.netty.buffer.PoolThreadCache@50e5f409
[Wed, 19. Jan 2022 19:36:36 CET ERROR] tmpNioBuf=<null>
[Wed, 19. Jan 2022 19:36:36 CET ERROR] allocator=PooledByteBufAllocator(directByDefault: true)
[Wed, 19. Jan 2022 19:36:36 CET ERROR] refCnt=1
[Wed, 19. Jan 2022 19:36:36 CET ERROR] readerIndex=24
[Wed, 19. Jan 2022 19:36:36 CET ERROR] writerIndex=24
[Wed, 19. Jan 2022 19:36:36 CET ERROR] markedReaderIndex=0
[Wed, 19. Jan 2022 19:36:36 CET ERROR] markedWriterIndex=0
[Wed, 19. Jan 2022 19:36:36 CET ERROR] maxCapacity=2147483647
[Wed, 19. Jan 2022 19:36:36 CET ERROR] ]
[Wed, 19. Jan 2022 19:36:36 CET ERROR] manager:
[Wed, 19. Jan 2022 19:36:36 CET ERROR] com.comphenix.protocol.injector.PacketFilterManager@164b4da0[
[Wed, 19. Jan 2022 19:36:36 CET ERROR] unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6971b6dc
[Wed, 19. Jan 2022 19:36:36 CET ERROR] packetListeners=[PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
[Wed, 19. Jan 2022 19:36:36 CET ERROR] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@441f1d0d
[19:36]
[Wed, 19. Jan 2022 19:36:36 CET ERROR] playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7368ea51
[Wed, 19. Jan 2022 19:36:41 CET ERROR] inputBufferedPackets=[]
[Wed, 19. Jan 2022 19:36:41 CET ERROR] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3f028fd1
[Wed, 19. Jan 2022 19:36:41 CET ERROR] sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5b2119bb
[Wed, 19. Jan 2022 19:36:41 CET ERROR] hasClosed=false
[Wed, 19. Jan 2022 19:36:41 CET ERROR] classLoader=org.bukkit.plugin.java.PluginClassLoader@3131f333
[Wed, 19. Jan 2022 19:36:41 CET ERROR] reporter=com.comphenix.protocol.ProtocolLib$1@676a80a7
[Wed, 19. Jan 2022 19:36:41 CET ERROR] server=CraftServer{serverName=Mohist,serverVersion=1.16.5-917,minecraftVersion=1.16.5}
[Wed, 19. Jan 2022 19:36:41 CET ERROR] library=ProtocolLib v4.6.0
[Wed, 19. Jan 2022 19:36:41 CET ERROR] asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7833a5c3
[Wed, 19. Jan 2022 19:36:41 CET ERROR] knowsServerPackets=true
[Wed, 19. Jan 2022 19:36:41 CET ERROR] knowsClientPackets=true
[Wed, 19. Jan 2022 19:36:41 CET ERROR] phaseLoginCount=2
[Wed, 19. Jan 2022 19:36:41 CET ERROR] phasePlayingCount=2
[Wed, 19. Jan 2022 19:36:41 CET ERROR] packetCreation=false
[Wed, 19. Jan 2022 19:36:41 CET ERROR] nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@81a306c
[Wed, 19. Jan 2022 19:36:41 CET ERROR] pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@47e47faf
[Wed, 19. Jan 2022 19:36:41 CET ERROR] hasRecycleDistance=true
[Wed, 19. Jan 2022 19:36:41 CET ERROR] minecraftVersion=(MC: 1.16.5)
[Wed, 19. Jan 2022 19:36:41 CET ERROR] debug=false
[Wed, 19. Jan 2022 19:36:41 CET ERROR] ]
[Wed, 19. Jan 2022 19:36:41 CET ERROR] Sender:
[Wed, 19. Jan 2022 19:36:41 CET ERROR] com.comphenix.protocol.injector.netty.ChannelInjector@5d8054df[
[19:36]
[Wed, 19. Jan 2022 19:36:41 CET ERROR] decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
[Wed, 19. Jan 2022 19:36:46 CET ERROR] encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
[Wed, 19. Jan 2022 19:36:46 CET ERROR] factory=com.comphenix.protocol.injector.netty.InjectionFactory@24f63d3c
[Wed, 19. Jan 2022 19:36:46 CET ERROR] player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@7db6f09e
[Wed, 19. Jan 2022 19:36:46 CET ERROR] updated=<null>
[Wed, 19. Jan 2022 19:36:46 CET ERROR] playerName=<null>
[Wed, 19. Jan 2022 19:36:46 CET ERROR] playerConnection=<null>
[Wed, 19. Jan 2022 19:36:46 CET ERROR] networkManager=net.minecraft.network.NetworkManager@194bf180
[Wed, 19. Jan 2022 19:36:46 CET ERROR] originalChannel=[id: 0x0bf6d4af, L:/ipadresse:25569 - R:/ipadresse:51251]
[Wed, 19. Jan 2022 19:36:46 CET ERROR] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@194bf180, previous=[id: 0x0bf6d4af, L:/ipadresse:25569 - R:/ipadresse:51251], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@ae078c7, previousLoaded=true, currentSet=true, forceAccess=true]
[Wed, 19. Jan 2022 19:36:46 CET ERROR] packetMarker={}
[Wed, 19. Jan 2022 19:36:46 CET ERROR] currentEvent=<null>
[Wed, 19. Jan 2022 19:36:46 CET ERROR] finalEvent=<null>
[Wed, 19. Jan 2022 19:36:46 CET ERROR] unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1d42519
[Wed, 19. Jan 2022 19:36:46 CET ERROR] vanillaDecoder=net.minecraft.network.NettyPacketDecoder@533d49a9
[19:36]
[Wed, 19. Jan 2022 19:36:46 CET ERROR] vanillaEncoder=net.minecraft.network.NettyPacketEncoder@5a123549
[Wed, 19. Jan 2022 19:36:51 CET ERROR] finishQueue=[]
[Wed, 19. Jan 2022 19:36:51 CET ERROR] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@81a306c
[Wed, 19. Jan 2022 19:36:51 CET ERROR] processor=com.comphenix.protocol.injector.NetworkProcessor@2a22ee60
[Wed, 19. Jan 2022 19:36:51 CET ERROR] injected=true
[Wed, 19. Jan 2022 19:36:51 CET ERROR] closed=false
[Wed, 19. Jan 2022 19:36:51 CET ERROR] cumulation=PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)
[Wed, 19. Jan 2022 19:36:51 CET ERROR] cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4d73b2df
[Wed, 19. Jan 2022 19:36:51 CET ERROR] singleDecode=false
[Wed, 19. Jan 2022 19:36:51 CET ERROR] decodeWasNull=false
[Wed, 19. Jan 2022 19:36:51 CET ERROR] first=true
[Wed, 19. Jan 2022 19:36:51 CET ERROR] decodeState=1
[Wed, 19. Jan 2022 19:36:51 CET ERROR] discardAfterReads=16
[Wed, 19. Jan 2022 19:36:51 CET ERROR] numReads=0
[Wed, 19. Jan 2022 19:36:51 CET ERROR] added=true
[Wed, 19. Jan 2022 19:36:51 CET ERROR] ]
[Wed, 19. Jan 2022 19:36:51 CET ERROR] Version:
[Wed, 19. Jan 2022 19:36:51 CET ERROR] ProtocolLib v4.6.0
[Wed, 19. Jan 2022 19:36:51 CET ERROR] Java Version:
[Wed, 19. Jan 2022 19:36:51 CET ERROR] 11.0.13
[Wed, 19. Jan 2022 19:36:51 CET ERROR] Server:
[Wed, 19. Jan 2022 19:36:51 CET ERROR] 1.16.5-917 (MC: 1.16.5)

**Comment by joaco1808-jpg** [comment]
Same error
