### ISSUE TITLE
Packet encoding of packet ID 20 threw (skippable? false)

### ISSUE THREAD

**Issue by thehuze** [dmulloy2/ProtocolLib#1495]
Hello. I have lastest build of ViaVersion, ProtocolLib and CrazyCrates. When the player opens the case, he is kicked with such an error

(https://github.com/dmulloy2/ProtocolLib/files/7906027/dump-2022-01-20_17.35.25.txt)
https://paste.gg/p/anonymous/3ff56215f9214692800eafde1822c361

**Comment by thehuze** [comment]
ActualIt's not fixed...

**Comment by thehuze** [comment]
This error appears when you often open inventories (chests, etc.)

**Comment by dmulloy2** [comment]
Seems to be a bug with CrazyCrates, report it to them
