### ISSUE TITLE
Packet encoding of packet ID 85 threw (skippable? false) java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by roggy666** [dmulloy2/ProtocolLib#1496]
When I install ProtocolLib, plugin start to kick players with this error, I use : GeyserMC, floodgate, ViaVersion (this plugins in error too, but when I use them without ProtocolLib, it works nice.

![IMG_20220120_212428](https://user-images.githubusercontent.com/59109355/150409111-e68aa7f5-feca-4436-b5ee-fe94b92498b7.jpg)

**Version Info**
ProtocolLib v4.8.0-SNAPSHOT-b540

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).
