### ISSUE TITLE
USE_ENTITY 1.18 problem

### ISSUE THREAD

**Issue by Dave4245** [dmulloy2/ProtocolLib#1497]
**Describe the bug**
When trying to create a packet NPC click listener the methods event.getPacket().getEntityUseActions() and event.getPacket().getHands() return empty.

**To Reproduce**
Here is an image of the code and all useful information: 
![image](https://user-images.githubusercontent.com/53492807/150448198-238400b2-3943-4639-b1c7-2b1b64b93a88.png)

I tried putting the hands if statement first, but that also returned empty.

**Expected behavior**
For the final if statement to be called.

**Version Info**
I can't provide it as it is located inside an isolated container.

**Additional context**
I don't know if I have missed something but I was using version 4.7.0 and the same thing was happening, I also saw a pull request with a fix to this in 1.17 but IDK if that is relevant here as it's 1.18.

**Comment by derklaro** [comment]
For 1.17+ use `getEnumEntityUseActions` instead.

**Comment by Dave4245** [comment]
Awesome thanks for the help.
