### ISSUE TITLE
Idk what this even is but it seems to be a detriment to performance.

### ISSUE THREAD

**Issue by ZepsiZola** [dmulloy2/ProtocolLib#1499]
**Describe the bug**
It seems like there's an inefficiency in the code because Idk why this specific process would take up so much processing on the server.

**To Reproduce**
1. Start up a server with ProtocolLib Running
2. Enter `/spark profiler --only-ticks-over 150 --timeout 600`
3. Analyse the spark profile
4. See this process taking up a large amount of processing.

**Screenshots**
![image](https://user-images.githubusercontent.com/49735083/150530816-a7bc2224-cde6-4388-9931-464d3082b1f0.png)
https://spark.lucko.me/Ma3z1kPkCt

**Version Info**
https://pastebin.com/TQf7JXnA

**Comment by ryantheleach** [comment]
![image](https://user-images.githubusercontent.com/141554/152583240-0649f742-639f-496d-96b1-7679c94e4309.png)

Generally speaking, you should report stuff like this to the plugin author using Protocol Lib.

https://www.spigotmc.org/resources/holographic-placeholders-holoextension.64535/

The plugin is performing a deep clone on EVERY entity metadata packet.

https://github.com/NeutralPlasma/HoloExtension/blob/master/src/main/java/eu/virtusdevelops/holoextension/modules/protocolLib/PacketEditor.java#L37
