### ISSUE TITLE
Protocole Manager null

### ISSUE THREAD

**Issue by Zefix0509** [dmulloy2/ProtocolLib#1500]
The console said that my protocole manager is null. Do you know why?

I'm using the lastest build for version 1.18

I'm trying to add a listener on particules packets

Here's my code:
`@Override
    public void onEnable() {

        instance = this;
        protocolManager = ProtocolLibrary.getProtocolManager();

        protocolManager.addPacketListener(
        new PacketAdapter(this, ListenerPriority.NORMAL,
                PacketType.Play.Server.WORLD_PARTICLES) {
            @Override
            public void onPacketSending(PacketEvent event) {

                System.out.println(event.getPlayer().getName() + " est le joueur en question: " + event.getPlayer().getUniqueId());

                // Item packets (id: 0x29)
                if (event.getPacketType() ==
                        PacketType.Play.Server.WORLD_PARTICLES && event.getPlayer().getUniqueId() == UUID.fromString("f1786fc3-9795-415a-a9c0-8538fd69fae8")) {
                    System.out.println(event.getPacketType().name());
                    event.setCancelled(true);
                }
            }
        });

        System.out.println("PacketParticule");

    }`

**Comment by derklaro** [comment]
Can you provide us the stacktrace and more background information, like if you're depending on ProtocolLib etc?

**Comment by dmulloy2** [comment]
or where this code is called. for example, if it's in `onLoad`, you might not have access to the protocol manager. or in `onEnable`, you may not be properly depending on PL

**Comment by derklaro** [comment]
Another thing that came to my mind is that you're shading protocol lib into your plugin - don't do that. Put the plugin onto your server directly and depend on it.

**Comment by 5GameMaker** [comment]
I have the same issue
```java
ProtocolManager manager = ProtocolLibrary.getProtocolManager();

if (manager != null) {
    manager.addPacketListener(new PacketAdapter(plugin, ListenerPriority.NORMAL, PacketType.Play.Client.ARM_ANIMATION) {
        @Override
        public void onPacketReceiving(PacketEvent event) {
            super.onPacketReceiving(event);
            onPlayerBreakStateChanges(event);
        }
    });
}
```
Code above is inside `onEnable` and `ProtocolLib` is provided as a hard dependency.

**Comment by derklaro** [comment]
Please ensure that you haven't shaded protocol lib into your plugin then...

**Comment by Withicality** [comment]
Check your pom.xml, make sure the scope is provided
![image](https://user-images.githubusercontent.com/54366349/156867284-732782e9-24af-46f2-99fe-4bc8ed57d6a6.png)

**Comment by 5GameMaker** [comment]
> Check your pom.xml, make sure the scope is provided ![image](https://user-images.githubusercontent.com/54366349/156867284-732782e9-24af-46f2-99fe-4bc8ed57d6a6.png)

That helped, ty
