### ISSUE TITLE
Error, pls help

### ISSUE THREAD

**Issue by ZayanPlayz** [dmulloy2/ProtocolLib#1501]
<html>
<body>

Stack Trace:
78 | java.lang.ExceptionInInitializerError
79 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:68)
80 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
81 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
82 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
83 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
84 | at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:428)
85 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:285)
86 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
87 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
88 | at java.base/java.lang.Thread.run(Thread.java:833)
89 | Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unsupported class file major version 61
90 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:409)
91 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
92 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
93 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
94 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
95 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
96 | at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
97 | at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
98 | at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
99 | ... 10 more
100 | Dump:
101 | Parameters:
102 | [NULL]
103 | Sender:
104 | com.comphenix.protocol.ProtocolLib@67d684d0[
105 | statistics=<null>
106 | backgroundCompiler=<null>
107 | packetTask=-1
108 | tickCounter=0
109 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@42282eff
110 | configExpectedMod=-1
111 | updater=com.comphenix.protocol.updater.SpigotUpdater@687ca787
112 | redirectHandler=<null>
113 | commandProtocol=<null>
114 | commandPacket=<null>
115 | commandFilter=<null>
116 | packetLogging=<null>
117 | skipDisable=false
118 | isEnabled=false
119 | loader=org.bukkit.plugin.java.JavaPluginLoader@626fa37a
120 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-174,minecraftVersion=1.18.1}
121 | file=plugins/ProtocolLib.jar
122 | description=org.bukkit.plugin.PluginDescriptionFile@3290d4f3
123 | dataFolder=plugins/ProtocolLib
124 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
125 | naggable=true
126 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
127 | configFile=plugins/ProtocolLib/config.yml
128 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@20361d5b
129 | ]
130 | Version:
131 | ProtocolLib v4.6.0
132 | Java Version:
133 | 17.0.1
134 | Server:
135 | git-Paper-174 (MC: 1.18.1)
136 |  
137

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by derklaro** [comment]
Please update your protocol lib version to the latest dev build (4.8.0, see the readme for instructions)
