### ISSUE TITLE
MOHIST CONSOLE ERRORS

### ISSUE THREAD

**Issue by VovelPunch** [dmulloy2/ProtocolLib#1502]
**Describe the bug**
I dont have a clue a bunch of console errors...
**To Reproduce**
if you want to reproduce then use latest version of mohist use this/these:
Modpack: https://www.curseforge.com/minecraft/modpacks/last-man-standing 
Plugins: https://haste.mohistmc.com/uqeyidenuf
2. I dont know fanny around and prance about the minecraft world with a fancy modded dragon. 
3. ...
4. ...
5. ...
**Expected behavior**
not have my console full of errors
**Screenshots**
no need
**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
[dump-2022-01-24_14.26.26.txt](https://github.com/dmulloy2/ProtocolLib/files/7925862/dump-2022-01-24_14.26.26.txt)

**Additional context**
[latest (15).log](https://github.com/dmulloy2/ProtocolLib/files/7925820/latest.15.log)

**Comment by derklaro** [comment]
Same thing as #1503
