### ISSUE TITLE
Error [BUG]

### ISSUE THREAD

**Issue by LeonMaximal1** [dmulloy2/ProtocolLib#1504]
29.01 14:01:44 [Server] WARN at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:390)
29.01 14:01:44 [Server] WARN at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
29.01 14:01:44 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
29.01 14:01:44 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
29.01 14:01:44 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:491)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
29.01 14:01:44 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
29.01 14:01:44 [Server] WARN at AdvancedNMotd-9.2.0.jar//ru.namerpro.Protocol.Base.Main.onPacketSending(Main.java:92)
29.01 14:01:44 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
29.01 14:01:44 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:359)
29.01 14:01:44 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
29.01 14:01:44 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
29.01 14:01:44 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
29.01 14:01:44 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
29.01 14:01:44 [Server] INFO Could not set motd, because something went wrong! Here is an error.
29.01 14:01:41 [Server] INFO T3odora_ issued server command: /tpaccept
29.01 14:01:38 [Server] INFO DrZamfir issued server command: /tpa T3odora_
29.01 14:01:36 [Server] INFO The user DrZamfir has successfully logged in.
29.01 14:01:31 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
29.01 14:01:31 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
29.01 14:01:31 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
29.01 14:01:31 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
29.01 14:01:31 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
29.01 14:01:31 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//com.gmail.picono435.picojobs.api.managers.PlayersManager.lambda$getJobPlayerFromStorage$2(PlayersManager.java:104)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//com.gmail.picono435.picojobs.storage.sql.file.FlatfileStorageFactory.getJob(FlatfileStorageFactory.java:81)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:106)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1185)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1738)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1211)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1511)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:170)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:181)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.message.DbException.get(DbException.java:205)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
29.01 14:01:31 [Server] WARN at PicoJobs-null.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
29.01 14:01:31 [Server] WARN org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-200]
29.01 14:01:31 [Server] WARN Error connecting to the storage. The plugin will not work correctly.
29.01 14:01:31 [Server] WARN XMPP is not configured properly. If you do not know what XMPP is, you may wish to remove the EssentialsXXMPP plugin from your server.
29.01 14:01:31 [Multicraft] DrZamfir ran command Message of the Day
29.01 14:01:31 [Connect] User DrZamfir, IP 78.96.82.249
29.01 14:01:31 [Server] INFO UUID of player DrZamfir is 1744808e-5e61-3c2a-94ab-eb27434df166
29.01 14:01:23 [Server] INFO Online Players 1/30: T3odora_
29.01 14:01:23 [Server] INFO ---------------[ Player List ]---------------
29.01 14:01:10 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
29.01 14:01:10 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
29.01 14:01:10 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
29.01 14:01:10 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
29.01 14:01:10 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
29.01 14:01:10 [Server] WARN at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
29.01 14:01:10 [Server] WARN at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
29.01 14:01:10 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.01 14:01:10 [Multicraft] Skipped 45 lines due to rate limit (30/s)
29.01 14:01:07 [Server] WARN at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:390)
29.01 14:01:07 [Server] WARN at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
29.01 14:01:07 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
29.01 14:01:07 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
29.01 14:01:07 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:491)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
29.01 14:01:07 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
29.01 14:01:07 [Server] WARN at AdvancedNMotd-9.2.0.jar//ru.namerpro.Protocol.Base.Main.onPacketSending(Main.java:92)
29.01 14:01:07 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
29.01 14:01:07 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:359)
29.01 14:01:07 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
29.01 14:01:07 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
29.01 14:01:07 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
29.01 14:01:07 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
29.01 14:01:07 [Server] INFO Could not set motd, because something went wrong! Here is an error.
29.01 14:01:07 [Multicraft] Skipped 53 lines due to rate limit (30/s)
29.01 14:01:05 [Server] WARN at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:390)
29.01 14:01:05 [Server] WARN at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
29.01 14:01:05 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
29.01 14:01:05 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
29.01 14:01:05 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:491)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
29.01 14:01:05 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
29.01 14:01:05 [Server] WARN at AdvancedNMotd-9.2.0.jar//ru.namerpro.Protocol.Base.Main.onPacketSending(Main.java:92)
29.01 14:01:05 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
29.01 14:01:05 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:359)
29.01 14:01:05 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
29.01 14:01:05 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
29.01 14:01:05 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
29.01 14:01:05 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
29.01 14:01:05 [Server] INFO Could not set motd, because something went wrong! Here is an error.
29.01 14:01:05 [Multicraft] Skipped 54 lines due to rate limit (30/s)
29.01 14:01:02 [Server] WARN at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:390)
29.01 14:01:02 [Server] WARN at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
29.01 14:01:02 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
29.01 14:01:02 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
29.01 14:01:02 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:491)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
29.01 14:01:02 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
29.01 14:01:02 [Server] WARN at AdvancedNMotd-9.2.0.jar//ru.namerpro.Protocol.Base.Main.onPacketSending(Main.java:92)
29.01 14:01:02 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
29.01 14:01:02 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:359)
29.01 14:01:02 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
29.01 14:01:02 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
29.01 14:01:02 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
29.01 14:01:02 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
29.01 14:01:02 [Server] INFO Could not set motd, because something went wrong! Here is an error.
29.01 14:00:59 [Server] INFO Loaded all 1 languages!
29.01 14:00:59 [Multicraft] Skipped 53 lines due to rate limit (30/s)
29.01 14:00:58 [Server] WARN at net.minecraft.network.NetworkManager.writePacket(NetworkManager.java:390)
29.01 14:00:58 [Server] WARN at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
29.01 14:00:58 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
29.01 14:00:58 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
29.01 14:00:58 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:491)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
29.01 14:00:58 [Server] WARN at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
29.01 14:00:58 [Server] WARN at AdvancedNMotd-9.2.0.jar//ru.namerpro.Protocol.Base.Main.onPacketSending(Main.java:92)
29.01 14:00:58 [Server] WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
29.01 14:00:58 [Server] WARN at java.base/java.util.Objects.checkIndex(Objects.java:359)
29.01 14:00:58 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
29.01 14:00:58 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
29.01 14:00:58 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
29.01 14:00:58 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
29.01 14:00:58 [Server] INFO Could not set motd, because something went wrong! Here is an error.
29.01 14:00:56 [Server] INFO Creating new data for player: T3odora_
29.01 14:00:55 [Server] INFO Loaded 1 images...
29.01 14:00:55 [Server] WARN You are using the latest version of the plugin.

**Comment by derklaro** [comment]
Please post we full stack trace, using for example [a gist](https://gist.new)

**Comment by dmulloy2** [comment]
this is likely an issue with the picojobs plugin, report it to them
