### ISSUE TITLE
Need help for the right PacketType Names

### ISSUE THREAD

**Issue by HOPSGESALZT** [dmulloy2/ProtocolLib#1507]
**Make sure you're doing the following**
- [ ✔ ] You're using the latest build for your server version
- [ ✔ ] This isn't an issue caused by another plugin
- [ ✔ ] You've checked for duplicate issues
- [ ✔ ] You didn't use `/reload`

**Describe the question**
I want to use the API but I cannot find the right Protocol Names because they are all not named the same as in https://wiki.vg/Protocol#Request;

**API method(s) used**
None because I cannot find the right Packets

**Expected behavior**
A Site for declaration what PacketType is what Protocol

**Code**
Not needed

**Additional context**
Cannot find anything to it I am using it on Minecraft Version 1.8.8

**Comment by derklaro** [comment]
ProtocolLib ist using the Packet Names of Minecraft (by their classes, earlier versions are still using the spigot mapped packet names), this is the reason why the packets are not identifiable directly. You can either try out which packet type is equivalent to which mojang (or spigot) mapped name, but maintaining a wiki to map those names is just too much work (especially cause we would have to do this for 1.7 - 1.18)

**Comment by HOPSGESALZT** [comment]
Ty
