### ISSUE TITLE
Server Thread Report

### ISSUE THREAD

**Issue by LcyDev** [dmulloy2/ProtocolLib#1508]
**Describe the bug**
This happened multiple times with the same output.
I'm not blaming this plugin but i need some help.

**Log**
https://pastebin.com/zQG2qXnU

**Version Info**
ProtocolLib-4.7.0 build #540

**Additional context**
My server is in 1.17 but i support 1.18 players.
I'm not sure if i should be using the latest dev release or not.

**Comment by derklaro** [comment]
Looks to me like an issue of `itemsadder` not ProtocolLib, report it to them
