### ISSUE TITLE
problem ive been having for a week

### ISSUE THREAD

**Issue by zookeh** [dmulloy2/ProtocolLib#1519]
my server version is 1.7.9
whenever i try to join the server (i use bungeecord btw)
it spams the console with this and disconnects me 
![Screenshot_74](https://user-images.githubusercontent.com/44171501/154729863-bd824fa6-7c1b-46e0-a872-78d18e7b7047.png)

**Comment by derklaro** [comment]
Go to the latest 3.X version for 1.7 support. Please note that 3.x is no longer supported tho, consider updating your server...

**Comment by Jakewolfm** [comment]
can i have the link for that please?

**Comment by derklaro** [comment]
Scroll down on the version page (https://www.spigotmc.org/resources/protocollib.1997/history) a little bit until you find 3.x builds :)

**Comment by Jakewolfm** [comment]
its still not working lmao

**Comment by derklaro** [comment]
Are you on 3.7.0? What is the stacktrace now?

**Comment by Jakewolfm** [comment]
ok i just downloaded latest version of plib and i just put the 1.8 version into my 1.7 server plugins folder and it somehow works

**Comment by derklaro** [comment]
That's even better, nice to hear!
