### ISSUE TITLE
ProtocolLib - 1.9 Dev Build // Crash upon "anything" (?)

### ISSUE THREAD

**Issue by Pr0totype2** [dmulloy2/ProtocolLib#152]
Heey,

Whatever I do, ProtocolLib wants to get in the way...
For example, when I leave the server;
`01.03 15:11:23 [Disconnect] User Pr0totype2 has disconnected, reason: Disconnected
01.03 15:11:24 [Server] INFO Error Unable to inject incoming channel [id: 0xa9547c6a, /// MY IP => /51.254.131.210:25565]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@2b2fb056.
01.03 15:11:24 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xa9547c6a, /// MY IP => /51.254.131.210:25565].
01.03 15:11:24 [Server] INFO If this problem hasn't already been reported, please open a ticket
01.03 15:11:24 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01.03 15:11:24 [Server] INFO Stack Trace:
01.03 15:11:24 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
01.03 15:11:24 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01.03 15:11:24 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01.03 15:11:24 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.inject(NettyChannelInjector.java:284)
01.03 15:11:24 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
01.03 15:11:24 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:24 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:24 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:24 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:24 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:24 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
01.03 15:11:24 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
01.03 15:11:49 [Multicraft] Skipped 58 lines due to rate limit (30/s)
01.03 15:11:49 [Server] INFO Error Unable to inject incoming channel [id: 0xb90eae78, /// MY IP => /51.254.131.210:25565]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@2b2fb056.
01.03 15:11:49 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xb90eae78, /// MY IP => /51.254.131.210:25565].
01.03 15:11:49 [Server] INFO If this problem hasn't already been reported, please open a ticket
01.03 15:11:49 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01.03 15:11:49 [Server] INFO Stack Trace:
01.03 15:11:49 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
01.03 15:11:49 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01.03 15:11:49 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01.03 15:11:49 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.inject(NettyChannelInjector.java:284)
01.03 15:11:49 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
01.03 15:11:49 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:49 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:49 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:49 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:49 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:49 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
01.03 15:11:49 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
01.03 15:11:51 [Multicraft] Auto-saving world...
01.03 15:11:51 [Multicraft] Skipped 249 lines due to rate limit (30/s)
01.03 15:11:51 [Server] INFO Saving is already turned on.
01.03 15:11:51 [Server] INFO Saving...
01.03 15:11:51 [Server] INFO Saved the world
01.03 15:11:52 [Server] ERROR Could not pass event AsyncPlayerChatEvent to LegacyPvE v1.0.0
01.03 15:11:52 [Server] INFO org.bukkit.event.EventException
01.03 15:11:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1224) [spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1162) [spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
01.03 15:11:52 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
01.03 15:11:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_95]
01.03 15:11:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_95]
01.03 15:11:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
01.03 15:11:52 [Server] INFO Caused by: java.lang.NullPointerException
01.03 15:11:52 [Server] INFO at com.pr0totype2.legacypve.handlers.RanksHandler.getPowerLevel(RanksHandler.java:50) ~[?:?]
01.03 15:11:52 [Server] INFO at com.pr0totype2.legacypve.utils.PlayerUtils.onPlayerChatAsync(PlayerUtils.java:34) ~[?:?]
01.03 15:11:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
01.03 15:11:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
01.03 15:11:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
01.03 15:11:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
01.03 15:11:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
01.03 15:11:52 [Server] INFO ... 11 more
01.03 15:11:53 [Disconnect] User Pr0totype2 has disconnected, reason: Disconnected
01.03 15:11:54 [Server] INFO Error Unable to inject incoming channel [id: 0x22d25f80, /// MY IP => /51.254.131.210:25565]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@2b2fb056.
01.03 15:11:54 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x22d25f80, /// MY IP => /51.254.131.210:25565].
01.03 15:11:54 [Server] INFO If this problem hasn't already been reported, please open a ticket
01.03 15:11:54 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01.03 15:11:54 [Server] INFO Stack Trace:
01.03 15:11:54 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
01.03 15:11:54 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01.03 15:11:54 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01.03 15:11:54 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.inject(NettyChannelInjector.java:284)
01.03 15:11:54 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
01.03 15:11:54 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:54 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:54 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:54 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:54 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:11:54 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
01.03 15:11:54 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)`
Or when I join;
`01.03 15:14:32 [Server] INFO Error Unable to inject incoming channel [id: 0xbb553c64, /// MY IP => /51.254.131.210:25565]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@2b2fb056.
01.03 15:14:32 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xbb553c64, /// MY IP => /51.254.131.210:25565].
01.03 15:14:32 [Server] INFO If this problem hasn't already been reported, please open a ticket
01.03 15:14:32 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01.03 15:14:32 [Server] INFO Stack Trace:
01.03 15:14:32 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
01.03 15:14:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01.03 15:14:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
01.03 15:14:32 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.inject(NettyChannelInjector.java:284)
01.03 15:14:32 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
01.03 15:14:32 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:14:32 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:14:32 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:14:32 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:14:32 [Server] INFO at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
01.03 15:14:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
01.03 15:14:32 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:412)
01.03 15:14:32 [Server] INFO at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
01.03 15:14:35 [Multicraft] Skipped 262 lines due to rate limit (30/s)`

**Comment by dmulloy2** [comment]
Are you by chance using ViaVersion?

**Comment by Pr0totype2** [comment]
Nope...

**Comment by dmulloy2** [comment]
Can you provide a list of your plugins?

**Comment by Pr0totype2** [comment]
Plugins (23): TimTheEnchanter, LoreAttributesRecoded, PlugMan, ChestRegen, WorldEdit, VoxelSniper, CoreProtect, Lores, Vault, ProtocolLib, EffectLib, HolographicDisplays, Votifier, GAListener, WorldGuard, Citizens, Shopkeepers, CrateReloaded, MythicMobs, CS-CoreLib, RealMail, QuestWorld, LegacyPvE

**Comment by dmulloy2** [comment]
Did this happen on 1.8 or is it new in 1.9?

**Comment by Pr0totype2** [comment]
In the new 1.9 update, using latest build.

**Comment by dmulloy2** [comment]
Based on #169, it likely has to do with HolographicDisplays and/or Citizens. What versions of those plugins are you using?

**Comment by Pr0totype2** [comment]
Latest version for all, seems to work now ^-^
