### ISSUE TITLE
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener

### ISSUE THREAD

**Issue by Oranamous** [dmulloy2/ProtocolLib#1528]
**Describe the bug**
On loading the server with my plugin installed, I get a 'java.lang.NoClassDefFoundError' error mentioning 'com/comphenix/protocol/events/PacketListener' and the plugin I'm creating is unable to load. More info in pastebin links. I doubt this is actually an issue with ProtocolLib, if that's correct, let me know what I did wrong!

[Log](https://pastebin.com/86y5XdQD)
[pom.xml](https://pastebin.com/7qqWXGAb)
[Raewyn_core.java](https://pastebin.com/m7h4TWGx)

**Expected behavior**
I expected to see no errors in the console, and my plugin should have been able to load.

**Version Info**
[Pastebin](https://pastebin.com/NmJa4ivC)

**Comment by dmulloy2** [comment]
Do you have ProtocolLib listed as a dependency?

**Comment by Oranamous** [comment]
Yep, you can check pom.xml to see for yourself

**Comment by dmulloy2** [comment]
you have to put it in the plugin yml too

**Comment by Oranamous** [comment]
Oof, I hadn't done that!

**Comment by Oranamous** [comment]
I'm still a rookie I guess, I'll close this issue in a few minutes.
