### ISSUE TITLE
getEntityFromID appears to be broken

### ISSUE THREAD

**Issue by MyzelYam** [dmulloy2/ProtocolLib#153]
Since the 1.9 update, my plugin PremiumVanish appears to be unable to fetch entities from IDs using ProtocolLib, I'm not sure if this is my fault or 1.9's fault, what do you think is the cause?

http://pastebin.com/H38MkVAf
ProtocolLib version 3.7-SNAPSHOT-b234
CraftBukkit version git-Spigot-604e046-69e196f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

Thanks for your continuous effort into updating ProtocolLib, you are a truly great member of the spigot community <3

**Comment by dmulloy2** [comment]
Add entity tracking to the surprisingly short list of 1.9 casualties. I'll look into it.
