### ISSUE TITLE
Latest ProtocolLib changes break BuyCraft completely.

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#1530]
This: https://github.com/dmulloy2/ProtocolLib/commit/073bfa2b86048aade0a0f32638f0255fdbd3f282 breaks BuyCraft completely.

https://pastebin.com/raw/8d7FS14A

Rolling back to build 548 = all is functional.

**Comment by SlimeDog** [comment]
Perhaps the same root issue (if not I will open another): On both 1.18.1-3443 and 1.18.2-3453, with lots of plugins (it's a plugin test server) all up-to-date bleeding-edge dev builds, ProtocolLib 5.0.0-b549 blocks connectivity completely. The servers do not even register in the client. Reverting resolves the problem.

**Comment by derklaro** [comment]
Hey, thank you both for reporting/confirming issues with the new version. Honestly I was already expecting some plugins to break over the change... 

@andrewkm I will look into the BuyCraft code later today and try to figger out if they did something stupid or if we did!
@SlimeDog if you have any other exceptions thrown when starting the server with v5 over v4 then feel free to post them here as well, that way I don't have to look into multiple issues or lose track over them 😂

**Comment by SlimeDog** [comment]
Will do. There are no exception (on my test servers) with 5.0.0-b548, but my use cases are limited at the moment, since we are in a development cycle for a new plugin.

**Comment by derklaro** [comment]
Found the issue and fixed it, thanks for your report! See https://github.com/dmulloy2/ProtocolLib/suites/5595558993/artifacts/181561818 for a version you can test :)

**Comment by SlimeDog** [comment]
Thanks. Quick work.

We have other things on the plate with our own development. I will probably wait for the dev build.

**Comment by andrewkm** [comment]
@derklaro a quick test shows BuyCraft being fixed, however the server shutdown process is still wonky...
https://pastebin.com/raw/i1CtkUJB

**Comment by derklaro** [comment]
@andrewkm does that happen every time?

**Comment by andrewkm** [comment]
Yes.

**Comment by SlimeDog** [comment]
I am not seeing those issues on shutdown.

**Comment by derklaro** [comment]
I'm a bit confused as I am not able to reproduce the issue, even on the exact same server version you are using (unless it is a custom fork of paper...)

**Comment by andrewkm** [comment]
We are running 1.17.2 build 409 (latest that was released).

**Comment by SlimeDog** [comment]
FWIW, I think you mean 1.17.1-409.

**Comment by andrewkm** [comment]
Yeah that lol, 1.18.2 has me brainwashed.

**Comment by SlimeDog** [comment]
Still seeing issues with b550 on Spigot/Paper 1.18.2 latest builds. I am away from the servers atm, but if no one else posts overnight (here), I will.

**Comment by derklaro** [comment]
Can you specify more? This issue was closed as the cause of it was fixed... Does the same issue persist? Or are you referring to other issues? 🤔

**Comment by SlimeDog** [comment]
It's probably a different problem, but it was reported to me verbally. If so, I will open a new issue.
