### ISSUE TITLE
PacketWrapper Advancement Packet Issues

### ISSUE THREAD

**Issue by SkyLicks** [dmulloy2/ProtocolLib#1533]
**Describe the bug**

**To Reproduce**
1. Create a packet listener for the advancement packet.
2. Use the WrapperPlayServerAdvancements packet wrapper to getAdvancements
`ProtocolLibrary.getProtocolManager().addPacketListener(
                new PacketAdapter(Core.getInstance(), PacketType.Play.Server.ADVANCEMENTS) {
                    @Override
                    public void onPacketSending(PacketEvent event) {
                        WrapperPlayServerAdvancements advancements = new WrapperPlayServerAdvancements(event.getPacket());
                        Map<MinecraftKey, WrapperPlayServerAdvancements.SerializedAdvancement> advancementMap = advancements.getAdvancements().orElse(null);
                    }
                }
        );`
3. Now send yourself an advancement (really all I tested gave errors). For example: /advancement grant SkylixMC only minecraft:adventure/sleep_in_bed

**Expected behavior**
The expected behavior is to be able to retrieve advancements without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/34877092/157602124-ba636a26-62a6-4ed0-9a32-5a08f4190501.png)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/rWKDfwSd)

**Additional context**
I'm was just trying to figure out how the advancement packet works so I can send "fake" packet advancements.

**Comment by derklaro** [comment]
PacketWrapper is currently not updated anymore. However there might be a version for 1.12, but I'm not sure...
