### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke 

### ISSUE THREAD

**Issue by SufkopGamer** [dmulloy2/ProtocolLib#1543]
This is my code:

`private void registerPacketListeners() {
    ProtocolLibrary.getProtocolManager().addPacketListener((PacketListener)new ClientMoveHandler.PacketListening((Plugin)this));
    ProtocolLibrary.getProtocolManager().addPacketListener((PacketListener)new ClientEntityUnmountListener((Plugin)this));
    ProtocolLibrary.getProtocolManager().addPacketListener((PacketListener)new MountListener(this));
  }`

This is my error:

`java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null`

**Comment by derklaro** [comment]
Hi,
you're either not depending on ProtocolLib or you accidentally shaded ProtocolLib into your plugin.

**Comment by SufkopGamer** [comment]
How do you mean?

I use ProtocolLib for Packets and PacketEvents

**Comment by SufkopGamer** [comment]
![image](https://user-images.githubusercontent.com/86513008/158564776-d60e272c-84f9-4c41-bf41-96e46a3f4bdc.png)
This is the whole error

**Comment by derklaro** [comment]
Just make sure that (if you are using maven) the ProtocolLib dependency scope is `provided` (if you are using gradle use `compileOnly` over `implementation` or `api`)

**Comment by SufkopGamer** [comment]
I use Maven how can is `provided` it?

**Comment by derklaro** [comment]
```xml
  <dependency>
    <groupId>com.comphenix.protocol</groupId>
    <artifactId>ProtocolLib</artifactId>
    <version>4.8.0</version>
    <scope>provided</scope>
  </dependency>
  ```
  Like this

**Comment by SufkopGamer** [comment]
Thx
