### ISSUE TITLE
Incorrect Protocol Version Reported When Using ViaVersion

### ISSUE THREAD

**Issue by akaiomoi** [dmulloy2/ProtocolLib#1545]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
Im Not Getting The Correct Protocol Version While Using ViaVersion & ProtocolLib, It Reports 1.12.2 As Protocol Version 47 (1.8) Instead Of Protocol Version 340 (1.12.2)

**API method(s) used**
ProtocolLibrary.getProtocolManager().getProtocolVersion(e.getPlayer())

**Expected behavior**
I Expect To Get The Correct Protocol Version Of The Player

**Code**
```
if(ProtocolLibrary.getProtocolManager().getProtocolVersion(e.getPlayer()) > 47) {
    return;
} else if(ProtocolLibrary.getProtocolManager().getProtocolVersion(e.getPlayer()) < 47) {
    return;
}
```

**Additional context**
Using ViaVersion

**Comment by derklaro** [comment]
Hi,
did I understand the problem correctly? You're joining using 1.12 but ProtocolLib reports 1.8? Which server version are you running?

**Comment by OmenDoesStuff** [comment]
> Hi, did I understand the problem correctly? You're joining using 1.12 but ProtocolLib reports 1.8? Which server version are you running?

1.8.8
with protocollib 4.8.0

**Comment by derklaro** [comment]
So the server is on 1.12 and you're joining with 1.8?

**Comment by OmenDoesStuff** [comment]
> So the server is on 1.12 and you're joining with 1.8?

no, the server is 1.8 and im joining with 1.12
