### ISSUE TITLE
Add a Function

### ISSUE THREAD

**Issue by TimeLessHD** [dmulloy2/ProtocolLib#1549]
It would be awesome to add a thing in the config to turn off the Error messages in the main game chat

**Comment by derklaro** [comment]
Hi, do you mind providing more details? Like for example a screenshot / the content of the message you mentioned

**Comment by TimeLessHD** [comment]
https://imgur.com/mbXvIUs 
this message

**Comment by dmulloy2** [comment]
Should be available in the latest dev builds. You can also remove the `protocol.info` permission from players in the meantime if you want to stick to releases
