### ISSUE TITLE
[5.0] receiveClientPacket broke API compatibility, and is also broken itself

### ISSUE THREAD

**Issue by bergerkiller** [dmulloy2/ProtocolLib#1552]
**Describe the bug**
ProtocolLib 5.0 removed the old (typo'd) recieveClientPacket and replaced it with receiveClientPacket, which has an extra boolean parameter. While trying to work around this issue I now find that the new method throws an UnsupportedOperationException when called.

Exception: https://paste.traincarts.net/uvafakocaf.php

**To Reproduce**
1. Install BKCommonLib from here ( https://ci.mg-dev.eu/job/BKCommonLib/1268/ )
2. Install Traincarts and TC-Coasters
3. Go near to a TCC node and left-click to select it
4. TCC cancels the original packets and enqueues a different interaction packet instead (to prevent nodes' invisible entities breaking block breaking nearby)
5. ProtocolLib throws an exception: https://paste.traincarts.net/uvafakocaf.php

**Expected behavior**
No exception.

**Version Info**
https://paste.traincarts.net/nunoderiji.pl

**Additional context**
In case this was due to calling it while handling the send of another packet, I also tried calling that method in a next-tick task. The same happened, so this isnt the cause here. ( https://paste.traincarts.net/ibaqogeyiz.m )

Code involves at-runtime generated code. But the basics boil down to this small adaptor snippet being called from receivePacket() further down below. https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/network/ProtocolLibPacketHandler.java#L85
```
Player player = ...
Object packet = ...
PacketContainer toReceive = new PacketContainer(PacketRegistry.getPacketType(packet.getClass()), packet);
ProtocolLibrary.getProtocolManager().receiveClientPacket(player, toReceive, true);
```

**Comment by derklaro** [comment]
Actually looking at the `setCancelled` code it's just more legacy code which had no function in v4 anyway... Probably going to remove that as well 🤔 

(`setCancelled` would throw an exception in v4 as well but is based on `isCancelled` which is always `false` in that context by default)

**Comment by bergerkiller** [comment]
Can you link a jar to test that commit I can give those changes a test too? :)

**Comment by derklaro** [comment]
Sure, https://github.com/derklaro/ProtocolLib/suites/5812117406/artifacts/194536192

**Comment by bergerkiller** [comment]
Works great, no errors, and looks like the packet is handled correctly when I click at the entity. Of course the async listener issue is still there but I assume one jar only contains the fixes of one PR at a time.

**Comment by derklaro** [comment]
Yes, it only contains the fix for this issue :)
