### ISSUE TITLE
1.9: Missing wrappers for SoundCategory and MobEffectList

### ISSUE THREAD

**Issue by MyzelYam** [dmulloy2/ProtocolLib#156]
It looks like REMOVE_ENTITY_EFFECT and NAMED_SOUND_EFFECT packets don't have the same fields as documented on wiki.vg, this is what they are currently like (coded a quick overview which shows the amount and type of the fields):
```
[16:03:52 INFO]: [PremiumVanish] DEBUG: Packet Fields of type NAMED_SOUND_EFFECT
[16:03:52 INFO]: getFloat: 1
[16:03:52 INFO]: getModifier: 7 (SoundCategory, SoundCategory, SoundCategory, SoundCategory, SoundCategory, SoundCategory, SoundCategory)
[16:03:52 INFO]: getIntegers: 4
[16:03:52 INFO]: END
[16:03:52 INFO]: [PremiumVanish] DEBUG: Packet Fields of type REMOVE_ENTITY_EFFECT
[16:03:52 INFO]: getModifier: 2 (MobEffectList, MobEffectList)
[16:03:52 INFO]: getIntegers: 1
[16:03:52 INFO]: END
```

Since SoundCategory and MobEffectList are NMS classes we can't read/modify the fields without NMS code anymore.

**Comment by Rocknest** [comment]
ProtocolLib reads/writes JAVA FIELDS in packet classes

**Comment by MyzelYam** [comment]
So we need a wrapper?

**Comment by games647** [comment]
@MyzelYam Do you used http://wiki.vg/Pre-release_protocol ?

**Comment by MyzelYam** [comment]
@games647 I've looked at both the pre-release protocol and the current protocol on wiki.vg, and both show different fields than there actually are on the server, since there actually is a NMS class to represent the effects/sound categories we need a wrapper to be able to read them again.

**Comment by dmulloy2** [comment]
The actual memory representation and the documentation on the wiki are slightly different. ProtocolLib reads from the memory representation (you can find it in the decompile folder when you build Spigot). The wiki documents what is actually sent to the client in serialized form.

**Comment by dmulloy2** [comment]
While I look into making wrappers, you can still use the fields. You can use the packet's base modifier to grab the field, then use another structure modifier to read and modify that object's fields. Basically what wrappers do.
