### ISSUE TITLE
Cancel PLAYER_INFO outgoing packets = all players are invisible

### ISSUE THREAD

**Issue by sgdc3** [dmulloy2/ProtocolLib#157]
With 1.7 and 1.8 cancelling this packet only hide players from the tablist, but now everyone seems inisible.
Original issue: https://github.com/Xephi/AuthMeReloaded/issues/576

**Comment by dmulloy2** [comment]
This may be an issue with Minecraft itself. I don't know enough about authme to be entirely sure though.

**Comment by games647** [comment]
>This may be an issue with Minecraft itself. 

Indeed: See:

>[Spawn Player](http://wiki.vg/Protocol#Spawn_Player)
[...]This packet must be sent after the Player List Item (Play, 0x38, clientbound) packet that adds the player data for the client to use when spawning a player. **If the tab list entry for the UUID included in this packet is not present when this packet arrives, the entity will not be spawned.** The tab includes skin/cape data. [...]

**Comment by sgdc3** [comment]
Damn Mojang xD

**Comment by dmulloy2** [comment]
I'd be happy to help with this on ProtocolLib's end, but this looks like an internal MC issue.

**Comment by sgdc3** [comment]
@dmulloy2 Maybe if we send the player_info before a player spawns and then we empty the tablist?
