### ISSUE TITLE
FieldAccessException "flags" field of type byte in Play.Server.Abilities cannot be accessed in my plugin? 

### ISSUE THREAD

**Issue by TheRealWHfan** [dmulloy2/ProtocolLib#1571]
**Describe the bug**

The byte field in play.server.abilities through packetcontainer.getBytes doesn't exist when it should in my custom plugin. I expected it to write the new byte into the packet instead of giving an error as the flags field exists on https://wiki.vg/Protocol#Player_Abilities_.28clientbound.29

**To Reproduce**
1. Run a server with protocollib and your own plugin 
2. Run 3 lines of the following code anywhere in your plugin:
<img width="684" alt="Screen Shot 2022-04-08 at 1 24 27 pm" src="https://user-images.githubusercontent.com/39373178/162356802-b44671a5-fa3f-4ccc-8485-dc6ce1a2d965.png">
3. See the error:
<img width="1403" alt="Screen Shot 2022-04-08 at 1 17 46 pm" src="https://user-images.githubusercontent.com/39373178/162357149-c3e9d6de-d0e0-49a3-83e0-d66c9ad005d3.png">

Version Info:
https://pastebin.com/xTF5tZqN

**Additional context**
The flags field exists when listening to packets being sent to cilent.

**Comment by lukalt** [comment]
The encoding documented on wiki.vg does not always match how the Minecraft internally stores the packet data. In this case, the byte flag is decoded into different booleans. With ProtocolLib, you can only access the fields of the corresponding Packet class, e.g. `PacketPlayOutAbilities` / `ClientboundPlayerAbilitiesPacket` in this case. In 1.19.4, it contains the following field: 
![image](https://user-images.githubusercontent.com/9149282/233854828-1c758e87-2414-403e-8ce9-89cd529406cb.png)
