### ISSUE TITLE
ProtocolLibs Console Errors

### ISSUE THREAD

**Issue by BboyZeroOne** [dmulloy2/ProtocolLib#1573]
**Describe the bug**
Console Errors when running latest version of ProtocolLibs 4.8.0 
Console Error Messages
https://pastebin.com/S8UVGkcD

**To Reproduce**
No steps. But I believe it is caused when using LargeRaids plugin.

**Expected behavior**
No console errors/server crash.

**Screenshots**
-

**Version Info**
https://pastebin.com/TejnGq3G

**Additional context**
-

**Comment by derklaro** [comment]
This is a QualityArmory bug and not related to ProtocolLib
