### ISSUE TITLE
Add documentation and sources

### ISSUE THREAD

**Issue by Scrayos** [dmulloy2/ProtocolLib#158]
Hey,

I looked into the POM and I've seen that there's a profile called `release-sign-artifacts`. Apparently there seem to be neither sources nor a java-documentation in the repository. Could you add this profile at least for the release of milestone-artifacts?

I'd really appreciate a documentation from within my IDE aswell as the sources.

**Comment by dmulloy2** [comment]
I thought maven automatically downloaded the documentation? At any rate, I'll try to remember that next time I release a build.

**Comment by Scrayos** [comment]
Maven only automatically downloads documentation and sources if they're generated. But they aren't even generated and that's why they're not in your repo aswell.

**Comment by games647** [comment]
Any news on this?

**Comment by dmulloy2** [comment]
It's mostly something I have to remember when releasing versions, not really something that can be changed code wise.

**Comment by nullEuro** [comment]
+1 I would appreciate that too! You also could configure maven to automatically generate sources and docs for each deployment.

**Comment by dmulloy2** [comment]
@nullEuro I believe it's already configured to do so, I just keep forgetting to set the flag when releasing.

**Comment by dmulloy2** [comment]
_Should_ be included in the 4.2.0 release, I think I got it working.

**Comment by games647** [comment]
Yes it works for 4.2. Thank you.
