### ISSUE TITLE
Cannot retrieve entity from ID when upgrade from 4.6.0 to 4.8.0

### ISSUE THREAD

**Issue by jiongjionger** [dmulloy2/ProtocolLib#1595]
Describe the bug
Cannot retrieve entity from ID when upgrade ProtocolLib from 4.6.0 to 4.8.0.

Server version: 1.12.2 Paper

I also tried to upgrade the error reporting plugin to the latest version, which didn't help anything.

https://pastebin.com/RyecwVLR
https://pastebin.com/cGKZ0uC1
https://pastebin.com/tbeTpGG8

**Comment by jiongjionger** [comment]
I tried 4.7.0, and it's the same problem. 4.6.0 and 4.4.0 is work fine.

**Comment by daboluo666** [comment]
@dmulloy2 me too

**Comment by SkyLicks** [comment]
This is caused by all listeners being in async by default. 
https://www.spigotmc.org/threads/protocollib-get-entity-from-entityid-error.550321/

Newest version of protocol lib adds a listener option for forced-sync listeners.
