### ISSUE TITLE
Client Packets

### ISSUE THREAD

**Issue by Storkclips** [dmulloy2/ProtocolLib#1597]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Either freshly logged in after a restart, I've got some ideas about what is causing it- but not sure.

**Screenshots**
18.05 00:14:01 [Server] Netty Epoll Server IO #6/INFO Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@43d7610.
18.05 00:14:01 [Server] Netty Epoll Server IO #6/ERROR INTERNAL ERROR: Unable to intercept a read client packet.
18.05 00:14:01 [Server] INFO If this problem hasn't already been reported, please open a ticket
18.05 00:14:01 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
18.05 00:14:01 [Server] INFO Stack Trace:
18.05 00:14:01 [Server] INFO java.lang.RuntimeException: Error occured while instancing generated class.
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
18.05 00:14:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18.05 00:14:01 [Server] INFO at net.minecraft.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:85)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18.05 00:14:01 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18.05 00:14:01 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18.05 00:14:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18.05 00:14:01 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
18.05 00:14:01 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
18.05 00:14:01 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
18.05 00:14:01 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
18.05 00:14:01 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
18.05 00:14:01 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:831)
18.05 00:14:01 [Server] INFO Caused by: java.lang.reflect.InvocationTargetException
18.05 00:14:01 [Server] INFO at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
18.05 00:14:01 [Server] INFO at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
18.05 00:14:01 [Server] INFO at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
18.05 00:14:01 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
18.05 00:14:01 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
18.05 00:14:01 [Server] INFO ... 38 more
18.05 00:14:01 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
18.05 00:14:01 [Server] INFO at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_CHandshakePacket$java_lang_Object.<init>(Unknown Source)
18.05 00:14:01 [Server] INFO ... 44 more

**Version Info**
ProtocolLib Dump
Timestamp: 05/18/22 04:17:17

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.16.5-R0.1-SNAPSHOT
Server Version: 1.16.5-989 (MC: 1.16.5)
Java Version: 16.0.1

ProtocolLib: com.comphenix.protocol.ProtocolLib@297fb2d7[
  statistics=com.comphenix.protocol.metrics.Statistics@42ab3dcd
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1566bebf
  packetTask=8
  tickCounter=29726
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2fcd1228
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@7a020bc1
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@2e3fe75c
  commandProtocol=com.comphenix.protocol.CommandProtocol@3561e203
  commandPacket=com.comphenix.protocol.CommandPacket@15d22156
  commandFilter=com.comphenix.protocol.CommandFilter@7fe46c2e
  packetLogging=com.comphenix.protocol.PacketLogging@2eb07189
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@147befa6
  server=CraftServer{serverName=Mohist,serverVersion=1.16.5-989,minecraftVersion=1.16.5}
  file=plugins/ProtocolLib (1).jar
  description=org.bukkit.plugin.PluginDescriptionFile@10a7a4ee
  dataFolder=plugins/ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@6707e51d
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=org.bukkit.plugin.PluginLogger@61ef23e7
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@1fb25665[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2fcd1228
  packetListeners=[PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=MycteriaCombat, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ProMaintenanceMode, sending=ListeningWhitelist[priority=HIGHEST, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=HIGHEST, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=MycteriaEconomy, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@62691b7e
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1d8ba50d
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1007c9a7
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@579cc5dd
  hasClosed=false
  classLoader=org.bukkit.plugin.java.PluginClassLoader@6707e51d
  reporter=com.comphenix.protocol.ProtocolLib$1@7d0486bb
  server=CraftServer{serverName=Mohist,serverVersion=1.16.5-989,minecraftVersion=1.16.5}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@13034b21
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=5
  phasePlayingCount=9
  packetCreation=true
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@70e052c9
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@54f1273a
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.16.5)
  debug=false
]

Listeners:
litebans.gV@4c26be46[
  e=litebans.bD@2a22e6a3
  d=litebans.bO@78fb7dd
  g=litebans.bj@3ab2c89b
  b=litebans.by@22da2431
  h=LiteBans v2.9.3
  plugin=LiteBans v2.9.3
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
litebans.hV@62c0ffb1[
  a=litebans.bj@3ab2c89b
  e=LiteBans v2.9.3
  plugin=LiteBans v2.9.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener@4e6a6d5e[
  plugin=ServerListPlus v3.4.8
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
com.okgabe.mycteriacombat.event.EntityPacketListener@46bb8310[
  plugin=MycteriaCombat v0.51
  plugin=MycteriaCombat v0.51
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2]], gamephase=PLAYING, options=[]]
]
com.hotmail.AdrianSR.ProMaintenanceMode.Bukkit.Main.ProtocolLibHandler$StatusPacketListener@4c0b3f86[
  plugin=ProMaintenanceMode v1.0.5
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
me.spiderdeluxe.mycteriaeconomy.lib.fo.PacketUtil$2@54ff302[
  type=SET_SLOT[class=PacketPlayOutSetSlot, id=22]
  plugin=MycteriaEconomy v0.6
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
MycteriaCombat by []
MycteriaEconomy by [SpiderDeluxe]
ProMaintenanceMode by [AdrianSR]
LiteBans by [Ruan]
ServerListPlus by [Minecrell <https://github.com/Minecrell>]

**Comment by derklaro** [comment]
Mohist is not supported (as they for example change class names as you can see), please switch Spigot (or a fork of spigot)

**Comment by Storkclips** [comment]
Aight. MOOOOOOHIST!!!!
