### ISSUE TITLE
Crashing on 1.19

### ISSUE THREAD

**Issue by HenrikoMagnifico** [dmulloy2/ProtocolLib#1606]
**Describe the bug**
This is of course something to be expected, since it's a major update after all. Just wanted to chime in and let you know! 

**To Reproduce**
1. Start a 1.19 Spigot server with Protocollib installed.
2. See the plugin fail to load.

**Expected behavior**
For the plugin to load without errors.

**Screenshots**
![2022-06-07_18 59 44](https://user-images.githubusercontent.com/11783274/172440432-8ec2693c-d4f1-4d03-b8a7-07bdabd0b944.png)

**Version Info**
[https://pastebin.com/43nvgvKa](https://pastebin.com/43nvgvKa)

**Additional context**
Crash log: [https://www.toptal.com/developers/hastebin/udigegekas.properties](https://www.toptal.com/developers/hastebin/udigegekas.properties)

**Comment by derklaro** [comment]
Just give us some time to update... As you can see https://github.com/dmulloy2/ProtocolLib/pull/1601 is still a work in progress

**Comment by derklaro** [comment]
You can download a version which runs on 1.19 from [here](https://cdn.discordapp.com/attachments/946646266811674714/983826994934468658/ProtocolLib.jar). Please provide feedback if something is not working in the pull request i linked earlier. Thanks for the patience :)

**Comment by dmulloy2** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
