### ISSUE TITLE
[1.19] Unable to intercept a read client packet

### ISSUE THREAD

**Issue by noiverre** [dmulloy2/ProtocolLib#1608]
**Error log**
https://paste.gg/p/anonymous/36842c054e484c42a6f40079e35652c2

**Version Info**
https://paste.gg/p/anonymous/625307a7b3cb4a43b9c10839f18a6cb6

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support
