### ISSUE TITLE
PacketType.Status.Server.SERVER_INFO listeners not firing

### ISSUE THREAD

**Issue by LOOHP** [dmulloy2/ProtocolLib#1620]
**Describe the bug**
The following code never gets called despite clients pinging the server for status. (The packet itself did reach the client)
```java
protocolManager.addPacketListener(new
 PacketAdapter(PacketAdapter.params().plugin(plugin).types(PacketType.Status.Server.SERVER_INFO)) {
            @Override
            public void onPacketSending(PacketEvent event) {
                   ...
            }
});
```

**Expected behavior**
Gets called whenever a server info response is sent to clients.

**Version Info**
[dump-2022-06-10_13.48.17.txt](https://github.com/dmulloy2/ProtocolLib/files/8876081/dump-2022-06-10_13.48.17.txt)

**Comment by LOOHP** [comment]
btw WrappedServerPing should probably include the new "previewsChat" field.

**Comment by derklaro** [comment]
Can you try it with https://cdn.discordapp.com/attachments/896044362427949087/984792523904012288/ProtocolLib.jar please?

**Comment by LOOHP** [comment]
Will do, in a moment.

**Comment by LOOHP** [comment]
I can confirm it is working, thanks for the quick fix!
