### ISSUE TITLE
1.19 Dev Builfd

### ISSUE THREAD

**Issue by matipoirierg** [dmulloy2/ProtocolLib#1631]
I've been testing 1.19, with the 567 protocollib build. I have an issue, my server tps drops to 0.3 (yes, that laggy) because of protocolib.
https://timings.aikar.co/?id=1f72d716285e4b86972a05d03d7b3603#

**Comment by derklaro** [comment]
Please use spark to attach performance metrics, timings are not helping at all

**Comment by MrRockis** [comment]
This happened to us as well. It started happening with build #566. Build #565 works without any issues.

**Comment by derklaro** [comment]
Again, please attach a spark profile result so that I can analyze and resolve the issue 🤔

**Comment by derklaro** [comment]
So I just did a quick test so and cannot reproduce this, please provide more information in order for me to help :/
![image](https://user-images.githubusercontent.com/40468651/173232199-540e5dc8-4359-4ff2-80ee-306b438585f6.png)

**Comment by MrRockis** [comment]
Hopefully this will help you finding the cause of the issue. https://spark.lucko.me/ylIKIBxwIQ

It is somehow connected to PremiumVanish plugin, but this issue started happening after commit https://github.com/dmulloy2/ProtocolLib/commit/4db1e39ac76743bf1775249c1749161dd5f4909e (Build #566).

**Comment by derklaro** [comment]
Can you also attach the protocollib dump? (`/protocol dump`)

**Comment by MrRockis** [comment]
Here you go. Let me know if you need something else
[dump-2022-06-12_15.51.09.txt](https://github.com/dmulloy2/ProtocolLib/files/8885856/dump-2022-06-12_15.51.09.txt)
.

**Comment by derklaro** [comment]
I wasn't able to reproduce this, but after looking closely at the commit again I noticed that the check if the packet write was actually called from the event loop was missing (I am 100% sure I had that check, but I removed it again or smth)... Could you please test if the issue still persists with https://github.com/derklaro/ProtocolLib/suites/6897607157/artifacts/267594273 ?

**Comment by Brokkonaut** [comment]
I had the same issue with extreme lags and did some profiling, it is mostly that com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID() now is horrible slow, the previous version of protocollib i used (some build from early 1.18.2) did not have this issue.

**Comment by derklaro** [comment]
This is definitely not related to this issue, but being worked on: #1566

**Comment by Brokkonaut** [comment]
> This is definitely not related to this issue, but being worked on: #1566

Ok, thats great, i had to remove protocollib and all dependent plugins for now.

**Comment by MrRockis** [comment]
> I wasn't able to reproduce this, but after looking closely at the commit again I noticed that the check if the packet write was actually called from the event loop was missing (I am 100% sure I had that check, but I removed it again or smth)... Could you please test if the issue still persists with https://github.com/derklaro/ProtocolLib/suites/6897607157/artifacts/267594273 ?

This issue is still happening with this build.

**Comment by matipoirierg** [comment]
I'm sorry I can't achieve a spark timing right now, not in my home but I think the issue is causes for using PremiumVanish, @MrRockis Do you use premium vanish?

**Comment by derklaro** [comment]
He is. Unforntanetly I cannot see the source code of it, so it's a bit hard to track down the issue :/ - will give it a shot again now

**Comment by derklaro** [comment]
Okay, after giving it some attempts to reproduce it seems that I actually found the issue: PremiumVanish seems to clone some packets during sending which marks them incorrectly as non-processed causing an infinite loop. I've fixed that now, could you please give https://github.com/derklaro/ProtocolLib/suites/6899303438/artifacts/267710223 a try?

**Comment by ILikeOrangeJuice** [comment]
I also had insane TPS drops with the latest official dev version on 1.19 (basically looping to death), tried this last posted version above this post now and it for now seems to be resolved, Ram usage is normal, tps constant 20, Paper mspt around same values as 1.18 server version, no issues with plugins hooking into Protocollib.
Will update if any errors occour, but as said, seems to be fixed, at least for me, for now!:)

**Comment by victorlindox** [comment]
Hello, I have a problem on my server with Lag, TPS is lowering to 15 and MSPT going over 70, all sparks accuse ProtocolLib as the cause of the lag, but I've tried everything but the lag continues, it does This has been happening for about 2 weeks.
Could anyone help?
ProtocolLib is up to date with the latest Dev Build, and Purpur is up to date on 1.19 and the latest update.
https://spark.lucko.me/ouLYG9rxIZ

**Comment by victorlindox** [comment]
![Sem título](https://user-images.githubusercontent.com/41601203/180112075-f4e1d9ea-f231-4a7e-a021-1ab88801fe51.png)
