### ISSUE TITLE
1.19 Spawn Entity does not respect entity id

### ISSUE THREAD

**Issue by Chasewhip8** [dmulloy2/ProtocolLib#1632]
**Describe the bug**
In 1.19 with latest dev build, the spawn entity packet does not respect the type written to position 1 as follows:

        packet.getIntegers()
                .write(0, id)
                .write(1, 52);
        
Where 52 should be a magma slime, it always spawns an allay regardless of id.

**To Reproduce**
1. Attempt to spawn a magma slime with the spawn entity packet in 1.19

**Expected behavior**
Spawns a magma slime

**Version Info**
https://pastebin.com/jny2bccF

**Comment by derklaro** [comment]
You need to use the entity type modifier, you are editing something else.
