### ISSUE TITLE
1.19 spam errors in the chat

### ISSUE THREAD

**Issue by phillipunzen** [dmulloy2/ProtocolLib#1633]
**Describe the bug**
If you install the plugin in 1.19, it throws a lot of errors into the chat. These errors occur randomly.

**To Reproduce**
1. Install the plugin
2. Join the Server
3. Open the Chat

**Screenshots**
![Screenshot 2022-06-12 134945](https://user-images.githubusercontent.com/58786365/173231723-3b8b3877-2c9f-44b2-8903-bf5af6ba3bca.png)

**Version Info**
https://pastebin.com/0dtp0Bfs

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support
