### ISSUE TITLE
[5.0.0-SNAPSHOT] Nexus repository doesn't have the latest version

### ISSUE THREAD

**Issue by diogotcorreia** [dmulloy2/ProtocolLib#1634]
I'm updating my plugin to 1.19, but ProtocolLib's Nexus Repository doesn't have the latest commits that implement 1.19 support (from the Nexus browse menu, [I can see the latest build is from June 3rd](https://repo.dmulloy2.net/#browse/browse:public:com%2Fcomphenix%2Fprotocol%2FProtocolLib%2F5.0.0-SNAPSHOT%2F5.0.0-20220603.031413-2)).

I can compile ProtocolLib locally and that works for development, but my CI is failing because of this: https://github.com/tritonmc/Triton/pull/196

If relevant, this is my Gradle configuration:
https://github.com/tritonmc/Triton/blob/bfb87b2404183e455c7262af1f5b1b03d1d1fad0/build.gradle#L35
https://github.com/tritonmc/Triton/blob/bfb87b2404183e455c7262af1f5b1b03d1d1fad0/core/build.gradle#L19

Would it be possible to release a new build?

Thank you for the awesome work!

**Comment by derklaro** [comment]
For now, please use jitpack instead which always provides you with the latest version available: https://jitpack.io/#dmulloy2/ProtocolLib/master-SNAPSHOT

**Comment by dmulloy2** [comment]
should be updated on nexus now as well
