### ISSUE TITLE
Error message when using plugin with obfuscator

### ISSUE THREAD

**Issue by TecEash1** [dmulloy2/ProtocolLib#1635]
**Describe the bug**
I keep getting this message 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/92249532/173247691-3f8f316c-171d-4463-99c2-059d3ebcac60.png">

I am on the latest version of the plugin - also I am tring to use the latest (1.19) version of the obfuscator plugin with this

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support
