### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LittleDuck363** [dmulloy2/ProtocolLib#1640]
I dont know what's going on and from what I can find yall don't have a discord so I can't ask there. Here's my pastebin

https://pastebin.com/njhjTbqh

**Comment by derklaro** [comment]
Please use the latest development build from [https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/%C2%A0to) get 1.19 support
