### ISSUE TITLE
FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.

### ISSUE THREAD

**Issue by JhordanPG** [dmulloy2/ProtocolLib#1649]
I get the following error and I can't find a way to fix it, I attach the server logs.

Minecraft Versión 1.19 - Build 569
https://pastebin.com/4kr5Dhwh <- Here I attach more details of the problem.

![image](https://user-images.githubusercontent.com/42554918/173744432-39258d1a-7831-4bfb-b89b-a1f25698a57e.png)
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/8905909/latest.log)

**Comment by matipoirierg** [comment]
Detailed error with debug: https://pastebin.com/4kr5Dhwh

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by matipoirierg** [comment]
> Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

he is using latest

**Comment by JhordanPG** [comment]
> Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

I am using the latest version.

**Comment by JhordanPG** [comment]
https://pastebin.com/qjiYVMZf <- The previous errors disappeared... Now I only get this one...

**Comment by JhordanPG** [comment]
> https://pastebin.com/qjiYVMZf <- The previous errors disappeared... Now I only get this one...

It doesn't always come out, sometimes it comes out and sometimes it doesn't.

**Comment by PhoenixCodingStuff** [comment]
can confirm , same error on latest version on 1.19^
