### ISSUE TITLE
error on disable

### ISSUE THREAD

**Issue by FakEEE14** [dmulloy2/ProtocolLib#1650]
**Describe the bug**
it's happen when i try to shotdown my server

**To Reproduce**
just intall the snapshot 569 and shotdown your server

**Expected behavior**
expect no errors on shotdown

**Screenshots**
![image](https://user-images.githubusercontent.com/68513641/173790156-f89e0f02-7544-45b0-863c-4382047629b1.png)
![image](https://user-images.githubusercontent.com/68513641/173790202-8dae0182-4184-42af-966e-83de7125919c.png)

**Version Info**
snapshot - build 569

**Comment by derklaro** [comment]
This seems to be a case where a player connects while the server is shutting down, but the channel was injected before - I would say that you can ignore that, there is not much we can do to prevent this from happening :/

**Comment by FakEEE14** [comment]
but the server is empty and whitelisted
