### ISSUE TITLE
I'm getting this error when I start my server up

### ISSUE THREAD

**Issue by strikeknight57** [dmulloy2/ProtocolLib#1652]
I haven't had a chance to hop on the server while this error has popped up. but it asked that I post it here.

To reproduce the error I am running on a paper client. Other than that I don't know what would have to be done.

Here is the error information:

> [09:50:00 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
>   If this problem hasn't already been reported, please open a ticket
>   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>   Stack Trace:
>   java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
>         at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
>         at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
>         at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
>         at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
>         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>         at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
>         at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
>         at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
>         at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
>         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
>         at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:833)
>   Dump:
>   Parameters:
>     io.netty.buffer.PooledUnsafeDirectByteBuf@7bf3043e[
>       memoryAddress=2671369015360
>       recyclerHandle=io.netty.util.Recycler$DefaultHandle@255297c6
>       chunk=Chunk(55e6c501: 1%, 24576/4194304)
>       handle=1125929971613696
>       memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
>       offset=16384
>       length=9
>       maxLength=16
>       cache=io.netty.buffer.PoolThreadCache@60472455
>       tmpNioBuf=<null>
>       allocator=PooledByteBufAllocator(directByDefault: true)
>       refCnt=2
>       readerIndex=9
>       writerIndex=9
>       markedReaderIndex=0
>       markedWriterIndex=0
>       maxCapacity=2147483647
>     ]
>     manager:
>       com.comphenix.protocol.injector.PacketFilterManager@83aa3e8[
>         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3b0b86de
>         packetListeners=[]
>         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@536403b2
>         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@30814787
>         inputBufferedPackets=[]
>         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6d79879c
>         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@aa3d19b
>         hasClosed=false
>         classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
>         reporter=com.comphenix.protocol.ProtocolLib$1@43aee733
>         server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.19}
>         library=ProtocolLib v4.8.0
>         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@76f1e776
>         knowsServerPackets=true
>         knowsClientPackets=true
>         phaseLoginCount=0
>         phasePlayingCount=0
>         packetCreation=false
>         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3fbc34ac
>         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3d7c97a
>         hasRecycleDistance=true
>         minecraftVersion=(MC: 1.19.0)
>         debug=false
>       ]
>   Sender:
>     com.comphenix.protocol.injector.netty.ChannelInjector@14303c82[
>       decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
>       encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
>       factory=com.comphenix.protocol.injector.netty.InjectionFactory@4c6839ca
>       player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@59a9c8e9
>       updated=<null>
>       playerName=<null>
>       playerConnection=<null>
>       networkManager=net.minecraft.network.NetworkManager@12b3bf7
>       originalChannel=org.geysermc.geyser.network.netty.ChannelWrapper@18dffb16
>       channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@12b3bf7, previous=org.geysermc.geyser.network.netty.ChannelWrapper@18dffb16, current=com.comphenix.protocol.injector.netty.ChannelInjector$3@30e19c7a, previousLoaded=true, currentSet=true, forceAccess=true]
>       packetMarker={}
>       currentEvent=<null>
>       finalEvent=<null>
>       unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@10b225ca
>       vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@2c0c79ea
>       vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@4c54d8f8
>       finishQueue=[]
>       channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@3fbc34ac
>       processor=com.comphenix.protocol.injector.NetworkProcessor@161a65e2
>       injected=true
>       closed=false
>       cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
>       cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@59969de2
>       singleDecode=false
>       first=true
>       firedChannelRead=false
>       selfFiredChannelRead=true
>       decodeState=1
>       discardAfterReads=16
>       numReads=0
>       added=true
>     ]
>   Version:
>     ProtocolLib v4.8.0
>   Java Version:
>     17.0.1
>   Server:
>     git-Paper-17 (MC: 1.19)

**Version Info**
I'm running the latest version of protocolLib on paper 1.19-17

**Additional context**

**Comment by AlexanderOFGR** [comment]
ProtocolLib v4.8.0 does not support 1.19. Update to a dev version or wait for a stable release

**Comment by AlexanderOFGR** [comment]
Sorry for the late response! Download the latest dev build here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
