### ISSUE TITLE
error 1.19 ProtocolLib

### ISSUE THREAD

**Issue by SteveImStuck** [dmulloy2/ProtocolLib#1654]
ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19-R0.1-SNAPSHOT
Server Version: git-Paper-18 (MC: 1.19)
Java Version: 17.0.3.1

ProtocolLib: com.comphenix.protocol.ProtocolLib@7b536d71[
  statistics=com.comphenix.protocol.metrics.Statistics@eed398c
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@42f21797
  packetTask=2
  tickCounter=11718
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@28177251
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@542b3758
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@34f3e049
  commandProtocol=com.comphenix.protocol.CommandProtocol@53b58e02
  commandPacket=com.comphenix.protocol.CommandPacket@1a9754c
  commandFilter=com.comphenix.protocol.CommandFilter@c3503d6
  packetLogging=com.comphenix.protocol.PacketLogging@27ef4bb1
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@585504d0
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-18,minecraftVersion=1.19}
  file=plugins\ProtocolLib (2).jar
  description=org.bukkit.plugin.PluginDescriptionFile@129c0983
  dataFolder=plugins\ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib (2).jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins\ProtocolLib\config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@6bfce415
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@379bf891[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@28177251
  packetListeners=[]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1794445c
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@238ad8ae
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4bbdf33e
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@582b85e2
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib (2).jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@189276ac
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-18,minecraftVersion=1.19}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3812d476
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=0
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1ae8d095
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@14ed4f50
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.0)
  debug=false
]

No listeners

**Comment by ifloppy** [comment]
Same problem

**Comment by AlexanderOFGR** [comment]
ProtocolLib v4.8.0 does not support your version (1.19). Wait for the next stable release or download a dev build

**Comment by Relozan2006** [comment]
use dev builds: https://ci.dmulloy2.net/job/ProtocolLib/
