### ISSUE TITLE
 [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by MM4004** [dmulloy2/ProtocolLib#1660]
**Describe the bug**
Long console spaming error

**To Reproduce**
1. Player using lunarclient, and join to server

**Expected behavior**
Many lines in console

**Screenshots**
I not have screenshot but i have copy of log
[16:04:29] [Netty Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@28bf5cd5[
      memoryAddress=2977200889920
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@5ce3fec
      chunk=Chunk(372bd581: 14%, 565248/4194304)
      handle=14073813260042240
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=204800
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@8107939
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@33986394[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2f77e800
        packetListeners=[PacketAdapter[plugin=TabList, sending=ListeningWhitelist[priority=HIGH, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@68d9db43
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1378c04
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6e52f502
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@73cff309
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@fc40aed
        reporter=com.comphenix.protocol.ProtocolLib$1@139c75b8
        server=CraftServer{serverName=CraftBukkit,serverVersion=3507-Spigot-fa893f0-c3f219e,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7eb243d3
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65fd6c2f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4018848e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@3882113a[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@42e5f8bc
      player=CraftPlayer{name=MMgame4}
      updated=<null>
      playerName=MMgame4
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2aa71ff1
      originalChannel=[id: 0xb1209e45, L:/127.0.0.1:4040 - R:/127.0.0.1:61533]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2aa71ff1, previous=[id: 0xb1209e45, L:/127.0.0.1:4040 - R:/127.0.0.1:61533], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@c69d622, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@24ca1d54
      vanillaDecoder=net.minecraft.network.PacketDecoder@3600c6ab
      vanillaEncoder=net.minecraft.network.PacketEncoder@2b0dd768
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65fd6c2f
      processor=com.comphenix.protocol.injector.NetworkProcessor@1d435c36
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@49ea7931
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    3507-Spigot-fa893f0-c3f219e (MC: 1.19)

**Version Info**
I see this in log but if missing i can add

**Additional context**
None

**Comment by bensuperpc** [comment]
I confirm this bug with **Purpur 1668 and Paper 28** in 1.19, There is no longer this problem on build 569 : https://ci.dmulloy2.net/job/ProtocolLib/569/

**Comment by AmitYT3** [comment]
> **Describe the bug** Long console spaming error
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Player using lunarclient, and join to server
> 2. See error
> 
> **Expected behavior** Many lines in console
> 
> **Screenshots** I not have screenshot but i have copy of log [16:04:29] [Netty Server IO #1/ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet. If this problem hasn't already been reported, please open a ticket at https://github.com/dmulloy2/ProtocolLib/issues with the following data: Stack Trace: java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397) at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658) at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.base/java.lang.Thread.run(Thread.java:833) Dump: Parameters: io.netty.buffer.PooledUnsafeDirectByteBuf@28bf5cd5[ memoryAddress=2977200889920 recyclerHandle=io.netty.util.Recycler$DefaultHandle@5ce3fec chunk=Chunk(372bd581: 14%, 565248/4194304) handle=14073813260042240 memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304] offset=204800 length=34 maxLength=48 cache=io.netty.buffer.PoolThreadCache@8107939 tmpNioBuf= allocator=PooledByteBufAllocator(directByDefault: true) refCnt=2 readerIndex=34 writerIndex=34 markedReaderIndex=0 markedWriterIndex=0 maxCapacity=2147483647 ] manager: com.comphenix.protocol.injector.PacketFilterManager@33986394[ unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2f77e800 packetListeners=[PacketAdapter[plugin=TabList, sending=ListeningWhitelist[priority=HIGH, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@68d9db43 playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1378c04 inputBufferedPackets=[] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6e52f502 sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@73cff309 hasClosed=false classLoader=org.bukkit.plugin.java.PluginClassLoader@fc40aed reporter=com.comphenix.protocol.ProtocolLib$1@139c75b8 server=CraftServer{serverName=CraftBukkit,serverVersion=3507-Spigot-fa893f0-c3f219e,minecraftVersion=1.19} library=ProtocolLib v4.8.0 asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7eb243d3 knowsServerPackets=true knowsClientPackets=true phaseLoginCount=0 phasePlayingCount=1 packetCreation=false nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65fd6c2f pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4018848e hasRecycleDistance=true minecraftVersion=(MC: 1.19.0) debug=false ] Sender: com.comphenix.protocol.injector.netty.ChannelInjector@3882113a[ decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception factory=com.comphenix.protocol.injector.netty.InjectionFactory@42e5f8bc player=CraftPlayer{name=MMgame4} updated= playerName=MMgame4 playerConnection= networkManager=net.minecraft.network.NetworkManager@2aa71ff1 originalChannel=[id: 0xb1209e45, L:/127.0.0.1:4040 - R:/127.0.0.1:61533] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2aa71ff1, previous=[id: 0xb1209e45, L:/127.0.0.1:4040 - R:/127.0.0.1:61533], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@c69d622, previousLoaded=true, currentSet=true, forceAccess=true] packetMarker={} currentEvent= finalEvent= unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@24ca1d54 vanillaDecoder=net.minecraft.network.PacketDecoder@3600c6ab vanillaEncoder=net.minecraft.network.PacketEncoder@2b0dd768 finishQueue=[] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65fd6c2f processor=com.comphenix.protocol.injector.NetworkProcessor@1d435c36 injected=true closed=false cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34) cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@49ea7931 singleDecode=false first=true firedChannelRead=false selfFiredChannelRead=true decodeState=1 discardAfterReads=16 numReads=0 added=true ] Version: ProtocolLib v4.8.0 Java Version: 17.0.1 Server: 3507-Spigot-fa893f0-c3f219e (MC: 1.19)
> 
> **Version Info** I see this in log but if missing i can add
> 
> **Additional context** None

Me To

**Comment by AmitYT3** [comment]
Me Toooo
