### ISSUE TITLE
Protocollib and Mypet

### ISSUE THREAD

**Issue by SrMonsterYT** [dmulloy2/ProtocolLib#1664]
when catching a frog pet this happens: 

error: https://pastebin.com/8RMJudzB
error image: https://prnt.sc/2TBrKNCY3Y2p

how to solve the problem: removing protocollib

server version: spigot/paper 1.19

ProtocolLib version: 5.0.0-SNAPSHOT-b569

**Comment by derklaro** [comment]
Please attach the protocollib dump as well

**Comment by SrMonsterYT** [comment]
> Please attach the protocollib dump as well

what is dump?
