### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by sebastiantho** [dmulloy2/ProtocolLib#1665]
**Describe the bug**
Console error.  https://pastebin.com/EzFzyyjD

**Version Info**
https://pastebin.com/7pGVpkRm

**Comment by srnyx** [comment]
Duplicate of https://github.com/dmulloy2/ProtocolLib/issues/1663

**Comment by sebastiantho** [comment]
> Duplicate of #1663

Ah my bad.
