### ISSUE TITLE
Important: Can't teleport to nether, disconnect - internal server error

### ISSUE THREAD

**Issue by freakyy85** [dmulloy2/ProtocolLib#167]
When trying to go through a nether portal, players get disconnected with the following error:

http://paste.ubuntu.com/15304737/

**Comment by dmulloy2** [comment]
This doesn't appear to be an issue with ProtocolLib - it's not mentioned anywhere in that stack.

**Comment by freakyy85** [comment]
ok. sorry then. it was a spigot bug which is fixed in the meantime. :)
