### ISSUE TITLE
Chat event is not fired on advancement chat message

### ISSUE THREAD

**Issue by Nononitas** [dmulloy2/ProtocolLib#1670]
**Describe the bug**
You can't listen to advacements messages on version 1.19 using v5 Build 569
On 1.18 it works like excepted, where you get an event fired for an advancement message

**To Reproduce**

1. Register a listener for example like that https://pastebin.com/sFkLpWfw
2. give yourself an advancement like: /advancement grant Nononitas only minecraft:adventure/ol_betsy
3. You will see that the event wasn't fired

**Expected behavior**
That the PacketType.Play.Out.Server.CHAT event is fired

**Comment by derklaro** [comment]
I suppose that the message is now send via SYSTEM_CHAT rather than the CHAT packet

**Comment by Nononitas** [comment]
Ah I see
On SYSTEM_CHAT it tells me there is no ChatBaseComponent altough it's clearly there in the packet in content or isn't it?
https://pastebin.com/SfYDigyd

**Comment by Elikill58** [comment]
> Ah I see On SYSTEM_CHAT it tells me there is no ChatBaseComponent altough it's clearly there in the packet in content or isn't it? https://pastebin.com/SfYDigyd

It seems to contains a Component object (that is from Kyori's API) and a string (which seems to be a json)

**Comment by Nononitas** [comment]
So I guess these components aren't supported?

**Comment by Nononitas** [comment]
Ok, I can intercept it with SYSTEM_CHAT but I can't cancel the event. The output is basically ignored.
https://pastebin.com/FycUMAhV

**Comment by derklaro** [comment]
I can try it out for mysql later, but I'm pretty sure you can cancel packets (if I understand your problem correctly)

**Comment by Nononitas** [comment]
> I can try it out for mysql later, but I'm pretty sure you can cancel packets (if I understand your problem correctly)

So?

**Comment by derklaro** [comment]
Works for me, nothing is displayed in the client chat. My code:
```java
 var listener = new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.SYSTEM_CHAT) {
  @Override
  public void onPacketSending(PacketEvent event) {
    log.warning("CANCELLING " + event.getPacket().getStrings().read(0));
    event.setCancelled(true);
  }
});

```

Output:
```
CANCELLING {"translate":"chat.type.advancement.task","with":[{"insertion":"derklaro","clickEvent":{"action":"suggest_command","value":"/tell derklaro "},"hoverEvent":{"action":"show_entity","contents":{"type":"minecraft:player","id":"bcc582ed-494d-4b93-86cb-b58564651a26","name":{"text":"derklaro"}}},"text":"derklaro"},{"color":"green","translate":"chat.square_brackets","with":[{"hoverEvent":{"action":"show_text","contents":{"color":"green","extra":[{"text":"\n"},{"translate":"advancements.story.mine_stone.description"}],"translate":"advancements.story.mine_stone.title"}},"translate":"advancements.story.mine_stone.title"}]}]}
```
