### ISSUE TITLE
When a player is connecting :  [Netty Epoll Server IO #1/ERROR]

### ISSUE THREAD

**Issue by Neileroo** [dmulloy2/ProtocolLib#1671]
**Describe the bug**
When a player connect I have an error : [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

1.  Starting the server
2. Join with my premium account
3. Error in console : https://pastebin.com/ptCb2YSx

Version : Paper 1.19-R0.1-SNAPSHOT
ProtocolLib : 4.8.0

**Comment by no-hands-hand** [comment]
I am also having this issue, stack trace and dump here: https://pastebin.com/SXrn3uZx

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/
