### ISSUE TITLE
1.19 error 

### ISSUE THREAD

**Issue by tonibonbona** [dmulloy2/ProtocolLib#1673]
**Describe the bug**
Protocolib doesn't work on 1.19 purpur

**To Reproduce**
1. install latest purpur version
2. install latest plib version
3. start the server
4. see error

**Expected behavior**

**Screenshots**
(https://prnt.sc/KZyshgiEgwKw)
**Version Info**
ProtocolLib Dump
Timestamp: 06/20/22 14:48:43

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19-R0.1-SNAPSHOT
Server Version: git-Purpur-1669 (MC: 1.19)
Java Version: 17.0.2

ProtocolLib: com.comphenix.protocol.ProtocolLib@2d2ff03d[
  statistics=com.comphenix.protocol.metrics.Statistics@50c286e
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@3f7b70a6
  packetTask=3
  tickCounter=2175
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a418a85
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@5604a66f
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@4781a8a
  commandProtocol=com.comphenix.protocol.CommandProtocol@60d31d33
  commandPacket=com.comphenix.protocol.CommandPacket@449afcf
  commandFilter=com.comphenix.protocol.CommandFilter@770d46f7
  packetLogging=com.comphenix.protocol.PacketLogging@33e5aed6
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@4b27171c
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1669,minecraftVersion=1.19}
  file=plugins/ProtocolLib (1).jar
  description=org.bukkit.plugin.PluginDescriptionFile@259ee60
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (1).jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@1f3a405
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@28a4bdc3[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a418a85
  packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6196f8b0
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@478fb770
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4ac850e7
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@c1bee99
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (1).jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@5a9ed4d2
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1669,minecraftVersion=1.19}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@68d7f75b
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=1
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@26550c99
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@40472fee
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.0)
  debug=false
]

Listeners:
eu.decentsoftware.holograms.api.nms.PacketHandler__ProtocolLib$1@5df90981[
  plugin=DecentHolograms v2.4.2
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
DecentHolograms by [d0by]

**Additional context**

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
