### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by DenNotFound** [dmulloy2/ProtocolLib#1681]
**Describe the bug**

**To Reproduce**
1.paper1.19, protocollib
2. run the server
3. error spam

**Expected behavior**
no error

**Screenshots**

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/VnjKq1m2)

**Additional context**
[Add any other context about the problem here.](https://pastebin.com/BywmF9cY)

**Comment by Roper89** [comment]
Same error on paper1.19

**Comment by Vaesim** [comment]
Same error on 
Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.3.1
  Server:
    git-Purpur-1670 (MC: 1.19)

**Comment by ashton727** [comment]
Same error except for me its pasted in chat.

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
