### ISSUE TITLE
ProtocalLib Internal Exception Error

### ISSUE THREAD

**Issue by ImperialPlays75** [dmulloy2/ProtocolLib#1688]
I am currently running a Forge server on 1.16.5 with Magma installed so that I am able to run TCP Shield on it. However, whenever I use the TCP Shield plugin with the ProtocalLib plugin, it never lets me enter the server always with an error like: 

{Player} lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 608, Size: 48

I can't find anything online to help and I have found that without the ProtocalLib plugin and only the TCP, it lets the server boot, without TCP actually working mind you because it needs ProtocalLib to work. I've also updated my Java, and tried two separate versions of Magma and ProtocalLib as well to no success.

I am new to server hosting so any help would be appreciated.

**Comment by dmulloy2** [comment]
We currently do not support forge/hybrid servers
