### ISSUE TITLE
Error Message Spam

### ISSUE THREAD

**Issue by NearusTheGreat** [dmulloy2/ProtocolLib#169]
Ever since I updated to 1.9 I get this error message and it spams me : http://bit.ly/1QBrRk2

**Comment by dmulloy2** [comment]
Can you provide some more information like plugins, server version, etc?

**Comment by NearusTheGreat** [comment]
Running Spigot 1.9
List of plugins: GroupManager, WorldEdit, Simple-AutoSave, Vault, PlotMe, WorldGuard, Playtime, Chairs, NoBrackets, AutoBroadcaster, SurvivalGames, Marriage, OnTime, CoreProtect, ClearLag, ProtocolLib, BuycraftX, PlotMe-DefaultGenerator, SpectatorDisabler, Essentials, Citizens, ServerSigns, EssentialsSpawn, Multiverse-Core, ChatGuard, Paintball, uSkyBlock, Autorank, EssentialsChat, GriefPrevention, HolographicDisplays, Multiverse-Inventories, Multiverse-NetherPortals, COM_Zombies
Worked fine in 1.8 now its broken :P

**Comment by dmulloy2** [comment]
Run /protocol dump and paste the contents using pastebin.

**Comment by dmulloy2** [comment]
Based on #152, it likely has to do with Holographic Displays and/or Citizens. What versions of those plugins are you using?

**Comment by Pr0totype2** [comment]
@NearusTheGreat Update every plugin to latest version
Citizens2, download latest dev build
http://ci.citizensnpcs.co/job/Citizens2/lastBuild/
For HolographicDisplays, it now say a 1.9-dev build aswell.
http://dev.bukkit.org/bukkit-plugins/holographic-displays/

// Worked fine for me eversince.
