### ISSUE TITLE
ProtocolLib broken Sculk Block - 1.19 Bug

### ISSUE THREAD

**Issue by AccioAce** [dmulloy2/ProtocolLib#1691]
**Describe the bug**
ProtocolLib has a bug where Sculks block doesn't drop EXP as it suppose to when players break them. I tested it and it didn't work for me. 

**To Reproduce**
Explained above ^ and provided a short gif video as well.

**Expected behavior**
Sculks block should be dropping EXP upon breaking it.

**Screenshots**
Here's a gif of it not dropping exp when it suppose too -> https://gyazo.com/31f76294431b74c2147d77ece5fbd99b

**Version Info**
ProtocolLib Dump: https://www.toptal.com/developers/hastebin/epoxuhifoh.kotlin

**Additional context**
Not that I know of, but it does need fixing asap.

**Comment by derklaro** [comment]
I just tested it on a clean installation and (as expected) the issue is not caused by ProtocolLib. Try removing other plugins, one of them might depend on PLib and works no longer when you remove it, letting it look like PLib is causing the issue

**Comment by AccioAce** [comment]
> I just tested it on a clean installation and (as expected) the issue is not caused by ProtocolLib. Try removing other plugins, one of them might depend on PLib and works no longer when you remove it, letting it look like PLib is causing the issue

That strange then because that what I did and PLib was the issue. umm

**Comment by AccioAce** [comment]
ah your right is not PLib, I swear I thought it was. My bad!
