### ISSUE TITLE
How to fix "ProtocolLib does not support plugin reloaders!"

### ISSUE THREAD

**Issue by ThomskiiXD** [dmulloy2/ProtocolLib#1692]
**Describe the bug**
I wanted to add YamipaPlugin and it required ProtocolLib, when I started the server, ProtocolLib keeps on disabling, any ways to fix it?
 
Server Latest log: 
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/8986823/latest.log)

**Comment by derklaro** [comment]
Whatever server software you are using is not bundling commons-lang leading to a startup failure. While we are working on eleminating the usage of external dependencies as much as possible, the current solution is to switch to a supported software like spigot or paper.

**Comment by ThomskiiXD** [comment]
I'm using Mohist 1.18.2 with paper and java

**Comment by ThomskiiXD** [comment]
Nvm, I'll just wont use Yamipa, Thanks
