### ISSUE TITLE
1.19 Error

### ISSUE THREAD

**Issue by ARR4NN** [dmulloy2/ProtocolLib#1693]
**Describe the bug**
Latest protocolLib version on 1.19

https://paste.gg/p/anonymous/76831eb6c9544c62b429e55301eb6775

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by ARR4NN** [comment]
Oh, thats strange i had just gotten the latest version from that link

**Comment by derklaro** [comment]
Judging from the version (which I can see in your dump) you did not download the latest build, you probably downloaded the last build of v4.8
