### ISSUE TITLE
No SPAWN_ENTITY_LIVING packet listener?

### ISSUE THREAD

**Issue by dsevvv** [dmulloy2/ProtocolLib#1695]
**Describe the bug**
It appears that there is no SPAWN_ENTITY_LIVING packet listener?? This seems like this is not intended behavior. This worked fine with 1.18, but has now broken using the 1.19 ProtocolLib dev builds.

[Error paste](https://pastebin.com/g6NE80DU)

**To Reproduce**
1. Run a server that uses the most recent dev version of ProtocolLib and the plugin "DamageIndicatorsPlus"
2. Start up the server

**Expected behavior**
Before the 1.19 update, this packet was used to modify the outbound entity spawn packet. This doesn't seem to exist within the 1.19 plib api.

**Screenshots**
N/A

**Version Info**
[Paste](https://pastebin.com/1WAWdNhy)

**Additional context**
I am using this packet to make specific entities invisible, it is core to the function of DamageIndicators.

**Comment by derklaro** [comment]
That's not an issue of protocollib, minecraft 1.19 merged all entity spawn packets into one packet (except for players and experience orbs). See https://wiki.vg/Protocol#Spawn_Entity
