### ISSUE TITLE
1.19 console error

### ISSUE THREAD

**Issue by GioPera06** [dmulloy2/ProtocolLib#1697]
https://pastebin.com/g1PhWDnV
I keep getting this error in console and in game chat, help?

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/
