### ISSUE TITLE
Error Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by GoT-HiM** [dmulloy2/ProtocolLib#1700]
**Describe the bug**
While loading, bring this warn to console, I wanted to report it in case it creates errors.

**To Reproduce**
1. Start the server, with the last devbuild and Triton
2. You can see after the startup, in the logs, the warn

**Expected behavior**
Absence of Warn

**Screenshots**
There is directly the pastebin

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/6XB72S9c)

**Additional context**
Here there's the warn:
https://pastebin.com/byBp7MPM

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/
