### ISSUE TITLE
SET_WARNING_TIME SET_WARNING_CENTER and SET_WARNING_BLOCKS don't work in 1.8

### ISSUE THREAD

**Issue by Usepot** [dmulloy2/ProtocolLib#1701]
**Describe the bug**
3 worldborder commands don't work and im guessing what is the "1.8" port doesnt work properly either
Whenever I try to do anything but set the size of the border using WORLD_BORDER it doesnt work
**To Reproduce**
1. Use 1.8.8 paper (idk if its paper or not)
2. Use SET_BORDER_CENTER, SET_BORDER_WARNING_DELAY, SET_BORDER_WARNING_DISTENCE, INITIALIZE_BORDER, SET_BORDER_LERP_SIZE, SET_BORDER_SIZE (You can use worldborder to replace SET_BORDER_SIZE but the other 5 packets I send on 1.8)

**Expected behavior**
its supposed to change the worldborder center and warning blocks and stuff.
i'm trying to make it so I can show the red corner thing when ur next to the worldborder on command
**Screenshots**

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.]
(https://pastebin.com/T4Bbx8H6)
**Additional context**
[Add any other context about the problem here.]
https://pastebin.com/8yKNsr12
this is the error log for set border size if you need it

also is 1.8 actively supported in protocollib or is this just gonna stay a bug and im gonna have to use nms

**Comment by derklaro** [comment]
You need to use the deprecated "WORLD_BORDER" packet type, as the packet was split in version 1.17 and previously was one single packet for all the types.

**Comment by Usepot** [comment]
> You need to use the deprecated "WORLD_BORDER" packet type, as the packet was split in version 1.17 and previously was one single packet for all the types.

Whenever I use WORLD_BORDER it only does the size and nothing else even though I put it there, is there any way I can find how to use the packet properly?

**Comment by derklaro** [comment]
Check https://wiki.vg/index.php?title=Protocol&oldid=7368#World_Border (hope that helps - if not check out the spigot 1.8 code 🤔 )

**Comment by Usepot** [comment]
ty!
this helped a ton
