### ISSUE TITLE
Latest Dev Builds Break Simple Voice Chat

### ISSUE THREAD

**Issue by DrBurgerMaster** [dmulloy2/ProtocolLib#1706]
**Describe the bug**
The latest dev builds break Simple Voice Chat (SVC). (Players cannot connect to the voice server).
No errors appear in the console related to this issue.

Previous builds work with SVC but builds 557 or greater seem to be incompatible with the plugin.
Build 548 and previous work, however errors appear in chat (known & fixed in dev builds)
549-556 cannot be tested as these builds do not allow players to connect on 1.19 servers (known & fixed in 557)

**To Reproduce**
1. Install the Simple Voice Chat spigot plugin
2. Configure the Voice Server / Ports
3. Restart Server & Join (Voice Chat works)
4. Install ProtocolLib build 557 or greater
5. Restart and join (Voice Chat no longer works)

**Expected behavior**
Simple Voice Chat and ProtocolLib are not expected to have conflicts

**Version Info**
https://pastebin.com/0dyG54a9

**Comment by derklaro** [comment]
As from your dump I cannot see any dependency of SVC on ProtocolLib. That means that (most likely) SVC tries something which is incompatible with PLib. Please report that to them (the last dev builds change some stuff related to channel injection, maybe that is a reason 🤷 )

**Comment by DrBurgerMaster** [comment]
I talked to the SVC dev's and this was their response:
![SVC Dev Response](https://user-images.githubusercontent.com/61357145/176507836-aed31ccb-c3b2-4e68-8f3d-5f3367ff1d77.png)

**Comment by mjwells2002** [comment]
id love to have any info on how we could cause this, the only thing we use in current versions is the plugin messaging system
