### ISSUE TITLE
1.19 FULL SUPPORT

### ISSUE THREAD

**Issue by sujyrokimora** [dmulloy2/ProtocolLib#1709]
**Is your feature request related to a problem? Please describe.**
My server needs the plugin to run 1.19 im stuck 1.18.2 because lack of updates

**Describe the solution you'd like**
Run 1.19

**Describe alternatives you've considered**
None

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
