### ISSUE TITLE
Protocol Error in my server!

### ISSUE THREAD

**Issue by MiniMaccc** [dmulloy2/ProtocolLib#1710]
- [ ] This issue is not solved in a development build

**Describe the bug**
When I start my server, a huge amount of errors regarding `Protocol` appear in my console

**To Reproduce**
1. Go to my server on Aternos
2. Click on 'start'
3. Scroll down to 'console'

**Expected behavior**
Server to turn on perfectly fine with no errors in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/105380963/176660313-43f6972d-c0a5-4c8d-8575-3c99f64f714a.png)

**Version Info**
[Protocol Error.txt](https://github.com/dmulloy2/ProtocolLib/files/9019167/Protocol.Error.txt)

**Additional context**

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
