### ISSUE TITLE
Can I ask Aternos team to put the 1.19 ProtocolLib in their approved plugins ?

### ISSUE THREAD

**Issue by DrSlav** [dmulloy2/ProtocolLib#1721]
I was just wondering if i can put a submision in for 1.19 ProtocolLib plugin for Aternos because right now there is no way to put the 1.19 version in the server plugin folder. I just want to ask because i don't know if you are going to agree with it. 

Have a nice day!

**Comment by derklaro** [comment]
Just ask them to use the development builds all the time, there are important fixes which aren't instantly pushed to spigotmc anyway.

**Comment by Seawolf035** [comment]
> Just ask them to use the development builds all the time, there are important fixes which aren't instantly pushed to spigotmc anyway.

People have asked. They won't do it until it's pushed to a main branch update on spigotmc essentially causing issues for people hosting on aternos that need it for other plugins to work https://board.aternos.org/thread/102824-protocolib-needs-to-be-updated-to-1-19/
