### ISSUE TITLE
Console error because of ProtocolLib

### ISSUE THREAD

**Issue by RenatoPugaR** [dmulloy2/ProtocolLib#1727]
- [ ] This issue is not solved in a development build

**Describe the bug**
When using the plugin Interactive Chat, players can't send any messages in the chat because of packet cloning method error from ProtocolLib.

Here is the console error: https://pastebin.com/armGtUFc

**To Reproduce**
1. Use Interactive Chat (any version) and ProtocolLib 4.8.0 or 4.7.0
2. When you try to talk (at least to me), your message does not appear in the chat and an error appears in console
3. See error

**Expected behavior**
That players can chat normally.

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
Here it is: https://pastebin.com/cs5E8BGu

**Additional context**
I am using venture chat, but removing venture chat does not resolve this issue.
I am using Paper 1.16.5

**Comment by derklaro** [comment]
See #1735 for now (saw that issue before this one)
