### ISSUE TITLE
Performance issue when migrating from 4.x to 5.x

### ISSUE THREAD

**Issue by MWHunter** [dmulloy2/ProtocolLib#1732]
There is a regression in PacketFilterManager.getEntityFromId()

4.x: https://spark.lucko.me/GhXCKfywf8
5.x dev builds: https://spark.lucko.me/tMHRwu8MF8

I don't see why Bukkit.getEntity can't be used directly, as ProtocolLib sync's packets on the main thread

**Comment by derklaro** [comment]
We know that the issue is there and I will take a look soon-ish. I don't really know what you mean by Bukkit.getEntity as there is only getEntity(UUID) and World#getEntity(id) doesn't exist as well.

**Comment by MWHunter** [comment]
Oh, I really though bukkit had a method.  The NMS world does have that method at least.

**Comment by derklaro** [comment]
Yea thats the case, but iirc there is an issue with two methods - one including entity parts (like EnderDragonPart) and one does not. I thinks thats why we're currently stale on that but maybe I can figure out a nice solution for that in the next days ;)
