### ISSUE TITLE
Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by SkeloD** [dmulloy2/ProtocolLib#1735]
- [ ] This issue is not solved in a development build

**Describe the bug**
When i start up my server and i join it just spam in chat it just saying unable to read client packet. A lot of times

**Screenshots**
![image](https://user-images.githubusercontent.com/101269133/178150644-98c58fff-c3b9-454a-bcbb-d2f9d7fb7a50.png)
![image](https://user-images.githubusercontent.com/101269133/178150661-065adb39-4ca0-40fe-82d0-ef12f28604b2.png)
![image](https://user-images.githubusercontent.com/101269133/178150668-0181f558-bef5-4c4e-a683-8ae3c3668018.png)

**Comment by derklaro** [comment]
Update to the latest development build for 1.19 support: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
