### ISSUE TITLE
com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute()

### ISSUE THREAD

**Issue by ricardouxr** [dmulloy2/ProtocolLib#1737]
How can I solve this? It consumes too much resource and I don't understand what exactly

(Consumes more when users start to connect)

![Screenshot_20220711_013028](https://user-images.githubusercontent.com/109061307/178202432-070da47a-e63c-4b13-922d-fe6d69f36040.png)

**Comment by derklaro** [comment]
wdym "too much resource"? Its less than one percent of the overall server total time...

**Comment by ricardouxr** [comment]
> wdym "too much resource"? Its less than one percent of the overall server total time...

You didn't read that right apparently, (Starts to over-consume when players start connecting)

**Comment by derklaro** [comment]
okay, more = 0.01%? Thats still not much 🤷 
Maybe you should re-think which information might be useful for people (like me) which cannot magically see your issues.

**Comment by ricardouxr** [comment]
> bien, más = 0,01%? eso todavía no es mucho🤷 Tal vez debería volver a pensar qué información podría ser útil para las personas (como yo) que no pueden ver sus problemas mágicamente.

xd
