### ISSUE TITLE
1.19 protocollib eror

### ISSUE THREAD

**Issue by JrBorshon** [dmulloy2/ProtocolLib#1738]
- [ ] This issue is not solved in a development build

**Describe the bug**

 /103.162.58.238:42476 lost connection: Internal Exception: de.sportkanone123.clientdetector.spigot.packetevents.exceptions.WrapperFieldNotFoundException: PacketEvents failed to find a GameProfile indexed 0 by its type in the net.minecraft.network.protocol.login.PacketLoginInStart class!

**Screenshots**
> https://prnt.sc/h4jW2ZMT0AkL

**Version Info**
https://pastebin.pl/view/fedded15

**Comment by derklaro** [comment]
Thats seems like a PacketEvents issue and not related to ProtocolLib. Please report it to them instead.

**Comment by NoJokeFNA** [comment]
Did you try to reload the server by any chance?
