### ISSUE TITLE
Latest dev build: Leaderboards are being sent in wrong order

### ISSUE THREAD

**Issue by PureMC** [dmulloy2/ProtocolLib#1745]
- [x] This issue is not solved in a development build

**Describe the bug**
Hello,
on the latest dev build of ProtocolLib (5.0.0-SNAPSHOT-b575) leaderboards are being sent in the wrong order. What I mean by that is being explained pretty good futher down by two images.

**To Reproduce**
1. 'Install the latest dev build'
2. Type '/baltop' for example
3. Look at the output

**Expected behavior**
Correct order of leaderboards

**Screenshots**
What it should look like:
![2022-07-13_21 38 02](https://user-images.githubusercontent.com/109244524/178820951-8694a41e-d6d0-43c0-9fc6-b1596c61ae0a.png)

How it actually looks like:
![2022-07-13_21 43 01](https://user-images.githubusercontent.com/109244524/178821100-a831182d-b933-485e-989d-a4d49863f1b4.png)

**Version Info**
https://pastebin.com/2FMSp0yT

**Additional context**
This error does not occur on older versions (4.8).

**Comment by derklaro** [comment]
Without any code or any additional information I cannot give you any advise.

**Comment by LiritoMC** [comment]
Are you using Essentials or CMI?

**Comment by derklaro** [comment]
> What information are you thinking of?

I was thinking about something like code which shows me how you're sending the messages in order to reproduce the issue

**Comment by PureMC** [comment]
> Are you using Essentials or CMI? That would be an external issue not related to ProtocolLib


Hello,
yeah, I'm using Essentials. However, it's not just Essentials. pvpstats has the same problem (https://github.com/slipcor/PVPStats). 

> > What information are you thinking of?
> 
> I was thinking about something like code which shows me how you're sending the messages in order to reproduce the issue


I'm not sure but I think this is the code for pvpstats: https://github.com/slipcor/PVPStats/blob/master/src/main/java/net/slipcor/pvpstats/api/LeaderboardBuffer.java (leaderboards) and https://github.com/slipcor/PVPStats/blob/master/src/main/java/net/slipcor/pvpstats/api/PlayerStatisticsBuffer.java (player statistics).
