### ISSUE TITLE
Chat exception causes some chat functions to stop working.

### ISSUE THREAD

**Issue by nicholasrobertm** [dmulloy2/ProtocolLib#1755]
- [x] This issue is not solved in a development build

**Describe the bug**
This bug seems to cause things like Grief Defender's /claimlist to output improperly to chat. It will only output some of the text but not all of the text. This is seen in other plugins that output in chat as well. This error comes from the plugin InteractiveChat but the stacktrace seems to indicate the problem may be in ProtocolLib. I'm unsure what triggers this bug, it seems to just happen after a certain amount of time of the server being online with 40+ players.

Side note but I'd love to have this fixed and am willing to donate to whomever can find a solution for it! If any additional info is needed please let me know

**To Reproduce**
1. Have Interactive chat and protocol lib
2. Wait for it to happen (Exact reproduction steps unknown) 

**Expected behavior**
Chat continued to function

**Screenshots**
Here is what /claimlist (from griefdefender) looks like after the error in the log below is thrown
![image](https://user-images.githubusercontent.com/3313264/179452012-5ec9eb26-ae58-4cdf-8255-822372548528.png)

Here is what it should look like
![image](https://user-images.githubusercontent.com/3313264/179452465-c1bf4624-b5e7-4d3c-a215-8caae8f86232.png)

**Version Info**
https://pastebin.com/m5WUFH7S

**Additional context**
Log that gets thrown https://pastebin.com/FF7vizNw

**Comment by derklaro** [comment]
Seems to be a duplicate of #1734

**Comment by nicholasrobertm** [comment]
ahn right, completely missed the dupe, can close this and will follow on the other one!
