### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BlackGraphics** [dmulloy2/ProtocolLib#1756]
Plugin not working 1.19 Paper server
Logs: https://pastebin.com/UZrnwNEd
https://i.imgur.com/A8k0NdS.png
How to fix it?

**Comment by derklaro** [comment]
Please download the latest build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar to get 1.19 support
