### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by herkintm** [dmulloy2/ProtocolLib#1757]
- [ ] This issue is not solved in a development build

A text

[dump-2022-07-20_12.19.38.txt](https://github.com/dmulloy2/ProtocolLib/files/9148918/dump-2022-07-20_12.19.38.txt)
heres dump

4.80

**Additional context**

**Comment by derklaro** [comment]
Please download the latest build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar to get 1.19 support
