### ISSUE TITLE
PlayerTabList

### ISSUE THREAD

**Issue by danieltabrizian** [dmulloy2/ProtocolLib#176]
Hello,
I have been trying to get more than 16 char custom characters in the tablist and this turned out to be possible if uing prefixes and suffixes to add onto the string. I found an api to do this but its outdated. So i took on the challange to update it and i havent had any luck...
At one point in the code it throws an error when constructing player info.
Basically i need a packetcontainer which has the packettype.play.server.player_info with a custom name in it. I hope you can help!

**Comment by dmulloy2** [comment]
You would use the PlayerInfoData list modifier (PacketContainer#getPlayerInfoDataLists()) and modify the displayName variable.
