### ISSUE TITLE
"PacketContainer.deepclone()" is heavy

### ISSUE THREAD

**Issue by WarnDa** [dmulloy2/ProtocolLib#1760]
**Describe the bug**
I'm using latest dev build of protocollib, and chat packets are heavy

**To Reproduce**
1) Use a plugin that send messages to one player using "player.sendMessage"
2) send a lot of message (1-2 per second)
2) do a spark

**Expected behavior**
Should be less heavy, is this planned for a recode/optimisation in your V5 ?

**Screenshots**
![image](https://user-images.githubusercontent.com/31826333/180011133-3e3c4b46-c353-47f1-b966-76a695e00371.png)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/hrwBJhAJ

**Additional context**
The spark : https://spark.lucko.me/9orqLFS8bB

**Comment by LOOHP** [comment]
Doesn't look like the server is struggling or close to struggling because of that 0.35% caused by cloning chat packets for fallback use.

**Comment by WarnDa** [comment]
Okay thanks for your answer, I was hopping there could be changes to reduce it, but not currently, so I'm closing this :)
