### ISSUE TITLE
Could not submit plugin stats of ProtocolLib

### ISSUE THREAD

**Issue by JhordanPG** [dmulloy2/ProtocolLib#1761]
https://pastebin.com/SPJUuMmi <- Every so often I get that error message and I don't know how to fix it, I'm using the latest version of ProtocolLib , and purpur 1.19, and I haven't been able to find a solution.

Versión info: https://pastebin.com/Wvuq5csQ

**Comment by derklaro** [comment]
That just means that we're sending too many requests to bstats (can for example be caused by a server restart). Nothing to worry about.
