### ISSUE TITLE
Low TPS and high MSPT

### ISSUE THREAD

**Issue by victorlindox** [dmulloy2/ProtocolLib#1762]
- [ ] This issue is not solved in a development build

**Describe the bug**
Hello, I have a problem on my server with Lag, TPS is lowering to 15 and MSPT going over 70, all sparks accuse ProtocolLib as the cause of the lag, but I've tried everything but the lag continues, it does This has been happening for about 2 weeks.

Could anyone help?
ProtocolLib is up to date with the latest Dev Build, and Purpur is up to date on 1.19 and the latest update.

**Screenshots**

![Sem título](https://user-images.githubusercontent.com/41601203/180114441-33479e95-ca06-47ec-94c2-e5c29b3ec210.png)

**Version Info**
[dump-2022-07-20_22.38.28.txt](https://github.com/dmulloy2/ProtocolLib/files/9155601/dump-2022-07-20_22.38.28.txt)

**Comment by derklaro** [comment]
Looking at the spark report you've posted in the other issue, the issue is not caused by ProtocolLib but rather native calls of netty. The issue is just shown by ProtocolLib because it's the final instance which calls the write operation to the netty channel.

**Comment by victorlindox** [comment]
thanks a lot, so I'm still seeing what's causing it, but I'm thinking it's the login plugin, nLogin. I already removed some plugins to see what it is
