### ISSUE TITLE
Cannot get the blockstate of a banner on digging

### ISSUE THREAD

**Issue by lolitee** [dmulloy2/ProtocolLib#1765]
- [ ] This issue is not solved in a development build

**Describe the bug**
Protocollib returns error if the player digs banner if we are trying to get the state of it, however we are still able to get the type of it. In the other hand I'm able to get the block state with the "BlockDamageEvent" event which also requires to dig anything, but doesn't end up erroring out 

**To Reproduce**
1. try to get the block state of a block that is being digged
2. dig banner block

**Expected behavior**
return banners item state

**Screenshots**

https://user-images.githubusercontent.com/62479501/180597848-8b85ecfa-f29f-45de-ac50-e8360ebfb9da.mp4

https://user-images.githubusercontent.com/62479501/180597590-b50142d9-875b-47d3-a1a1-3799e19da8a8.mp4

**Version Info**
https://pastebin.com/e0Ttpbk1

**Comment by derklaro** [comment]
Incoming packets are not processed on the main server thread, therefore acessing blocks is unsafe and might result in errors like those you see.

**Comment by lolitee** [comment]
that was the issue, thank you!!
