### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by Valsinoq** [dmulloy2/ProtocolLib#1766]
- [x] This issue is not solved in a development build

**Describe the bug**
I am not good at reading code or whatever, but all I know is that I play with these plugins:
**https://aternos.org/addons/a/spigot/8695 | Version 2.3.0**
**https://aternos.org/addons/a/bukkit/authme-reloaded | Version AuthMe 5.6.0-beta2 MySQL 8 Hotfix**
**https://aternos.org/addons/a/spigot/17129 | Version 4.4.1**
**https://aternos.org/addons/a/spigot/18494 | Version 1.25.1**
**https://aternos.org/addons/a/artemis-bukkit/geyser | Version 1154 (Bedrock v1.19.0 - v1.19.10)**
**https://aternos.org/addons/a/spigot/1997 | Version 4.8.0**
**https://aternos.org/addons/a/spigot/64270 | Version 6.1**
**https://aternos.org/addons/a/spigot/2124 | Version 14.2.1**

I use Aternos, 1.19, PaperMC as software and have a bunch of other datapacks. Datapacks: 
_ancient-cities-overhaul-nikeyso.zip
537.02 kB
anti creeper grief v1.1.3.zip
7.77 kB
anti enderman grief v1.1.3.zip
6.87 kB
anti ghast grief v1.1.3.zip
7.66 kB
better-chests-e1610.zip
21.62 kB
BlazeandCave's Advancements Pack Terralith.zip
87.59 kB
BlazeandCaves Advancements Pack 1.14.3.zip
3.26 MB
[bukkit](https://aternos.org/files/world/datapacks/bukkit)
classic fishing loot v1.1.3.zip
4.58 kB
dungeon-now-loading-v16.2-1.19.zip
12.14 MB
dungeons-v1-8-0-terralith.zip
97.28 kB
dynamic_light_v1.2.zip
23.26 kB
enchantment-plus-v1-15 (1).zip
557.35 kB
fast leaf decay v2.0.6.zip
19.67 kB
fokastudio-s-ender-expansion-v-1-5b.zip
2.41 MB
harderendcity1-19.zip
111.02 kB
hopobettermineshaft-1-19-1-1-5 (1).zip
1.46 MB
hopobetterruinedportals-1-19-1-3-2.zip
165.48 kB
hopobetterunderwaterruins-1-19-1-0-9.zip
306.19 kB
incendium-v5-1-0.zip
8.46 MB
merge-xp.zip
5.42 kB
multiplayer sleep v2.6.3.zip
21.35 kB
name colors v1.0.1.zip
6.86 kB
No-Lag-Datapack.zip
70.55 kB
pk-better-compass-v-1-0-1.zip
25.68 kB
pk-waystones-v-1-0-3.zip
125.97 kB
simple-damage-indicator-e250.zip
20.23 kB
Spawner+Craft+[datapack]+v1.11.0.zip
85.56 kB
spectator night vision v1.1.3.zip
6.44 kB
terralith-v2-3-2.zip
3.77 MB
towns-and-towers-structure-add-on-1-7-2 (1).zip_

_**(I'm not sure what that will do, but just in case.)**_

**To Reproduce**
1. Go to 'turn on server'
2. Click on 'console'
3. Scroll down to 'see latest logs'

**Expected behavior**
Game crashes

**Screenshots**
<html>
<body>

Stack Trace:
--
3887 | java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
3888 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
3889 | at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
3890 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
3891 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
3892 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
3893 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
3894 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
3895 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3896 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3897 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3898 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
3899 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
3900 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3901 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3902 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3903 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
3904 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3905 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3906 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3907 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
3908 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
3909 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
3910 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
3911 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3912 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3913 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3914 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
3915 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3916 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3917 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3918 | at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
3919 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3920 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3921 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
3922 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
3923 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
3924 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
3925 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
3926 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
3927 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
3928 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
3929 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
3930 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
3931 | at java.base/java.lang.Thread.run(Thread.java:833)
3932 | Dump:
3933 | Parameters:
3934 | io.netty.buffer.PooledUnsafeDirectByteBuf@2820abda[
3935 | memoryAddress=139668108704512
3936 | recyclerHandle=io.netty.util.Recycler$DefaultHandle@1b93377d
3937 | chunk=Chunk(5037097e: 21%, 868352/4194304)
3938 | handle=1125929971613698
3939 | memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
3940 | offset=16416
3941 | length=2
3942 | maxLength=16
3943 | cache=io.netty.buffer.PoolThreadCache@72c9f809
3944 | tmpNioBuf=<null>
3945 | allocator=PooledByteBufAllocator(directByDefault: true)
3946 | refCnt=2
3947 | readerIndex=2
3948 | writerIndex=2
3949 | markedReaderIndex=0
3950 | markedWriterIndex=0
3951 | maxCapacity=2147483647
3952 | ]
3953 | manager:
3954 | com.comphenix.protocol.injector.PacketFilterManager@51ee7f39[
3955 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6fc94c59
3956 | packetListeners=[PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
3957 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@162a0f91
3958 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2bdffb1
3959 | inputBufferedPackets=[]
3960 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@20084f68
3961 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50664b4
3962 | hasClosed=false
3963 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
3964 | reporter=com.comphenix.protocol.ProtocolLib$1@4396a502
3965 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-69,minecraftVersion=1.19}
3966 | library=ProtocolLib v4.8.0
3967 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4caae306
3968 | knowsServerPackets=true
3969 | knowsClientPackets=true
3970 | phaseLoginCount=0
3971 | phasePlayingCount=1
3972 | packetCreation=false
3973 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65422209
3974 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@67107b57
3975 | hasRecycleDistance=true
3976 | minecraftVersion=(MC: 1.19.0)
3977 | debug=false
3978 | ]
3979 | Sender:
3980 | com.comphenix.protocol.injector.netty.ChannelInjector@746be6d8[
3981 | decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
3982 | encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
3983 | factory=com.comphenix.protocol.injector.netty.InjectionFactory@67bc2372
3984 | player=CraftPlayer{name=Fr3sh}
3985 | updated=<null>
3986 | playerName=Fr3sh
3987 | playerConnection=<null>
3988 | networkManager=net.minecraft.network.NetworkManager@4b33c6a6
3989 | originalChannel=[id: 0xe634bd8b, L:/**.**.**.**:38196 - R:/**.**.**.**:56678]
3990 | channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@4b33c6a6, previous=[id: 0xe634bd8b, L:/**.**.**.**:38196 - R:/**.**.**.**:56678], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5d711357, previousLoaded=true, currentSet=true, forceAccess=true]
3991 | packetMarker={}
3992 | currentEvent=<null>
3993 | finalEvent=<null>
3994 | unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4475eac3
3995 | vanillaDecoder=net.minecraft.network.PacketDecoder@1126121d
3996 | vanillaEncoder=net.minecraft.network.PacketEncoder@5cdf0aee
3997 | finishQueue=[]
3998 | channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65422209
3999 | processor=com.comphenix.protocol.injector.NetworkProcessor@62a99194
4000 | injected=true
4001 | closed=false
4002 | cumulation=PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2)
4003 | cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@a67b706
4004 | singleDecode=false
4005 | first=true
4006 | firedChannelRead=false
4007 | selfFiredChannelRead=true
4008 | decodeState=1
4009 | discardAfterReads=16
4010 | numReads=0
4011 | added=true
4012 | ]
4013 | Version:
4014 | ProtocolLib v4.8.0
4015 | Java Version:
4016 | 17.0.2
4017 | Server:
4018 | git-Paper-69 (MC: 1.19)

</body>
</html>
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2820abda[
      memoryAddress=1[3966](https://mclo.gs/Q2tM8Kl#L3966)8108704512
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1b93377d
      chunk=Chunk(5037097e: 21%, 868352/4194304)
      handle=1125929971613698
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16416
      length=2
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@72c9f809
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=2
      writerIndex=2
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@51ee7f39[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6fc94c59
        packetListeners=[PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@162a0f91
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2bdffb1
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@20084f68
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50664b4
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4396a502
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-69,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4caae306
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65422209
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@67107b57
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@746be6d8[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@67bc2372
      player=CraftPlayer{name=Fr3sh}
      updated=<null>
      playerName=Fr3sh
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@4b33c6a6
      originalChannel=[id: 0xe634bd8b, L:/**.**.**.**:38196 - R:/**.**.**.**:56678]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@4b33c6a6, previous=[id: 0xe634bd8b, L:/**.**.**.**:38196 - R:/**.**.**.**:56678], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5d711357, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4475eac3
      vanillaDecoder=net.minecraft.network.PacketDecoder@1126121d
      vanillaEncoder=net.minecraft.network.PacketEncoder@5cdf0aee
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65422209
      processor=com.comphenix.protocol.injector.NetworkProcessor@62a99194
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@a67b706
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-69 (MC: 1.19)
    
    **Version Info**
I don't know how, a bit confused 

**Additional context**
https://mclo.gs/Q2tM8Kl

**Comment by derklaro** [comment]
You need the dev version of ProtocolLib which is currently not available at aternos. Please upvote the other issues regarding that topic and close this one ;)
