### ISSUE TITLE
Unable to open book for player

### ISSUE THREAD

**Issue by Cryptite** [dmulloy2/ProtocolLib#177]
Had this snippet of code that worked in 1.8 but seems to silently fail/do nothing now:

http://pastebin.com/sd9Ckjcs

**Comment by dmulloy2** [comment]
You're using an empty byte buffer, so that might have something to do with it.

**Comment by Cryptite** [comment]
Wound up using a different method involving the BookUtil class in this thread: https://www.spigotmc.org/threads/open-book-gui.131470/
