### ISSUE TITLE
Cannot add an NbtCompound to an NbtList

### ISSUE THREAD

**Issue by hedgehog1029** [dmulloy2/ProtocolLib#178]
I have a weird issue where I can't add NbtCompounds to NbtLists. I'm not sure if this is my fault or a protocollib issue?

Error thrown: http://hastebin.com/imejekecuz.avrasm
Code: http://hastebin.com/upoyovazip.avrasm

I have tried passing many different names, tried passing null (throws an NPE) and tried .addClosest, but none work.

Any ideas?

**Comment by dmulloy2** [comment]
You can't add named tags to lists, so remove names or replace them with empty strings.

**Comment by hedgehog1029** [comment]
Using an empty string works, thanks!
