### ISSUE TITLE
Console Error 

### ISSUE THREAD

**Issue by NewBeginnings1** [dmulloy2/ProtocolLib#1781]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ yes ] You're using the latest build for your server version
- [ not that i seen ] This isn't fixed in a recent development build
- [Dont think so.. ] This isn't an issue caused by another plugin
- [Yeah, im getting server console spam with errors] You've checked for duplicate issues
- [ nope, Start and stop ] You didn't use `/reload`

Debug paste link: https://pastebin.com/jWEsWKaT

Description and relevant errors:
Everytime i start my server im getting console spammed with a error (see pastebin) Ive tried to narrow down whats causing it but am having no luck. I tried updating the Jar file and no luck either

**Comment by AerialLine** [comment]
I'm struggling with that problem too.
I know plugin is a version that is not yet supported, but please fix it.

Environment is: OpenJDK 64-Bit Server VM 18.0.1.1
                          Windows 10 10.0 (amd64)
                          Paper-81 (1.19.1)
                          
Plguins is: ViaVersion v4.3.2
                 ViaBackwards v4.3.1
                 Shopkeepers v2.16.0
                 Themis v0.13.0
                 Geyser-Spigot v2.0.5-SNAPSHOT
                 floodgate v2.2.0-SNAPSHOT
                          
https://pastebin.com/xpx0gQJ0 <- Output Errors on Server open (3 Errors)
https://pastebin.com/bthXA5Tw <- Output Errors on Player join in (many)

**Comment by AerialLine** [comment]
PS: I was walking and caught an exception.

https://pastebin.com/2hdMs9Eu

**Comment by AerialLine** [comment]
ah New version 5.0.0 was distributed
The error seems to have been fixed.
It's still a dev version, but at that error seems to have been fixed!

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Firepup6500** [comment]
Great that this was fixed in a dev build, but my hosting service doesn't support the site for the dev builds, hope this becomes a release build soon.

**Comment by AerialLine** [comment]
> Great that this was fixed in a dev build, but my hosting service doesn't support the site for the dev builds, hope this becomes a release build soon.

good luck.
a littel time
