### ISSUE TITLE
Repeated "Error unable to intercept a read client packet" in chat

### ISSUE THREAD

**Issue by Calebplaysgames** [dmulloy2/ProtocolLib#1785]
- [ ] This issue is not solved in a development build

**Describe the bug**
as title says it says a repeated "Error unable to intercept a read client packet" in chat over and over.
this is 1.19 and uses the newest possible version, 4.8.0

**To Reproduce**

**Expected behavior**
 it to not fill chat with this 

**Screenshots**
github wont allow screenshots here for some reason.
https://imgur.com/a/thnzBDx

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
4.8.0

**Additional context**

**Comment by derklaro** [comment]
Please use the build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19+ support.
