### ISSUE TITLE
Enter say on the console and all players will exit

### ISSUE THREAD

**Issue by guixinyang** [dmulloy2/ProtocolLib#1788]
lost connection: Internal Exception: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.d()'

**Comment by guixinyang** [comment]
Sorry, this is not the problem of this plugin

**Comment by lokka30** [comment]
For other users encountering this issue, please state the solution if you happen to find it.
If this issue is unrelated to ProtocolLib then I recommend closing this issue 😃
