### ISSUE TITLE
Error filtering reports crash

### ISSUE THREAD

**Issue by RealisticThreat** [dmulloy2/ProtocolLib#1789]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [Yes ] You're using the latest build for your server version
- [Yes] This isn't fixed in a recent development build
- [Yes ] This isn't an issue caused by another plugin
- [Yes] You've checked for duplicate issues
- [Yes] You didn't use `/reload`

Debug paste link: https://pastebin.com/acUyaCR5

Description and relevant errors: Stack trace included in debug paste link.

**Comment by derklaro** [comment]
Can you provide more context when the problem happended? Or include the full server log or smth?

**Comment by RealisticThreat** [comment]
[2022-07-29-6.log](https://github.com/dmulloy2/ProtocolLib/files/9219604/2022-07-29-6.log)

Here is the full server log. All the protocollib errors are in the end. The server crash happened 20-30 min after server startup.

**Comment by derklaro** [comment]
1. You should report to `taboverlay` that they use unsupported api
2. The issue you're seeing from ProtocolLib is a race codition which happened because the server was crashing. That is nothing we can really fix, you can just ignore these issues.
