### ISSUE TITLE
Compatibility with Citizens

### ISSUE THREAD

**Issue by Scratch741** [dmulloy2/ProtocolLib#179]
Hello! I've been having problems with Citizens lately. We figured out that the issue with Citizens is ProtocolLib. The issue is that **Citizens do not spawn NPC's**, and also, other than Citizens not being compatible with ProtocolLib, **not seeing other players** when connecting to the server for some reason. Now here's the question, is it a problem with Citizens or ProtocolLib? If you could help me out I'd be grateful. I will wait for your answer to this issue, and if you reply that you are 100% sure that it is not a problem with ProtocolLib, I will repost this to Citizens' author aswell.

**Comment by dmulloy2** [comment]
What versions of Citizens, ProtocolLib, and Spigot are you using?

**Comment by Scratch741** [comment]
Citizens 2.0.17, ProtocolLib 4.0.0, Spigot 1.9

**Comment by Scratch741** [comment]
Thanks, but I'm still having issues with the disappearing players that can't be seen on the tab list aswell. I will disable Citizens and will give u further information if players do or do not disappear even without Citizens, I will edit this comment-

**Comment by Scratch741** [comment]
I found the issue that made the NPC's disappear. I didn't expect it that much, but it's **Authme**. Combination of ProtocolLib, Citizens, and Authme makes the NPC's disappear for some reason. Probably because it disables alot of stuff.

**Comment by dmulloy2** [comment]
Yeah, there have been issues with AuthMe in 1.9. Based on the repo, it doesn't look like it has been updated for 1.9 yet.

**Comment by dmulloy2** [comment]
Looks like Authme's been updated to 1.9. If there are still issues, report them in another ticket.
