### ISSUE TITLE
#1740 has broken the PRIMED_TNT entity

### ISSUE THREAD

**Issue by Peng1104** [dmulloy2/ProtocolLib#1791]
- [x] This issue is not solved in a development build

**Describe the bug**

[Video showing the bug](https://youtu.be/OhcfUEieAP8)

The new way of getting the entitys, (#1740) has broken my plugin, Bukkit has a long problem of getting some entitys by their IDs, in special the [PRIMED_TNT](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#PRIMED_TNT).

My Code:

	@Override
	public void onSend(PacketEvent event) {
		if (event.getPacketType() == Server.SPAWN_ENTITY) {
			PacketPlayOutSpawnEntity packet = new PacketPlayOutSpawnEntity(event.getPacket()); //PacketWrapper
			
			if (packet.getEntityType() == EntityType.PRIMED_TNT) {
				for (ProtectedRegion region : getRegionSet(getManager(event.getPlayer().getWorld()), packet.getLocation())) { // WorldGuard Stuff
					if (region.getFlag(flag) == State.ALLOW) { // WorldGuard Stuff
						event.setCancelled(true);
						packet.getEntity(event).remove(); //Entity is null
						break;
					}
				}
			}
		}
	}

**Expected behavior**
Revert this commit.

**Screenshots**

**Version Info**
ProtocolLib-5.0.0-SNAPSHOT-b576 to the latest one.

**Comment by derklaro** [comment]
Idk what you want to say, but it seems to work for me?
I'm using this code:
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, PacketType.Play.Server.SPAWN_ENTITY) {
  @Override
  public void onPacketSending(PacketEvent event) {
    EntityType type = event.getPacket().getEntityTypeModifier().read(0);
    Entity resolved = event.getPacket().getEntityModifier(event).read(0);

    event.getPlayer().sendMessage(type + " /// " + resolved);
    }
});
```

And get that output:
![image](https://user-images.githubusercontent.com/40468651/181816497-90c32084-1bfd-4b57-b9a3-798e530743b8.png)

**Comment by Peng1104** [comment]
> ```java
> getPacket
> ```

whit version of the Minecraft Server are you using?

**Comment by derklaro** [comment]
git-Paper-86 (MC: 1.19.1)

**Comment by Peng1104** [comment]
@derklaro As you where the autor of the #1740 can you help me to create a check if the ProtocolLib is running in a legacy version and use the old way of getting the Entitys?

**Comment by derklaro** [comment]
Interesting, seems like there are different types of lists when an entity is added to the world. For TNT it kinda looks like this: addToAllEntity -> trackAndSendPacket -> addEntityById. Therefore you cannot find the entity using the outbound id.

I'm not happy with just using the old way (looping over all entities) to find the entity, there must be a better way to do that. Will take a look into that soonish.

**Comment by Peng1104** [comment]
I have made a work around 

> Interesting, seems like there are different types of lists when an entity is added to the world. For TNT it kinda looks like this: addToAllEntity -> trackAndSendPacket -> addEntityById. Therefore you cannot find the entity using the outbound id.
> 
> I'm not happy with just using the old way (looping over all entities) to find the entity, there must be a better way to do that. Will take a look into that soonish.

Thx I am no specialist at the minecraft server inside workings, I have made a work around using the EntityExplodeEvent for my problem, but it has cause a side effect of a invisible PRIMED_TNT been pressent until it explodes, blocking any projectile from hitting the "behind" TNT.

	@Override
	public void onSend(PacketEvent event) {
		if (event.getPacketType() == Server.SPAWN_ENTITY) {
			PacketPlayOutSpawnEntity packet = new PacketPlayOutSpawnEntity(event.getPacket());
			
			if (packet.getEntityType() == EntityType.PRIMED_TNT) {
				for (ProtectedRegion region : getRegionSet(getManager(event.getPlayer().getWorld()),
						packet.getLocation())) {
					
					if (region.getFlag(flag) == State.ALLOW) {
						event.setCancelled(true);
						break;
					}
				}
			}
		}
	}

	@EventHandler
	private void onTNTExplosion(@NotNull EntityExplodeEvent event) {
		if (event.getEntityType() == EntityType.PRIMED_TNT) {
			for (ProtectedRegion region : getRegionSet(getManager(event.getEntity().getWorld()),
					event.getEntity().getLocation())) {
				
				if (region.getFlag(flag) == State.ALLOW) {
					event.getEntity().remove();
					event.setCancelled(true);
					break;
				}
			}
		}
	}

**Comment by derklaro** [comment]
FTR: seems like the tracking change was introduced in 1.14
