### ISSUE TITLE
VISUAL BUG

### ISSUE THREAD

**Issue by PhoenixGaming155** [dmulloy2/ProtocolLib#1793]
- [ ] This issue is not solved in a development build

**Describe the bug**
My server have Mohist and the server print a message each x time.

**To Reproduce**

4. See error. The error appear each x time.
I think that only is a visual bug, but i want disguise it

**Expected behavior**

**Screenshots**
![caperror](https://user-images.githubusercontent.com/100540221/181917708-22a5ecd2-2c51-4004-951e-99f18bbd8d42.png)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
I no find the document.

**Additional context**

[message (4).txt](https://github.com/dmulloy2/ProtocolLib/files/9226607/message.4.txt)

**Comment by derklaro** [comment]
Mohist is not supported. Please use spigot (or a fork like paper) to get support.
