### ISSUE TITLE
PacketType.Play.Server.CHAT not firing

### ISSUE THREAD

**Issue by kangarko** [dmulloy2/ProtocolLib#1796]
- [X] This issue is not solved in a development build >> actually **happens only in development builds**

**Describe the bug**
I made a simple code extending SimpleAdapter and registered as all the other code: https://i.imgur.com/JWSEMht.png

**Expected behavior**
The console message should appear on chatting. It **does work fine** on ProtocolLib 4.8.0 but **is consistently broken under latest 5.0.0 snapshots**, does not fire at all.

**Version Info**
5.0.0-SNAPSHOT-b586

[dump-2022-07-31_19.29.06.txt](https://github.com/dmulloy2/ProtocolLib/files/9229375/dump-2022-07-31_19.29.06.txt)

**Comment by derklaro** [comment]
chat messages in 1.19.1 are sent by spigot via SYSTEM_CHAT

**Comment by kangarko** [comment]
Thank you! Maybe @dmulloy2 can include a note for developers somewhere visible ;)

**Comment by derklaro** [comment]
I don't see any reason for that, CHAT and SYSTEM_CHAT are still different packet types, and chat *should* be used for player messages, but that means that the message cannot be modified (because it's signed). Therefore spigot is using SYSTEM_CHAT, Paper might switch soon tho.
