### ISSUE TITLE
PacketWrappers | Entity packets

### ISSUE THREAD

**Issue by pmilon** [dmulloy2/ProtocolLib#180]
Hi,

After the recent 1.9 update, all entity wrapper packets I am using in my plugin no longer work.
For example, the WrapperPlayServerSpawnEntityLiving does not throw any error, but no entity's spawning (though my code didn't change) :

http://pastebin.com/XxKv6PyG

WrapperPlayServerEntityRelMove throws an IndexOutOfBound error when trying to change de velocity on y axis.
Given that it uses bytes for the velocity changes, i've modified it so it uses integers (because IntegersModifier's size is 4 ; 1 for entity ID & 3 for velocity's changes) :

http://pastebin.com/uWttTp8s

But it still doesn't work...
I think PacketWrappers related to entities are broken and need a little update, am I wrong?

Thanks for reading.

**Comment by pmilon** [comment]
I might have resolved y problem.
But this is important because it applies to every packet using coordinates :
They are now saved as Doubles and no longer multiplied by 32.

I'm doing further investigation and will update this post when my problem is completely resolved.

**Comment by pmilon** [comment]
Well, this would have been too easy.
So it appears that this applies to every packet using fixed coordinates (x,y,z) like spawnEntityLiving or spawnEntityWeather, but this is not solving my problem with velocity packet.

**Comment by pmilon** [comment]
Problem solved.
Velocity changes in VelocityPacket are saved as integers (value*8000.0D).

Use of this post :
- Every packet using fixed coordinates as integers multiplied by 32 needs an update.
- WrapperPlayServerEntityRelMove needs an update.

These changes only apply to 1.9 spigot.

**Comment by dmulloy2** [comment]
Should be fixed in https://github.com/dmulloy2/PacketWrapper/commit/22b866872c91cb5c40d758c870a05a3f2b6c6879
