### ISSUE TITLE
Messages are being sent in the wrong order

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#1806]
- [x] This issue is not solved in a development build

**Describe the bug**
Hello, on the lastest ProtocolLib version (v5.0.0-SNAPSHOT-b587), messages are being sent in the wrong order (see screenshots) while having specific plugins installed. I've had this issue already with ChatControl and fixed it myself by disabling every feature requiring ProtocolLib.  However, InteractiveChat is having the same issue. The author of it told me that he was doing some tests and that it seems like ProtocolLib self is the problem; he's willing to provide additional information if needed. This issue applies on 1.8.8 + ProtocolLib 5.0 **only**. ProtocolLib 4.8 works fine.

**To Reproduce**
1. Run your server on 1.8.8 (Paper) & install ProtocolLib v5 as well as InteractiveChat
2. Restart the server
3. Type commands showing leaderboards (just like /baltop or similar)
4. See wrong ordering

**Expected behavior**
Correct order.

**Screenshots**
![image](https://user-images.githubusercontent.com/109244524/182672772-e4f3cc65-2247-4cb8-85d1-2d793fd45ed4.png)

**Version Info**
https://pastebin.com/nXgXbqnk

**Additional context**

**Comment by LOOHP** [comment]
According to my testing, the (sync) chat packet listener seems to be receving clientbound chat packets in the wrong order on 1.8.8 and with ProtocolLib 5.0.0 (4.8.0 works fine).
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(PacketAdapter.params().plugin(plugin).listenerPriority(ListenerPriority.MONITOR).types(PacketType.Play.Server.CHAT)) {
        @Override
        public void onPacketSending(PacketEvent event) {
                PacketContainer packet = event.getPacket();
                if (packet.getModifier().read(1) == null) {
                        System.out.println(packet.getChatComponents().read(0).getJson());
                } else {
                        System.out.println(ComponentSerializer.toString((BaseComponent[]) packet.getModifier().read(1)));
                }
        }
});
```

**Comment by derklaro** [comment]
@LOOHP can you specify "wrong oder"? Completely random, reversed etc? (Maybe a screen how it should look like and how it looks 😄 )

**Comment by LOOHP** [comment]
Ah right, "wrong order" here refers to "incorrect order, different and appears to be random each time".

**Comment by LOOHP** [comment]
It happens when chat messages are sent in quick secession, they might not arrive at the chat listeners in the right order*.

**Comment by derklaro** [comment]
Need to take a look at this then. Based on the fact that it works on 1.19 I'm not really sure what exactly is causing the issue here...

**Comment by PureMC** [comment]
Hey, wondering if there are any news on this. @derklaro
