### ISSUE TITLE
com.comphenix.net.sf.cglib.proxy.Enhancer 

### ISSUE THREAD

**Issue by LestRocky** [dmulloy2/ProtocolLib#1807]
the console drops errors when im trying to join in my server 

ProtocolLib version 1.8

https://pastebin.com/aMJ75k6X

**Comment by derklaro** [comment]
I cannot see which version of ProtocolLib you are running, but based on the fact that it still uses gclib: please update to get support

**Comment by LestRocky** [comment]
protocollib 4.3.0
