### ISSUE TITLE
Tab Menu

### ISSUE THREAD

**Issue by dustin1525** [dmulloy2/ProtocolLib#181]
When my players join with this plugin activated, I get 0 console errors, but players tab menu seems to break. (I'll try my best explaining the next bit but please try to stay with me). 

Every time a player joins, they can not see the players that join before them
Example:

Jimmy joins the server,
Bob joins the server,
Richard joins the server,

Jimmy can see Bob, but Bob can't see Jimmy.
Richard can see no one but Bob AND Jimmy can see Richard.

Sadly as said above, no console errors are given.

**Comment by dustin1525** [comment]
http://pastebin.com/G6kn2HUf

**Comment by dmulloy2** [comment]
Fairly certain this is an issue with AuthMe. I've gotten reports like this and the cause was AuthMe.

**Comment by dustin1525** [comment]
Alright, Thank you for your help!
