### ISSUE TITLE
 Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@45b31c5f.

### ISSUE THREAD

**Issue by TheIrishLadYT** [dmulloy2/ProtocolLib#1810]
<html>
<body>

Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@45b31c5f.
--
528 | [19:53:18] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
529 | If this problem hasn't already been reported, please open a ticket
530 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
531 | Stack Trace:
532 | java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
533 | at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
534 | at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
535 | at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
536 | at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584)
537 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
538 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
539 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
540 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
541 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
542 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
543 | at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
544 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
545 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
546 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
547 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
548 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
549 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
550 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
551 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
552 | at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90)
553 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
554 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
555 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
556 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
557 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
558 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
559 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
560 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
561 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
562 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
563 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
564 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
565 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
566 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
567 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
568 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
569 | at java.base/java.lang.Thread.run(Thread.java:833)
570 | Dump:
571 | Parameters:
572 | io.netty.buffer.PooledUnsafeDirectByteBuf@3e3bd77a[
573 | memoryAddress=140596609032208
574 | recyclerHandle=NOOP_HANDLE
575 | chunk=Chunk(5024d11: 1%, 24576/4194304)
576 | handle=1125929971613696
577 | memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
578 | offset=16384
579 | length=1
580 | maxLength=16
581 | cache=io.netty.buffer.PoolThreadCache@233daa0
582 | tmpNioBuf=<null>
583 | allocator=PooledByteBufAllocator(directByDefault: true)
584 | refCnt=2
585 | readerIndex=1
586 | writerIndex=1
587 | markedReaderIndex=0
588 | markedWriterIndex=0
589 | maxCapacity=2147483647
590 | ]
591 | manager:
592 | com.comphenix.protocol.injector.PacketFilterManager@2bb013b5[
593 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3c4db917
594 | packetListeners=[]
595 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@203792e4
596 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5f892194
597 | inputBufferedPackets=[]
598 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@740fbc6b
599 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@255b26fc
600 | hasClosed=false
601 | classLoader=org.bukkit.plugin.java.PluginClassLoader@66ada867
602 | reporter=com.comphenix.protocol.ProtocolLib$1@39673001
603 | server=CraftServer{serverName=CraftBukkit,serverVersion=3553-Spigot-14a2382-ef09464,minecraftVersion=1.19}
604 | library=ProtocolLib v4.7.0
605 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@26913e49
606 | knowsServerPackets=true
607 | knowsClientPackets=true
608 | phaseLoginCount=0
609 | phasePlayingCount=0
610 | packetCreation=false
611 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7b494ee0
612 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2d1b4db0
613 | hasRecycleDistance=true
614 | minecraftVersion=(MC: 1.19.0)
615 | debug=false
616 | ]
617 | Sender:
618 | com.comphenix.protocol.injector.netty.ChannelInjector@45b31c5f[
619 | decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
620 | encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
621 | factory=com.comphenix.protocol.injector.netty.InjectionFactory@7dccef6d
622 | player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2040556f
623 | updated=<null>
624 | playerName=<null>
625 | playerConnection=<null>
626 | networkManager=net.minecraft.network.NetworkManager@a3c5da2
627 | originalChannel=[id: 0xaeacd353, L:/172.20.0.46:50520 - R:/50.83.112.61:51488]
628 | channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@a3c5da2, previous=[id: 0xaeacd353, L:/172.20.0.46:50520 - R:/50.83.112.61:51488], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@ddb662b, previousLoaded=true, currentSet=true, forceAccess=true]
629 | packetMarker={}
630 | currentEvent=<null>
631 | finalEvent=<null>
632 | unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@49d556e7
633 | vanillaDecoder=net.minecraft.network.PacketDecoder@613cbd22
634 | vanillaEncoder=net.minecraft.network.PacketEncoder@6dfd79f8
635 | finishQueue=[]
636 | channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7b494ee0
637 | processor=com.comphenix.protocol.injector.NetworkProcessor@58c0bba3
638 | injected=true
639 | closed=false
640 | cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
641 | cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5c11d834
642 | singleDecode=false
643 | first=true
644 | firedChannelRead=true
645 | selfFiredChannelRead=true
646 | decodeState=1
647 | discardAfterReads=16
648 | numReads=0
649 | added=true
650 | ]
651 | Version:
652 | ProtocolLib v4.7.0
653 | Java Version:
654 | 17.0.2
655 | Server:
656 | 3553-Spigot-14a2382-ef09464 (MC: 1.19)

</body>
</html>Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@45b31c5f.
[19:53:18] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@3e3bd77a[
      memoryAddress=140596609032208
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(5024d11: 1%, 24576/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@233daa0
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2bb013b5[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3c4db917
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@203792e4
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5f892194
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@740fbc6b
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@255b26fc
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@66ada867
        reporter=com.comphenix.protocol.ProtocolLib$1@39673001
        server=CraftServer{serverName=CraftBukkit,serverVersion=3[553](https://aternos.org/log/#L553)-Spigot-14a2382-ef09464,minecraftVersion=1.19}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@26913e49
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7b494ee0
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2d1b4db0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@45b31c5f[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7dccef6d
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2040[556](https://aternos.org/log/#L556)f
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@a3c5da2
      originalChannel=[id: 0xaeacd353, L:/172.20.0.46:50520 - R:/50.83.112.61:51488]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@a3c5da2, previous=[id: 0xaeacd353, L:/172.20.0.46:50520 - R:/50.83.112.61:51488], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@ddb662b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@49d556e7
      vanillaDecoder=net.minecraft.network.PacketDecoder@[613](https://aternos.org/log/#L613)cbd22
      vanillaEncoder=net.minecraft.network.PacketEncoder@6dfd79f8
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7b494ee0
      processor=com.comphenix.protocol.injector.NetworkProcessor@58c0bba3
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5c11d834
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    17.0.2
  Server:
    3553-Spigot-14a2382-ef09464 (MC: 1.19)

its all in red on Aternos plz fix this

**Comment by REDKING-11** [comment]
same happened to me?

**Comment by purejosh** [comment]
Same. Hopefully there's a fix soon...

**Comment by purejosh** [comment]
Oh, I feel stupid. We need to use the dev build. 

Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19
Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0) for all other recent Minecraft versions

**Comment by Froggo8311** [comment]
I've been having the same issue. Hopefully the dev build works.

**Comment by Froggo8311** [comment]
I went and downloaded the latest build, and I have not had any error messages since.
