### ISSUE TITLE
Protollib ERROR 

### ISSUE THREAD

**Issue by Manskieeboy** [dmulloy2/ProtocolLib#1819]
An error message keeps popping up in the console everytime a player join.

Here's the logs
https://mclo.gs/IYE7T4G

**Comment by LoJoSho** [comment]
You are currently using ProtocolLib version 4.8. Use ProtocolLib 5.0 for 1.19. 

https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Manskieeboy** [comment]
Ok thanks
