### ISSUE TITLE
Protocollib and AdvancedTabOverlay on 1.19.1

### ISSUE THREAD

**Issue by hypigler** [dmulloy2/ProtocolLib#1821]
- [✔️] This issue is not solved in a development build

**Describe the bug**
Console has errors when protocollib and advanced tab overlay are installed in the same server.
Functionality seems to remain unharmed though. But those errors pop up quite frequently in console when a player is online.

**To Reproduce**
1. have protocollib installed
2. have advanced tab overlay installed
3. have player join server
4. see error sent in console

**Expected behavior**
Nothing to come from my console.

**Screenshots**
My Server Log of Startup, Player Join and Disconnect, Then Stop Server.
https://pastebin.com/aqqQv16u

**Version Info**
Protocollib Dump:
https://pastebin.com/KFpjurAT

**Additional context**
an orange name from advanced tab overlay support said it was a incompatibility with protocollib, so i have come here to seek help and potentially have this problem resolved.

**Comment by derklaro** [comment]
ATO uses methods which no longer exist due to recent changes how we handle reflection.
