### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Big-Guns** [dmulloy2/ProtocolLib#1825]
Make sure you've done the following:
- [*] You're using the latest build for your server version
- [*] This isn't fixed in a recent development build
- [unsure] This isn't an issue caused by another plugin
- [*] You've checked for duplicate issues
- [*] You didn't use `/reload`

Dump link:

https://gist.github.com/Big-Guns/1b4f05ad6ac6ade628a13a817a986bdb

Description and relevant errors:
Started throwing the following error the other day, not sure why.
https://gist.github.com/Big-Guns/85fbdaee8008f4d14bc568742525afea

Plugins list: https://i.imgur.com/6sYhvjR.png

**Comment by ARR4NN** [comment]
Same error for me
