### ISSUE TITLE
Causing server downtime

### ISSUE THREAD

**Issue by xiaozhangup** [dmulloy2/ProtocolLib#1826]
- [x] This issue is not solved in a development build

https://mclo.gs/pw9GRO3

Version 591

**Comment by derklaro** [comment]
This is a MyPet issue, basically receive listeners are now called sync as well if not specified differently. They are deadlocking the server thread by waiting for another sync operation to complete.

**Comment by wanyanjiabin** [comment]
use Version 587 can work with MyPet

**Comment by derklaro** [comment]
Instead of downgrading I would recommend contacting MyPet so that they fix the underlying issue 🤔
