### ISSUE TITLE
Using MonitorAdapter breaks server ping [1.19.x]

### ISSUE THREAD

**Issue by KosmX** [dmulloy2/ProtocolLib#1828]
- [x] This issue is not solved in a development build

**Describe the bug**
When registering a MonitorAdapter packetlistener, server ping won't work.

**To Reproduce**
Create a plugin implementing ProtocolLib. [you may use an older Emotecraft plugin build....](https://github.com/KosmX/emotes/blob/3fdb9c60a014d187d4ed5e684685e52c5de9a982/bukkit/src/main/java/io/github/kosmx/emotes/bukkit/BukkitWrapper.java#L63)

Load 1.19 server (paper or purpur tested)  
From client (or `mcstatus` command) ping the server.
The ping won't work

**Expected behavior**
the ping works

**Screenshots**
![image](https://user-images.githubusercontent.com/15692868/184243300-fda852dd-ec03-4469-809a-125dbfc93d53.png)

**Version Info**
https://pastebin.com/9EXarwuM

**Additional context**
I'm not 100% sure that my implementation is correct.

But it works if I use `PacketAdapter` instead of `MonitorAdapter`.

**Comment by KosmX** [comment]
The ping does not work, but I can join the game/use the plugin without any other issue.

**Comment by derklaro** [comment]
Fixed the underlying issue, nice catch! However for your usecase I would recommend using a single PacketAdapter for the `NAMED_ENTITY_SPAWN` packet as it will reduce the server load :)

**Comment by KosmX** [comment]
I've already changed the plugin to use PacketAdapter.

**Comment by derklaro** [comment]
👍 Didn't see that :)
