### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by SirCraftypants** [dmulloy2/ProtocolLib#1829]
- [x] This issue is not solved in a development build

**Describe the bug**
When anyone tries to join the server they get an internal java socket exception

**To Reproduce**
1. Install Paper 1.19.2
2. Install Protocolib #593
3. Try to join the Server

**Expected behavior**
Denied oonnection 

**Screenshots**
![2022-08-12](https://user-images.githubusercontent.com/66942713/184312310-91335f76-447b-4b08-9c30-97185b9812ec.png)

**Version Info**
https://paste.helpch.at/ixodujedes.cs

**Additional context**
Error https://paste.helpch.at/wisolujaja.php

**Comment by derklaro** [comment]
Did this happen after you changed from an earlier v5 build, or is this a general observation?

**Comment by SirCraftypants** [comment]
> Did this happen after you changed from an earlier v5 build, or is this a general observation?

If i recall i was on the 1.19 version above 553

**Comment by derklaro** [comment]
So the issue occurred after upgrading from build 553 or for all versions since 553? 🤔

**Comment by SirCraftypants** [comment]
> So the issue occurred after upgrading from build 553 or for all versions since 553? 

I hadn't updated in a while so from either 553 or 556 to 593

**Comment by SirCraftypants** [comment]
oh i also updated from 1.19 paper to 1.19.2

**Comment by SirCraftypants** [comment]
Just to be clear because i wasn't before, when i say when anyone tries that includes me the op/owner.

**Comment by derklaro** [comment]
Hm, just tested a bit and I am unable to reproduce this on a vanilla server 🤔

**Comment by SirCraftypants** [comment]
> Hm, just tested a bit and I am unable to reproduce this on a vanilla server 🤔

just got this when i tried to join the server https://paste.helpch.at/rofikumomi.php

**Comment by SirCraftypants** [comment]
just updated to #595 and the error i linked above in the last reply is still occurring

**Comment by SirCraftypants** [comment]
> Hm, just tested a bit and I am unable to reproduce this on a vanilla server 🤔

My server been down for 4 days, still getting this error https://paste.helpch.at/rofikumomi.php and being disconnected on join.

I've gone through ever plugin i have that uses protocolib as a dependency and removed the only plugin that had problems i.e. mypets but not because of this issue, because it's not yet updated for 1.19.2 which is the Paper version i'm on. Despite the removal of mypets this error persists. I've tried all the 1.19.2 protocolib versions up to latest 595 and same problem.

**Comment by derklaro** [comment]
Does the error persist without any plugins other than ProtocolLib? If not try removing each plugin and re-add them until the error comes back... 🤔

**Comment by SirCraftypants** [comment]
> Does the error persist without any plugins other than ProtocolLib? If not try removing each plugin and re-add them until the error comes back... 🤔

I removed all plugins that depend on protocolib and error still persists 

java.lang.IllegalArgumentException: Packet too big (is 9540306, should be less than 8388608): net.minecraft.network.protocol.game.PacketPlayOutAdvancements@712841c5

**Comment by derklaro** [comment]
then try to remove ProtocolLib...

**Comment by SirCraftypants** [comment]
I found the plugin causing the error,  after having to uninstall and one by one reinstall over 80 plugins, it was CustomAdvancements-1.2.3-1.19, i will close this and contact its dev. thanks.
