### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 11 bytes extra whilst reading packet 0

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [dmulloy2/ProtocolLib#1832]
- [x] This issue is not solved in a development build

**Describe the bug**
Everytime After I add ProtocolLib on my server, I will be unable to join my server.
It will says "lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 11 bytes extra whilst reading packet 0"

**To Reproduce**
1. Install Mohist 1.16.5 on your server.
2. Put ProtocolLib into the "Plugins" Folder, then launch it.
3. Try to join your server.

**Expected behavior**
Join the server with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/42903464/184373945-523f972a-b291-492d-b9ee-ceb1cf003541.png)

**Version Info**
[dump-2022-08-12_22.19.17.txt](https://github.com/dmulloy2/ProtocolLib/files/9317519/dump-2022-08-12_22.19.17.txt)

**Additional context**
I tried v4.6, v4.7, v4.8, But the results are the same.
v5.0 is not working on my server.

**Comment by derklaro** [comment]
Mohist is not supported. Please use Spigot (or a fork of Spigot like Paper) to get support.

**Comment by NikaoRG** [comment]
Tengo el mismo problema. Utilizo el  Mohist 1.16.5, asique recomiendas que cambie  Mohist? y instale otro ?

**Comment by Peng1104** [comment]
> Tengo el mismo problema. Utilizo el Mohist 1.16.5, asique recomiendas que cambie Mohist? y instale otro ?

[SpogeForge](https://essentialsx.net/do-not-use-mohist.html) perhaps?
