### ISSUE TITLE
ProtocolLib breaking weapon damage & sword sweeping on mobs.

### ISSUE THREAD

**Issue by mibby** [dmulloy2/ProtocolLib#1835]
- [x] This issue is not solved in a development build

**Describe the bug**
ProtocolLib dev builds are breaking tool damage & sweeping animation from occurring. All swords and axes seem to do 1 damage instead of normal.

Another report here. Breaking from this PR https://github.com/dmulloy2/ProtocolLib/pull/1815.
RE: https://github.com/dmulloy2/ProtocolLib/pull/1815#issuecomment-1211361527

ProtocolLib dev 590 - 593 have the issue. Downgrading to dev 589, issue doesn't exist.
https://ci.dmulloy2.net/job/ProtocolLib/

**To Reproduce**
1. Spawn in a diamond sword & a zombie egg.
2. Place zombie down and hit it with the diamond sword.
3. No sweeping attack and only does 1 heart of damage.

**Expected behavior**
Normal damage on mobs.

**Additional context**
I use a handful of plugins that rely on ProtocolLib such as LibsDisguises. Here is a protocol dump. No exceptions or errors occur otherwise.
https://paste.gg/p/anonymous/7e0a7a47de8a4c53a44b2830531a047a/files/1f4d093173dd4141bb2b15319091a8eb/raw

Paper dev 125 / Purpur dev 1759 (1.19.2)

**Comment by dmulloy2** [comment]
looking into this now
