### ISSUE TITLE
Server crash when I login

### ISSUE THREAD

**Issue by janhoeck** [dmulloy2/ProtocolLib#184]
My Server crashes, when I install ProtocolLib. When I remove ProtocolLib, than all works fine.
http://paste.md-5.net/jeqogacuqu.avrasm

Can this happen by ProtocolLib or is anything else broken?

**Comment by dmulloy2** [comment]
Run /protocol dump and paste the results using pastebin.

**Comment by dmulloy2** [comment]
Any more information on this issue?
