### ISSUE TITLE
1.16 Server Lag

### ISSUE THREAD

**Issue by adabugra** [dmulloy2/ProtocolLib#1843]
- [ ] This issue is not solved in a development build

**Describe the bug**
This bug happenes every 5 minutes and server freezes for 10-20 seconds
https://pastes.dev/5MRtP5VvOm

**Version Info**
ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b595
Bukkit Version: 1.16.5-R0.1-SNAPSHOT
Server Version: git-Paper-794 (MC: 1.16.5)
Java Version: 16.0.1

**Comment by Elikill58** [comment]
The pastebin is empty

**Comment by adabugra** [comment]
> The pastebin is empty

https://pastes.dev/5MRtP5VvOm
