### ISSUE TITLE
Listener all packets break ping and login on 1.19.2

### ISSUE THREAD

**Issue by Elikill58** [dmulloy2/ProtocolLib#1844]
- [x] This issue is not solved in a development build

**Describe the bug**
The server can't be pinged and can't join, it show:
![image](https://user-images.githubusercontent.com/17381066/184496493-bb4c8e73-9253-4432-9faa-c84eeb522dae.png)

**To Reproduce**
Use this code:
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(myPlugin, ListenerPriority.LOWEST, PacketRegistry.getClientPacketTypes()) {
   @Override
   public void onPacketSending(PacketEvent e) {}

   @Override
   public void onPacketReceiving(PacketEvent e) {}
});
```
Will create the error.

**Version Info**
```
ProtocolLib Dump
Timestamp: 08/13/22 15:36:00

ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b595
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Paper-125 (MC: 1.19.2)
Java Version: 17.0.1
```

**Additional context**
I got same problem by using all Server types which were breaking the ping result (show the red cross on top right on server list)

Everything were working fine with 1.19.1 and below

**Comment by derklaro** [comment]
Should be fixed with https://github.com/dmulloy2/ProtocolLib/suites/7798052962/artifacts/328819227

**Comment by Elikill58** [comment]
Yes, I can confirm it's fixed with this dev build, thanks you !

I keep this issue opened, I will let the PR merge close it :)
