### ISSUE TITLE
I can't join my server with protocollib

### ISSUE THREAD

**Issue by ChristianScaduto** [dmulloy2/ProtocolLib#1845]
Hello j have protocolllib #595 and I cant join my server,with version 4.8.0 i can join but plugins don't work,im in minecraft 1.19,someone help me please
![20220811_213303](https://user-images.githubusercontent.com/96024233/184497237-6bad6a90-ba30-4b68-a5eb-21955be48801.jpg)

**Comment by Zoiter7** [comment]
Protocolib 4.8.0 is not works in 1.19

You have to download the last build version for 1.19.
Here you can download it: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Pantera07** [comment]
Please use the latest version.
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
