### ISSUE TITLE
Problems with the server that applied the development version 597 build

### ISSUE THREAD

**Issue by starlight9105** [dmulloy2/ProtocolLib#1848]
server bukkit paper-1.19-81.jar

Problem 1. Only weak attacks applied
normal attack, critical attack not possible

Problem 2. First login after client execution fails unconditionally

ProtocolLib plugin is currently in temporary isolation and normal

**Comment by Helear1** [comment]
I have the same issue with the latest dev build

**Comment by Helear1** [comment]
Its fixed in the 598 build
