### ISSUE TITLE
RPGPlayerLeveling Fix (1.8)

### ISSUE THREAD

**Issue by Blamo27** [dmulloy2/ProtocolLib#185]
We're using your plugin with RPG Levelling, and it's causing this error to spam the console whenever the player put something in the inventory of the Weapon Master (NPC merchant).

http://i.imgur.com/K3GJnCG.png

We would like to know what we can do to fix that (we tried multiple versions of both plugins).

**Comment by dmulloy2** [comment]
I'm not entirely sure how this involves ProtocolLib, looks like an issue with that plugin

**Comment by OsipXD** [comment]
Yes, it's not a problem of ProtocolLib

**Comment by Blamo27** [comment]
I see... Well in fact we paid that plugin RPGLevelling, and it seems it's not working in 1.8 with ProtocolLib. The author of RPGLevelling basically told us to fuck off, so it appears we're screwed... :/

**Comment by dmulloy2** [comment]
The author appears to think the error's "at the core of Spigot", so yeah looks like you're out of luck. There's nothing I can do on ProtocolLib's end, sorry.
