### ISSUE TITLE
ServerListPlus ProtocolLib Error

### ISSUE THREAD

**Issue by Faller10** [dmulloy2/ProtocolLib#186]
I tried multiple ServerListPlus and ProtocolLib versions! But everytime I start the server, and hover over the players count, It gives me this error! Could you help me please?
Thanks, and btw, LOVE YOUR PLUGIN!

Obs.: Currently, I'm using ServerListPlus v3.4.4-1.7.X and ProtocolLib 3.6.5.
I'm using Spigot build 

Error: http://pastebin.com/wKh4GdmH

**Comment by KyleNehman** [comment]
Getting the same kind of UnhandledException from PacketSending that seems to be the result of whenever I call `...  new WrappedDataWatcher(packet.getWatchableCollectionModifier().read(0)); `

**Comment by dmulloy2** [comment]
Use build 232 for Spigot 1.7: http://ci.dmulloy2.net/job/ProtocolLib/232/

**Comment by KyleNehman** [comment]
I don't understand how you can tell me to use an older version that's going to cause even more errors (including but not limited to java.lang.IllegalArgumentException: Unable to find a field tracker with the type net.minecraft.server.v1_9_R1.Entity in net.minecraft.server.v1_9_R1.EntityTrackerEntry)

**Comment by dmulloy2** [comment]
@KyleNehman Your issue is completely separate from this one. Please create a new one with the entire stack trace (with pastebin)
