### ISSUE TITLE
Players constantly being kicked from our server

### ISSUE THREAD

**Issue by yeatt** [dmulloy2/ProtocolLib#1861]
So this issue has been going on for the past week, and there doesn't seem to be an end. We're pretty confident it is a ProtoclLib issue.

We are seeing the same error show only for plugins that use ProtocolLib, here is an example:

[18:12:30 WARN]: [Coinflip] Task #9922795 for Coinflip v1.0 generated an exception
net.minecraft.server.CancelledPacketHandleException: null

It's really hurting us as a server, and many of our plugins rely on this one in order to function.

**Comment by derklaro** [comment]
Please append the full stack trace, as well as the protocollib dump in order for us to help you
