### ISSUE TITLE
Motd from Maintanance plugin doesnt work

### ISSUE THREAD

**Issue by andreighigea** [dmulloy2/ProtocolLib#1863]
- [ ] This issue is not solved in a development build

**Describe the bug**
I added Protocollib to my server in order to add plugins which depend on it, but protocollib made Maintanance not work. Well for other people it says that the server is curently under maintanace when they try to join but the MOTD doesnt show this anymore

**To Reproduce**
1. Install 'Protocollib'
2. Install  'Maintanance'
3. Do '/maintanance on'
4. Leave server and see MOTD

**Expected behavior**
MOTD should be different saying maitanance is on

**Version Info**
4.8.0

**Comment by Peng1104** [comment]
Post a issue to the "Maintanance" plugin author, as this is not a ProtocolLib problem.
