### ISSUE TITLE
(Server/Client).CHAT packet

### ISSUE THREAD

**Issue by RaiTaki** [dmulloy2/ProtocolLib#1864]
- [ ] This issue is not solved in a development build

**Describe the bug**
PacketType.Play.(Server/Client).CHAT packet listening isn't working.

**To Reproduce**
1. Registered my listener.
2. Debugged it.

**Expected behavior**
Get the PacketType.Play.(Server/Client).CHAT packet.

**Screenshots**
![image](https://user-images.githubusercontent.com/55250747/185786719-6217c7df-465a-4a15-ab5a-8d0877cd8c02.png)

**Version Info**
https://pastebin.com/FSqVsv75

**Additional context**
I tried PacketType.Play.Server.SET_ACTION_BAR_TEXT too, didn't work.

**Comment by diogotcorreia** [comment]
On Minecraft 1.19 there is a new packet: [`PacketType.Play.Server.SYSTEM_CHAT`](https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/PacketType.Play.Server.html#SYSTEM_CHAT)
Only signed chat uses the "old" CHAT packet
