### ISSUE TITLE
noClassDefError

### ISSUE THREAD

**Issue by lavaking46** [dmulloy2/ProtocolLib#1870]
- [✔️  ] This issue is not solved in a development build

**Describe the bug**
I'm trying to use protocolLib so that I can use packets to hide player armor. When I load my plugin(1.19) it gives a noClassDefError for PacketListener.

**To Reproduce**
Create simple plugin with something like this in your onEnable method
```
        ProtocolManager manager = ProtocolLibrary.getProtocolManager();
        manager.addPacketListener(new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.ENTITY_EQUIPMENT) {
            @Override
            public void onPacketSending(PacketEvent event) {
                if (equipmentPacketProcessor == null) return;
                equipmentPacketProcessor.process(event);
            }
        });

```
**Expected behavior**
I expected to add a new packetlistener that would allow me to listen for packets that I would then overwrite.

**Version Info**
https://pastebin.com/p0t8Jw0i

**Comment by derklaro** [comment]
You need to add a depend on ProtocolLib in your plugin.yml.

**Comment by lavaking46** [comment]
I Already did

**Comment by lavaking46** [comment]
The error is still the same after having ProtocolLib listed as a dependency

**Comment by lavaking46** [comment]
Sorry to try and continue bumping this and such but I'm still having this issue after having added the plugin as a dependency in my plugin.yml and their has been no updates.
