### ISSUE TITLE
Bungee - Could not decode packet

### ISSUE THREAD

**Issue by Epicrazer27** [dmulloy2/ProtocolLib#1871]
21:37:45 [WARNING] [rqzv] <-> DownstreamBridge <-> [Bedwars] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 9, cap: 64))

we have HBedwars plugin, when we click on the leaderboard this error shows in bungee and sends us to the fallback server. We found out the issue was ProtocolLib, but the error only happens when on a bungeecord server.

**Comment by derklaro** [comment]
The issue is not caused by ProtocolLib, it is caused by a plugin which is (seemingly) creating an invalid packet using the ProtocolLib api.
