### ISSUE TITLE
On server load

### ISSUE THREAD

**Issue by Cakequester** [dmulloy2/ProtocolLib#1873]
Stack Trace: java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397) at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658) at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.base/java.lang.Thread.run(Thread.java:833) Dump: Parameters: io.netty.buffer.PooledUnsafeDirectByteBuf@ffeb387[ memoryAddress=140702592127088 recyclerHandle=io.netty.util.Recycler$DefaultHandle@28804724 chunk=Chunk(4f1acb80: 10%, 385024/4194304) handle=21955078248202241 memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304] offset=319520 length=26 maxLength=32 cache=io.netty.buffer.PoolThreadCache@5d10a527 tmpNioBuf=<null> allocator=PooledByteBufAllocator(directByDefault: true) refCnt=2 readerIndex=26 writerIndex=26 markedReaderIndex=0 markedWriterIndex=0 maxCapacity=2147483647 ] manager: com.comphenix.protocol.injector.PacketFilterManager@1c721692[ unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@345f828d packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[LOOK[class=PacketPlayInLook, id=19], GROUND[class=d, id=20], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priori packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@85ef3a8 playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@48422605 inputBufferedPackets=[] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@21ed8f64 sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2da7db4d hasClosed=false classLoader=org.bukkit.plugin.java.PluginClassLoader@78c6fccb reporter=com.comphenix.protocol.ProtocolLib$1@62b38fc server=CraftServer{serverName=CraftBukkit,serverVersion=3566-Spigot-584b459-c379a6b,minecraftVersion=1.19.2} library=ProtocolLib v4.8.0 asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@47151226 knowsServerPackets=true knowsClientPackets=true phaseLoginCount=0 phasePlayingCount=8 packetCreation=true nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5ab456a pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3fdabdcf hasRecycleDistance=true minecraftVersion=(MC: 1.19.2) debug=false ] Sender: com.comphenix.protocol.injector.netty.ChannelInjector@43f04af7[ decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception factory=com.comphenix.protocol.injector.netty.InjectionFactory@1badc2ff player=CraftPlayer{name=CadeMonster} updated=<null> playerName=CadeMonster playerConnection=net.minecraft.server.network.PlayerConnection@44b8c732 networkManager=net.minecraft.network.NetworkManager@11476d82 originalChannel=[id: 0xdcbad0b4, L:/240.4.65.109:25575 - R:/240.4.14.148:53760] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@11476d82, previous=[id: 0xdcbad0b4, L:/240.4.65.109:25575 - R:/240.4.14.148:53760], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@4972f017, previousLoaded=true, currentSet=true, forceAccess=true] packetMarker={} currentEvent=<null> finalEvent=<null> unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@29acf77e vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@7426002 vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@9306131 finishQueue=[] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5ab456a processor=com.comphenix.protocol.injector.NetworkProcessor@19c5d0d2 injected=true closed=false cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26) cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@d93f198 singleDecode=false first=true firedChannelRead=false selfFiredChannelRead=true decodeState=1 discardAfterReads=16 numReads=0 added=true ] Version: ProtocolLib v4.8.0 Java Version: 17.0.1 Server: 3566-Spigot-584b459-c379a6b (MC: 1.19.2)
Debug paste link:

Description and relevant errors:
didn't use /reload this just happens on load

**Comment by Peng1104** [comment]
@Cakequester Update ProtocolLib to lates dev version, read spigot page.
