### ISSUE TITLE
"Packet encoding of packet ID 85 threw (skippable? false)"

### ISSUE THREAD

**Issue by MrJack025** [dmulloy2/ProtocolLib#1874]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [] You're using the latest build for your server version
- [ ] This isn't fixed in a recent development build
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:

[dump-2022-08-25_17.12.03.txt](https://github.com/dmulloy2/ProtocolLib/files/9428529/dump-2022-08-25_17.12.03.txt)
I saw that someone had the same error as me, but never put his /protocol dump this is mine I hope you can help me:

https://pastebin.pl/view/b3a679ef

Description and relevant errors:

Hello! my server is disconnecting all the users (it only disconnects them, it doesn't crash the server, it only disconnects the users, they can connect again quickly without problems) and this error appears in the console:

"Packet encoding of packet ID 85 threw (skippable? false)"

Yesterday I contacted by chat and they suggested me to update ProtocolLib to the latest version but it didn't work, so they redirected me to open a ticket.

**Comment by MisterGranti67** [comment]
I also have this problem, I spam this 10 times, then everyone and kicked out of the server. So when we are a hundred connected, it is clear that it hurts.
https://hastebin.com/uxolerawob.swift
