### ISSUE TITLE
Stack trace bug

### ISSUE THREAD

**Issue by nexiumz** [dmulloy2/ProtocolLib#1876]
- [ ] This issue is not solved in a development build

**Describe the bug**
`28.08 06:07:42 [Server] INFO Stack Trace:
28.08 06:07:42 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
28.08 06:07:42 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
28.08 06:07:42 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
28.08 06:07:42 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
28.08 06:07:42 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
28.08 06:07:42 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
28.08 06:07:42 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
28.08 06:07:42 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
28.08 06:07:42 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
28.08 06:07:42 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
28.08 06:07:42 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
28.08 06:07:42 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
28.08 06:07:42 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
28.08 06:07:42 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
28.08 06:07:42 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
28.08 06:07:42 [Server] INFO Dump:
28.08 06:07:42 [Server] INFO Parameters: 
28.08 06:07:42 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@34f2158c[
28.08 06:07:42 [Server] INFO memoryAddress=139938691685664
28.08 06:07:42 [Server] INFO recyclerHandle=io.netty.util.Recycler$DefaultHandle@70d70902
28.08 06:07:42 [Server] INFO chunk=Chunk(1aaff21a: 15%, 598016/4194304)
28.08 06:07:42 [Server] INFO handle=5629563958722561
28.08 06:07:42 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
28.08 06:07:42 [Server] INFO offset=81968
28.08 06:07:42 [Server] INFO length=34
28.08 06:07:42 [Server] INFO maxLength=48
28.08 06:07:42 [Server] INFO cache=io.netty.buffer.PoolThreadCache@61f42324
28.08 06:07:42 [Server] INFO tmpNioBuf=<null>
28.08 06:07:42 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
28.08 06:07:42 [Server] INFO refCnt=2
28.08 06:07:42 [Server] INFO readerIndex=34
28.08 06:07:42 [Server] INFO writerIndex=34
28.08 06:07:42 [Server] INFO markedReaderIndex=0
28.08 06:07:42 [Server] INFO markedWriterIndex=0
28.08 06:07:42 [Server] INFO maxCapacity=2147483647
28.08 06:07:42 [Server] INFO ]
28.08 06:07:42 [Server] INFO manager:
28.08 06:07:42 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@7c8c77a3[
28.08 06:07:42 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2cb5a0c2
28.08 06:07:42 [Server] INFO packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PlayerAuctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]]
28.08 06:07:42 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@747723e6
28.08 06:07:42 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@d357170
28.08 06:07:42 [Server] INFO inputBufferedPackets=[]
28.08 06:07:42 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@129b2e1a
28.08 06:07:42 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@13a93f3b
28.08 06:07:42 [Server] INFO hasClosed=false
28.08 06:07:42 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
28.08 06:07:42 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@5e8c46bb
28.08 06:07:42 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-91,minecraftVersion=1.19.1}
28.08 06:07:42 [Server] INFO library=ProtocolLib v4.8.0
28.08 06:07:42 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3334081d
28.08 06:07:42 [Server] INFO knowsServerPackets=true
28.08 06:07:42 [Server] INFO knowsClientPackets=true
28.08 06:07:42 [Server] INFO phaseLoginCount=0
28.08 06:07:42 [Server] INFO phasePlayingCount=4
28.08 06:07:42 [Server] INFO packetCreation=false
28.08 06:07:42 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1e07d5f2
28.08 06:07:42 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2682404
28.08 06:07:42 [Server] INFO hasRecycleDistance=true
28.08 06:07:42 [Server] INFO minecraftVersion=(MC: 1.19.1)
28.08 06:07:42 [Server] INFO debug=false
28.08 06:07:42 [Server] INFO ]
28.08 06:07:42 [Server] INFO Sender:
28.08 06:07:42 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@1b178f2f[
28.08 06:07:42 [Server] INFO decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
28.08 06:07:42 [Server] INFO encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
28.08 06:07:42 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@67aea062
28.08 06:07:42 [Server] INFO player=CraftPlayer{name=Chronologica1}
28.08 06:07:42 [Server] INFO updated=<null>
28.08 06:07:42 [Server] INFO playerName=Chronologica1
28.08 06:07:42 [Server] INFO playerConnection=<null>
28.08 06:07:42 [Server] INFO networkManager=net.minecraft.network.NetworkManager@26b12c62
28.08 06:07:42 [Server] INFO originalChannel=[id: 0xc90f7236, L:/172.17.0.8:25565 - R:/144.217.77.101:45665]
28.08 06:07:42 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@26b12c62, previous=[id: 0xc90f7236, L:/172.17.0.8:25565 - R:/144.217.77.101:45665], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@492f2aab, previousLoaded=true, currentSet=true, forceAccess=true]
28.08 06:07:42 [Server] INFO packetMarker={}
28.08 06:07:42 [Server] INFO currentEvent=<null>
28.08 06:07:42 [Server] INFO finalEvent=<null>
28.08 06:07:42 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1380c15b
28.08 06:07:42 [Server] INFO vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@3cfd2d75
28.08 06:07:42 [Server] INFO vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@67b57f93
28.08 06:07:42 [Server] INFO finishQueue=[]
28.08 06:07:42 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1e07d5f2
28.08 06:07:42 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@4260e201
28.08 06:07:42 [Server] INFO injected=true
28.08 06:07:42 [Server] INFO closed=false
28.08 06:07:42 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
28.08 06:07:42 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@a53ff3e
28.08 06:07:42 [Server] INFO singleDecode=false
28.08 06:07:42 [Server] INFO first=true
28.08 06:07:42 [Server] INFO firedChannelRead=true
28.08 06:07:42 [Server] INFO selfFiredChannelRead=true
28.08 06:07:42 [Server] INFO decodeState=1
28.08 06:07:42 [Server] INFO discardAfterReads=16
28.08 06:07:42 [Server] INFO numReads=0
28.08 06:07:42 [Server] INFO added=true
28.08 06:07:42 [Server] INFO ]
28.08 06:07:42 [Server] INFO Version:
28.08 06:07:42 [Server] INFO ProtocolLib v4.8.0
28.08 06:07:42 [Server] INFO Java Version:
28.08 06:07:42 [Server] INFO 17.0.2
28.08 06:07:42 [Server] INFO Server:
28.08 06:07:42 [Server] INFO git-Paper-91 (MC: 1.19.1)
28.08 06:07:43 [Server] INFO CONSOLE issued server command: /list 
28.08 06:07:43 [Server] INFO There are 1 out of maximum 40 players online.
28.08 06:07:43 [Server] INFO Admins: [OWNER]Chronologica1
28.08 06:07:49 [Server] WARN [DetailedErrorReporter] Internal exception count: 32!
28.08 06:07:49 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@1b178f2f.`
**To Reproduce**
Have "spoof", a player spoofing plugin on a 1.19 server, "player" joining causes issues

**Expected behavior**
Not this lol

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by derklaro** [comment]
Use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support
