### ISSUE TITLE
I forgot my password in a public server and i didnt bind my account with a email Is there any solution?

### ISSUE THREAD

**Issue by Eclabiur** [dmulloy2/ProtocolLib#1877]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.

**API method(s) used**
List what API method(s) you're using

**Expected behavior**

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by derklaro** [comment]
I am not sure how this question is related to ProtocolLib?

**Comment by Eclabiur** [comment]
> I am not sure how this question is related to ProtocolLib

Its not.
