### ISSUE TITLE
Command to Update to Latest Dev Build

### ISSUE THREAD

**Issue by BobtheBob123456** [dmulloy2/ProtocolLib#1878]
Basically, my idea to have a new command called /pl update. This command allow you to update to the next version of Protocollib, or the latest dev build if you run /pl update dev.

The reason I suggest this is I use aternos and it won't let me download the latest dev builds so this would be extremely useful.

**Comment by derklaro** [comment]
I don't think that is something that we can implement, especially considering platform limitations like on windows where deleting the old file is not possible until the server has been stopped completely.
