### ISSUE TITLE
Player head skin problem

### ISSUE THREAD

**Issue by Choreoz** [dmulloy2/ProtocolLib#188]
Hi, I'm trying to replace player's helmet slot with a player head by editing ENTITY_EQUIPMENT packet  just how it's done here https://gist.github.com/aadnk/11323369

My packet listener - http://pastebin.com/EHCg9aqb

The problem is that the head skin won't show up.
Screenshot - http://imgur.com/jAIAUk4
Spigot version: 1.8
I'm running ProtocolLib v3.7.0 and I also tried v3.6.5
The server is in offline mode, but if I'm trying to place player heads in my helmet slot manually, the head skin is rendering just fine.

Any ideas on how to get this to work?

**Comment by dmulloy2** [comment]
You'll likely have to update some of the packet handling to use the new ItemSlot enum and by extension the use of both hands. You might consider using [SkinsRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/), which does what it looks like you're trying to do.
