### ISSUE TITLE
Error message spamming console

### ISSUE THREAD

**Issue by FinestAF** [dmulloy2/ProtocolLib#1881]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/utKcbxfY

Description and relevant errors: An error message spams my console. I spoke with the developer of the printer plugin who said it was a protocollib problem.
I am running paper 1.18.2

Error message:
https://pastebin.com/utKcbxfY

**Comment by derklaro** [comment]
The error is correct. Accessing chunk entities from an async context is not something you should do, nor is there any support by us if you do that.
