### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tpgaming720** [dmulloy2/ProtocolLib#1883]
ProtocolLib Dump
Timestamp: 08/30/22 02:46:44

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Paper-135 (MC: 1.19.2)
Java Version: 17.0.2

ProtocolLib: com.comphenix.protocol.ProtocolLib@20be085d[
  statistics=com.comphenix.protocol.metrics.Statistics@40b2194a
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@49b088cf
  packetTask=9
  tickCounter=6151
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6d5f1180
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@23450acc
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@73690219
  commandProtocol=com.comphenix.protocol.CommandProtocol@23c13d77
  commandPacket=com.comphenix.protocol.CommandPacket@6efa2f30
  commandFilter=com.comphenix.protocol.CommandFilter@65625b49
  packetLogging=com.comphenix.protocol.PacketLogging@5e20f436
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@74a04000
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-135,minecraftVersion=1.19.2}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@4b9c620b
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@658b12ca
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@79d910b1[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6d5f1180
  packetListeners=[PacketAdapter[plugin=ServerBooster, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Pl-Hide-Pro, sending=ListeningWhitelist[priority=NORMAL, packets=[COMMANDS[class=PacketPlayOutCommands, id=18]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Pl-Hide-Pro, sending=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=ServerBooster, sending=ListeningWhitelist[priority=NORMAL, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=34]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@69feea5b
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@455dcac1
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@74300643
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@61f6ca54
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@7fc45803
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-135,minecraftVersion=1.19.2}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@20929829
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=7
  packetCreation=true
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e3cd8f9
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@13b05e51
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.2)
  debug=false
]

Listeners:
dev.lone.serverbooster.main.aF@5bbeba3f[
  b=dev.lone.serverbooster.main.aE@135dee3b
  plugin=ServerBooster v1.1.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]]
]
eu.decentsoftware.holograms.api.nms.PacketHandler__ProtocolLib$1@616ebd4d[
  plugin=DecentHolograms v2.5.3
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
eu.nononitas.plhidepro.spigot.b.b@2f0dcc3a[
  plugin=Pl-Hide-Pro v2.3.2
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[COMMANDS[class=PacketPlayOutCommands, id=18]], gamephase=PLAYING, options=[]]
]
eu.nononitas.plhidepro.spigot.b.e@1c08dc9[
  a={}
  plugin=Pl-Hide-Pro v2.3.2
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]
]
dev.lone.serverbooster.main.an@6ff29a0f[
  b=dev.lone.serverbooster.main.am@38346607
  plugin=ServerBooster v1.1.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=34]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
Pl-Hide-Pro by [Nononitas]
DecentHolograms by [d0by]
ServerBooster by [LoneDev, Travis Watkins, redwall_hp, Esmorall]

**Comment by DimaSergeew** [comment]
protocollib 4.8.0 no support 1.18, pls install dev build
