### ISSUE TITLE
Mohist dont work on with the Plugin

### ISSUE THREAD

**Issue by discofalafel** [dmulloy2/ProtocolLib#1887]
- [ ] This issue is not solved in a development build

**Describe the bug**
Im Using Mohist 1.16.5-1072 and it dont work with Protocollib 4.8.0

**To Reproduce**
Use Mohist server and try to join

**Expected behavior**
That the Plugin work 

**Screenshots**
Idk have one but if i try to join: MH007 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 29 bytes extra whilst reading packet

**Version Info**
4.8.0

**Additional context**
I cant join with the plugin on my mohist server

**Comment by RafaelGamerBr49** [comment]
hi friend, protocollib only "support" mohist in 1.12.2, i search alot about it
