### ISSUE TITLE
ProtocolLibray#getProtocolManager returns null

### ISSUE THREAD

**Issue by WindLeaf233** [dmulloy2/ProtocolLib#1889]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
Please have this solved, thanks! #1875

**Comment by WindLeaf233** [comment]
I noticed that the Owner neither any Contributors did not respond that issue, if this issue make you confused I'm sorry, I really need to solve this issue. :(

**Comment by JaHollTV** [comment]
same issue

**Comment by JaHollTV** [comment]
> I noticed that the Owner neither any Contributors did not respond that issue, if this issue make you confused I'm sorry, I really need to solve this issue. :(

did you solve it?

**Comment by CodingWithSimax** [comment]
Same issue here, the plugin is currently not usable

**Comment by WindLeaf233** [comment]
> > I noticed that the Owner neither any Contributors did not respond that issue, if this issue make you confused I'm sorry, I really need to solve this issue. :(
> 
> did you solve it?

No

**Comment by JaHollTV** [comment]
> ot respond that issue, if this issue make you confused I'm sorry, I really need to solve this issue. :(

Possibly found a solution: 
If you use Gradle then don't use shadow or implementation for ProtocolLib.
Only use: compileOnly("com.comphenix.protocol", "ProtocolLib", "4.8.0");
