### ISSUE TITLE
Use ASM or similar for public/packageprivate method/field reflection access

### ISSUE THREAD

**Issue by Janmm14** [dmulloy2/ProtocolLib#189]
Once the class created at runtime is loaded it can give another speed boost.

**Comment by Shevchik** [comment]
Almost all the packet fields are just private. You will have to generate code that uses MagicAccessorImpl or private static method handles anyway.

**Comment by Janmm14** [comment]
I don't know exactly, but can't you generate static inner classes?

**Comment by dmulloy2** [comment]
Something like this maybe: https://github.com/aadnk/ProtocolLib/commit/1b2f07a24cad6eabcd0db7d3eb16a6907f7ce94f

**Comment by Janmm14** [comment]
Actually I did not knew about that magic thing.

And for benchmarks: Many things can go wrong, I'd suggest using JMH Benchmark Framework.

**Comment by Techcable** [comment]
Unsafe should be used for field access.

**Comment by sinnlosername** [comment]
You could use ASM to rewrite classes at runtime, so you can edit fields from private to public/protected

**Comment by Techcable** [comment]
You don't need to edit field visibility if you use `sun.misc.Unsafe`.
In fact, Unsafe is so fast that the JDK's underlying reflection implementation uses it exclusively, without doing any bytecode generation at all.
Unsafe accesses are compiler intrinsics that compile down to a couple assembly instructions, just like a direct field access.

**Comment by DziNeIT** [comment]
Isn't sun.misc.Unsafe JDK implementation specific?

**Comment by Janmm14** [comment]
Well oracle and openjdk both have it, that should be enough if its used

**Comment by sinnlosername** [comment]
Unsafe might be removed in java 9 ._.

**Comment by DziNeIT** [comment]
@Janmm14 but there is a theoretical possibility others may be used and even if we assume all users have Oracle/OpenJDK, there's no guarantee Unsafe will be retained in future versions - there's already some speculation it might go in 9

**Comment by dmulloy2** [comment]
I'd say the top consideration with Unsafe is if it will be removed in Java 9. A theoretical JDK _may_ exist without Unsafe, but that's definitely an edge case.

Unsafe would appear to be an easy thing to implement, the question is if the plugin will break with Java 9. The best solution appears to be one that uses Unsafe if present and falls back to the old implementation if not. Then if Java 9 removes Unsafe, the plugin will fall back and an alternate solution can be explored.

**Comment by MiniDigger** [comment]
well, jdk9 is feature complete and will be feature extension complete in 2 weeks. if it hasn't been removed yet, it will not be removed with java 9.
http://openjdk.java.net/projects/jdk9/

**Comment by sinnlosername** [comment]
Even if it will be in Java 9, there is a reason why it is called "Unsafe". 
It is never a good idea to use it. it might cause some crazy bugs. I still prefer to use asm to edit field's and to dynamiclly generate classes which directly interact with nms code. You could also do dynamiclly generated wrapper classes which extend nms classes, so developers can extend the wrapper classes, so they extend nms classes :O

**Comment by dmulloy2** [comment]
@sinnlosername ProtocolLib already uses ASM to dynamically generate classes that interact with NMS code, see the structure compiler: https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java

As for unsafe being unsafe, reflection already can cause crazy bugs, this is essentially just a quicker way of reflecting. Even libraries like Netty use unsafe for faster reflection.

**Comment by Techcable** [comment]
Unsafe isnt being removed and Java 9, but you should still use some sort of [wrapper class](https://github.com/Techcable/PineappleCommons/blob/master/src/main/java/net/techcable/pineapple/reflection/PineappleField.java) that gracefully falls back to reflection if Unsafe isnt found.
