### ISSUE TITLE
Unable to intercept a read client packet

### ISSUE THREAD

**Issue by mercadanteus** [dmulloy2/ProtocolLib#1899]
- [ ] This issue is not solved in a development build

**Describe the bug**
error in log 

**To Reproduce**
Run server with Eco plugin or aparenty another buch of plugins that generate the same error

**Version Info**
protocol dump:  https://hastebin.com/kuwewaqusi.kotlin

**Additional context**
Error log:  https://hastebin.com/fasovucera.yaml

**Comment by Hahaa13** [comment]
+1
