### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by BOHPUMAGEJ** [dmulloy2/ProtocolLib#1903]
- [ ] This issue is not solved in a development build

**Describe the bug**
bug occurs from time to time in server while running 

**To Reproduce**
start server
go to log or console

**Expected behavior**
error gets printed in minecraft chat
and a whole lot of things gets printed in console and log

**Screenshots**
this gets pasted into chat the number on the end constantly changes:

Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@7562ff4c.

**Version Info**
Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    3580-Spigot-e53686f-5901d58 (MC: 1.19.2)

**Additional context**
log copy in the file
[mcserver-log.txt](https://github.com/dmulloy2/ProtocolLib/files/9540456/mcserver-log.txt)

**Comment by TheKrafter** [comment]
also, if this helps, here are the plugins im using:
```
AdvancedReplay*, AntiCheatReplay, DiscordSRV, floodgate, Geyser-Spigot, GriefPrevention, LuckPerms, NoChatReports, ProtocolLib, Themis
```
advanced replay is the one that depends on protocollib
