### ISSUE TITLE
Console Error:   "INTERNAL ERROR: Unable to intercept a read client packet."

### ISSUE THREAD

**Issue by CallMeCanadian** [dmulloy2/ProtocolLib#1918]
- [ ] This issue is not solved in a development build

**Describe the bug**
—
I have a console error on startup that says to make a ticket and report it.
[21:51:03 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
(said data is attached under screenshots, sorry for the inconvenience)

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2022-09-23 at 8 59 04 PM](https://user-images.githubusercontent.com/107430344/192075274-72a6e308-db82-4018-a1a3-026d398c01be.png)

[dump-2022-09-23_21.57.10.txt](https://github.com/dmulloy2/ProtocolLib/files/9637701/dump-2022-09-23_21.57.10.txt)

[ProtocolLib Console Error.txt](https://github.com/dmulloy2/ProtocolLib/files/9637706/ProtocolLib.Console.Error.txt)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
My server is Paper, 1.19.2; I just updated to 1.19.2 and switched from Spigot to Paper a couple days ago.
ProtocolLib has been on our server for at least a couple months with no problems.

**Comment by ShadedPL** [comment]
Getting the same on my end constantly.
Logs as below
https://gist.github.com/ShadedPL/93469790b4d59d6c2ec01c518c0f9c94

**Comment by ShadedPL** [comment]
Latest Dev version (#600) seems to fix this

**Comment by CallMeCanadian** [comment]
> 

Where can I download that build?

**Comment by CallMeCanadian** [comment]
@ShadedPL where can I find the download for that build?
