### ISSUE TITLE
The TAB error using 1.9 version.

### ISSUE THREAD

**Issue by arturek1666** [dmulloy2/ProtocolLib#192]
Hi, I notice that when your plugin is installed I can't see my nick or other players nick on a tab. I remove every plugin and try to find out with one was it and looks like it only happens when I install your plugin. Please fix this if I am right  about this error if not just inform me, as I might make a mistake.

**Comment by arturek1666** [comment]
By the way, it doesn't happen all the times.

**Comment by dmulloy2** [comment]
Are you using AuthMe?

**Comment by arturek1666** [comment]
Yes i do

**Comment by dmulloy2** [comment]
This is an issue with AuthMe.
