### ISSUE TITLE
protocollib slows server down a lot

### ISSUE THREAD

**Issue by DimaSergeew** [dmulloy2/ProtocolLib#1922]
- [Protocollib #600] This issue is not solved in a development build

**Describe the bug**
Dear developer! please optimize Protocollib, it loads my server very much, the problem appeared after build #590, because of which our tps drops a lot with high online

**To Reproduce**
1. Go to 'put any build above #590 and run at least 100 players per server, Protocollib starts to load the main thread I tried to increase the number of netty threads but it didn't get any better :('

**Expected behavior**
Return the good protocollib to the way it was before version #590

**Screenshots**
[
![Screenshot_3](https://user-images.githubusercontent.com/75163645/192138334-e136b273-d234-4d62-9034-67eb599b30cc.png)
](url)

**Version Info**
[[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/UANKeqkX)]

**Additional context**
in recent updates, the load of protocollib on the main thread has grown significantly, I ask the developer to take action, or make the plugin work asynchronous

**Comment by Aseeef** [comment]
Can you link the full spark profile? It would help protocol lib contributors evaluate whether PLib or another plugin using PLib is causing the lag.

**Comment by DimaSergeew** [comment]
> Can you link the full spark profile? It would help protocol lib contributors evaluate whether PLib or another plugin using PLib is causing the lag. (Such as premium vanish)

does it help with optimization at all?
![Uploading Screenshot_2.png…]()

**Comment by DimaSergeew** [comment]
> Can you link the full spark profile? It would help protocol lib contributors evaluate whether PLib or another plugin using PLib is causing the lag. (Such as premium vanish)

does it help with optimization at all?
![Screenshot_2](https://user-images.githubusercontent.com/75163645/192757469-400a94aa-86db-4a3c-84ae-a7148cbf9a8f.png)

**Comment by DimaSergeew** [comment]
> Can you link the full spark profile? It would help protocol lib contributors evaluate whether PLib or another plugin using PLib is causing the lag. (Such as premium vanish)

![Screenshot_3](https://user-images.githubusercontent.com/75163645/192761418-548c5a76-4e6f-4d1c-892d-0d1a15902226.png)

**Comment by derklaro** [comment]
> does it help with optimization at all?

If you're running the latest version then it will not help at all. The background compiler was removed a versions ago.
