### ISSUE TITLE
Problem after migrating server to 1.19.2

### ISSUE THREAD

**Issue by KirillLegend** [dmulloy2/ProtocolLib#1926]
- [ ] This issue is not solved in a development build

**Describe the bug**
A lot of incomprehensible text litters the console very much after transferring the server to a new version

**How did this problem come about?**
1. Transferred the server to 1.19.2
2. We went to the hosting. to the console and found the following problem

**Expected behavior**
I hope that there will be no errors after the transition

**Screenshots**
![image](https://user-images.githubusercontent.com/114423230/192317610-05e0eece-2813-4535-9562-571fa54af6a5.png)
![image](https://user-images.githubusercontent.com/114423230/192317669-acb8a0fc-6e85-4672-9109-031c638c0abc.png)
![image](https://user-images.githubusercontent.com/114423230/192317712-fd34878b-c372-4cf8-b024-8c6e87ff25ac.png)

**Version Info**
https://pastebin.com/6UiCdcf0

**Additional context**
No other errors found

**Comment by Aseeef** [comment]
This is on the protocol lib homepage.
![image](https://user-images.githubusercontent.com/74121396/192521502-60a90434-0b79-42b1-b0b1-51e5c2d09555.png)
