### ISSUE TITLE
Error intercepting chat

### ISSUE THREAD

**Issue by Protatsu2670** [dmulloy2/ProtocolLib#1928]
![A561CE50-4F47-47E2-8F61-FA0F0751572A](https://user-images.githubusercontent.com/114555188/192688864-5127a22f-e8f7-4e05-8a68-cd3b71397793.png)
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Go to '...'2. 
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Protatsu2670** [comment]
https://pastebin.com/nJF5gFsS

**Comment by 08star** [comment]
![image](https://user-images.githubusercontent.com/25859816/193475212-1d324950-9279-408e-9083-ff20fc124ed9.png)
