### ISSUE TITLE
IS IT DEAD?

### ISSUE THREAD

**Issue by rafalohaki** [dmulloy2/ProtocolLib#1938]
NO UPDATES?

**Comment by derklaro** [comment]
not dead

**Comment by rafalohaki** [comment]
its been 1month and 19days since last update. thats very long time

**Comment by RashPlayzZz** [comment]
There is some bugs please fix

**Comment by derklaro** [comment]
> There is some bugs please fix

It's open source, feel free to do that

**Comment by rafalohaki** [comment]
Yep, its dead.

**Comment by GTP95** [comment]
> its been 1month and 19days since last update. thats very long time

That's not a long time at all.
