### ISSUE TITLE
ExceptionInInitializerError on 4.8.0

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#1939]
- [x] This issue is not solved in a development build

**Describe the bug**
It doesn't load the plugin 

**To Reproduce**
run ProtocolLib 4.8.0 with gradle paperweight debug environment

**Expected behavior**
loads plugin

**Screenshots**

**Version Info**
(https://paste.gg/p/anonymous/c93c07bc9b4b42dc99d68d9d2507b493)

**Additional context**

**Comment by derklaro** [comment]
Only v5 has support for mojang mapped servers

**Comment by codesmith47** [comment]
So I need to wait until this is updated for 1.19.
