### ISSUE TITLE
ProtocolLib JavaDocs are not displayed

### ISSUE THREAD

**Issue by Nightfighter001** [dmulloy2/ProtocolLib#194]
Hi, I really would like to use ProtocolLib, but when I tried to view the JavaDoc, it was only white page with some Frames. Here a screenshot:
![ScreenShot](https://cloud.githubusercontent.com/assets/12753781/14665417/629e7a18-06d3-11e6-9d51-92dd8b95dcb7.PNG)
I tried it in Microsoft Edge and also the Firefox Developer Edition.
These are the Infos, Firefox displayed:
![Konsole](https://cloud.githubusercontent.com/assets/12753781/14665474/cb38664c-06d3-11e6-8a4a-28ab6957b082.PNG)

Sorry for my bad English and thank you for your help and time :)

EDIT: Sorry, I had Firefox in German, now here is a englisch Version of the console:
![Console](https://cloud.githubusercontent.com/assets/12753781/14665833/43fc71a2-06d6-11e6-9941-701d53a133bf.PNG)
And here also the link to the JavaDocs: [>>Click<<](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/)

**Comment by dmulloy2** [comment]
Dang I thought I fixed this already. Jenkins' new security policy messes with how the javadocs are displayed.

**Comment by dmulloy2** [comment]
Should be fixed.
