### ISSUE TITLE
Unexpected error occured while the server is running

### ISSUE THREAD

**Issue by Pixeluted** [dmulloy2/ProtocolLib#1940]
![image](https://user-images.githubusercontent.com/78791776/195845177-8421f46b-2567-4912-bcf5-8935a08c12eb.png)

**Comment by VishramKidPG123** [comment]
I have the same issue

**Comment by GTP95** [comment]
Got the same issue right after updating Spigot and VotingPlugin, I'm running ProtocolLib v4.8.0 on Java 17.0.4.1, Spigot version is 3599-Spigot-4aa5ead-aaf484f (MC: 1.19.2).

**Comment by GTP95** [comment]
I see this same error is reported in #1936

**Comment by Pixeluted** [comment]
Looks like this is not an issue in the latest built version. https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by VishramKidPG123** [comment]
Yep, with the updated version it works fine. Thanks!
