### ISSUE TITLE
ProtocolLib INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by TomasitoLP** [dmulloy2/ProtocolLib#1941]
ProtocolLib Dump
Timestamp: 10/15/22 10:59:37

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Purpur-1819 (MC: 1.19.2)
Java Version: 17.0.4

ProtocolLib: com.comphenix.protocol.ProtocolLib@70227c8c[
  statistics=com.comphenix.protocol.metrics.Statistics@48842343
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5f865782
  packetTask=13
  tickCounter=3304
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2e2dfefb
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@331392cc
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@50364e3e
  commandProtocol=com.comphenix.protocol.CommandProtocol@3941f140
  commandPacket=com.comphenix.protocol.CommandPacket@54968bad
  commandFilter=com.comphenix.protocol.CommandFilter@7bbce601
  packetLogging=com.comphenix.protocol.PacketLogging@199910f6
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@2f642974
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1819,minecraftVersion=1.19.2}
  file=plugins/protocollib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@4fcf04d6
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/protocollib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@210cbed
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@40a3cb75[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2e2dfefb
  packetListeners=[PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@6f3da410, PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@c3eb3cd
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@40bab6fd
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1e1c25fc
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5f87dae2
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/protocollib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@26deaa04
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1819,minecraftVersion=1.19.2}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4c8a1d2d
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=2
  phasePlayingCount=5
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@66b0b901
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@178ec47d
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.2)
  debug=false
]

Listeners:
fr.xephi.authme.listener.protocollib.InventoryPacketAdapter@56fdb33e[
  logger=fr.xephi.authme.ConsoleLogger@c316d52
  playerCache=fr.xephi.authme.data.auth.PlayerCache@3bef31b6
  dataSource=fr.xephi.authme.datasource.CacheDataSource@1366f864
  plugin=AuthMe v5.6.0-beta2-b2453
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]]
]
litebans.fk@2ff3120b[
  g=litebans.dl@9300369
  c=litebans.dx@14cc3111
  d=litebans.dj@4c5c10c6
  f=litebans.d1@3bddd332
  b=LiteBans v2.10.4
  plugin=LiteBans v2.10.4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
litebans.iA@551f1ee2[
  e=litebans.dj@4c5c10c6
  c=LiteBans v2.10.4
  plugin=LiteBans v2.10.4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
com.comphenix.protocol.async.NullPacketListener@6f3da410[
  sendingWhitelist=ListeningWhitelist[priority=LOW, packets=[], gamephase=PLAYING, options=[ASYNC]]
  receivingWhitelist=ListeningWhitelist[priority=LOW, packets=[ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0]], gamephase=PLAYING, options=[ASYNC]]
  plugin=FastLogin v1.12-SNAPSHOT-2989d9a
]
com.Zrips.CMI.AllListeners.ProtocolEvent$1@15271ae8[
  plugin=CMI v9.2.4.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
AuthMe by [Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008]
FastLogin by [games647, https://github.com/games647/FastLogin/graphs/contributors]
LiteBans by [Ruan]
CMI by [Zrips]

**Comment by TomasitoLP** [comment]
I need help with this, because this spamming in chat to players.

**Comment by 7dev7urandom** [comment]
I have the same issue

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
