### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by xMasa-1022** [dmulloy2/ProtocolLib#1942]
- [ ] This issue is not solved in a development build

**Describe the bug**
Traceback report it.
> https://pastebin.com/zezei6Ri

**To Reproduce**
1. Install Spigot 1.19.2 server.
2. Click on 'server.bat'( https://pastebin.com/mS9dt2xr )
3. See error

**Version Info**
`/protocol dump` result -> https://pastebin.com/5mDymRbR

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
