### ISSUE TITLE
Unable to find a field null

### ISSUE THREAD

**Issue by Currypan1229** [dmulloy2/ProtocolLib#1944]
- [ ] This issue is not solved in a development build

**Describe the bug**
https://pastebin.com/z2W8FG3n

**To Reproduce**
1. Install Spigot 1.19.2 server.
2. Run the server
3. See error

**Plugins**
Plugins (19): FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GeyserSkinManager, InfernalMobs, LevelledMobs, LuckPerms, LunaChat*, Magic, MoreMobHeads, OpenInv, PlugMan, ProtocolLib, SpawnerSilk, Vanillabosses, ViaBackwards, ViaRewind, ViaVersion

**Comment by lChrisjm** [comment]
got the same issue

**Comment by Danieljunek17** [comment]
same issue

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
