### ISSUE TITLE
1.8 PVP PROBLEM > PROTOCOLLİB 5.0.0

### ISSUE THREAD

**Issue by Draigo1984** [dmulloy2/ProtocolLib#1945]
Hello  I know protocollib its for 1.19 verison but I have server I need Protocol V5.0.0 version for plugins

 I have 1.18.2 server and I want to use protocollib 5.0.0 but when I useed this version my pvp damage its broken like 1.8 pvp system

**Comment by Wackgamer** [comment]
I don't know what is happenning with the plugin that is like broken and crashes older versions than 1.19
