### ISSUE TITLE
Can't see players when I have ProtocolLib Installed

### ISSUE THREAD

**Issue by LordToncimir** [dmulloy2/ProtocolLib#195]
Ok Heres the thing.
When i use ProtocolLib i can't see players that joined server before me but without ProtocolLib i can see them its same with other players not just me also can't see them in tablist but can in /list plz help!
List of My Plugins Without ProtocolLib:
![plugins picture](https://cloud.githubusercontent.com/assets/18601915/14721353/4c71d7e2-0806-11e6-9607-37971f78db41.png)

**Comment by games647** [comment]
AuthMe issue

**Comment by LordToncimir** [comment]
But everything works fine without protocollib...

**Comment by games647** [comment]
HideTablist is a feature from AuthMe. It's enabled by default, but it requires ProtocolLib. If it's missing AuthMe will disable the feature silently.

**Comment by LordToncimir** [comment]
Ok ill give it a try

**Comment by LordToncimir** [comment]
Setting HideTablist to false did the job thanks a lot mate this was bothering me for few days! :D

**Comment by games647** [comment]
Could you close this issue then?

**Comment by LordToncimir** [comment]
sure
