### ISSUE TITLE
Unhandled Exception 64

### ISSUE THREAD

**Issue by KyleNehman** [dmulloy2/ProtocolLib#196]
Very similar to the previous Unhanded Exception.

Error: http://pastebin.com/bhMA9gjM

Possibly related to this issue: The method referenced [here ](https://gist.github.com/aadnk/5431819)does nothing.

**Comment by dmulloy2** [comment]
````No field with type net.minecraft.server.v1_9_R1.DataWatcher exists in class PacketPlayOutEntityTeleport.````

There isn't a data watcher in the entity teleport packet. Check the source generated by build tools.
