### ISSUE TITLE
Add wrappers for metadata types: CatVariant, FrogVariant, PaintingVariant

### ISSUE THREAD

**Issue by MelonHell** [dmulloy2/ProtocolLib#1963]
- [x] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to change the type of cat, frog, painting without using NMS

**Describe the solution you'd like**
Add CatVariantWrapper, FrogVariantWrapper, PaintingVariantWrapper

**Describe alternatives you've considered**
Using NMS like here
```java
WrappedDataWatcher.Serializer serializer = WrappedDataWatcher.Registry.get(CatVariant.class, false);
WrappedDataWatcher.WrappedDataWatcherObject wrappedDataWatcherObject = new WrappedDataWatcher.WrappedDataWatcherObject(19, serializer);
WrappedWatchableObject wrappedWatchableObject = new WrappedWatchableObject(wrappedDataWatcherObject, CatVariant.WHITE);
```

**Additional context**
wiki.vg info:
- https://wiki.vg/Entity_metadata#Entity_Metadata_Format
number 19, 20, 22
- cat metadata: https://wiki.vg/Entity_metadata#Cat
- frog metadata: https://wiki.vg/Entity_metadata#Frog
- painting metadata: https://wiki.vg/Entity_metadata#Painting

**Comment by derklaro** [comment]
There are no enum wrappers for that as these values are registered in registries. To get them you can use something like:
```java
    Class<?> catVariantClass = MinecraftReflection.getMinecraftClass("world.entity.animal.CatVariant");
    WrappedRegistry registry = WrappedRegistry.getRegistry(catVariantClass);
    Object catVariantWhite = registry.get(new MinecraftKey("white"));
```

Note that there is no need to get a value from a registry twice as (in that case) they are frozen since the startup.

**Comment by MelonHell** [comment]
> There are no enum wrappers for that as these values are registered in registries. To get them you can use something like:
> 
> ```java
>     Class<?> catVariantClass = MinecraftReflection.getMinecraftClass("world.entity.animal.CatVariant");
>     WrappedRegistry registry = WrappedRegistry.getRegistry(catVariantClass);
>     Object catVariantWhite = registry.get(new MinecraftKey("white"));
> ```
> 
> Note that there is no need to get a value from a registry twice as (in that case) they are frozen since the startup.

Thanks for the advice, I'll take it.

would still like to see it in some form in the ProtocolLib
