### ISSUE TITLE
Java Error Illegal Arguments?

### ISSUE THREAD

**Issue by r3bbl3** [dmulloy2/ProtocolLib#197]
I have a really big Problem.
I want to use the Plugin BlockHunt_Update of my Server but
this Plugin want ProtocolLib and libsDisguises. 
The Disguises works well but your Plugin gives me:

Error Unable to inject incoming channel [id: 0xcc9d9b7d, <--- This code Changes
/77.47.53.105..... <-- This IP changes! /84.200.206.195:28920 <--- My Server
(java.lang.IllegalArgumentException: Duplicate handler name: 
com.comphenix.protocol.injector.netty.ChannelInjector@142566 <--- Changes also!

I can not use this Plugin! I changed the Version and deletet it because this spam my Chat
as well!
Please help me. The Server use Spigot 1.8.6 and your Plugin don't work with it!
Thank you for helping.
Send me the new plugin that maybe will work. freakspider@hotmail.de
Thanks
------------
r3bbl3

**Comment by dmulloy2** [comment]
Run /protocol dump and paste the output using pastebin.

**Comment by dmulloy2** [comment]
Any more information on this?

**Comment by r3bbl3** [comment]
This Messenges Recive me After joining The Server and reloading. It say also that The listener not really work i still run Spigot 1.8.6

**Comment by dmulloy2** [comment]
Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by r3bbl3** [comment]
http://pastebin.com/NYQwxrFq
here you go

**Comment by dmulloy2** [comment]
The paste appears to be private, can you make it public?

**Comment by r3bbl3** [comment]
http://pastebin.com/NYQwxrFq
made it. Please help me the messenges spam as well...

**Comment by dmulloy2** [comment]
Oh I missed the part about reloading. Reloading is highly discouraged because it causes errors like this.
