### ISSUE TITLE
Incompatible with FlamePaper

### ISSUE THREAD

**Issue by linsaftw** [dmulloy2/ProtocolLib#1973]
I am the developer of FlamePaper, a 1.8.8 Paper fork and it was updated to latest Netty version and since then ProtocolLib is not launching.

This is the stacktrace. https://pastebin.com/Ng6g7PqA

Is there some way to make it work without downgrading netty?

**Comment by derklaro** [comment]
Try ProtocolLib v5 from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by linsaftw** [comment]
> Try ProtocolLib v5 from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Working!
