### ISSUE TITLE
ProtocolLib's Repository Returns a 500 Error

### ISSUE THREAD

**Issue by Navoei** [dmulloy2/ProtocolLib#1983]
The title says it all, when compiling a plugin while ProtocolLib is a depdendency, the IDE returns a 500 Internal Server Error.

Edit: This only happens when using 5.0.0-SNAPSHOT as the server version.

So, my question is, how can I compile my plugin using the latest version of ProtocoLib for 1.19?

**Comment by Galapen** [comment]
This is still an issue. All 5.0.0-SNAPSHOT [metadata](https://repo.dmulloy2.net/repository/public/com/comphenix/protocol/ProtocolLib/5.0.0-SNAPSHOT/maven-metadata.xml) files return server error 500.
