### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by LeitoCc187** [dmulloy2/ProtocolLib#2006]
ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
29.11 02:47:10 [Server] INFO If this problem hasn't already been reported, please open a ticket
29.11 02:47:10 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
29.11 02:47:10 [Server] INFO Stack Trace:
29.11 02:47:10 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
29.11 02:47:10 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
29.11 02:47:10 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
29.11 02:47:10 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
29.11 02:47:10 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
29.11 02:47:10 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
29.11 02:47:10 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
29.11 02:47:10 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
29.11 02:47:10 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
29.11 02:47:10 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
29.11 02:47:10 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
29.11 02:47:10 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
29.11 02:47:10 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
29.11 02:47:10 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
29.11 02:47:10 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
29.11 02:47:10 [Server] INFO Dump:
29.11 02:47:10 [Server] INFO Parameters: 
29.11 02:47:10 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@43214c10[
29.11 02:47:10 [Server] INFO memoryAddress=140125523102912
29.11 02:47:10 [Server] INFO recyclerHandle=io.netty.util.Recycler$DefaultHandle@14747279
29.11 02:47:10 [Server] INFO chunk=Chunk(4a4b3b02: 29%, 1212416/4194304)
29.11 02:47:10 [Server] INFO handle=25332812328468480
29.11 02:47:10 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
29.11 02:47:10 [Server] INFO offset=368640
29.11 02:47:10 [Server] INFO length=34
29.11 02:47:10 [Server] INFO maxLength=48
29.11 02:47:10 [Server] INFO cache=io.netty.buffer.PoolThreadCache@aabee10
29.11 02:47:10 [Server] INFO tmpNioBuf=<null>
29.11 02:47:10 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
29.11 02:47:10 [Server] INFO refCnt=2
29.11 02:47:10 [Server] INFO readerIndex=34
29.11 02:47:10 [Server] INFO writerIndex=34
29.11 02:47:10 [Server] INFO markedReaderIndex=0
29.11 02:47:10 [Server] INFO markedWriterIndex=0
29.11 02:47:10 [Server] INFO maxCapacity=2147483647
29.11 02:47:10 [Server] INFO ]
29.11 02:47:10 [Server] INFO manager:
29.11 02:47:10 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@3c1b342d[
29.11 02:47:10 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@79c1342c
29.11 02:47:10 [Server] INFO packetListeners=[PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
29.11 02:47:10 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@365d40c0
29.11 02:47:10 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4be75a52
29.11 02:47:10 [Server] INFO inputBufferedPackets=[]
29.11 02:47:10 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2e38a55f
29.11 02:47:10 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5ea884e0
29.11 02:47:10 [Server] INFO hasClosed=false
29.11 02:47:10 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
29.11 02:47:10 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@2af94b5
29.11 02:47:10 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-300,minecraftVersion=1.19.2}
29.11 02:47:10 [Server] INFO library=ProtocolLib v4.8.0
29.11 02:47:10 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@18123a17
29.11 02:47:10 [Server] INFO knowsServerPackets=true
29.11 02:47:10 [Server] INFO knowsClientPackets=true
29.11 02:47:10 [Server] INFO phaseLoginCount=0
29.11 02:47:10 [Server] INFO phasePlayingCount=3
29.11 02:47:10 [Server] INFO packetCreation=false
29.11 02:47:10 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5da0cafd
29.11 02:47:10 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@668fff92
29.11 02:47:10 [Server] INFO hasRecycleDistance=true
29.11 02:47:10 [Server] INFO minecraftVersion=(MC: 1.19.2)
29.11 02:47:10 [Server] INFO debug=false
29.11 02:47:10 [Server] INFO ]
29.11 02:47:10 [Server] INFO Sender:
29.11 02:47:10 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@5d273b06[
29.11 02:47:10 [Server] INFO decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
29.11 02:47:10 [Server] INFO encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
29.11 02:47:10 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@51f56131
29.11 02:47:10 [Server] INFO player=CraftPlayer{name=LeitoCc187}
29.11 02:47:10 [Server] INFO updated=<null>
29.11 02:47:10 [Server] INFO playerName=LeitoCc187
29.11 02:47:10 [Server] INFO playerConnection=<null>
29.11 02:47:10 [Server] INFO networkManager=net.minecraft.network.NetworkManager@ffb6ee0
29.11 02:47:10 [Server] INFO originalChannel=[id: 0x6ffc5afc, L:/145.239.205.20:25682 - R:/51.195.135.160:48005]
29.11 02:47:10 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@ffb6ee0, previous=[id: 0x6ffc5afc, L:/145.239.205.20:25682 - R:/51.195.135.160:48005], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7123b7de, previousLoaded=true, currentSet=true, forceAccess=true]
29.11 02:47:10 [Server] INFO packetMarker={}
29.11 02:47:10 [Server] INFO currentEvent=<null>
29.11 02:47:10 [Server] INFO finalEvent=<null>
29.11 02:47:10 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@15384df7
29.11 02:47:10 [Server] INFO vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@4160bdde
29.11 02:47:10 [Server] INFO vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@185caacb
29.11 02:47:10 [Server] INFO finishQueue=[]
29.11 02:47:10 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5da0cafd
29.11 02:47:10 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@23addfce
29.11 02:47:10 [Server] INFO injected=true
29.11 02:47:10 [Server] INFO closed=false
29.11 02:47:10 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
29.11 02:47:10 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4bddc52e
29.11 02:47:10 [Server] INFO singleDecode=false
29.11 02:47:10 [Server] INFO first=true
29.11 02:47:10 [Server] INFO firedChannelRead=false
29.11 02:47:10 [Server] INFO selfFiredChannelRead=true
29.11 02:47:10 [Server] INFO decodeState=1
29.11 02:47:10 [Server] INFO discardAfterReads=16
29.11 02:47:10 [Server] INFO numReads=0
29.11 02:47:10 [Server] INFO added=true
29.11 02:47:10 [Server] INFO ]
29.11 02:47:10 [Server] INFO Version:
29.11 02:47:10 [Server] INFO ProtocolLib v4.8.0
29.11 02:47:10 [Server] INFO Java Version:
29.11 02:47:10 [Server] INFO 17.0.5
29.11 02:47:10 [Server] INFO Server:
29.11 02:47:10 [Server] INFO git-Paper-300 (MC: 1.19.2)

**Comment by sandornot** [comment]
I keep getting the same thing

**Comment by AuroaRZ-Online** [comment]
same

**Comment by TheRediStone** [comment]
same

**Comment by liponex** [comment]
Also has this problem

**Comment by liponex** [comment]
As I can see, the old version of the plugin is displayed in the log, personally I used build number 605 which could work with 1.19.x

**Comment by Lopastudio** [comment]
same thing please anyone help

**Comment by liponex** [comment]
I fixed problem for me by using previous build (604)

**Comment by Creveoolus** [comment]
> 604

sorry, but how could i find it?

**Comment by liponex** [comment]
[All dev builds here](https://ci.dmulloy2.net/job/ProtocolLib/) 
[Build 604](https://ci.dmulloy2.net/job/ProtocolLib/604/)

This information can be found in the README.MD :)

**Comment by befapo** [comment]
> 

Had the same issue, using the previous build (604) fixed it. Thank you.
