### ISSUE TITLE
ProtocolLib TPS lag caused by getSimpleName()

### ISSUE THREAD

**Issue by mibby** [dmulloy2/ProtocolLib#202]
PaperSpigot 716
ProtocolLib dev 273

@dmulloy2 See https://github.com/PaperMC/Paper/issues/249#issuecomment-216062360

**Comment by dmulloy2** [comment]
That code is only called when the packet types are initializing. I can't imagine that would have a (lasting) TPS hit.

**Comment by mibby** [comment]
What is your definition of lasting? I've had TPS drops caused by tracker lag persisting upwards of 20+ minutes, which seems quite unacceptable. It comes and goes at random. According to aikar and the warmroast profile of when I was last affected, protocolib was the biggest impact.

**Comment by Shevchik** [comment]
That means that is happens only once.

**Comment by dmulloy2** [comment]
Unless the method is called more than once (which it shouldn't be), the impact would only be when the server starts, but shouldn't last.

**Comment by mibby** [comment]
Is there any way to debug when the method is called? As this happened hours after the server has started.

**Comment by dmulloy2** [comment]
It looks as though it is also called when there are changes to the packet map. Currently it strictly checks the ````modCount```` of the map, although this seems to be a less-than-ideal check.

**Comment by mibby** [comment]
Alright, thanks for looking into it. :) I'll update and let you know how profiled performance is with protocollib.

**Comment by mibby** [comment]
I assume you will be keeping the debug output at start-up regardless of what the protocollib debug state is?

```
[12:46:35] [Server thread/INFO]: [Debug] NettyProtocolRegistry#initialize()
[12:46:35] [Server thread/INFO]: [Debug] NettyProtocolRegistry#initialize()
[12:46:35] [Server thread/INFO]: [Debug] NettyProtocolRegistry#initialize()
```
