### ISSUE TITLE
Entity Metada Packet error

### ISSUE THREAD

**Issue by thelipe7** [dmulloy2/ProtocolLib#2026]
- This issue is not resolved in a development build

**Describe the bug**
When sending a metadata packet the player is kicked and I get console error.

**To Reproduce**
Enviar 1. send the package.

**Expected Behavior**
The package being sent and things being changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/101154133/207126488-cee4c2e6-81cd-42a4-9930-f7e3d5cea1e5.png)

**Versions**
ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b606
Bukkit Version: 1.19.3-R0.1-SNAPSHOT
Server Version: git-Paper-"a46fef3" (MC: 1.19.3)
Java Version: 17.0.5

**Additional Context**
My code:
![image](https://user-images.githubusercontent.com/101154133/207126582-d1f5ee19-fb33-42d4-92d8-5a77d8693469.png)

**Comment by derklaro** [comment]
See https://github.com/dmulloy2/ProtocolLib/pull/1946#issuecomment-1345250144

**Comment by thelipe7** [comment]
This WrappedDataValue class doesn't exist for me, and also looking at the source here on github it doesn't exist, also it doesn't exist in the latest version available on dev

**Comment by SananR** [comment]
Experiencing the same issue, can't seem to find the new WrappedDataValue class

**Comment by lokka30** [comment]
Linked to #2032
