### ISSUE TITLE
Issues with WrapperRegistry on 1.19.3

### ISSUE THREAD

**Issue by Jpx3** [dmulloy2/ProtocolLib#2027]
- [ ] This issue is not solved in a development build

**Describe the bug**
Exception thrown when using WrappedRegistry
"com.comphenix.protocol.wrappers.WrappedRegistry.get(String)" because "registry" is null
[19:43:58 WARN]: at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedAttribute$Builder.build(WrappedAttribute.java:442)

**To Reproduce**
    PacketContainer packet = ProtocolLibrary.getProtocolManager().createPacket(PacketType.Play.Server.UPDATE_ATTRIBUTES);
    WrappedAttribute attribute = WrappedAttribute.newBuilder().attributeKey(name).baseValue(baseValue).packet(packet).build();

**Version Info**
ProtocolLib Build #606

**Additional context**
Minecraft 1.19.3

**Comment by Janmm14** [comment]
@derklaro what about now?
