### ISSUE TITLE
1.9.4

### ISSUE THREAD

**Issue by AshourAziz** [dmulloy2/ProtocolLib#204]
Plugin shutsdown server when booting on a 1.9.4 server no errors 

http://pastebin.com/mGwE6TcS

**Comment by AshourAziz** [comment]
SMH, had too many tabs open, please close ;-;

**Comment by dmulloy2** [comment]
Can anyone verify if ProtocolLib works with 1.9.4?

**Comment by Foulwerp** [comment]
4.0.0-SNAPSHOT for Spigot 1.9.x seems to work with 1.9.4

I only tested my updated version of Orebfuscator for 1.9.4 with it, but so far it seems to work.

**Comment by mibby** [comment]
@dmulloy2 Could this be a protocollib problem on 1.9.4?

https://github.com/libraryaddict/LibsDisguises/issues/131#issuecomment-218331523

**Comment by dmulloy2** [comment]
@mibby That looks to be a packet constructor error, so it'd be on their end.
