### ISSUE TITLE
Where is latest Maven release?

### ISSUE THREAD

**Issue by Jeppa** [dmulloy2/ProtocolLib#2047]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

The Maven repo is still on old build.
Under https://repo.dmulloy2.net/service/rest/repository/browse/public/com/comphenix/protocol/ProtocolLib/5.0.0-SNAPSHOT/
it's still build from july...

How can i use the latest build (607) without adding it by hand to my pom.xml?

Is there another place for it than repo.dmulloy2.net ???

**Comment by dmulloy2** [comment]
oops, sorry about that. running low on space in the repo so i stopped deploying every version. forgot to manually deploy this one. should be available now
