### ISSUE TITLE
Console error for supervanish/protocollib

### ISSUE THREAD

**Issue by sandornot** [dmulloy2/ProtocolLib#2065]
[protocollib message.txt](https://github.com/dmulloy2/ProtocolLib/files/10305084/protocollib.message.txt)

my server has been crashing a ton today but only after i added the most recent dev build of supervanish. the error messages are coming from supervanish but say "This error likely happened inside of ProtocolLib code which is out of SuperVanish's control". i've talked to my host about the crashes and they recommended reporting this issue so here i am

**Comment by Brokkonaut** [comment]
It is a bug of supervanish, he has to use "event.getPacket().getPlayerInfoDataLists().read(1)" there (1 instead of 0) in 1.19.3, similar for the write
