### ISSUE TITLE
ViaVersion w/ ProtocolLib

### ISSUE THREAD

**Issue by OverscorePlayZ** [dmulloy2/ProtocolLib#207]
Hello there!

I would like to begin with stating that this is a very great plugin, I have had no issues up to this point and am pretty sure this is a issue you have heard of and can give me a response for. I am a user of your plugin, and ViaVersion as I want my users to be able to join on 1.8 and 1.9 to my hub as a couple of my gamemodes are on 1 version while my players would prefer the other gamemode on the other. Therefore, my hub must be both. My problem is, is that our custom coded plugins use your API (Excuse me if I use any of these terms incorrectly, I am not the dev, I am the owner), therefore, we have no other solution to this problem. Again, I hope to not anger you as I am sure this is something you see quite often, though, with hours of research and testing, we have yet to find a solution. Thank you for your time in reading this message and hope to speak with you shortly!

Kind regards,
OverscorePlayZ
(Owner of TitansCraft Network)

**Comment by OverscorePlayZ** [comment]
Here's the error (Client Side):

DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): SlicedAbstractByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4167, widx: 4183, cap: 8192)) @ io.netty.handler.codec.MessageToMessageDecoder:99

**Comment by dmulloy2** [comment]
Is there a server-side error you can provide?

**Comment by OverscorePlayZ** [comment]
Certainly,

OverscorePlayZ lost connection: Internal Exception: java.io.ioException: An established connection was aborted by the software in your host machine

**Comment by dmulloy2** [comment]
It was my understanding that the incompatibility between ProtocolLib and ViaVersion was resolved. Are you using late bind by any chance?

**Comment by OverscorePlayZ** [comment]
Our server is not currently using late-bind. Unless you enable/disable ProtocolLib (via Plugman) you may not join on 1.9.... 1.8 works just fine but we need both.

**Comment by dmulloy2** [comment]
Are you using BKCommonLib? It looks like it causes issues as well: https://github.com/MylesIsCool/ViaVersion/issues/394

**Comment by dmulloy2** [comment]
Any more info on this?
