### ISSUE TITLE
Plib on 1.19

### ISSUE THREAD

**Issue by sovtec** [dmulloy2/ProtocolLib#2076]
Using paper 1.19-81
Plib version 5.0.0-SNAPSHOT-b607

Getting this on restart sometimes, _https://pastebin.com/Fs1hTg9F_ 

I use plib with reconnect by Tau - _https://www.spigotmc.org/resources/automatic-server-reconnect-bungee-reconnect.84395/_

Do you know what the issue could be from the stack trace linked above? Not really sure what's going on here

**Comment by sovtec** [comment]
> I think build 607 and newer are not compatible with 1.19, 1.19.1 and 1.19.2 anymore... :(

I see. Do you by any chance remember what latest supported plib version for 1.19 is?

**Comment by Jeppa** [comment]
Build 606 was ok for 1.19.2. 
but i don't know if it was ok for 1.19, too.
The issues started with 1.19.3, so i would say: go and try :)

**Comment by dmulloy2** [comment]
@sovtec can you create that paste again? would like to bring back backwards compatibility for 1.19 in the latest builds

**Comment by sovtec** [comment]
> @sovtec can you create that paste again? would like to bring back backwards compatibility for 1.19 in the latest builds

Hello my friend, ofc.

Great news that you are adding backward compatibility to 1.19 💯 

After some digging, I located the error again. _https://pastebin.com/HBBafNeW_

**Comment by sovtec** [comment]
Anything on this yet?

**Comment by sovtec** [comment]
> @sovtec can you create that paste again? would like to bring back backwards compatibility for 1.19 in the latest builds

Did you by any chance look into this for the recent update?
