### ISSUE TITLE
NPE in handleLogin

### ISSUE THREAD

**Issue by djyee** [dmulloy2/ProtocolLib#208]
- lastest spigot build API version 1.9.4-R0.1-SNAPSHOT
protocollib last build 
Hello protocollib give error i have no idea why give error can you helpme ? 
sorry for bad english

console error: http://pastebin.com/Mjt31rBA

**Comment by dmulloy2** [comment]
Can you use the latest development build and provide the debug information?

**Comment by djyee** [comment]
sure i set debug true here errors http://pastebin.com/YFV8DaFh    if this is not debug can you tell me how can i get debug info ? thanks for your help.

**Comment by dmulloy2** [comment]
Sorry, I was catching the wrong exception. Run the latest build and it should provide a bit more info, like the value of PACKET_LOGIN_CLIENT

**Comment by djyee** [comment]
i cant find protocolLib 4.0.2-SNAPSHOT  can you upload to jenkins :D

**Comment by dmulloy2** [comment]
Looks as though the server crashed last night, should be all good now.

**Comment by djyee** [comment]
okey i run last version here errors http://pastebin.com/jH44CFuZ

**Comment by dmulloy2** [comment]
It appears that ProtocolLib can't find the login start packet, but it definitely exists. Are you using a modified version of Spigot? Do any other errors show up from ProtocolLib?

**Comment by djyee** [comment]
no classic spigot version i download here https://tcpr.ca/downloads/spigot

**Comment by dmulloy2** [comment]
Sites like those are technically illegal due to copyright issues. Download and use the official BuildTools from Spigot to get an official build of Spigot. This is explained in detail here: https://www.spigotmc.org/wiki/buildtools/

**Comment by djyee** [comment]
i am runung mac os x maybe thats plugin give error ?

**Comment by dmulloy2** [comment]
Shouldn't be an issue with OSX

**Comment by djyee** [comment]
i downloaded spigot using buildtools its fixed no longer give error  and i think jenkins crashed again :( 
if some one get error some think like this ask him were dowloaded spigot from XD

**Comment by dmulloy2** [comment]
Yeah stuff like that tends to happen with unofficial builds.
