### ISSUE TITLE
[1.18.2] ProtocolLib is not loaded when the server starts

### ISSUE THREAD

**Issue by Minori101** [dmulloy2/ProtocolLib#2082]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://pastebin.com/tQmsJsGq

Description and relevant errors:
ProtocolLib is not loaded when the server starts. Using PaperSpigot 1.18.2

**Comment by dmulloy2** [comment]
My guess is it has to do with Java 19. Any reason you're using it instead of Java 17?
