### ISSUE TITLE
InventoryClickType enum wrapper

### ISSUE THREAD

**Issue by SkyBeastMC** [dmulloy2/ProtocolLib#209]
Hey!
I havn't found the InventoryClickType enum wrapper (net.minecraft.server.v1_9_R1.InventoryClickType // PacketPlayInWindowClick). I think this enum was added in 1.9 because I can't found this enum in McDevs repo.

PacketPlayInWindowClick fields:
```
  private int a; //Window ID
  private int slot;
  private int button;
  private short d; //Action ID (For Transaction confirmation)
  private ItemStack item;
  private InventoryClickType shift; //Action (PICKUP (left click), PICKUP_ALL (double click) for example)
```
So I found an ugly way using this:
```
Class<?> clazz = Class.forName(MinecraftReflection.getMinecraftPackage()+".InventoryClickType");
Debug.debug(clazz.getName());
packet.getSpecificModifier(clazz).read(0);
```
Can you add this enum wrapper? ;)
I love this plugin ;)

EDIT: I'm currently using this:
https://github.com/SkyBeastMC/GUILib/blob/master/GUILib/src/fr/skybeastmc/guilib/listeners/ProtocolPacketListener.java
If you want to.

**Comment by dmulloy2** [comment]
It's only ever used once, but you can use your own enum like this:

https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayClientWindowClick.java#L137
