### ISSUE TITLE
Спам в консоль

### ISSUE THREAD

**Issue by Nektoo** [dmulloy2/ProtocolLib#2090]
Дорогие разработчики. Недавно столкнулся с проблемой в вашем последнем билде плагина ProtocolLib(https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/com.comphenix.protocol$ProtocolLib/). Этот плагин при заходе игрока на сервер он спамит огромным текстом в консоль. В добавок к этому, возможно из за этой ошибки он и ломает игру другим игрокам. Например: при заходе у НЕКОТОРЫХ игроков может повысится пинг или просто сервер на вид остановится, в итоге их просто кикнет. Данная проблема не у всех, а только у некоторых игроков. Причем, в лобби всё нормально, у всех всё заходит и играется хорошо, но перейдя на сервер выживания, идет спам в консоль. Версия плагина там и там одинаковая.
Вот текст спама:
net.minecraft.network.protocol.game.PacketPlayOutCommands$b@32371fe9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@276265f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@559d0640, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5f872d5e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5545b910, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@66322939, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5b208cb9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3daba75e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@455e04c2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@32d286b1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6d488116, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@d395ab6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@387437c7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1e35d976, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@37dcbb97, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@70f7bb30, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@69a460e6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@596afacd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@bb8f274, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@46dbf608, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@c321d65, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@28022bc, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4ee74bca, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@57958fa8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4b50790a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4846371e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3c0b9cc7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4798ac21, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@f4805f1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@76cf2dc1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@16c27a7b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@14392526, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5b91cddd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@54bf524b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@51abeb05, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@c66e403, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@59cc2f77, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@774f130f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79b22d20, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@424f98e9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7a40a040, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7598136c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1dabebd2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@239da05e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5ca046cd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@69163d46, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2b21aecd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@657064a7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3bb8c0ea, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@631c26d6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@456dabbe, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@235ebae8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5e9c81f9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5cb4266a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@742c5619, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@22f32b8e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@185af560, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@65a00777, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@732a0944, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@483ef3f4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@700ee66, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@62feca4e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@41bd8f7c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7e2375ec, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7e50d790, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6a68ceae, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@47037af0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@22eaebe9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5afe5473, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@764fec3c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2ac7ccff, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5f07dfed, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@777245b2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7e55696c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6ae1f26d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@b78b06b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6ec23b63, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3b0931de, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5e1ede48, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@102bc608, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6fcdee4d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1d38a5ab, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@357cd4da, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7ba95ffb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7b166945, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@23db8e71, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@705244d4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@41358ba2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@9a18e80, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@767621c3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1460bf3d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79654e88, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7cb51aaa, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3b0a54c6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2a828dcd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79c0871b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2d74b2c3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@44317fcf, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7a636e61, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@766c669, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@f0c9eec, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@408c57c5, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@21fd29d3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1019f60b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7b89e11a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5999b3d1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@11e2aa80, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4e14af19, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7a2116f0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6e32355e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6a8034b2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@107229c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@736322da, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@c84612d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@674af1ab, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5f612c1c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@35fea0d8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1adc3243, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2a2b5f1a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7c7c978f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3cc400b8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@47716349, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@37d22732, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2f8a1ea8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@33571a21, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7f705c29, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@59bd0f42, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@26bd2583, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2db0b567, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@50dc25ec, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@61aaf7aa, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2ef44721, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6c7d415, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@37856264, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@124c499, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@d6546d3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@353a4c16, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@29308e97, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@e178724, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@29e30beb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4edeb83d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6337d347, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@51ab56a2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@60a6a32f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5b82e056, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6f2ad8a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@d67e5b0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@588d80e8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@14415bff, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7cc3a00, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@35b4152c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@10a59b2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1f8a64cf, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79f04104, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6c782663, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3fec3597, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@730c92b9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@80f15bd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@256961e1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7bf7a856, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6cf974cb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1c2b2614, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@72232a19, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@34d08913, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1328fc6e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@56767399, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3d6ef8ac, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@d466603, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@59592049, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3cd66a40, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@76b74eee, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@48ff4845, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@58b4727b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@573f9747, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1b336370, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@293cad33, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@52e025c5, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79ce1571, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79e6d1db, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@357fbee1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@66626b86, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6f0e9fa6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2029f395, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@68e9c9c7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1da2a107, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@64afeba, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@699010bd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4f114bb9, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@47b371c5, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@165de8a7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7fa10729, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3a28d7e7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@66c9b43e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1f286090, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6847b413, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@14acd113, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3f6feffc, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@631f2461, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@362de33d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@44fb98a2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4ab8fce, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1e0d9f16, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@47e0b3e1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5f460d37, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7cb3cee, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@75ccf62e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@37f13ccd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5831a0b1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6c3db15, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@14ac2065, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2a056169, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7f6468b0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@67671f3a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@12bda4bb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@133291ac, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4fcf5a92, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@108e129e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6f69f448, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6851b7f8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5dff7baa, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3d858869, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1d6ef025, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@78e56a07, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5e616c9a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4fb671ff, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@25335ff4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@76d5ac07, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@23050bfb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5f40bfed, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@60b3870e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3b5daa8b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@300c24c8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6ae94af3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@169e3b57, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4041d2fd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@113a9459, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@31a4fa5f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@56873bbf, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@181fdda8, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5d421aae, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4b22755b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2417f543, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@42038ef4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@f597b70, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@57094f6d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4caf1522, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1285466d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@56433db6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4b2c6234, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7f1e6876, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4790ffd6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@871d41f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@20642ae7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2cb5ab45, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6c1b9f4a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6a4c6ffa, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6b7e5346, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6a9022ef, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5ac11138, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@537b9625, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4a860b6f, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@216acf8a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7370424e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7cb528bb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6929931, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@717310f6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@605ea4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@55c54ee3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@470c1e7b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2e9142cc, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2c86acc4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@53cb5de1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@74136e25, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5030c549, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4949b307, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4064cb9a, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2fe9e7f5, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@79a565cc, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7d702074, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1b2e1c5b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@7b189684, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2941172e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@554ef1f2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3e69e3c4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@17afe3b, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2023715d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@240d5ca, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@73467185, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@259bc2f0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1e09e687, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1a639e09, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5a690e99, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@219edb66, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@70722c0c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@76e767dd, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6468b25e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@337a005e, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@52894871, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1f1d1472, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3e46af8d, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@5d5d30eb, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@458f21f1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@32c603b6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3977f8a4, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@d995d09, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@31a565e2, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@337c0bd3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@35c867c0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@72fe0565, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@686ef4ad, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@3b9f48e0, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4d1fce34, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4f482fdf, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@509c7107, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1105ebbc, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2258e9c6, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@2c600c85, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@1fc75447, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@21a11408, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4452cf23, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@687ae708, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@4dbae32c, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@6412afc7, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@36eb5fb1, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@916acc3, net.minecraft.network.protocol.game.PacketPlayOutCommands$b@13af8d4e, 

и там еще много таких строк.

**Comment by Nektoo** [comment]
Ответы на просторах интернета не дали результатов. Может здесь помогут

**Comment by dmulloy2** [comment]
if my google translate is correct, it seems like you have an issue with the latest development build. in that case, could you run `/protocol dump` and paste the output with pastebin?

**Comment by Nektoo** [comment]
> protocol dump

ProtocolLib Dump
Timestamp: 01/11/23 08:30:50

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Pufferfish-42 (MC: 1.19.2)
Java Version: 17.0.5

ProtocolLib: com.comphenix.protocol.ProtocolLib@fdc4cf0[
  statistics=com.comphenix.protocol.metrics.Statistics@15075c63
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@734e623d
  packetTask=8
  tickCounter=709873
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@137172ba
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@7c8410e1
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@11d2684d
  commandProtocol=com.comphenix.protocol.CommandProtocol@3e19da50
  commandPacket=com.comphenix.protocol.CommandPacket@3e461824
  commandFilter=com.comphenix.protocol.CommandFilter@62191415
  packetLogging=com.comphenix.protocol.PacketLogging@608b981b
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@10301500
  server=CraftServer{serverName=Pufferfish,serverVersion=git-Pufferfish-42,minecraftVersion=1.19.2}
  file=plugins/ProtocolLib (2).jar
  description=org.bukkit.plugin.PluginDescriptionFile@1e39b81a
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (2).jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@85db3ba
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@65e3a5b0[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@137172ba
  packetListeners=[PacketAdapter[plugin=PL-Hide-Pro, sending=ListeningWhitelist[priority=NORMAL, packets=[COMMANDS[class=PacketPlayOutCommands, id=18]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PL-Hide-Pro, sending=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@43bb9521
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@307da4eb
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@48cb5971
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50370670
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (2).jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@4fba93ca
  server=CraftServer{serverName=Pufferfish,serverVersion=git-Pufferfish-42,minecraftVersion=1.19.2}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2fefdd
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=4
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@77f5fec7
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4ac571a
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.2)
  debug=false
]

Listeners:
de.nononitas.plhidepro.spigot.listeners.CommandSuggestionListener@2f907e03[
  plugin=PL-Hide-Pro v1.6.2
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[COMMANDS[class=PacketPlayOutCommands, id=18]], gamephase=PLAYING, options=[]]
]
io.github.kosmx.emotes.bukkit.BukkitWrapper$1@25aa7473[
  plugin=emotecraft v2.2.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]]
]
de.nononitas.plhidepro.spigot.listeners.TabcompleteListener@71511fec[
  incomingCommand={}
  plugin=PL-Hide-Pro v1.6.2
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[ASYNC]]
]

Plugins Using ProtocolLib:
PL-Hide-Pro by [Nononitas]
emotecraft by [KomsX]

**Comment by dmulloy2** [comment]
Try this build: https://ci.dmulloy2.net/job/ProtocolLib/606/

**Comment by Nektoo** [comment]
> Try this build: https://ci.dmulloy2.net/job/ProtocolLib/606/

Тоже спамит. Но меньше теперь проц нагружен

![image](https://user-images.githubusercontent.com/96636991/212026207-9363a9b8-6f31-447e-ad06-9ebf7c944e2a.png)
[dump-2023-01-12_10.14.47.txt](https://github.com/dmulloy2/ProtocolLib/files/10399984/dump-2023-01-12_10.14.47.txt)

**Comment by Nektoo** [comment]
Anyone help me?
