### ISSUE TITLE
Error I'm getting with my Paper server..

### ISSUE THREAD

**Issue by ImSotallyTober** [dmulloy2/ProtocolLib#2093]
![image](https://user-images.githubusercontent.com/122477590/211883053-c0c4e48b-ed8a-4a2b-bafd-bf29b15a037e.png)

**I'm not sure what to do? I am using the latest version as of 1/11/23.**

**_Here is what I got in the console:_**

1.01 18:01:09 [Server] INFO Stack Trace:
11.01 18:01:09 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
11.01 18:01:09 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
11.01 18:01:09 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
11.01 18:01:09 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
11.01 18:01:09 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
11.01 18:01:09 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
11.01 18:01:09 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
11.01 18:01:09 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
11.01 18:01:09 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
11.01 18:01:09 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
11.01 18:01:09 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
11.01 18:01:09 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
11.01 18:01:09 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
11.01 18:01:09 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
11.01 18:01:09 [Server] INFO Dump:
11.01 18:01:09 [Server] INFO Parameters: 
11.01 18:01:09 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@7941f87f[
11.01 18:01:09 [Server] INFO memoryAddress=139921109076880
11.01 18:01:09 [Server] INFO recyclerHandle=io.netty.util.Recycler$DefaultHandle@25050e11
11.01 18:01:09 [Server] INFO chunk=Chunk(9f2df1c: 27%, 1122304/4194304)
11.01 18:01:09 [Server] INFO handle=562980018192384
11.01 18:01:09 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
11.01 18:01:09 [Server] INFO offset=8192
11.01 18:01:09 [Server] INFO length=26
11.01 18:01:09 [Server] INFO maxLength=32
11.01 18:01:09 [Server] INFO cache=io.netty.buffer.PoolThreadCache@15b93e03
11.01 18:01:09 [Server] INFO tmpNioBuf=<null>
11.01 18:01:09 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
11.01 18:01:09 [Server] INFO refCnt=2
11.01 18:01:09 [Server] INFO readerIndex=26
11.01 18:01:09 [Server] INFO writerIndex=26
11.01 18:01:09 [Server] INFO markedReaderIndex=0
11.01 18:01:09 [Server] INFO markedWriterIndex=0
11.01 18:01:09 [Server] INFO maxCapacity=2147483647
11.01 18:01:09 [Server] INFO ]
11.01 18:01:09 [Server] INFO manager:
11.01 18:01:09 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@ede2f84[
11.01 18:01:09 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2df1ab74
11.01 18:01:09 [Server] INFO packetListeners=[PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
11.01 18:01:09 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1194ce8a
11.01 18:01:09 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@20b7fd06
11.01 18:01:09 [Server] INFO inputBufferedPackets=[]
11.01 18:01:09 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5fea549b
11.01 18:01:09 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7fe0ee19
11.01 18:01:09 [Server] INFO hasClosed=false
11.01 18:01:09 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
11.01 18:01:09 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@48b79ff1
11.01 18:01:09 [Server] INFO server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1892,minecraftVersion=1.19.3}
11.01 18:01:09 [Server] INFO library=ProtocolLib v4.8.0
11.01 18:01:09 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5ab4dcd5
11.01 18:01:09 [Server] INFO knowsServerPackets=true
11.01 18:01:09 [Server] INFO knowsClientPackets=true
11.01 18:01:09 [Server] INFO phaseLoginCount=2
11.01 18:01:09 [Server] INFO phasePlayingCount=2
11.01 18:01:09 [Server] INFO packetCreation=false
11.01 18:01:09 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4577a30f
11.01 18:01:09 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4e7eb8c
11.01 18:01:09 [Server] INFO hasRecycleDistance=true
11.01 18:01:09 [Server] INFO minecraftVersion=(MC: 1.19.3)
11.01 18:01:09 [Server] INFO debug=false
11.01 18:01:09 [Server] INFO ]
11.01 18:01:09 [Server] INFO Sender:
11.01 18:01:09 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@597542ee[
11.01 18:01:09 [Server] INFO decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
11.01 18:01:09 [Server] INFO encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
11.01 18:01:09 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@652f8f2d
11.01 18:01:09 [Server] INFO player=CraftPlayer{name=ImSotallyTober}
11.01 18:01:09 [Server] INFO updated=<null>
11.01 18:01:09 [Server] INFO playerName=ImSotallyTober
11.01 18:01:09 [Server] INFO playerConnection=<null>
11.01 18:01:09 [Server] INFO networkManager=net.minecraft.network.NetworkManager@35957791
11.01 18:01:09 [Server] INFO originalChannel=[id: 0xef5a4e95, L:/209.192.163.77:25565 - R:/45.18.136.108:51351]
11.01 18:01:09 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@35957791, previous=[id: 0xef5a4e95, L:/209.192.163.77:25565 - R:/45.18.136.108:51351], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@76153e65, previousLoaded=true, currentSet=true, forceAccess=true]
11.01 18:01:09 [Server] INFO packetMarker={}
11.01 18:01:09 [Server] INFO currentEvent=<null>
11.01 18:01:09 [Server] INFO finalEvent=<null>
11.01 18:01:09 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@584707b
11.01 18:01:09 [Server] INFO vanillaDecoder=net.minecraft.network.PacketDecoder@1b33a6a5
11.01 18:01:09 [Server] INFO vanillaEncoder=net.minecraft.network.PacketEncoder@33bbd187
11.01 18:01:09 [Server] INFO finishQueue=[]
11.01 18:01:09 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4577a30f
11.01 18:01:09 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@4a2385d0
11.01 18:01:09 [Server] INFO injected=true
11.01 18:01:09 [Server] INFO closed=false
11.01 18:01:09 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
11.01 18:01:09 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@35d1152e
11.01 18:01:09 [Server] INFO singleDecode=false
11.01 18:01:09 [Server] INFO first=true
11.01 18:01:09 [Server] INFO firedChannelRead=false
11.01 18:01:09 [Server] INFO selfFiredChannelRead=true
11.01 18:01:09 [Server] INFO decodeState=1
11.01 18:01:09 [Server] INFO discardAfterReads=16
11.01 18:01:09 [Server] INFO numReads=0
11.01 18:01:09 [Server] INFO added=true
11.01 18:01:09 [Server] INFO ]
11.01 18:01:09 [Server] INFO Version:
11.01 18:01:09 [Server] INFO ProtocolLib v4.8.0
11.01 18:01:09 [Server] INFO Java Version:
11.01 18:01:09 [Server] INFO 17.0.5

**Comment by ehighb** [comment]
I have the same error

**Comment by ehighb** [comment]
nvm download this version of it  https://ci.dmulloy2.net/job/ProtocolLib/606/

**Comment by Jeppa** [comment]
>ProtocolLib v4.8.0
>git-Purpur-1892,minecraftVersion=1.19.3

--> that doesn't fit...
