### ISSUE TITLE
Incompatibility with Glowstone

### ISSUE THREAD

**Issue by Small-Ku** [dmulloy2/ProtocolLib#210]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues

Debug paste link:http://pastebin.com/hNsAeetm

Description and relevant errors:ProtocolLib seems like not compatible with Glowstone.

**Comment by dmulloy2** [comment]
ProtocolLib currently does not support Glowstone. One of the eventual goals of the API splitoff was to support different platforms, but this is currently not the case.
