### ISSUE TITLE
ProtocolManager is null

### ISSUE THREAD

**Issue by HubiSm4** [dmulloy2/ProtocolLib#2104]
I want to send silent packet using ProtocolLib, but console throws an exception: Cannot invoke "com.comphenix.protocol.ProtocolManager.sendServerPacket(org.bukkit.entity.Player, com.comphenix.protocol.events.PacketContainer, boolean)" because "protocolManager" is null

Im getting manager like this: 
![image](https://user-images.githubusercontent.com/45921479/212464438-071f641b-695a-4056-bfc4-5efd6667dba6.png)

I tried to use api version 4.8.0 and dev build 5.0.0, nothing worked

Anyone know how to fix it?

**Comment by IllegalTempo** [comment]
Define your ProtocolManager in OnEnable()
