### ISSUE TITLE
anyone knows what is causing spam of this error?

### ISSUE THREAD

**Issue by MalevolentMech** [dmulloy2/ProtocolLib#2106]
https://mclo.gs/UzavXSt

**Comment by IllegalTempo** [comment]
Use a development version of protocollib fix this for me

**Comment by Rapaduraa** [comment]
what number of the version u use?

**Comment by IllegalTempo** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by IllegalTempo** [comment]
![image](https://user-images.githubusercontent.com/109812715/212560831-a8eff893-bd84-410d-aec5-19cbd063ab0b.png)
Latest is 612
