### ISSUE TITLE
Stacktrace on quick disconnect

### ISSUE THREAD

**Issue by Kakifrucht** [dmulloy2/ProtocolLib#211]
Debug paste link: https://pastebin.com/zJ8G8N8a (contains stacktrace aswell)

This happens immediately after restart of server. The error is spammed a couple of times.

**Comment by dmulloy2** [comment]
Does this happen after a full restart or reload?

Also, can you set ````debug: true```` in the ProtocolLib config.yml and ````debug=true```` in the server.properties?

This exception is important:
````-snip- lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: object is not an instance of declaring class````

**Comment by Kakifrucht** [comment]
It was a full restart of the server. I'm pretty sure that it only happens if the initial connection is established during server launch. This also seems to be minor, as it doesn't happen if there is some delay between start and connect. I will try to enable debug once I get time for it.
Not sure if relevant, but I'm using ViaVersion aswell.

**Comment by dmulloy2** [comment]
It might have to do with ViaVersion, I've been getting lots of bug reports caused by it lately.

**Comment by Kakifrucht** [comment]
Can't reproduce anymore, not sure if fixed during ViaVersion update or some spigot update in the meanwhile.
