### ISSUE TITLE
EnumGamemode problem

### ISSUE THREAD

**Issue by AarowDeveloper** [dmulloy2/ProtocolLib#2112]
- [ ] This issue is not solved in a development build

**Describe the bug**
net.minecraft.world.level.EnumGamemode.NOT_SET method doesn't exist is an error i used EnumWrapper.EnumGamemode.NOT_SET, but the problem is the nms's EnumGamemode is just a bunch of letters due to obfuscation

**Expected behavior**
That this doesn't happen

**Version Info**
Latest Dev Build

**Additional context**
Just change the code so instead of using old enum values, use the new, which are now letters

**Comment by lukalt** [comment]
Could you please share your code and briefly explain what you are trying to do? Also, which Minecraft version are you targetting
