### ISSUE TITLE
PlayerInfoAction bug

### ISSUE THREAD

**Issue by AarowDeveloper** [dmulloy2/ProtocolLib#2113]
PacketType packetType = PacketType.Play.Server.PLAYER_INFO;
 PacketContainer packetContainer = new PacketContainer(packetType);
 packetContainer.getPlayerInfoAction().write(0, EnumWrappers.PlayerInfoAction.ADD_PLAYER);

 Exception in thread "Thread-16" FieldAccessException: Field index 0 is out of bounds for length 0

**Comment by portlek** [comment]
if you are using 1.19.3 check this out:
https://www.spigotmc.org/threads/1-19-3-add_player-and-remove_player-with-protocollib.585490/
