### ISSUE TITLE
Packet encoding of packet ID 78 threw (skippable? false)

### ISSUE THREAD

**Issue by TheFaik** [dmulloy2/ProtocolLib#2117]
The player writes to the chat and as a result he is kicked, and the error is reproduced in the console.

1. Log in to the server
2. Writes to the chat (just a message, not a command).
3. Departure from the server + error in the console.

Screenshot:

![1674225779604](https://user-images.githubusercontent.com/99492973/213731172-e97a4154-9df9-455e-be51-a2b95e9d66e0.png)

ProtocolLib dump:

[dump-2023-01-21_01.02.19.txt](https://github.com/dmulloy2/ProtocolLib/files/10467441/dump-2023-01-21_01.02.19.txt)

*Translation from Russian into English was made through Google Translate.*

**Comment by Brokkonaut** [comment]
Some plugin that writes incorrect data in the packet needs an update. try updating or removing plugins like tablist plugins or npc plugins

**Comment by TonyMontero** [comment]
If you don't paste your plugin's list it will be almost impossible to find what's going on.
