### ISSUE TITLE
error with viaversion, netty?

### ISSUE THREAD

**Issue by Dimatert9** [dmulloy2/ProtocolLib#212]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Debug paste link:
http://pastebin.com/Lgqxp3P9
Description and relevant errors:
https://github.com/MylesIsCool/ViaVersion/issues/411

**Comment by dmulloy2** [comment]
I don't see how this is an issue with ProtocolLib.
