### ISSUE TITLE
ProtocolLib logging exception when sending actionbar / updating sign with the paper api (No interaction with protocolLib directly)

### ISSUE THREAD

**Issue by ToberoCat** [dmulloy2/ProtocolLib#2123]
- [ ] This issue is not solved in a development build

**Describe the bug**
Okay, I've written a plugin for a customer. The customer uses protocol lib on his server, my plugin doesn't interact with it. Every time my plugin sends a actionbar / changes a signs title (Don't know excatly which of these two things caused the issue), protocollib crashes, with no hint to any of my classes related to it.

**To Reproduce**
Sadly, I don't know excatly how it got produced, but sending a actionbar to a player or updating the lines causes this issue

**Expected behavior**
I didn't want the server to crash due to a unknown cause
**Screenshots**
Don't have one, sorry

**Version Info**
Sorry, can't give you it, as my customer has already went to bed. Will take some time
**Additional context**
The server runs with NullcordX, 1.19.2. 
[Crash my customer got](https://paste.helpch.at/izutoxewer.swift)

**Comment by Jeppa** [comment]
Updating ProtocolLib to build 606 should help...

**Comment by ToberoCat** [comment]
Okay
