### ISSUE TITLE
Packet encoding of packet ID 78 threw (skippable? false)

### ISSUE THREAD

**Issue by Cocotterooo** [dmulloy2/ProtocolLib#2125]
- [ ] This issue is not solved in a development build

**Describe the bug**
Packet encoding of packet ID 78 threw (skippable? false) it happens when trying to enter the server

**Expected behavior**
be able to enter the server normally 

**Screenshots**
![image](https://user-images.githubusercontent.com/103317717/214603364-fe9c1c53-4f5a-4d24-a172-b5243144beb9.png)

Complete Log: https://mclo.gs/fXqMD25

**Version Info**
https://pastebin.com/NcpQD8SE

**Additional context**
This started for me when I upgraded the server from 1.19.2 to 1.19.3 and updated most of the plugins.

I have Purpur 1.19.3 (Build 1905)

**Comment by WMythos** [comment]
did you ever find a fix for this? @Cocotterooo
