### ISSUE TITLE
weird errors

### ISSUE THREAD

**Issue by halaay** [dmulloy2/ProtocolLib#2128]
![image_2023-01-27_194603736](https://user-images.githubusercontent.com/82904903/215144372-ab690afe-a4ca-4fe6-80c5-bc9b519660da.png)
- [ ] This issue is not solved in a development build

**Describe the bug**
okay, so i downloaded protocol lib cuz interactive chat needed it, and i also downloaded placeholderapi, vault and multiverse core, i think i downloaded the 1.19.3 one (if that exists) since my server is 1.19.3, is there a fix?

**To Reproduce**

**Expected behavior**
idk

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/Nrcx8f5S

**Additional context**

**Comment by halaay** [comment]
also, i have the latest 1.19.3 dev build

**Comment by Jeppa** [comment]
And again.....
You should use the latest dev build (ProtocolLib)...

**Comment by Kesuaheli** [comment]
I am **using the latest dev build** (#612 from 2 weeks ago) and have this exact issue. Running 1.19.3 Server and this error appears (multiple times) when joining.
