### ISSUE TITLE
Protocol Lib console spam

### ISSUE THREAD

**Issue by GamingWithRyan** [dmulloy2/ProtocolLib#2129]
**Describe the bug**
I don't know whats happening but this is my whole console right now. Alot of which is telling me to report it as a bug on this github page.
https://paste.shockbyte.com/alutopiyuvecavirebay

**To Reproduce**
1.  See error

**Expected behavior**
No console spam.

**Version Info**
https://paste.denizenscript.com/View/105787

**Additional context**
Plugin list: https://paste.denizenscript.com/View/105788
Paper Version: https://paste.denizenscript.com/View/105789
Latest.log: https://paste.denizenscript.com/View/105791
Server version 1.19.3
Protocol Lib config.yml: https://paste.denizenscript.com/View/105792

**Comment by Kesuaheli** [comment]
Getting the same.
As soon as a player joins it throws the error (multiple times) and ask to open a ticket.
Server version is also 1.19.3.

I guess there's a significant change in mojangs protocol, so that packets can't be read anymore.

**Comment by GamingWithRyan** [comment]
Kesuaheli I fixed mine by updating protocol lib to the latest dev build because that's what it says on the spigot page.

**Comment by Kesuaheli** [comment]
Thanks, I thought I was already using it, but I double-checked and found my mistake. Now I'm on build #612 and as far it seems to work.

**Comment by GamingWithRyan** [comment]
Ok good to know it worked for yours aswell! I'm going to close this now.
