### ISSUE TITLE
Error whenever listener is called

### ISSUE THREAD

**Issue by xXProdigalXx** [dmulloy2/ProtocolLib#213]
Error: http://pastebin.com/jBj35cZM
All relevant code: http://pastebin.com/ix0vb4Mh

The error happens every time the listener is called.

**Comment by MiniDigger** [comment]
you are trying to read a field that is not there.
use http://wiki.vg/Protocol#Entity_Metadata to get an documentation on the packets.

**Comment by dmulloy2** [comment]
You're using the Packets class, which is deprecated and no longer updated. Switch to [PacketType](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/PacketType.html) and your issue should be resolved.
