### ISSUE TITLE
ProtocolLib 5.0无法加载

### ISSUE THREAD

**Issue by bliur** [dmulloy2/ProtocolLib#2131]
- [ ] This issue is not solved in a development build

**Describe the bug**
Plug-in failed to load
**To Reproduce**

load ProtocolLib 5.0

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

https://netcut.cn/1gnrgf2q9
**Additional context**

**Comment by Jeppa** [comment]
Afaik you should not use latest dev build for 1.12 server ... :/
Release 4.8.0 is good.

**Comment by bliur** [comment]
> Afaik 你不应该为 1.12 服务器使用最新的开发版本...... ：/ 版本 4.8.0 很好。

girmac需要他:（

**Comment by Jeppa** [comment]
english please,
and what is girmac ?

**Comment by bliur** [comment]
> 请用英语，什么是吉尔马克？我猜你的意思是严峻的？嗯......它支持 1.12 并需要 5.x ProtocolLib...也许尝试像 606 这样的旧开发版本之一......

Thank you very much for your help, unfortunately version 606 still does not work, the following error is reported
https://netcut.cn/gdhdhb
