### ISSUE TITLE
Error receiving packet 78

### ISSUE THREAD

**Issue by Nalkos** [dmulloy2/ProtocolLib#2133]
**Describe the bug**
When I connect to my server everything is fine but when I go to a specific chunk it disconnects me from the server with the message : Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class net.minecraft.network syncher Dataillatcher$Iten cannot be cast to class net.minecraft.network.syncher Datallatcher Sb (netminecraftnetworksyncher DatallatchersIten and netminecraftnetwork syncher Datallatchers are in unnamed module of loader JavanetURLClassLoader 85b883586)
What should I do to solve this problem?

**Screenshots**
![beug serveur ProtocolLib](https://user-images.githubusercontent.com/19148025/215554173-c0c4e1f9-228a-4438-aa26-d9559f2edabe.PNG)

**Version Info**
https://pastebin.com/Er6HX62Q

L'error "Error receiving packet 78":
https://pastebin.com/gcyRJg3R

**Comment by plytki** [comment]
@Nalkos I have the same exact error.
