### ISSUE TITLE
FieldAccessException!

### ISSUE THREAD

**Issue by yxdeath** [dmulloy2/ProtocolLib#214]
Code : http://pastebin.com/2BiK9dcK

When player level changed, I want to change ItemMeta in player inventory.
State WINDOW_ITEMS packet through inventoryupdate method when player level changed.

But it have crashed because of FieldAccessException.

**Comment by MiniDigger** [comment]
You should provide the stack trace.

**Comment by yxdeath** [comment]
@MiniDigger http://pastebin.com/cFrfLMVc

**Comment by MiniDigger** [comment]
PacketPlayOutWindowItems does not contain a ItemStack field. Take a look at the documentation here to see which fields are available http://wiki.vg/Protocol#Window_Items

**Comment by yxdeath** [comment]
I don't know to use that with StructureModifier or any slot data field.

**Comment by dmulloy2** [comment]
The fields in the window items packet are:
````java
    private int a;
    private ItemStack[] b;
````

I would venture to guess you're looking to modify the ItemStack array, which you would do with ````packet.getItemArrayModifier()````

**Comment by yxdeath** [comment]
`					try {
						Field field = Class.forName("net.minecraft.server.v1_9_R1.PacketPlayOutWindowItems").getDeclaredField("b");
						field.setAccessible(true);
						
						field.get(packet.getItemArrayModifier().read(0));
						
						ItemStack[] im = (ItemStack[]) field.get(packet.getItemArrayModifier().read(0));
						for(int i = 0; i < im.length; i++) {
							if(im[i].getType() == Material.BEACON) {
								event.getPlayer().sendMessage("Test Message 5");
							}
						}
					} catch (Exception e) {
						e.printStackTrace();
					}`


What should I do in this code?

**Comment by dmulloy2** [comment]
ProtocolLib will do all the reflection for you, you don't need to be using the Field or Class classes. 

````ItemStack[] array = packet.getItemArrayModifier().read(0);```` would suffice

**Comment by yxdeath** [comment]
Problem solve :)

Thanks so much
