### ISSUE TITLE
Huge console exception + spam messages on chat when a player joins

### ISSUE THREAD

**Issue by DavidTheExplorer** [dmulloy2/ProtocolLib#2143]
**Describe the bug**
Title.

**To Reproduce**
Literally join a server that has the latest version on Spigot.

**Version Info**
https://pastebin.com/nPGXaAYG

**Comment by Jeppa** [comment]
>ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.3-R0.1-SNAPSHOT

**8(**

**Comment by DavidTheExplorer** [comment]
> > ProtocolLib Version: ProtocolLib v4.8.0
> > Bukkit Version: 1.19.3-R0.1-SNAPSHOT
> 
> **8(**

What?

**Comment by Jeppa** [comment]
Info from dev version page:
>Recommended Versions
    [Latest](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for 1.19.3
    [#606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for 1.19-1.19.2
    [v4.8.0](https://github.com/dmulloy2/ProtocolLib/releases/download/4.8.0/ProtocolLib.jar) for 1.8-1.18.x

Info from project page @ spigot :
>Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19.3
Use build [606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for Minecraft 1.19-1.19.2
Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0) for all other recent Minecraft versions

so... what do you think.... :)

**Comment by DavidTheExplorer** [comment]
> Info from dev version page:
> 
> > Recommended Versions
> > [Latest](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for 1.19.3
> > [#606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for 1.19-1.19.2
> > [v4.8.0](https://github.com/dmulloy2/ProtocolLib/releases/download/4.8.0/ProtocolLib.jar) for 1.8-1.18.x
> 
> Info from project page @ spigot :
> 
> > Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19.3
> > Use build [606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for Minecraft 1.19-1.19.2
> > Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0) for all other recent Minecraft versions
> 
> so... what do you think.... :)
I think it's ridiculous that the Spigot page says 1.19 support while the downloaded jar breaks on that version, this must be solved asap.
