### ISSUE TITLE
MC Server Issue console error spam 

### ISSUE THREAD

**Issue by Senpaii28** [dmulloy2/ProtocolLib#2148]
ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
03.02 21:51:16 [Server] INFO If this problem hasn't already been reported, please open a ticket
03.02 21:51:16 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
03.02 21:51:16 [Server] INFO Stack Trace:
03.02 21:51:16 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
03.02 21:51:16 [Server] INFO at ProtocolLib (2).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
03.02 21:51:16 [Server] INFO at ProtocolLib (2).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
03.02 21:51:16 [Server] INFO at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
03.02 21:51:16 [Server] INFO at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
03.02 21:51:16 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
03.02 21:51:16 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
03.02 21:51:16 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
03.02 21:51:16 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
03.02 21:51:16 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
03.02 21:51:16 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
03.02 21:51:16 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
03.02 21:51:16 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
03.02 21:51:16 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
03.02 21:51:16 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:831)
03.02 21:51:16 [Server] INFO Dump:
03.02 21:51:16 [Server] INFO Parameters: 
03.02 21:51:16 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@521c7cdb[
03.02 21:51:16 [Server] INFO memoryAddress=140707102882080
03.02 21:51:16 [Server] INFO recyclerHandle=NOOP_HANDLE
03.02 21:51:16 [Server] INFO chunk=Chunk(3b0a3835: 2%, 65536/4194304)
03.02 21:51:16 [Server] INFO handle=563083097407488
03.02 21:51:16 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
03.02 21:51:16 [Server] INFO offset=8192
03.02 21:51:16 [Server] INFO length=210
03.02 21:51:16 [Server] INFO maxLength=224
03.02 21:51:16 [Server] INFO cache=io.netty.buffer.PoolThreadCache@d968855
03.02 21:51:16 [Server] INFO tmpNioBuf=<null>
03.02 21:51:16 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
03.02 21:51:16 [Server] INFO refCnt=2
03.02 21:51:16 [Server] INFO readerIndex=210
03.02 21:51:16 [Server] INFO writerIndex=210
03.02 21:51:16 [Server] INFO markedReaderIndex=0
03.02 21:51:16 [Server] INFO markedWriterIndex=0
03.02 21:51:16 [Server] INFO maxCapacity=2147483647
03.02 21:51:16 [Server] INFO ]
03.02 21:51:16 [Server] INFO manager:
03.02 21:51:16 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@ea859ec[
03.02 21:51:16 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@37c5bc4c
03.02 21:51:16 [Server] INFO packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
03.02 21:51:16 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@65f6cc3b
03.02 21:51:16 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4925f193
03.02 21:51:16 [Server] INFO inputBufferedPackets=[]
03.02 21:51:16 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@58ea662
03.02 21:51:16 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1fb34d43
03.02 21:51:16 [Server] INFO hasClosed=false
03.02 21:51:16 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0, pluginEnabled=true, url=plugins/ProtocolLib (2).jar}
03.02 21:51:16 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@4cf7dd9a
03.02 21:51:16 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-"4da844f",minecraftVersion=1.19.3}
03.02 21:51:16 [Server] INFO library=ProtocolLib v4.7.0
03.02 21:51:16 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5a751a6d
03.02 21:51:16 [Server] INFO knowsServerPackets=true
03.02 21:51:16 [Server] INFO knowsClientPackets=true
03.02 21:51:16 [Server] INFO phaseLoginCount=1
03.02 21:51:16 [Server] INFO phasePlayingCount=2
03.02 21:51:16 [Server] INFO packetCreation=false
03.02 21:51:16 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@35e1321c
03.02 21:51:16 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@26b2c1b0
03.02 21:51:16 [Server] INFO hasRecycleDistance=true
03.02 21:51:16 [Server] INFO minecraftVersion=(MC: 1.19.3)
03.02 21:51:16 [Server] INFO debug=false
03.02 21:51:16 [Server] INFO ]
03.02 21:51:16 [Server] INFO Sender:
03.02 21:51:16 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@fd9bf09[
03.02 21:51:16 [Server] INFO decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
03.02 21:51:16 [Server] INFO encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
03.02 21:51:16 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@6bb1e067
03.02 21:51:16 [Server] INFO player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@29523bef
03.02 21:51:16 [Server] INFO updated=<null>
03.02 21:51:16 [Server] INFO playerName=<null>
03.02 21:51:16 [Server] INFO playerConnection=<null>
03.02 21:51:16 [Server] INFO networkManager=net.minecraft.network.NetworkManager@538da9a6
03.02 21:51:16 [Server] INFO originalChannel=[id: 0x5a6f7e36, L:/172.17.0.11:25565 - R:/51.161.99.12:38575]
03.02 21:51:16 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@538da9a6, previous=[id: 0x5a6f7e36, L:/172.17.0.11:25565 - R:/51.161.99.12:38575], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5b25f09e, previousLoaded=true, currentSet=true, forceAccess=true]
03.02 21:51:16 [Server] INFO packetMarker={}
03.02 21:51:16 [Server] INFO currentEvent=<null>
03.02 21:51:16 [Server] INFO finalEvent=<null>
03.02 21:51:16 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4d060432
03.02 21:51:16 [Server] INFO vanillaDecoder=net.minecraft.network.PacketDecoder@4def63a7
03.02 21:51:16 [Server] INFO vanillaEncoder=net.minecraft.network.PacketEncoder@159f2ef
03.02 21:51:16 [Server] INFO finishQueue=[]
03.02 21:51:16 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@35e1321c
03.02 21:51:16 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@856ee4d
03.02 21:51:16 [Server] INFO injected=true
03.02 21:51:16 [Server] INFO closed=false
03.02 21:51:16 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 210, widx: 210, cap: 210)
03.02 21:51:16 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@3e1256bb
03.02 21:51:16 [Server] INFO singleDecode=false
03.02 21:51:16 [Server] INFO first=true
03.02 21:51:16 [Server] INFO firedChannelRead=false
03.02 21:51:16 [Server] INFO selfFiredChannelRead=true
03.02 21:51:16 [Server] INFO decodeState=1
03.02 21:51:16 [Server] INFO discardAfterReads=16
03.02 21:51:16 [Server] INFO numReads=0
03.02 21:51:16 [Server] INFO added=true
03.02 21:51:16 [Server] INFO ]
03.02 21:51:16 [Server] INFO Version:
03.02 21:51:16 [Server] INFO ProtocolLib v4.7.0
03.02 21:51:16 [Server] INFO Java Version:
03.02 21:51:16 [Server] Startup 17
03.02 21:51:16 [Server] INFO Server:
03.02 21:51:16 [Server] INFO git-Paper-"4da844f" (MC: 1.19.3)

**Comment by Jeppa** [comment]
>03.02 21:51:16 [Server] INFO ProtocolLib v4.7.0
03.02 21:51:16 [Server] INFO git-Paper-"4da844f" (MC: 1.19.3)

Serious? **8(**
