### ISSUE TITLE
No field with type [Lnet.minecraft.server.v1_9_R2.IChatBaseComponent; exists in class PacketPlayOutTileEntityData

### ISSUE THREAD

**Issue by ProgrammingAtDawn** [dmulloy2/ProtocolLib#215]
Not sure whether this belongs here, but lets try...

Error: http://pastebin.com/ZJS12ga9
Code: http://pastebin.com/7HS6wt95

Description:
I'm trying to get the ExperienceBankII plugin running with the latest ProtocolLib version (4.0.1) on Spigot 1.9.4.
Not sure, whether this is a problem in the plugin itself or in ProtocolLib, but as the exception is happening in the ProtocolLib code, I'm reporting here first.

Did something change in the underlying code, that signs don't have "IChatBaseComponentArray" anymore?

Not exactly the same error, but similarities to #213

**Comment by dmulloy2** [comment]
That's an issue with the plugin. In 1.9.4 the sign update packet was removed and the functionality was moved to the tile entity packet.

**Comment by ProgrammingAtDawn** [comment]
Will ProtocolLib provide a function to get the text lines / marshalled IChatBaseComponent equivalent from the tile entity packet? In lack of better knowledge right now I'm using really bad code to walk through the NBTModifier as a workaround.

**Comment by dmulloy2** [comment]
Any method on ProtocolLib's side would probably go through the NBTModifier anyways. What code are you using now?

**Comment by ProgrammingAtDawn** [comment]
Before: https://gist.github.com/ProgrammingAtDawn/d3933f6665598cea2f79d9041281867f
After: https://gist.github.com/ProgrammingAtDawn/25b166275a1501cda852f91a2e3e2bd6

I don't have any clue about minecraft plugin development, just took the java debugger, looked where the data is stored and walked to it.

**Comment by dmulloy2** [comment]
Yeah that's effectively what anything on ProtocolLib's side would be. If anything I'd add it to a utility class.
