### ISSUE TITLE
Packet prelogin and login unable to intercept

### ISSUE THREAD

**Issue by wyamg4** [dmulloy2/ProtocolLib#2151]
- [ ] This issue is not solved in a development build

**Describe the bug**
An error wall is printed to the console and in-game chat every time PacketType.Play.Server.OPEN_WINDOW occurs.

**To Reproduce**
Listen for OPEN_WINDOW packet within an OpenInventoryEvent listener. Open an inventory.

**Expected behavior**
Packet is received successfully and you can identify/change packet fields.

**Screenshots**
Error wall provided: https://pastebin.com/L7p64WnX

**Version Info**
https://pastebin.com/b4SdrtzA

**Additional context**
N/A

**Comment by Jeppa** [comment]
And again a candidate... :)
>ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.3-R0.1-SNAPSHOT

That doesn't fit...

**Comment by wyamg4** [comment]
Should I be on 19.2?

**Comment by Jeppa** [comment]
You should be on dev build #612...
