### ISSUE TITLE
Since i added protocollib on my 1.19.3 paper server this is popping in my chat and console

### ISSUE THREAD

**Issue by ismailbesic** [dmulloy2/ProtocolLib#2157]
[16:20:42 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@7fdcf7a0[
    a=[UPDATE_LATENCY]
    b=[b[profileId=12d48134-16ee-3964-9719-d60186563f5c, profile=com.mojang.authlib.GameProfile@28327f09[id=12d48134-16ee-3964-9719-d60186563f5c,name=IsmailSIGMA,properties={},legacy=false], listed=true, latency=106, gameMode=CREATIVE, displayName=null, chatSession=null]]
  ]
[16:18:56 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart

**Comment by Jeppa** [comment]
ProtocolLib version?
