### ISSUE TITLE
Unsupported server packet id.

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#216]
`[22:36:50 WARN]: [ProtocolLib] [PacketFilterManager] [SensibleToolbox] Unsupported server packet ID in current Minecraft version: UNREGISTERED[LEGACY, SERVER, -1, legacy: 104, classNames: []]`

Description and relevant errors:
so i'm not soo familiar with protocol lib, so i was wondering if you could help me out with an error ive been getting with a plugin im working with atm.

**Comment by dmulloy2** [comment]
Looks like SensibleToolbox needs to be updated, they're using the unsupported Packets class: https://github.com/TheBusyBiscuit/sensibletoolbox/blob/master/src/main/java/me/desht/dhutils/ItemGlow.java
