### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by Mas-o** [dmulloy2/ProtocolLib#2161]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/64kFwucx

Description and relevant errors: Seems to fail client packages out of nowhere

**Comment by Jeppa** [comment]
> _Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
... 
>     * [x]  This isn't fixed in a recent development build
... 
>     * [x]  You've checked for duplicate issues

and
>08.02 15:34:58 [Server] INFO ProtocolLib v4.8.0
08.02 15:34:58 [Server] INFO 3649-Spigot-19641c7-7167588 (MC: 1.19.3)

Serious????
-> https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
