### ISSUE TITLE
Error when entering a specific chunk: Packet encoding of packet ID 78 threw

### ISSUE THREAD

**Issue by SushiBarIV** [dmulloy2/ProtocolLib#2162]
- [x] This issue is not solved in a development build

**Describe the bug**
I used a custom made gun plugin from a dev I commissioned to use protocollib for some features.
However while in 1.19.2 everything was fine at first I thought updating to 1.19.3 shouldn't be an issue ^^
So I shot with a gun, since then I get kicked when I enter that chunk with following error: https://pastebin.com/4PCqykAJ

the kick message is just "Disconnected"

Then I deleted my user data so I respawn at the default spawn, I shot around and everything was find.
When I remove ProtocolLib everything works aswell, I can enter that bugged chunk aswell.

**To Reproduce**
Can't really reproduce it yourself I guess.

**Expected behavior**
Well, that I get not kicked from the Server when entering a chunk ^^

**Screenshots**
None

**Version Info**
https://pastebin.com/t9WaNN1Y

**Additional context**
I tried with multiple forks: Paper, Spigot and Purpur all 1.19.3

**Comment by SushiBarIV** [comment]
Demonstration:
https://user-images.githubusercontent.com/45595515/217667878-d49f49c6-ddaf-4dcf-bb07-e5b344f292b5.mp4

**Comment by SammHP** [comment]
I'm having the same issue

**Comment by Jeppa** [comment]
I would try removing TAB ...
It is ONE of the reasons for this bug.
https://github.com/dmulloy2/ProtocolLib/issues/2094#issuecomment-1410893495
