### ISSUE TITLE
Paper 1.19.3 Console Bug Dump

### ISSUE THREAD

**Issue by yatsecs** [dmulloy2/ProtocolLib#2165]
- [ ] This issue is not solved in a development build

**Describe the bug**
I'm not sure, the console told me to make this report. I keep getting a ton of text in the server console and game chat which is annoying and i don't know how to get rid of it

**To Reproduce**
1. Install plugin on Paper 1.19.3
2. Start Server
3. That's all

**Expected behavior**
Literally nothing, a seperate plugin lists this one as a dependancy so I installed it. didn't edit anything

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.
](https://pastebin.com/YJzPqyvR)

**Comment by Jeppa** [comment]
>ProtocolLib v4.8.0
git-Paper-393 (MC: 1.19.3)

Does ANYONE even READ the project page or the development page??????????
I give it up... :(
Daily the same, multiple issues and all with the same content...

OK, one last time: **_ProtocolLib** v4.8.0 is NOT compatible with 1.19.x! You must use latest dev build!!!_**

**Comment by yatsecs** [comment]
> OK, one last time: **_ProtocolLib v4.8.0 is NOT compatible with 1.19.x! You must use latest dev build!!!_**

Sorry mate I just hit the download button on spigot, why is the latest version of there nearly a year old anyway? I'd assume most people would need the 1.19 versions

**Comment by Jeppa** [comment]
> > OK, one last time: **_ProtocolLib v4.8.0 is NOT compatible with 1.19.x! You must use latest dev build!!!_**
> 
> Sorry mate I just hit the download button on spigot, why is the latest version of there nearly a year old anyway? I'd assume most people would need the 1.19 versions

Yes, there realy should be a release update, that supports all versions...
But for now there's only the dev build.
And that info is on the main page on spigot, written in big friendly letters ;)
