### ISSUE TITLE
Console reported error

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#2168]
As per the request on my console, please see below for errors I am receiving.  I have just updated to the newest release of Paper 1.19.3 #399, however, this was happening on the previous version.

13.02 19:22:53 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@4bd4cf44.
13.02 19:22:53 [Server] ERROR INTERNAL ERROR: Unable to intercept a read client packet.
13.02 19:22:53 [Server] INFO If this problem hasn't already been reported, please open a ticket
13.02 19:22:53 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
13.02 19:22:53 [Server] INFO Stack Trace:
13.02 19:22:53 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
13.02 19:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
13.02 19:22:53 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
13.02 19:22:53 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
13.02 19:22:53 [Server] INFO Dump:
13.02 19:22:53 [Server] INFO Parameters: 
13.02 19:22:53 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@2d5412cc[
13.02 19:22:53 [Server] INFO memoryAddress=140342889322640
13.02 19:22:53 [Server] INFO recyclerHandle=NOOP_HANDLE
13.02 19:22:53 [Server] INFO chunk=Chunk(6e8e7c17: 1%, 16384/4194304)
13.02 19:22:53 [Server] INFO handle=562980018192384
13.02 19:22:53 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
13.02 19:22:53 [Server] INFO offset=8192
13.02 19:22:53 [Server] INFO length=19
13.02 19:22:53 [Server] INFO maxLength=32
13.02 19:22:53 [Server] INFO cache=io.netty.buffer.PoolThreadCache@25d48ec9
13.02 19:22:53 [Server] INFO tmpNioBuf=<null>
13.02 19:22:53 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
13.02 19:22:53 [Server] INFO refCnt=2
13.02 19:22:53 [Server] INFO readerIndex=19
13.02 19:22:53 [Server] INFO writerIndex=19
13.02 19:22:53 [Server] INFO markedReaderIndex=0
13.02 19:22:53 [Server] INFO markedWriterIndex=0
13.02 19:22:53 [Server] INFO maxCapacity=2147483647
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO manager:
13.02 19:22:53 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@129c2b89[
13.02 19:22:53 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@13bf4dd5
13.02 19:22:53 [Server] INFO packetListeners=[PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=MyPet, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MyPet, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
13.02 19:22:53 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6283403d
13.02 19:22:53 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@111a0e72
13.02 19:22:53 [Server] INFO inputBufferedPackets=[]
13.02 19:22:53 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6229bfbb
13.02 19:22:53 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@b9187ce
13.02 19:22:53 [Server] INFO hasClosed=false
13.02 19:22:53 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
13.02 19:22:53 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@73ebac29
13.02 19:22:53 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-386,minecraftVersion=1.19.3}
13.02 19:22:53 [Server] INFO library=ProtocolLib v4.8.0
13.02 19:22:53 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1d38e03c
13.02 19:22:53 [Server] INFO knowsServerPackets=true
13.02 19:22:53 [Server] INFO knowsClientPackets=true
13.02 19:22:53 [Server] INFO phaseLoginCount=0
13.02 19:22:53 [Server] INFO phasePlayingCount=4
13.02 19:22:53 [Server] INFO packetCreation=false
13.02 19:22:53 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@46118124
13.02 19:22:53 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@59c37fff
13.02 19:22:53 [Server] INFO hasRecycleDistance=true
13.02 19:22:53 [Server] INFO minecraftVersion=(MC: 1.19.3)
13.02 19:22:53 [Server] INFO debug=false
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO Sender:
13.02 19:22:53 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@4bd4cf44[
13.02 19:22:53 [Server] INFO decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
13.02 19:22:53 [Server] INFO encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
13.02 19:22:53 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@4adf6804
13.02 19:22:53 [Server] INFO player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@271c20f4
13.02 19:22:53 [Server] INFO updated=<null>
13.02 19:22:53 [Server] INFO playerName=<null>
13.02 19:22:53 [Server] INFO playerConnection=<null>
13.02 19:22:53 [Server] INFO networkManager=net.minecraft.network.NetworkManager@7eab21df
13.02 19:22:53 [Server] INFO originalChannel=[id: 0x3225c582, L:/172.17.0.19:25591 - R:/192.99.245.214:50778]
13.02 19:22:53 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@7eab21df, previous=[id: 0x3225c582, L:/172.17.0.19:25591 - R:/192.99.245.214:50778], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2802de75, previousLoaded=true, currentSet=true, forceAccess=true]
13.02 19:22:53 [Server] INFO packetMarker={}
13.02 19:22:53 [Server] INFO currentEvent=<null>
13.02 19:22:53 [Server] INFO finalEvent=<null>
13.02 19:22:53 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6fc57564
13.02 19:22:53 [Server] INFO vanillaDecoder=net.minecraft.network.PacketDecoder@2e70bcd
13.02 19:22:53 [Server] INFO vanillaEncoder=net.minecraft.network.PacketEncoder@5b9c309e
13.02 19:22:53 [Server] INFO finishQueue=[]
13.02 19:22:53 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@46118124
13.02 19:22:53 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@21798b75
13.02 19:22:53 [Server] INFO injected=true
13.02 19:22:53 [Server] INFO closed=false
13.02 19:22:53 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 19, widx: 19, cap: 19)
13.02 19:22:53 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1bfa45f4
13.02 19:22:53 [Server] INFO singleDecode=false
13.02 19:22:53 [Server] INFO first=true
13.02 19:22:53 [Server] INFO firedChannelRead=false
13.02 19:22:53 [Server] INFO selfFiredChannelRead=true
13.02 19:22:53 [Server] INFO decodeState=1
13.02 19:22:53 [Server] INFO discardAfterReads=16
13.02 19:22:53 [Server] INFO numReads=0
13.02 19:22:53 [Server] INFO added=true
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO Version:
13.02 19:22:53 [Server] INFO ProtocolLib v4.8.0
13.02 19:22:53 [Server] INFO Java Version:
13.02 19:22:53 [Server] INFO 17.0.2
13.02 19:22:53 [Server] INFO Server:
13.02 19:22:53 [Server] INFO git-Paper-386 (MC: 1.19.3)
13.02 19:22:53 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@4bd4cf44.
13.02 19:22:53 [Server] ERROR INTERNAL ERROR: Unable to intercept a read client packet.
13.02 19:22:53 [Server] INFO If this problem hasn't already been reported, please open a ticket
13.02 19:22:53 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
13.02 19:22:53 [Server] INFO Stack Trace:
13.02 19:22:53 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
13.02 19:22:53 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
13.02 19:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
13.02 19:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
13.02 19:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
13.02 19:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
13.02 19:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
13.02 19:22:53 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
13.02 19:22:53 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
13.02 19:22:53 [Server] INFO Dump:
13.02 19:22:53 [Server] INFO Parameters: 
13.02 19:22:53 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@4e7ffd6[
13.02 19:22:53 [Server] INFO memoryAddress=140342889330832
13.02 19:22:53 [Server] INFO recyclerHandle=NOOP_HANDLE
13.02 19:22:53 [Server] INFO chunk=Chunk(6e8e7c17: 1%, 24576/4194304)
13.02 19:22:53 [Server] INFO handle=1125929971613696
13.02 19:22:53 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
13.02 19:22:53 [Server] INFO offset=16384
13.02 19:22:53 [Server] INFO length=1
13.02 19:22:53 [Server] INFO maxLength=16
13.02 19:22:53 [Server] INFO cache=io.netty.buffer.PoolThreadCache@25d48ec9
13.02 19:22:53 [Server] INFO tmpNioBuf=<null>
13.02 19:22:53 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
13.02 19:22:53 [Server] INFO refCnt=2
13.02 19:22:53 [Server] INFO readerIndex=1
13.02 19:22:53 [Server] INFO writerIndex=1
13.02 19:22:53 [Server] INFO markedReaderIndex=0
13.02 19:22:53 [Server] INFO markedWriterIndex=0
13.02 19:22:53 [Server] INFO maxCapacity=2147483647
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO manager:
13.02 19:22:53 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@129c2b89[
13.02 19:22:53 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@13bf4dd5
13.02 19:22:53 [Server] INFO packetListeners=[PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=MyPet, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MyPet, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
13.02 19:22:53 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6283403d
13.02 19:22:53 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@111a0e72
13.02 19:22:53 [Server] INFO inputBufferedPackets=[]
13.02 19:22:53 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6229bfbb
13.02 19:22:53 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@b9187ce
13.02 19:22:53 [Server] INFO hasClosed=false
13.02 19:22:53 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
13.02 19:22:53 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@73ebac29
13.02 19:22:53 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-386,minecraftVersion=1.19.3}
13.02 19:22:53 [Server] INFO library=ProtocolLib v4.8.0
13.02 19:22:53 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1d38e03c
13.02 19:22:53 [Server] INFO knowsServerPackets=true
13.02 19:22:53 [Server] INFO knowsClientPackets=true
13.02 19:22:53 [Server] INFO phaseLoginCount=0
13.02 19:22:53 [Server] INFO phasePlayingCount=4
13.02 19:22:53 [Server] INFO packetCreation=false
13.02 19:22:53 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@46118124
13.02 19:22:53 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@59c37fff
13.02 19:22:53 [Server] INFO hasRecycleDistance=true
13.02 19:22:53 [Server] INFO minecraftVersion=(MC: 1.19.3)
13.02 19:22:53 [Server] INFO debug=false
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO Sender:
13.02 19:22:53 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@4bd4cf44[
13.02 19:22:53 [Server] INFO decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
13.02 19:22:53 [Server] INFO encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
13.02 19:22:53 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@4adf6804
13.02 19:22:53 [Server] INFO player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@271c20f4
13.02 19:22:53 [Server] INFO updated=<null>
13.02 19:22:53 [Server] INFO playerName=<null>
13.02 19:22:53 [Server] INFO playerConnection=<null>
13.02 19:22:53 [Server] INFO networkManager=net.minecraft.network.NetworkManager@7eab21df
13.02 19:22:53 [Server] INFO originalChannel=[id: 0x3225c582, L:/172.17.0.19:25591 - R:/192.99.245.214:50778]
13.02 19:22:53 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@7eab21df, previous=[id: 0x3225c582, L:/172.17.0.19:25591 - R:/192.99.245.214:50778], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2802de75, previousLoaded=true, currentSet=true, forceAccess=true]
13.02 19:22:53 [Server] INFO packetMarker={}
13.02 19:22:53 [Server] INFO currentEvent=<null>
13.02 19:22:53 [Server] INFO finalEvent=<null>
13.02 19:22:53 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6fc57564
13.02 19:22:53 [Server] INFO vanillaDecoder=net.minecraft.network.PacketDecoder@2e70bcd
13.02 19:22:53 [Server] INFO vanillaEncoder=net.minecraft.network.PacketEncoder@5b9c309e
13.02 19:22:53 [Server] INFO finishQueue=[]
13.02 19:22:53 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@46118124
13.02 19:22:53 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@21798b75
13.02 19:22:53 [Server] INFO injected=true
13.02 19:22:53 [Server] INFO closed=false
13.02 19:22:53 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
13.02 19:22:53 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1bfa45f4
13.02 19:22:53 [Server] INFO singleDecode=false
13.02 19:22:53 [Server] INFO first=true
13.02 19:22:53 [Server] INFO firedChannelRead=true
13.02 19:22:53 [Server] INFO selfFiredChannelRead=true
13.02 19:22:53 [Server] INFO decodeState=1
13.02 19:22:53 [Server] INFO discardAfterReads=16
13.02 19:22:53 [Server] INFO numReads=0
13.02 19:22:53 [Server] INFO added=true
13.02 19:22:53 [Server] INFO ]
13.02 19:22:53 [Server] INFO Version:
13.02 19:22:53 [Server] INFO ProtocolLib v4.8.0
13.02 19:22:53 [Server] INFO Java Version:
13.02 19:22:53 [Server] INFO 17.0.2
13.02 19:22:53 [Server] INFO Server:
13.02 19:22:53 [Server] INFO git-Paper-386 (MC: 1.19.3)

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
