### ISSUE TITLE
Add TinyProtocol to Maven repository

### ISSUE THREAD

**Issue by MineTheCube** [dmulloy2/ProtocolLib#217]
It would be great if you could add TinyProtocol to your Maven repository so I can shade it directly into my plugin and don't need to copy the sources and reference CraftBukkit.
Thanks in advance. :)

*See [original issue](https://github.com/aadnk/ProtocolLib/issues/59) on aadnk's Github*

**Comment by dmulloy2** [comment]
Added it to the snapshot repo with version 1.0.0-SNAPSHOT

**Comment by MineTheCube** [comment]
Great !
But could you remove `ExamplePugin.class` from it ?

**Comment by dmulloy2** [comment]
I can't imagine one class making much of a difference, but you could always just minimize the jar.

As for dependencies, it doesn't really matter if you depend on Spigot or Spigot-API.

**Comment by Sentropic** [comment]
Is this still up? I tried both `https://repo.dmulloy2.net/repository/public/` and `https://repo.dmulloy2.net/repository/snapshots/`, along with
```
        <dependency>
            <groupId>com.comphenix.tinyprotocol</groupId>
            <artifactId>TinyProtocol</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```
but it's not there.
