### ISSUE TITLE
openlogin

### ISSUE THREAD

**Issue by gambler000** [dmulloy2/ProtocolLib#2175]
I have no idea if this is solved in anything other then 4.8.0 as [aternos.org](https://aternos.org/) has only the  spigot versions from [https://www.spigotmc.org/resources/1997](https://www.spigotmc.org/resources/1997)

**Describe the bug**
message from openlogin to log in gets propably caught by themis as incorrect packet 

resulting in no message recieved and pages of error messages

**To Reproduce**
1. Go to [aternos.org](https://aternos.org/) and signup
2. install paper 
3. install openlogin, themis, protocollib

4. look at your chat and server logs
[logs here](https://mclo.gs/KZKd6g6)

**Expected behavior**
themis and openlogin playing nicely along with each other

**Version Info**
[version 4.8.0 compiled on 4. 3. 2022](https://www.spigotmc.org/resources/protocollib.1997/history)
[/protocol dump](https://pastebin.com/0fpUUh08)

**Additional context**
 would like to see devbuild number something like 4.7.614 - so it is clear if it was implemented after or before certain version

im going to post this also to openlogin issues

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189

**Comment by gambler000** [comment]
the point is that aternos does not allow dev builds (for security reasons), so unless aternos allows dev builds of plugins or protocollib creates a full version from 1.19.3 devbuild this will be unresolved
