### ISSUE TITLE
Paket 78 is destroying servers

### ISSUE THREAD

**Issue by WMythos** [dmulloy2/ProtocolLib#2178]
- [ ] This issue is not solved in a development build

**Describe the bug**
Im not going to describe packs 78 threw as it has been described dozens of time already

I typically gross 1.5k monthly across my bungee network, but due to the packet error corrupting my server I have grossed zero. zero. this error is huge and I just really hope its being worked on. my servers unplayable and I can't seem to figure out a solution. iv hired people to try and nobody can. PLEASE fix this

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2094#issuecomment-1410893495
