### ISSUE TITLE
Has anybody got an idea why i can't import the libraries?

### ISSUE THREAD

**Issue by obv42** [dmulloy2/ProtocolLib#2179]
import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.PacketContainer;

**Comment by TomTeDev** [comment]
Are you using gradle or maven? Are you using mappings? Most of the time issues with imports are on user side rather than plugin. So this question shouldnt be asked here in the first place

**Comment by obv42** [comment]
I'm using maven and no maps

**Comment by TomTeDev** [comment]
Send pom.xml using pastebin or any other common text hosting website

**Comment by obv42** [comment]
https://pastebin.com/pijm5Jbt

**Comment by obv42** [comment]
um..just opened intellj and now it's somehow able to import it
idk what was wrong but anyway
ty
