### ISSUE TITLE
can't see each other

### ISSUE THREAD

**Issue by MclWilly** [dmulloy2/ProtocolLib#218]
hello!
i have a problem with this plugin
when i use this plugin
people can't see each other in my server.
at best,only one can see one.

sorry,poor my english

**Comment by MiniDigger** [comment]
Are you sure that your issue is produced by protocol lib? Try removing it to see if the issue persist.

**Comment by dmulloy2** [comment]
Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by dmulloy2** [comment]
Any more info on this?
