### ISSUE TITLE
Metrics lagging my game??

### ISSUE THREAD

**Issue by Yomamaeatstoes** [dmulloy2/ProtocolLib#2187]
- [ ] This issue is not solved in a development build

**Describe the bug**
Metrics makes lag
**To Reproduce**
1. Go to '...' No idea
2. Click on '....' No idea
3. Scroll down to '....' No idea

**Expected behavior**
For metrics not to create lag
**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
newest dev build
**Additional context**

https://timings.aikar.co/dev/?id=a997c802f21c45868fcd3825901f1cb2

**Comment by Yomamaeatstoes** [comment]
plugins/ProtocolLib/dump-2023-02-22_11.03.06.txt

**Comment by Jeppa** [comment]
> plugins/ProtocolLib/dump-2023-02-22_11.03.06.txt

That is not a link , just the name ;)

**Comment by Yomamaeatstoes** [comment]
oh lmaoo, how do I get the link? Oh after I turned it off I longer got the tps drops and lag spikes
