### ISSUE TITLE
Jenkins unavailable -> 500 Response code

### ISSUE THREAD

**Issue by games647** [dmulloy2/ProtocolLib#219]
Currently your Jenkins instance is unreachable, because of a 500 error.

Error message:

HTTP ERROR: 500

Problem accessing /job/ProtocolLib/. Reason:

    PermGen space

**Comment by dmulloy2** [comment]
It looks like Jenkins periodically runs out of memory. I'm not entirely sure what I can do about that though.

**Comment by games647** [comment]
At least it works for the moment, thanks.
