### ISSUE TITLE
Internal Error: Unable to intercept a read client packet

### ISSUE THREAD

**Issue by notdyLn** [dmulloy2/ProtocolLib#2196]
ERROR(S):
Unable to intercept a read client packet
Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart

ProtocolLib Dump
Timestamp: 02/25/23 14:45:28

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: 3610-Spigot-6198b5a-19df23a (MC: 1.19.2)
Java Version: 17.0.6

ProtocolLib: com.comphenix.protocol.ProtocolLib@7113e45[
  statistics=com.comphenix.protocol.metrics.Statistics@78137a63
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2a45dca0
  packetTask=101
  tickCounter=10882
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@78cd31e4
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@7ea8e684
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@70c51c02
  commandProtocol=com.comphenix.protocol.CommandProtocol@13e6a01b
  commandPacket=com.comphenix.protocol.CommandPacket@17c2de1b
  commandFilter=com.comphenix.protocol.CommandFilter@2e6796a1
  packetLogging=com.comphenix.protocol.PacketLogging@769aaa63
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@505a3ad3
  server=CraftServer{serverName=CraftBukkit,serverVersion=3610-Spigot-6198b5a-19df23a,minecraftVersion=1.19.2}
  file=plugins\ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@51e904c5
  dataFolder=plugins\ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@1954d03e
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins\ProtocolLib\config.yml
  logger=org.bukkit.plugin.PluginLogger@60c32163
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@7f325c14[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@78cd31e4
  packetListeners=[PacketAdapter[plugin=AdvancedNMotd, sending=ListeningWhitelist[priority=NORMAL, packets=[SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2748825f
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@71d797f5
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1c68a727
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@dbbe75f
  hasClosed=false
  classLoader=org.bukkit.plugin.java.PluginClassLoader@1954d03e
  reporter=com.comphenix.protocol.ProtocolLib$1@6e02c6cd
  server=CraftServer{serverName=CraftBukkit,serverVersion=3610-Spigot-6198b5a-19df23a,minecraftVersion=1.19.2}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7aaf561b
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=1
  phasePlayingCount=2
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4ff13f6f
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@17b5528
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.2)
  debug=false
]

Listeners:
ru.namerpro.Protocol.Base.Main@70d8f8[
  privNum=0
  privFile=
  plugin=AdvancedNMotd v9.2.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]]
]
ru.namerpro.Bukkit.Utils.ClientDetectorWrapper@300e2207[
  plugin=AdvancedNMotd v9.2.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
AdvancedNMotd by [NamerPRO]

**Comment by StanByes** [comment]
Same error

**Comment by josmanFL** [comment]
hola, no entiendo mucho de esto pero tengo este mismo error me podrían ayudar

**Comment by ORN-Fox** [comment]
Same error

**Comment by seanfilimon** [comment]
Same Error

**Comment by zonneschijn7** [comment]
same error
