### ISSUE TITLE
[API] The ClientboundPlayerChatPacket internal objects

### ISSUE THREAD

**Issue by Peng1104** [dmulloy2/ProtocolLib#2197]
- [X] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**

Since the release of minecraft 1.19, reading the chat packages has become a problem, the reason behind the problem is the big change that happened in the package, with that there are no wrappers for the new chat objects.

**Describe the solution you'd like**

The creation of Wrappers for the below classes

- PlayerChatMessage
- SignedMessageHeader
- MessageSignature
- SignedMessageBody
- SignedMessageBody$Packet (#a) (1.19.3)
- FilterMask
- ChatMessageContent
- LastSeenMessages
- LastSeenMessages$Packet (#a)

**Describe alternatives you've considered**
Manual reflection. But it would be nice if there is a ProtocolLib way of doing it.

**Additional context**
Objects Structures:

- ClientboundPlayerChatPacket 
   - PlayerChatMessage (1.19-1.19.2)
   - UUID (1.19.3)
   - int (1.19.3)
   - MessageSignature (1.19.3)
   - SignedMessageBody$Packet (#a) (1.19.3)
   - IChatBaseComponent (1.19.3)
   - FilterMask (1.19.3)
   - ChatMessageType$BoundNetwork (#b) 
- PlayerChatMessage (1.19-1.19.2)
   - SignedMessageHeader
   - MessageSignature
   - SignedMessageBody
   - Optional of IChatBaseComponent
   - FilterMask
   - Duration
   - Duration
- SignedMessageHeader (1.19-1.19.2)
   - MessageSignature
   - UUID
- MessageSignature
  - byte[]
- SignedMessageBody
  - ChatMessageContent (1.19-1.19.2)
  - String (1.19.3)
  - Instant
  - long
  - LastSeenMessages
- SignedMessageBody$Packet (#a) (1.19.3)
  - String
  - Instant
  - long
  - LastSeenMessages#a
- ChatMessageContent (1.19-1.19.2)
  - String
  - IChatBaseComponent
- FilterMask
  - BitSet
  - Internal enum "Type" (#a)
- LastSeenMessages
  - List of internal class "Packet" (#a) (1.19-1.19.2)
  - List of MessageSignature (1.19.3)
- LastSeenMessages$Packet (#a)
  - UUID (1.19-1.19.2)
  - MessageSignature (1.19-1.19.2)
  - List of MessageSignature$Packet (#a) (1.19.3)

**Comment by Peng1104** [comment]
Any chance of this been implemented?

**Comment by TechsCode** [comment]
Hey @dmulloy2 could you please help here ? We would really appreciate it. It’s really needed
