### ISSUE TITLE
Unable to access PacketType.Play.Server.SERVER_DATA

### ISSUE THREAD

**Issue by davidjpfeiffer** [dmulloy2/ProtocolLib#2199]
**Describe the bug**
I am including ProtocolLib in my Maven project but I am unable to reference `PacketType.Play.Server.SERVER_DATA` because it does not exist. I am wondering if the repository was not updated correctly for version 4.8.0.

**To Reproduce**
Use this Maven repository:
```
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
```
Use this Maven dependency:
```
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>4.8.0</version>
            <scope>provided</scope>
        </dependency>
```

Try to reference `PacketType.Play.Server.SERVER_DATA` from the code

**Version Info**
4.8.0

**Comment by Peng1104** [comment]
SERVER_DATA exits only on the 5.0.0 version

**Comment by davidjpfeiffer** [comment]
How can I get access to that version? 4.8.0 is the latest version everywhere I look.

**Comment by Peng1104** [comment]
dev builds
