### ISSUE TITLE
Non fatal error occuring when players join, and periodically

### ISSUE THREAD

**Issue by Seraph353** [dmulloy2/ProtocolLib#2217]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't fixed in a recent development build
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link: https://pastebin.com/0r4iUFnQ

Description and relevant errors:
Occured on players first join after the server started, then periodically during play. 
Note: I have removed IP addresses that were shown as they belonged to players

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
