### ISSUE TITLE
1.19.2 Constant error unable to intercept a read client packet

### ISSUE THREAD

**Issue by sini27** [dmulloy2/ProtocolLib#2227]
Tried mulitple different versions of protocollib. Using the latest gives me this error but all of the plugins work and using build 606 won't even let me connect to the server. 
![2023-03-13_22 58 15](https://user-images.githubusercontent.com/127745945/224688911-7dafa2f9-fcf6-4b1c-8009-29fd77253e7e.png)

**Comment by Bud82jp** [comment]
Im getting this as well

**Comment by Olzie-12** [comment]
Use the latest dev build
