### ISSUE TITLE
Compatibility with catserver

### ISSUE THREAD

**Issue by lidashuai-li** [dmulloy2/ProtocolLib#2229]
- [ ] This issue is not solved in a development build

**Describe the bug**
When I use the latest version of catserver to install the latest build, it will fail to load

**To Reproduce**
1. Put protocollib in plugin folder
2. Start Server

**Expected behavior**
Unable to load and reported an error

**Screenshots**
![0N5HY812 {96EHDTXDN$63G](https://user-images.githubusercontent.com/78547426/225172699-ff869968-eecd-4d10-b140-e2cff3f7d980.png)

**Version Info**
5.0.0-SNAPSHOT-b615

**Additional context**
I understand that it is rude to let you compatible with a mixed server, but at present, many excellent plugins are written based on your latest version, so can it be compatible if possible

**Comment by Jeppa** [comment]
For 1.12 servers you should currently NOT use latest build ;(
