### ISSUE TITLE
WrappedDataWatcher.GetByte(int index) throws a NullpointerException if the Byte doesn't exist

### ISSUE THREAD

**Issue by redinzane** [dmulloy2/ProtocolLib#223]
Error with Stacktrace:
http://pastebin.com/nBzVS15L

According to the [JavaDoc](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/wrappers/WrappedDataWatcher.html#getByte(int)) GetByte() should return null if the Byte does not exist at this index. However, in v.4.0.1 of ProtocolLib it insteads throws a NullPointerException when I try to access a byte that does not exist.

**Comment by dmulloy2** [comment]
You should use ````watcher.hasIndex(index)```` before accessing a value. I'll clarify this in the JavaDocs.

**Comment by redinzane** [comment]
It actually worked as documented, returning null, in the past. I discovered this using code I reused from one of aadnk's old plugins.

**Comment by dmulloy2** [comment]
Mojang changed the whole game of data watchers in 1.9, so very little works as it did in the past.

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/242b25eb1ef5f745072023ee8033cc2855e56d03
