### ISSUE TITLE
exception when mining shulker chest

### ISSUE THREAD

**Issue by aaa8881** [dmulloy2/ProtocolLib#2238]
protocollib #615 , pufferfish #61 

https://pastebin.com/qD7v76Jv

player sometimes disconnects when mining shulker chest.
After a while, we found this is caused probably by custom fish item. ( not 100% sure ) 
this is nbt data of a fish item , 
https://imgur.com/a/KljYhhA

unsure if this could be handled in protocollib.

**Comment by Brokkonaut** [comment]
We have the same issues but no custom fish items on our server and use paper instead of pufferfish
