### ISSUE TITLE
Protocollib doesn't startup properly with Java 8, 11 and 16 openj9

### ISSUE THREAD

**Issue by pabloalba16** [dmulloy2/ProtocolLib#2241]
- [X] This issue is not solved in a development build

**Describe the bug**
Latest Protocollib version (5.0.0 builds) doesn't load properly when SWM is also running on the server

**To Reproduce**
1. Go to the jenkins build and download any of the 5.0.0 builds
2. Add Protocollib and start the server with any of those mencioned Java
3. You can see the error at the startup or at the logs

**Expected behavior**

It should not give that error and allow other protollib's depend plugins to also load properly

**Screenshots**

Here's the pastebin with the error

https://pastebin.com/nzCA5k7s
https://pastebin.com/Z2AJrNXJ

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

I can't as it does not load properly, it is the latest build, does not happen on 4.8.0 or previous versions

**Additional context**

My servers are using pterodactyI panel and i tested on both 1.8.9 and .1.12.2 and they display the same error as provided above

**Comment by Jeppa** [comment]
For 1.12 you should still be on 4.8.0...

**Comment by pabloalba16** [comment]
Man it's not my fault that to run plugins that depend on Protocollib i have to use the latest dev build no matter what server version i'm running

**Comment by Jeppa** [comment]
If a plugin that depends on ProtocolLib realy needs the latest dev build, even on servers older than 1.19... then the developer of that plugin did something wrong,  I'm afraid.. :(

Since latest dev builds not yet properly support older versions, the plugin must check for it and only use any new features  with new version...
:(

**Comment by pabloalba16** [comment]
Realised SWM wasn't the problem, it's just the dev builds doesn not support java 8, 11 and 16 openj9 (it does on hotspot)
