### ISSUE TITLE
API Site is Down?

### ISSUE THREAD

**Issue by ItsRainingHP** [dmulloy2/ProtocolLib#2247]
Why is your API down? Is there an ETA on return?

![image](https://user-images.githubusercontent.com/79205731/226208347-dd4b11ec-b89c-4b7d-adb3-1b715ea6a76a.png)

![image](https://user-images.githubusercontent.com/79205731/226208350-8ff4342c-8511-4eb3-a097-c315e578e76e.png)

**Comment by jannickvieluf** [comment]
Same issue for me:
```
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.comphenix.protocol:ProtocolLib:4.8.0.
     Required by:
         project :
      > Could not resolve com.comphenix.protocol:ProtocolLib:4.8.0.
         > Could not get resource 'https://repo.dmulloy2.net/repository/public/com/comphenix/protocol/ProtocolLib/4.8.0/ProtocolLib-4.8.0.pom'.
            > Could not GET 'https://repo.dmulloy2.net/repository/public/com/comphenix/protocol/ProtocolLib/4.8.0/ProtocolLib-4.8.0.pom'. Received status code 503 from server: Service Unavailable
```

**Comment by Olzie-12** [comment]
same issue

**Comment by Roomiiaan** [comment]
Same here! Critical issue!!!

**Comment by EinSchokomuffin** [comment]
Pipeline not working! Needs to be fixed ASAP

**Comment by Olzie-12** [comment]
You can use jitpack btw guys

**Comment by ItsRainingHP** [comment]
> You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0

What about for citizens?

**Comment by Roomiiaan** [comment]
> You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0

Why should I use jitpack? All systems are based on the "main repo". I can't use this.

**Comment by jannickvieluf** [comment]
@Olzie-12 
> You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0

Of course, but I really don't want to change all my projects for that

**Comment by Olzie-12** [comment]
> > You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0
> 
> Why should I use jitpack? All systems are based on the "main repo". I can't use this.

Because they’ve provided the a

> @Olzie-12
> 
> > You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0
> 
> Of course, but I really don't want to change all my projects for that

Fair enough, but if people are finding it as an issue then that’s an alternative for now 🤷‍♂️

**Comment by Olzie-12** [comment]
> > You can use jitpack btw guys https://jitpack.io/#dmulloy2/ProtocolLib/4.8.0
> 
> Why should I use jitpack? All systems are based on the "main repo". I can't use this.

Then you can make it just adapt to jitpack.io and not their main repo. It’s an alternative for now 🤷‍♂️

**Comment by CJCrafter** [comment]
```kotlin
maven { url 'https://jitpack.io' }
```
```kotlin
implementation("com.github.dmulloy2:ProtocolLib:4.8.0")
```

**Comment by Olzie-12** [comment]
> ```kotlin
> ```kotlin
> maven { url 'https://jitpack.io' }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```kotlin
> implementation("com.github.dmulloy2:ProtocolLib:4.8.0")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Of course, this is possible but if this is the "official" solution they should provide this information in the README file and not simply assume that everyone knows what todo
> ```

Well everyone is complaining obviously it’s down, if someone really needed the repository. Then they know what to use, it’s an alternative for now ovviously

**Comment by dmulloy2** [comment]
Jitpack is an officially supported alternative if the main repo goes down. Repo should be back up. Will investigate further why it was down and try to mitigate it in the future
