### ISSUE TITLE
error plugin

### ISSUE THREAD

**Issue by CREEPER974** [dmulloy2/ProtocolLib#2250]
https://mclo.gs/CyN0X8G

good afternoon lately the protocollib has been giving errors and the error I'm talking about is in that link to put the complete error I'm not right-handed in github so I do it this way
i want to solve

**Comment by CREEPER974** [comment]
good afternoon lately the protocollib has been giving errors and the error I'm talking about is in that link to put the complete error I'm not right-handed in github so I do it this way
i want to solve

**Comment by jannickvieluf** [comment]
You're using 1.19.4 and I don't know if it is supported at all but for 1.19.3 and maybe also 1.19.4 you need to use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) as described here: https://www.spigotmc.org/resources/protocollib.1997/

**Comment by BySwiizen** [comment]
> You're using 1.19.4 and I don't know if it is supported at all right now.
> 
> But for 1.19.3 and maybe also 1.19.4 you need to use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) as described here: https://www.spigotmc.org/resources/protocollib.1997/

There are a lot of bugs in this version...
