### ISSUE TITLE
It told me to paste this

### ISSUE THREAD

**Issue by EssJay2105** [dmulloy2/ProtocolLib#2254]
<html>
<body>

Stack Trace:
4255 | java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
4256 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
4257 | at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
4258 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
4259 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
4260 | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
4261 | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
4262 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
4263 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4264 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4265 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4266 | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
4267 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4268 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4269 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4270 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
4271 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
4272 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4273 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4274 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4275 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
4276 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4277 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4278 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4279 | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
4280 | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
4281 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4282 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4283 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4284 | at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
4285 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4286 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4287 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4288 | at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
4289 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4290 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4291 | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
4292 | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
4293 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
4294 | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
4295 | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
4296 | at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
4297 | at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
4298 | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
4299 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
4300 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
4301 | at java.base/java.lang.Thread.run(Unknown Source)
4302 | Dump:
4303 | Parameters:
4304 | io.netty.buffer.PooledUnsafeDirectByteBuf@21332198[
4305 | memoryAddress=140583206435008
4306 | recyclerHandle=io.netty.util.Recycler$DefaultHandle@336f9a0a
4307 | chunk=Chunk(262686a: 31%, 1286144/4194304)
4308 | handle=55732075453480961
4309 | memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
4310 | offset=811264
4311 | length=256
4312 | maxLength=256
4313 | cache=io.netty.buffer.PoolThreadCache@23b3692b
4314 | tmpNioBuf=<null>
4315 | allocator=PooledByteBufAllocator(directByDefault: true)
4316 | refCnt=2
4317 | readerIndex=34
4318 | writerIndex=34
4319 | markedReaderIndex=0
4320 | markedWriterIndex=0
4321 | maxCapacity=2147483647
4322 | ]
4323 | manager:
4324 | com.comphenix.protocol.injector.PacketFilterManager@5d05c8e7[
4325 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4cb5da15
4326 | packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LoginSecurity, sending=ListeningWhitelist[priority=LOW, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], WINDOW_DATA[class=ClientboundCustomChatCompletionsPacket, id=21], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=25]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]]]
4327 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@74770899
4328 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@52675670
4329 | inputBufferedPackets=[]
4330 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2156fe2b
4331 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4351fd66
4332 | hasClosed=false
4333 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
4334 | reporter=com.comphenix.protocol.ProtocolLib$1@f2e1655
4335 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
4336 | library=ProtocolLib v4.8.0
4337 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@71a30879
4338 | knowsServerPackets=true
4339 | knowsClientPackets=true
4340 | phaseLoginCount=0
4341 | phasePlayingCount=10
4342 | packetCreation=true
4343 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5c72e544
4344 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4a3e756d
4345 | hasRecycleDistance=true
4346 | minecraftVersion=(MC: 1.19.2)
4347 | debug=false
4348 | ]
4349 | Sender:
4350 | com.comphenix.protocol.injector.netty.ChannelInjector@3add93e1[
4351 | decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
4352 | encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
4353 | factory=com.comphenix.protocol.injector.netty.InjectionFactory@23e8baa8
4354 | player=CraftPlayer{name=EssJay3702}
4355 | updated=<null>
4356 | playerName=EssJay3702
4357 | playerConnection=net.minecraft.server.network.PlayerConnection@73aa0fe7
4358 | networkManager=net.minecraft.network.NetworkManager@1976e1d5
4359 | originalChannel=[id: 0x85aba077, L:/172.20.0.10:44212 - R:/178.88.7.69:62078]
4360 | channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@1976e1d5, previous=[id: 0x85aba077, L:/172.20.0.10:44212 - R:/178.88.7.69:62078], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@768e3a34, previousLoaded=true, currentSet=true, forceAccess=true]
4361 | packetMarker={}
4362 | currentEvent=<null>
4363 | finalEvent=<null>
4364 | unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@44a434b5
4365 | vanillaDecoder=net.minecraft.network.PacketDecoder@5a445444
4366 | vanillaEncoder=net.minecraft.network.PacketEncoder@5bb3ec67
4367 | finishQueue=[]
4368 | channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5c72e544
4369 | processor=com.comphenix.protocol.injector.NetworkProcessor@390fb40b
4370 | injected=true
4371 | closed=false
4372 | cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 256)
4373 | cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4111211a
4374 | singleDecode=false
4375 | first=true
4376 | firedChannelRead=false
4377 | selfFiredChannelRead=true
4378 | decodeState=1
4379 | discardAfterReads=16
4380 | numReads=0
4381 | added=true
4382 | ]
4383 | Version:
4384 | ProtocolLib v4.8.0
4385 | Java Version:
4386 | 17.0.4.1
4387 | Server:
4388 | git-Paper-307 (MC: 1.19.2)
4389

<br class="Apple-interchange-newline">
</body>
</html>Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@21332198[
      memoryAddress=140583206435008
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@336f9a0a
      chunk=Chunk(262686a: 31%, 1286144/419[4304](https://aternos.org/log/#L4304))
      handle=55732075453480961
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=811264
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@23b3692b
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5d05c8e7[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4cb5da15
        packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LoginSecurity, sending=ListeningWhitelist[priority=LOW, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], WINDOW_DATA[class=ClientboundCustomChatCompletionsPacket, id=21], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=25]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@74770899
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@52675670
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2156fe2b
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@[4351](https://aternos.org/log/#L4351)fd66
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@f2e1655
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@71a30879
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5c72e544
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4a3e756d
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@3add93e1[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@23e8baa8
      player=CraftPlayer{name=EssJay3702}
      updated=<null>
      playerName=EssJay3702
      playerConnection=net.minecraft.server.network.PlayerConnection@73aa0fe7
      networkManager=net.minecraft.network.NetworkManager@1976e1d5
      originalChannel=[id: 0x85aba077, L:/172.20.0.10:44212 - R:/178.88.7.69:62078]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@1976e1d5, previous=[id: 0x85aba077, L:/172.20.0.10:44212 - R:/178.88.7.69:62078], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@768e3a34, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@44a434b5
      vanillaDecoder=net.minecraft.network.PacketDecoder@5a445444
      vanillaEncoder=net.minecraft.network.PacketEncoder@5bb3ec67
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5c72e544
      processor=com.comphenix.protocol.injector.NetworkProcessor@390fb40b
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4111211a
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    git-Paper-307 (MC: 1.19.2)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
