### ISSUE TITLE
1.19.4 GameProfile issue

### ISSUE THREAD

**Issue by naickkk** [dmulloy2/ProtocolLib#2256]
Listen a ClientboundPlayerInfoUpdatePacket

![image](https://user-images.githubusercontent.com/91740990/227602331-0c34fc34-b3d2-44b7-9e66-f5f681b8a4c9.png)

ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b618
Bukkit Version: 1.19.4-R0.1-SNAPSHOT
Server Version: git-Paper-466 (MC: 1.19.4)
Java Version: 17.0.2

**Comment by lukalt** [comment]
What's your code? Did the same code work on 1.19.3?

**Comment by dmulloy2** [comment]
Typically FieldAccessExceptions where the index 0 is out of bounds for length 0 means that field no longer exists. Hard to say without looking at code
