### ISSUE TITLE
i installed the latest version yet this appears when i load the server, this spam for like 4 - 6 times

### ISSUE THREAD

**Issue by Kentakiprayd** [dmulloy2/ProtocolLib#2259]
![image](https://user-images.githubusercontent.com/121296802/227700819-f9be7b7e-f12c-4961-871c-70978d90fced.png)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
