### ISSUE TITLE
Can't see eachother and tablist is empty.

### ISSUE THREAD

**Issue by WatchAc** [dmulloy2/ProtocolLib#226]
Debug paste link: http://pastebin.com/ELiCJGY6

Description and relevant errors: Hello , I've installed ProtocolLib first for a tab plugin because it had it on the dependencies list.I saw that the players were all invisible and the tab was empty , I uninstalled all but protocol lib.Still the same error . When I uninstalled protocol lib the error dissapeared. Same happened today with the protocol lib plugin with a disguise one. I'm using spigot 1.8.8 lastest version , and the lastest compatible version of protocollib. Can someone please help me ?

**Comment by dmulloy2** [comment]
Pretty sure this was something with AuthMe. Try updating it.
