### ISSUE TITLE
https://i.imgur.com/WBvCJVa.png

### ISSUE THREAD

**Issue by PacketL0st** [dmulloy2/ProtocolLib#2262]
**Make sure you're doing the following**
- [ X] You're using the latest build for your server version
- [ ?] This isn't an issue caused by another plugin
- [X ] You've checked for duplicate issues
- [X ] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
Is this a bug or is there another reason this is happening?
https://i.imgur.com/WBvCJVa.png

**Expected behavior**
The head of my skin is sideways but when I remove Protocol Lib, it isn't. Could this be caused by another plugin?

**Comment by Jeppa** [comment]
I don't get it.. hmmm

**Comment by PacketL0st** [comment]
My skin's face is only visually messed up whenever joining my own server with protocol lib on it. After removing protocol Lib, I no longer have this issue. Whenever I'm in vanish mode, my skin's face is fine but whenever unvanishing, it becomes messed up again. Could this be another plugin that's dependant on protocol lib messing this up?
