### ISSUE TITLE
Build #616 download link broken/missing.

### ISSUE THREAD

**Issue by NMLEthereal** [dmulloy2/ProtocolLib#2269]
Disregarding the template due to the nature of the issue. Reporting this directly here to ensure it is seen.

Build in question is #616 ; https://ci.dmulloy2.net/job/ProtocolLib/616/artifact/target/ProtocolLib.jar

The link is broken and the download is non-existent. Cheers ^^

**Comment by dmulloy2** [comment]
shoot. it probably got auto pruned by jenkins. try with the latest build and report any issues. i could also try to rebuild it if it's too broken

**Comment by Ibotmealot** [comment]
@dmulloy2 Broke something with supervanish that is spamming the hell out of my console, but don't know if this more of a super vanish thing or a ProtocolLib thing. https://mclo.gs/gaEZAcj

**Comment by NMLEthereal** [comment]
Hi, no the latest build does not work for me. It crashes with BetonQuest (1.19.3) and they asked me to downgrade to #612 (I suppose #616 would work as well?)

(#624 leaves issues)

**Comment by Vliegenier04** [comment]
It seems PremiumVanish, as well as Citizens is broken in any other version than #616, but that download link is indeed broken. Would love to see an updated link <3

**Comment by dmulloy2** [comment]
@Ibotmealot i think that error was fixed in the most recent build

**Comment by dmulloy2** [comment]
i will rebuild 616

@NMLEthereal  @Vliegenier04  could you guys open issues for those bugs? i would like to restore backwards compatibility in the near future

**Comment by dmulloy2** [comment]
https://ci.dmulloy2.net/userContent/ProtocolLib-616.jar

**Comment by Nutmegan** [comment]
> 

Same issue for me with the 616 not registering with the correct snapshot number

[07:24:39 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.0.0-SNAPSHOT
