### ISSUE TITLE
ENTITY_EQUIPMENT packet contains incorrect data

### ISSUE THREAD

**Issue by jd1378** [dmulloy2/ProtocolLib#227]
ENTITY_EQUIPMENT packet first index (0) always return BOW .

**Comment by dmulloy2** [comment]
Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by jd1378** [comment]
http://pastebin.com/zHcr5wLX

**Comment by jd1378** [comment]
im getting the item in mainhand using this :

**Comment by jd1378** [comment]
im using FakeEquipment class , and getting this crash on console . 
hope this helps : 
http://pastebin.com/ma25VVHz

**Comment by dmulloy2** [comment]
FakeEquipment is outdated since slots were changed in 1.9. You'll have to update it to account for the changes in 1.9.

**Comment by jd1378** [comment]
can you give me an example ?
the problem is not the slots , the only slot added is main hand that is 0 and off hand 1 and i've added them to my code , the problem is every which one i try to get returns bow !

**Comment by jd1378** [comment]
i found the problem , thanks .
