### ISSUE TITLE
(java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer)

### ISSUE THREAD

**Issue by ljberrios** [dmulloy2/ProtocolLib#228]
Error Cannot perform automatic updates. (java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer) occured in ProtocolLib v3.6.5.
23.06 17:18:19 [Server] ERROR INTERNAL ERROR: Cannot perform automatic updates.
23.06 17:18:19 [Server] INFO If this problem hasn't already been reported, please open a ticket
23.06 17:18:19 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
23.06 17:18:19 [Server] INFO Stack Trace:
23.06 17:18:19 [Server] INFO java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
23.06 17:18:19 [Server] INFO at com.comphenix.protocol.ProtocolConfig.getAutoDelay(ProtocolConfig.java:319)
23.06 17:18:19 [Server] INFO at com.comphenix.protocol.ProtocolLibrary.checkUpdates(ProtocolLibrary.java:612)
23.06 17:18:19 [Server] INFO at com.comphenix.protocol.ProtocolLibrary.access$700(ProtocolLibrary.java:68)
23.06 17:18:19 [Server] INFO at com.comphenix.protocol.ProtocolLibrary$3.run(ProtocolLibrary.java:583)
23.06 17:18:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
23.06 17:18:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
23.06 17:18:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
23.06 17:18:19 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
23.06 17:18:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
23.06 17:18:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
23.06 17:18:19 [Server] INFO at java.lang.Thread.run(Thread.java:745)

**Comment by dmulloy2** [comment]
I would just turn it off, especially if you're using an old version as it is.
