### ISSUE TITLE
Folia support for ProtocolLib?

### ISSUE THREAD

**Issue by Agaloth** [dmulloy2/ProtocolLib#2281]
Here is the repo link: https://github.com/PaperMC/Folia

**__Here is a summary of everything made with ChatGPT to save some time:__**

__For plugin developers, there are a few key takeaways from the given text:__

1. Folia introduces regionised multithreading, which means that plugins will require modification to function properly. Plugin developers should expect compatibility with existing plugins to be at zero.

2. Folia introduces new API additions, such as the RegionisedScheduler and EntityScheduler, which can help plugins run on the correct thread context.

3. To ensure compatibility with Folia, plugin developers must mark their plugin as compatible by placing "folia-supported: true" in the plugin.yml file. Additionally, plugins must take advantage of the RegionisedScheduler and EntityScheduler API to ensure correct behavior.

4. Plugins should not assume that they can access or modify data in other regions, as Folia regions tick in parallel and do not share data. Plugin developers should take advantage of the upcoming thread-check API to ensure correct behavior.

5. There are currently broken API, including the scoreboard API, and planned API changes, such as super aggressive thread checks, which may impact plugin development.

Overall, plugin developers should be prepared for significant changes in their plugins to ensure compatibility with Folia. They should take advantage of the new API additions and mark their plugin as compatible to ensure correct behavior. Additionally, they should be aware of the limitations and rules of Folia's regionised multithreading to avoid bugs and errors in their plugins.

**Comment by dmulloy2** [comment]
honestly ProtocolLib will probably at least mostly support it based on that description unless they made substantial changes to the network stack. plugins using PL may have some trouble with the threading though

**Comment by Agaloth** [comment]
I see, thanks a lot for the response. Let me know if there is anything I can do to run tests and let you guys know in that thread for any issues that appears.

**Comment by dmulloy2** [comment]
plan on giving it a try soon so i will keep this thread updated

**Comment by LOOHP** [comment]
Probably only scheduler calls like `Bukkit.getScheudler()...` need to be addressed.

**Comment by mani1232** [comment]
Hehe
https://github.com/dmulloy2/ProtocolLib/pull/2346

**Comment by gavenda** [comment]
Initial Folia support (#2346) has parts that still uses BukkitScheduler:

https://github.com/dmulloy2/ProtocolLib/blob/65a9ef5acf00b978bd605090790a638384769c1c/src/main/java/com/comphenix/protocol/async/AsyncFilterManager.java#L343-L345

This is a given since its initial support, just mentioning it.
