### ISSUE TITLE
Build for 1.19.3 not available?

### ISSUE THREAD

**Issue by CerialPvP** [dmulloy2/ProtocolLib#2284]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
none

Description and relevant errors:
On the Spigot page, the 1.19.3 build is no longer available. What build should I use for 1.19.3?

**Comment by Jeppa** [comment]
Here the download works...

**Comment by dmulloy2** [comment]
latest dev build for 1.19.3

**Comment by CerialPvP** [comment]
> latest dev build https://ci.dmulloy2.net/job/ProtocolLib

I tried that, but when I download it, it spams me with packet errors
