### ISSUE TITLE
Server Crashing with alot of Console Spam

### ISSUE THREAD

**Issue by CreeperBois** [dmulloy2/ProtocolLib#2286]
- [ ] This issue is not solved in a development build

**Describe the bug**
The server keep crashing.

**To Reproduce**
-  Start the server with these plugins with default config on PaperMC 1.19.1:
CMILib,Coins,EconomyShopGUI,EssentialsX - Chat,Protect,Spawn,Floodgate,Geyser,HolographicDisplays,Jobs Reborn, P-Lifesteal,LuckPerms,nLogin,OneplayerSleep,OpeNLogin,ProtocolLib,SkinsRestorer,Themis,Vault,ViaVersion,ViaBackWards,WorldEdit,World Guard

**Expected behavior**
Start the Server Normally

**Version Info**
Cant the server dont start 

Server Log:
https://mclo.gs/ePAEG18

**Comment by lukalt** [comment]
You are using a ProtocolLib version thats incompatible with MC 1.19.1. Use this build: https://ci.dmulloy2.net/job/ProtocolLib/606/

**Comment by CreeperBois** [comment]
is this version on Spigot?

**Comment by lukalt** [comment]
No, only dev builds are currently available for 1.19 or later. However, the required builds are linked at the top of the SpigotMC page: https://www.spigotmc.org/resources/protocollib.1997/ @CreeperBois
