### ISSUE TITLE
ServerPingRecord initializer race condition

### ISSUE THREAD

**Issue by electronicboy** [dmulloy2/ProtocolLib#2289]
- [x] This issue is not solved in a development build

**Describe the bug**
https://github.com/dmulloy2/ProtocolLib/blob/fb2075b774634bff12f2b451bed27e3d1608b31a/src/main/java/com/comphenix/protocol/wrappers/ping/ServerPingRecord.java#L33

This initiaizer code is marking stuff as initialised before it actually is, thus causing a potential race condition when multiple threads try to decode this packet
https://gist.github.com/electronicboy/fc7dada07007ca6e0b1d12a29e2d7d21

**To Reproduce**
Multiple pings early during startup

**Expected behavior**

**Screenshots**

**Version Info**
https://paste.gg/p/anonymous/8a9b3389a2154946bd1ed3ce800e9366/files/71128597b1f64714b4f2b9020f163e54/raw

https://github.com/dmulloy2/ProtocolLib/commit/fb2075b774634bff12f2b451bed27e3d1608b31a

**Additional context**
reporting for a friend, can get additional info if needed, but, very unlikely

**Comment by andrewkm** [comment]
This has been causing us quite a bit of issues with PremiumVanish @dmulloy2 
Example: https://pastebin.com/raw/xKnnWg3q
