### ISSUE TITLE
NullPointerException when call PacketFilterManager.updateEntity

### ISSUE THREAD

**Issue by mics8128** [dmulloy2/ProtocolLib#229]
Make sure you've done the following:
- [x] You're using the latest build for your server version (b296)
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

Debug paste link:
[errorlog](https://gist.github.com/mics8128/46550d48dda69dd551012616ee2eb333)

Description and relevant errors:
this error will show when plugin call showEntity in [this class](https://github.com/mics8128/NoMoreESP/blob/master/src/main/java/tw/mics/spigot/plugin/nomoreesp/EntityHider.java).
but i check all parameter is not null, 
and running function in bukkit sync scheduler.

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by mics8128** [comment]
http://pastebin.com/5s0xva0D

**Comment by dmulloy2** [comment]
Run the latest dev build and provide the errors from it.

**Comment by mics8128** [comment]
http://pastebin.com/HjmunSrV

**Comment by mics8128** [comment]
it never happen again when i check entity isdead before update entity :)
sorry for my mistake.
