### ISSUE TITLE
[ERROR]: Packet encoding of packet ID 78 threw (skippable? false) randomly kick players

### ISSUE THREAD

**Issue by Timoti11** [dmulloy2/ProtocolLib#2291]
- [x] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Download most recent version of ProtocolLib
2. Install last build 1.19.4 (with 1.19.3 and older Protocol same issue)
3. Randomly when somebody open/drop/break a shulker server kicks all players near the 'zone'
4. [See errors in console](https://pastebin.com/txUe01aw)

**Expected behavior**
Players don't kick

**Screenshots**
N/A - Everything required is in error log

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/yBugssNN)

**Additional context**

**TAB**
 ```
 unlimited-nametag-mode:
    enabled: false
```

**Comment by MCZQ** [comment]
Hello, I also have this problem, can you solve it? If you are a Chinese, Qing add my QQ3128608670, if you are a foreigner, please help me in this post, thank you!

**Comment by lukalt** [comment]
Hi, based on the log and the ProtocolLib Version Info, I do not see how ProtocolLib could be causing this issue. I see a couple of 3rd party plugins that interfere with the Netty Pipeline, maybe one of the is causing the problem.

Could you please check if the problem persists if you use no other plugin except for ProtocolLib?

Also, try to remove the AniPopPup Plugin (`com.github.kaspiandev.antipopup`). According to the package name, it should support Minecraft 1.19.3 but you are using a 1.19.4 server.
