### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by CrazyCraft88** [dmulloy2/ProtocolLib#2296]
Wath is this?..  :S  
Who is the Problem...

Protocollib. Fehler
manager:
      com.comphenix.protocol.injector.PacketFilterManager@6d453bdb[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4204b288
        packetListeners=[PacketAdapter[plugin=MCPerks, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PluginHiderPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PluginHiderPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6185ee0c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@495180a9
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@d8ee1bb
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6af99270
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@7dd26a1
        reporter=com.comphenix.protocol.ProtocolLib$1@2442e4ad
        server=CraftServer{serverName=CraftBukkit,serverVersion=3712-Spigot-b31949f-be8682a,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1b2acaec
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@39496861
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@31a87f5a
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2f9f8f12[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1478443b
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@3838eed5
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@543fa242
      originalChannel=[id: 0xd8b80790, L:/185.239.238.89:25565 - R:/109.123.240.84:34038]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@543fa242, previous=[id: 0xd8b80790, L:/185.239.238.89:25565 - R:/109.123.240.84:34038], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7a04f7a3, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@535f070
      vanillaDecoder=net.minecraft.network.PacketDecoder@2cb16f26
      vanillaEncoder=net.minecraft.network.PacketEncoder@57cc462
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@39496861
      processor=com.comphenix.protocol.injector.NetworkProcessor@72845f92
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 21, widx: 21, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@2f7872ab
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    3712-Spigot-b31949f-be8682a (MC: 1.19.4)

**Comment by Nutmegan** [comment]
Your protocolLib version is out of date for minecraft 1.19.4.
Download a more updated version that supports your server version here
https://ci.dmulloy2.net/job/ProtocolLib/
