### ISSUE TITLE
SEVERE

### ISSUE THREAD

**Issue by Donitovan** [dmulloy2/ProtocolLib#230]
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

Debug paste link: http://pastebin.com/uKMXQV0Z

Description and relevant errors: https://gyazo.com/26da7618d3360b0d727ec2de6f9b0204 (screenshot) 

I'm using an unofficial launcher of minecraft

**Comment by Donitovan** [comment]
With an other version of protocollib : http://pastebin.com/88rmCntv

**Comment by dmulloy2** [comment]
ProtocolLib does not support unofficial launchers, because they cause errors like these.
