### ISSUE TITLE
com.comphenix.protocol 

### ISSUE THREAD

**Issue by Anonventions** [dmulloy2/ProtocolLib#2301]
**Make sure you're doing the following**
- [v] You're using the latest build for your server version
- [v] This isn't an issue caused by another plugin
- [v] You've checked for duplicate issues
- [v] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
How do I exactly fix the error: Dependency 'com.comphenix.protocol:ProtocolLib:4.7.1' not found

**API method(s) used**
List what API method(s) you're using
1. PaperAPI
2. ProtocolLibAPI

**Expected behavior**
My pom.xml file should've supported the com.comphenix.protocol so it can import right on the code, but it seems to showcase the error all the time.

**Code**
If applicable, add relevant code from your project
import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.ProtocolManager;
import com.comphenix.protocol.events.PacketContainer;
import com.comphenix.protocol.wrappers.PlayerInfoData;

**Additional context**
The code i'm working on is for 1.18.2 and i tried to use the latest versions/searched for the latest repo, not sure why it's giving me this error.

**Comment by DCUGITHUBZONE** [comment]
used latest versions/tried diff versions on it, repo might be issue though, not sure where to find/locate the correct repo for it.
