### ISSUE TITLE
red error told me to report

### ISSUE THREAD

**Issue by bradau2008** [dmulloy2/ProtocolLib#2305]
allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@64d10bf0[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4794b71c
        packetListeners=[PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@43af5f46]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@32c9bebf
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@564b8417
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3aa99ba5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@58e7f7bb
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2999c425
        reporter=com.comphenix.protocol.ProtocolLib$1@2724965e
        server=CraftServer{serverName=CraftBukkit,serverVersion=3566-Spigot-584b459-c379a6b,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5b47173f
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5f982b05
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3043e544
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@465864a4[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@577e4979
      player=CraftPlayer{name=SeaInk}
      updated=<null>
      playerName=SeaInk
      playerConnection=net.minecraft.server.network.PlayerConnection@13cc7c93
      networkManager=net.minecraft.network.NetworkManager@7d37e97b
      originalChannel=[id: 0xef932351, L:/240.4.54.69:25575 - R:/240.4.0.168:55404]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@7d37e97b, previous=[id: 0xef932351, L:/240.4.54.69:25575 - R:/240.4.0.168:55404], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@c9f09e9, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@967319a
      vanillaDecoder=net.minecraft.network.PacketDecoder@4b596dfc
      vanillaEncoder=net.minecraft.network.PacketEncoder@6a0eba6f
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5f982b05
      processor=com.comphenix.protocol.injector.NetworkProcessor@2e713f38
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@3c252310
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    3566-Spigot-584b459-c379a6b (MC: 1.19.2)

**Comment by lukalt** [comment]
You are using the wrong version of ProtocolLib. Use https://ci.dmulloy2.net/job/ProtocolLib/606/ for 1.19.2 support.
