### ISSUE TITLE
Bug report regarding the use of ProtocolLib on 1.19.2 servers！

### ISSUE THREAD

**Issue by MCZQ** [dmulloy2/ProtocolLib#2306]
Sorry to bother you, but when I was using ProtocolLib, a strange thing happened, when one player placed some sign around and another player teleported or approached this player, one of the players was kicked off the server (similar to a kick?).

When I removed ProtocolLib, the problem was solved. But ProtocolLib is a good plugin for my server！

I tried ProtocolLib's versions 606, 626, 627, 628, 629, 630 and all had the problem!

I ended up switching to version 4.8.0 and found that the issue did not occur, but it is known that version 4.8.0 does little to work for plugins for 1.19.2.

So, I hope that the author, as well as all the strong people, will help me solve this problem! The following are the server background errors and player-side information：
![8b4804ea3b0bf823209ae1ff01fc851](https://user-images.githubusercontent.com/56064852/230156480-4caa1857-b380-462b-b2d4-0780fe5896ea.png)
![SUGM7RD448}JKAWPQN ~511](https://user-images.githubusercontent.com/56064852/230156916-c35a8fe4-697c-4cc2-933b-45c261543176.png)

**Comment by lukalt** [comment]
Please share your complete log and the protocollib dump
