### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by maximina16** [dmulloy2/ProtocolLib#2308]
- [ yes ] This issue is not solved in a development build

**Describe the bug**
Everytime I spawn a mythicmob it crashes

**Version Info**
https://pastebin.com/rGZXaeu5

**Additional context**
https://pastebin.com/MeWBpetj

**Comment by dmulloy2** [comment]
Try this build: https://github.com/lukalt/ProtocolLib/suites/11944629428/artifacts/626109069 and keep us posted on the output (cc @lukalt)

**Comment by maximina16** [comment]
it seems fixed

**Comment by lukalt** [comment]
> > Try this build: https://github.com/lukalt/ProtocolLib/suites/11944629428/artifacts/626109069 and keep us posted on the output (cc @lukalt)
> 
> I've got exact the same error and this version fixes that. But it breaks a lot of other plugins using protocollib.

Do you mean that the changes from my version introduced additional bugs? The changes have been merged into the master of ProtocolLib today, so the latest ProtocolLib version should fix the problem.

**Comment by Dagrond** [comment]
> > > Try this build: https://github.com/lukalt/ProtocolLib/suites/11944629428/artifacts/626109069 and keep us posted on the output (cc @lukalt)
> > 
> > 
> > I've got exact the same error and this version fixes that. But it breaks a lot of other plugins using protocollib.
> 
> Do you mean that the changes from my version introduced additional bugs? The changes have been merged into the master of ProtocolLib today, so the latest ProtocolLib version should fix the problem.

Well, that version did cause some problems with Viaversion and vulcan, but after installing the latest dev build, all seems to be fixed, I get no error and all plugins are working fine.
