### ISSUE TITLE
Idk, Help(?)

### ISSUE THREAD

**Issue by DCUGITHUBZONE** [dmulloy2/ProtocolLib#2309]
**Make sure you're doing the following**
- [done ] You're using the latest build for your server version
- [ done] This isn't an issue caused by another plugin
- [done ] You've checked for duplicate issues
- [ done] You didn't use `/reload`

**Describe the question**
So I'm trying to create a skin plugin, and I'm using Protocolib to make it use a skin-folder set in my plugin

**API method(s) used**
Not sure how to explain it [not native in english and started newly coding...]

**Expected behavior**
For it to take the skin from the folder and apply it on my base-skin/change my skin

**Code**
I'm not sure what this means

**Additional context**
[23:38:09 INFO]: Axmon issued server command: /wardrobeclothes:clothes equip clothes
[23:38:09 INFO]: [WardrobeClothes] Applying skin: clothes to player Axmon
[23:38:09 ERROR]: [WardrobeClothes] ProtocolManager is null! [I have fixed this 4534594534 times in my code so it doesn't load before protocolib and etc etc, but idk anymore]

**Comment by DCUGITHUBZONE** [comment]
Thin the APIs are these for this input:

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.ProtocolManager;
import com.comphenix.protocol.events.PacketContainer;
import com.comphenix.protocol.wrappers.EnumWrappers;
import com.comphenix.protocol.wrappers.PlayerInfoData;
import com.comphenix.protocol.wrappers.WrappedChatComponent;
import com.comphenix.protocol.wrappers.WrappedGameProfile;
import com.comphenix.protocol.wrappers.WrappedSignedProperty;

**Comment by lukalt** [comment]
In order to help you, you need to share your Java code. I guess you are not using the API correctly.

**Comment by DCUGITHUBZONE** [comment]
I ended up fixing it after removing some unnecessary bits from my main-class which I didn't see the first time, sorry for the bother
