### ISSUE TITLE
Scoreboard Issue

### ISSUE THREAD

**Issue by FlyraXD** [dmulloy2/ProtocolLib#2314]
- [x] This issue is not solved in a development build

**Describe the bug**
For some reason when I use the latest version of ProtocolLib my Scoreboard bugs out, I use https://github.com/ThatKawaiiSam/Assemble 's Scoreboard API That supports 32 Letters each line so I'm guessing its not a API issue hence me creating this Bug, My Scoreboards Lines seem to glitch out and then if you have more timers/things on your scoreboard it comes back, this mostly happens for 1.7 players, I'm using the latest version of ViaVer,Rewind

No ERROR

**Expected behavior**
Scoreboard bugging out lines bugging out, glitching etc

**Screenshots**
(Default Scoreboard: https://gyazo.com/89af79f454b67b1910de00a311e131d7) [ProtocolLib 4.8.0]

Bugged Scoreboard 
https://gyazo.com/70d8a98c813186ad274acc25138116fb
https://gyazo.com/883198bba99fad1b0c48ba38793befaf
https://gyazo.com/36d393aa6324dad998cd1e275b25dd3e
https://gyazo.com/5e7b7c51f4c18dff56ec5425232421bb

**Version Info**
5.0.0 ProtocolLib / ProtocolDump (https://hastebin.com/share/zotiratuqa.ruby)

**Additional context**
Scoreboard seems to be working fine on version 4.8.0, of ProtcolLib

**Comment by lukalt** [comment]
The link to the protocol dump does not work. Also, which server version are you using?
