### ISSUE TITLE
1.9.4 and Protocollib 4.0.1 - On ping event, on server join and all packet events errors

### ISSUE THREAD

**Issue by unlemci** [dmulloy2/ProtocolLib#232]
Hello, Original Spigot 1.9.4 and Protocollib 4.0.1 gives error on when i ping server, join to server and all packet events...

Here is my /protocol dump:
http://hastebin.com/repesidoqi.sm

Is it normal?

**Comment by dmulloy2** [comment]
Can you provide the error(s)?

**Comment by unlemci** [comment]
Yes i can provide erros. What you want testing things from me?

**Comment by dmulloy2** [comment]
I just need all the _different_ errors thrown

**Comment by unlemci** [comment]
Here is my log with all errors:

http://hastebin.com/mavilaselu.hs

I pinged my server and getting error, i joined my server and getting a lot of error...

Maybe Certain locales (Turkish) won't work with 1.9.4?

**Comment by dmulloy2** [comment]
Errors like these _generally_ happen with non-Build Tools versions of Spigot. Did you use Build Tools?

**Comment by unlemci** [comment]
Yes i used Build Tools to download Original Spigot 1.9.4. But not about Original Spigot.

Also i found error's source if anyone has this error, he have to change his PC language to English.
Because of Certain locales won't work with Protocollib.

Like this:
Turkish has some special characters like "ş,ğ,ı" and they are not in English Alphabet. And of course these softwares are English. Than its giving error.

Problem is solved thanks for looking. Problem causes by Certain Locales.
