### ISSUE TITLE
TinyProtocol not in the Maven repo anymore

### ISSUE THREAD

**Issue by Seggan** [dmulloy2/ProtocolLib#2326]
`TinyProtocol` seems to have been removed from the snapshots repository. Browsing for it, I cannot find it, and my IDE cannot find it either.

**Comment by Sentropic** [comment]
Same here! I couldn't find it anywhere

**Comment by VocanicZ** [comment]
Does anyone figure out where It's repo moved? or they completlely  removed it.

**Comment by Sentropic** [comment]
I've been waiting for almost a year now, they haven't uploaded it back yet.
