### ISSUE TITLE
ProtocolLib won't start or show in /pl

### ISSUE THREAD

**Issue by ShadyVADER** [dmulloy2/ProtocolLib#233]
I'm running CraftBukkit version git-Spigot-6016ac7-10c10b3 (MC: 1.10).

I tried using  ProtocolLib  4.0.2-SNAPSHOT-b293 so I could run AntiAura, but it did not show up in the /pl.  I then tried to use ProtocolLib 4.0.2-SNAPSHOT-b300, and it had the same problem.

One of the other dependencies for AntiAura was Lib's Disguises, and I tried to download that as well, but with the same issues.

Nothing shows in the console, and I can't get either of those two to run.

**Comment by ShadyVADER** [comment]
It's not something to do with how I download the plugins either, because I just downloaded other plugins and they worked fine.

**Comment by MiniDigger** [comment]
make sure that the files are in your plugin folder. 
if they are, attach a console log.

**Comment by ShadyVADER** [comment]
They are in my plugin folder.  The plugin just refuses to launch.

Do I just copy and paste the entire console log into here?  It's pretty lengthy and I haven't seen anything in there dealing with the plugin :/

**Comment by MiniDigger** [comment]
use http://paste.md-5.net/ to past the log

**Comment by ShadyVADER** [comment]
http://paste.md-5.net/raw/borolamumu

**Comment by ShadyVADER** [comment]
I tried other versions again and they didn't work again. :|

**Comment by dmulloy2** [comment]
The plugin isn't installed correctly, hence why it doesn't show up anywhere in the logs. Make sure you're downloading the proper jar and putting it in the plugins folder.

**Comment by ShadyVADER** [comment]
Since I'm clearly having an extremely difficult time figuring out which version is the correct one, can you please tell me?  I've tried almost all of the builds from #293 - #301 and I can't figure it out :/

**Comment by ShadyVADER** [comment]
I've figured it out.  Turns out I was placing it into my plugins folder incorrectly.  I was turning the plugin into a folder before inserting it, but I tried leaving it as the .jar and they downloaded and launched.  Sorry for wasting your time.  Thank you for the help, though.
