### ISSUE TITLE
Question regarding ProtocolLib 5.0.0 Release

### ISSUE THREAD

**Issue by lukalt** [dmulloy2/ProtocolLib#2334]
The latest release of ProtocolLib on SpigotMC is more than a year old and quite a lot of changes have been made in this repository since than. In particular, the version on SpigotMC lacks support for MC 1.19 or later which confuses lots of users.

I was wondering what tasks or problems still need to be solved for the full release of ProtocolLib 5.0.0?

P.s. Both build 606 and 616 linked on SpigotMC are dead at the moment because the corresponding builds were automatically archived by Jenkins.

**Comment by dmulloy2** [comment]
i actually had been planning on it right before 1.19.4 came out. now i think there are a few backwards compatibility issues i'd like to make sure are fixed before releasing

**Comment by lukalt** [comment]
Okay 👍
