### ISSUE TITLE
[ProtocolLib] Task #13981 for ProtocolLib v3.7.0 generated an exception

### ISSUE THREAD

**Issue by felipeleite5w** [dmulloy2/ProtocolLib#2337]
My players get timed out af

[ProtocolLib] Task #13981 for ProtocolLib v3.7.0 generated an exception

Maybe this version is not supported anymore, but any ideas what could be causing it

**Comment by felipeleite5w** [comment]
?

**Comment by Jeppa** [comment]
Any why not trying an update?
