### ISSUE TITLE
ProtocolLib / LibsDisguises with MythicMobs Bug Kick

### ISSUE THREAD

**Issue by blazex224** [dmulloy2/ProtocolLib#234]
Whenever I try to spawn a mob using MythicMobs, I get kicked from the server and presented with this screen:
[http://i.imgur.com/DR38wJS.png](http://i.imgur.com/DR38wJS.png)

I am almost sure that this isn't a MythicMobs problem, because the error log does not display anything related to it.

My spigot version is 1.9.4
I have tried using LibsDisguises version 9.0.6 along with ProtocolLib version 4.0.0 and then I tried using the 1.10 version of those plugins just to see if anything would change, and I continue to get the same error.

Error log from console:
[http://pastebin.com/XMHKv2et](http://pastebin.com/XMHKv2et)

Thanks!

**Comment by dmulloy2** [comment]
Make sure you're using the proper version of LibsDisguises. This doesn't appear to be a ProtocolLib issue.
