### ISSUE TITLE
Event Loop caus low TPS

### ISSUE THREAD

**Issue by wryel2000** [dmulloy2/ProtocolLib#2357]
- [ ] This issue is not solved in a development build

1. Go to 'https://spark.lucko.me/umspE1YrVh'
2. Click on 'plugin performace view'
3. Scroll down to 'Protocol Lib'
4. See error "print"

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://spark.lucko.me/umspE1YrVh)

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.pl/view/50181ce6)

**Comment by lukalt** [comment]
The first half here is not a issue with ProtocolLib itself but rather a problem with other plugin that use ProtocolLib taking about 3.6% of the tick time. If you expand the call tree, you can identify these plugins. In your case, the problematic plugins should be CitizensNPC, LibsDisquise and AnticheatReloaded.

![image](https://user-images.githubusercontent.com/9149282/233829420-035af236-5e28-438c-9ca0-c7754d13c21d.png)

The second half is a little bit more challenging to tackle down. @derklaro recently contributed lots of changes that reduce the number of networking done on the main thread. Please try if the latest pre-release of ProtocolLib (https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1) improves the situation

**Comment by wryel2000** [comment]
Tks dude. u solved my problem! 

i go write here, "key search" with other peoples have this problem, find when search!

- ProtocolInjector.onPacketSending
- SortedPacketListenerList.invokePacketSending

tks to support
"
