### ISSUE TITLE
i have an bug that the player and the npc head texture gitch

### ISSUE THREAD

**Issue by realistc** [dmulloy2/ProtocolLib#2364]
- [ ] This issue is not solved in a development build
![2023-04-23_20 44 26](https://user-images.githubusercontent.com/82268658/234082139-88a313ab-1a8c-4f72-80eb-0bec8b1c7e4d.png)

**Describe the bug**
So if i install the plugin the plugin 'infact' the players skins, the head texture from the skin is on the other side. it infect npcs to

**To Reproduce**

**Expected behavior**
6f11aae7a2bd.png)

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
thats all everything works fine only the plugin 'infact' the player skins

**Comment by lukalt** [comment]
Please share the output of `/protocol dump`
