### ISSUE TITLE
Issue - Data Watcher with Item

### ISSUE THREAD

**Issue by Ducki0210** [dmulloy2/ProtocolLib#2367]
**Describe the bug**
I really have no idea how it happens but it seems to have started when I grabbed a torch and it kicked me off the server.
Since then, I am getting kicked instantly each time I am trying to join again with the same error

**Expected behavior**
I expected no issue and everything going right

**Screenshots**

**Version Info**
https://pastebin.com/jzCAVZD9

**The error**
https://pastebin.com/1h2batZG

**Comment by lukalt** [comment]
One of your plugins seems to be outdated. The way entity metadata  is stored changed with 1.19. The author of the plugins need to migrate from WrappedWatachbleObject to WrappedDatsWatcherValue.
That's not a problem of ProtocolLib itself

**Comment by Ducki0210** [comment]
Ty
