### ISSUE TITLE
ProtocalLib v5.0.0 Bug

### ISSUE THREAD

**Issue by ZiriiNotFound** [dmulloy2/ProtocolLib#2371]
- [ ] This issue is not solved in a development build

**Describe the bug**
Currently, when using the pre-release v5.0.0, players cannot crit and do less damage.

**To Reproduce**
1. Download ProtocalLib v5.0.0 on 1.19.4
2. Restart server
3. Players cannot crit

**Expected behavior**
Players should be able to crit and do normal damage.

**Screenshots**

**Version Info**
v5.0.0

**Additional context**

**Comment by dniym** [comment]
Experiencing the same issue on 1.17.1 with protocollib 5.0 build 654 installed, also players seem to be reporting that
they have sweeping edge on their swords but don't do sweeping edge dmg.

**Comment by dniym** [comment]
It appears this bug is related to my plugin, IllegalStack.    I apologize for not recognizing this sooner, version 2.9 fixes this issue if you're here wondering why your players can't crit or do sweeping edge damage, upgrade and the issue should go away!

**Comment by neinTMEINDIUGHYIUJYUHBTRYG** [comment]
hehe 😼 👍
