### ISSUE TITLE
EntityMetadata doesn't work in 1.19.3

### ISSUE THREAD

**Issue by karu1231** [dmulloy2/ProtocolLib#2378]
- [x] This issue is not solved in a development build

**Describe the bug**
When I try to rewrite EntityMetadata Packet in 1.19.3 with onPacketSending, I get an error that Datawatcher is unrecognized.

**To Reproduce**
1. Listen for EntityMetadata packets using PacketAdapter.
2. To extract data from the packet, read number 0 of WatchableCollectionModifier.
3. See error

**Expected behavior**
Manipulate EntityMeta packet data. (Note that this is an error that appeared when the code that worked in 1.18.1 was brought to 1.19.3, but worked fine in 1.18.1.)

**Screenshots**
![image](https://user-images.githubusercontent.com/51406692/236145312-e6e82451-331e-4c10-9910-667a876f38a5.png)
![image](https://user-images.githubusercontent.com/51406692/236145079-641a6215-b369-43de-a5b3-c5e16e1b653d.png)

**Comment by lukalt** [comment]
You need to update your code to the new metadata system of Minecraft. WrappedWatchableObject has been replaced with WrappedDataValue. There is also a modifier for this. I think it is `getWrappedDataValueLists()` or similar

**Comment by karu1231** [comment]
Thank you for your reply.
I changed it to WrappedDataValue and tried to change the displayName, but I get the error again.

![image](https://user-images.githubusercontent.com/51406692/236192361-bf625cc5-fe2c-48cb-b75a-bd1389d49831.png)
![スクリーンショット (1301)](https://user-images.githubusercontent.com/51406692/236192378-2d90bd76-56f5-4854-a19a-6cc77de276e5.png)

**Comment by lukalt** [comment]
You need to provide the unwrapped handle in the constructor of `WrappedDataValue`. So in your case `Optional.of(WrappedChatComponent.fromText(name).getHandle())`

**Comment by karu1231** [comment]
Thanks for your advice, it is very helpful.
I have successfully reached the program I was looking for. Thank you very much.
Since it seems to have worked successfully, I will close this Issue.
