### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by mustengs** [dmulloy2/ProtocolLib#238]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link: http://pastebin.com/u7jdLkMc

Description and relevant errors: It keep on crashing my server

**Comment by dmulloy2** [comment]
I think you're missing the top part of the stack. Can you provide it?

**Comment by decontamin4t0R** [comment]
This seems to relate to Lib's Disguises

**Comment by dmulloy2** [comment]
Any more info on this?
