### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart

### ISSUE THREAD

**Issue by YodaZen** [dmulloy2/ProtocolLib#2385]
- [ ] This issue is not solved in a development build

**Describe the bug**
Trying to use ProtocolLib with Diskuise. 1.19.4

**To Reproduce**
Add newest version of ProtocolLib and newest version of Diskuise onto a 1.19.4 server.

**Expected behavior**
Make the skript addon work i guess.

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/ZpitCJpa)

**Additional context**
The console message:

https://pastebin.com/piwxZbeN

**Comment by lukalt** [comment]
Use the latest pre release: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1
