### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart

### ISSUE THREAD

**Issue by Dhruvjain32** [dmulloy2/ProtocolLib#2386]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

Error in Pastebin:
https://pastebin.com/ZiusZF19

**Comment by lukalt** [comment]
Use this version: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1

**Comment by matytyma** [comment]
> Use this version: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1

Happens also with the newer version, server version 1.19.2

**Comment by lukalt** [comment]
Please share the whole stack trace/log

**Comment by matytyma** [comment]
Not my server, but I got some screenshots from the owner:
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/bfd23e71-cc12-4c68-8229-cd887e46db67)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/422f5b79-e584-418b-b3ad-626c3d5a671e)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/00191c09-a43b-4d06-9a00-3d1739e57c88)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/f9b5b58a-7564-49bf-90a3-93225da71c09)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/4557af62-90c3-47c2-b160-95b9eca5a8f2)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/fbd9ce88-c749-4ac0-ab30-a23295ef919f)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/40507e67-5061-4e59-ae10-53928f0c1b10)
![image](https://github.com/dmulloy2/ProtocolLib/assets/100159609/601567e2-2b4c-4aef-ad75-4197af54f69f)

**Comment by lukalt** [comment]
As I said, they need to be using ProtocolLib 5.0.0-rc1 (https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1). ProtocolLib 4.8.0 has no 1.19+ support.

**Comment by matytyma** [comment]
Trust but verify, yeah :sweat_smile:. I told the server owner to put 5.0.0 there (even sent direct link to the file) and didn't check the logs much
