### ISSUE TITLE
v5-SNAPSHOT | Cant create PLAYER_INFO packet

### ISSUE THREAD

**Issue by MahmutTaylanOzturk** [dmulloy2/ProtocolLib#2387]
- [ ] This issue is not solved in a development build

**Describe the bug**
This bug is thrown when I try to create player info packet

**To Reproduce**
 1. use the latest v5 dependecy from repo host
2. Join the game and wait for tab creation
3. After the creation of tab it will create player info packets too

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/122650474/236591726-a2dbecc1-8853-4d32-82ba-59e430f74362.png)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Stack trace of error: https://paste.md-5.net/siqoponena.cs

**Comment by lukalt** [comment]
You need to migrate from getPlayerInfoAction() to grtPlayerInfoActions().  Check https://wiki.vg/Protocol for reference. Also you need to use index 1 for the entry list.

**Comment by MahmutTaylanOzturk** [comment]
> You need to migrate from getPlayerInfoAction() to grtPlayerInfoActions(). Check https://wiki.vg/Protocol for reference. Also you need to use index 1 for the entry list.

Converted to this 
![image](https://user-images.githubusercontent.com/122650474/236612831-4e8c5d4c-1a68-4033-a321-bbf0330568b5.png)

But now I am getting this error
https://paste.md-5.net/kucijohuyi.bash

I am trying to convert this lib to 1.19. Can changing this getPacket method fix this whole project? Or what should I update in this api? https://github.com/thekeenant/tabbed

**Comment by MahmutTaylanOzturk** [comment]
I fixed the issue but now I there is no blank spaces in tab

Normal:
![image](https://user-images.githubusercontent.com/122650474/236619765-5b07609b-dafb-483a-ac4b-e3fcfe9d9eb4.png)
Current:
![image](https://user-images.githubusercontent.com/122650474/236619774-4dcf3cba-c6cb-432b-a164-e141f82b5f2d.png)

**Comment by lukalt** [comment]
Well, I do not think this is related to ProtocolLib but rather something changed with the Minecraft Client. Maybe you can try to set  the empty lines to a non-empty string that it not rendered on client side, e.g. just "§a".

**Comment by MahmutTaylanOzturk** [comment]
That can be the issue. But I think the issue is new Listed boolean in PlayerInfoData. How can I send this listed packet to the player?
![image](https://user-images.githubusercontent.com/122650474/236628311-0e4691af-3fb0-452d-8834-8989c5915766.png)

**Comment by lukalt** [comment]
Make sure to include UPDATE_LISTED in the actions set, i.e. ,

`handle.getPlayerInfoActions().write(0, EnumSet.of(EnumWrappers.PlayerInfoAction.ADD_PLAYER,
                EnumWrappers.PlayerInfoAction.INITIALIZE_CHAT,
                EnumWrappers.PlayerInfoAction.UPDATE_GAME_MODE,
                EnumWrappers.PlayerInfoAction.UPDATE_LISTED,
                EnumWrappers.PlayerInfoAction.UPDATE_LATENCY,
                EnumWrappers.PlayerInfoAction.UPDATE_DISPLAY_NAME));`

You can specify the listed flag in the constructor of PlayerInfoData
