### ISSUE TITLE
1.8 and holographic displays, so I have some issues when I put newers version of protocolLib, some holograms enable the visibility of armors stands in 1.8, with holographic displays & procasino plugin

### ISSUE THREAD

**Issue by Peter84841** [dmulloy2/ProtocolLib#2389]
- [x] This issue is not solved in a development build

**Describe the bug**
in my 1.8.8 minecraft server: heads or objects on the armor stand are not loaded.

**To Reproduce**
1. I join the server (protocollib 4.8)
2. heads and arrow in stand loaded
3. I join the server (protocollib 5.0)
4. heads and arrow in stand NOT loaded
(Protocollib 5.0 requirement to work server's anticheat)

**Expected behavior**
after I leave the blocks on the invisible armor stands and fill them and approach them again, the server does not display them.

**Screenshots**
https://imgur.com/a/K0k6PkF

**Video**
https://www.youtube.com/watch?v=RMi2XrEVdSE

**Version Info**
https://pastebin.com/SbpGYsKM

**Additional context**
Please fix it <3

**Comment by lukalt** [comment]
Please try HolographicDisplays v3.0.1
