### ISSUE TITLE
NullPointerException caused by missing login packet

### ISSUE THREAD

**Issue by prodkid** [dmulloy2/ProtocolLib#239]
http://pastebin.com/ix3WQ9ha
I believe it started occurring when I added iptables rules.

Running Bungeecord, occurring on all of my servers

**Comment by dmulloy2** [comment]
Errors like these occur when you use illicit builds of Spigot or CraftBukkit. Sites that offer compiled downloads of Spigot are by their very nature illicit and should not be trusted. Packet class paths should be in the format of ````net.minecraft.server.v[version].Packet[Phase][Direction][Name]````. If they're not, ProtocolLib will not function.

Make sure you're using BuildTools to build your Spigot or CraftBukkit jar. See here for more information: https://www.spigotmc.org/wiki/buildtools/

**Comment by prodkid** [comment]
Yeah, I am running KCauldron, however this was never an issue until i setup iptables. I am wondering If I need to setup a rule to fix the packets.

Heres the dump info
http://pastebin.com/cSnvaySK

**Comment by dmulloy2** [comment]
4.x won't work with 1.7.10 anyways. You might have better luck with 3.6.5:http://ci.dmulloy2.net/job/ProtocolLib/222/

**Comment by dmulloy2** [comment]
Try the 3.7.0 release: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
