### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by TheRedMagic** [dmulloy2/ProtocolLib#2390]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

https://pastebin.com/vPAGxqus

Description and relevant errors:

This error is spammed in consel

**Comment by lukalt** [comment]
Use the latest pre release: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1
