### ISSUE TITLE
Error when startup

### ISSUE THREAD

**Issue by anothermeer** [dmulloy2/ProtocolLib#2391]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://pastebin.com/zUSmBiLb
Description and relevant errors:
This error showed up at startup

**Comment by lukalt** [comment]
Use the latest pre release: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1

**Comment by Squawkykaka** [comment]
Same problem here thanks for the solution
