### ISSUE TITLE
Strange protocollib error

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2397]
**Describe the bug**
https://pastes.dev/Sb68ajiUQC

**To Reproduce**
i don't know really

**Version Info**
[dump-2023-05-13_15.29.09.txt](https://github.com/dmulloy2/ProtocolLib/files/11469649/dump-2023-05-13_15.29.09.txt)

**Comment by lukalt** [comment]
You cannot access the block asynchronously.  Set the `ListenerOptions.SYNC` option for your packet listener to ensure that the listener is called on the main thread, e.g.:

```
new PacketAdapter(plugin, ListenerPriorit.NORMAL, Arrays.asList(PacketType.Play.Server.ENTITY_TELEPORT),
			ListenerOptions.SYNC);
```

**Comment by F3F5** [comment]
> 

thanks!!
