### ISSUE TITLE
Could not load 'plugins/ProtocolLib.jar' in folder 'plugins' on my server purpur 1.18.2

### ISSUE THREAD

**Issue by WorldOfChuaHe** [dmulloy2/ProtocolLib#2399]
- [ ] This issue is not solved in a development build

**Describe the bug**
IDk how it happed, in my console show "Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'"
link here : https://pastebin.com/ueiY4UgT

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by lukalt** [comment]
Please share your whole log and the output of `/protocol dump` as stated in the issue template.

**Comment by WorldOfChuaHe** [comment]
> Please share your whole log and the output of `/protocol dump` as stated in the issue template.

it say "/protocol dump
[14:35:45 INFO]: Unknown command. Type "/help" for help."

**Comment by lukalt** [comment]
Okay, this makes sense. But please share the whole log file (`logs/latest.log` in the server folder).
