### ISSUE TITLE
Error Occurs when player login

### ISSUE THREAD

**Issue by l89669** [dmulloy2/ProtocolLib#240]
Error Occurs when player login. 

Debug paste link:
Sorry but I cannot reach pastbin.com in my country.

18.07 10:00:26 [Server] WARN [ProtocolLib] [DetailedErrorReporter] Internal exception count: 65536!
18.07 10:00:26 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalStateException: Failed to obtain login start packet. Did you build Spigot with BuildTools?) occured in com.comphenix.protocol.injector.netty.ChannelInjector@5ac37130.
18.07 10:00:26 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
18.07 10:00:26 [Server] INFO If this problem hasn't already been reported, please open a ticket
18.07 10:00:26 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
18.07 10:00:26 [Server] INFO Stack Trace:
18.07 10:00:26 [Server] INFO java.lang.IllegalStateException: Failed to obtain login start packet. Did you build Spigot with BuildTools?
18.07 10:00:26 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:592)
18.07 10:00:26 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:534)
18.07 10:00:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
18.07 10:00:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
18.07 10:00:26 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
18.07 10:00:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
18.07 10:00:26 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
18.07 10:00:26 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
18.07 10:00:26 [Server] INFO at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
18.07 10:00:26 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
18.07 10:00:26 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
18.07 10:00:26 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
18.07 10:00:26 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
18.07 10:00:26 [Server] INFO at java.lang.Thread.run(Unknown Source)
18.07 10:00:26 [Server] INFO Dump:
18.07 10:00:26 [Server] INFO Parameters: 
18.07 10:00:26 [Server] INFO io.netty.buffer.UnpooledHeapByteBuf@1dc2f7b0[
18.07 10:00:26 [Server] INFO alloc=io.netty.buffer.UnpooledByteBufAllocator@6ed0d19c
18.07 10:00:26 [Server] INFO array={6,-64,-90,87,-123,120,33,-51,30,64,86,15,-14,-82,92,114,-44,64,86,119,-96,-62,-36,114,-44,64,-123,15,-13,-38,31,-24,46,66,-88,-76,68,64,-37,119,-108,0}
18.07 10:00:26 [Server] INFO tmpNioBuf=<null>
18.07 10:00:26 [Server] INFO refCnt=1
18.07 10:00:26 [Server] INFO readerIndex=42
18.07 10:00:26 [Server] INFO writerIndex=42
18.07 10:00:26 [Server] INFO markedReaderIndex=0
18.07 10:00:26 [Server] INFO markedWriterIndex=0
18.07 10:00:26 [Server] INFO maxCapacity=2147483647
18.07 10:00:26 [Server] INFO swappedBuf=<null>
18.07 10:00:26 [Server] INFO ]
18.07 10:00:26 [Server] INFO manager:
18.07 10:00:26 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@70ce28f5[
18.07 10:00:26 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@70ecade7
18.07 10:00:26 [Server] INFO packetListeners=[]
18.07 10:00:26 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@78213b01
18.07 10:00:26 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4e928d62
18.07 10:00:26 [Server] INFO interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@39176ca3
18.07 10:00:26 [Server] INFO inputBufferedPackets=[]
18.07 10:00:26 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@381f72f4
18.07 10:00:26 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4020a0e6
18.07 10:00:26 [Server] INFO hasClosed=false
18.07 10:00:26 [Server] INFO classLoader=org.bukkit.plugin.java.PluginClassLoader@60e06d83
18.07 10:00:26 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@2d096385
18.07 10:00:26 [Server] INFO server=CraftServer{serverName=Cauldron,serverVersion=1.7.10-1614.54,minecraftVersion=1.7.10}
18.07 10:00:26 [Server] INFO library=ProtocolLib v4.0.2
18.07 10:00:26 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2bfecf7a
18.07 10:00:26 [Server] INFO knowsServerPackets=true
18.07 10:00:26 [Server] INFO knowsClientPackets=true
18.07 10:00:26 [Server] INFO phaseLoginCount=0
18.07 10:00:26 [Server] INFO phasePlayingCount=0
18.07 10:00:26 [Server] INFO packetCreation=false
18.07 10:00:26 [Server] INFO spigotInjector=<null>
18.07 10:00:26 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2699b188
18.07 10:00:26 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7f3d400
18.07 10:00:26 [Server] INFO hasRecycleDistance=true
18.07 10:00:26 [Server] INFO minecraftVersion=(MC: 1.7.10)
18.07 10:00:26 [Server] INFO loginPackets=com.comphenix.protocol.injector.LoginPackets@298b0eb0
18.07 10:00:26 [Server] INFO debug=false
18.07 10:00:26 [Server] INFO ]
18.07 10:00:26 [Server] INFO Sender:
18.07 10:00:26 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@5ac37130[
18.07 10:00:26 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@71246f89
18.07 10:00:26 [Server] INFO player=CraftPlayer{name=Knight}
18.07 10:00:26 [Server] INFO updated=<null>
18.07 10:00:26 [Server] INFO playerName=Knight
18.07 10:00:26 [Server] INFO playerConnection=<null>
18.07 10:00:26 [Server] INFO networkManager=net.minecraft.network.NetworkManager@7e8ef24a
18.07 10:00:26 [Server] INFO originalChannel=[id: 0x2b2259ff, /58.59.197.15:29104 => /192.168.114.106:25565]
18.07 10:00:26 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=private io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@7e8ef24a, previous=[id: 0x2b2259ff, /58.59.197.15:29104 => /192.168.114.106:25565], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@bcf75e8, previousLoaded=true, currentSet=true, forceAccess=true]
18.07 10:00:26 [Server] INFO packetMarker={}
18.07 10:00:26 [Server] INFO currentEvent=<null>
18.07 10:00:26 [Server] INFO finalEvent=<null>
18.07 10:00:26 [Server] INFO scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@4a44df50
18.07 10:00:26 [Server] INFO vanillaDecoder=net.minecraft.util.MessageDeserializer@43d168f0
18.07 10:00:26 [Server] INFO vanillaEncoder=net.minecraft.util.MessageSerializer@682b24d3
18.07 10:00:26 [Server] INFO finishQueue=[]
18.07 10:00:26 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2699b188
18.07 10:00:26 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@74698e13
18.07 10:00:26 [Server] INFO injected=true
18.07 10:00:26 [Server] INFO closed=false
18.07 10:00:26 [Server] INFO cumulation=UnpooledHeapByteBuf(ridx: 42, widx: 42, cap: 42)
18.07 10:00:26 [Server] INFO singleDecode=false
18.07 10:00:26 [Server] INFO decodeWasNull=false
18.07 10:00:26 [Server] INFO added=true
18.07 10:00:26 [Server] INFO ]
18.07 10:00:26 [Server] INFO Version:
18.07 10:00:26 [Server] INFO ProtocolLib v4.0.2
18.07 10:00:26 [Server] INFO Java Version:
18.07 10:00:26 [Server] INFO 1.8.0_65
18.07 10:00:26 [Server] INFO Server:
18.07 10:00:26 [Server] INFO 1.7.10-1614.54 (MC: 1.7.10)

Description and relevant errors:
It happens randomly when player trying to login.

Server Version:
Thermos 1.7.10-54

Plugins:
18.07 10:06:50 [Server] INFO Plugins (28): CoreProtect, Itemizer, WorldEdit, PlayerCommands, Essentials, GroupManager, PlaceholderAPI, WorldBorder, EasyBackup, Multiverse-Core, ProtocolLib, InvBack, EssentialsProtect, EssentialsChat, BanItem, EssentialsAntiBuild, iConomy, BossShop, Multiverse-Portals, Vault, EssentialsSpawn, ScriptBlock, AuthMe, NeverLag, QuickShop, VipZero, Residence, LockettePro

**Comment by MiniDigger** [comment]
I don't think that protocollib supports thermos (https://github.com/CyberdyneCC/Thermos)

**Comment by l89669** [comment]
Heard from another issue that 4.x do not support 1.7.10 anymore, I'll rollback to 3.6.0.

**Comment by dmulloy2** [comment]
ProtocolLib doesn't support Thermos. Your best bet is to try 3.6.5.
