### ISSUE TITLE
(QUESTION)

### ISSUE THREAD

**Issue by CheatSupport** [dmulloy2/ProtocolLib#241]
Hey!

I use PaperSpigot 1.8.8, and was wondering is http://ci.dmulloy2.net/job/ProtocolLib/310/ compatible with that version? it says: "4.1 for 1.8 thru 1.10.x"

Please let me know, thanks

**Comment by CheatSupport** [comment]
@dmulloy2

**Comment by CheatSupport** [comment]
@dmulloy2 Please let me know :D

**Comment by dmulloy2** [comment]
4.1 supports all CraftBukkit, Spigot, and PaperSpigot versions 1.8 thru 1.10.2
