### ISSUE TITLE
Bug report with all versions of ProtocoliLib 5.0.0+ > in minecraft server 1.8 

### ISSUE THREAD

**Issue by HeenoDev** [dmulloy2/ProtocolLib#2411]
We can't see armors on players, the armors are buggy and when they are present for some players there is not armor. like in the screen the armor stand should have a head but it don,t show it same for other peices of armors 
![Screenshot 2023-05-25 203346](https://github.com/dmulloy2/ProtocolLib/assets/113239428/d82834a9-d893-4955-aa34-1f57febb8736)

**Comment by lukalt** [comment]
Please share your code and the output of `/protocol dump`

**Comment by lukalt** [comment]
Thank you. Did the problem occur with older versions of ProtocolLib?

**Comment by HeenoDev** [comment]
Nope under PorocolLib version 5.0.0 < it doesn't, and do you know when you will fix it ?

**Comment by Godl1nk** [comment]
these are caused by sending packets async

**Comment by Godl1nk** [comment]
Protocollib 5.0 will have issues with packets which are handled async. spigots that have things like Async Tracking will have invis stuff including npcs and holograms (which is armor stand)

**Comment by HeenoDev** [comment]
Then have some news about this?

**Comment by lukalt** [comment]
@Godl1nk Do you know a way to reproduce this?

**Comment by HeenoDev** [comment]
I don't really know, like when you load/unload or die and comeback some piece of armor don't show up

**Comment by HeenoDev** [comment]
Some news here ? cauz the last successful build is not fixed ^
