### ISSUE TITLE
Troubles with PacketEvent

### ISSUE THREAD

**Issue by xw1w1** [dmulloy2/ProtocolLib#2412]
Im making some chat plugin and need to collect messages

```Java
public void onPacket(@NotNull PacketEvent event) {
        if (event.getPacketType() == PacketType.Play.Server.SYSTEM_CHAT) {
            PacketContainer container = event.getPacket();
            ClientboundSystemChatPacket clientboundSystemChatPacket = (ClientboundSystemChatPacket)container.getHandle();
            if (!clientboundSystemChatPacket.c()) {
                    String packetContent = clientboundSystemChatPacket.content();
                    if (packetContent.toLowerCase().replaceAll("[{}\":\\[]\\d}\\$\\^\\|,\\\\/;]", "").trim().contains("jndi")) {
                        event.setCancelled(true);
                    } else {
                        <redacted>
                    }
                }
            }
        }
    }
```

it throwns out when im doing player.sendMessage(net.kyori.adventure.text.Component)
Not sure what could be wrong, worked very little with ProtocolLib so hopefully getting some help

**Comment by lukalt** [comment]
The name of the method is wrong. You need to override `void onPacketSending(PacketEvent event);` but you implemented `void onPacket(PacketEvent event);`. I'd suggest to add `@Override` in front of the method's signature to get compilation error if you use a wrong method name.

Also, I suggest to use ProtocolLib's method for accessing the Packet fields so you do not need to use NMS, i.e:

`boolean overlay = container.getBooleans().read(0);`
`String json = container.getStrings().read(0);`

**Comment by xw1w1** [comment]
[10:51:42 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@ae29021[
    content=<null>
    b=false
  ]
  
 still getting this in console

**Comment by xw1w1** [comment]
Also, I saw this piece of code:
Component adventure$content = clientboundSystemChatPacket.adventure$content();
what could it be?

**Comment by lukalt** [comment]
Please refer to this example on how you can access both fields with a single method call: https://github.com/lukalt/PacketWrapper/blob/master/src/main/java/com/comphenix/packetwrapper/wrappers/play/clientbound/WrapperPlayServerSystemChat.java#L44 @xw1w1
