### ISSUE TITLE
Async PacketListener breaking NetworkMarker PostListener

### ISSUE THREAD

**Issue by Ingrim4** [dmulloy2/ProtocolLib#2416]
- [x] This issue is not solved in a development build

**Describe the bug**
All registered `PacketPostListeners` aren't executed if the `PacketType` has an async `PacketListener`. If you only register the sync `PacketListener` in the provided example repo then the `PacketPostListener` works as intended but as soon as you register an async listener this won't work anymore. Same goes for a single async `PacketListener` with a sync listener.

**To Reproduce**
1. clone https://github.com/Imprex-Development/protocol-networkmarker
2. mvn clean package
3. put plugin on server
4. join server
5. see memory slowly creeping up

**Expected behavior**
All registered post listeners should be executed.

**Version Info**
https://gist.github.com/Ingrim4/82d147a095fdd710afff33d4d9ff9f34

**Comment by lukalt** [comment]
We can't access the linked repository. Maybe it's private?

**Comment by Ingrim4** [comment]
Sorry copied wrong, changed it in the issue.
