### ISSUE TITLE
protocollib + viaversion = conflict

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2419]
Console Error
https://paste.gg/p/anonymous/fba5187f8d31461eaaa5f4a2ae4682f0

Bug Description
viaversion conflict

support says: The error isn't ViaVersion related

**Comment by lukalt** [comment]
Which Java Version and JVM (Hotspot vs OpenJ9) are you using?

**Comment by F3F5** [comment]
and i don't reloaded protocollib, it only with viaversion installed caused this random erorrs

**Comment by Draghonir** [comment]
Hello same way for me 

<img width="1719" alt="1" src="https://github.com/dmulloy2/ProtocolLib/assets/107469643/d2397227-2c9f-481f-9a0e-a50f4a8efc2e">
<img width="781" alt="2" src="https://github.com/dmulloy2/ProtocolLib/assets/107469643/ae874623-d32d-42a8-8bdb-37a645b374cf">

**Comment by Draghonir** [comment]
https://spark.lucko.me/alxpcKUQAY if you need info from my server

**Comment by F3F5** [comment]
https://pastes.dev/1bl5AMAGxH

**Comment by lukalt** [comment]
@F3F5 Please try build 649: https://ci.dmulloy2.net/job/ProtocolLib/649/. The problem should be fixed now

**Comment by F3F5** [comment]
> @F3F5 Please try build 649: https://ci.dmulloy2.net/job/ProtocolLib/649/. The problem should be fixed now

same issues

**Comment by F3F5** [comment]
https://pastes.dev/NHzv3hIbWK

**Comment by mxson** [comment]
the issue is still occurring for myself as well

**Comment by lukalt** [comment]
I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

**Comment by F3F5** [comment]
> I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

can you look at our problem

**Comment by lukalt** [comment]
I have absolutely no clue how this could be caused. Maybe @derklaro can help here

**Comment by Draghonir** [comment]
> I was talking about the issue mentioned by @Draghonir, sorry. That one should be fixed.

is fixed for me ;)

**Comment by derklaro** [comment]
Is there no other error while starting up the server that is related to ProtocolLib? (search for the log message `Unable to retrieve trusted lookup`)

**Comment by F3F5** [comment]
> Is there no other error while starting up the server that is related to ProtocolLib? (search for the log message `Unable to retrieve trusted lookup`)

no

**Comment by F3F5** [comment]
@dmulloy2 please check :0
