### ISSUE TITLE
Please update to 1.20

### ISSUE THREAD

**Issue by CCjun6** [dmulloy2/ProtocolLib#2423]
This plugin is not available in version 1.20
Please update the author if you have time

**Comment by derklaro** [comment]
The update was merged and released yesterday

**Comment by CCjun6** [comment]
> 该更新于昨天联合并发布

what？ Already published? Can you give me a link, thank you very much

**Comment by EyesX** [comment]
> > 该更新于昨天联合并发布
> 
> what？ Already published? Can you give me a link, thank you very much

https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by NoltoxGit** [comment]
This issue can be closed.

**Comment by catball242** [comment]
cant find it

**Comment by Freddereck** [comment]
update to 1.20.4 pls
