### ISSUE TITLE
java conflict with protocollib

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2424]
Console Error
https://pastes.dev/VM3b0sOebX

**Comment by F3F5** [comment]
@dmulloy2

**Comment by dmulloy2** [comment]
fixed in a recent dev build. https://ci.dmulloy2.net/job/ProtocolLib

**Comment by F3F5** [comment]
> fixed in a recent dev build. https://ci.dmulloy2.net/job/ProtocolLib

https://pastes.dev/huGKixCeGl same problem. java openj9
