### ISSUE TITLE
Error when i join server

### ISSUE THREAD

**Issue by Xlueus** [dmulloy2/ProtocolLib#2429]
I just got a server installed protocol lib version 3.7 and I keep getting this error whenever I join, there was another post based on this error but there wasn't really a solution I don't think.

**Expected behavior**
Let me join the server.

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/135395177/c44ba8a9-8851-4823-9668-91b3698665ca)

**Version Info**
Version: 3.7
Server Version: 1.7.10

**Comment by lukalt** [comment]
Use Java 7 or maybe Java 8. You are using a 10 year old version...

**Comment by Xlueus** [comment]
> Use Java 7 or maybe Java 8. You are using a 10 year old version...

i am using java 8

**Comment by lukalt** [comment]
Please double check this. I dont think modules were available in Java 8 yet

**Comment by Xlueus** [comment]
> Please double check this. I dont think modules were available in Java 8 yet

sorry you were correct I had installed it but I hadn't put it in my batch idk its really weird but thanks for your help!
