### ISSUE TITLE
Backwards compatibility for sign editing

### ISSUE THREAD

**Issue by eccentricdevotion** [dmulloy2/ProtocolLib#243]
When using ProtocolLib v4.1.0-SNAPHOT-b313 on a 1.8.8 CraftBukkit server [git-Bukkit-e1ebe52 (MC: 1.8.8)] if a plugin (such as TARDIS v3.4.2) creates an OPEN_SIGN_ENTITY packet the server will report a NoSuchFieldError.

Example error: https://bpaste.net/show/1461455de20d

Is it possible to extend this recent commit: https://github.com/dmulloy2/ProtocolLib/commit/05ffeb8e7f50c7c1f8ff81abe80ac26e0e6f8dc3#diff-226cb6a05c21a8f2e21926b6b6ece074 to include the OPEN_SIGN_ENTITY packet (now renamed OPEN_SIGN_EDITOR) and CB 1.8.8 backwards compatibility?

**Comment by dmulloy2** [comment]
Not sure how I missed it, but it should be a pretty simple fix.

**Comment by eccentricdevotion** [comment]
Thank you :)
