### ISSUE TITLE
Getting chunk block data?

### ISSUE THREAD

**Issue by soshimee** [dmulloy2/ProtocolLib#2431]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
There doesn't seem to be a method for getting the block data from the chunk data.

**API method(s) used**
AbstractStructure#getLevelChunkData()

**Expected behavior**
There should be a way to access all the block data, not just the block entities and height maps.

**Code**
None.

**Additional context**
None.

**Comment by lukalt** [comment]
Hi,  you can access the encoded block data of the chunk using `getBuffer()`. However, this just a byte array like in the actual NMS packet class. I do not think that we can provide proper wrapper methods for parsing this raw data in ProtocolLib.

**Comment by PainOchoco** [comment]
Hi, is it possible to set chunk data from a bukkit Chunk? e.g.

Here I'm using PacketWrapper but if you have a solution with ProtocolLib I'll take it.
```java
Chunk playerChunk = player.getChunk();
PacketContainer packet = protocolManager.createPacket(PacketType.Play.Server.MAP_CHUNK);
WrapperPlayServerMapChunk wrapper = new WrapperPlayServerMapChunk(packet);
wrapper.setChunkData(/* get chunk data somehow */);
wrapper.setLightData(/* get chunk light data somehow */);
```

Thanks!
