### ISSUE TITLE
error server reloading and restarten

### ISSUE THREAD

**Issue by mikaig** [dmulloy2/ProtocolLib#2434]
- [x] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by mikaig** [comment]
me server try to reloads to this plugin it sayed that its an error. its doesnt work i cant start up me server anymore it sayed we are reloading it and restart

**Comment by dmulloy2** [comment]
i'm not exactly sure what you mean, but it sounds like you're reloading. don't use /reload
