### ISSUE TITLE
 java.lang.IllegalArgumentException: Unable to find method run(interface org.bukkit.plugin.Plugin, interface java.lang.Runnable) in io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler

### ISSUE THREAD

**Issue by hkkongou** [dmulloy2/ProtocolLib#2438]
- [ ✅] This issue is not solved in a development build

**Describe the bug**
 ProtocolLib # 653 dev build cannot enable
version # 652 can enable

**To Reproduce**
1. put jar in folia server 1.20.1
2. error occur

**Expected behavior**
no erorr

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/61608872/0323b191-8e41-4fcd-930e-45e9980cb40f)

**Version Info**
command cannot use since plugin is not enabled 

**Additional context**
using folia-bundler-1.20.1-R0.1-SNAPSHOT-reobf

**Comment by dmulloy2** [comment]
ah right it's a consumer
