### ISSUE TITLE
ProtocolLib error in conjunction with PremiumVanish plugin

### ISSUE THREAD

**Issue by PABLORAGNIzc** [dmulloy2/ProtocolLib#2439]
- [x] This issue is not solved in a development build

When trying to use the plugin "PremiumVanish" for Paper version 1.20.1, when logging into the server and using the /v command (which puts you in invisible to players) it throws a huge error, the what the error detail clarifies that it may be due to ProtocolLib, I would like to leave the error report so you can observe if it is true or if the plugin itself should perform an update.

![image](https://github.com/dmulloy2/ProtocolLib/assets/84411800/a76e190e-3d47-4730-b3c3-d4eb133329ac)

[**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/S4qz6iMY)

I would like to show part of the error that this plugin throws, the truth is that it is all that I can present. If you need more detail of the error I can put it here, I hope not to anger anyone as I do it with total ignorance and just trying to solve my problems. Thank you. Here part of the error:

[12:08:27] [Server thread/ERROR]: [PremiumVanish] Important: This error may be related to PV or ProtocolLib being out of date. Please follow the instructions on the PV resource page. Usually this means installing the latest version of ProtocolLib. This error occurred within the Intercept/Hybrid player hider and can be temporarily avoided by setting PlayerHider to Prevention in the PV configuration file. Please report this error if you are already using the latest version of ProtocolLib and PV.

**Comment by lukalt** [comment]
PremiumVanish has not been updated to 1.20 yet. That's why it is not working. This is not the problem here. Contact the developer of the plugin so they can update it.

**Comment by PABLORAGNIzc** [comment]
> PremiumVanish aún no se ha actualizado a 1.20. Por eso no funciona. Este no es el problema aquí. Póngase en contacto con el desarrollador del complemento para que puedan actualizarlo.

Okay, thank you my friend for your prompt and respectful response for someone who does not have a lot of experience with these things. 10/10
