### ISSUE TITLE
No skin, no player in tab

### ISSUE THREAD

**Issue by MrCrazyKill** [dmulloy2/ProtocolLib#244]
Hi, i'm french so my english is bad :'( .
When i install your plugin, in the tab, is there no player and i dont have my skin :'( i have ProtocolLib 3.7
and Spigot 1.8.8

**Comment by MrCrazyKill** [comment]
I have a lot of plugin (51 plugin) so can you give me a list of plugin that make bug protocollib

**Comment by dmulloy2** [comment]
I feel like I respond to this ticket every week. If you have AuthMe, it's AuthMe. If not, run /protocol dump and paste the output with pastebin.

**Comment by MrCrazyKill** [comment]
Ok thank you i have it but i can't take off authme

**Comment by games647** [comment]
Just update AuthMe to a dev-build or disable the hideTablist feature in the config.

**Comment by MrCrazyKill** [comment]
Thanks ! It work

**Comment by games647** [comment]
@MrCrazyKill Then please close this.

**Comment by Memermint** [comment]
Ok I downloaded AuthMe dev-build tab list issue was fixed but now I can't even walk after login...

**Comment by games647** [comment]
This has nothing to do with ProtocolLib.

**Comment by Memermint** [comment]
Is here any other possibility how to fix it exception install AuthMe dev-build ?

**Comment by games647** [comment]
@Memermint https://github.com/Xephi/AuthMeReloaded/issues/875

**Comment by Memermint** [comment]
@games647 Thank you for your assistance and service, I fixed it and I'll rethink my review to 5 stars!
Thank you so much!
