### ISSUE TITLE
[DEV] How can I HIDE particle effects from hidden players?

### ISSUE THREAD

**Issue by Rhywenny** [dmulloy2/ProtocolLib#245]
Hi,
I'm trying to hide the particles of hidden players. In spigot, they said to me that I would use ProtocoLib, but I've never used it to do this. Can anyone help me with this code or sending me a link of this?
Thanks in advance!

**Comment by dmulloy2** [comment]
I would take a look at the particle packet: http://wiki.vg/Protocol#Particle
