### ISSUE TITLE
NPE on playSleepAnimation

### ISSUE THREAD

**Issue by bengalman** [dmulloy2/ProtocolLib#246]
Protocol Dump: http://pastebin.com/aufQSy39
Console Output: http://pastebin.com/4047TheS
Server is running 1.10, building against 1.10, and I am using ProtocolLib 4.0.1
Current code:
`public void startTask(Player p) {
        **playSleepAnimation(p);**
    	startCountdown(p);
    }

    **private void playSleepAnimation(Player asleep) {**
        final PacketContainer bedPacket = manager.createPacket(PacketType.Play.Server.BED, false);
        final Location loc = asleep.getLocation();
        
        // http://wiki.vg/Protocol#Use_Bed
        bedPacket.getIntegers().write(0, asleep.getEntityId());
         
        bedPacket.getBlockPositionModifier().write(0, new BlockPosition(loc.getBlockX(), loc.getBlockY() + 1, loc.getBlockZ()));
         
         
        broadcastNearby(asleep, bedPacket);
    }
    private void stopSleepAnimation(Player sleeping) {
        final PacketContainer animation = manager.createPacket(PacketType.Play.Server.ANIMATION, false);
        
        // http://wiki.vg/Protocol#Animation
        animation.getEntityModifier(sleeping.getWorld()).write(0, sleeping);
        animation.getIntegers().write(1, 2);
        
        broadcastNearby(sleeping, animation);
    }
    private void broadcastNearby(Player asleep, PacketContainer bedPacket) {
        for (Player observer : manager.getEntityTrackers(asleep)) {
            try {
                manager.sendServerPacket(observer, bedPacket);
            } catch (InvocationTargetException e) {
                throw new RuntimeException("Cannot send packet.", e);
            }
        }
    }`

The line numbers in the console output (100 and 106) correspond to the bold lines. startTask is called in an event and the value passed into it is event.getPlayer().

**Comment by dmulloy2** [comment]
This looks to be a pretty standard NPE, check if the ProtocolManager or Player is null. I only see one bold line though.

**Comment by bengalman** [comment]
Sorry the formatting got messed up when trying to add bold lines to code. The line with two stars (*) is the second bold line. I'll test debug outputs as soon as I'm home :)

**Comment by dmulloy2** [comment]
Any more info on this?
