### ISSUE TITLE
"Chunk getEntities call" Console spamming

### ISSUE THREAD

**Issue by Jqstln** [dmulloy2/ProtocolLib#2462]
- [ ] This issue is not solved in a development build

**Describe the bug**
My console has been spamming this error constantly. The error is too big to paste here, so here's the link. 
https://mclo.gs/IAehbqE

**Expected behavior**

**Screenshots**

**Version Info**
ProtocolLib Version: ProtocolLib v5.1.0-SNAPSHOT-654
Bukkit Version: 1.20-R0.1-SNAPSHOT
Server Version: git-Purpur-1990 (MC: 1.20)
Java Version: 17.0.7

Full PL logs; https://mclo.gs/1JQGQVC

**Additional context**

**Comment by lukalt** [comment]
Update IllegalStack to version `2.9.2a`

**Comment by Jqstln** [comment]
Looks like that fixed the issue! Thanks!
