### ISSUE TITLE
.getProtocolManager().getProtocolVersion(player); return 47

### ISSUE THREAD

**Issue by Regomy** [dmulloy2/ProtocolLib#2463]
Protocollib v5.0.0 latest
Server version 1.8.8

When a player logs in with any version, running .getProtocolManager().getProtocolVersion(player); returns 47, even if his version is 1.20. Why? Obviously it's the server version, but why does it return the server version? And if it should be, how can I get the player version without nms and and 3rd party API?

**Comment by derklaro** [comment]
You're probably using one of the plugins that allows player with a newer version of mc to join your older server. Use their api to get the players actual protocol version instead.
