### ISSUE TITLE
Tab list players disappear

### ISSUE THREAD

**Issue by Memermint** [dmulloy2/ProtocolLib#247]
I have one problem.. when I installed this plugin my players on server tab list disappeared

http://pastebin.com/xysd8DMn

No errors in console

**Comment by games647** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/244

**Comment by dmulloy2** [comment]
@AuthMe @sgdc3 @ljacqu

Please fix this or inform your users about this, I feel like I'm responding to the same ticket over and over again.
