### ISSUE TITLE
Async Packets Bug with 1.8 minecraft versions, with 5.0 protocolLib versions 

### ISSUE THREAD

**Issue by HeenoDev** [dmulloy2/ProtocolLib#2474]
I'm in 1.8.8
With the latest Build of protocolLib (I have already tried with the stable version of 5.0).
He the problem is when I upgrade the Protocol Version at 5.0 at least, (I need to have it at 5.0), it shows me some "armor bugs", for armor stands, holograms from holographic displays and for armor on players.

So to reproduce this, unload / load chunks several time and you will se some of your armors stands with no "VISUAL" armors. same for players, kill them, get back, do it several time and you will definitely have this bug.

![2023-07-07_20 05 43](https://github.com/dmulloy2/ProtocolLib/assets/113239428/ec0fbf12-a3dd-4f2a-8c3f-e63328cf91f3)

**Comment by HeenoDev** [comment]
Same problem with chat, there is some problems like lines is not displayed in ordrers

**Comment by HeenoDev** [comment]
hello???

**Comment by lukalt** [comment]
Please share the output of `/protocol dump`

**Comment by HeenoDev** [comment]
[dump-2023-07-13_01.20.13.txt](https://github.com/dmulloy2/ProtocolLib/files/12034440/dump-2023-07-13_01.20.13.txt)

here it is !
and yes sorry i'm juste i little bit stressing it's kind of urgent so.. ^^

**Comment by HeenoDev** [comment]
then?

**Comment by HeenoDev** [comment]
It's urgent please

**Comment by lukalt** [comment]
It's hard to tell what is going wrong here as you are using a lot of closed source plugin that use ProtocolLib. 

Please first verify that it caused by ProtocolLib by just putting ProtocolLib and no other plugins on the server.
Then add each of your plugins one after another and check when the problems starts to occur so we know somewhat of the source of your problem. 

From the dump you sent, I suspect that the problem is either zTournament or PvpGambling. Both plugins seem to implement the same Entity Hider - maybe this conflicts and causes this problem.

**Comment by HeenoDev** [comment]
Okay so I've tested if pvpgambling and zTournement, and ztournement was the problem, thank you to help me I really appreciate like really ! thank you very much !

but the chat is still broken, with the 2 disabled

**Comment by lukalt** [comment]
Okay, good to here.
What's wrong with the chat? I guess it is probably also caused by another plugin that is incompatible with ProtocolLib

**Comment by HeenoDev** [comment]
hum I don't know, but like the lines is not in order, like I have the title down and the texte up, is not supposed to be like this

**Comment by HeenoDev** [comment]
Ok I foud It thanks you very much I really appreciate !

**Comment by xXkguyXx** [comment]
Can confirm I see similar issues with v5 (mainly with holograms and chat not working). Last v4 (4.8.0 I think it was?) build woks without any issues. Handful of private plugins however.

**Comment by derklaro** [comment]
Without any code to reproduce it's nearly impossible to find the cause of this. We need at least some working code to get the issue running and some steps to then actually see the issue that you're describing.
