### ISSUE TITLE
OpenJ9 java conflict

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#2475]
**Describe the bug**
JAVA 8 - OpenJ9 java issues

**To Reproduce**
1. Run server 
2. See this error https://pastes.dev/NKNcQowrLZ

**Expected behavior**
With java openj9 conflict
@dmulloy2

**Comment by dmulloy2** [comment]
OpenJ9 isn't supported due to differences in how it handles reflection. I'd recommend using a hotspot JDK
