### ISSUE TITLE
Java Exception Server 1.8.9

### ISSUE THREAD

**Issue by Draecal** [dmulloy2/ProtocolLib#248]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ x ] You're using the latest build for your server version
- [ x ] This isn't an issue caused by another plugin
- [ x ] You've checked for duplicate issues

Debug paste link: https://bpaste.net/show/c19010958505

Description and relevant errors: Plugin related **Ucars**, **UcarsTrade**, **Uflight**

**Comment by games647** [comment]
That's an error in Car Lock.

**Comment by dmulloy2** [comment]
I don't see ProtocolLib anywhere in that stack. Report this to the author of CarLock

**Comment by Draecal** [comment]
**Carlock** was working fine until I updated **ProtocolLib** to the latest version

**Comment by games647** [comment]
CarLock doesn't even use ProtocolLib.

**Comment by games647** [comment]
I see two potential causes which are both completely independent from ProtocolLib.

First the plugin calls eject, but then calls getVehicle on the player afterwards although the player is already ejected. 

Second vehicle.getCustomName() could be null, so
```java
e.getVehicle().getCustomName().equals(null)
```
could create a NPE too.
