### ISSUE TITLE
Publish the library to modrinth

### ISSUE THREAD

**Issue by spartacus04** [dmulloy2/ProtocolLib#2481]
- [x] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**
When publishing a plugin to Modrinth I can add a dependency for each release. Unfortunately the website doesn't allow to add external urls so I can't add Protocollib to it and I have to manually specify to download protocollib

**Describe the solution you'd like**
Publishing the library to modrinth

**Describe alternatives you've considered**
Just add a manual link to the library in the readme of the mod but it's not consistent with how the website works

**Comment by zefir-git** [comment]
This is closed as completed but the plugin doesn’t seem to be on Modrinth.

**Comment by Neboer** [comment]
Please publish this plugin to Modrinth. There are already a lot of minecraft automation workflows worked for Modrinth. It will help many developers and server maintainers.
