### ISSUE TITLE
Hello, This is the problem I encountered during the opening process

### ISSUE THREAD

**Issue by starlightgl** [dmulloy2/ProtocolLib#2483]
This is the problem I encountered on the 1.20.1 server, which will appear across servers, the server side is waterfull, and the plugin version is 5.0
This happens when players cross servers
![(2FO_E0_F_HQSB~X1~`PHGM](https://github.com/dmulloy2/ProtocolLib/assets/139604919/2eba1619-9977-45cc-8439-dc9667b320c2)
![8C BJ`D2C X%YRI{J})`P)6](https://github.com/dmulloy2/ProtocolLib/assets/139604919/c39712c3-9bee-46b7-bb33-cecde0cfccbb)

**Comment by lukalt** [comment]
Use the latest development build for 1.20.1 support: https://ci.dmulloy2.net/job/ProtocolLib/661/

**Comment by starlightgl** [comment]
> 使用最新的开发版本支持 1.20.1：https://ci.dmulloy2.net/job/ProtocolLib/661/

This version still doesn't solve it

**Comment by starlightgl** [comment]
Whenever a player teleports across servers, this yellow error will appear in the background, and players with OP permissions will receive white messages madly, and it seems that they will stop reporting errors after the cross-server transmission is completed
![R9NBTZ S7A~8B1$}PV5B2DN](https://github.com/dmulloy2/ProtocolLib/assets/139604919/8a1bd08c-04f4-4533-acfd-2d046989cc6d)

**Comment by starlightgl** [comment]
![LUZ}%E4SLT%{T~VO {1VC5](https://github.com/dmulloy2/ProtocolLib/assets/139604919/0d5d46b4-a682-45a1-9477-89942a050e3b)
This is the second half

**Comment by lukalt** [comment]
Please send the whole log of the server a file and the output of the "/protocol dump" command. Otherwise we can't help here

**Comment by starlightgl** [comment]
This is the first server
[dump-2023-07-16_02.19.37.txt](https://github.com/dmulloy2/ProtocolLib/files/12062450/dump-2023-07-16_02.19.37.txt)
This is the second server
[dump-2023-07-16_02.20.41.txt](https://github.com/dmulloy2/ProtocolLib/files/12062456/dump-2023-07-16_02.20.41.txt)
