### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by audiodk** [dmulloy2/ProtocolLib#2484]
- [x] This issue is not solved in a development build

**Describe the bug**
I get this error with latest dev build #661.

**To Reproduce**
1. Go to 'NPC'
2. Click on 'any menu option'

**Expected behavior**

**Screenshots**

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin](https://pastebin.com/9vZ16L4L).

**Additional context**
Nothing that I can understand

**Comment by lukalt** [comment]
Update the IllegalStack plugin to the latest version: https://www.spigotmc.org/resources/dupe-fixes-illegal-stack-remover.44411/update?update=508650
