### ISSUE TITLE
Is the plugin gonna ba Update to 1.20.1 ?

### ISSUE THREAD

**Issue by Just1Chat** [dmulloy2/ProtocolLib#2488]
I try to use the simple voice chat plugin with the protocollibs plugin but its say that is in the 1.19 version maybe its because of that is any version of 1.20 exist i cant find it ?

**Comment by lukalt** [comment]
You can download the development build for MC 1.20.1 here: https://ci.dmulloy2.net/job/ProtocolLib/661/
