### ISSUE TITLE
When is ProtocolLib 1.20.x Coming out?

### ISSUE THREAD

**Issue by Blxodys** [dmulloy2/ProtocolLib#2489]
I kinda want to use some plugins but I don't want it to malfunction and Stuff!
If I could please get an answer thanks!

**Comment by lukalt** [comment]
You can download the latest development build here: https://ci.dmulloy2.net/job/ProtocolLib/661/
This version has been tested and should work without any problems. Please keep in mind that the plugins you are using also need to be updated to 1.20.1 and to the latest Minecraft Protocol. However that are only minor changes from 1.19.4 to 1.20.1.
