### ISSUE TITLE
[BUG] Fake Item Display Vanishes when Applying Translation and Scale Vector

### ISSUE THREAD

**Issue by Dearliet** [dmulloy2/ProtocolLib#2492]
When attempting to spawn a fake item display using ProtocolLib, applying the translation and scale vector causes the itemstack of the display entity to vanish.

<br>

**Steps to Reproduce:**
1. Install the following dependencies:
```xml
<dependency>
    <groupId>io.papermc.paper</groupId>
    <artifactId>paper-api</artifactId>
    <version>1.20.1-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>com.comphenix.protocol</groupId>
    <artifactId>ProtocolLib</artifactId>
    <version>5.0.0</version>
    <scope>provided</scope>
</dependency>
```
2. Copy and paste [this code snippet](https://gist.github.com/Dearliet/8256d015c992852c87fa8b01bd328b7c#file-example-kt) which is responsible for spawning the fake item display with the help of the two packet wrapper classes, `WrapperPlayServerEntityMetadata` and `WrapperPlayServerSpawnEntity`.

**Comment by Dearliet** [comment]
Not a bug, someone helped me find a solution. 
All you have to do is utilize the`org.joml.Vector3f` class for serialization instead of using `getVectorSerializer()`:

```kotlin
val vectorSerializer = WrappedDataWatcher.Registry.get(Vector3f::class.javaObjectType)
val translation = WrappedDataWatcher.WrappedDataWatcherObject(10, vectorSerializer)
val scale = WrappedDataWatcher.WrappedDataWatcherObject(11, vectorSerializer)
val watcher = WrappedDataWatcher()
watcher.setObject(translation, Vector3f(0f, 0f, 0f))
watcher.setObject(scale, Vector3f(1f, 1f, 1f))
```

**Comment by JVerbruggen** [comment]
Not a solution, Vector3F should be able to be used alongside the VectorSerializer.  @dmulloy2 
Bumping against this as well with error:
```
java.lang.ClassCastException: class com.comphenix.protocol.wrappers.Vector3F cannot be cast to class net.minecraft.core.Vector3f (com.comphenix.protocol.wrappers.Vector3F is in unnamed module of loader 'ProtocolLib (6).jar' @587bf368; net.minecraft.core.Vector3f is in unnamed module of loader java.net.URLClassLoader @759ebb3d)
```

Yes changing it to minecraft vector3f would work, but thats not what is correct I suppose?
