### ISSUE TITLE
Memory leak volatileField ?

### ISSUE THREAD

**Issue by Likaos** [dmulloy2/ProtocolLib#25]
Hello,

Here is a DUMP from a java heap crash, as you can see I have a ton of finaliser object that are never cleaned http://puu.sh/dIoAC/c128c1bc07.png

Its from the last 1.7.10 build available #10 from your protocollib, for the moment i'm still in 1.7.10 and I cannot test with 1.8 build for the moment, it happen slowly after ~16 Hours of uptime and above 30000 unique players loggon (hub server).

Do you know this leaks ? Did you fixed it ? Can it come from an other plugin using Protocollib (I'm using libdisguise for example).

Thanks !

**Comment by dmulloy2** [comment]
That doesn't seem like an issue with ProtocolLib. Finalizers aren't explicitly used.
