### ISSUE TITLE
How to set the container type for P.S.OPEN_SCREEN?

### ISSUE THREAD

**Issue by tinyoverflow** [dmulloy2/ProtocolLib#2506]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
I would like to send a OPEN_SCREEN package to the player. Unfortunately I'm not able to set the [container type](https://wiki.vg/Inventory). It seems to use an `InternalStructure` with a handle of `net.minecraft.world.inventory.Containers` and I'm not sure if and how I can set that with ProtocolLib.

**Code**

```java
PacketContainer packet = manager.createPacket(PacketType.Play.Server.OPEN_WINDOW);
packet.getIntegers().write(0, id);
// How to set the container type?
packet.getChatComponents().write(0, WrappedChatComponent.fromText(title));
```

**Comment by ThomasMo54** [comment]
Same question here. Still no answer ?

**Comment by tinyoverflow** [comment]
No, unfortunately not.

**Comment by Tobies** [comment]
Same issue, Did you find a solution?
