### ISSUE TITLE
ProtocolLib taking large part of server thread.

### ISSUE THREAD

**Issue by legendcuzican13** [dmulloy2/ProtocolLib#2508]
Well, this really isn't much of a bug, but I'm more so wondering if there is anything to be done that can help ProtocolLib causing much lag on my server.

**To Reproduce**
Add plugin to server.

**Expected behavior**
ProtocolLib taking up less of the thread.

![Screenshot (68)](https://github.com/dmulloy2/ProtocolLib/assets/108838775/9522aba4-f8af-422c-b92f-2f67c929004c)

**Version Info**
https://pastebin.com/nG78Ekg7

**Comment by MeowIce** [comment]
![image](https://github.com/dmulloy2/ProtocolLib/assets/70711319/08801c76-dbd1-422f-b15a-8d331f266371)
I dont have this problem

**Comment by dmulloy2** [comment]
can you drill down on that entry? a lot of things go through the event loop proxy. could be a rogue listener

**Comment by legendcuzican13** [comment]
Hey @dmulloy2 thanks for the quick response. 

I've drilled it down some more in this SS

![Screenshot_20230814_102023_Chrome](https://github.com/dmulloy2/ProtocolLib/assets/108838775/ee58a41f-64c0-4243-b551-3f26d3108d88)

**Comment by dmulloy2** [comment]
seems like there might be something wrong with your OS's netty library. might be worth looking into re-installing it

**Comment by legendcuzican13** [comment]
Ah alright, i'll try that.

**Comment by legendcuzican13** [comment]
@dmulloy2 Hey there, I just tried re installing netty, but noticed little to no difference in the results shown from the timings report. Is there possibly a different solution?

**Comment by legendcuzican13** [comment]
Ah I see, in that case I'll try removing plugins that are ProtocolLib dependent one by one and see if that indicates which one could possibly be rogue.

In any case, here's my plugin list incase that helps:

ProtocolLib, Citizens, WorldGuard, WorldEdit, Grim, Vulcan, LegendSMPCore(custom plugin), ChatControl(protocollib dependent), IllegalStack(protocollib dependent), CrazyAuctionsPlus, LP, LPC, Essentials, EssentialsSpawn, Skript, BeautyQuests, spark, CoreProtect, DiscordSRV, BuyCraftX, ClearLag, TabList, AdvancedBan, BetterGui, Multiverse, SkinsRestorer, Vault, and UltimateAutoRestart.

**Comment by legendcuzican13** [comment]
No success.

**Comment by dei15** [comment]
This is also happening to me 
![image](https://github.com/dmulloy2/ProtocolLib/assets/99554686/66d4de15-70b5-4dea-8f41-9e38d7cc2d76)

**Comment by dei15** [comment]
causing massive tps drops

**Comment by DereC4** [comment]
NettyEventLoopProxy.execute

Happening to me too

**Comment by dollannn** [comment]
Also experiencing this
