### ISSUE TITLE
ProtocolLib occupies thread problem

### ISSUE THREAD

**Issue by NewPixelDev** [dmulloy2/ProtocolLib#2513]
- [x] This issue is not solved in a development build

**Describe the bug**
Occupies extremely high threads on the server, causing the server to freeze and greatly reducing the fluency of the server.

**To Reproduce**
It is not clear for now.

**Expected behavior**
There should not be so many threads occupied, and it should not be the culprit of Caton!

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/129480648/8e6b6416-9dcd-493f-9fb5-60cee3384323)

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/Xz9Wjr7c)

**Additional context**
none.

**Comment by lukalt** [comment]
Hello,

the problem is caused by the Citiziens plugin (https://www.spigotmc.org/resources/citizens.13811/). Please refer to their support for help
