### ISSUE TITLE
Hello, do you plan to develop your api in 1.20.1? Thank you very much.

### ISSUE THREAD

**Issue by GithubErwan** [dmulloy2/ProtocolLib#2515]
**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.

**API method(s) used**
List what API method(s) you're using

**Expected behavior**

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by lukalt** [comment]
Hello, ProtocolLib is already available for 1.20.1. Is there any more problem with it?

**Comment by GithubErwan** [comment]
Strange because when I looked to install the API on spigot the latest version is 1.19 that's why I ask
