### ISSUE TITLE
Protocol Lib error on chat (1.8)

### ISSUE THREAD

**Issue by Skilles** [dmulloy2/ProtocolLib#252]
**Make sure you've done the following:**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

**Debug paste link:**
http://pastebin.com/jHdbKJmd
**Description and relevant errors:**
This happens whenever I chat. I suspect it might have to do with VentureChat and Protocol Lib interfering, but that shouldn't happen as Protocol Lib is a dependency of the chat plugin.

**Comment by Techno-Brony** [comment]
Same here, I'm getting that error as well. However, it isn't interfering with chat in a way I can notice. Everything seems fine except I get that error.

**Comment by dmulloy2** [comment]
Oh hey an actual bug! That's kind of refreshing actually. I'll give it a look.
