### ISSUE TITLE
Plugin using way too much server thread

### ISSUE THREAD

**Issue by TheProOne1** [dmulloy2/ProtocolLib#2524]
- [ ] This issue is not solved in a development build

Why is this plugin using so much server thread? This is ridiculous. How do I fix this?

![image](https://github.com/dmulloy2/ProtocolLib/assets/143269084/84839ed8-88af-4a06-b582-d4ca54233ceb)

**Comment by lubaskinc0de** [comment]
![image](https://github.com/dmulloy2/ProtocolLib/assets/100635212/c492a353-7376-4205-b0ce-ae067826364f)
similar issue

**Comment by lukalt** [comment]
As far as I am concerned, this is not a problem of ProtocolLib but rather a problem of the Minecraft Server and Netty itself. ProtocolLib just intercepts the packet processing and that's the reason why it shows up for ProtocolLib in the timings/traces.
Maybe @derklaro can help here

**Comment by derklaro** [comment]
Yea, thats a sync listener problem. ProtocolLib just calls the packet listeners, therefore it shows up. The Epoll write should be in a netty event loop thread and not on the main thread.
