### ISSUE TITLE
Entity Destroy packet crashing client

### ISSUE THREAD

**Issue by Craftiii4** [dmulloy2/ProtocolLib#253]
Hey, I've been unable to fix this.

When updating a plugin to 1.10 the client crashes when sending an Entity_Destroy packet for an entity spawned through an SPAWN_ENTITY_LIVING packet.

I'm unsure if I'm doing something wrong here, I've looked but can't find working code.

Sending this packet, results in the client crashing:
```
PacketContainer destroyEntity = new PacketContainer(PacketType.Play.Server.ENTITY_DESTROY);
destroyEntity.getIntegerArrays().write(0, new int[] { IDStored.get(p.getUniqueId()) });
```

Adding this line (as the [protocol](http://wiki.vg/Protocol#Destroy_Entities) specifies, to let it know how many items are in the array), results in an console error
`
destroyEntity.getIntegers().write(0, 1);
`

& the error here: http://pastebin.com/AYFKXesR

Any idea how to fix?
Thanks in advance.

**Comment by NorthPL** [comment]
PacketPlayOutEntityDestroy.class has only one field - array of integers. Array size is obtained automatically (in b(PacketDataSerializer) method). So you can't set array size manually.

I think that you simply send bad entity ID. Check what is returned by IDStored.get(p.getUniqueId()) and ensure that is entity currently visible by player.

**Comment by dmulloy2** [comment]
I'm pretty sure you could just use ````Player#getEntityId````, no real need for a map to store it.

**Comment by Craftiii4** [comment]
I use the packet to destroy a horse entity, the map is used to determine the ID of the horse. The ID alternates as the player customizes their horse

Sorry for wasting your time, turns out the issue was not with the destroy packet at all, but with the spawn packet. I was accidentally setting the metadata value over the incorrect field(caused by the gravity field), causing the client to crash when the horse was despawned then respawned again after . 

As the horse always appeared the first time I had (incorrectly) assumed the destroy packet was causing the issue. 

Thanks for your help
