### ISSUE TITLE
Build #232 #222 and others: Error on player join

### ISSUE THREAD

**Issue by RedEpicness** [dmulloy2/ProtocolLib#254]
Debug paste link: http://pastebin.com/f4Z4n5VV

Description and relevant errors: 

I tried using ProtocolLib for my Spigot server running 1.7.10. On player join event, this following error appears: http://pastebin.com/7XF5nP4R
I tried using builds #232 which is the recommended for 1.7.x, #222, #303, #291, #280, #252 with the same error popping up. There are custom coded plugins on the server, but the log doesn't show any sign of them nor do they modify packets in any way. I am also running BungeeCord Build #1119 if that is relevant.

EDIT: /packet names also throws a similar error about not finding the field null in ChannelManager...

**Comment by dmulloy2** [comment]
Try the 3.7.0 release: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0

**Comment by RedEpicness** [comment]
That worked without the previous error, thanks a lot! It did say this when i joined though, if it's relevant:
`[17:51:52 INFO]: [ProtocolLib] Unable to find org.spigotmc.ProtocolData$ByteShort

[17:51:52 INFO]: [ProtocolLib] Unable to find org.spigotmc.ProtocolData$DualByte

[17:51:52 INFO]: [ProtocolLib] Unable to find org.spigotmc.ProtocolData$HiddenByte

[17:51:52 INFO]: [ProtocolLib] Unable to find org.spigotmc.ProtocolData$IntByte

[17:51:52 INFO]: [ProtocolLib] Unable to find org.spigotmc.ProtocolData$DualInt
`

**Comment by dmulloy2** [comment]
Don't worry about those. I'm not entirely sure what ProtocolData was, but it's not a thing anymore. I'll remove the messages.

**Comment by RedEpicness** [comment]
Thanks for the help! :)
