### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by LittleDuck363** [dmulloy2/ProtocolLib#2544]
27.09 17:56:20 [Server] [INFO] java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
27.09 17:56:20 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
27.09 17:56:20 [Server] [INFO] at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
27.09 17:56:20 [Server] [INFO] at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
27.09 17:56:20 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
27.09 17:56:20 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
27.09 17:56:20 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
27.09 17:56:20 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
27.09 17:56:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
27.09 17:56:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
27.09 17:56:20 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:833)
27.09 17:56:20 [Server] [INFO] Dump:
27.09 17:56:20 [Server] [INFO] Parameters: 
27.09 17:56:20 [Server] [INFO] [NULL]
27.09 17:56:20 [Server] [INFO] Sender:
27.09 17:56:20 [Server] [INFO] com.comphenix.protocol.ProtocolLib@4288dc09[
27.09 17:56:20 [Server] [INFO] statistics=<null>
27.09 17:56:20 [Server] [INFO] packetTask=<null>
27.09 17:56:20 [Server] [INFO] tickCounter=0
27.09 17:56:20 [Server] [INFO] configExpectedMod=-1
27.09 17:56:20 [Server] [INFO] updater=com.comphenix.protocol.updater.SpigotUpdater@2ec4d230
27.09 17:56:20 [Server] [INFO] redirectHandler=<null>
27.09 17:56:20 [Server] [INFO] scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6991e720
27.09 17:56:20 [Server] [INFO] commandProtocol=<null>
27.09 17:56:20 [Server] [INFO] commandPacket=<null>
27.09 17:56:20 [Server] [INFO] commandFilter=<null>
27.09 17:56:20 [Server] [INFO] packetLogging=<null>
27.09 17:56:20 [Server] [INFO] skipDisable=false
27.09 17:56:20 [Server] [INFO] isEnabled=false
27.09 17:56:20 [Server] [INFO] loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@67c4d02a
27.09 17:56:20 [Server] [INFO] server=CraftServer{serverName=Paper,serverVersion=git-Paper-"298c478",minecraftVersion=1.20.2}
27.09 17:56:20 [Server] [INFO] file=plugins/ProtocolLib.jar
27.09 17:56:20 [Server] [INFO] description=org.bukkit.plugin.PluginDescriptionFile@6bf52b58
27.09 17:56:20 [Server] [INFO] pluginMeta=org.bukkit.plugin.PluginDescriptionFile@6bf52b58
27.09 17:56:20 [Server] [INFO] dataFolder=plugins/ProtocolLib
27.09 17:56:20 [Server] [INFO] classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
27.09 17:56:20 [Server] [INFO] naggable=true
27.09 17:56:20 [Server] [INFO] newConfig=YamlConfiguration[path='', root='YamlConfiguration']
27.09 17:56:20 [Server] [INFO] configFile=plugins/ProtocolLib/config.yml
27.09 17:56:20 [Server] [INFO] logger=com.destroystokyo.paper.utils.PaperPluginLogger@4cbfbdfc
27.09 17:56:20 [Server] [INFO] ]
27.09 17:56:20 [Server] [INFO] Version:
27.09 17:56:20 [Server] [INFO] ProtocolLib v5.1.0
27.09 17:56:20 [Server] [INFO] Java Version:

**Comment by lukalt** [comment]
ProtocolLib v5.1.0 is not compatible with MC 1.20.2. Please use this development build: https://ci.dmulloy2.net/job/ProtocolLib/669/
