### ISSUE TITLE
Problem with protocollib

### ISSUE THREAD

**Issue by MetinCZ** [dmulloy2/ProtocolLib#255]
Hello i have a problem with plugin protocollib.  
Bugs:
Players is invisible and tab is empty. 

Pastebin here: http://pastebin.com/dN48WUuG
Screenshot TAB here: https://ctrlv.cz/OnIL
"language is czech" 
please help me. 
Thanks
(Sorry for my english.)

**Comment by dmulloy2** [comment]
AuthMe.

**Comment by MetinCZ** [comment]
Thank you!  Have a nice day
