### ISSUE TITLE
initialize 

### ISSUE THREAD

**Issue by polimpo4** [dmulloy2/ProtocolLib#2558]
Starting minecraft server **1.20.1 craftbukkit**. With the **latest version of ProtocolLib and version 5.1.0** both have the same problem.
After the server gives "done" it displays an error:

[19:19:47] [Server thread/INFO]: Done (13.847s)! For help, type "help"
[19:19:48] [Server thread/INFO]: Error Cannot perform automatic updates. (java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null) occurred in ProtocolLib v5.1.0.
[19:19:48] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:540)
        at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:511)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1208)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:374)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1155)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:980)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7b772d1d[
        plugin=ProtocolLib v5.1.0
        server=CraftServer{serverName=CraftBukkit,serverVersion=3871-Bukkit-3f9263b,minecraftVersion=1.20.1}
        reporter=com.comphenix.protocol.ProtocolLib$1@3a6c93ee
        minecraftVersion=(MC: 1.20.1)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5b42b486
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@199f6536
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2d9290b3
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@733f950c
        registeredListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=15]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@3d97e969
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5f439d38
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@666d996b
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@6b2b87a9[
      statistics=com.comphenix.protocol.metrics.Statistics@28426da9
      packetTask=com.comphenix.protocol.scheduler.DefaultTask@226e0f0b
      tickCounter=20
      configExpectedMod=1
      updater=<null>
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@64e7cb06
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@53460efc
      commandProtocol=com.comphenix.protocol.CommandProtocol@68520e18
      commandPacket=com.comphenix.protocol.CommandPacket@3a96424e
      commandFilter=com.comphenix.protocol.CommandFilter@60f311e1
      packetLogging=com.comphenix.protocol.PacketLogging@3a1c2ed
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@7b7b2e4f
      server=CraftServer{serverName=CraftBukkit,serverVersion=3871-Bukkit-3f9263b,minecraftVersion=1.20.1}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@73f7875c
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@12267ddc
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@6c8e1f3
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.8
  Server:
    3871-Bukkit-3f9263b (MC: 1.20.1)

>[19:19:48] [Server thread/INFO]: Error Cannot perform automatic updates. (java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null) occurred in ProtocolLib v5.1.0.
>[19:19:48] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
>  If this problem hasn't already been reported, please open a ticket
>  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>  Stack Trace:
>  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
>        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:540)
>        at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:511)
>        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77)
>        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
>        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1208)
>        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:374)
>        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1155)
>        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:980)

**Comment by lukalt** [comment]
ProtocolLib 5.1.0 does not support Minecraft 1.20.1. Please use the latest release of ProtocolLib: https://github.com/dmulloy2/ProtocolLib/releases/download/5.1.0/ProtocolLib.jar.
