### ISSUE TITLE
NullPointerEx. at onPacketReceiving

### ISSUE THREAD

**Issue by MeGysssTaa** [dmulloy2/ProtocolLib#256]
**Description and relevant errors:**
Hello. One user of one of my plugins reported me the following error: http://pastebin.com/wK608WfK
Most of stacktrace elements are related to ProtocolLib packages and not to mine. The 'onPacketReceiving' method listens for USE_ENTITY packets sent by player.

**Server version:** 1.7
**ProtocolLib version:** 3.7
**Java version:** 1.8

That's all I have.

**Comment by dmulloy2** [comment]
Could you provide the source of the onPacketReceiving method?

**Comment by Shevchik** [comment]
You are trying to get field that doesn't exist most likely

**Comment by MeGysssTaa** [comment]
https://gist.github.com/MeGysssTaa/74b8acea096fd4d642131eb07d7a9f4c

**Comment by dmulloy2** [comment]
I don't see where you're accessing ProtocolLib in that gist.

**Comment by dmulloy2** [comment]
Any more info on this?
