### ISSUE TITLE
Listening for custom payload packets does not work on protocollib 1.20.2

### ISSUE THREAD

**Issue by ThrowerWay** [dmulloy2/ProtocolLib#2561]
- [X] This issue is not solved in a development build

**Describe the bug**
Listening for custom payload packets does not work on protocollib 1.20.2

**To Reproduce**
Make a packet listener for custom payload

**Expected behavior**
Should detect it from player, doesnt.

**Screenshots**

**Version Info**
5.1.1-SNAPSHOT-669

**Comment by Waterman1001** [comment]
Perhaps this issue is related to my issue: #2552 
A fix would be highly appreciated!

**Comment by Waterman1001** [comment]
Thanks for your reply!
What kind of packet events are you using? Because for my own issue, specifically listening to Keep Alive packet and Pong packet is not working...
Indeed, it takes long for update unfortunately :(
