### ISSUE TITLE
NullPointerException when creating a WrappedVillagerData

### ISSUE THREAD

**Issue by KBD2** [dmulloy2/ProtocolLib#2563]
- [x] This issue is not solved in a development build

**Describe the bug**
Trying to create a `WrappedVillagerData` via `WrappedVillagerData.fromValues` causes a `NullPointerException`.

**To Reproduce**
1. Call `WrappedVillagerData.fromValues` with valid arguments.
 - e.g. `WrappedVillagerData.fromValues(WrappedVillagerData.Type.PLAINS, WrappedVillagerData.Profession.NONE, 1);`

**Expected behavior**
A new instance of `WrappedVillagerData` is created.

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/44832995/b34c3b2b-cd50-48b9-b66c-a25a20b82e26)

**Version Info**
ProtocolLib Version: ProtocolLib v5.1.1-SNAPSHOT-669
Bukkit Version: 1.20.1-R0.1-SNAPSHOT
Server Version: git-Paper-181 (MC: 1.20.1)
Java Version: 20.0.1

**Comment by wzard27** [comment]
bump - same error
