### ISSUE TITLE
Players can not join

### ISSUE THREAD

**Issue by UsefullSpoon** [dmulloy2/ProtocolLib#2565]
- [x] This issue is not solved in a development build

**Describe the bug**
Players who try to join get met with an error

**To Reproduce**
1. Have protocollib 5.1.1-snapshot-668
2. have someone join
3. error code (see pastebin)
4. **https://pastebin.com/zTn5tYvJ**

**Expected behavior**
players being able to join

**Screenshots**
no screenshot needed. pastebin has everything

**Version Info**
https://pastebin.com/jjNndka0

**Additional context**
-

**Comment by lukalt** [comment]
Hi, it looks like you are using an outdated Version of Citizens. Please update to their latest version and try again: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by UsefullSpoon** [comment]
updated to the latest supported citizens. Still having issues

**Comment by lukalt** [comment]
Could you than please share the whole server log so we can see what other plugins might cause problems with ProtocolLib?

**Comment by UsefullSpoon** [comment]
**https://pastebin.com/0TGFT7wi**
