### ISSUE TITLE
vertion

### ISSUE THREAD

**Issue by OMKOAKRE12** [dmulloy2/ProtocolLib#2567]
**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.

**API method(s) used**
List what API method(s) you're using

**Expected behavior**

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by OMKOAKRE12** [comment]
which version supports Minecraft 1.20

**Comment by chrydin** [comment]
lastest version 5.1.0 works until 1.20.1; last dev build is in the works and works partially.
