### ISSUE TITLE
"Unload Chunk" packet does not return integers (1.20.2)

### ISSUE THREAD

**Issue by DaJokni** [dmulloy2/ProtocolLib#2571]
- [x] This issue is not solved in a development build

**Describe the bug**
While listening to the unload chunk packet, trying to get the integers from the packet returns nothing, this worked on 1.20.1.

**To Reproduce**
listen to PacketEvent, check if packettype is unload chunk &:
`StructureModifier<Integer> integers = event.getPacket().getIntegers();
System.out.println(integers);
`

**Expected behavior**
The integers should be available in the integers method.

**Version Info**
Build 669 on paper 1.20.2 build 234

**Additional context**
I believe #2569 could be related.

**Comment by lukalt** [comment]
Mojang changed the underlying packet. You now need to access `event.getPacket().getChunkCoordIntPairs()` instead

**Comment by DaJokni** [comment]
Thanks for the help, ive tested that and it seems to be working correctly now.
