### ISSUE TITLE
NamedEntitySpawn Packet is unknown 1.20.2

### ISSUE THREAD

**Issue by ch4ika** [dmulloy2/ProtocolLib#2577]
Plugin tried to register listener for unknown packet NAMED_ENTITY_SPAWN[PLAY, SERVER, 235, classNames: [net.minecraft.network.protocol.game.PacketPlayOutNamedEntitySpawn, net.minecraft.network.protocol.game.ClientboundNamedEntitySpawnPacket, net.minecraft.network.play.server.SPacketSpawnPlayer] (unregistered)] [direction: from SERVER]

**Comment by derklaro** [comment]
That packet was removed in 1.20.2 (the packet type is deprecated accordingly).

**Comment by ch4ika** [comment]
What should I use instead?

**Comment by Brokkonaut** [comment]
> What should I use instead?

SPAWN_ENTITY

**Comment by ch4ika** [comment]
thankyou

**Comment by 9mkpark9** [comment]
I'm getting the same error. It's version 1.20.2 and I'm trying to fix something like this in a file. Can you tell me a tutorial?
