### ISSUE TITLE
Not loading plugin 1.20.2

### ISSUE THREAD

**Issue by DetahMC** [dmulloy2/ProtocolLib#2582]
-20.10 15:33:03 [Server] INFO Stack Trace:
20.10 15:33:03 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.&lt;init&gt;(PacketFilterManager.java:120)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
20.10 15:33:03 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
20.10 15:33:03 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
20.10 15:33:03 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
20.10 15:33:03 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
20.10 15:33:03 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
20.10 15:33:03 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
20.10 15:33:03 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
20.10 15:33:03 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
20.10 15:33:03 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
20.10 15:33:03 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
20.10 15:33:03 [Server] INFO Dump:
20.10 15:33:03 [Server] INFO Parameters: 
20.10 15:33:03 [Server] INFO [NULL]
20.10 15:33:03 [Server] INFO Sender:
20.10 15:33:03 [Server] INFO com.comphenix.protocol.ProtocolLib@23d56d40[
20.10 15:33:03 [Server] INFO statistics=&lt;null&gt;
20.10 15:33:03 [Server] INFO packetTask=&lt;null&gt;
20.10 15:33:03 [Server] INFO tickCounter=0
20.10 15:33:03 [Multicraft] Skipped 51 lines due to rate limit (50.0/s)

**Comment by WOLFRAGE99** [comment]
Yea I'm having the same problem too. Sucks to see that your dealing with it. Best of luck man.

**Comment by haeLL420** [comment]
same issue (using purpur)

**Comment by lukalt** [comment]
ProtocolLib 5.1.0, which you are probably using, only support Minecraft 1.20.1. For 1.20.2 support, please use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib/669/
