### ISSUE TITLE
Configuration state packets

### ISSUE THREAD

**Issue by ValeraShimchuck** [dmulloy2/ProtocolLib#2586]
In 1.20.2(764 protocol) was added a configuration state. I need packets in the state, but in last(5.1.0) version seems new state is absent.

**Comment by lukalt** [comment]
You need the latest development build for 1.20.2 support: https://ci.dmulloy2.net/job/ProtocolLib/669/

**Comment by ValeraShimchuck** [comment]
-

**Comment by ValeraShimchuck** [comment]
How can I get this version through maven repo?

**Comment by molor** [comment]
How can I also get this version through maven repo?

**Comment by molor** [comment]
How can I also get this version through maven repository?

![image](https://github.com/dmulloy2/ProtocolLib/assets/19989717/4c3f4c41-50b5-4941-a1fa-70ce7fadb29c)

I'm already updated the sources and documentation several times for every project in IDEA, cleared all caches and restarted, but there's still no new configuration state packets added in https://github.com/dmulloy2/ProtocolLib/commit/03d7be13d0f5409be9c77c0505a383636a0a1c32 :/

![image](https://github.com/dmulloy2/ProtocolLib/assets/19989717/344a7b13-2b04-41e4-853d-d3276bbefa90)

**Comment by lukalt** [comment]
The version tag of the latest version is `5.1.1-SNAPSHOT`, not `5.1.0`. This version, however, is not provided to the nexus repository AFAIK.
So you need to install it locally:

```
# Clone the repository:
git clone https://github.com/dmulloy2/ProtocolLib.git

# Build the latest ProtocolLib version yourself:
./gradlew build

# Install the freshly built artifact to your local maven repository
./gradlew publishToMavenLocal
```

This might not be the most convenient solution, but you should be able to include ProtocolLib into your main POM now:

```
<dependency>
    <groupId>com.comphenix.protocol</groupId>
    <artifactId>ProtocolLib</artifactId>
    <version>5.1.1-SNAPSHOT</version>
   <scope>compile</scope>
</dependency>
```
