### ISSUE TITLE
Issue Loading ProtocolLib plugin

### ISSUE THREAD

**Issue by akaboydeve** [dmulloy2/ProtocolLib#2592]
Installing ProtocolLib in a new server giving error and the plugin is not loaded
![image](https://github.com/dmulloy2/ProtocolLib/assets/73843791/4dfbac07-0806-4e89-8ec9-475bc8d2eb77)

**Comment by DilanTheDev** [comment]
I got the same erorr

**Comment by OutHimic** [comment]
I'm sure that too! | 我也遇到了同样的问题!

**Comment by tadaroke** [comment]
I got the same erorr

**Comment by Dymeth** [comment]
Guys. just use dev builds from here: https://ci.dmulloy2.net/job/ProtocolLib/
