### ISSUE TITLE
Latest ProtocolLib does not work with Paper 1.20.2 while earlier ones does.

### ISSUE THREAD

**Issue by NamerPRO** [dmulloy2/ProtocolLib#2593]
- [x] This issue is not solved in a development build

**Describe the bug**
Motd is not set via ProtocolLib Snapshot 5.1.1-SNAPSHOT-673 on Paper 1.20.2 (# 249) server and a player cannot join server while with ProtocolLib 5.1.1-SNAPSHOT-669 same code works fine. There are no errors in console.

**To Reproduce**
1. Download AdvancedNMotd: https://www.spigotmc.org/resources/advancednmotd-let-your-motd-smile.58677/
2. Put it to Paper's 1.20.2 (# 249) plugins folder with ProtocolLib SNAPSHOT 673 (latest at the moment of writing report).
3. See that motd is not set and player cannot join server.
4. Replace ProtocolLib SNAPSHOT 673 with earlier SNAPSHOT 669.
5. See that motd is set correctly and player can join server.

**Expected behavior**
Motd must be set and player must have an access to join server.

**Screenshots**
When used with ProtocolLib SNAPSHOT 673 (latest at the moment of writing report):
![iimg](https://github.com/dmulloy2/ProtocolLib/assets/90556614/947a460b-e717-4b64-b3ee-a1bbeb866985)

When used with ProtocolLib SNAPSHOT 669:
![iimg](https://github.com/dmulloy2/ProtocolLib/assets/90556614/d2372061-875f-4518-94d2-95d4420b4383)

**Version Info**
https://pastebin.com/j1vhfvL6

**Comment by Dymeth** [comment]
Are you using TCPShield or any another plugins? Looks like it's some plugins incompatibility in ProtocolLib 1.5.1+. You can test it without any plugins, just ProtocolLib?

**Comment by Kar1nfil** [comment]
someone can send link to ProtocolLib SNAPSHOT 669? Version 1.20.2

**Comment by Dymeth** [comment]
> I do not use neither TCPShield not other plugins. I tested AdvancedNMotd being the only plugin at the server excluding ProtocolLIB before writing this issue.

Issue appears when using AdvancedNMotd too. So, if AdvancedNMotd isn't installed there are no any problems with ping or joining server.

I checked out the both plugins code (TCPShield and AdvancedNMotd) and find out that this is what is causing the ping and server connection problems. Is just enough to register packet adapter with packet PacketType.Handshake.Client.SET_PROTOCOL:
`@Override
public void onEnable() {
    ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, PacketType.Handshake.Client.SET_PROTOCOL) {
        @Override
        public void onPacketSending(PacketEvent event) {
        }
    });
}`
There are no any errors in the console, but the onPacketSending() method is not called.
Also connecting to the server becomes impossible ("Disconnected" error), and “Incompatible version!” is displayed in the list of servers.

TCPShield registration: https://github.com/TCPShield/RealIP/blob/bb7511d37f915ea1b8416ac24dd8564b9d3d0e20/src/main/java/net/tcpshield/tcpshield/bukkit/protocollib/handler/ProtocolLibHandshakeHandler.java#L18

AdvancedNMotd registration: https://github.com/NamerPRO/AdvancedNMotd/blob/b764e435696ca9b5fc0a0ef1a77e417261e9dee2/src/ru/namerpro/AdvancedNMotd/Bukkit/Main.java#L61
