### ISSUE TITLE
 ProtocolLib does not support plugin reloaders! Please use the built-in reload command!  

### ISSUE THREAD

**Issue by AikePetunia** [dmulloy2/ProtocolLib#2598]
- [ ] This issue is not solved in a development build

**Describe the bug**
Just installing the lastest relace (5.10) with Orebfuscator

**To Reproduce**
1. Install the lastest version on GitHub
2. Start the server
3. Ctrl + f "Protocol"

**Expected behavior**
Start without problems to make Orebfuscator work.

**Version Info**
5.10

https://pastebin.com/N0emge7V

**Additional context**
Geyser.

**Comment by Nagol12344** [comment]
Dont use the reload command or plugin reloaders, reloading plugins is known to break plugins untill you reboot.

**Comment by Dymeth** [comment]
Use dev builds from here: https://ci.dmulloy2.net/job/ProtocolLib/
