### ISSUE TITLE
Spectator mode does not work correctly

### ISSUE THREAD

**Issue by festchannel** [dmulloy2/ProtocolLib#260]
Hi, I have a problem on the server(spigot) 1.10.2 with version 4.0.2 of your plugin. In general, everything works well, but in a spectator mode no one can fly through the blocks. I checked all added at the time plugins: this is not Orebfuscator and not AntiCheatReloaded. As I understand it, your plugin should not change the gameplay so much.

**Comment by dmulloy2** [comment]
It doesn't change gameplay at all. One of your other plugins is causing this.

**Comment by festchannel** [comment]
Yes, after a few days of searching the information I have just now decided to upgrade AuthMe, and everything started working.
