### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LGLLewis** [dmulloy2/ProtocolLib#2600]
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/13227026/latest.log)

Whenever i try do to procotol debug or any commands for this plugin it keeps saying "an internal error has occured" 

https://pastebin.com/PE0gBzhY

ProtocolLib Version:
5.1.0

Server Version
1.20.2

**Comment by Dymeth** [comment]
Use dev builds from here: https://ci.dmulloy2.net/job/ProtocolLib/
