### ISSUE TITLE
Regression bug in commit af33a2ab41199f7c564a5ca9f919e91822532cf4

### ISSUE THREAD

**Issue by nickuc** [dmulloy2/ProtocolLib#2601]
- [x] This issue is not solved in a development build

**Describe the bug**
When registering an event that listens for the [handshake packet (SET_PROTOCOL)](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/PacketType.java#L53), an "Incompatible version!" will appear in motd. This bug was introduced in build [#670](https://ci.dmulloy2.net/job/ProtocolLib/670/) (most likely by commit af33a2ab41199f7c564a5ca9f919e91822532cf4). Build [#669](https://ci.dmulloy2.net/job/ProtocolLib/669/) does not have the same problem.

**To Reproduce**
1. Download and install latest build.
2. Intercept the SET_PROTOCOL packet as the following example:
```java
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, PacketType.Handshake.Client.SET_PROTOCOL) {
      @Override
      public void onPacketReceiving(PacketEvent event) {
            // packet received
      }
});
```
3. See error

**Expected behavior**
Have the same behavior as build [#669](https://ci.dmulloy2.net/job/ProtocolLib/669/).

**Screenshots**
[#669](https://ci.dmulloy2.net/job/ProtocolLib/669/)
<img src="https://i.imgur.com/aKrtBwR.png"></img>

[#670](https://ci.dmulloy2.net/job/ProtocolLib/670/)
<img src="https://i.imgur.com/BBUdE4P.png"></img>

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/raw/dppHLgxQ)

**Additional context**
No additional context.

**Comment by Dymeth** [comment]
Right, #2593 it's exactly the same issue.

TCPShield registration: https://github.com/TCPShield/RealIP/blob/bb7511d37f915ea1b8416ac24dd8564b9d3d0e20/src/main/java/net/tcpshield/tcpshield/bukkit/protocollib/handler/ProtocolLibHandshakeHandler.java#L18

AdvancedNMotd registration: https://github.com/NamerPRO/AdvancedNMotd/blob/b764e435696ca9b5fc0a0ef1a77e417261e9dee2/src/ru/namerpro/AdvancedNMotd/Bukkit/Main.java#L61

**Comment by Dymeth** [comment]
The problem is `PacketType.Handshake.Client.SET_PROTOCOL` packet changes client protocol before calling `NetworkManagerInjector.onPacketReceiving()`.
So in `NetworkManagerInjector.onPacketReceiving()` ProtocolLib tries to get PacketType by the `PacketType.Protocol.STATUS` or `PacketType.Protocol.LOGIN` protocols, but not `PacketType.Protocol.HANDSHAKING` which is actually stored in PacketRegistry.REGISTER.protocolClassToType
