### ISSUE TITLE
Set Player On Ground packet

### ISSUE THREAD

**Issue by Walnuttt** [dmulloy2/ProtocolLib#2606]
Hey, I am trying to find the packet that sets players on the ground, and I can't seem to find any reference to it in the JavaDocs. I am aware that the player position packet does have a boolean field that does this, but I am looking for specifically this packet.

The packet I'm referring to is this one: https://wiki.vg/Protocol#Set_Player_On_Ground

Any help would be greatly appreciated, and sorry if I missed anything, I am still extremely new to plugin development :))

**Comment by Dymeth** [comment]
You can jusy find PacketType with the same packet ID (0x19) in [PacketType class](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/PacketType.java)

When searching, pay attention to the type of protocol (most often PLAY) and the direction of the packet (in your case, the sender Server):
https://github.com/dmulloy2/ProtocolLib/blob/80a097953f98e9aa7ab4c5c0cf3d04ddcbaabd50/src/main/java/com/comphenix/protocol/PacketType.java#L428
