### ISSUE TITLE
Cant see players and cant see anyone on tab list/scoreboard

### ISSUE THREAD

**Issue by xddman** [dmulloy2/ProtocolLib#261]
Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- **[ ] You've checked for duplicate issues**

Debug paste link: http://pastebin.com/QTB76af0

Description and relevant errors:
Hello, for the past few days i have been trying to get a plugin called dice furniture to work, i added the plugin to my plugins folder and other plugins needed for it, tho i had protocolLib already, but i had a version for 1.8, on my 1.9 server, it worked with no problems tho. When i added this plugin, it didnt work with the old version of protocolLib so i downloaded the latest version of protocolLib for 1.9. when i started the server, the other plugin (Dice furniture) worked as it should, but, when someone logs in, he couldnt see the players who logged in before him in game and on the tab list (when you hold tab) players could only see players that log in after them. i tought the problem might be caused by dice furniture and some other plugin i added, i removed them both, and it still didnt work, couldnt see players, then i put back the old version of protocolLib and it worked. so the problem is only with the versions for 1.9. I might aswell add that the server is running in offline mode and using SkinsRestorer and players couldnt see their own skin with the new version of protocolLib, they would see only the default Steve skin on themselfs, but other people could see their skin that they uploaded to minecraft.net. i also tried about 8 developer builds, all had the same problem. Thank you for reading, hopefully you can help me resolve my problem.

**Comment by games647** [comment]
That's AuthMe's fault. Update AuthMe to a dev build or disable the tablist hider.

**Comment by dmulloy2** [comment]
3rd bullet point is to check for duplicate issues. This issue has been reported about a million times. It's AuthMe.

**Comment by xddman** [comment]
i didnt think its authme becouse i tried it with authme on my pc, server i use to test plugins, and protocol lib and authme worked, when i uploaded protocollib to the dedicated server it then didnt want to work, i checked for duplicate issues from the 13 or so i saw, on the first page here on github i never used github so i dont really know how to check if there are more than that, i googled the error and nothing came up, im sorry for asking you a question that is asked alot, i just didnt know how to check if there is a bigger list of issues. sorry again and thank you for helping me.
