### ISSUE TITLE
Is there a version for 1.20.2?

### ISSUE THREAD

**Issue by xNovakx** [dmulloy2/ProtocolLib#2613]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Dymeth** [comment]
Test with last dev build from here: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Zebrahawk** [comment]
This is the updated file:
https://github.com/dmulloy2/ProtocolLib/suites/17615178874/artifacts/1006720717
