### ISSUE TITLE
fix 1.20.2 please, many people need it. 

### ISSUE THREAD

**Issue by BlondeDrip** [dmulloy2/ProtocolLib#2614]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Dymeth** [comment]
Test with last dev build from here: https://ci.dmulloy2.net/job/ProtocolLib/
