### ISSUE TITLE
Help needed: Adding fake player *only* to the tab list

### ISSUE THREAD

**Issue by radstevee** [dmulloy2/ProtocolLib#2625]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
I need to spawn in a fake player *only* to the tab list (so the character is not visible) with a custom display name.

**API method(s) used**
PacketContainer, WrappedGameProfile, PlayerInfoData, sendServerPacket(), EnumWrappers

**Expected behavior**
A fake player in the tablist

**Code**
```kotlin
fun createFakePlayer(name: String, displayName: Component, uuid: UUID): Player? {
    val packet = PacketContainer(PacketType.Play.Server.PLAYER_INFO)

    // Set the parameters
    packet.modifier.writeDefaults()
    val profile = WrappedGameProfile(uuid, name)
    packet.playerInfoDataLists.write( // error is appearing here
        0,
        mutableListOf(
            PlayerInfoData(
                profile,
                0,
                EnumWrappers.NativeGameMode.SPECTATOR,
                WrappedChatComponent.fromText(name)
            )
        )
    )

    packet.playerInfoAction.write(0, EnumWrappers.PlayerInfoAction.ADD_PLAYER)

    // Send the packet to all players
    for (player in Bukkit.getOnlinePlayers()) {
        MCInfinite.protocolManager!!.sendServerPacket(player, packet)
    }

    // Get the player
    val player = Bukkit.getPlayer(uuid)
    player?.displayName(displayName)

    return player
}
```

**Additional context**
I get this error:
`Caused by: java.lang.ClassCastException: Cannot cast java.util.ArrayList to java.util.EnumSet`

**Comment by lukalt** [comment]
Hi, which Minecraft Version are you targeting? The code works for 1.19.2 or earlier. For more recent versions, the internal packet structure changed. 
Here you can find an example on how to implement this: https://github.com/lukalt/PacketWrapper/blob/master/src/main/java/com/comphenix/packetwrapper/wrappers/play/clientbound/WrapperPlayServerPlayerInfo.java (for 1.19.4, but it should work the same for 1.20.2)

**Comment by radstevee** [comment]
I'm using 1.20.1, I'll try it out

**Comment by radstevee** [comment]
> Hi, which Minecraft Version are you targeting? The code works for 1.19.2 or earlier. For more recent versions, the internal packet structure changed. Here you can find an example on how to implement this: https://github.com/lukalt/PacketWrapper/blob/master/src/main/java/com/comphenix/packetwrapper/wrappers/play/clientbound/WrapperPlayServerPlayerInfo.java (for 1.19.4, but it should work the same for 1.20.2)

Sorry for spoonfeeding, but how do I actually use that in my plugin?
