### ISSUE TITLE
Field index is out of bounds errors spam

### ISSUE THREAD

**Issue by lvanko** [dmulloy2/ProtocolLib#2626]
The console gets spammed everi several seconds by an error.

**Describe the bug**
Here's the error: [https://pastebin.com/qnPTaFym](https://pastebin.com/qnPTaFym)

**To Reproduce**
1. Install ProtocolLib dev version 673
2. Start server

**Expected behavior**
No console erorrs

**Version Info**
ProtocolLib dev #673, PaperMC 1.20.2

**Comment by Dymeth** [comment]
It's AntiSeedCracker plugin issue, not ProtocolLib
