### ISSUE TITLE
PacketPlayInUpdateSign broken for 1.8 servers

### ISSUE THREAD

**Issue by Supereg** [dmulloy2/ProtocolLib#263]
Since 1.9 the PacketPlayInUpdateSign changed from textcomponent array back to string array.
It seems ProtocolLib cannot handle the backwards compatibility. When I try to access the componets with #getChatComponentArrays() I get the following error http://hastebin.com/uvojiviloy.vala.

**Comment by dmulloy2** [comment]
The component array modifier should automatically handle both cases.

**Comment by Supereg** [comment]
Maybe something wrong with the ComponentArrayConverter? https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L1364

Since the excpetion also reads "No field with type net.minecraft.server.v1_8_R3.NBTTagCompound".

**Comment by Supereg** [comment]
In old 3.x versions MinecraftReflection.getIChatBaseComponentArrayClass() was called directly and it worked.

**Comment by Supereg** [comment]
Works fine when calling this directly, not over the ComponentArrayConverter:

e.getPacket().getModifier().withType(
                        MinecraftReflection.getIChatBaseComponentArrayClass(),
                        BukkitConverters.getIgnoreNull(new LegacyComponentConverter()))
