### ISSUE TITLE
Using way too much performance.

### ISSUE THREAD

**Issue by TheProOne1** [dmulloy2/ProtocolLib#2632]
![image](https://github.com/dmulloy2/ProtocolLib/assets/143269084/2ae9c0e4-d2a5-456e-89d4-21337d0404b7)

The plugin is just using WAY too much performance, please find a fix.

**Comment by SquidXTV** [comment]
3.5% seems quite alright for such an advanced plugin

**Comment by lukalt** [comment]
Hi, 
as @SquidXTV already indicated, 3.5% is not much.
However, the 3.5% performance impact consists of 2.2% wall time spent by netty. 
This performance impact would have been also be present if you did not use ProtocolLib.
The way ProtocolLib works just causes it to be accounted to ProtocolLib.

So nothing to worry about here and also nothing ProtocolLib can fix
