### ISSUE TITLE
With Purpur 1.20.1 and Velocity, players are unable to join the server

### ISSUE THREAD

**Issue by xiaozhangup** [dmulloy2/ProtocolLib#2637]
- [x] This issue is not solved in a development build

**Describe the bug**
With Purpur 1.20.1 and Velocity, players are unable to access the server.

And if I use ProtocolLib 669, there's no such problem.

**To Reproduce**
1. Use purpur-1.20.1-2062 and velocity
2. Install protocolLib 673
3. Join the server

**Expected behavior**
https://mclo.gs/0QRaUAq

**Screenshots**

**Version Info**
https://pastebin.com/5CFG6aA8

**Additional context**
Build 669 work fine for me.

**Comment by Dymeth** [comment]
Possibly related with https://github.com/dmulloy2/ProtocolLib/issues/2601

Try to use Purpur 1.20.2 with ProtocolLib build 669
