### ISSUE TITLE
ProtocolLib conflict holomobhealth

### ISSUE THREAD

**Issue by SrMonsterYT** [dmulloy2/ProtocolLib#2638]
why is this happening? it seems that there is a conflict with the HoloMobHealth plugin

image: https://prnt.sc/fxqFj2A5piJp

plugin HoloMobHealth: https://www.spigotmc.org/resources/holomobhealth-display-mob-health-damage-indicator-client-side-javascript-formatting.75975/

server version: git-Pufferfish-27 (MC: 1.20.1)

**Comment by Dymeth** [comment]
This is HoloMobHealth plugin issue, not ProtocolLib

**Comment by SrMonsterYT** [comment]
> ProtocolLib: 6.12% HoloMobHealth: 5.67%
> 
> For the most part it's HoloMobHealth plugin performance issue, not ProtocolLib

is there any solution I can suggest to him to solve this?
