### ISSUE TITLE
Version Incompatibility with 1.20.2

### ISSUE THREAD

**Issue by xEchoes** [dmulloy2/ProtocolLib#2653]
- [yes ] This issue is not solved in a development build

**Describe the bug**
So, I installed protocollib's most recent version #673, and am unable to join, at all with no error messages. If I hover over the ping in the server list, it shows incompatible version (1.20.2 server), yet I'm trying to connect with 1.20.2

**To Reproduce**
1. Get version 673 installed on 1.20.2 most recent paper version
2. check ping in server list
3. show error

**Expected behavior**
I'm expecting to actually join the server.

**Screenshots**
 Image: https://github.com/dmulloy2/ProtocolLib/assets/91864696/a7277016-4279-4e52-9edc-809fadb3694a

**Version Info**
ProtocolLib Dump
Timestamp: 11/24/23 18:27:40

ProtocolLib Version: ProtocolLib v5.1.1-SNAPSHOT-673
Bukkit Version: 1.20.2-R0.1-SNAPSHOT
Server Version: git-Paper-299 (MC: 1.20.2)
Java Version: 17.0.1

ProtocolLib: com.comphenix.protocol.ProtocolLib@7df23600[
  statistics=com.comphenix.protocol.metrics.Statistics@6e87c44c
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@2c44ba36
  tickCounter=6438
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@56e10ae1
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@3a4f740b
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6a3a62aa
  commandProtocol=com.comphenix.protocol.CommandProtocol@63a6f0d1
  commandPacket=com.comphenix.protocol.CommandPacket@3d4e4846
  commandFilter=com.comphenix.protocol.CommandFilter@7c608cc8
  packetLogging=com.comphenix.protocol.PacketLogging@45f68edc
  skipDisable=false
  isEnabled=true
  loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1182decb
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-299,minecraftVersion=1.20.2}
  file=plugins\ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@263f6919
  pluginMeta=org.bukkit.plugin.PluginDescriptionFile@263f6919
  dataFolder=plugins\ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.1-SNAPSHOT-673, pluginEnabled=true, url=plugins\ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins\ProtocolLib\config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@503d6bc8
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@3e9668a[
  plugin=ProtocolLib v5.1.1-SNAPSHOT-673
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-299,minecraftVersion=1.20.2}
  reporter=com.comphenix.protocol.ProtocolLib$1@5ec3b04f
  minecraftVersion=(MC: 1.20.2)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7d359d08
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46edda4d
  inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@e78292c
  outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d7ab164
  registeredListeners=[PacketAdapter[plugin=AureliumSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=55]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ChatItem, sending=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=ClientboundPlayerChatPacket, id=55], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=103]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AureliumSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=72]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=49]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=46], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=45], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=107], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=68]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=65]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=84]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=60]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=5]], gamephase=PLAYING, options=[ASYNC]]], io.josemmo.bukkit.plugin.renderer.ItemService@5cf54cec, PacketAdapter[plugin=AureliumSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=103]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=18]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=ChatItem, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=16]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@1c76a81e
  playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@34e1266f
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@7b9f4896
  debug=false
  closed=false
  injected=true
]

Listeners:
com.archyx.aureliumskills.ui.ActionBarCompatHandler$4@7fbcd1be[
  plugin=AureliumSkills vBeta 1.3.23
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=55]], gamephase=PLAYING, options=[]]
]
me.dadus33.chatitem.chatmanager.v1.packets.protocollib.ProtocollibPacketManager$1@2cbc771f[
  plugin=ChatItem v2.4.9
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=ClientboundPlayerChatPacket, id=55], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=103]], gamephase=PLAYING, options=[]]
]
litebans.d0@22627bab[
  g=LiteBans v2.7.5
  b=litebans.cK@2400cb83
  plugin=LiteBans v2.7.5
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
com.archyx.aureliumskills.ui.ActionBarCompatHandler$1@24a12faa[
  plugin=AureliumSkills vBeta 1.3.23
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=72]], gamephase=PLAYING, options=[]]
]
com.olziedev.playerwarps.o.c$1@6b50347b[
  b=com.olziedev.playerwarps.o.c@74e628f8
  plugin=PlayerWarps v6.29.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=49]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.myzelyam.supervanish.visibility.ServerListPacketListener@657755fa[
  plugin=SuperVanish v6.2.12
  plugin=SuperVanish v6.2.12
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$3@6bf35cbe[
  plugin=Citizens v2.0.33-SNAPSHOT (build 3268)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=46], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=45], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=107], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=68]], gamephase=PLAYING, options=[ASYNC]]
]
net.goldtreeservers.worldguardextraflags.protocollib.RemoveEffectPacketListener@3da365f1[
  plugin=WorldGuardExtraFlags v4.1.5-SNAPSHOT
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=65]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$1@41fd79e8[
  plugin=Citizens v2.0.33-SNAPSHOT (build 3268)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=84]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$2@2d81d494[
  plugin=Citizens v2.0.33-SNAPSHOT (build 3268)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=60]], gamephase=PLAYING, options=[ASYNC]]
]
litebans.bK@5b2d6755[
  e=LiteBans v2.7.5
  g=litebans.cH@3a7d1dd3
  a=litebans.cZ@7f99538c
  h=litebans.cK@2400cb83
  i=litebans.c6@37491dce
  plugin=LiteBans v2.7.5
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=5]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
io.josemmo.bukkit.plugin.renderer.ItemService@5cf54cec[
]
com.archyx.aureliumskills.ui.ActionBarCompatHandler$2@75e6015c[
  plugin=AureliumSkills vBeta 1.3.23
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=103]], gamephase=PLAYING, options=[]]
]
eu.decentsoftware.holograms.api.nms.PacketHandlerProtocolLib$1@6ba4787f[
  plugin=DecentHolograms v2.8.4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=18]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
me.dadus33.chatitem.chatmanager.v1.listeners.HandshakeListener@555174ed[
  plugin=ChatItem v2.4.9
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.myzelyam.supervanish.visibility.hiders.modules.TabCompleteModule@785f8b22[
  hider=de.myzelyam.supervanish.visibility.hiders.PreventionHider@299f4f09
  plugin=SuperVanish v6.2.12
  errorLogged=false
  plugin=SuperVanish v6.2.12
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=16]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
WorldGuardExtraFlags by [isokissa3]
AureliumSkills by [Archyx]
Citizens by [fullwall]
YamipaPlugin by []
ChatItem by [dadus33, WOLFI3654, Elikill58]
SuperVanish by [MyzelYam]
LiteBans by [Ruan]
DecentHolograms by [d0by]
PlayerWarps by [Olzie]

**Comment by JamieIsGeek** [comment]
I am having this exact issue, its been driving me crazy all day

**Comment by JamieIsGeek** [comment]
Just tried the intitial 1.20.2 build and that has solved the issue for me. https://ci.dmulloy2.net/job/ProtocolLib/669/

**Comment by RichRich3000** [comment]
dosn't work for me

**Comment by JamieIsGeek** [comment]
You're using build version 309, the latest version that i've found that works is build 669 as said here

> Just tried the intitial 1.20.2 build and that has solved the issue for me. https://ci.dmulloy2.net/job/ProtocolLib/669/
