### ISSUE TITLE
The error reported by protocolllib when generating blocks

### ISSUE THREAD

**Issue by jiuwu02** [dmulloy2/ProtocolLib#2657]
- [ ] This issue is not solved in a development build

**Describe the bug**
Problems that occur when generating worlds

**To Reproduce**
Required Settings: The transfer range of the BetterRTP plugin is set to 10000000

Plugin list:
> pl
[21:59:16 INFO]: Paper Plugins: (1):
[21:59:16 INFO]:  - BKCommonLib
[21:59:16 INFO]: Bukkit Plugins: (5):
[21:59:16 INFO]:  - BetterRTP, My_Worlds, PlaceholderAPI, ViaBackwards, ViaVersion

1. Create a world "/mw create world1"
2. Teleport to the world created "mw teleport world1"
3. Use the BetterRTP command "rtp"
4. A server crash occurred

**Expected behavior**
Let the server run fully

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/107833020/82639ddd-4224-4aff-81aa-38f357521412)

**Version Info**
[dump-2023-11-28_22.03.53.txt](https://github.com/dmulloy2/ProtocolLib/files/13488949/dump-2023-11-28_22.03.53.txt)

**Additional context**
After I removed the plugin protocolllib, the problem was no longer there, and I continued to use the steps above and it was completely normal, with no server crashes

Server error log
[2023-11-28-4.log](https://github.com/dmulloy2/ProtocolLib/files/13488971/2023-11-28-4.log)

**Comment by Brokkonaut** [comment]
That is not protocollib at all
