### ISSUE TITLE
Add permissions and commands to the plugin.yml

### ISSUE THREAD

**Issue by harleypig** [dmulloy2/ProtocolLib#266]
Make sure you've done the following:
- [x] You've checked for duplicate issues

I didn't see any relevant issues, I apologize if I missed one.

Description and relevant errors:
Please add the available permissions and commands to the plugin.yml file.

**Comment by MiniDigger** [comment]
> Commands
**Protocol**
Main administrative command. Supports the following sub-commands:
config: Reload the configuration file.
check: Check for new versions on BukkitDev.
version: Displays the currently running version of ProtocolLib.
timings: Toggle measuring the amount of CPU time spent by each plugin.
listeners: Display what plugins are using ProtocolLib, and the packet types they are intercepting.
All of these commands require the permission protocol.admin.

**Comment by dmulloy2** [comment]
What MiniDigger said, plus it's mostly all there in the plugin.yml
