### ISSUE TITLE
please update to 1.20.2 last update was not working to 1.20.2

### ISSUE THREAD

**Issue by EditingMitten39** [dmulloy2/ProtocolLib#2668]
- [ ] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jeppa** [comment]
The link from github page: https://ci.dmulloy2.net/job/ProtocolLib

**Comment by xotrikspl** [comment]
> Latest dev build works on 1.20.2 ...

what version of java are you using?

**Comment by EditingMitten39** [comment]
8
