### ISSUE TITLE
Error in my server

### ISSUE THREAD

**Issue by ikerSupremoYT** [dmulloy2/ProtocolLib#2671]
?
![Captura](https://github.com/dmulloy2/ProtocolLib/assets/116213804/ab331c0a-eaf6-426c-87b9-3c5482ff434d)
![Captura2](https://github.com/dmulloy2/ProtocolLib/assets/116213804/e31adcbc-497f-47b5-9306-171b95b3ab3e)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
