### ISSUE TITLE
not working on 1.20.2  

### ISSUE THREAD

**Issue by EditingMitten39** [dmulloy2/ProtocolLib#2672]
its not working in 1.20.2 if you tusting me go check you self  
https://www.spigotmc.org/resources/protocollib.1997/
 
Recent Reviews

----------------------------------------------------------------------------------------------------------------------------------------
[RazerJazer](https://www.spigotmc.org/members/razerjazer.1336164/)
RazerJazer  Version: 5.1.0
Dev build doesn't work with my 1.20.2 Minehut proxy server. If there is any fix with this in the future, Please LMK!
[Sunday at 8:39 PM](https://www.spigotmc.org/resources/protocollib.1997/reviews?resource_rating_id=444190)
[scatty5457](https://www.spigotmc.org/members/scatty5457.1763727/)
scatty5457  Version: 5.1.0
latest dev builds work with 1.20.1 but the players cant join if server resource pack is enabled
[Dec 2, 2023](https://www.spigotmc.org/resources/protocollib.1997/reviews?resource_rating_id=444086)
[RevresYm](https://www.spigotmc.org/members/revresym.63569/)
RevresYm  Version: 5.1.0
If people would check the jenkins they would realize that build 669 is 1.20.2.
For some reason there is an eighty character limit on reviews, so this is just filler text that has zero meaning what so ever to the review.
[Nov 15, 2023](https://www.spigotmc.org/resources/protocollib.1997/reviews?resource_rating_id=443191)
[SyntaxError_01](https://www.spigotmc.org/members/syntaxerror_01.1354283/)
SyntaxError_01  Version: 5.1.0
Please update the plugin to support 1.20.2 version. This would be amazing if it will be updated to the latest.
[Nov 14, 2023](https://www.spigotmc.org/resources/protocollib.1997/reviews?resource_rating_id=443169)
[BorakanT](https://www.spigotmc.org/members/borakant.1182607/)
BorakanT  Version: 5.1.0
Latest build doesn't work on 1.20.2 and developer doesn't update it for 1.20.2 too.

**Comment by Jeppa** [comment]
Use latest dev build... 
here it works on 1.20.2 (if not: post the error.)

PS: version 5.1.0 is not a dev build version number...

**Comment by GodKingKirai** [comment]
Can confirm, using 5.0.0 dev build fixes the issue. https://ci.dmulloy2.net/job/ProtocolLib/
