### ISSUE TITLE
Crash on 1.20.2

### ISSUE THREAD

**Issue by Amirmg086** [dmulloy2/ProtocolLib#2673]
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/13624138/latest.log)

**Comment by Jeppa** [comment]
I can't see any problems with ProtocolLib in that log...

**Comment by FabianFrischmann** [comment]
The first error is a issue between Mojang and you, the rest look like plugin errors, but nothing with Protocollib

**Comment by FabianFrischmann** [comment]
> [12:57:40] [Server thread/INFO]: Stopping server

This seems to be initiatet by command

**Comment by Amirmg086** [comment]
I when
I delete ProtocolLib, the server runs and does not stop
