### ISSUE TITLE
Warning in Console

### ISSUE THREAD

**Issue by HollishKid** [dmulloy2/ProtocolLib#268]
Hello,

- You're using the latest build for your server version
I'm afraid I can't do this due to incompatability with LibsDisguises & MythicMobs (the latest versions of all of these combined make the client crash when approaching a disguised MythicMob, this error is known to the MM Staff). Now using 4.0.2.

- This isn't an issue caused by another plugin
Definitly looks like ProtocolLib ...

Debug paste link:
http://pastebin.com/9eEdGZgq
(I pasted the entire console log, for you to see what I mean with:
I suspect this to be the cause of my server restarting periodically.

If you could help me out, that would be awesome !

Thanks !

**Comment by dmulloy2** [comment]
It isn't ProtocolLib. Some plugin or client is sending bad packets. What does your /protocol dump look like?

**Comment by HollishKid** [comment]
Oups, I thought I recognized ProtocolLib in these warnings ...
Here is the output of the /protocol dump:

http://pastebin.com/7vTp7STb

**Comment by dmulloy2** [comment]
Yeah idk what to tell you other than it's a plugin sending malformed packets.
