### ISSUE TITLE
Protocllib not starting up.

### ISSUE THREAD

**Issue by Cisaa** [dmulloy2/ProtocolLib#2687]
- [ ] This issue is not solved in a development build

**Describe the bug**
Plugin doesn't st

**To Reproduce**
Start the server ig

**Expected behavior**
The plugin should start, but it doesn't
**Screenshots**

**Version Info**
Can't start the plugin, so i cannot run commands.

**Additional context**
logs: https://mclo.gs/dx90LOs

**Comment by Jeppa** [comment]
You should update ProtocolLib ...

**Comment by incredimike** [comment]
I have the same error with most recent protocollib and paper
