### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find entity trackers for CraftVillager. (Build #325)

### ISSUE THREAD

**Issue by maxlehot1234** [dmulloy2/ProtocolLib#269]
HI everyone, I don,t know why but for no reason, my console was spam by this error almost 100 times per seconds...

If you have an idea or a fix, I will take it.

I have Spigot 1.10.2 (build version October4th)
ProcolLib dev build #325
Java 8

This is the error I see:
http://pastebin.com/kKaFdPF0

I ask the phoenix616 dev on spigot but he told me to contact you, because it was not related to his plugin.

Thanks again and have a nice day/night to you

**Comment by dmulloy2** [comment]
This is generally caused by dead entities, so this is likely an issue with his plugin.

**Comment by maxlehot1234** [comment]
@dmulloy2 
I just try to remove protocollib from my server and never have the issue again... So it seems to come from protocolib, because I try to remove all plugins that use villager and change nothing...

So anyone else have this issue?

**Comment by dmulloy2** [comment]
Well yeah of course it goes away, his plugin is accessing ProtocolLib and causing this error.

**Comment by maxlehot1234** [comment]
Ok..... I will try to deal with this stupid error that no dev can fix it...

**Comment by maxlehot1234** [comment]
@dmulloy2 You can mark this as resolved. I found the issue. It comes from antiaura plugin from spigot...
I contact the dev of antiaura and wait his answer.

Thanks for your time
