### ISSUE TITLE
Can't change server brand

### ISSUE THREAD

**Issue by molor** [dmulloy2/ProtocolLib#2692]
- [x] This issue is not solved in a development build

**Describe the bug**
Server brand can't be changed by modifying the CUSTOM_PAYLOAD packet.

**To Reproduce**
```java
public Test(TestPlugin thePlugin) {
	super(thePlugin, ListenerPriority.HIGHEST, List.of(PacketType.Configuration.Server.CUSTOM_PAYLOAD), ListenerOptions.ASYNC);
}

private static final MinecraftKey KEY = new MinecraftKey("brand");
private static final String BRAND = "Test";

@Override
public void onPacketSending(PacketEvent theEvent) {
	if (theEvent.isCancelled())
		return;

	StructureModifier<CustomPacketPayloadWrapper> theModifier =
		theEvent.
			getPacket().
			getCustomPacketPayloads();

	if (theModifier.read(0).getId().equals(KEY))
		theModifier.write(0, new CustomPacketPayloadWrapper(BRAND.getBytes(StandardCharsets.UTF_8), KEY));
}
```

Then just try to connect to the server.

**Expected behavior**
`"Test" server` in [F3]

**Screenshots**

![image](https://github.com/dmulloy2/ProtocolLib/assets/19989717/c3f40d5b-0089-4ea3-a35f-825845e67a32)

**Version Info**
Paper `1.20.4-330`
PL `5.2.0-SNAPSHOT-678`

**Comment by molor** [comment]
Hi @derklaro! Because you're the author of https://github.com/dmulloy2/ProtocolLib/pull/2553, can you please look at this? What I'm doing wrong?

**Comment by derklaro** [comment]
You probably need to serialize the brand as utf (prefix it with a varint indicating the length)

**Comment by molor** [comment]
> prefix it with a varint indicating the length

How I can do that?

**Comment by molor** [comment]
How I can do that?! :/

**Comment by Ingrim4** [comment]
I haven't tested this, but the following code should address the issue:

```java
try (ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
     DataOutputStream dataOut = new DataOutputStream(byteOut)) {
    
    StreamSerializer.getDefault().serializeString(dataOut, "custom_brand");
   
    // Obtain the payload for the CustomPacketPayloadWrapper
    byte[] payload = byteOut.toByteArray();
} catch (IOException e) {
    e.printStackTrace();
}
```
