### ISSUE TITLE
1.20.4 Packet 0/91 (ClientBoundSetScorePacket) was larger than I expected, found 16 bytes extra whilst reading packet 91

### ISSUE THREAD

**Issue by Ghasklin** [dmulloy2/ProtocolLib#2704]
- [ ] This issue is not solved in a development build

**Describe the bug**
On death, you get instantly kicked from the server and you can't rejoin because of the death screen. It's a game breaking bug with ProtocolLib installed and since my server is currently 1.20.4 and 3 plugins rely on it, it's an issue. Though, it only persists when someone dies. 

**To Reproduce**
1. Go in-game
2. Die in some way (it doesn't matter)
3. See error

**Expected behavior**
I expected to die and just be able to respawn.

**Screenshots**
![ERROR](https://github.com/dmulloy2/ProtocolLib/assets/64926779/12ad32ac-80bf-4d68-99c7-e5497cec8871)

**Version Info**
https://pastebin.com/6q2g17XQ

**Additional context**
Nope.

**Comment by Ghasklin** [comment]
Some more information: 

When I am on version 1.20.4, it seems to work fine but with ViaVersion and ViaBackwards, it seems to break on any other version. 

When removing ProtocolLib though, everything seems to work fine.

**Comment by Ghasklin** [comment]
bump

**Comment by ItzVaios** [comment]
i have the same issue 2 months now...
when you die, this error appears...
i tried to remove protocollib and the error disappeared. (but i need it because i have oraxen and orebsfucator).

did u find the solution of this error? please msg me back.

**Comment by dmulloy2** [comment]
an error like that generally happens when another plugin creates a malformed packet. does this still happen when you remove SimpleScore?

**Comment by ItzVaios** [comment]
nice.. without simplescore it doesn't appear.. but do you have any recommendation for scoreboard plugin that doesn't make this error appear?

**Comment by dmulloy2** [comment]
can't speak to any specific plugins. just wanted to verify that this wasn't caused by PL itself. sometimes it appears that way since we enable that behavior and the problem goes away by extension

**Comment by ItzVaios** [comment]
ok.. i ll try simplescore again and if it doesn't work ill just try all the scoreboard plugins until it doesn't appear the error..
