### ISSUE TITLE
Get this Error on Server-Startup with Spigot 1.20.4

### ISSUE THREAD

**Issue by bypassRobin** [dmulloy2/ProtocolLib#2707]
**Describe the bug**
Bug on Server Startup

**To Reproduce**
Download newest Spigot 1.20.4 jar and neweste ProtolcolLib + Start the Server

**Expected behavior**

**Screenshots**
Error on Server Startup: https://pastebin.com/GFgAeKvp

**Version Info**
Newest ProtocolLib + newest Spigot 1.20.4 Version.

**Additional context**
Hope you can fix this bug. I have many important plugins for 1.20.4, i cant downgrade my Version.

**Comment by joelawm** [comment]
I am also getting this error, same dump

**Comment by SantaSpeen** [comment]
+1

**Comment by ultronek01** [comment]
Same

**Comment by lukalt** [comment]
Hi, 
ProtocolLib currently does not provide stable 1.20.4 support. The version you use (5.1.0) only supports Minecraft 1.20.1 or older.

Please use the latest development build from the build server for now: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar

This version has not been tested in-depth but should work generally
