### ISSUE TITLE
Please, update to 1.20.2

### ISSUE THREAD

**Issue by AllGrihan** [dmulloy2/ProtocolLib#2713]
- [ ] This issue is not solved in a development build

**Describe the bug**
Update the version of plugin please

**Additional context**
Update the plugin to 1.20.2 please. My server can't update without this. nLogin reqires that. Thanks

**Comment by lukalt** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar for 1.20.2 support
