### ISSUE TITLE
I have found a ProtocolLib for Minecraft 1.20.2

### ISSUE THREAD

**Issue by Berowen** [dmulloy2/ProtocolLib#2714]
Я не знаю с чем это связано, но когда я создал майнкрафт сервер на одном не очень популярном хостинге и установил NLogin, то при 2 перезагрузке сервера NLogin откуда-то скачал ProtocolLib, который совместим с 1.20.2. Я не знаю откуда он NLogin его взял, однако он работает

I don’t know what this is connected with, but when I created a Minecraft server on one not very popular hosting and installed NLogin, then when I rebooted the NLogin server twice, I downloaded ProtocolLib from somewhere, which is compatible with 1.20.2. I don't know where NLogin got it from, but it works

[protocollib_is_here.zip](https://github.com/dmulloy2/ProtocolLib/files/13814020/protocollib_is_here.zip)

**Comment by lukalt** [comment]
The latest development build supports MC 1.20.2 and later: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar
