### ISSUE TITLE
Paper 1.20.4 - ProtocolLib v5.1.0

### ISSUE THREAD

**Issue by MiniMaccc** [dmulloy2/ProtocolLib#2715]
- [ ] This issue is not solved in a development build

**Describe the bug**
Stack Trace:

java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

**To Reproduce**
Install Paper 1.20.4
See Error In Logs

**Expected behavior**
For ProtocolLib to be working

**Screenshots**

**Version Info**
ProtocolLib v5.1.0

**Comment by lukalt** [comment]
Use this version: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/ for 1.20.4 support. 5.1.0 explicitly does NOT support as 1.20.4, as also stated in the log file.

**Comment by Milireso** [comment]
> Use this version: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/ for 1.20.4 support. 5.1.0 explicitly does NOT support as 1.20.4, as also stated in the log file.

Thank you for for the link.
It works! And it even seems to even work (or at least load, haven't done any testing yet) on Folia 1.20.2 and dev 1.20.4. Why isn't this file version linked on spigot, nor under latest releases on Github page? Additionally, adding version number in filename would make identifying them much easier.
Yes, I am nitpicking, but the unnecessary 1-star reviews sadden me.
