### ISSUE TITLE
Chat Not Working When Adding ProtocolLib

### ISSUE THREAD

**Issue by MiniMaccc** [dmulloy2/ProtocolLib#2720]
- [ ] This issue is not solved in a development build

**Describe the bug**
When ever I add ProtocolLib to my server, the chat does not work.

**To Reproduce**
1. Add ProtocolLib
2. Type in chat - nothing appears

**Expected behavior**
For ProtocolLib to work and my chat messages appear

**Screenshots**

**Version Info**
ProtocolLib #679

**Additional context**

**Comment by xMandoU** [comment]
Hey I have the same issue with build #679 on 1.20.4
I saw you closed it as completed how did you fix it?
