### ISSUE TITLE
Minecraft 1.20.2 packet Listener is not called

### ISSUE THREAD

**Issue by Wolf2323** [dmulloy2/ProtocolLib#2722]
- [x] This issue is not solved in a development build

**Describe the bug**
It seems that packet Listener are not called anymore at all on MC 1.20.2, all other versions seems to work fine.
This is an issue probably since the 1.20.4 compatibility, the last working version of ProtocolLib was build 673.

**To Reproduce**
1. Setup an 1.20.2 MC server
2. Install the latest ProtocolLib version (tested with build 679)
3. Have an plugin listen to packets, we listen to `PacketType.Play.Client.STEER_VEHICLE` and `PacketType.Play.Server.ANIMATION`
4. Test it out

**Expected behavior**
The listener should be called

**Screenshots**
/

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
[dump-2024-01-04_18.20.58.txt](https://github.com/dmulloy2/ProtocolLib/files/13833634/dump-2024-01-04_18.20.58.txt)

**Additional context**
I tested this issue with MC 1.18.2 and 1.19.4 and 1.20.4 without any issues

**Comment by Wolf2323** [comment]
Was this now actually fixed? i looked up the history, but i can not identify the commit fixing this

**Comment by dmulloy2** [comment]
@Ingrim4

**Comment by Ingrim4** [comment]
Will look into it tomorrow

**Comment by Ingrim4** [comment]
Can't reproduce on spigot or paper. Please make sure you tested this with the latest dev build since your dump file is from version 679 (latest is 716).

**Comment by Wolf2323** [comment]
Ok, it seems to be actually fixed with 716
