### ISSUE TITLE
Error Upon Start

### ISSUE THREAD

**Issue by Flintstqne** [dmulloy2/ProtocolLib#2725]
- [ x ] This issue is not solved in a development build

**Describe the bug**
Whenever I start my server, ProtocolLib is disabled with the following stack trace every time:
[Pastebin](https://pastebin.com/t0tTxw2D)
**Version Info**
5.1.0

**Comment by lukalt** [comment]
Use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar
