### ISSUE TITLE
ProtocoLib 4.1 Error?

### ISSUE THREAD

**Issue by Laos1996** [dmulloy2/ProtocolLib#273]
I am not sure if its error with ProtocoLib but what I can read from, I think it actually is.
http://pastebin.com/Cs1ziwap

ProtocolLib dump
http://pastebin.com/Hws57aw5

**Comment by dmulloy2** [comment]
My first inclination is that it's something specific to paper again, but it could also be a plugin that creates fake entities.

**Comment by dmulloy2** [comment]
Any more info on this?
