### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KAIKOAUGUSTIN** [dmulloy2/ProtocolLib#2731]
<html>
<body>

java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
--
35 | at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
36 | at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
37 | at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
38 | at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
39 | at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
40 | at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
41 | at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
42 | at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:433)
43 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
44 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
45 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
46 | at java.base/java.lang.Thread.run(Thread.java:1583)
47 | Dump:
48 | Parameters:
49 | [NULL]
50 | Sender:
51 | com.comphenix.protocol.ProtocolLib@42568482[
52 | statistics=<null>
53 | packetTask=<null>
54 | tickCounter=0
55 | configExpectedMod=-1
56 | updater=com.comphenix.protocol.updater.SpigotUpdater@31e69b6
57 | redirectHandler=<null>
58 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@759a8fc3
59 | commandProtocol=<null>
60 | commandPacket=<null>
61 | commandFilter=<null>
62 | packetLogging=<null>
63 | skipDisable=false
64 | isEnabled=false
65 | loader=org.bukkit.plugin.java.JavaPluginLoader@6d3c5a35
66 | server=CraftServer{serverName=CraftBukkit,serverVersion=4014-Spigot-864e4ac-771182f,minecraftVersion=1.20.4}
67 | file=plugins/ProtocolLib.jar
68 | description=org.bukkit.plugin.PluginDescriptionFile@1e2bd70
69 | dataFolder=plugins/ProtocolLib
70 | classLoader=org.bukkit.plugin.java.PluginClassLoader@2b844a66
71 | naggable=true
72 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
73 | configFile=plugins/ProtocolLib/config.yml
74 | logger=org.bukkit.plugin.PluginLogger@151b21e7
75 | ]
76 | Version:
77 | ProtocolLib v5.1.0
78 | Java Version:
79 | 21.0.1
80 | Server:
81 | 4014-Spigot-864e4ac-771182f (MC: 1.20.4)

</body>
</html>java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:[35](https://aternos.org/log/#L35)2)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:433)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@42568482[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@31e69b6
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@759a8fc3
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6d3c5a35
      server=CraftServer{serverName=CraftBukkit,serverVersion=[40](https://aternos.org/log/#L40)14-Spigot-864e4ac-771182f,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1e2bd70
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2b8[44](https://aternos.org/log/#L44)a66
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@1[51](https://aternos.org/log/#L51)b21e7
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.1
  Server:
    4014-Spigot-8[64](https://aternos.org/log/#L64)e4ac-7[71](https://aternos.org/log/#L71)182f (MC: 1.20.4)

**Comment by lukalt** [comment]
Use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar
