### ISSUE TITLE
Visible armor stand in latest version ProtocolLib + Holograms.

### ISSUE THREAD

**Issue by DardBrinza** [dmulloy2/ProtocolLib#274]
I use latest paper spigot 1.8.8, latest ViaVersion, latest Holographic Displays

Debug paste link: http://pastebin.com/04tkmiEi

Image: http://images.vfl.ru/ii/1479400987/b6a67f31/14990321.png

P.S. My paper spigot: http://rgho.st/8ngWZjZMP

**Comment by dmulloy2** [comment]
There's not really anything that can be done about this on ProtocolLib's end. This is an issue with HD.
