### ISSUE TITLE
ERROR]: Couldn't place player in world

### ISSUE THREAD

**Issue by Z3r0xh** [dmulloy2/ProtocolLib#2742]
https://pastebin.com/ZEEs76NM

Server pufferfish last update to 1.20.1

ProtocolLib version 5.2.0-SNAPSHOT-679

I encounter this problem especially with geyser users but also with java users sometimes.

It's a little annoying because when they try to get in they get kicked out the first time but then they get in fine.

**Comment by fra130701** [comment]
bump
https://paste.coralmc.it/qezesesomi.properties
