### ISSUE TITLE
ProtocolLib wont work.

### ISSUE THREAD

**Issue by ansahtoby12** [dmulloy2/ProtocolLib#2748]
Stack Trace:
--
124 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
125 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
126 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
127 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
128 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
129 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
130 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
131 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
132 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
133 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
134 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
135 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
136 | at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
137 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
138 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
139 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
140 | at java.base/java.lang.Thread.run(Thread.java:840)
141 | Dump:
142 | Parameters:
143 | [NULL]
144 | Sender:
145 | com.comphenix.protocol.ProtocolLib@7674c01[
146 | statistics=<null>
147 | packetTask=<null>
148 | tickCounter=0
149 | configExpectedMod=-1
150 | updater=com.comphenix.protocol.updater.SpigotUpdater@53b0f31d
151 | redirectHandler=<null>
152 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@40ef60d6
153 | commandProtocol=<null>
154 | commandPacket=<null>
155 | commandFilter=<null>
156 | packetLogging=<null>
157 | skipDisable=false
158 | isEnabled=false
159 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2471f5c9
160 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
161 | file=plugins/ProtocolLib.jar
162 | description=org.bukkit.plugin.PluginDescriptionFile@4db7923d
163 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4db7923d
164 | dataFolder=plugins/ProtocolLib
165 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
166 | naggable=true
167 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
168 | configFile=plugins/ProtocolLib/config.yml
169 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@5d91de25
170 | ]
171 | Version:
172 | ProtocolLib v5.1.0
173 | Java Version:
174 | 17.0.9
175 | Server:
176 | git-Paper-318 (MC: 1.20.2)

**Comment by CloudeLecaw** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar
