### ISSUE TITLE
Chat Error  v4.2.0-SNAPSHOT-b330

### ISSUE THREAD

**Issue by Cleggy1012** [dmulloy2/ProtocolLib#275]
Running Spigot 1.11-R0.1-SNAPSHOT
ProtocolLib v4.2.0-SNAPSHOT-b330

Debug paste link:
http://pastebin.com/hgEYG9Gz

Errors on load and when players chat.

**Comment by dmulloy2** [comment]
ProtocolLib does not support plugin (re-)loaders.
