### ISSUE TITLE
NettyEventLoopProxy.proxyRunnable()

### ISSUE THREAD

**Issue by w8oooo** [dmulloy2/ProtocolLib#2769]
- [NONE ] This issue is not solved in a development build

**Describe the bug**
when  players try to join a sub-server 

**To Reproduce**
1 - download ProtocolLib
2 - put in on a network (bungee - hub - box - etc)
3 - make player join that server
4 - the server lag

**Expected behavior**
ProtocolLib not using a lot of server resources

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/156964710/52dddfa9-2997-487f-8229-6baccb10b49d)

**Version Info**
[pastebin](https://pastebin.com/rDj8pyKG).

**Additional context**
spark [link](https://spark.lucko.me/2VeRz1PC3E)

**Comment by smscentras** [comment]
old story there, ProtocolLib shit, all knows that.
