### ISSUE TITLE
i cant use the latest version for my server on 1.20.2

### ISSUE THREAD

**Issue by Lootje1806** [dmulloy2/ProtocolLib#2778]
- [ ] This issue is not solved in a development build

**Describe the bug**
when i put the plugin in my server it dont work i get errors because the latest version didnt work on 1.20.2 but i cant download the 5.1.1 because i get a screen that says that the page didnt work but normal if i click on it it downloads by it self

**To Reproduce**
 Error Cannot perform automatic updates. (java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null) occurred in ProtocolLib v5.2.0-SNAPSHOT-679.
[21:50:29] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:540)
at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:511)
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:77)
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1195)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:374)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1137)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:962)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:290)
at java.base/java.lang.Thread.run(Thread.java:840)
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@2460d528[
plugin=ProtocolLib v5.2.0-SNAPSHOT-679
server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Bukkit-d485cde,minecraftVersion=1.20.2}
reporter=com.comphenix.protocol.ProtocolLib$1@20f6abe9
minecraftVersion=(MC: 1.20.2)
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6b10a7b1
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@497bf66e
inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@466933e
outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@11dad9b8
registeredListeners=[PacketAdapter[plugin=AdvancedSeasons, sending=ListeningWhitelist[priority=NORMAL, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=37]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@7f19d91d
playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@69c78816
networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@59080973
debug=false
closed=false
injected=true
Sender:
com.comphenix.protocol.ProtocolLib@1ed81cf3[
statistics=com.comphenix.protocol.metrics.Statistics@2f38ff04
packetTask=com.comphenix.protocol.scheduler.DefaultTask@7a6a45cd
tickCounter=20
configExpectedMod=1
updater=<null>
redirectHandler=com.comphenix.protocol.ProtocolLib$2@63b08862
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3d513f63
commandProtocol=com.comphenix.protocol.CommandProtocol@55793712
commandPacket=com.comphenix.protocol.CommandPacket@7d95545d
commandFilter=com.comphenix.protocol.CommandFilter@1a812015
packetLogging=com.comphenix.protocol.PacketLogging@2e1fae01
skipDisable=false
isEnabled=true
loader=org.bukkit.plugin.java.JavaPluginLoader@3242cd77
server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Bukkit-d485cde,minecraftVersion=1.20.2}
file=plugins/ProtocolLib (1).jar
description=org.bukkit.plugin.PluginDescriptionFile@652250de
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@589d2e1b
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=org.bukkit.plugin.PluginLogger@250c9296
Version:
ProtocolLib v5.2.0-SNAPSHOT-679
Java Version:
17.0.10
Server:
3950-Bukkit-d485cde (MC: 1.20.2)

i help i can download the 5.1.1 version of protocollib. thankyou

**Comment by HMCyber** [comment]
same here
