### ISSUE TITLE
Error in 4.2.0 b332

### ISSUE THREAD

**Issue by GonDykCZ** [dmulloy2/ProtocolLib#278]
Links:

Error: http://pastebin.com/U30j5CSW
My code: http://pastebin.com/mJ7PnFKg

I'm using lasted spigot 1.11 and ProtocolLib v4.2.0 b332. 

Thanks 👍

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/7b61796506907a7be331ccd37ae54ef4c144bd26
