### ISSUE TITLE
Chat Stops working

### ISSUE THREAD

**Issue by xxcosita3czxx** [dmulloy2/ProtocolLib#2783]
- [ yes ] This issue is not solved in a development build

**Describe the bug**
When i install latest development build, it completly disables any output in chat. Console works, but chat dont. Only output of protocol reload i can see
**To Reproduce**
1. Download protocollib
2. Create latest paper minecraft server
3. put protocollib in
4. start server

**Expected behavior**
It should work as normal, adding support for customizer and enabling oraxe 
**Screenshots**
There is no error in the chat or console, but just imagine if you write something in chat, it just doesnt show. Or if u use a command, it also doesnt show
**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
[dump-2024-02-06_10.43.00.txt](https://github.com/dmulloy2/ProtocolLib/files/14177614/dump-2024-02-06_10.43.00.txt)

**Additional context**
I think there may be problem with LPC or essentials, but who knows...

**Comment by lukalt** [comment]
Looks like a problem with UltraCustomizer. Please update the plugin and check again: https://www.spigotmc.org/resources/ultra-customizer.49330/
