### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-47...16])

### ISSUE THREAD

**Issue by InvisibleT4rget** [dmulloy2/ProtocolLib#2799]
- [x] This issue is not solved in a development build

**Describe the bug**
when i have UltraCustomizer.jar in my plugins folder with ProtocolLib causes this problem every player gets kicked from the Server after Achiefements, /kill command /effect command and some more. This is the kick message: and there is no error in the Console . Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([-47...16])

**To Reproduce**
1.Install UltraCustomizer by [TechsCode](https://www.spigotmc.org/members/techscode.29620/)
2. Install Protocol Lib  5.1.0 for 1.20.1 Spigot Server
3. join the server and use the /kill and / effect command to give someone an effect or kill someone, also try to gain an achievement, every player will get kicked

**Expected behavior**
i want to have compability so no player gets kicked with this message an my Server wont Lagg or get errors

**Screenshots**
https://prnt.sc/nDtziAlGSCBP

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
Protocol Lib  5.1.0 for 1.20.1 Spigot Server -->  https://pastebin.com/kvw9bcpJ

**Additional context**
would appreciate an response per email invisibletrg42@gmail.com or here in github

**Comment by GsTio86** [comment]
I also have the same problem, but I mean they will appear when executing commands such as /tp <player> etc.
I don't use the latest version because, the new version will break the operation of BetonQuest, so I lowered it to 673, but the same problem will happen with the latest version

Screenshot: 
![image](https://github.com/dmulloy2/ProtocolLib/assets/74390539/5e7506d7-4ffc-4093-b0fa-b512dfcc5050)

ProtocolLib dump: https://pastebin.com/CV6yqAvH

**Comment by L0RRIX-1** [comment]
Same problem here, running the 679 snapshot

**Comment by Wink011** [comment]
I have the same problem.....
io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: Expected id to be a string, was an array ([181...97])
Please someone guide me to fix the problem.
This error appears when I use Alacrity Pack on 1.20 Optifine and I try to trade with the villagers.
If someone have a solution, please let me know. Thanks!

**Comment by L0RRIX-1** [comment]
update to the latest version NO DEV BUILD

**Comment by L0RRIX-1** [comment]
FOR ALL, the problem is itemsadder and triton, check that 2 plugins

**Comment by Yuyears** [comment]
I've also encountered a similar issue, using mohist-1.20.1-876.jar.  I've also seen similar issues reported under other plugins.  I'm unsure if this is a mohist problem or a plugin problem.
