### ISSUE TITLE
Help Me Please!

### ISSUE THREAD

**Issue by CodaMacroft** [dmulloy2/ProtocolLib#280]
I havn't done any of the below because I like 1.7.10 and I have tried everything ik! I just need help please! I have been installing a couple plugins today and when I restarted my server my console gave me a lot of junk! here is the pastBin link with the server console log: http://pastebin.com/awu6rYr6

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues

Debug paste link: http://pastebin.com/awu6rYr6

Description and relevant errors:

**Comment by MiniDigger** [comment]
I doubt that you will get any help on 1.7, that thing is like 3 years old... 
the error you are getting is a incompatibility between your server version and the plugin.

**Comment by CodaMacroft** [comment]
Ok thanks so much! I just don't know how to read error codes like this one
:( so I needed someone to tell me what the heck it meant so thanks a lot!
that is all the help I needed! Thanks!

**Comment by dmulloy2** [comment]
A 1.7 version of ProtocolLib can be found here: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0

It doesn't receive support and only critical bug fixes are issued.

**Comment by CodaMacroft** [comment]
Wow thanks man!
