### ISSUE TITLE
ProtocolLib 1.20.4 issue

### ISSUE THREAD

**Issue by illudota** [dmulloy2/ProtocolLib#2803]
- [ ] This issue is not solved in a development build

**Describe the bug**
2 errors in the console and it won't load

**To Reproduce**
Install latest ProtocolLib on 1.20.4

**Expected behavior**
Won't load

**Screenshots**
https://mcpaste.io/62cc293de173af1b
then proceeds to this: https://mcpaste.io/9b89c550aef0a2c3

**Version Info**
5.1.0

**Additional context**
How to fix lol

**Comment by lukalt** [comment]
Use this build: https://ci.dmulloy2.net/job/ProtocolLib/679/
