### ISSUE TITLE
Question about animated placeholder in chat

### ISSUE THREAD

**Issue by FlimixST** [dmulloy2/ProtocolLib#2823]
Hello. I would like to know if it is possible to make an animated placeholder in chat using ProtocolLib. That is, I wrote a plugin that animates placeholder (changes its text once every 30 milliseconds) and I was wondering if it is possible to animate it in chat, for example in a player's prefix? If yes, can you suggest how it can be done? Like for example there is a color code §k like this

**Comment by lukalt** [comment]
Hi, 
the actual question is not whether ProtocolLib supports this but rather if it is supported by Minecraft itself - and the answer to this is no; this is currently not supported.
