### ISSUE TITLE
PacketEvent: PacketType.Play.Server.SET_SLOT bug report.

### ISSUE THREAD

**Issue by Shesper** [dmulloy2/ProtocolLib#284]
this bug is not print stack trace. but there seems to be a bug related to PacketEvent.Set_Slot .

Every time I update the inventory(player.updateInventory()), ItemStack is not recognized in PacketEvent.Set_Slot.

I tried to change the item lore using the Set_Slot event, but is not working.

I know it's tough, But can you check this bug?

check version: Protocollib build #346

**Comment by games647** [comment]
Do you set the changed item with getItemModifier().write?

**Comment by Shesper** [comment]
games647//

yes

**Comment by games647** [comment]
Could you post your testing code

**Comment by Shesper** [comment]
I'll show you later. I'm out now.

**Comment by dmulloy2** [comment]
When you update the inventory, the changes you make with packets are overwritten. This is not a bug.
