### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Change2K** [dmulloy2/ProtocolLib#2847]
<html>
<body>

[05:48:31] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
--
34 | If this problem hasn't already been reported, please open a ticket
35 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
36 | Stack Trace:
37 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
38 | at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
39 | at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
40 | at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
41 | at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
42 | at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
43 | at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
44 | at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
45 | at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:435)
46 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
47 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
48 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
49 | at java.base/java.lang.Thread.run(Thread.java:840)
50 | Dump:
51 | Parameters:
52 | [NULL]
53 | Sender:
54 | com.comphenix.protocol.ProtocolLib@68736f83[
55 | statistics=<null>
56 | packetTask=<null>
57 | tickCounter=0
58 | configExpectedMod=-1
59 | updater=com.comphenix.protocol.updater.SpigotUpdater@4438ada2
60 | redirectHandler=<null>
61 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1e7596c
62 | commandProtocol=<null>
63 | commandPacket=<null>
64 | commandFilter=<null>
65 | packetLogging=<null>
66 | skipDisable=false
67 | isEnabled=false
68 | loader=org.bukkit.plugin.java.JavaPluginLoader@2d063f83
69 | server=CraftServer{serverName=CraftBukkit,serverVersion=4065-Spigot-e9ec548-06d9159,minecraftVersion=1.20.4}
70 | file=plugins/ProtocolLib.jar
71 | description=org.bukkit.plugin.PluginDescriptionFile@5f2eb117
72 | dataFolder=plugins/ProtocolLib
73 | classLoader=org.bukkit.plugin.java.PluginClassLoader@f5f7f8e
74 | naggable=true
75 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
76 | configFile=plugins/ProtocolLib/config.yml
77 | logger=org.bukkit.plugin.PluginLogger@78df7e84
78 | ]
79 | Version:
80 | ProtocolLib v5.1.0
81 | Java Version:
82 | 17.0.10
83 | Server:
84 | 4065-Spigot-e9ec548-06d9159 (MC: 1.20.4)

</body>
</html>
[05:48:31] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:[35](https://exaroton.com/log/#L35)2)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:435)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@687[36](https://exaroton.com/log/#L36)f83[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@44[38](https://exaroton.com/log/#L38)ada2
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1e7596c
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@2d063f83
      server=CraftServer{serverName=CraftBukkit,serverVersion=[40](https://exaroton.com/log/#L40)65-Spigot-e9ec5[48](https://exaroton.com/log/#L48)-06d9159,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5f2eb117
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@f5f7f8e
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@78df7e84
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    4065-Spigot-e9ec[54](https://exaroton.com/log/#L54)8-06d91[59](https://exaroton.com/log/#L59) (MC: 1.20.4)

**Comment by ItsFahrenheit** [comment]
I Have This Problem Too, I Think Its Because The Plugin Isn't Updated For 1.20.4
