### ISSUE TITLE
plugin not working in 1.20.2 plz help

### ISSUE THREAD

**Issue by ansahtoby12** [dmulloy2/ProtocolLib#2860]
[07:39:58] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
--
60 | If this problem hasn't already been reported, please open a ticket
61 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
62 | Stack Trace:
63 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
64 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
65 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
66 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
67 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
68 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
69 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
70 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
71 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
72 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
73 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
74 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
75 | at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
76 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
77 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
78 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
79 | at java.base/java.lang.Thread.run(Thread.java:840)
80 | Dump:
81 | Parameters:
82 | [NULL]
83 | Sender:
84 | com.comphenix.protocol.ProtocolLib@340e6569[
85 | statistics=<null>
86 | packetTask=<null>
87 | tickCounter=0
88 | configExpectedMod=-1
89 | updater=com.comphenix.protocol.updater.SpigotUpdater@30dd45b8
90 | redirectHandler=<null>
91 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2731c8bf
92 | commandProtocol=<null>
93 | commandPacket=<null>
94 | commandFilter=<null>
95 | packetLogging=<null>
96 | skipDisable=false
97 | isEnabled=false
98 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@200f31e
99 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
100 | file=plugins/ProtocolLib.jar
101 | description=org.bukkit.plugin.PluginDescriptionFile@1f48969b
102 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1f48969b
103 | dataFolder=plugins/ProtocolLib
104 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
105 | naggable=true
106 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
107 | configFile=plugins/ProtocolLib/config.yml
108 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@33885c32
109 | ]
110 | Version:
111 | ProtocolLib v5.1.0
112 | Java Version:
113 | 17.0.10
114 | Server:
115 | git-Paper-318 (MC: 1.20.2)

[07:39:58] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@340e[65](https://exaroton.com/log/#L65)[69](https://exaroton.com/log/#L69)[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@30dd45b8
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2[73](https://exaroton.com/log/#L73)1c8bf
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@200f31e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1f48969b
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1f48969b
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@338[85](https://exaroton.com/log/#L85)c32
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-318 (MC: 1.20.2)

**Comment by ansahtoby12** [comment]
and if anything please send the jar file for the protocollib because the link i went to says it doesnt exist or i dont have access to it

**Comment by TheCalypso** [comment]
Hello, could you try using the last version of Protocolibs at https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/ ?

**Comment by andreypfau** [comment]
Same problem at `git-Folia-24 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e97b1ee)` using latest release version

Build 679 works fine
