### ISSUE TITLE
using ProtocolLib in hybrid (Mohist) server results in error that disables plugin

### ISSUE THREAD

**Issue by BloxMaster3** [dmulloy2/ProtocolLib#2866]
- [x] This issue is not solved in a development build

**Describe the bug**
when starting a hybrid server (mohist) with Protocollib installed I get an error that disables ProtocolLib
**To Reproduce**
1. download and run [latest mohist 1.12.2](https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.12.2)
2. run a server start batch and then stop server
3. download and add protocollib 
4. run the server and it should give an error

**Expected behavior**
no error in log and plugin works correctly
**Screenshots**
![Screenshot 2024-03-31 081547](https://github.com/dmulloy2/ProtocolLib/assets/136217084/91e3c37f-d379-4822-9534-ba5e3813337c)
![Screenshot 2024-03-31 224422](https://github.com/dmulloy2/ProtocolLib/assets/136217084/3fc2cd83-96dc-46dc-8671-3d99f7ef3093)
![Screenshot 2024-03-31 224514](https://github.com/dmulloy2/ProtocolLib/assets/136217084/7ea331bd-e8eb-49b5-a7c4-f43fd6a0c8dd)
**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
tried and gave an error that said it was disabled, then tried to reload the plugin and that also gave an error
PL version is 5.1.0
**Additional context**
here's the full server log: [latest.log](https://github.com/dmulloy2/ProtocolLib/files/14818866/latest.log)
Yes, the log doesn't have any mods loaded but that's to keep the log small so I still want the server to be hybrid

**Comment by HaHaWTH** [comment]
Can reproduce on Mohist 1.12.2, but the issue should be reported to MohistMC, it's their fault.
Anyway, you can try CatServer1.12.2, I tested without errors.

**Comment by BloxMaster3** [comment]
> Can reproduce on Mohist 1.12.2, but the issue should be reported to MohistMC, it's their fault. Anyway, you can try CatServer1.12.2, I tested without errors.

already did r[eport to mohist](https://github.com/MohistMC/Mohist/issues/3039) but ill try catserver, thanks for the referral

**Comment by HaHaWTH** [comment]
> > Can reproduce on Mohist 1.12.2, but the issue should be reported to MohistMC, it's their fault. Anyway, you can try CatServer1.12.2, I tested without errors.
> 
> just tried it, still errored ![Screenshot 2024-04-01 173509](https://private-user-images.githubusercontent.com/136217084/318573357-5ee243a0-0862-48d4-8f6a-bf310453ed38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTc4MDAsIm5iZiI6MTcxMjAxNzUwMCwicGF0aCI6Ii8xMzYyMTcwODQvMzE4NTczMzU3LTVlZTI0M2EwLTA4NjItNDhkNC04ZjZhLWJmMzEwNDUzZWQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwMDI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWM3NzFiOWRmZWQ4ZDNmNmQyMDZjY2I0ODVhYjc4ZjJjNDk5Njk4YzY3OWExMDljOGE1MjhiZTJmNDQwMGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jjVSC8Lk7g53xJayfP9QoGowhLP7Mlq-2JBA8zIanio) [latest.log](https://github.com/dmulloy2/ProtocolLib/files/14828783/latest.log)

Consider downgrading to 4.8.0 or 5.0.0?

**Comment by BloxMaster3** [comment]
figured it out, had to downgrade to ProtocolLib 4.5.1

**Comment by BloxMaster3** [comment]
figured it out, had to downgrade to ProtocolLib 4.5.1
