### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by IXSENPA1XI** [dmulloy2/ProtocolLib#2872]
- [ ] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**
can you plese update this plugin to be used with the lastes vertion as i cannot use this on the latest vertion

**Describe the solution you'd like**
id love for this to be updated to the latest vertion 1.20.x

**Describe alternatives you've considered**
there are no other alternatives as many of my plugins require this jar file to run

**Comment by justsimplehosting** [comment]
Is your feature request related to a problem? Yes, the plugin doesn't work on the later version of 1.20.X

Describe the solution you'd like
We would appricate an updated version of this, My client wants to use ItemsAdder but is unable too due the plugin not operating correctly.

Describe alternatives you've considered

Maybe an alternate plugin to use if ProtocalLib isn't going to be updated.

The console Error output:
06.04 15:07:53 [Server] Server thread/INFO [ProtocolLib] Loading ProtocolLib v5.1.0
06.04 15:07:53 [Server] Server thread/WARN [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
06.04 15:07:54 [Server] Server thread/ERROR [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
06.04 15:07:54 [Server] INFO If this problem hasn't already been reported, please open a ticket
06.04 15:07:54 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
06.04 15:07:54 [Server] INFO Stack Trace:
06.04 15:07:54 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
06.04 15:07:54 [Server] INFO at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
06.04 15:07:54 [Server] INFO at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
06.04 15:07:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
06.04 15:07:54 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
06.04 15:07:54 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
06.04 15:07:54 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:840)
06.04 15:07:54 [Server] INFO Dump:
06.04 15:07:54 [Server] INFO Parameters:
06.04 15:07:54 [Server] INFO [NULL]
06.04 15:07:54 [Server] INFO Sender:
06.04 15:07:54 [Server] INFO com.comphenix.protocol.ProtocolLib@5ac29af[
06.04 15:07:54 [Server] INFO statistics=<null>
06.04 15:07:54 [Server] INFO packetTask=<null>
06.04 15:07:54 [Server] INFO tickCounter=0
06.04 15:07:54 [Server] INFO configExpectedMod=-1
06.04 15:07:54 [Server] INFO updater=com.comphenix.protocol.updater.SpigotUpdater@33adde9b
06.04 15:07:54 [Server] INFO redirectHandler=<null>
06.04 15:07:54 [Server] INFO scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6fc78ccd
06.04 15:07:54 [Server] INFO commandProtocol=<null>
06.04 15:07:54 [Server] INFO commandPacket=<null>
06.04 15:07:54 [Server] INFO commandFilter=<null>
06.04 15:07:54 [Server] INFO packetLogging=<null>
06.04 15:07:54 [Server] INFO skipDisable=false
06.04 15:07:54 [Server] INFO isEnabled=false
06.04 15:07:54 [Server] INFO loader=org.bukkit.plugin.java.JavaPluginLoader@4eea04e4
06.04 15:07:54 [Server] INFO server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Spigot-2888990-d485cde,minecraftVersion=1.20.2}
06.04 15:07:54 [Server] INFO file=plugins/ProtocolLib.jar
06.04 15:07:54 [Server] INFO description=org.bukkit.plugin.PluginDescriptionFile@77ebe717
06.04 15:07:54 [Server] INFO dataFolder=plugins/ProtocolLib
06.04 15:07:54 [Server] INFO classLoader=org.bukkit.plugin.java.PluginClassLoader@3abb8127
06.04 15:07:54 [Server] INFO naggable=true
06.04 15:07:54 [Server] INFO newConfig=YamlConfiguration[path='', root='YamlConfiguration']
06.04 15:07:54 [Server] INFO configFile=plugins/ProtocolLib/config.yml
06.04 15:07:54 [Server] INFO logger=org.bukkit.plugin.PluginLogger@3a4a4180
06.04 15:07:54 [Server] INFO ]
06.04 15:07:54 [Server] INFO Version:
06.04 15:07:54 [Server] INFO ProtocolLib v5.1.0
06.04 15:07:54 [Server] INFO Java Version:
06.04 15:07:54 [Server] INFO 17.0.10
06.04 15:07:54 [Server] INFO Server:
06.04 15:07:54 [Server] INFO 3950-Spigot-2888990-d485cde (MC: 1.20.2)

**Comment by ScrapMetalGolem** [comment]
Try https://ci.dmulloy2.net/job/ProtocolLib/
