### ISSUE TITLE
net.minecraft.server.v1_12_R1.ReportedException: Sending packet

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#2876]
- [x] This issue is not solved in a development build

**Describe the bug**
 https://pastebin.com/JRhat02i

**To Reproduce**
I don't know

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/mNFbqVgQ ( 5.1.0 because of the downgrade to fix the error )

**Comment by Medved0546** [comment]
I'm too have this issue in 1.16.5

**Comment by pepters** [comment]
me too

**Comment by F3F5** [comment]
@dmulloy2
