### ISSUE TITLE
1.11 ProtocolLib Block Lag

### ISSUE THREAD

**Issue by Mineacer** [dmulloy2/ProtocolLib#288]
Hello there,

Recently, my server has a tremendous amount of block lag, making it extremely difficult for users to mine, as blocks briefly re-appear for ~0.5 seconds before being broken, causing severe distress to mining in a fluent and smooth manner. After testing for around an hour and a half (through plugin elimination), I discovered that ProtocolLib (latest development build) for MC version 1.11 is the result of this.

I hope this issue is able to fixed in the near future,
Mineacer.

**Comment by dmulloy2** [comment]
It's a plugin using ProtocolLib. Run ````/protocol dump```` and look for plugins that deal with blocks, placement, mining, breaking, etc.

**Comment by Mineacer** [comment]
The only plugin that I had that was dependent on ProtocolLib was ChatItem (https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/).

This plugin does not deal with placement, mining or breaking of blocks in any way, it simply allows users to link items in chat.

How does this work?

**Comment by dmulloy2** [comment]
Duplicated by #290
