### ISSUE TITLE
Sending packet : type cannot be null

### ISSUE THREAD

**Issue by CyriacF** [dmulloy2/ProtocolLib#2898]
- [ X ] This issue is not solved in a development build

**Describe the bug**
When i put the new version 5.2.0 instead of 5.1.0 i can't connect on my server, the server shut down with this error
Error : https://mclo.gs/0aHkbzQ

**To Reproduce**
Put the new jar in paper or spigot 1.8 and connect in 1.8

**Expected behavior**
Can play and connect to my server

**Screenshots**

**Version Info**
https://mclo.gs/j2VJLXy

**Additional context**

**Comment by OlekAleksander** [comment]
Same issue
