### ISSUE TITLE
Failed to intercept client packet for null: Invalid player.

### ISSUE THREAD

**Issue by TheChampTF** [dmulloy2/ProtocolLib#29]
Running git-Bukkit-0899683 (MC: 1.8) 

02.01 01:26:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.7.0_03]
02.01 01:26:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.7.0_03]
02.01 01:26:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at net.minecrell.bukkit.randomjoinmessage.RjmListener$1.run(RjmListener.java:53) [RandomJoinMessage.jar:?]
02.01 01:26:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:837) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:92) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:131) [custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:298) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:330) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:62) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:610) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:634) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
02.01 01:26:55 [Server] INFO at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(ProtocolLibHook.java:61) [ChatControl.jar:?]
02.01 01:26:55 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[custom.jar:git-Bukkit-0899683]
02.01 01:26:55 [Server] INFO org.json.simple.parser.ParseException
02.01 01:26:55 [Server] ERROR Unable to parse chat packet
02.01 01:26:55 [Server] INFO UUID of player FallenWrath is a1e38a13-6773-4255-8b87-b83309c1e794
02.01 01:26:55 [Server] INFO Failed to intercept client packet for null: Invalid player.

**Comment by dmulloy2** [comment]
That first error is the result of an interesting tug-of-war between memory leaks and null pointers.  The second error is an issue with ChatControl.

**Comment by TheChampTF** [comment]
Issue with ChatControl reported http://paste.yu8.me/?d5e55ab7fd60d267#0P5Me+zHbqJIcVC2J2yuG+joh7HKfSFX13UT6ZkcKso=

And ideas on the first thing?

**Comment by dmulloy2** [comment]
The log looked like it was upside down.  The first error is with ChatControl, the second one (Failed to intercept chat packet...) should be fixed.
