### ISSUE TITLE
ProtocolLib 1.11 Block Lag + OrebFuscator

### ISSUE THREAD

**Issue by Mineacer** [dmulloy2/ProtocolLib#290]
Hello there,

Recently, my server has a tremendous amount of block lag, making it extremely difficult for users to mine, as blocks briefly re-appear for ~0.5 seconds before being broken, causing severe distress to mining in a fluent and smooth manner. After testing for around an hour and a half (through plugin elimination), I discovered that ProtocolLib (latest development build) for MC version 1.11 is the result of this.

The only plugin I have that messes with blocks is Orebfuscator, is it possible to find a solution that will allow smoother mining?

I hope this issue is able to fixed in the near future,
Mineacer.

**Comment by dmulloy2** [comment]
I think that's just a trade-off with Orebfuscator. Do you value smooth mining or anti-xray?

**Comment by Mineacer** [comment]
[dump-2017-02-05_05.53.47.txt](https://github.com/dmulloy2/ProtocolLib/files/752891/dump-2017-02-05_05.53.47.txt)

Please help me analyse this dump file! The block lag is insane :(

**Comment by dmulloy2** [comment]
com.lishid.**orebfuscator**.hook.ProtocolLibHook$2@2604bbf5[
  plugin=Orebfuscator4 v4.2.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist{priority=NORMAL, packets=[**PacketPlayInBlockDig**[19, legacy: 7]], gamephase=PLAYING, options=[]}
  sendingWhitelist=EMPTY_WHITELIST
]

**Comment by Mineacer** [comment]
Does this mean Orebfuscator is causing the block lag?

**Comment by dmulloy2** [comment]
That's what I would guess. Try removing it and see if your issue is resolved.
