### ISSUE TITLE
Problem with WrappedChatComponent in PacketType.Play.Server.BOSS

### ISSUE THREAD

**Issue by beachvisitor** [dmulloy2/ProtocolLib#2901]
This issue is not solved in a development build

**Describe the bug**
When I add a listener on the packet "PacketType.Play.Server.BOSS" to get the WrappedChatComponent using "e.getPacket().getChatComponents().read(0);" and make changes to this component, I get an error in the console.

[Error](https://pastebin.com/GzNng0HN)

**To Reproduce**
1. Add a listener to the packet "PacketType.Play.Server.BOSS"
2. In the onPacketSending() method
execute the code "e.getPacket().getChatComponents().read(0);" to get the component.
3. Compile the plugin.
4. Send BossBar to the player and receive an error in the console.

**Expected behavior**
I want to get the WrappedChatComponent and change it a little.

**Version Info**
[dump](https://pastebin.com/5WztP5dQ)

**Additional context**
The problem is not resolved with ProtocolLib 5.2.0 and other versions. I tested this with a clean server with only two plugins, mine and ProtocolLib - the error remained.

**Comment by DoubleNico** [comment]
The bossbar was changed, here is how I did it to work for me https://github.com/zippo-store/HypeGradients/blob/3a8048ce55f495d867f0f893dc908a8f29571d39/HypeGradients-Build/src/main/java/me/doublenico/hypegradients/wrappers/boss/WrapperBossBar.java

**Comment by beachvisitor** [comment]
> The bossbar was changed, here is how I did it to work for me https://github.com/zippo-store/HypeGradients/blob/3a8048ce55f495d867f0f893dc908a8f29571d39/HypeGradients-Build/src/main/java/me/doublenico/hypegradients/wrappers/boss/WrapperBossBar.java

Thank you so much, finally it works!
