### ISSUE TITLE
1.20.5

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#2903]
Its not working

**Comment by Jeppa** [comment]
Yes, latest build (#686) throws an error here, too.
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket when  calling com.comphenix.protocol.ProtocolLibrary.getProtocolManager().createPacket(com.comphenix.protocol.PacketType.Play.Server.PLAYER_INFO)

**Comment by jurohn** [comment]
https://pastebin.com/r33gb2UK

1.20.6 Error dump

**Comment by LoneDev6** [comment]
Duplicate of https://github.com/dmulloy2/ProtocolLib/issues/2900
Please close.

**Comment by 0bviouslee** [comment]
> > Duplicate of #2900 Please close.
> 
> Its still not working (2024-05-04)

why are you rushing the release every single day lol, you aren't even waiting til a new build comes out

**Comment by Jeppa** [comment]
> Its still not working (2024-05-04)

Without a new release: sure...
