### ISSUE TITLE
Unable to inject incoming channel error

### ISSUE THREAD

**Issue by Okervill** [dmulloy2/ProtocolLib#291]
Issue began after updating to the latest version which i got the link from in my console as output by the plugin

Debug paste link: http://pastebin.com/XsYwFy30

Description and relevant errors: 

https://i.gyazo.com/fcdf8a2c6d00327391204345bab2a6f7.png - appears in chat every ~5-10 minutes

I tried reverting to the previous version but the errors remain

**Comment by dmulloy2** [comment]
Try updating to the latest dev build and avoid using plugin reloaders

**Comment by dmulloy2** [comment]
Any more info on this?
