### ISSUE TITLE
Won't enable

### ISSUE THREAD

**Issue by LittleDuck363** [dmulloy2/ProtocolLib#2911]
- This issue is not solved in a development build

**Describe the bug**
I don't think it's really a bug but ProtocolLib won't enable on the newest version of Minecraft (1.20.6) and I am using the newest Dev build of ProtocolLib.

<html>
<body>

[15:14:51] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_20_R1
--
55 | [15:14:51] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
56 | If this problem hasn't already been reported, please open a ticket
57 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
58 | Stack Trace:
59 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
60 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
61 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
62 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
63 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
64 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
65 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
66 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
67 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
68 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
69 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
70 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
71 | at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:522)
72 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321)
73 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154)
74 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
75 | at java.base/java.lang.Thread.run(Thread.java:1583)
76 | Dump:
77 | Parameters:
78 | [NULL]
79 | Sender:
80 | com.comphenix.protocol.ProtocolLib@536e94f4[
81 | statistics=<null>
82 | packetTask=<null>
83 | tickCounter=0
84 | configExpectedMod=-1
85 | updater=com.comphenix.protocol.updater.SpigotUpdater@6cb241d3
86 | redirectHandler=<null>
87 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4b5ca185
88 | commandProtocol=<null>
89 | commandPacket=<null>
90 | commandFilter=<null>
91 | packetLogging=<null>
92 | skipDisable=false
93 | isEnabled=false
94 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1f374bd2
95 | server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2183,minecraftVersion=1.20.6}
96 | file=plugins/.paper-remapped/ProtocolLib.jar
97 | description=org.bukkit.plugin.PluginDescriptionFile@72de59bf
98 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@72de59bf
99 | dataFolder=plugins/ProtocolLib
100 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
101 | naggable=true
102 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
103 | configFile=plugins/ProtocolLib/config.yml
104 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@134d2a7d
105 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2a46855
106 | allowsLifecycleRegistration=true
107 | ]
108 | Version:
109 | ProtocolLib v5.2.0-SNAPSHOT-679
110 | Java Version:
111 | 21.0.3
112 | Server:
113 | git-Purpur-2183 (MC: 1.20.6)

</body>
</html>

**To Reproduce**
1. Go to your server panel.
2. Restart the server.

**Expected behavior**
For the plugin to enable.

**Version Info**
build 688 from today 5/6/2024

**Comment by Athar42** [comment]
You should retry with the latest build 689 (working on my Paper test env.).
