### ISSUE TITLE
Spigot & Paper class name mismatches for EnumChatVisibility

### ISSUE THREAD

**Issue by 0utplay** [dmulloy2/ProtocolLib#2926]
- [x] This issue is not solved in a development build

**Describe the bug**
Some of the enum wrapper classes on spigot servers do not match the names on paper servers.
One example I stumbled upon is EnumChatVisibility (spigot) & ChatVisibility (paper)

**To Reproduce**
Start a paper (1.20.6) server with the latest protocollib build.
Use any EnumWrapper (causes the init)

**Expected behavior**
Support for both spigot & paper

**Screenshots**
Spigot:
![image](https://github.com/dmulloy2/ProtocolLib/assets/60936899/dc742445-e69e-4b50-b918-78c62e907343)
Paper:
![image](https://github.com/dmulloy2/ProtocolLib/assets/60936899/2d511ff7-f45f-474a-9497-2614f1b5dc15)

The issue I noticed:
![image](https://github.com/dmulloy2/ProtocolLib/assets/60936899/b6ac751f-02cd-4576-952a-71b8a9edd071)

**Version Info**
https://pastebin.com/z13YdYad

**Additional context**
I'm willing to do some work on this. Just wanted to ask if there already are solutions for this or any approaches you would like to do in order to resolve the issue. I think there might be many more cases like the mentioned one.

**Comment by 0utplay** [comment]
Might be somehow related to #2920

**Comment by Jeppa** [comment]
Also mentioned here #2913 and here https://github.com/dmulloy2/ProtocolLib/issues/2669#issuecomment-2096596447

**Comment by dawon** [comment]
Since Paper uses mojang mappings, I would say this typo was made by mojang...

**Comment by 0utplay** [comment]
The typo being there or not is not the real issue 🤷‍♂️
