### ISSUE TITLE
Dev 689 will not work with Paper 1.20.6 build 74

### ISSUE THREAD

**Issue by Leahcimkrob** [dmulloy2/ProtocolLib#2929]
- This issue is not solved in a development build

**Describe the bug**
ProtocolLib will not load

https://mclo.gs/i7iaarL

**Comment by EuSouVoce** [comment]
You have two versions on the plugins folder, delete the old one and use only the latest

**Comment by Leahcimkrob** [comment]
I can't find a 2nd file from ProtocolLib in plugin-folder

**Comment by Leahcimkrob** [comment]
Paper always creates a paper-remapped folder in the plugin folder.
There I delete ProtocolLib and after a restart the file is still there with the same error

**Comment by Jeppa** [comment]
This might be this: #2912
please rename that file...

**Comment by Leahcimkrob** [comment]
Thanks, with "_" in the name it works, with "-" in the name it doesn't. Unusual
