### ISSUE TITLE
Player Skulls "Vanishing"

### ISSUE THREAD

**Issue by HyperionNexus** [dmulloy2/ProtocolLib#293]
When placing any custom head other than the vanilla ones, the skin will display until you log out or unload the chunks. This is some kind of compatibility issue with BKcommonlib, as it fixes itself if one or the other is removed. 

If you need the log (though it didn't appear to have any errors for the two) I can probably get one.

I also posted it on [BKcommonlib's issue tracker](https://github.com/bergerhealer/BKCommonLib/issues/30).

**Comment by dmulloy2** [comment]
This would appear to be an issue with BKCommonLib. Issues like these often arise when you're dealing with (seemingly) abandoned projects. I believe there's a fork of it out there that the ViaVersion dev made, so it might be worth looking into. There's nothing that can really be done on PL's end though.

**Comment by HyperionNexus** [comment]
I did hear about the fork as well, but I think it was taken down. I'll look into it though, thanks.
