### ISSUE TITLE
Mixing custom enchants on anvil

### ISSUE THREAD

**Issue by Takivad11** [dmulloy2/ProtocolLib#2932]
- [ ] This issue is not solved in a development build

**Describe the bug**
I made a custom enchantment with 4 levels, and let's say i want to mix in a anvil 2 leggings with Enchantment level 2, which would return a enchantment level 3, and it is doing it, and protocollib acually displays the enchant name, but it also displays the enchant BEFORE mixing, so in the example i said, it would be something like

Before mixing
- Leggings: Ender Safety  II

After Mixing
- Leggings: Ender Safety III
                  Ender Safety II

**To Reproduce**
1. Make a custom enchantment with more than 1 level
2. Pick up 2 books/pieces of armot/weapon of that same enchant level
3. Mix them in a anvil

**Expected behavior**
Before mixing
- Leggings: Ender Safety II

After Mixing
- Leggings: Ender Safety III

**Screenshots**
BEFORE:
![image](https://github.com/dmulloy2/ProtocolLib/assets/167753598/97185d1e-823a-4e2c-ac82-0c58cf713517)

AFTER:
![image](https://github.com/dmulloy2/ProtocolLib/assets/167753598/3ec67055-c46d-46cd-9beb-d41af2aad1c9)

**Version Info**
https://pastebin.com/phx30JGv

**Additional context**

**Comment by Jeppa** [comment]
> and protocollib acually displays the enchant name,

I doubt that ProtocolLib displays anything... this is just a library for protocol handling...
There must be any other plugin doing that!
