### ISSUE TITLE
Server Timed Out

### ISSUE THREAD

**Issue by ByNetsky** [dmulloy2/ProtocolLib#294]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:

Description and relevant errors:

18.02 20:07:06 [Server] INFO Error Timeout: Unknown origin java.io.DataInputStream@6ecd521f for packet Packet250CustomPayload$$EnhancerByCGLIB$$a7586046[23, legacy: 250]. Are you using GamePhase.LOGIN? (null) occured in com.comphenix.protocol.injector.packet.ProxyPacketInjector@64d62833.
18.02 20:07:06 [Server] SEVERE INTERNAL ERROR: Timeout: Unknown origin java.io.DataInputStream@6ecd521f for packet Packet250CustomPayload$$EnhancerByCGLIB$$a7586046[23, legacy: 250]. Are you using GamePhase.LOGIN?
18.02 20:07:06 [Server] INFO If this problem hasn't already been reported, please open a ticket
18.02 20:07:06 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
18.02 20:07:06 [Server] INFO Stack Trace:
18.02 20:07:06 [Server] INFO Dump:
18.02 20:07:06 [Server] INFO manager:
18.02 20:07:06 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@72de5159[
18.02 20:07:06 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@67008722
18.02 20:07:06 [Server] INFO packetListeners=[PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet14BlockDig$$EnhancerByCGLIB$$d19f7f0e[7, legacy: 14]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet15Place$$EnhancerByCGLIB$$85dd2e35[8, legacy: 15]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet250CustomPayload$$EnhancerByCGLIB$$a7586046[23, legacy: 250]], gamephase=PLAYING, options=[]}]]
18.02 20:07:06 [Server] INFO packetInjector=com.comphenix.protocol.injector.packet.ProxyPacketInjector@64d62833
18.02 20:07:06 [Server] INFO playerInjection=com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler@27e95ffd
18.02 20:07:06 [Server] INFO interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@4a9cef83
18.02 20:07:06 [Server] INFO inputBufferedPackets=[]
18.02 20:07:06 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@530a7ba
18.02 20:07:06 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3d53a6ff
18.02 20:07:06 [Server] INFO hasClosed=false
18.02 20:07:06 [Server] INFO classLoader=org.bukkit.plugin.java.PluginClassLoader@6bdb3837
18.02 20:07:06 [Server] INFO reporter=com.comphenix.protocol.ProtocolLibrary$1@5ebb9fcf
18.02 20:07:06 [Server] INFO server=CraftServer{serverName=CraftBukkit,serverVersion=git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-653,minecraftVersion=1.5.2}
18.02 20:07:06 [Server] INFO library=ProtocolLib v3.6.5
18.02 20:07:06 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@44565927
18.02 20:07:06 [Server] INFO knowsServerPackets=true
18.02 20:07:06 [Server] INFO knowsClientPackets=true
18.02 20:07:06 [Server] INFO phaseLoginCount=1
18.02 20:07:06 [Server] INFO phasePlayingCount=4
18.02 20:07:06 [Server] INFO packetCreation=true
18.02 20:07:06 [Server] INFO spigotInjector=<null>
18.02 20:07:06 [Server] INFO nettyInjector=<null>
18.02 20:07:06 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@40433d64
18.02 20:07:06 [Server] INFO hasRecycleDistance=true
18.02 20:07:06 [Server] INFO minecraftVersion=(MC: 1.5.2)
18.02 20:07:06 [Server] INFO loginPackets=com.comphenix.protocol.injector.LoginPackets@7e739131
18.02 20:07:06 [Server] INFO debug=false
18.02 20:07:06 [Server] INFO ]
18.02 20:07:06 [Server] INFO Sender:
18.02 20:07:06 [Server] INFO com.comphenix.protocol.injector.packet.ProxyPacketInjector@64d62833[
18.02 20:07:06 [Server] INFO manager=com.comphenix.protocol.injector.PacketFilterManager@72de5159
18.02 20:07:06 [Server] INFO reporter=com.comphenix.protocol.ProtocolLibrary$1@5ebb9fcf
18.02 20:07:06 [Server] INFO playerInjection=com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler@27e95ffd
18.02 20:07:06 [Server] INFO filter=com.comphenix.protocol.injector.packet.ProxyPacketInjector$1@6b9dfa62
18.02 20:07:06 [Server] INFO readPacketIntercepted=true
18.02 20:07:06 [Server] INFO ]
18.02 20:07:06 [Server] INFO Version:
18.02 20:07:06 [Server] INFO ProtocolLib v3.6.5
18.02 20:07:06 [Server] INFO Java Version:
18.02 20:07:06 [Server] INFO 1.7.0_111
18.02 20:07:06 [Server] INFO Server:
18.02 20:07:06 [Server] INFO git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-653 (MC: 1.5.2)

Crash Dump:

ProtocolLib Dump
Timestamp: 02/18/17 20:11:47

ProtocolLib Version: ProtocolLib v3.6.5
Bukkit Version: 1.5.2-R1.1-SNAPSHOT
Server Version: git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-653 (MC: 1.5.2)
Java Version: 1.7.0_111

ProtocolLib: com.comphenix.protocol.ProtocolLibrary@744b1247[
  statistics=com.comphenix.protocol.metrics.Statistics@7ec39e
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@25cba53
  packetTask=5
  tickCounter=1179
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4248ad79
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.BukkitUpdater@15cca05b
  redirectHandler=com.comphenix.protocol.ProtocolLibrary$2@2d33c18b
  commandProtocol=com.comphenix.protocol.CommandProtocol@20e7a3dc
  commandPacket=com.comphenix.protocol.CommandPacket@47b6d164
  commandFilter=com.comphenix.protocol.CommandFilter@336d2104
  skipDisable=false
  isEnabled=true
  initialized=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@4192a7fc
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-653,minecraftVersion=1.5.2}
  file=plugins/ProtocolLib-3.4.0.jar
  description=org.bukkit.plugin.PluginDescriptionFile@352b306
  dataFolder=plugins/ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@47a626a3
  naggable=true
  ebean=<null>
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=org.bukkit.plugin.PluginLogger@64ddcad1
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@7c6906a6[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4248ad79
  packetListeners=[PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet250CustomPayload$$EnhancerByCGLIB$$16859811[23, legacy: 250]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet15Place$$EnhancerByCGLIB$$f50a6600[8, legacy: 15]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=ExtFunctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[Packet14BlockDig$$EnhancerByCGLIB$$40ccb6d9[7, legacy: 14]], gamephase=PLAYING, options=[]}]]
  packetInjector=com.comphenix.protocol.injector.packet.ProxyPacketInjector@7da032e
  playerInjection=com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler@7a06c508
  interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@5271cece
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2dc060ab
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@310a9204
  hasClosed=false
  classLoader=org.bukkit.plugin.java.PluginClassLoader@47a626a3
  reporter=com.comphenix.protocol.ProtocolLibrary$1@31fac23d
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-653,minecraftVersion=1.5.2}
  library=ProtocolLib v3.6.5
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@12a3abf5
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=1
  phasePlayingCount=3
  packetCreation=false
  spigotInjector=<null>
  nettyInjector=<null>
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@59af3953
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.5.2)
  loginPackets=com.comphenix.protocol.injector.LoginPackets@7edca624
  debug=false
]

Listeners:
de.thomasweigold.extensionfunctions.ExtensionFunctions$2@2808dcef[
  plugin=ExtFunctions v1.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist{priority=NORMAL, packets=[Packet250CustomPayload$$EnhancerByCGLIB$$16859811[23, legacy: 250]], gamephase=PLAYING, options=[]}
  sendingWhitelist=EMPTY_WHITELIST
]
de.thomasweigold.extensionfunctions.ExtensionFunctions$1@3f5aa204[
  plugin=ExtFunctions v1.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist{priority=NORMAL, packets=[Packet15Place$$EnhancerByCGLIB$$f50a6600[8, legacy: 15]], gamephase=PLAYING, options=[]}
  sendingWhitelist=EMPTY_WHITELIST
]
de.thomasweigold.extensionfunctions.ExtensionFunctions$3@679bc61b[
  plugin=ExtFunctions v1.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist{priority=NORMAL, packets=[Packet14BlockDig$$EnhancerByCGLIB$$40ccb6d9[7, legacy: 14]], gamephase=PLAYING, options=[]}
  sendingWhitelist=EMPTY_WHITELIST
]

**Comment by dmulloy2** [comment]
1.5.2 hasn't been supported for some time now. Your best bet is to try older versions that may support it.
