### ISSUE TITLE
Broken pipe && ClosedChannelException && OutOfMemoryError

### ISSUE THREAD

**Issue by SaloEater** [dmulloy2/ProtocolLib#295]
Debug paste link:
http://pastebin.com/tpJRzRnf

Description and relevant errors:
Pastebin's error mix with java.nio.channels.ClosedChannelException and flood in console since random moment until full server stop. And there is some OutOfMemoryError on 72003 string. I attached full log from server's start until it's end.
[2017-02-19-2.txt](https://github.com/dmulloy2/ProtocolLib/files/785854/2017-02-19-2.txt)

**Comment by dmulloy2** [comment]
Looks to be an issue with ViaVersion and/or EchoPet.

**Comment by Fluxty** [comment]
On TacoSpigot 1.8.8, we also received a ClosedChannelException, usually directly after a reboot, crash detection won't pick it up so I have to be around to reboot the server. We believe it's linked to protocollib as well.

**Comment by krconv** [comment]
I also believe that this is an issue with ProtocolLib. I wrote a plugin (CrackedLogin) to provide authentication, which holds most of the packets sent to the player until he/she either types in a password or leaves. 
Anytime a player leaves before authenticating this error will start occuring anytime the server is queried (either from a client or from a uptime tracking service) until a reload or restart.

**Comment by dmulloy2** [comment]
> holds most of the packets sent to the player until he/she either types in a password or leaves

There's your problem right there. If you hold on to the packets then release them down the pipeline after the channel closes, you get that error.

**Comment by krconv** [comment]
I have narrowed the problem down. I'm get this error anytime someone queries the server (e.g. from the multiplayer menu) while a PacketListener is registered with the ProtocolManager.
This is what a client sees if a PacketListener is running on the server:
 ![error](https://cloud.githubusercontent.com/assets/1918630/23906523/9941d2bc-08a4-11e7-951b-09d36e817553.png)

**Comment by dmulloy2** [comment]
You have to set the listener for server list packets to be async
