### ISSUE TITLE
Null when getMouse()

### ISSUE THREAD

**Issue by Neszku** [dmulloy2/ProtocolLib#296]
Can anyone tell me why im getting null here?

My code: http://pastebin.com/r5qbQfPu

Wrapper: http://pastebin.com/2CNsG5Nf

version: 3.7.0

Debug paste link:
http://pastebin.com/4tpk09cP

**Comment by dmulloy2** [comment]
1.7.10 is no longer supported, but it would appear that you're using a method that doesn't exist on 1.7.10.
