### ISSUE TITLE
Plugin is not fully updated to 1.20.6!

### ISSUE THREAD

**Issue by Goinging** [dmulloy2/ProtocolLib#2960]
- [x] This issue is not solved in a development build

**Describe the bug**
[13:29:19 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.

Some dev's are waiting until it fully updates before updating their plugins which have this plugin as a dependency like the dev of Pl-Hide. The last commit on the Github looks like it failed so I am not sure what is going on with this plugin.

**Version Info**
ProtocolLib Version: ProtocolLib v5.2.1-SNAPSHOT-689
Bukkit Version: 1.20.6-R0.1-SNAPSHOT
Server Version: 1.20.6-129-0513374 (MC: 1.20.6)
Java Version: 21.0.1

**Comment by ScrapMetalGolem** [comment]
The whole world is waiting for the same thing you are. At this point, planned release for 1.21 is only 2 weeks away; it's starting to look like we might all be forced to move ahead to that, despite whatever plans we had made. All we can do is wait and offer whatever support we can offer, aside from the devs that are migrating to other libraries.

**Comment by Raidware** [comment]
> * [x]  This issue is not solved in a development build
> 
> **Describe the bug** [13:29:19 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
> 
> Some dev's are waiting until it fully updates before updating their plugins which have this plugin as a dependency like the dev of Pl-Hide. The last commit on the Github looks like it failed so I am not sure what is going on with this plugin.
> 
> **Version Info** ProtocolLib Version: ProtocolLib v5.2.1-SNAPSHOT-689 Bukkit Version: 1.20.6-R0.1-SNAPSHOT Server Version: 1.20.6-129-0513374 (MC: 1.20.6) Java Version: 21.0.1

Yes.
