### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2962]
- [x] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Go to  https://github.com/dmulloy2/ProtocolLib/actions/runs/9343896005/job/25714155175
2. Click on Run gradle build lifecycle
3. Scroll down

**Comment by dmulloy2** [comment]
yeah that's expected for now. the unit tests need to be updated.

see https://ci.dmulloy2.net/job/ProtocolLib for the dev builds
