### ISSUE TITLE
Unable to load build 694, "detected a newer version"

### ISSUE THREAD

**Issue by Toseflo** [dmulloy2/ProtocolLib#2963]
I tried to load dev build 694 on a 1.20.6 server without any other plugins. I get the error "Detected a newer version of ProtocolLib (694.0.0) in plugin folder than the current (5.2.1-SNAPSHOT)". The server is running Paper-133.

The log file is attached:
[latest.log](https://github.com/user-attachments/files/15537969/latest.log)

**Comment by dmulloy2** [comment]
i'm just going to change that check

**Comment by dmulloy2** [comment]
looks like it doesn't have the intended effect when it's remapped by paper. interesting
