### ISSUE TITLE
Filter command feature request

### ISSUE THREAD

**Issue by DuckCraftPvP** [dmulloy2/ProtocolLib#297]
Please add a ability to disable the filter command because it interferes with alot of other plugins, Or just change the command all-together.

**Comment by MiniDigger** [comment]
how does it interfere? 
which plugins are affected?

**Comment by DuckCraftPvP** [comment]
any item filter plugin like:
https://www.spigotmc.org/resources/1-7-1-11-itemfilter.30546/
or https://www.spigotmc.org/resources/randompackage.32323/

**Comment by MiniDigger** [comment]
oh, you mean because they use the commands? 
use your commands.yml to add aliases for them, or use the fully qualified command name (/plugin:command)

**Comment by DuckCraftPvP** [comment]
but i dont want alias for the plugins, i want to be able to use the /filter command on those plugins.

**Comment by DuckCraftPvP** [comment]
cant you just add ability to disable the filter command?

**Comment by MiniDigger** [comment]
no. bukkit doesn't allow that.   
what you could do is open the protocol lib jar in a archive viewer, locate the plugin yml, locate the filter: command section and remove that. this will disable the filter command.

**Comment by DuckCraftPvP** [comment]
i did that i was just wondering cause i dont like seeing the error everytime i start mc xD

**Comment by DuckCraftPvP** [comment]
also i saw you have a spigot-dark style.css how do i apply it to spigot site?

**Comment by MiniDigger** [comment]
https://www.spigotmc.org/threads/i-made-a-dark-forum-theme-and-it-sucks.143475/

**Comment by dmulloy2** [comment]
Like @MiniDigger said, Bukkit doesn't allow you to just 'disable' a command via a configuration option. There are some hacky ways to get around this you could look into though.
