### ISSUE TITLE
FieldAccessException: Field index 0 is out of bounds for length 0

### ISSUE THREAD

**Issue by NoltoxGit** [dmulloy2/ProtocolLib#2989]
- [x] This issue is not solved in a development build

**Describe the bug**
I have a error with the [Custom-Nameplates](https://github.com/Xiao-MoMi/Custom-Nameplates) since the build #700 and after.

**Logs:**
https://mclo.gs/va8Nrbr#L1706

**Version Info**
[`/protocol dump`](https://mclo.gs/jmnUFXG) informations.

**Comment by Muffin2Go** [comment]
This Problem occurs because the packet that is sent by CustomNameplates has likely changed. Thats not an ProtocolLib error! The packet calling by CustomNameplates has to be changed ;)
