### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class [...]$2 from class [...]

### ISSUE THREAD

**Issue by G4merSylver** [dmulloy2/ProtocolLib#299]
So I am experimenting with the packet listener, through it isnt going rather well - I fail at the mere attempt of adding the listener.

Make sure you've done the following:
    - [ Tried it under 4.2.0 and 4.1.0 (Minecraft 1.10) ] You're using the latest build for your server version
    - [ Check ] This isn't an issue caused by another plugin
    - [ I saw it once, but the user merely wrote 'changed versions' - didnt work in my case. ] You've checked for duplicate issues

Debug paste link: 
    - http://pastebin.com/zrudgMQz (Error Log) 
    - http://pastebin.com/9bGCExQP (Code Sample)

Description and relevant errors: Method is called from the onEnable() call, the error log is generated under v4.1.0 but under either version a java.lang.IllegalAccessError was thrown. The only thing I got to add would be that I didnt bother adding "depend: [ProtocolLib]" to the plugin.yml since it seems to work fine without it (Under IntelliJ IDEA)

**Comment by MiniDigger** [comment]
try restarting your server, looks like one of the nice issues which come with using hacks like plugman.

**Comment by G4merSylver** [comment]
Thanks for the hint, turns out it really was Plugman! Didn't think it'd turn out to be that.

**Comment by MiniDigger** [comment]
thats why most developers don't support stupid plugins like that.
