### ISSUE TITLE
Heavy load

### ISSUE THREAD

**Issue by VesterTop** [dmulloy2/ProtocolLib#2993]
This is not the first time I notice that the plugin can load the entire server very heavily, perhaps there is a solution to this problem?
![image](https://github.com/dmulloy2/ProtocolLib/assets/83246978/532b0068-7c06-4e79-a55f-58833bc54fd1)

**Comment by TrentonH1ll** [comment]
5% Is Not A "Heavy Load"!

**Comment by Brokkonaut** [comment]
You should expand that node to see what is going on there up to the last node that has unusual high load. Otherwise it is not really helpful.

**Comment by VesterTop** [comment]
> You should expand that node to see what is going on there up to the last node that has unusual high load. Otherwise it is not really helpful.

This is not the maximum, I have sometimes seen values up to 18%

**Comment by VesterTop** [comment]
![image](https://github.com/dmulloy2/ProtocolLib/assets/83246978/d2ff8a09-fbb6-47dd-bfdd-63e208ea09db)

**Comment by dmulloy2** [comment]
none of that looks particularly out of the ordinary. if you had a specific place where we were using a lot of resources we might be able to act on it. otherwise i'm not concerned with that amount of load
