### ISSUE TITLE
NoClassDefFound Stack Trace on Startup

### ISSUE THREAD

**Issue by ExcelsiorVFX** [dmulloy2/ProtocolLib#30]
When starting Protocol Lib v3.4.0 in the latest 1.8 Spigot (December 23), I get this stack trace:

http://pastebin.com/XzXsY2Ln

Is it my fault, or is it a bug?

**Comment by dmulloy2** [comment]
Use the latest version from my Jenkins: http://ci.shadowvolt.com/job/ProtocolLib/
