### ISSUE TITLE
Player get kicked when kill a Mob

### ISSUE THREAD

**Issue by ByNetsky** [dmulloy2/ProtocolLib#300]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

Debug paste link:
http://pastebin.com/RipZbAU2

Description and relevant errors:

10.03 22:36:23 [Server] SEVERE A critical server error occured handling a packet, kicking 2848979
10.03 22:36:23 [Server] INFO java.lang.NullPointerException
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.ItemShard.getCharge(ItemShard.java:144)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.CommonProxy.processShard(CommonProxy.java:72)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.CommonProxy.livingDeath(CommonProxy.java:21)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.HandlerForgeEvents.livingDeath(HandlerForgeEvents.java:10)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler_112_HandlerForgeEvents_livingDeath_LivingDeathEvent.invoke(.dynamic)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:111)
10.03 22:36:23 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:333)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.EntityLiving.func_70645_a(EntityLiving.java:1355)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(EntitySkeleton.java:222)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.EntityLiving.func_70097_a(EntityLiving.java:1171)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:73)
10.03 22:36:23 [Server] INFO at mods.tinker.tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:192)
10.03 22:36:23 [Server] INFO at mods.tinker.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:615)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1368)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetServerHandler.func_72507_a(NetServerHandler.java:1594)
10.03 22:36:23 [Server] INFO at net.minecraft.network.packet.Packet7UseEntity.func_73279_a(SourceFile:36)
10.03 22:36:23 [Server] INFO at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:223)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
10.03 22:36:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
10.03 22:36:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
10.03 22:36:23 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
10.03 22:36:23 [Server] WARNING Failed to handle packet for Chemist_Fred/212.114.51.116: java.lang.NullPointerException
10.03 22:36:23 [Server] INFO java.lang.NullPointerException
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.ItemShard.getCharge(ItemShard.java:144)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.CommonProxy.processShard(CommonProxy.java:72)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.CommonProxy.livingDeath(CommonProxy.java:21)
10.03 22:36:23 [Server] INFO at com.shadwdrgn.soulshards.HandlerForgeEvents.livingDeath(HandlerForgeEvents.java:10)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler_112_HandlerForgeEvents_livingDeath_LivingDeathEvent.invoke(.dynamic)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
10.03 22:36:23 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:111)
10.03 22:36:23 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:333)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.EntityLiving.func_70645_a(EntityLiving.java:1355)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(EntitySkeleton.java:222)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.EntityLiving.func_70097_a(EntityLiving.java:1171)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:73)
10.03 22:36:23 [Server] INFO at mods.tinker.tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:192)
10.03 22:36:23 [Server] INFO at mods.tinker.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:615)
10.03 22:36:23 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1368)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetServerHandler.func_72507_a(NetServerHandler.java:1594)
10.03 22:36:23 [Server] INFO at net.minecraft.network.packet.Packet7UseEntity.func_73279_a(SourceFile:36)
10.03 22:36:23 [Server] INFO at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:223)
10.03 22:36:23 [Server] INFO at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
10.03 22:36:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
10.03 22:36:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
10.03 22:36:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
10.03 22:36:23 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by dmulloy2** [comment]
ProtocolLib isn't even mentioned in the stack trace, this is an issue with soul shards.
