### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#3006]
coming soon! should be an easy one since most of the breaking changes were in 1.20.6

**Comment by andrewkm** [comment]
Thanks for all your continued work and recent help with a few broken plugins! <3

**Comment by andrewkm** [comment]
Bro is fast AF!
https://github.com/dmulloy2/ProtocolLib/commit/e726f6eb0d7971200175bcb2d216d1a19e806605
<3

**Comment by andrewkm** [comment]
By the way @dmulloy2 compilation issues on your Jenkins:
https://ci.dmulloy2.net/job/ProtocolLib/717/console

For some reason mine is building just fine though.

**Comment by dmulloy2** [comment]
interesting. guess i did something too weird & broke the JVM lol

**Comment by andrewkm** [comment]
Been using it on 1.20.6 by the way, looks good. :)
