### ISSUE TITLE
when i load this plugin i got this error

### ISSUE THREAD

**Issue by tim12465** [dmulloy2/ProtocolLib#301]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link :http://pastebin.com/ay8YXG0B

Description and relevant errors:
i have install a plugin FastLogin is this plugin cause this error?

**Comment by dmulloy2** [comment]
This is not caused by ProtocolLib, it's probably due to FastLogin.
