### ISSUE TITLE
should not be displayed in the client 

### ISSUE THREAD

**Issue by YuanYuanOwO** [dmulloy2/ProtocolLib#3010]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
/protocol dump:https://paste.helpch.at/jazahobulu.rb

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't fixed in a recent development build
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
N/A

Description and relevant errors:
i think the following should not be displayed in the client  
![7fccf0b6f31c51af87dfcfc2c3ffde01](https://github.com/dmulloy2/ProtocolLib/assets/81153017/2c4004ff-e543-4eaa-8498-d781f7daba7a)  
not sure how to reproduce it at 100%

**Comment by dmulloy2** [comment]
I don't think that error message is coming from us. Seems like maybe a plugin is either shading ProtocolLib into its own jar or is not properly including ProtocolLib as a dependency

**Comment by YuanYuanOwO** [comment]
> I don't think that error message is coming from us. Seems like maybe a plugin is either shading ProtocolLib into its own jar or is not properly including ProtocolLib as a dependency

i mean  
this message is should be displayed in the player game client  
and i think
https://github.com/Ghost-chu/QuickShop-Hikari/blob/6b54f4bfcea87bd378725cceb0c0b5d652780cc3/quickshop-bukkit/src/main/resources/plugin.yml#L12

**Comment by dmulloy2** [comment]
I see. It seems like QuickShop-Hikari is shading the adventure library into their own jar. I'd recommend opening an issue with them
