### ISSUE TITLE
Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

### ISSUE THREAD

**Issue by Javimoa95** [dmulloy2/ProtocolLib#3014]
- [ ] This issue is not solved in a development build

**Describe the bug**
Plugin won't load because of some issues I don't even understand. 
**To Reproduce**
1. Download lastest version
2. Upload it
3. Voliá, it doesn't work
**Expected behavior**
I expected it to work and run tbh, it said it was ready for 1.20.6
**Screenshots**

**Version Info**
ProtocolLib v5.2.0-SNAPSHOT-679
459

Logs: https://mclo.gs/HJ3C3tr

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
