### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Pkung123** [dmulloy2/ProtocolLib#302]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:

Description and relevant errors:
 If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
  	at com.comphenix.protocol.ProtocolConfig.isAutoDownload(ProtocolConfig.java:263)
  	at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:610)
  	at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:66)
  	at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:576)
  	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
  	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
  	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@74cc85[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1f6349
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutSpawnEntity[0, legacy: 14], PacketPlayOutEntityMetadata[57, legacy: 28], PacketPlayOutSpawnEntityLiving[3, legacy: 15]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1cf8947
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3db926
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@46730a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@12ac3d3
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@9e7625
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1096dc3
        reporter=com.comphenix.protocol.ProtocolLib$1@15e9c62
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-5818108-a486600,minecraftVersion=1.8.4}
        library=ProtocolLib v4.2.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1050e96
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@15fc9fc
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1c5ee41
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.4)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@19d25b4
        debug=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@a711e8[
      statistics=com.comphenix.protocol.metrics.Statistics@167c6f
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@439901
      packetTask=2
      tickCounter=20
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1f6349
      configExpectedMod=1
      updater=com.comphenix.protocol.updater.SpigotUpdater@1f216f1
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@c03dba
      commandProtocol=com.comphenix.protocol.CommandProtocol@114a9ce
      commandPacket=com.comphenix.protocol.CommandPacket@198203f
      commandFilter=com.comphenix.protocol.CommandFilter@6d1640
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@1cfd461
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-5818108-a486600,minecraftVersion=1.8.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1805a57
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1096dc3
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@10ff1eb
    ]
  Version:
    ProtocolLib v4.2.0
  Java Version:
    1.7.0_45
  Server:
    git-Spigot-5818108-a486600 (MC: 1.8.4)

**Comment by dmulloy2** [comment]
There's something wrong with your config.yml. Paste it using pastebin.

**Comment by dmulloy2** [comment]
Any more info on this?
