### ISSUE TITLE
Failed to handle packet [server 1.8 version protocollib 5.2.0]

### ISSUE THREAD

**Issue by Z3r0xh** [dmulloy2/ProtocolLib#3021]
- [ ] This issue is not solved in a development build

**Describe the bug**

Users are kicked when moving between servers with different protocollib versions.

1.8 in lobby and modalities 1.20.6

**To Reproduce**
Using bungeecord as a proxy and a lobby in 1.8,

You enter the lobby and change to a mode in 1.20.6, both with their respective versions of protocollib.

When you enter the lobby everything is fine and you enter the mode.

When returning to the lobby (/lobby using phoenixLobby) 1 out of 4 times you are kicked out with this error:
https://mclo.gs/1bkZ1nL

**Expected behavior**
Don't kick players when moving between servers

**Screenshots**
none

**Version Info**
https://pastebin.com/kphMVJah

https://mclo.gs/1bkZ1nL

**Comment by uRyanxD** [comment]
This has been fixed in development versions

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by Z3r0xh** [comment]
- [ ] 

> This has been fixed in development versions
> 
> https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

I cannot use this version since I have the problem on a server that is at 1.8, I have to use version 5.2.0 according to the spigot website
