### ISSUE TITLE
SET_PROTOCOL is not working 

### ISSUE THREAD

**Issue by vortexthedev** [dmulloy2/ProtocolLib#3023]
- [ ] This issue is not solved in a development build

**Describe the bug**
1.20.6 PacketHandshakingInSetProtocol is using ClientIntent instead of EnumProtocol.

**To Reproduce**
Listen to PacketType.SET_PROTOCOL and try to read protocol:
`
ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(plugin,
                ListenerPriority.LOWEST, PacketType.Handshake.Client.SET_PROTOCOL) {
            @Override
            public void onPacketReceiving(PacketEvent event) {
                PacketType.Protocol state = event.getPacket().getProtocols().read(0);
            }
});
`

![image](https://github.com/dmulloy2/ProtocolLib/assets/72511773/9be3920d-387c-49a9-ae89-7aafc612a363)

**Comment by Ingrim4** [comment]
This is technically not a bug. The `SetProtocol` packet no longer includes a `Protocol` enum field. Instead, it now contains a new enum called `ClientIntent`. Therefore, this should be considered a feature request for a new enum wrapper for `ClientIntent`.
