### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by ACat321** [dmulloy2/ProtocolLib#3025]
<html>
<body>

java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
--
34 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
35 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
36 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
37 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
38 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
39 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
40 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
41 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
42 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
43 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
44 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
45 | at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
46 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
47 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
48 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
49 | at java.base/java.lang.Thread.run(Thread.java:1583)
50 | Dump:
51 | Parameters:
52 | [NULL]
53 | Sender:
54 | com.comphenix.protocol.ProtocolLib@72537ee6[
55 | statistics=<null>
56 | packetTask=<null>
57 | tickCounter=0
58 | configExpectedMod=-1
59 | updater=com.comphenix.protocol.updater.SpigotUpdater@714bce24
60 | redirectHandler=<null>
61 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@18062aa5
62 | commandProtocol=<null>
63 | commandPacket=<null>
64 | commandFilter=<null>
65 | packetLogging=<null>
66 | skipDisable=false
67 | isEnabled=false
68 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@698233c7
69 | server=CraftServer{serverName=Paper,serverVersion=1.21-4-090775e,minecraftVersion=1.21}
70 | file=plugins/.paper-remapped/ProtocolLib.jar
71 | description=org.bukkit.plugin.PluginDescriptionFile@68f08754
72 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@68f08754
73 | dataFolder=plugins/ProtocolLib
74 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
75 | naggable=true
76 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
77 | configFile=plugins/ProtocolLib/config.yml
78 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@7237dbe9
79 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@20e248
80 | allowsLifecycleRegistration=true
81 | ]
82 | Version:
83 | ProtocolLib v5.2.0-SNAPSHOT-679
84 | Java Version:
85 | 21.0.3
86 | Server:
87 | 1.21-4-090775e (MC: 1.21)

</body>
</html>java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:3[34](https://aternos.org/log/#L34))
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:5[35](https://aternos.org/log/#L35))
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@725[37](https://aternos.org/log/#L37)ee6[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@714bce24
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@18062aa5
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@698233c7
      server=CraftServer{serverName=Paper,serverVersion=1.21-4-090775e,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@68f08754
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@68f08754
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@7237dbe9
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@20e2[48](https://aternos.org/log/#L48)
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-4-090775e (MC: 1.21)

**Comment by PikaMug** [comment]
Use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib/
