### ISSUE TITLE
Libdisguise compatibility with 4.2.0 on 1.8.8 version server

### ISSUE THREAD

**Issue by xion87** [dmulloy2/ProtocolLib#303]
I dont have any errors, i use lib'disguise 8.6.7 on 1.8.8 server plus viaversion, when i am using protocollib 4.2.0 with selfdisguise enabled, and somesone disguise, all chunk around him will unload, and player need to relog for fix it. Is fixable from protocollib side?

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
no errors

**Comment by MiniDigger** [comment]
did you open an issue on libs github? I don't think that protocol lib can do anything here

**Comment by dmulloy2** [comment]
This isn't fixable from PL's side.

**Comment by xion87** [comment]
I think is fixable because with old version of protocolib it work fine but my anticheat will break.
