### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Wilson159** [dmulloy2/ProtocolLib#3030]
**Describe the bug**
I have ProtocolLib installed on my server as it is a dependency for another plugin, but when I start my server I get the `[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.` error...

Here is the error data: [https://pastebin.com/FytuxtCW](https://pastebin.com/FytuxtCW)

**To Reproduce**
1. Install ProtocolLib on 1.20.6 PaperMC server
2. Run server

**Expected behavior**
That ProtocolLib runs correctly.

**Version Info**
It also gives me an error ([https://pastebin.com/2uWd7KcK](https://pastebin.com/2uWd7KcK)) when I run the command but `ProtocolLib v5.2.0-SNAPSHOT-679` from what I can tell...

**Comment by Jeppa** [comment]
Please update...

**Comment by Wilson159** [comment]
> Please update...

Ah thank you, sorry!
