### ISSUE TITLE
Server crash after join

### ISSUE THREAD

**Issue by JH3Y50N** [dmulloy2/ProtocolLib#3034]
- [X] This issue is not solved in a development build

**Describe the bug**
PaperSpigot 1.8.8 Java version 17, the server just crash after someone join, It happens sometimes, not always.

**To Reproduce**
I don't know, someone join on the server and happens the crash

**Version Info**
v5.2.0

**Additional context**

> [17:11:15] [Server thread/INFO]: Voxxel[/XXXXXX:37453] logged in with entity id 52403423 at ([world]0.5, 51.0, 0.5)
> [17:11:15] [Server thread/WARN]: Entity threw exception at world:0.5,51.0,0.5
> [17:11:15] [Server thread/WARN]: net.minecraft.server.v1_8_R3.ReportedException: Sending packet
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:925)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:356)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:249)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:270)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1650)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1617)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1450)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:846)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [17:11:15] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:842)
> [17:11:15] [Server thread/WARN]: Caused by: java.lang.NullPointerException: type cannot be null
> [17:11:15] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
> [17:11:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
> [17:11:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911)
> [17:11:15] [Server thread/WARN]: 	... 12 more
> [17:11:15] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.server.v1_8_R3.ReportedException: Sending packet
> 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:925) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:312) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:277) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:203) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
> 	at java.lang.Thread.run(Thread.java:842) [?:?]
> Caused by: java.lang.NullPointerException: type cannot be null
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
> 	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
> 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	... 9 more
> [17:11:15] [Server thread/ERROR]: 	Cause of unexpected exception was
> java.lang.NullPointerException: type cannot be null
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
> 	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
> 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
> 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:312) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:277) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:203) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
> 	at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by Ingrim4** [comment]
Might be fixed by the latest dev build but could also throw a new error since 1.8 isn't as much tested as newer version of the game.
https://ci.dmulloy2.net/job/ProtocolLib/
