### ISSUE TITLE
More documentation on ProtocolLib...?

### ISSUE THREAD

**Issue by Namnodorel** [dmulloy2/ProtocolLib#304]
So, maybe I'm just not experienced enough or something, but I seriously need more guidance when using ProtocolLib to develop a plugin. 

In this specific situation, I need to recognize any nametag changes of an NPC, and wanted to try out ProtocolLib for that purpose. I managed to add a new listener using the PacketAdapter, with the Packet type I needed, `ENTITY_METADATA`. Aaand that is where I got stuck. The `PacketContainer` class requires you to know exactly what you want to extract from the packet and where it is, but I plain do not. wiki.vg/Protocol didn't really help me either. `metadata` is apparently always `null` and if it weren't, I'd have no idea what parameter to pass as `key`, because wiki.vg just gives indexes for the different parameters, nothing else. 

I could really use some help on this or, for that matter, a better general documentation on the usage of ProtocolLib.

**Comment by dmulloy2** [comment]
Can you provide some code? I can guess at what it looks like, but I'm not exactly sure what you're trying right now.

As for the documentation, there's the [JavaDoc](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/), wiki.vg, [PacketWrapper](https://github.com/dmulloy2/PacketWrapper), and about a million help threads out there.

**Comment by Namnodorel** [comment]
The JavaDoc only provides information about what methods etc. ProtocolLib has, but in ProtocolLib I still need to know that `packet.getStrings().read(0);` in an `PacketType.Play.Client.CHAT` event returns the chat message. And as I said already, wiki.vg is not too much of a big help there (or I suck at interpreting what it says). I have tried some "black magic" (Reflections) to try and figure out where the needed information is stored. But the results weren't really useful: http://pastebin.com/SNcuqMhx

Help threads aren't a good resource especially because they are spread everywhere and it can be really hard to find some actual advice, just because it is not really easy to get an overview. That is, why some more in-depth and comprehensive guides would be useful.

This is the code I have (it's barely anything, I know):
```
[...].addPacketListener(new PacketAdapter(ArdaCraftHooks.getPlugin(), PacketType.Play.Server.ENTITY_METADATA) {
            @Override
            public void onPacketSending(PacketEvent event) {
                PacketContainer packet = event.getPacket();

                //packet.[???].setNameTag("AmazingNameTag"); or whatever it needs to change such values.
            }
        });
```

**Comment by MiniDigger** [comment]
if you have trouble figuring out the values, [PacketWrapper](https://github.com/dmulloy2/PacketWrapper) is definitely what you want to use.
protocollib can only help you modify and send packets, you need to figure out the actual values you want to change, thats out of the scope of protocol lib. 
wiki.vg is your goto solution for that. the packet is documented here: http://wiki.vg/Protocol#Entity_Metadata
as you can see the packet has a metadata filed that you want to modify. that format is explained here. metadata is an array, you want the look at the 2nd index and change that (as that is the custom name)

**Comment by Namnodorel** [comment]
Okay, thanks ^^ I took a second look at PacketWrapper, it was useful :)

But what I really wanted to do still didn't work out. Have a look at this video: https://youtu.be/JrrDKnw_5TI
It explains better what went wrong than I can here just through text...

**Comment by dmulloy2** [comment]
The relevant part from that pastebin is this:
````
   handle=net.minecraft.server.v1_10_R1.PacketPlayOutEntityMetadata@1f13564c   [
      a=433,
      b=java.util.ArrayList@54c6166d      {
         net.minecraft.server.v1_10_R1.DataWatcher$Item@5204a54e         [
            a=net.minecraft.server.v1_10_R1.DataWatcherObject@507ca9fa            [
               a=12,
               b=net.minecraft.server.v1_10_R1.DataWatcherRegistry$1@31973858               [
 
           ]
        ],
        b=0,
        c=false
     ]
  }
   ],
````

Basically you want to look at modifying that array list via ````packet.getWatchableCollectionModifier().read(0)```` and its associated methods

**Comment by Namnodorel** [comment]
But the thing now is, how was I supposed to know that without asking here? "WatchableCollectionModifier" isn't really something where I immediately know what it is for. Or even, that I'd need it in order to read the packet data.

**Comment by MiniDigger** [comment]
WatchableCollectionModifier wrapps the ArrayList. then you can read the DataWatchers out of that. the data watchers are what holds the data.

**Comment by Namnodorel** [comment]
Might be, but I'm trying to make the point that a more comprehensive documentation would be more convenient for both people like me and people who can actually answer those questions. I get the information I need without having to wait for an answer or hourlong testing what works and how, and you don't have to explain that much stuff to stupid people anymore.

**Comment by dmulloy2** [comment]
I agree that it would be more convenient, but frankly the cost-benefit here isn't even close. The amount of time it would take to make a ProtocolLib-centric packet documentation would far exceed having to answer a few questions every once in a while. Right now the current situation is, to me at least, the best one.

**Comment by MiniDigger** [comment]
if you want real time help, I suggest using the spigot irc. it's way better for support, issues are more for discussion on actual bugs ^^
