### ISSUE TITLE
Folia 1.20.6 reporting error

### ISSUE THREAD

**Issue by x1aoren** [dmulloy2/ProtocolLib#3059]
- [ ] This issue is not solved in a development build

**Describe the bug**
Error reported

**To Reproduce**
Error occurs when starting the server

**Expected behavior**
normal operation

**Screenshots**
![23e0d3f057cbbf471ebaf8cc8e6dec25](https://github.com/dmulloy2/ProtocolLib/assets/136235181/89b8345d-2071-4cff-997c-9490be39a5be)

**Version Info**
Minecraft 1.20.6
Latest Folia Construction
ProtocolLib v5.2.0

**Additional context**

**Comment by x1aoren** [comment]
This server is running Folia version 1.20.6-5-master@d797082 (2024-06-19T22:19:29Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Unable to use/protocol dump

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/
