### ISSUE TITLE
İnternal server error

### ISSUE THREAD

**Issue by enderylmz** [dmulloy2/ProtocolLib#3068]
[dump-2024-06-30_15.16.53.txt](https://github.com/user-attachments/files/16044595/dump-2024-06-30_15.16.53.txt)

![image](https://github.com/dmulloy2/ProtocolLib/assets/174252177/43c37b4d-4839-4727-9a3b-936499f9b16f)
 
 
  When my players interact with the menus, they are kicked out for this reason. When they upgrade to protocolibin 5.2.0, they are kicked out due to the internal server error.
  
  
  error version in 5.2.0
  
![image](https://github.com/dmulloy2/ProtocolLib/assets/174252177/49a2c415-6e18-44cf-bbda-5d4b9c10003c)

Due to this error, I cannot upgrade to 5.2.0, please help.

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/
