### ISSUE TITLE
Error when player logs in

### ISSUE THREAD

**Issue by grdgyyr** [dmulloy2/ProtocolLib#307]
- [X] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

Debug paste link:
https://pastebin.com/Ee3Fp6Na

Description and relevant errors:
Token Enchant which is visible in debug is updated to its latest build. I sent this debug to them for additional help. Thanks in advanced.

**Comment by MiniDigger** [comment]
its caused by tokenenchant, report it there.

**Comment by dmulloy2** [comment]
More specifically TokenEnchant is trying to access a field that does not exist.
