### ISSUE TITLE
Custom Enchants error

### ISSUE THREAD

**Issue by Operating2844** [dmulloy2/ProtocolLib#3074]
I am using the latest version of ProtocolLib (ProtocolLib v5.3.0-SNAPSHOT-723) with the latest available version of Paper (1.21-38).

When I give a player a piece of armor with a custom enchantment, they are kicked with the error: ‘lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null.’

There is no error in the console or logs. I am giving the armor with the packet type “PacketType.Play.Server.ENTITY_EQUIPMENT”

**Comment by dmulloy2** [comment]
this is a bug with PacketEvents
