### ISSUE TITLE
Field index 0 is out of bounds for length 0

### ISSUE THREAD

**Issue by ImYenil** [dmulloy2/ProtocolLib#3079]
- [ ] This issue is not solved in a development build

**Describe the bug**
https://pastebin.com/EGn6y15v

**To Reproduce**
Just join server

**Expected behavior**
X
**Screenshots**
X
**Version Info**
https://pastebin.com/bJyRbSAL

**Additional context**
X

**Comment by Ingrim4** [comment]
This error is caused by [SimpleScore](https://github.com/r4g3baby/SimpleScore) please report this the author(s) of SimpleScore
