### ISSUE TITLE
Error In console

### ISSUE THREAD

**Issue by ICEconchy** [dmulloy2/ProtocolLib#309]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
https://pastebin.com/qW4itwUH
Description and relevant errors:
I am on a 1.10 server trying the download for 1.10 and It doesn't seem to work.

**Comment by dmulloy2** [comment]
That's...kinda bizarre actually. Try a different jar, either redownload the one you're using or grab a dev build

**Comment by ICEconchy** [comment]
I've done that, isn't working.

**Comment by dmulloy2** [comment]
I'm honestly at a loss, there's no reason it shouldn't be able to find an internal class unless your jar is corrupted.

Try downloading the 4.2.1 release: https://github.com/dmulloy2/ProtocolLib/releases/tag/4.2.1

**Comment by ICEconchy** [comment]
Do you mean the server jar? Or the plugin jar?

Becuase at the moment the server which this error comes up, has this: https://www.spigotmc.org/threads/server-commands-and-chat-not-working.231577/
