### ISSUE TITLE
Protocollib Error after updating 1.20.6 [updated protocollb to that version]

### ISSUE THREAD

**Issue by Dante6979** [dmulloy2/ProtocolLib#3098]
Itemsadder wasint working because we needed to update the version to 21 or higher which we did to 1.20.6

So now protocollib does not work and we tried numerous of versions but its just no working, id like to get this working for my client as im doing a commision currently. Thanls 

ERROR: 

<html>
<body>

14:33:40] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
--
42 | [14:33:43] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
43 | If this problem hasn't already been reported, please open a ticket
44 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
45 | Stack Trace:
46 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
47 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
48 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
49 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
50 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
51 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
52 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
53 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
54 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
55 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
56 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
57 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
58 | at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:532)
59 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:286)
60 | at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1136)
61 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
62 | at java.base/java.lang.Thread.run(Thread.java:1583)
63 | Dump:
64 | Parameters:
65 | [NULL]
66 | Sender:
67 | com.comphenix.protocol.ProtocolLib@37899aee[
68 | statistics=<null>
69 | packetTask=<null>
70 | tickCounter=0
71 | configExpectedMod=-1
72 | updater=com.comphenix.protocol.updater.SpigotUpdater@2c19a8ee
73 | redirectHandler=<null>
74 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@573c1969
75 | commandProtocol=<null>
76 | commandPacket=<null>
77 | commandFilter=<null>
78 | packetLogging=<null>
79 | skipDisable=false
80 | isEnabled=false
81 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@54ca7cf0
82 | server=CraftServer{serverName=Paper,serverVersion=1.20.6-DEV-20f5165,minecraftVersion=1.20.6}
83 | file=plugins/ProtocolLib.jar
84 | description=org.bukkit.plugin.PluginDescriptionFile@49514f8b
85 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@49514f8b
86 | dataFolder=plugins/ProtocolLib
87 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/ProtocolLib.jar}
88 | naggable=true
89 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
90 | configFile=plugins/ProtocolLib/config.yml
91 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@36d6a0d0
92 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@590261
93 | allowsLifecycleRegistration=true
94 | ]
95 | Version:
96 | ProtocolLib v5.2.0-SNAPSHOT-679
97 | Java Version:
98 | 21.0.2
99 | Server:
100 | 1.20.6-DEV-20f5165 (MC: 1.20.6)

</body>
</html>14:33:40] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
[14:33:43] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:532)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:286)
  	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1136)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@37899aee[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2c19a8ee
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@573c1969
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@54ca7cf0
      server=CraftServer{serverName=Paper,serverVersion=1.20.6-DEV-20f5165,minecraftVersion=1.20.6}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@[49](https://mclo.gs/8DVaAj9#L49)514f8b
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@49514f8b
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@36d6a0d0
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@590261
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    1.20.6-DEV-20f[51](https://mclo.gs/8DVaAj9#L51)65 (MC: 1.20.6)

**Comment by Jeppa** [comment]
Please read all the other issues here with the same error... the solution is there...

**Comment by Dante6979** [comment]
> Please read all the other issues here with the same error... the solution is there...

um I did you just put the same message? mind actually explaining the issue?

**Comment by Jeppa** [comment]
You ProtocolLib is outdated -> yours is SNAPSHOT-679 ...
