### ISSUE TITLE
Root tag must be a named compound tag

### ISSUE THREAD

**Issue by Kainzo** [dmulloy2/ProtocolLib#31]
This issue is happening on the sieralization process for any plugin that is using Protocol Lib.  Backpacks / PlayerSQl are the two I know of, reposting here to make sure its getting covered.

https://gist.github.com/mung3r/a7828449cc7f96d536a5

**Comment by dmulloy2** [comment]
I was never able to figure out the cause of this, is this still an issue?

**Comment by caxerx** [comment]
I want to make ItemRenamer work, but I also get this error.

**Comment by dmulloy2** [comment]
I was able to fix this by manually writing the NBT tag's id, but there isn't a great way to inject that into the write method.

**Comment by caxerx** [comment]
Are there any methods to prevent spigot remove the Custom NBT tag?

**Comment by dmulloy2** [comment]
You might be able to manually modify the bytes or mimic the behavior in the PacketDataSerializer, but I haven't found a clean way to do it yet.

**Comment by caxerx** [comment]
Thanks for your methods. But I don't know how to put the method in my plugin....

**Comment by caxerx** [comment]
I've tried to getInputStream on Set Creative Slot packet, but there are no slot and item id data in the byte array.
This is the problem in 1.8?

**Comment by PresidentxMC** [comment]
I'm getting the same error for dyed leather armor and player heads in my plugin. I thought I finally found a good serialization method and then this happens :(
