### ISSUE TITLE
error while enable plugin

### ISSUE THREAD

**Issue by DeathlyCoder** [dmulloy2/ProtocolLib#310]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
https://pastebin.com/AwyqQE18
Description and relevant errors:
error while /plugman load Protocollib

**Comment by MiniDigger** [comment]
plugman is not supported. restart your server properly to enable the plugin.

**Comment by DeathlyCoder** [comment]
ty
