### ISSUE TITLE
TinyProtocol

### ISSUE THREAD

**Issue by coco5843** [dmulloy2/ProtocolLib#311]
Latest TinyProtocol Version used,
Latest bungeecord version used,
Lastest minecraft version used 1.11.2 on spigot.

i'm using this code to detect if someone is clicking on an packet armorstand:
https://hastebin.com/usawusezut.swift
this  code is perfectly work but if you have bungeecord, it's not.
The server kicks you.

Description and relevant errors:
Message when kicked:
https://proxy.spigotmc.org/f755a14e717152faebb58075749272a718681a3e?url=http%3A%2F%2Fi.imgur.com%2FroIsHpA.png
Bungeecord error:
https://pastebin.com/raw/XwVZHSbL

**Comment by dmulloy2** [comment]
As a troubleshooting step, can you try this with the full ProtocolLib plugin? This could be a problem with the TinyProtocol implementation.

**Comment by coco5843** [comment]
I'm back:

this is my new code with protocollib:

https://hastebin.com/utiyaseteg.swift

same error and same problem:
https://pastebin.com/2DzH6RMs
