### ISSUE TITLE
Asynchronous Entity Fetching Causes Main Thread Check Failure in PaperMC Server

### ISSUE THREAD

**Issue by var1nthon** [dmulloy2/ProtocolLib#3129]
- [x] This issue is not solved in a development build

**Describe the bug**
An asynchronous operation in the Minecraft server using PaperMC causes a failed main thread check. The error occurs when trying to fetch entities in the server world, which should be performed on the main server thread but is being called asynchronously.

**To Reproduce**
1. Run the PaperMC server version 1.21-54-f250ec0.
2. Install and enable the ProtocolLib and IllegalStack plugins.
3. Trigger an operation that involves fetching entities, possibly through an action monitored by IllegalStack (e.g., certain player commands or interactions).

**Expected behavior**
Entity fetching operations should be performed on the main server thread to ensure thread safety and prevent crashes. The server should handle these operations without triggering asynchronous errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/41f8f61c-6a49-4e2e-b3af-ce3754e172d8)

**Version Info**
Server Version: PaperMC 1.21-54-f250ec0
Plugins Involved: ProtocolLib dump
[dump-2567-07-19_04.55.36.txt](https://github.com/user-attachments/files/16289574/dump-2567-07-19_04.55.36.txt)
IllegalStack (2.9.12-SNAPSHOT-01)

**Additional context**
Error Log: https://paste.helpch.at/jovololivi.php
Spark Log: https://spark.lucko.me/fDDjIW4j7X

Notes:
The error involves asynchronous access to server entities, which should be executed on the main thread to ensure thread safety.
Reviewing and modifying the relevant plugin code to ensure that entity-fetching operations are done on the main server thread might be necessary to resolve the issue.

**Comment by dmulloy2** [comment]
> Reviewing and modifying the relevant plugin code to ensure that entity-fetching operations are done on the main server thread might be necessary to resolve the issue.

Agreed, but this should be done by IllegalStack
