### ISSUE TITLE
Outdated Packetwrappers

### ISSUE THREAD

**Issue by Photon-GitHub** [dmulloy2/ProtocolLib#313]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

-> All yes.

Debug paste link:
- Nonexistant

Description and relevant errors:
I would like to see a message on the old packetwrapper repository pointing at your one as of the outdated classes (some still work and will cause confusion...) if it is possible.
~Photon

**Comment by dmulloy2** [comment]
I don't have access to the old repository
