### ISSUE TITLE
ProtocolLib not starting/Failing to Load

### ISSUE THREAD

**Issue by AdzelFirestar** [dmulloy2/ProtocolLib#3134]
- [ ] This issue is not solved in a development build

**Describe the bug**
I was attempting to do some server configuration and set up, but when I got to my crates plugin that has ProtocolLib as a hard dependency it refused to work. So I did /plugins and noticed ProtocolLib and the Crates plugin both RED. So I know it loaded, it just can't start.

**To Reproduce**
1. Started from a fresh server
2. Installed ProtocolLib
3. Installed Geyser and Floodgate
4. Installed the Mystery Boxes (1.20.57) Premium Spigot Plugin
5. Plugin does not enable

I don't know or think they are related but who knows.

**Expected behavior**
I expect ProtocolLib and my Crates Plugin to both work. I am working towards opening for my closed beta so this throws a bit of a wrench in the gears.

**Screenshots**
This is a screenshot of my plugins list with every plugin I have installed, in case you need it.

![2024-07-18_19 44 18](https://github.com/user-attachments/assets/31e4c6ed-d489-43ff-a586-770a07093ccb)

**Version Info**
Protocol Dump fails with an internal server error, but I will add a pastebin link to the error I got in the log which DOES include version information.

ProtocolLib Error/Version Info: https://pastebin.com/cBEvKR5P

**Additional context**

I am unsure if my MC Version is the problem, but I will try rolling back to a 1.20.x build to test it but I do really want to use 1.21

**Comment by AdzelFirestar** [comment]
Update: I thought it was the version so I updated protocollib to 5.2 and still nothing.

**Comment by AdzelFirestar** [comment]
Nevermind, I am so sorry. I am an idiot. I needed Version 5.3 for 1.21. I will close this issue now. Sorry,

**Comment by GreeningSiren** [comment]
Could you close this issue, if your problem is resolved?
