### ISSUE TITLE
3.7.0 issue

### ISSUE THREAD

**Issue by slatttt** [dmulloy2/ProtocolLib#3138]
- [ ] This issue is not solved in a development build

Have a core for 1.7.10, a dependency is protocol lib 3.7.0. Did some troubleshooting and it seems protocol lib is throwing error codes and not allowing me to log in. I am stuck on the "logging in" screen, and and error is being thrown in console.

**Expected behavior**
Expected it to work like normal, but an error only gets thrown in console when this specific version of protocollib is being used

**Screenshots**
![image](https://github.com/user-attachments/assets/63e37f02-bb89-4c8f-9777-da794404ae3e).

**Version Info**
3.7.0

CONSOLE ERROR:
https://pastebin.com/WDxEy1hB

**Comment by dmulloy2** [comment]
where are you downloading it from? looks like the build you're using is missing a required class

**Comment by slatttt** [comment]
fixed
