### ISSUE TITLE
Signs show invisible when placed

### ISSUE THREAD

**Issue by zmw1234** [dmulloy2/ProtocolLib#314]
I'm using protocolib 4.2.1 and my server is running spigot 1.10 whenever I place signs down they show invisible than when the server restarts the sign shows. 

Not sure how to fix this issue but I believe it's an issue with ProtocolLib everything was working fine until I had installed ProtocolLib.

**Comment by dmulloy2** [comment]
It's probably a plugin that's using ProtocolLib. Run /protocol dump and paste the output using pastebin.

**Comment by dmulloy2** [comment]
Any more info on this?
