### ISSUE TITLE
Bump ProtocolLib Version in Repository to 5.2.0

### ISSUE THREAD

**Issue by Barpadzik** [dmulloy2/ProtocolLib#3140]
- [ ] This feature is not currently present in a development build

I would ask for version updates in the repository https://repo.dmulloy2.net/repository/public/
to version 5.2.0 to be able to use ProtocolLib by adding the library using maven and gradle

**Describe the solution you'd like**
Just bump to new version

**Describe alternatives you've considered**
I don't see any

**Additional context**
Nope

**Comment by dmulloy2** [comment]
oops. looks like i deployed 5.2.0-SNAPSHOT but not the actual release. i'd recommend just depending on 5.3.0-SNAPSHOT until the release of 5.3.0 (which should be later this week)
