### ISSUE TITLE
Unable to load normally.

### ISSUE THREAD

**Issue by OutHimic** [dmulloy2/ProtocolLib#3143]
- [ - ] This issue is not solved in a development build

**Describe the bug**
在尝试加载ProtocolLib插件时，遇到了内部错误，原因是找不到匹配字段。这表明ProtocolLib可能与服务器的版本（1.21）不兼容，或者存在代码问题。ProtocolLib的版本是5.2.0-SNAPSHOT-679。
An internal error was encountered when trying to load the ProtocolLib plug-in because no matching fields were found. This indicates that ProtocolLib may be incompatible with the server version (1.21), or there is a code problem. The version of ProtocolLib is 5.2.0-SNAPSHOT-679.
[latest.log](https://github.com/user-attachments/files/16362085/latest.log)

**To Reproduce**
Start the server.

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
