### ISSUE TITLE
(Bug) Internal Server Error

### ISSUE THREAD

**Issue by actuallySoheil** [dmulloy2/ProtocolLib#3144]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Go to Server
2. Kick for internal server error

**Expected behavior**
1. Not to get internal server error

**Version Info**
ProtocolLib v5.2.0
[dump-2024-07-25_14.18.15.txt](https://github.com/user-attachments/files/16375571/dump-2024-07-25_14.18.15.txt)

**Additional context**
Error log: https://pastes.dev/bOluD5hrja

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
