### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SenselessTaste** [dmulloy2/ProtocolLib#316]
19.04 22:49:26 [Server] INFO [ProtocolLib] Loading ProtocolLib v4.2.1
19.04 22:49:26 [Server] ERROR [ProtocolLib] The updater could not save the configuration in \plugins\Updater
19.04 22:49:26 [Server] WARN java.io.FileNotFoundException: plugins\Updater\config.yml (Access is denied)
19.04 22:49:26 [Server] WARN at java.io.FileOutputStream.open0(Native Method)
19.04 22:49:26 [Server] WARN at java.io.FileOutputStream.open(Unknown Source)
19.04 22:49:26 [Server] WARN at java.io.FileOutputStream.<init>(Unknown Source)
19.04 22:49:26 [Server] WARN at java.io.FileOutputStream.<init>(Unknown Source)
19.04 22:49:26 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:70)
19.04 22:49:26 [Server] WARN at com.comphenix.protocol.updater.BukkitUpdater.<init>(BukkitUpdater.java:117)
19.04 22:49:26 [Server] WARN at com.comphenix.protocol.updater.Updater.create(Updater.java:288)
19.04 22:49:26 [Server] WARN at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:212)
19.04 22:49:26 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:303)
19.04 22:49:26 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:260)
19.04 22:49:26 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73)
19.04 22:49:26 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14)
19.04 22:49:26 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185)
19.04 22:49:26 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521)
19.04 22:49:26 [Server] WARN at java.lang.Thread.run(Unknown Source)

**Comment by dmulloy2** [comment]
Is there something wrong with your updater configuration? If not, you could just disable update checking.

**Comment by dmulloy2** [comment]
Any more info on this?
