### ISSUE TITLE
error Couldn't place player in world 

### ISSUE THREAD

**Issue by Savranchuk** [dmulloy2/ProtocolLib#3163]
Hello, my player encountered a problem when connecting to the server. Periodically, the error Couldn't place player in world pops up. I was advised on the Internet to update ProtocolLib, but without success. I decided to write to you. My server is on version 1.20.1
[dump-2024-08-01_21.14.18.txt](https://github.com/user-attachments/files/16461990/dump-2024-08-01_21.14.18.txt)

**Comment by Savranchuk** [comment]
![image](https://github.com/user-attachments/assets/06554319-7871-4b2f-baf6-8b5e2d6131dc)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
