### ISSUE TITLE
LinkageError "Make sure you're not using this jar for multiple server instances!"

### ISSUE THREAD

**Issue by Wazez** [dmulloy2/ProtocolLib#317]
[ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!
- Server is using latest dev build of ProtocolLib (4.2.1)
- Minigame server will sometimes be unjoin-able for [Proxy] Lost connection to server
Error Log:
https://puu.sh/vqPtT/7be38a0dda.txt

Protocol Dump:
https://puu.sh/vqQ46/0c435fe81e.txt

**Comment by dmulloy2** [comment]
I suppose the first question is are you using it for multiple server instances?

**Comment by Wazez** [comment]
No, each server uses its own protocolLib jar

**Comment by dmulloy2** [comment]
Hmm well this is new. Unfortunately, linkage errors are notoriously difficult to pin down. My first guess is that it has to do with "MineHeroesSpigot". Could you try using regular Spigot and see if the problem persists?

**Comment by dmulloy2** [comment]
Any more info on this?

**Comment by xion87** [comment]
got the same issue, it happen only with my factions server in rare case (i am using 1.8.8 + viaversion) using 4.2.0
https://hastebin.com/zowusigobu.md

**Comment by ForceUpdate1** [comment]
Hello,
i have the same problem

**Comment by VPSync** [comment]
Same issue with us.

**Comment by VPSync** [comment]
This issue is still not fixed.

**Comment by xion87** [comment]
Issue is not fixed, happen more often with factions server and rarely in other server
