### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by klynium** [dmulloy2/ProtocolLib#3173]
**Describe the bug**
ProtocolLib won't enable on my Spigot/Paper server on MC 1.21 with paper build #126. Console said to send this:
05.08 22:08:27 [Server] INFO Stack Trace:
05.08 22:08:27 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
05.08 22:08:27 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
05.08 22:08:27 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
05.08 22:08:27 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
05.08 22:08:27 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
05.08 22:08:27 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
05.08 22:08:27 [Server] INFO at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
05.08 22:08:27 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
05.08 22:08:27 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211)
05.08 22:08:27 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
05.08 22:08:27 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583)
05.08 22:08:27 [Server] INFO Dump:
05.08 22:08:27 [Server] INFO Parameters: 
05.08 22:08:27 [Server] INFO [NULL]
05.08 22:08:27 [Server] INFO Sender:
05.08 22:08:27 [Server] INFO com.comphenix.protocol.ProtocolLib@65f4909c[
05.08 22:08:27 [Server] INFO statistics=<null>
05.08 22:08:27 [Server] INFO packetTask=<null>
05.08 22:08:27 [Server] INFO tickCounter=0
05.08 22:08:27 [Server] INFO configExpectedMod=-1
05.08 22:08:27 [Server] INFO updater=com.comphenix.protocol.updater.SpigotUpdater@8576805
05.08 22:08:27 [Server] INFO redirectHandler=<null>
05.08 22:08:27 [Server] INFO scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@496679e3
05.08 22:08:27 [Server] INFO commandProtocol=<null>
05.08 22:08:27 [Server] INFO commandPacket=<null>
05.08 22:08:27 [Server] INFO commandFilter=<null>
05.08 22:08:27 [Server] INFO packetLogging=<null>
05.08 22:08:27 [Server] INFO skipDisable=false
05.08 22:08:27 [Server] INFO isEnabled=false
05.08 22:08:27 [Server] INFO loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1ca6227
05.08 22:08:27 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=1.21-85-4efd24b,minecraftVersion=1.21}
05.08 22:08:27 [Server] INFO file=plugins/.paper-remapped/ProtocolLib.jar
05.08 22:08:27 [Server] INFO description=org.bukkit.plugin.PluginDescriptionFile@10eec8a0
05.08 22:08:27 [Server] INFO pluginMeta=org.bukkit.plugin.PluginDescriptionFile@10eec8a0
05.08 22:08:27 [Server] INFO dataFolder=plugins/ProtocolLib
05.08 22:08:27 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
05.08 22:08:27 [Server] INFO naggable=true
05.08 22:08:27 [Server] INFO newConfig=YamlConfiguration[path='', root='YamlConfiguration']
05.08 22:08:27 [Server] INFO configFile=plugins/ProtocolLib/config.yml
05.08 22:08:27 [Server] INFO logger=com.destroystokyo.paper.utils.PaperPluginLogger@1e1ad7a8
05.08 22:08:27 [Server] INFO lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@706aa6d1
05.08 22:08:27 [Server] INFO allowsLifecycleRegistration=true
05.08 22:08:27 [Server] INFO ]
05.08 22:08:27 [Server] INFO Version:
05.08 22:08:27 [Server] INFO ProtocolLib v5.2.0-SNAPSHOT-679
05.08 22:08:27 [Server] INFO Java Version:
05.08 22:08:27 [Server] INFO 21
05.08 22:08:27 [Server] INFO Server:
05.08 22:08:27 [Server] INFO 1.21-85-4efd24b (MC: 1.21)

**Version Info**
Cannot get because plugin won't load.

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
