### ISSUE TITLE
Repository Is Down (503 Service Unavailable)

### ISSUE THREAD

**Issue by conaticus** [dmulloy2/ProtocolLib#3191]
Hi @dmulloy2, seems like the ProtocolLib repository is offline? Any ideas when this will be back up as I am unable to install ProtocolLib atm.

![image](https://github.com/user-attachments/assets/50b7823e-6aad-48ff-95ea-3eb58b352f6d)

**Comment by Mykindos** [comment]
Been down for quite a while today, going to have to look to mirror it once its back

**Comment by BoomerSchmirtz** [comment]
In the meanwhile put ProtocolLib into your project and load it hardcoded.

**Comment by dmulloy2** [comment]
repo is back up!
