### ISSUE TITLE
Internal server error on join

### ISSUE THREAD

**Issue by Le4ft** [dmulloy2/ProtocolLib#3209]
- [ ] This issue is not solved in a development build

**Describe the bug**
When player tries to join on the server, he gets kicked with reason "Internal server error" and he needs to retry like 20 times before he can access the server normally.

**To Reproduce**
I just put ProtocolLib on my server and it started doing this

**Version Info**
https://pastebin.com/x1KZTzQn

**Additional context**
Console Error: https://pastebin.com/vJvPDbbb

**Comment by Braresa** [comment]
Yep, same problem here, 1.8.8 running paperSpigot, excepct that he player only needs to rejoin one time.

**Comment by Braresa** [comment]
> Yep, same problem here, 1.8.8 running paperSpigot, excepct that he player only needs to rejoin one time.

Downgrading to 5.1.0 solves the problem.

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
