### ISSUE TITLE
Problem with gradle downloading dependencies from maven repository

### ISSUE THREAD

**Issue by antain** [dmulloy2/ProtocolLib#321]
After thats event with your maven repository, gradle fails to download `com.comphenix.executors:BukkitExecutors:1.1-SNAPSHOT` with [stacktrace](https://pastebin.com/XqA3BtXK).

So it instead of [BukkitExecutors-1.1-20150822.182359-3.jar](http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-20150822.182359-3.jar) searching for [BukkitExecutors-1.1-20170419.214252-1.jar](http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/BukkitExecutors-1.1-20170419.214252-1.jar).

Is timestamp and buildNumber correct in [this file](http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml)? Should not it be 20150822.182359 and 3?

Example gradle config to test: [tar file with wrapper and sample sources](https://drive.google.com/file/d/0B8dZRx7cfSzSajBqZTJNeFRiQWM/view?usp=sharing) or [only config on pastebin](https://pastebin.com/ycRuZTGK).

**Comment by games647** [comment]
Could you clear your gradle cache and try it again? It works for me without any issues using wrapper 3.4.1

**Comment by dmulloy2** [comment]
I redeployed the artifacts from Jenkins after the repository failed. Maybe I just need to rebuild the project?
