### ISSUE TITLE
StreamSerializer doesn't work anymore

### ISSUE THREAD

**Issue by mauricelps** [dmulloy2/ProtocolLib#3216]
- [ ] This issue is not solved in a development build

**Describe the bug**
I utilize ProtocolLib's StreamSerializer Class to sync survival server inventorys across servers.
Up to 1.20.6 everything worked like a charm, however upgrading to 1.21 it does not work anymore.
I then tried to take the plugin, which I was using before (which also used ProtocolLib) and it does throw the same issue.

**To Reproduce**
1. Join the server
2.) Put Items in the Enderchest / Inventory (Inventory or Armor Slots)
3.) Change server to any other synced
3.1) Error on the server where the player was leaving from
3.2) No Error on the server where the player is joining on

**Expected behavior**
See above, starting at Step 3 - there should no error be on com.comphenix.protocol.utility.StreamSerializer

**Screenshots**
Stack Trace of said error: https://pastebin.com/QL55BdYG

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/2jcKyy7f)

**Additional context**

**Comment by JustRed23** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/pull/3217
