### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by trashiest-person** [dmulloy2/ProtocolLib#3218]
12:27:19 PM   [INFO] >   Stack Trace:
12:27:19 PM   [INFO] >   java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
12:27:19 PM   [INFO] >   at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
12:27:19 PM   [INFO] >   at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
12:27:19 PM   [INFO] >   at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:461)
12:27:19 PM   [INFO] >   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236)
12:27:19 PM   [INFO] >   at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
12:27:19 PM   [INFO] >   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
12:27:19 PM   [INFO] >   at java.base/java.lang.Thread.run(Thread.java:1583)
12:27:19 PM   [INFO] >   Dump:
12:27:19 PM   [INFO] >   Parameters:
12:27:19 PM   [INFO] >   [NULL]
12:27:19 PM   [INFO] >   Sender:
12:27:19 PM   [INFO] >   com.comphenix.protocol.ProtocolLib@1dd4c94d[
12:27:19 PM   [INFO] >   statistics=<null>
12:27:19 PM   [INFO] >   packetTask=<null>
12:27:19 PM   [INFO] >   tickCounter=0
12:27:19 PM   [INFO] >   configExpectedMod=-1
12:27:19 PM   [INFO] >   updater=com.comphenix.protocol.updater.SpigotUpdater@2c057299
12:27:19 PM   [INFO] >   redirectHandler=<null>
12:27:19 PM   [INFO] >   scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@17a048f5
12:27:19 PM   [INFO] >   commandProtocol=<null>
12:27:19 PM   [INFO] >   commandPacket=<null>
12:27:19 PM   [INFO] >   commandFilter=<null>
12:27:19 PM   [INFO] >   packetLogging=<null>
12:27:19 PM   [INFO] >   skipDisable=false
12:27:19 PM   [INFO] >   isEnabled=false
12:27:19 PM   [INFO] >   loader=org.bukkit.plugin.java.JavaPluginLoader@318bfc89
12:27:19 PM   [INFO] >   server=CraftServer{serverName=CraftBukkit,serverVersion=4226-Spigot-146439e-2889b3a,minecraftVersion=1.21}
12:27:19 PM   [INFO] >   file=plugins\ProtocolLib.jar
12:27:19 PM   [INFO] >   description=org.bukkit.plugin.PluginDescriptionFile@7b5a522
12:27:19 PM   [INFO] >   classLoader=org.bukkit.plugin.java.PluginClassLoader@2158c7a1
12:27:19 PM   [INFO] >   dataFolder=plugins\ProtocolLib
12:27:19 PM   [INFO] >   naggable=true
12:27:19 PM   [INFO] >   newConfig=YamlConfiguration[path='', root='YamlConfiguration']
12:27:19 PM   [INFO] >   configFile=plugins\ProtocolLib\config.yml
12:27:19 PM   [INFO] >   logger=org.bukkit.plugin.PluginLogger@4fb26f22
12:27:19 PM   [INFO] >   ]
12:27:19 PM   [INFO] >   Version:
12:27:19 PM   [INFO] >   ProtocolLib v5.2.0-SNAPSHOT-679
12:27:19 PM   [INFO] >   Java Version:
12:27:19 PM   [INFO] >   21.0.3
12:27:19 PM   [INFO] >   Server:
12:27:19 PM   [INFO] >   4226-Spigot-146439e-2889b3a (MC: 1.21)

**Comment by Kuina-chan** [comment]
Resolved in [#3207](https://github.com/dmulloy2/ProtocolLib/issues/3207)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
