### ISSUE TITLE
error on torchspigot 1.11.2

### ISSUE THREAD

**Issue by mat41997** [dmulloy2/ProtocolLib#322]
logs
https://gist.github.com/mat41997/ddd4df9a67911ec2a6a052893b245f07

timings
https://timings.aikar.co/?id=76b57fa585fb467484a472e1bc816862

torchspigot
https://github.com/TorchSpigot/Torch

**Comment by dmulloy2** [comment]
Oh god they made another Spigot fork? It's probably something Torch changed

**Comment by games647** [comment]
@mat41997 Which build do you downloaded?

**Comment by mat41997** [comment]
46
https://circleci.com/gh/TorchSpigot/Torch/46
https://46-61716775-gh.circle-artifacts.com/0/tmp/circle-artifacts.fuBBsNb/Torchpowered-1.11.2.jar

**Comment by games647** [comment]
@mat41997 Could you try this one: https://github.com/games647/ProtocolLib/releases/tag/torch

Changes: https://github.com/games647/ProtocolLib/commit/e4dda3948e0859b3bb4ff89bd5ee0ecef6253c88

**Comment by mat41997** [comment]
it's works, thx 🥇

**Comment by GotoFinal** [comment]
@dmulloy2 @games647 @mat41997 
Also... I suggest to check code of that torch.... it is just... crap?

https://github.com/TorchSpigot/Torch/commit/47996fc6cc7930ab4694cfe0673802585dc9950b#diff-740e50d82da655b5ea60a47ea6050ad7R20 like string#intern

https://github.com/TorchSpigot/Torch/blob/879779072b4218d8a18926bd338b0b3c157fe02e/sources/src/main/java/org/torch/server/Regulator.java#L42
Gotta Catch 'Em All! if there will be no tasks in that weird "regulator" server will stop...

```java
    public void sendAll(Packet<?> packet) {
        Regulator.post(() -> {
            for (int index = 0, size = this.players.size(); index < size; ++index) {
                this.players.get(index).playerConnection.sendPacket(packet);
            }
        });
    }
```
This will crash too. (if some player leave in the middle of iteration) And why he is even sending that packets in separate thread... while netty does that too...

https://github.com/TorchSpigot/Torch/commit/05082562835004f5b57655bd661198dcd5a551b1
* cough * 

Don't use this, and don't trust every repository on the internet ... :D

**Comment by dmulloy2** [comment]
@GotoFinal this is sketching me out as well: https://github.com/TorchSpigot/Torch/commits?author=md-5 seems to imply that @md-5 worked on the project, but the author of the patches is not md_5: https://github.com/TorchSpigot/Torch/commit/c160f0a6feda91d2fded6f8893402655b0682007#diff-ed7e2941960e681e59fe84c32cd14718R2

**Comment by GotoFinal** [comment]
@dmulloy2 @mat41997 this is fork of TacoSpigot, so it is fork of PaperSpigot, so it is fork of Spigot, so it is made mostly by md_5, that are just commits from Spigot.

**Comment by mat41997** [comment]
@GotoFinal torchspigot isn't not tacospigot fork
"Torch is a fork of Paper with multi-thread computing and further optimizations."

**Comment by GotoFinal** [comment]
@mat41997 whatever, still this same case.

**Comment by dmulloy2** [comment]
@gotofinal right, but the commits appear to be him adding patches specifically to torch, not regular spigot commits

**Comment by GotoFinal** [comment]
@dmulloy2 where...? That just normal commits, you can find them in spigot repo too

**Comment by dmulloy2** [comment]
@GotoFinal This commit (https://github.com/TorchSpigot/Torch/commit/5e63fd1846be1f97a021acec5851c0f49916a670) definitely isn't in regular Spigot

**Comment by GotoFinal** [comment]
@dmulloy2 so seems that he committed this using @md-5 e-mail/username
