### ISSUE TITLE
format money

### ISSUE THREAD

**Issue by Angelius782** [dmulloy2/ProtocolLib#3225]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
Make sure you've done the following:
- [V ] You're using the latest build for your server version
- [ V] This isn't fixed in a recent development build
- [ V] This isn't an issue caused by another plugin
- [V ] You've checked for duplicate issues
- [V ] You didn't use `/reload`
Debug paste link: i don't understad what is it ?
Description and relevant errors:

hello, i would like to format money count like something like this but i don't have find the command
    '1000': 1k
    '1000000': 1m
    '1000000000': 1b
    '1000000000000': 1t

exemple 1200000 => 1,2m

<img width="422" alt="Clipboarder 2024 09 09" src="https://github.com/user-attachments/assets/9bd02233-8eba-4ef2-8bf2-897794153f84">
<img width="422" alt="Clipboarder 2024 09 09" src="https://github.com/user-attachments/assets/32c002e3-e723-4ebb-a648-c1283ca1865c">

**Comment by ineanto** [comment]
Ce problème n'a rien à voir avec ProtocolLib?
This issue has nothing to do with ProtocolLib?

**Comment by Angelius782** [comment]
non, c'est pour simplescore

**Comment by ineanto** [comment]
Alors pourquoi avoir ouvert une issue sous le dépôt ProtocolLib ? Je te conseille de fermer cette issue et d’aller voir du côté de simplescore.

**Comment by Angelius782** [comment]
désolé je me suis tromper de lien... je repost labas, désolé et merci... ( je le ferme des que j'ai transferer labas )

**Comment by ineanto** [comment]
Pas de soucis ça arrive !

**Comment by Ingrim4** [comment]
I guess this unrelated to I'm just gone close this
