### ISSUE TITLE
Can you help me solve this problem?

### ISSUE THREAD

**Issue by FarhanComel** [dmulloy2/ProtocolLib#3232]
<html>
<body>

Stack Trace:
--
35 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
36 | at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
37 | at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
38 | at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
39 | at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
40 | at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
41 | at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
42 | at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
43 | at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:458)
44 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232)
45 | at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
46 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
47 | at java.base/java.lang.Thread.run(Thread.java:1583)
48 | Dump:
49 | Parameters:
50 | [NULL]
51 | Sender:
52 | com.comphenix.protocol.ProtocolLib@639ed12c[
53 | statistics=<null>
54 | packetTask=<null>
55 | tickCounter=0
56 | configExpectedMod=-1
57 | updater=com.comphenix.protocol.updater.SpigotUpdater@358a6d4b
58 | redirectHandler=<null>
59 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2088dd67
60 | commandProtocol=<null>
61 | commandPacket=<null>
62 | commandFilter=<null>
63 | packetLogging=<null>
64 | skipDisable=false
65 | isEnabled=false
66 | loader=org.bukkit.plugin.java.JavaPluginLoader@77df3515
67 | server=CraftServer{serverName=CraftBukkit,serverVersion=4195-b-Spigot-f6a4805-6524758,minecraftVersion=1.20.6}
68 | file=plugins/ProtocolLib.jar
69 | description=org.bukkit.plugin.PluginDescriptionFile@2789b4ce
70 | dataFolder=plugins/ProtocolLib
71 | classLoader=org.bukkit.plugin.java.PluginClassLoader@61727b7c
72 | naggable=true
73 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
74 | configFile=plugins/ProtocolLib/config.yml
75 | logger=org.bukkit.plugin.PluginLogger@d1f747f
76 | ]
77 | Version:
78 | ProtocolLib v5.2.0-SNAPSHOT-679
79 | Java Version:
80 | 21.0.3
81 | Server:
82 | 4195-b-Spigot-f6a4805-6524758 (MC: 1.20.6)

</body>
</html>Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:[35](https://aternos.org/log/#L35)2)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:[36](https://aternos.org/log/#L36)9)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:458)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6[39](https://aternos.org/log/#L39)ed12c[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@358a6d4b
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2088dd67
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@77df3515
      server=CraftServer{serverName=CraftBukkit,serverVersion=[41](https://aternos.org/log/#L41)95-b-Spigot-f6a4805-6524758,minecraftVersion=1.20.6}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2789b4ce
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@61727b7c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@d1f747f
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    4195-b-Spigot-f6a4805-652[47](https://aternos.org/log/#L47)58 (MC: 1.20.6)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
