### ISSUE TITLE
22:52:51] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by cassy-0** [dmulloy2/ProtocolLib#3235]
protocolib error in log  i send ss:
![error](https://github.com/user-attachments/assets/f9e0f089-f89e-4b5e-8b54-2d47a8d4835a)
![error22](https://github.com/user-attachments/assets/be3e1755-4c61-48ec-ac6a-891e5197bf3e)
whats that?

**Comment by cassy-0** [comment]
i dowloand nighcore latest version and protocolib latest version\

**Comment by cassy-0** [comment]
i dowloand latest version nightocre and latest version protocolib

**Comment by PupaakDev** [comment]
Same error here

**Comment by Shoruz** [comment]
I had that error, just download the newest version

**Comment by PupaakDev** [comment]
> I had that error, just download the newest version

It is the latest version.

**Comment by MagmaBro123** [comment]
> > I had that error, just download the newest version
> 
> It is the latest version.

Same issue.
