### ISSUE TITLE
PacketAdapter not working correctly for WINDOW_ITEMS packet

### ISSUE THREAD

**Issue by NewbieOrange** [dmulloy2/ProtocolLib#325]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

This seems to be a very old bug in ProtocolLib, but the original issue is closed(without being fixed).
#105 

Debug paste link:
http://paste.ubuntu.com/24517449/
Description and relevant errors:
When I am using the WindowItems packet to modify items in the inventory, I found that sometimes it doesn't work as expected. The modification to the event seems useless.
For example, I tried to determine if an inventory has a special InventoryHolder, and modify items in it if it has one, but even if I set the item array to an empty array, nothing was changed. I also tried to cancel the event, and used /packet add server 48 true. The plugin said that the event is cancelled, but the inventory still opened in the client with items inside.
Currently, I am using a workaround, which is to resend the modified packet a tick later:
http://paste.ubuntu.com/24517480/

Hope this can be fixed soon if it is not my fault.

**Comment by dmulloy2** [comment]
What code were you using before?

**Comment by NewbieOrange** [comment]
Here is the original code:
http://paste.ubuntu.com/24528397/

**Comment by dmulloy2** [comment]
Looks like extendedclip (from the other issue you linked), created a new list and that fixed the problem. Maybe try that?

**Comment by NewbieOrange** [comment]
I tired to write an empty array and nothing happened. Even cancelling the event has no effect at all.

**Comment by NewbieOrange** [comment]
Is there any progress?
