### ISSUE TITLE
No Player skins with Protocol Lib

### ISSUE THREAD

**Issue by RedstoneRobin** [dmulloy2/ProtocolLib#326]
Hi,
I've a problem, if I install Protocol Lib on my server, all Player skins are steve skins.
What should I do?

PS: I need Protocol Lib for many other plugins.

**Comment by games647** [comment]
Do you habe AuthMe installed? If so update to a dev-build.

**Comment by MiniDigger** [comment]
protocollib itself doesn't tamper with skins. please post a list of the plugins you use.
also note that skins only work in online mode. so if your server is in offline mode (and not behind bungee or behind an offline bungee) it will not show skins.

**Comment by RedstoneRobin** [comment]
1. I haven't installed AuthMe
2. The server is online-mode=false because it is a bungeecord network. But in the bungeecord config is
online-mode=true and ip_forward=true and in the spigot.yml is bungeecord=true.
3. Sorry for my bad english.

**Comment by MiniDigger** [comment]
> please post a list of the plugins you use.

another plugin is messing with it. we can't help you if you don't give us a list. you can also try disabling plugins one by one till its gets fixed.

**Comment by RedstoneRobin** [comment]
Plugins:
https://cloud.githubusercontent.com/assets/27922571/25771477/29792060-3253-11e7-9ab3-72ef79c79e4e.PNG

**Comment by dmulloy2** [comment]
Actually could you run ````/protocol dump```` and paste the output with pastebin? That'll give us a list of plugins that specifically use ProtocolLib.

**Comment by RedstoneRobin** [comment]
https://hastebin.com/abecofovub.rb

**Comment by dmulloy2** [comment]
Try removing iTag as a debugging step

**Comment by RedstoneRobin** [comment]
1. There is a problem... I need iTag for some of this plugins.
2. I will test it.

**Comment by RedstoneRobin** [comment]
Thank you!
Without iTag all Playerskins are loaded!
PS: I've changed the plugins who needs iTag to plugins who don't need iTag.

Sorry for my bad english again!

Edit: on my second server I've iTag and Protocol Lib too but there all of them necessary. What should I do now??

**Comment by dmulloy2** [comment]
Might be worth reporting this to md_5, I'm not sure there's anything I can do on ProtocolLib's end.
