### ISSUE TITLE
Player address

### ISSUE THREAD

**Issue by FlamestoN** [dmulloy2/ProtocolLib#328]
Hello.
My code:
```
protocolManager.getAsynchronousManager().registerAsyncHandler(new PacketAdapter(this,
                ListenerPriority.NORMAL,
                PacketType.Login.Client.START) {
            @Override
            public void onPacketReceiving(PacketEvent e) {
                System.out.println(e.getPlayer().getAddress());
            }
        }).start();
```
e.getPlayer().getAddress() returns the address of the server, not the address (IP) of the player.

**Comment by MiniDigger** [comment]
you behind bungeecord?

**Comment by FlamestoN** [comment]
yes

**Comment by MiniDigger** [comment]
have you enabled bungee and ip forwarding in the spigot config?

On May 9, 2017 13:05, Dmitry <notifications@github.com> wrote:

yes

**Comment by FlamestoN** [comment]
spigot.yml:
bungeecord: true

bungeecord config:
ip_forward: true


But if i listen PacketType.Play.Client.SETTINGS packet, then e.getPlayer().getAddress() returns the address of the player.

**Comment by games647** [comment]
I think it's because the Player returned on the Start packet isn't a player instance from Craftbukkit, because there is none at that moment. It could be a fake instance created by ProtocolLib in [TemporaryPlayerFactory](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/ProtocolLib/src/main/java/com/comphenix/protocol/injector/server/TemporaryPlayerFactory.java)

This doesn't access the real address set by Spigot on the Handshake packet.

**Comment by FlamestoN** [comment]
TemporaryPlayerFactory.getInjectorFromPlayer(e.getPlayer()).getAddress() also returns server address

**Comment by games647** [comment]
Because ProtocolLib doesn't read the handshake packet. If BungeeCord is enabled, every connections goes over the BungeeCord server. The real ip of a player is just sent as string inside the handshake packet. So plugins like anti bot can see the real ip instead of the bungee ip.

**Comment by FlamestoN** [comment]
so, no way get player address on packet PacketType.Login.Client.START behind bungeecord?

**Comment by FlamestoN** [comment]
Thank you games647.
Problem solved.
On the stage PacketType.Handshake.Client.SET_PROTOCOL bungeecord sends a string with the player's address.
