### ISSUE TITLE
Request: Update netty

### ISSUE THREAD

**Issue by Potothingi** [dmulloy2/ProtocolLib#3293]
- [x] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**
I think the performance is degraded by older versions of netty.

**Describe the solution you'd like**
Update netty.
https://github.com/dmulloy2/ProtocolLib/blob/3442d3fb8fda576fee30ed456b4d5f9f7b7e3b9f/build.gradle#L39
https://github.com/netty/netty/releases/tag/netty-4.0.23.Final
The latest netty is 4.1.114, but ProtocolLib is using version 4.0.23. This is an old version from 10 years ago.

**Describe alternatives you've considered**
Update netty.

**Additional context**
![image](https://github.com/user-attachments/assets/2d25a78c-bd0e-4717-a63c-ca38d7254f83)
Older versions of netty may cause poor performance.

**Comment by dmulloy2** [comment]
this is not actually the version of netty that's run on the server. it's just the one we compile against
