### ISSUE TITLE
Duplicate class definition

### ISSUE THREAD

**Issue by Likaos** [dmulloy2/ProtocolLib#33]
Got this message on a minigame server after the loaging, all players get kicked when connect, need to reboot the server to fix.

[20:29:21] [Server thread/INFO]: matthieu31320 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/comphenix/protocol/events/PacketContainer"

**Comment by dmulloy2** [comment]
Make sure you only have one ProtocolLib jar and no other plugins that mimic ProtocolLib's class path.

**Comment by Likaos** [comment]
I only have one protocollib jar in the plugins folder, see that 

http://puu.sh/ekkSb/32d46abbfa.png

The firstplayers join an the bug happens latter...

**Comment by dmulloy2** [comment]
This doesn't happen with just ProtocolLib.  What plugins do you have that use ProtocolLib?

**Comment by Likaos** [comment]
Custom plugins... with some listeners

**Comment by dmulloy2** [comment]
Try removing them and see if it fixes the problem.

**Comment by Likaos** [comment]
That doesn't fix the problem, I've above 100 spigot running, they all use the same script / jar / configuration and I have this problem on several without any reason.

New problem this morning https://puu.sh/emF9F/d2adc957cb.png

**Comment by Likaos** [comment]
Fixed by removing packetWrapper (last version) and using only protocollib (last version too).
