### ISSUE TITLE
spigot 1.12 pre errors

### ISSUE THREAD

**Issue by ardentcrest** [dmulloy2/ProtocolLib#330]
11:52:05 [SEVERE]   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x438655e1, L:/192.168.1.100:25565 - R:/45.33.29.47:54382].
11:52:05   If this problem hasn't already been reported, please open a ticket
11:52:05   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
11:52:05   Stack Trace:
11:52:05   java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x438655e1, L:/192.168.1.100:25565 - R:/45.33.29.47:54382]
11:52:05   	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
11:52:05   	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
11:52:05   	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
11:52:05   	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
11:52:05   	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
11:52:05   	at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
11:52:05   	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
11:52:05   	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
11:52:05   	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
11:52:05   	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
11:52:06   	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
11:52:06   	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472)
11:52:06   	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
11:52:06   	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
11:52:06   	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85)
11:52:06   	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:259)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11:52:06   	at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:171)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11:52:06   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:52:06   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:52:06   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
11:52:06   	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
11:52:06   	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
11:52:06   	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
11:52:06   	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
11:52:06   	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
11:52:06   	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
11:52:06   	at java.lang.Thread.run(Thread.java:745)
11:52:06   Dump:
11:52:06     manager:
11:52:06       com.comphenix.protocol.injector.PacketFilterManager@20e5c91e[
11:52:06         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@23f4d770
11:52:06         packetListeners=[]
11:52:06         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2e1024c4
11:52:06         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7c45466f
11:52:06         interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@72e6cdc0
11:52:06         inputBufferedPackets=[]
11:52:06         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@77accbbb
11:52:06         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@58b5e78e
11:52:06         hasClosed=false
11:52:06         classLoader=org.bukkit.plugin.java.PluginClassLoader@668d4309
11:52:06         reporter=com.comphenix.protocol.ProtocolLib$1@e15b4c9
11:52:06         server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-429b0e3-5195487,minecraftVersion=1.12-pre2}
11:52:06         library=ProtocolLib v4.2.1
11:52:06         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5b390be5
11:52:06         knowsServerPackets=true
11:52:06         knowsClientPackets=true
11:52:06         phaseLoginCount=0
11:52:06         phasePlayingCount=0
11:52:06         packetCreation=false
11:52:06         spigotInjector=<null>
11:52:06         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@19fe088d
11:52:06         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@dd9feef
11:52:06         hasRecycleDistance=true
11:52:06         minecraftVersion=(MC: 1.12.0-pre2)
11:52:06         loginPackets=com.comphenix.protocol.injector.LoginPackets@389a6d86
11:52:06         debug=false
11:52:06       ]
11:52:06   Sender:
11:52:06     com.comphenix.protocol.injector.netty.ProtocolInjector@19fe088d[
11:52:06       injected=true
11:52:06       closed=false
11:52:06       playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@68a18d93
11:52:06       bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@28035185, container=net.minecraft.server.v1_12_R1.ServerConnection@4c2a8c03, previous=[AbstractBootstrap$PendingRegistrationPromise@5f182ef6(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@6b232022, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@599edbba, container=net.minecraft.server.v1_12_R1.ServerConnection@4c2a8c03, previous=[net.minecraft.server.v1_12_R1.NetworkManager@5355750a], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
11:52:06       injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@414c0e1e
11:52:06       networkManagers=[net.minecraft.server.v1_12_R1.NetworkManager@5355750a]
11:52:06       sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@5fbde75f
11:52:06       reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@2dedfeba
11:52:06       mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@201b3b6
11:52:06       bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@239c6116
11:52:06       invoker=com.comphenix.protocol.injector.PacketFilterManager@20e5c91e
11:52:06       reporter=com.comphenix.protocol.ProtocolLib$1@e15b4c9
11:52:06       debug=false
11:52:07     ]
11:52:07   Version:
11:52:07     ProtocolLib v4.2.1
11:52:07   Java Version:
11:52:07     1.8.0_121
11:52:07   Server:
11:52:07     git-Spigot-429b0e3-5195487 (MC: 1.12-pre2)``

**Comment by ardentcrest** [comment]
also 
11:43:38 [INFO] Error Unable to inject incoming channel [id: 0x4d402703, L:/192.168.1.100:25565 - R:/192.168.1.100:64764]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x4d402703, L:/192.168.1.100:25565 - R:/192.168.1.100:64764]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@19fe088d.``

**Comment by dmulloy2** [comment]
Try the last successful build: http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by ardentcrest** [comment]
`22:04:28 [INFO] Error Unable to inject incoming channel [id: 0x91ea5796, L:/192.168.1.100:25565 - R:/45.33.29.47:52836]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x91ea5796, L:/192.168.1.100:25565 - R:/45.33.29.47:52836]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@36a6fe70.`

**Comment by bwl** [comment]
I'm getting a similar error message with the latest build as well.

https://gist.github.com/bwl/07177477350c29e6cb73f1f4d67f31fb

**Comment by SlimeDog** [comment]
Also getting these errors with #359 on Spigot 1.11.2 latest. Should this not be run until 1.12 ?
