### ISSUE TITLE
Cannot build ProtocolLib due to 1.21.2 not being available on any repositories.

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#3302]
Cannot build ProtocolLib due to 1.21.2 not being available on any repositories.
https://pastebin.com/raw/cvCbkAZz

Attempted to use our own Maven repo via Jenkins but Gradle doesn't automatically consider the maven local repo.
Needs to be either fixed in Protocollib, or codemc needs to deploy 1.21.2

Due to the fast release of 1.21.3 post 1.21.2, things got overlooked it seems. @dmulloy2

**Comment by dmulloy2** [comment]
interesting. looks like codemc replaced 1.21.2 with 1.21.3. easy enough to fix on our end, though

**Comment by dmulloy2** [comment]
Fixed in bcff6c6
