### ISSUE TITLE
Error and client disconnect - API incompatibility? (b357 on Spigot 1.12-pre2)

### ISSUE THREAD

**Issue by asofold** [dmulloy2/ProtocolLib#332]
With ProtocolLib build 357, the client connection gets reset when trying to connect to 127.0.0.1. It happens with NoCheatPlus around build 1109 on, but not when ProtocolLib is the only plugin. NCP is built against the ProtocolLib-API 4.2.1 - also tried with building against ProtocolLib-API 4.2.2-SNAPSHOT... same thing.

Exception: https://gist.github.com/asofold/9ccb9cd04b31b735b3ff2da537810f22

Could this be an API-incompatibility issue due to Mojang having updated some dependencies?
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre2-released.240317/  perhaps around "Mojang has updated Guava to version 21.0.".

----

If i set the server address to localhost the client will crash with "java.lang.NullPointerException: Ticking screen", which appears to be a client-side issue rather.

**Comment by dmulloy2** [comment]
That seems likely. I just officially updated to the pre-release, so try out build [358](http://ci.dmulloy2.net/job/ProtocolLib/358/) (once it's done building)

**Comment by asofold** [comment]
Looks good - now i can connect - packet listeners appear to work.

Still there are two exceptions thrown for short moving around: https://gist.github.com/asofold/70ee8bf29a19c21c6a9c0667dea2f4ca

(Looks like one is with login and one with logout.)

**Comment by asofold** [comment]
Thank you very much for the fast reaction :).
