### ISSUE TITLE
wiki.vg closed?

### ISSUE THREAD

**Issue by isArkaDarkTime** [dmulloy2/ProtocolLib#3320]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Description and relevant errors:
Recently I tried to open wiki.vg and could not enter, I read the information on the Internet and found:
wiki.vg will cease operation on November 30, 2024.
I try to use vpn, he doesn't help.

**Comment by dmulloy2** [comment]
yeah it would appear so. i noticed this as well during a recent MC update. kinda makes sense unfortunately since i'm sure it was just a time/money sink

**Comment by dmulloy2** [comment]
not sure what their future plans are, if they have any. i never had anything to do with the project

**Comment by dmulloy2** [comment]
answer: minecraft.wiki: https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Protocol
