### ISSUE TITLE
Build 358+ no longer works on 1.1.2

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#333]
All builds above 357 are broken. 358-361.
With 361 I get the following on my client when trying to connect: http://i.imgur.com/UkvlIK3.png

**Comment by dmulloy2** [comment]
Mojang/Netty made some change that's causing a lot of bizarre problems. I'm just not sure what it is yet.

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/f99b977888d4ff10e2d347848ccf51d2e330765f
