### ISSUE TITLE
Is ProtocolLib for 1.12 going to support 1.11-1.8 too?

### ISSUE THREAD

**Issue by joserobjr** [dmulloy2/ProtocolLib#334]
I liked how it was one jar for all common versions, this simplified the things a lot and allowed us to do some fancy stuffs when ViaVersion is present. Is ProtocolLib 4.3.0+ going to work on 1.11-1.8 servers too?

**Comment by MiniDigger** [comment]
there is no reason to remove legacy support. 
protocollib was build in a way that it doesn't need much adjustments to new versions. 
it should always work (or be somewhat easy to fix) for the current way mojang does networking.

**Comment by dmulloy2** [comment]
The current dev builds are just a stopgap to support 1.12 once it's officially released

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/f99b977888d4ff10e2d347848ccf51d2e330765f
