### ISSUE TITLE
NPE with readSafely on ChatTypes

### ISSUE THREAD

**Issue by games647** [dmulloy2/ProtocolLib#336]
The ChatTypes enum only exists in 1.12, so I use the readSafely method which should return null if the field doesn't exist. Unfortunately here occurs a NPE inside ProtocolLib while accessing the subtypeCache ([ProtocolLib code](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/reflect/StructureModifier.java#L456)).

Details:
    - Tested Server: Spigot 1.11.2  (but 1.12 works)
    - ProtocolLib 4.3.0 latest build # 364
    - Related bug report on plugin page: games647/mcMMOAction/issues/10
    - PacketType: `PacketType.Play.Server.CHAT`

Plugin code - [link](https://github.com/games647/mcMMOAction/blob/master/src/main/java/com/github/games647/mcmmoaction/MessageListener.java#L37)
```java
        PacketContainer packet = packetEvent.getPacket();
        ChatType chatType = packet.getChatTypes().readSafely(0); //NPE on readSafely
        if (chatType == null) {
            //< 1.12 minecraft version
            chatType = ChatType.values()[packet.getBytes().read(0)];
        }
``` 

Exception: [hastebin](https://hastebin.com/nuyezejifu.css)

**Comment by dmulloy2** [comment]
The exception link isn't working

**Comment by games647** [comment]
>The exception link isn't working

I don't know what went wrong there, but it looks like you fixed it anyway.
