### ISSUE TITLE
Signs, Player Heads, armor stands, etc. are invisible when placed on Spigot 1.10.2 with Jenkins build #301 and newer

### ISSUE THREAD

**Issue by wilsondc15** [dmulloy2/ProtocolLib#338]
Signs, Player Heads, armor stands, etc. are invisible when placed on Spigot 1.10.2 with Jenkins build #301 and newer

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).
