### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by WhiteKyurem2003** [dmulloy2/ProtocolLib#343]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:https://pastebin.com/vqb8jXG0

Description and relevant errors:When a player logs in or logs out it spams the chat and console with that error.

**Comment by dmulloy2** [comment]
> You're using the latest build for your server version
You need to use 4.3.0 for Spigot 1.12.
