### ISSUE TITLE
Netty Epoll Server IO:Failed to initialize a channel.

### ISSUE THREAD

**Issue by LordChaos88** [dmulloy2/ProtocolLib#344]
Debug paste link:
https://pastebin.com/YQUdQFS8
***
ProtocolLib Dump
Timestamp: 06/09/17 20:36:09

ProtocolLib Version: ProtocolLib v4.2.1
Bukkit Version: 1.12-R0.1-SNAPSHOT
Server Version: git-Spigot-d5dfb24-ed8c725 (MC: 1.12)
Java Version: 1.8.0_112
***
Description and relevant errors:
I have updated all of the plugins including ProtocolLib to 4.2.1. and noticed that the error coming from ProtocolLib is spamming the console. My server (Spigot 1.12) will not be able to start up from that point. Can you see into the pastebin link I provided and see what did I do incorrectly? Or is that a bug coming from ProtocolLib? I am not exactly sure. Thank you for taking your time to look into this and help me out with it.

Sincerely,
LordChaos88

**Comment by LordChaos88** [comment]
Adding another pastebin link that might be of helpful to you. This is the first warning that comes before the paste link I gave you above.

Pastebin link:
https://pastebin.com/0sbin8H8

**Comment by LordChaos88** [comment]
Forgive me, but I successfully got the Stack Trace/Dump of the ProtocolLib situation. It seems that in the Stack Trace I actually have "Unable to find NetworkManager" error? If thats the case, could you tell me on how to have it fixed? Thanks :)
Pastebin link:
https://pastebin.com/3qxssCPY

**Comment by dmulloy2** [comment]
You need to use 4.3.0 for Spigot 1.12.

**Comment by LordChaos88** [comment]
I am on ProtocolLib 4.3.0 and it is still throwing a lot of console errors.
