### ISSUE TITLE
ProtocolLib > 369 loads up until the server is unresponsive

### ISSUE THREAD

**Issue by RobertLHarris** [dmulloy2/ProtocolLib#345]
When using ProtocolLib 369 and lower the server runs fine.  When I try 370+ the load on the server just very slowly just keeps climbing until the machine becomes unresponsive.  I've tried getting timings reports but the server becomes too unresponsive.  There is no console or visible output.  I found out it was ProtocolLib as I did a process of elimination on the different modules until I had it down to just ProtocolLib.

I'm running the latest spigot and these plugins.:

{0}:/usr/local/minecraft/plugins>ls -1 *.jar
AdminPlayerMenu-1.10.5.jar
AutoMessage-2.5.4.jar
CS-CoreLib_v1.5.14.jar
CommandStalker-1.0.jar
CoreProtect_2.14.2.jar
Dynmap-Essentials-0.91.jar
Dynmap-TARDIS-1.2.2-19.jar
Dynmap-Towny-0.71.jar
Dynmap-WorldGuard-0.90.jar
Essentials-2.x-SNAPSHOT-21.jar
EssentialsChat-2.x-SNAPSHOT-21.jar
EssentialsSpawn-2.x-SNAPSHOT-21.jar
GUIShop-6.1.4.jar
LibsDisguises-9.0.9-125.jar
Lockette-1.8.33.jar
Multiverse-Core-2.5-727.jar
Multiverse-NetherPortals-2.5-717.jar
Multiverse-Portals-2.5-751.jar
NightVisionReloaded-1.3.jar
OpenInv-3.2.1.jar
Parties-1.5.9.jar
PlayerVaults-210.jar
ProjectRassilon-2.0-PREVIEW-01.jar
ProtocolLib-4.3.0-369.jar
Questioner-91.1.0.0.jar
SQLibrary.jar
SilkSpawners-421.jar
SkQuery-Lime 1.11.jar
Skript-dev28c.jar
TARDIS-3.6-1628.jar
TARDISChunkGenerator-2.4-32.jar
TARDISWeepingAngels-2.3-89.jar
TerrainControl-2.8.2-176.jar
Towny-0.91.4.7.jar
TownyNameUpdater-91.1.0.0.jar
VanishNoPacket-v3.20.jar
Vault-1.6.6-01.jar
VoidWorld.jar
WorldBorder.jar
bPermissions-2.12-all-174.jar
craftbook-3.9-159.jar
dynmap-2.6-0.jar
dynmap-structures-1.1.0-all.jar
mcMMO-190.jar
worldedit-bukkit-6.1.7.2.jar
worldguard-6.2.1.jar

**Comment by dmulloy2** [comment]
That's really ...odd... since 370 is a single-line change of little significance. There's probably some other issue at play here.

**Comment by RobertLHarris** [comment]
Possibly, but if I have my system running great on 1.11.2 or 1.12 then upgrade from 369 to 370+, it will lag out and die within a day.  If I roll back to 369, I'm fine again.  I've done it many times.  Do you have any way to turn on debugging?

**Comment by dmulloy2** [comment]
There are multiple debugging mechanisms, in the ProtocolLib config, spigot.yml, and server.properties
