### ISSUE TITLE
Error in console when players refresh server list and can't join the server

### ISSUE THREAD

**Issue by maxlehot1234** [dmulloy2/ProtocolLib#347]
Debug paste link:
https://pastebin.com/w6yMiRpB

Description and relevant errors:
Hi when players refresh thjeir servers list, I get the error above.
They need to refresh their servers list at least 10-20 times to be able to see my server online and join it.

Directly when I remove ProtocolLib from my server, issue was fix.

I use PaperSpigot-1.12-b1111
Java 8
Latest Protocol Lib devbuild version ( #372)

Thank you

**Comment by Lucas-Uchiha** [comment]
The same occur on Bukkit 1.12. Fix please, thanks.

**Comment by dmulloy2** [comment]
I can tell you right now you're not using the latest dev build. That error was fixed a while ago

**Comment by maxlehot1234** [comment]
@dmulloy2 Really? I use the #372 build and I have this error....

**Comment by dmulloy2** [comment]
Yes, because line 241 in ListeningWhitelist.java doesn't reference that method: https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/events/ListeningWhitelist.java#L241

**Comment by FabioZumbi12** [comment]
@dmulloy2 The latest dev its #372 pm 09/06. Is there other location with your latest dev modified version?

**Comment by maxlehot1234** [comment]
@dmulloy2 Whitelist was disabled on my server and I have the same issue. Me and @FabioZumbi12 have build #372.

Where we can get the realt latest one in this case?

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/ProtocolLib/releases/tag/4.3.0

**Comment by maxlehot1234** [comment]
Solve in this new release. I think you can close this ticket ;) Thanks for the update even if you can't reproduce the problem.
