### ISSUE TITLE
[API] How check if player was created by TemporaryPlayerFactory?

### ISSUE THREAD

**Issue by Dimatert9** [dmulloy2/ProtocolLib#349]
Crash: https://pastebin.com/cvbmJNbN

Plugin source code:
https://github.com/Dimatert9/ItemFixer/blob/master/src/ru/leymooo/fixer/NBTListener.java#L32-L33
https://github.com/Dimatert9/ItemFixer/blob/master/src/ru/leymooo/fixer/NBTListener.java#L42

https://www.spigotmc.org/threads/itemfixer-remove-cheats-items-from-your-server.206139/page-5#post-2480277

I hope you will help me.

**Comment by dmulloy2** [comment]
The player should be instanceof InjectorContainer, which is in the same package as the factory.

**Comment by Dimatert9** [comment]
Thanks. I will check it later.

**Comment by games647** [comment]
@dmulloy2 

That class is not public.

**Comment by Dimatert9** [comment]
@dmulloy2 
![image](https://user-images.githubusercontent.com/8667294/27459182-9cb00102-57b5-11e7-9ed4-3043d3dcbec7.png)
it isnt plublic

**Comment by dmulloy2** [comment]
[This commit](https://github.com/dmulloy2/ProtocolLib/commit/390c21f6d55c342717e907bbb86d76324379502a) adds an API to check and attempts to limit the instances of temporary players.

**Comment by Dimatert9** [comment]
Thanks. But how check if player is temporary for old protocollib?
event.getPlayer().getClass().getSimpleName().equals("InjectorContainer"); this will work?

**Comment by dmulloy2** [comment]
A generic, backwards-compatible way to check would be
````if (event.getPlayer() instanceof Factory)````
Factory is a class in CGLib

**Comment by Dimatert9** [comment]
Thanks.
