### ISSUE TITLE
java.util.NoSuchElementException: decoder

### ISSUE THREAD

**Issue by TheChampTF** [dmulloy2/ProtocolLib#35]
Environment:
Java version: 1.7.0_03 Oracle Corporation
Operating system: Linux 2.6.38-8-server amd64
Bukkit version: git-Bukkit-96d09e3 (MC: 1.8)

07.01 21:00:57 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:312) [ProtocolLib.jar:?]
07.01 21:00:57 [Server] INFO at net.minecraft.server.v1_8_R1.QueuedProtocolSwitch.run(SourceFile:163) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPromise.addListeners(DefaultChannelPromise.java:28) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPromise.addListeners(DefaultChannelPromise.java:99) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.util.concurrent.DefaultPromise.addListeners(DefaultPromise.java:180) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:144) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:624) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:682) [custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListenerInnerClass1.operationComplete(SourceFile:88) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListenerInnerClass1.a(SourceFile:91) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:203) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5$1.addBefore(ChannelInjector.java:269) ~[?:?]
07.01 21:00:57 [Server] INFO at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:50) ~[?:?]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[custom.jar:git-Bukkit-96d09e3]
07.01 21:00:57 [Server] INFO java.util.NoSuchElementException: decoder
07.01 21:00:57 [Server] WARN An exception was thrown by net.minecraft.server.v1_8_R1.LoginListenerInnerClass1.operationComplete()

Got told to report it here from https://hub.spigotmc.org/jira/browse/SPIGOT-378

**Comment by dmulloy2** [comment]
What version of ProtocolLib are you using?

**Comment by TheChampTF** [comment]
284, sorry forgot to write that.

**Comment by dmulloy2** [comment]
I can't seem to reproduce this.  Can you provide some more context, like which of your plugins use ProtocolLib, any other protocol-related plugins, and the circumstances in which this error occurred?

**Comment by dmulloy2** [comment]
Closed due to lack of information.
