### ISSUE TITLE
Idk what it is

### ISSUE THREAD

**Issue by DennisFusha** [dmulloy2/ProtocolLib#350]
I am not 100% its protocol but the name protocol keeps popping up in the error.
Verison: Latest
Mc Version: 1.11.2

PL you can seet it in log

**Comment by Ghostium** [comment]
Hey, could you please add a list of installed plugins, your server version (Minecraft and Spigot?) and your Protocollib version plus, if you use it, the version of your Bungeecord. This will help the maintainer to help you faster.

**Comment by MiniDigger** [comment]
don't copy the log out of multicraft. that stupid things skips lines and sells that as a feature. grab the log out of the log file on your disk. its also easier to read the log if you post it to pastebin as the formatting isn't touched.
plus everyting ^ said.

**Comment by DennisFusha** [comment]
I cant upload the log in zip

**Comment by DennisFusha** [comment]
[LatestLog.txt](https://github.com/dmulloy2/ProtocolLib/files/1083219/LatestLog.txt)

**Comment by DennisFusha** [comment]
i tried removing protocol that fixed the problem but a few options in plugins don't work.
[latest.txt](https://github.com/dmulloy2/ProtocolLib/files/1083221/latest.txt)

**Comment by Ghostium** [comment]
Removing ProtocolLib does not helping in resolving the original error, it only prevents the error from happening. It would be nice if you could install ProtocolLib again, and uploading the error log, because maybe other users have this problem too, and then the problem can be resolved for everyone.

**Comment by dmulloy2** [comment]
I'm gonna need a ProtocolLib stack trace if we're gonna get anywhere

**Comment by DennisFusha** [comment]
??? what is a protocollib stack?

**Comment by DennisFusha** [comment]
Ok i installed protocol again i will send the error again.

**Comment by Ghostium** [comment]
The error log you previous posted contained a so-called stack trace. Its just a hint for the programmer where the error happened to help to fix bugs faster. Just append your server log when the error occurs again.
