### ISSUE TITLE
Repo down, again

### ISSUE THREAD

**Issue by MiniDigger** [dmulloy2/ProtocolLib#353]
[ERROR] Failed to execute goal on project voxelgameslib: Could not resolve dependencies for project me.minidigger:voxelgameslib:jar:2.0-SNAPSHOT: Failed to collect dependencies at com.comphenix.protocol:ProtocolLib:jar:4.3.0: Failed to read artifact descriptor
for com.comphenix.protocol:ProtocolLib:jar:4.3.0: Could not transfer artifact com.comphenix.protocol:ProtocolLib:pom:4.3.0 from/to protocollib-repo (http://repo.dmulloy2.net/content/groups/public/): repo.dmulloy2.net: Unknown host repo.dmulloy2.net -> [Help 1]

**Comment by dadus33** [comment]
Indeed, the whole of dmulloy2.net seems to be down.

**Comment by dmulloy2** [comment]
Ahh so funny story, I cancelled my web hosting last month but never migrated the DNS back. Should be back up shortly

**Comment by dmulloy2** [comment]
Back up, sorry for the downtime
