### ISSUE TITLE
Add a way to get the ChatMessageType enum in PacketPlayOutChat

### ISSUE THREAD

**Issue by geNAZt** [dmulloy2/ProtocolLib#358]
They changed the way chat position is sent in 1.12 from a byte to a ChatMessageType enum. Protocollib misses a StructureModifier for that type of enum. Please add it :) Thanks

**Comment by games647** [comment]
What about [getChatType](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L964)
