### ISSUE TITLE
Protocol new version error,

### ISSUE THREAD

**Issue by DennisFusha** [dmulloy2/ProtocolLib#360]
Hey, i tried second newest version of protocol on my latest spigot 1.11.2 server and then i have no error's but when i try latest one i get this error

[2017-06-23-1.txt](https://github.com/dmulloy2/ProtocolLib/files/1099224/2017-06-23-1.txt)

**Comment by dmulloy2** [comment]
> second newest version of protocol
What version are you using?

**Comment by DennisFusha** [comment]
ProtocolLib v4.2.1

**Comment by dmulloy2** [comment]
Update to 4.3.0.

**Comment by DennisFusha** [comment]
dmulloy i did but then i get the errors that u can see above so when i use 4.2.1 i don't get them.
