### ISSUE TITLE
[B not found in custom payload

### ISSUE THREAD

**Issue by sinnlosername** [dmulloy2/ProtocolLib#362]
I'm trying to send a custom payload (plugin message) to the client. In older versions it worked by writing the data as a byte array, but now it doesn't find a field of type [B. 

Version: 4.2 
Server: 1.8.8
Code: http://p.reflex.rip/9GNi.scala
Error: `[12:00:39 WARN]: FieldAccessException: No field with type [B exists in class PacketPlayOutCustomPayload.`

**Comment by MiniDigger** [comment]
not sure why it wouldn't work, but is there a reason you can't use bukkits inbuild plugin messaging api?

**Comment by dmulloy2** [comment]
They were changed to packet data serializers (generically `ByteBuf`s)
