### ISSUE TITLE
1.12 Title Action Updates

### ISSUE THREAD

**Issue by NecroneUnderscore** [dmulloy2/ProtocolLib#364]
http://wiki.vg/Protocol#Title

TitleAction enum needs ACTION_BAR

NMS code for title action
https://hastebin.com/womuzagaxo.cs

Thanks

**Comment by dmulloy2** [comment]
You could always pull request it ;)

**Comment by NecroneUnderscore** [comment]
Sorry I just thought you might want to keep ProtocolLib up to date with minecraft, my bad.

**Comment by MiniDigger** [comment]
@NecroneUnderscore he was just pointing out that protocol lib is open source and that a small change like this would be a perfect first contribution to the project. No need to get all angry.
