### ISSUE TITLE
Can't join a Server while listening for a packet

### ISSUE THREAD

**Issue by Min3MonDE** [dmulloy2/ProtocolLib#365]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
https://pastebin.com/wZ1Y9dfD

Description and relevant errors:
BungeeCord Error: https://pastebin.com/VhsGspp4
Server Error: `IQ4 lost connection: Internal Exception: java.io.IOException: Error while write(...): Connection reset by peer`
I'm listening for the MAP_CHUNK packet. If the Clients version is 1.11 the client can't connect. I'm doing nothing with the packet. My code: https://pastebin.com/SPVFV7pK
I'm using ViaVersion for multiversion support. Without running the code no error appears. I'm using this code to check for a client loading a chunk to resend entity packets. Other packettypes work -> no error, can connect.

**Comment by MiniDigger** [comment]
are you sure that you need to cancel the event? did only glimpse over your code, but that seems kinda off

**Comment by Min3MonDE** [comment]
the same error appears not canceling the event..

**Comment by dmulloy2** [comment]
The map chunk packet was removed at some point. I don't remember the exact version, but I'm not surprised that causes issues across versions.
