### ISSUE TITLE
NotSerializableException: net.minecraft.server.v1_12_R1.NBTTagByte

### ISSUE THREAD

**Issue by mibby** [dmulloy2/ProtocolLib#366]
@dmulloy2 Forwarding to you since libraryaddict claims this is a ProtocolLib issue. https://github.com/libraryaddict/LibsDisguises/issues/236

LibsDisguise dev 132
Paper dev 1133 (Spigot 1.12)
ProtocolLib dev 374

http://paste.ubuntu.com/24961628/

**Comment by dmulloy2** [comment]
Does this happen with the 4.3.0 release?

**Comment by mibby** [comment]
Not entirely sure. Just something I noticed when scanning my log files for errors the other day. I tend to always stay up to date with the latest source / dev builds.

**Comment by dmulloy2** [comment]
That commit was mostly untested changes to hopefully work with Java 9. Apparently it's gonna be a bloodbath with reflection, so I'd like to get out ahead of it. Could you try with 4.3.0 and let me know if the error persists?

**Comment by Cryptite** [comment]
I get this now too with a health spoof packet clone.
Trace: https://hastebin.com/evicirefoc.md

Code:
`ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(plugin, ENTITY_METADATA) {
            public void onPacketSending(PacketEvent event) {
                try {
                    Player observer = event.getPlayer();
                    StructureModifier<Entity> entityModifer = event.getPacket().getEntityModifier(observer.getWorld());
                    org.bukkit.entity.Entity entity = entityModifer.read(0);
                    if (entity != null && observer != entity && entity instanceof Player
                            && (entity.getPassenger() == null || entity.getPassenger() != observer)) {
                        event.setPacket(event.getPacket().deepClone());
                        StructureModifier<List<WrappedWatchableObject>> watcher = event.getPacket()
                                .getWatchableCollectionModifier();
                        for (WrappedWatchableObject watch : watcher.read(0)) {
                            if (watch.getIndex() == 7 && (float) watch.getValue() > 0) {
                                watch.setValue(r.nextInt((int) ((LivingEntity) entity).getHealth()) + r.nextFloat());
                            }
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });`

**Comment by Cryptite** [comment]
Was this closed on account of being fixed? Don't see any new builds is why I ask

**Comment by MiniDigger** [comment]
it was closed as part of a big house cleaning mission. if you still have this issue on the latest build, please state so so that this can be reopened.

**Comment by Cryptite** [comment]
Indeed I was using b390 when I posted my comment.
