### ISSUE TITLE
When I join my server?

### ISSUE THREAD

**Issue by Serhadx** [dmulloy2/ProtocolLib#368]
Debug paste link: https://pastebin.com/XQaKJjqa

Description and relevant errors: Basically I was casually strolling around, I don't think this error is to do with any other plugin but it gives me a java exception error when I join.

**Comment by LordChaos88** [comment]
I have the exact problem as yours. My ProtocolLib is on 4.3.0 version, using Java 8 and my minecraft server is on Spigotmc-1.12-R0.1. I contacted Support Team under Minecraft-Hosting.Pro and they said it is an issue with ProtocolLib. Can anyone help us as well?

**Comment by dmulloy2** [comment]
I'll look into this, but in the meantime 4.2.1 should work just fine
