### ISSUE TITLE
Error on join

### ISSUE THREAD

**Issue by DuckCraftPvP** [dmulloy2/ProtocolLib#369]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version  - Check
- [x] This isn't an issue caused by another plugin  - Check
- [x] You've checked for duplicate issues - Check

Debug paste link:
https://hastebin.com/okicoyefuy.md
Description and relevant errors:
spams console when someone joins server

**Comment by MiniDigger** [comment]
thats an issue caused by one of your plugins, not protocollib:
 at me.leontss1.bsa.Main$7.onPacketSending(Main.java:487)

**Comment by DuckCraftPvP** [comment]
protocol lib causes it.

**Comment by DuckCraftPvP** [comment]
that bsa plugin i uninstalled over a week ago. and that error is from today.

**Comment by MiniDigger** [comment]
If that error is there then the plugin is still there too.
So either the plugin is still there or your log is old.

**Comment by dmulloy2** [comment]
This issue is caused by whatever bsa is, not ProtocolLib.
