### ISSUE TITLE
1.7 Users crashing

### ISSUE THREAD

**Issue by S0LD** [dmulloy2/ProtocolLib#370]
http://prntscr.com/frpiu9

idk why this keeps happening but when 1.7 users try to join the server it crashes them.
do you know how to fix it

**Comment by MiniDigger** [comment]
please don't just delete the issue template, it contains info we need to be able to help you.
whats your protocollib version?
what do you see in your servers console? 
can you provide the full client error (its in your client logs, you can enable them in the launcher)? 
please provide the output of /protocol dump (use pastebin or something similar)
