### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by Darko266** [dmulloy2/ProtocolLib#374]
Hello,

My server is crashing because i joined the server.

https://pastebin.com/BzqtY2ca

When i join :
DarkOakHD lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer

My protocollib version is the newest (from spigot)
I use java 8 (the newest build)
Spigot-1.8.8 with 9 plugins if you want to hear them, please let me know

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).
