### ISSUE TITLE
NbtFactory#fromItemTag always modifies the itemStack provided

### ISSUE THREAD

**Issue by ricardomanuelfalcao** [dmulloy2/ProtocolLib#376]
I don't know if there is another method, but NbtFactory#fromItemTag creates a new nbtfactory is no one is found, which modifies the itemStack in the arguments and consequently modifies a lot of my stuff.

**Comment by dmulloy2** [comment]
What exactly does it modify?

**Comment by ricardomanuelfalcao** [comment]
After fetching the nbt tag, if it does not exist it creates an empty one to the provided itemstack.

**Comment by ricardomanuelfalcao** [comment]
I am using it to read nbt not writing actually, and if I check if a piece of dirt in the inventory has nbt it adds an empty tag, and because the client does not receive an update packet it becomes a ghost item. I don't want it to get a new nbt tag, just return null if does not exist

**Comment by dmulloy2** [comment]
Ghost item? Is that something that happens with vanilla or something custom you're doing?

**Comment by ricardomanuelfalcao** [comment]
For example on player interact event i check if the item in hand has a nbt tag. If it doesnt the api automatically attaches a new one to the item, making it desynced with the client

**Comment by Dimatert9** [comment]
you can try my class to fix this issue 
https://github.com/Dimatert9/ItemFixer/blob/master/src/ru/leymooo/fixer/utils/MiniNbtFactory.java

**Comment by Dimatert9** [comment]
@dmulloy2 After NbtFactory#fromItemTag items become unstackable with others item. (Items that wasnt modiefed with NbtFactory#fromItemTag)
Maybe return null and dont write '{tag: null}' to ItemStack? https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/wrappers/nbt/NbtFactory.java#L166
