### ISSUE TITLE
Issue happens upon startup and join

### ISSUE THREAD

**Issue by ICEconchy** [dmulloy2/ProtocolLib#377]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
https://pastebin.com/iU1iS0aU
Description and relevant errors:
Only happens when trying to join and disconnects all clients upon joining

**Comment by dmulloy2** [comment]
So this happens on a standard, double clicked the startup script run? You aren't using plugin (re)loaders or anything?

**Comment by ICEconchy** [comment]
I am using mcss but I don't think that does anything different.
mcss: https://www.mcserversoft.com
