### ISSUE TITLE
An exceptionCaught() event was fired

### ISSUE THREAD

**Issue by gacus007** [dmulloy2/ProtocolLib#38]
HI ,J've problem with :
 An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. java.nio.channels.ClosedChannelException

Server sometimes turn off after 1h -2 h working ,ram and %cpu increase to 90%. (Ram 60GB,CPU 8 cores)

My version protocol lib : 3.4.0, spigot 1.7.10

**Comment by dmulloy2** [comment]
Are you using the protocol hack or regular 1.7.10?

**Comment by gacus007** [comment]
J'm using protocol lib from dev bukkit .org and spigot 1.7.10 build 1604

**Comment by dmulloy2** [comment]
Sorry, but we can no longer support ProtocolLib 3.4.0 and 1.7.10 due to changes in Netty and Guava packages.

**Comment by gacus007** [comment]
Thx,do you know good ver spigot and protocollib.

**Comment by dmulloy2** [comment]
"Good" versions would be Spigot 1.8 and ProtocolLib 3.6.3

**Comment by TiREX69** [comment]
i preffer mc 1.7 and i have same bug.
