### ISSUE TITLE
Error in ProtcolLib

### ISSUE THREAD

**Issue by serguna99** [dmulloy2/ProtocolLib#381]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
https://pastebin.com/jhHvJwgJ
Make sure you've done the following:
- [x] You're using the latest build for your server version
I left the latest version of the protocol and right now put a higher one and issued such an error
- [x] This isn't an issue caused by another plugin
No
- [x] You've checked for duplicate issues
No

Debug paste link:

Description and relevant errors:

**Comment by dmulloy2** [comment]
Not sure how this is ProtocolLib
