### ISSUE TITLE
Unhandled exception occured in onPacketReceiving and InventoryClickEvent not fired

### ISSUE THREAD

**Issue by KyuuKun** [dmulloy2/ProtocolLib#382]
When i click with the right button of the mouse on a fake mob i get this error (This not happens with left button)

[21:05:48 ERROR]: [KSkillful] Unhandled exception occured in onPacketReceiving(PacketEvent) for KSkillful
net.minecraft.server.v1_11_R1.CancelledPacketHandleException
[21:05:48 ERROR]: Parameters:
  net.minecraft.server.v1_11_R1.PacketPlayInUseEntity@12e42f4[
    a=0
    action=INTERACT
    c=<null>
    d=MAIN_HAND
  ]

When i click it opens an inventory but the InventoryClickEvent is not fired, when i open the inventory with other way it works. How can i fix this two erros?

Sorry for any dummy error, I started in protocollib recently.

**Comment by dmulloy2** [comment]
How are you spawning the fake mob?

**Comment by KyuuKun** [comment]
`public void onJoin(PlayerJoinEvent e)
	{
		Player p = e.getPlayer();	
		
		File f = new File(plugin.getDataFolder(), "skillful.yml");
		
		YamlConfiguration config = YamlConfiguration.loadConfiguration(f);
		
		if(config.getInt("villager.y") > 0)
		{
			
			Location loc = new Location(Bukkit.getServer().getWorld(config.getString("villager.world")), (double) config.getInt("villager.x") + 0.5, config.getInt("villager.y"),
					(double) config.getInt("villager.z") + 0.5);
			
			WrapperPlayServerSpawnEntityLiving spawn = new WrapperPlayServerSpawnEntityLiving();
			spawn.setType(EntityType.VILLAGER);
			spawn.setX(loc.getX());
			spawn.setY(loc.getY());
			spawn.setZ(loc.getZ());	
			
			WrappedDataWatcher value = new WrappedDataWatcher();
			
			Serializer stringSerializer = Registry.get(String.class);
			Serializer boolSerializer = Registry.get(Boolean.class);
			Serializer intSerializer = Registry.get(Integer.class);
					
			value.setObject(new WrappedDataWatcher.WrappedDataWatcherObject(3, boolSerializer), true);
			value.setObject(new WrappedDataWatcher.WrappedDataWatcherObject(2, stringSerializer), Skillful.nserv + ChatColor.YELLOW + "George");
			value.setObject(new WrappedDataWatcher.WrappedDataWatcherObject(13, intSerializer), 1);
			
			spawn.setMetadata(value);
			
			spawn.sendPacket(p);
			
			int id = spawn.getHandle().getIntegers().read(0);
			
			VillagerInventory inv = plugin.getVillagerInventory();
			
			plugin.getProtocolManager().addPacketListener(new PacketAdapter(plugin, ListenerPriority.HIGH, PacketType.Play.Client.USE_ENTITY) {
				
				@Override
				public void onPacketReceiving(PacketEvent e) {
					if(e.getPacketType() == PacketType.Play.Client.USE_ENTITY)
					{
						if(e.getPacket().getIntegers().read(0) == id)
						{
							p.openInventory(inv.startInventory(p));
						}
					}
				}
				
			});
			
		}		
	}`

**Comment by KyuuKun** [comment]
`public Inventory startInventory(Player p)
	{
		Inventory inv = Bukkit.getServer().createInventory(p, 9, Skillful.nserv + ChatColor.GOLD + "George");		
		File player = new File(plugin.getDataFolder(), "players");
		
		File pf = new File(player, p.getName() + ".yml");
		YamlConfiguration config = YamlConfiguration.loadConfiguration(pf);		
		
		ItemStack coins = new ItemBuilder(Items.coins.clone()).addLore(ChatColor.AQUA + String.valueOf(config.getInt("money")) + " PH").construct();
		
		inv.setItem(3, Items.phshop);
		inv.setItem(4, coins);
		inv.setItem(5, Items.shop);
		
		return inv;
	}`

The code of inventory's creation
