### ISSUE TITLE
Protocollib doesn't support reload.

### ISSUE THREAD

**Issue by marcocorriero** [dmulloy2/ProtocolLib#383]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:

Description and relevant errors:

When protocollib gets reloaded, i try to re-enable it back with /plc and it self disables.

**Comment by dmulloy2** [comment]
> ProtocolLib doesn't support reload

And it won't any time soon

**Comment by marcocorriero** [comment]
Nevermind, it has been solved
