### ISSUE TITLE
Fix PlayServerWorldParticles

### ISSUE THREAD

**Issue by Scrayos** [dmulloy2/ProtocolLib#39]
I already contacted you about this in the SpigotThread, but wanted to bring it here, to make it easier to track for you. (http://www.spigotmc.org/threads/protocollib.36230/page-7#post-497661)

I am really in urge concerning this. I would really appreciate a quick-fix for this!

Thanks in Advance,
Scrayos

**Comment by Quicksteve** [comment]
See [here](http://dev.bukkit.org/bukkit-plugins/protocollib/tickets/263-sending-a-world-particles-packet/) for more information as well.

**Comment by Scrayos** [comment]
Yepp. But .. aadnk and LeoFSU wrote a Link to the same respository (the dmulloy2-PacketWrapper-Repo). And I use it, but there's a ToDo for the ParticleId :/
