### ISSUE TITLE
Sometimes started server under bungecord with protocollib become unreachable from network

### ISSUE THREAD

**Issue by xion87** [dmulloy2/ProtocolLib#392]
I noticed randomly, in the server where prottocolib i installed, on server start, bungee people are not able to connect in this server (i am using viaverson + 1.8.8),
There are no error, simple users will see the server offline, insted is online from console . happen randomly 1/500 times for me

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

**Comment by dmulloy2** [comment]
Do you get any errors?

**Comment by xion87** [comment]
No errors but I am sure that is a protocollib issue

**Comment by MiniDigger** [comment]
does it occur without protocollib? 
does it occur with protocollib and without viaversion?
does it occur with just protocollib?

**Comment by xion87** [comment]
does it occur without protocollib?
No, i got cases only in PROTOCOLIB servers, more often where there is the restart option after the match: at start i thinked was AAC (https://github.com/konsolas/AAC-Issues/issues/481) but it happened also in a game server with only protocolib and payload (with no anticheat)

does it occur with protocollib and without viaversion?
Never tried but viaversion server work fine  without protollib

does it occur with just protocollib?
Yes i am 100% sure

**Comment by xion87** [comment]
on bungee i got this 
NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by xion87** [comment]
On factions now i tried to join and it kick me, maybe is related
https://hastebin.com/gegayiteqi.md

**Comment by xion87** [comment]
any solutions?
