### ISSUE TITLE
Bytecode API contract broken with newer versions of ProtocolLib

### ISSUE THREAD

**Issue by geNAZt** [dmulloy2/ProtocolLib#394]
Hello,

i currently support a public plugin which depends on ProtocolLib. We compile it with 4.3.0 and now with the new versions the bytecode for the getGenericType() API changed. This commit, https://github.com/dmulloy2/ProtocolLib/commit/9e5bdf41240b8b6e6f579a90e52fe56a68f40509, changes the signature of the method from com/comphenix/protocol/reflect/EquivalentConverter.getGeneric to com/comphenix/protocol/reflect/GenericConverter resulting in a NoSuchMethodFoundError when executing the plugin build against 4.3.0 on latest development builds.

**Comment by dmulloy2** [comment]
Is this only an issue with plugins that used that method, or does it happen with other plugins as well?

**Comment by Janmm14** [comment]
It will happen with all plugins which are not recompiled and use that method or other methods which changed similar to that method.
Providing support for ProtocolLib 4.3.0 and 4.4.0 together would require some type of dirty hack or reflection.

What could be done is adding the method back in EquivalentConverter which just delegates it to GenericConverter.

**Comment by geNAZt** [comment]
Its only a issue with plugins that use the method since Java does only check for Signatures when using the Class/Method from it.

**Comment by dmulloy2** [comment]
Alright so this was actually an unnecessary change, I had planned to do stuff with functional programming, but I don't think I ended up needing to change what I did. Looks to work just fine reverting, so I'll do that. Sorry for the late response, starting college is _hectic_

**Comment by geNAZt** [comment]
The issue is not fully solved. https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java#L651 has the same issue. Old signature was com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter; new Signature is com.comphenix.protocol.wrappers.EnumWrappers.getGenericConverter(Ljava/lang/Class;Ljava/lang/Class;)Lcom/comphenix/protocol/reflect/EquivalentConverter

**Comment by dmulloy2** [comment]
In that case it was a necessary change, but what's the usecase for that method that isn't covered by [PacketContainer#getEnumModifier](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L996)?

**Comment by konsolas** [comment]
In my case, it was decoding the PlayerTeleportFlag enum inside PacketPlayerServerPosition:
```
public enum PlayerTeleportFlag {
   X, Y, Z, Y_ROT, X_ROT
}

// ...

packetContainer.getModifier().withType(
                Set.class,
                BukkitConverters.getSetConverter(FLAGS_CLASS, EnumWrappers
                        .getGenericConverter(PlayerTeleportFlag.class)));
```

Do you have a suggestion for this which works across multiple versions of ProtocolLib?

**Comment by Janmm14** [comment]
PacketWrapper also does it exactly like that: https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerPosition.java#L151

**Comment by Cryptite** [comment]
Any updates on this? Couple plugins (mine included) are waiting on this to resolve so that they (and our dependencies on them) can update to latest PL.

**Comment by Janmm14** [comment]
@dmulloy2
