### ISSUE TITLE
Error with Viaversion and BungeeCord

### ISSUE THREAD

**Issue by Pokemonplatin** [dmulloy2/ProtocolLib#395]
Looks like there is a problem with protocollib viaversion and BungeeCord

Every client with minecraft version 1.9+ will crash uppon serverjoin
http://i.imgur.com/qDsqlel.png

The error thrown by the Bungee server
https://pastebin.com/nx1P1pfM

The error only occurres when you register a listener for Mapchunk packets, you dont need to modify them
Mapchunkbulk packets work fine, even modifying them.

Server version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by Pokemonplatin** [comment]
https://pastebin.com/g1Z6sWLm
here is the dump

**Comment by dmulloy2** [comment]
Try using ProtocolLib 3.6.5: https://www.spigotmc.org/resources/protocollib.1997/download?version=69182
