### ISSUE TITLE
issues with commands/Plib not loading

### ISSUE THREAD

**Issue by beautifulpoison** [dmulloy2/ProtocolLib#397]
Tried to put in a new jar to see if my copy was just damaged and this happend
https://pastebin.com/46E5i3pt

Everytime players or console run a command it also comes us with large Warns
https://hastebin.com/emifayocin.vbs

**Comment by MiniDigger** [comment]
Please don't copy log out of multicrap, it skips lines. Use the latest.log file in your logs dir.
Can you try reproducing without ViaVersion?

**Comment by dmulloy2** [comment]
Based on what little I can gather from that error log, this is an issue with ViaVersion.
