### ISSUE TITLE
Server Crash. An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:

### ISSUE THREAD

**Issue by Norinoi** [dmulloy2/ProtocolLib#398]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link: https://pastebin.com/c8WNaDL2

Description and relevant errors: It seems like this only happens when I add ProtocolLib, which I was adding specifically for AAC. The server gets thrown into a limbo after a bit of error spam, so players are still on the server, but new players cannot join.
https://pastebin.com/DU3FwthL
https://pastebin.com/1YgDeXn0

**Comment by dmulloy2** [comment]
Did you reload your server?

**Comment by Norinoi** [comment]
If by that you mean restart the server, yes. After restarting it goes okay a for a while, there are still errors in console, but players can join. After a bit of time has passed it goes back into that stage of the server looking like it's offline so new people can't connect, but people already in the server are fine.

**Comment by Kritex** [comment]
I am not sure about this, but my server is dealing with the same situation. People with (or modded) hacked client are sending huge packets or something and crashing or kicking out players. Common client names are Eazy, and Liquid. My server version is 1.8.8 paperspigot, and using latest protocolib version.

**Comment by dmulloy2** [comment]
Does it only happen with large packets on 1.8?
