### ISSUE TITLE
cannot load protocolib

### ISSUE THREAD

**Issue by pablodrake** [dmulloy2/ProtocolLib#401]
Stack Trace:
24.08 20:26:05 [Server] INFO java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
24.08 20:26:05 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:245)
24.08 20:26:05 [Server] INFO at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)

**Comment by dmulloy2** [comment]
Please stick to the issue template. It contains information that is very helpful in getting your problem resolved.
