### ISSUE TITLE
Failed to login: Access Token can not be null or empty

### ISSUE THREAD

**Issue by Niketion** [dmulloy2/ProtocolLib#402]
Description and relevant errors:
How I change message "Failed to login: Access Token can not be null or empty"?

I tried with:
 - Packets.Client.JOIN
 - Packets.Client.JOIN_START
 - Packets.Client.KICK_DISCONNECT
 and 
 - Packets.Server.JOIN
 - Packets.Server.JOIN_START
 - Packets.Server.KICK_DISCONNECT

**Comment by dmulloy2** [comment]
Your issue is likely that you're using the deprecated Packets class. Try using PacketType.
