### ISSUE TITLE
WrappedChatComponent class initializer error

### ISSUE THREAD

**Issue by Juzz0r** [dmulloy2/ProtocolLib#403]
The error can be seen here: https://pastebin.com/cuaFKQey. I'm using ProtocolLib 4.3.0 with Minecraft 
git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT).

It seems that the field "gson" in ChatSerializer class is actually named "a". It can be seen from the code that the server is running http://i.imgur.com/4lbfoHO.png.

ProtocolLib dump file https://pastebin.com/PJ5jhsCa

**Comment by dmulloy2** [comment]
Shouldn't matter what the field is, though the issue here is likely that it's using the wrong package (for whatever reason gson was a craftbukkit lib in a weird package then got removed, complicating things like this)

**Comment by Rexcantor** [comment]
+1

Please fix it ASAP.
It said it couldn't find some class on `com.google.gson`, so I checked the server JAR and it didn't contain it. I added it to my plugin, so it could run, but now it throws that error and doesn't work.

If it helps, it happens in this line of my code:
`WrappedChatComponent msg = packet.getPacket().getChatComponents().read(0);`
where `packet` is a `PacketEvent`
