### ISSUE TITLE
Error spamming java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float

### ISSUE THREAD

**Issue by bukkit188** [dmulloy2/ProtocolLib#404]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version Yes
- [x] This isn't an issue caused by another plugin Yes
- [x] You've checked for duplicate issues Yes
- [x] You didn't use `/reload` Yes

Debug paste link:https://pastebin.com/4iBzqAmC

Description and relevant errors:
It throw me an error and slow my server horriblely when i flying arround
I checked for duplicate issues and i found one, but no comment or answer
Running Spigot 1.10.2 lastest version
ProtocolLib lastest too

**Comment by dmulloy2** [comment]
Issue's with whatever plugin this is: ````at me.leontss1.bsa.Main$7.onPacketSending(Main.java:487)````

**Comment by bukkit188** [comment]
Thanks alot, i deleted my anti cheat plugins and that seem fix the problem!
