### ISSUE TITLE
Maven repository does not include old versions

### ISSUE THREAD

**Issue by Janmm14** [dmulloy2/ProtocolLib#405]
Maven repository does not include old versions like 3.6.5 or 4.2.0

This makes rebuilding of old projects a little harder because you need to update the pom.

Edit: Same issue for old PacketWrapper builds - you can't just change the version there higher at all.

**Comment by dmulloy2** [comment]
Yeah maven repositories are tricky. What happened there was that my old repository failed and the artifacts got deleted along with it. Fixing it would involve cloning old trees on GitHub and deploying, which I don't really have the time for right now
