### ISSUE TITLE
Potentially deleted Player Object on teleport

### ISSUE THREAD

**Issue by Cryptite** [dmulloy2/ProtocolLib#408]
Running PaperSpigot b1199, 1.12.1, **but using ProtocolLib b343**

Debug paste link:
https://www.dropbox.com/s/46j52evahxz2bvc/dump-2017-09-05_14.40.42.txt?dl=0

Description and relevant errors:
Happens on a vanilla teleport: https://hastebin.com/nariwozabe.vbs

Disregard the teleportAsync method name from TheArtifact (my plugin), that method is the following:

```
    public void teleportAsync(Player player, Location to, Consumer<Player> done) {
        if (player == null) return;

        player.teleport(to);

        if (done != null)
            done.accept(player);

//        to.getWorld().getChunkAtAsync(to, (c) -> {
//            if (player != null) {
//                player.teleport(to);
//                if (done != null) {
//                    done.accept(player);
//                }
//            }
//        });
    }
```

**Comment by dmulloy2** [comment]
Accessing the Bukkit API asynchronously is dangerous, mostly for reasons like this

**Comment by Cryptite** [comment]
The method was unfortunately called Async, but wasn't doing any async things. Looks like the bug was the result of https://www.spigotmc.org/resources/combattagplus.4775/ which spawns a duplicate player NPC and I believe that was what was causing explosions. Closing for now.
