### ISSUE TITLE
Fix entityHider

### ISSUE THREAD

**Issue by Lightoner** [dmulloy2/ProtocolLib#41]
When I hide a projectile for a player, the player who can't see the projectile can collide with the projectile.

**Comment by dmulloy2** [comment]
What method are you using to hide projectiles?

**Comment by Lightoner** [comment]
entityHider.hideEntity(observer, entity);

**Comment by Lightoner** [comment]
From https://gist.github.com/aadnk/5871793

**Comment by dmulloy2** [comment]
It looks like it isn't handling the COMBAT_EVENT, you should add it here: https://gist.github.com/aadnk/5871793#file-entityhider-java-L38

**Comment by Lightoner** [comment]
It doesn't work.

**Comment by dmulloy2** [comment]
"It doesn't work" doesn't help me.

**Comment by Lightoner** [comment]
I had the packet but the player who can't see the projectile can block the projectile.

**Comment by dmulloy2** [comment]
You could try adding UPDATE_ENTITY_NBT as well

**Comment by Lightoner** [comment]
But with COMBAT_EVENT we don't know how the player is enter in combat :
We can't get the projectile which hit the player ?

**Comment by Lightoner** [comment]
Maybe it's impossible with ProtocolLib ?

**Comment by dmulloy2** [comment]
It should be, but if I remember correctly, COMBAT_EVENT handles the entities involved differently than other Entity-related events. I can look into a solution when I have more time.

**Comment by dmulloy2** [comment]
Try this one out: https://gist.github.com/dmulloy2/5526f5bf906c064c255e

**Comment by dmulloy2** [comment]
Any more information on this?

**Comment by Lightoner** [comment]
It doesn't work, I think it impossible with packets.
