### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by Taahbelle** [dmulloy2/ProtocolLib#411]
When i put the Plugin on my server and reload it, then if a player joins the server there is an error:
ExceptionConnecting:NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

Console:
https://pastebin.com/cTAcGjqq

Can anyone pelase help me? :)

**Comment by MiniDigger** [comment]
don't reload the server, only do full restarts please.
