### ISSUE TITLE
Error filtering reports

### ISSUE THREAD

**Issue by ALYHFYAN** [dmulloy2/ProtocolLib#412]
Hey,

Hope all is well. I have this error message on console. Thought i would bring it up. Thank you! 
Server version: Spigot 1.12
ProtocolLib version: 4.3.0 

https://pastebin.com/18GshVKn

**Comment by games647** [comment]
Remove the injection method value so it looks like the default:

https://github.com/dmulloy2/ProtocolLib/blob/01b68cf8e5a5cf22cd178735d6879f17a054602e/modules/ProtocolLib/src/main/resources/config.yml#L19

**Comment by ALYHFYAN** [comment]
It works, thank you! :)
