### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thorngard** [dmulloy2/ProtocolLib#415]
Hi, i have this problem..

https://pastebin.com/3Ta7bv2u

thanks for help

**Comment by dmulloy2** [comment]
I can't make heads or tails of that error log? What are you using to format them??

**Comment by thorngard** [comment]
20:32:20 CONSOLE: ERROR]: Could not pass event PlayerQuitEvent to ProtocolLib v4.3.0
20:32:20 CONSOLE: Source) [?:1.8.0_45]
20:32:20 CONSOLE: Method) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 CONSOLE: java.lang.IllegalArgumentException: 'PROTOCOL' is already in use
20:32:20 CONSOLE: Method) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 CONSOLE: Source) ~[?:1.8.0_45]
20:32:20 Dieu]Thorngard: se deconnecte
20:32:20 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0xf743db2e, /79.87.119.39:5313 => /87.98.251.160:29765]
20:32:20 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:21 CONSOLE: Source) [?:1.8.0_45]
20:32:21 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:21 CONSOLE: Source) [?:1.8.0_45]
20:32:21 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0x7e8ded10, /79.87.119.39:5314 => /87.98.251.160:29765]
20:32:21 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:21 CONSOLE: Source) [?:1.8.0_45]
20:32:21 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:22 CONSOLE: Source) [?:1.8.0_45]
20:32:22 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0x0252dbe1, /79.87.119.39:5315 => /87.98.251.160:29765]
20:32:22 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:22 CONSOLE: Source) [?:1.8.0_45]
20:32:22 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:22 CONSOLE: Source) [?:1.8.0_45]
20:32:24 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0xa0544927, /79.87.119.39:5316 => /87.98.251.160:29765]
20:32:24 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:24 CONSOLE: Source) [?:1.8.0_45]
20:32:24 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:24 CONSOLE: Source) [?:1.8.0_45]
20:32:25 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0x2d55b66d, /79.87.119.39:5317 => /87.98.251.160:29765]
20:32:25 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:26 CONSOLE: Source) [?:1.8.0_45]
20:32:26 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:26 CONSOLE: Source) [?:1.8.0_45]
20:32:26 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0x7da10a97, /79.87.119.39:5318 => /87.98.251.160:29765]
20:32:26 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:32:26 CONSOLE: Source) [?:1.8.0_45]
20:32:26 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:32:26 CONSOLE: Source) [?:1.8.0_45]
20:35:16 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0x2832ed92, /79.94.106.237:52888 => /87.98.251.160:29765]
20:35:16 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:35:16 CONSOLE: Source) [?:1.8.0_45]
20:35:16 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:35:17 CONSOLE: Source) [?:1.8.0_45]
20:41:03 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0xd67ce1e6, /79.87.119.39:5536 => /87.98.251.160:29765]
20:41:03 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:41:03 CONSOLE: Source) [?:1.8.0_45]
20:41:03 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:41:03 CONSOLE: Source) [?:1.8.0_45]
20:41:03 CONSOLE: WARN]: Failed to initialize a channel. Closing: [id: 0xc55db027, /79.87.119.39:5537 => /87.98.251.160:29765]
20:41:03 CONSOLE: not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
20:41:04 CONSOLE: Source) [?:1.8.0_45]
20:41:04 CONSOLE: WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
20:41:04 CONSOLE: Source) [?:1.8.0_45]

**Comment by MiniDigger** [comment]
Please copy the log out of your log file, not out of your control panel. The log is useless.

**Comment by dmulloy2** [comment]
My guess is that you reloaded and it predictably broke everything. Don't reload.
