### ISSUE TITLE
build389 - INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by ArtNRG** [dmulloy2/ProtocolLib#416]
Console error log: https://pastebin.com/vH6MjE5F
Debug paste link: https://pastebin.com/nX53zw6c

**Comment by dmulloy2** [comment]
How often do you get this error?

**Comment by ArtNRG** [comment]
@dmulloy2 just once

**Comment by dmulloy2** [comment]
So it hasn't reappeared?

**Comment by ArtNRG** [comment]
It's appeared few times.

**Comment by ArtNRG** [comment]
Are you need more error logs of theese error?
