### ISSUE TITLE
glowstone

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [dmulloy2/ProtocolLib#418]
this is a support issue with a server type: 
please could you add support for glowstone some how i think they support this kind of thing its just the methods are different but ahhhhh once you add this i think that platform would expand very fast as it will expand plugin support

many thanks either way

MrGamerz

**Comment by MiniDigger** [comment]
dupe of #308

**Comment by dmulloy2** [comment]
To provide a status update: there was a fork created, but there doesn't appear to be any public work done yet
