### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by DoNotSpamPls** [dmulloy2/ProtocolLib#422]
Java 9 has been released for a while now, and while not pushed to consumers yet, it will be soon enough.

**Comment by games647** [comment]
Shouldn't it already work? Do you have any issues with it? It works for me without any issues, but **it's only used for a test server.**

**Comment by MiniDigger** [comment]
I don't see a point as minecraft doesn't support java 9 yet. java 9 is a big release and it caused issues everywhere, its unlikely that minecraft will update to 9 any time soon.
