### ISSUE TITLE
ProtocolLib error when starting the server

### ISSUE THREAD

**Issue by BlackPhoeniix** [dmulloy2/ProtocolLib#427]
Debug paste link:
https://pastebin.com/jwAg78Hp

Description and relevant errors:

I tried several versions of ProtocolLib (4.3.0 and 4.4.0) and I still have the same error. The server runs under PaperSpigot 1.12 (Build 1169)

**Comment by minecraftxguys** [comment]
Same problem here

**Comment by BlackPhoeniix** [comment]
I finally found it was due to an incompatibility with another plugin (MineWeb)
