### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Wolfiediamond** [dmulloy2/ProtocolLib#429]
Hello, my server won't start. I need ProtocolLib for several plugins to work, and I also need LiteBans. LiteBans works fine on its own, ProtocolLib works fine on its own... I just need them to both work at the same time.

Please help me find a fix!

Video showing the error: https://youtu.be/RonY0KTUZZ0

Server log: https://pastebin.com/iLkWCnYS

**Comment by lunarenzox** [comment]
i have the same problem !

**Comment by lunarenzox** [comment]
i also need help plss guys need help

**Comment by dmulloy2** [comment]
Update to 4.3.0 or 4.4.0.
