### ISSUE TITLE
Error on PacketPlayOutNamedEntitySpawn

### ISSUE THREAD

**Issue by minoneer** [dmulloy2/ProtocolLib#43]
Hey,

we are currently experiencing some errors with the 1.8 spigot and ProtocolLib.

I've done some testing and it appears to always be related to showing/hiding players from others - be it by means of the new game mode 3 or a vanish plugin.

Stacktrace of first the plugin and then the gamemode:
http://pastebin.com/5yTAs8tP

Current versions:
spigot: CraftBukkit version git-Spigot-d0d1d87-bc03b6f (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
ProtocolLib: 3.6.3-SNAPSHOT Build#77

**Comment by dmulloy2** [comment]
TagAPI is completely broken with 1.8. You should remove it.

**Comment by minoneer** [comment]
Thanks for the Help - that fixed it.
