### ISSUE TITLE
NoSuchMethod

### ISSUE THREAD

**Issue by ArceusMaster0493** [dmulloy2/ProtocolLib#433]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://hastebin.com/uxacobizic.txt

Description and relevant errors:
Plugin throws `NoSuchMethod` when calling `getBukkitItemStack` method.
error: https://hastebin.com/olerecohun.txt

**Comment by dmulloy2** [comment]
AsgardAscension needs to be updated

**Comment by ArceusMaster0493** [comment]
Bug repro only on versions later than 4.1.0. Are you sure that it is not the later versions of ProtocolLib causing the error?
