### ISSUE TITLE
Could not initialize class WrappedChatComponent

### ISSUE THREAD

**Issue by dadus33** [dmulloy2/ProtocolLib#435]
Hello!
You might remember me from previous issues with ProtocolLib. I'm the developer of ChatItem, and from time to time there is some user reporting issues with ancient minecraft versions. In this case, it's about 1.8 R1 and I'm confident it's a ProtocolLib related issue, although I can't really pinpoint what is wrong, as for some reason the line numbers in the stack trace don't seem to match those in the source file here on GitHub. However I believe you will be able to trace the cause, so here's the stacktrace, exactly as linked to me: https://pastebin.com/vjuSnVK6 
The issue concerning my plugin and the ProtocolLib error that I believe caused it starts on line 470 in the paste. As you can see, there's a bunch of stack traces further down for every chat packet sent, so it must be a ProtocolLib issue.
I hope you will be able to sort it out once again. Thank you!

**Comment by dmulloy2** [comment]
Try one of the development builds. IIRC this error was fixed in one of them

**Comment by dadus33** [comment]
It might have been that. To be honest, I didn't try it myself but he said he downloaded it from the spigot page, so that might explain it not being the very latest one.
