### ISSUE TITLE
licensing - packaging with other plugins?

### ISSUE THREAD

**Issue by smmmadden** [dmulloy2/ProtocolLib#436]
Do you allow developers to package (include) ProtocolLIb with their plugins when they make it a hard dependency?  Is there a page that they should refer to when doing so?  I'm not doing it, but I have become aware that someone else has.

Thanks,
Steve

**Comment by MiniDigger** [comment]
If you redistribute it you need to be compatible with the GPL iirc.
Generell it's a idiotic idea to package it into your plugin, many ppl will already have it installed or use another versions so it's really not worth the extra file size.
If you want to automatically install it, the best way is to just download it from the ci or spigot directly.

**Comment by smmmadden** [comment]
thanks, that's what I thought as well. :-)
