### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by Adrawyn** [dmulloy2/ProtocolLib#440]
Debug paste link:

tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/PluginV from class com.comphenix.protocol.ProtocolLib initializing ProtocolLib v4.3.0 (Is it up to date?)
java.lang.IllegalAccessError: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/PluginV from class com.comphenix.protocol.ProtocolLib

Description and relevant errors:

Hello, I have this error when my server starts, in TacoSpigot 1.12.2 it's same in spigot 1.12.2:

**Comment by dmulloy2** [comment]
Try a development build: http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Adrawyn** [comment]
I have the same in PaperSpigot 1.8. 

Please, i really need help because i have a lot of plugins using ProtocolLib.

**Comment by dmulloy2** [comment]
Did you try a development version of ProtocolLib?

**Comment by dmulloy2** [comment]
bump
