### ISSUE TITLE
Exception when trying to use the itemstack serializer on 1_8_R3

### ISSUE THREAD

**Issue by MrCreeperkopf** [dmulloy2/ProtocolLib#444]
Codeline: https://hastebin.com/fosumamufo.java

Debug paste link: https://hastebin.com/vomexoxade.rb

Description and relevant errors: https://hastebin.com/acovadavoy.md

Error occurs btw also on 4.3.0

**Comment by dmulloy2** [comment]
Yeah so the serializers literally don't exist in 1.8

**Comment by MrCreeperkopf** [comment]
That's really helpful... not... It would be nice if you could say how I serialize an itemstack instead of saying that there are no serializers in 1.8. Top support...

**Comment by games647** [comment]
@MrCreeperkopf Do you already tried `.setObject(int, Object)` so in this case `.setObject(6, itemStack)` for 1.8 servers. As far as I know Minecraft's internal code will make class type check.

**Comment by MrCreeperkopf** [comment]
Yes I tried. Nothing happened.
