### ISSUE TITLE
If you send multiple team packets at once it crashes the client.

### ISSUE THREAD

**Issue by dniym** [dmulloy2/ProtocolLib#445]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x ] You're using the latest build for your server version
- [ x] This isn't an issue caused by another plugin
- [ x] You've checked for duplicate issues
- [ x] You didn't use `/reload`

Debug paste link:
No Console Errors just disconnects the client.
Description and relevant errors:

If you attempt to send multiple "team" packets to a player it crashes the client.

https://hastebin.com/yuwuwixara.cs    the following code which attempts to put players on different teams with different colors will crash when a new player / entity is added into the mix.

If all players/entities share a common team/color the code works fine.
https://hastebin.com/bosudobufu.cpp

NOTE:   I have found that if you send another team packet BEFORE the removeTeam method is run it will also crash the client.

**Comment by MiniDigger** [comment]
How is this an protocol lib issue? Debug the client crash log and try to figure out why it crashes on the data you send it.
