### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Zefferis** [dmulloy2/ProtocolLib#446]
Debug paste link:
https://pastebin.com/Ld9pWJeq

Description and relevant errors:
While going through the Server Log as players mentioned that lag was occuring, I stumbled upon this error being thrown, I was informed that this is an error thrown because of ProtocolLib

Console Error Throw:
https://pastebin.com/P9Ay9SpS

**Comment by dmulloy2** [comment]
my guess would be a client sending bad packets. not sure what could/should be done on PL's end other than suppressing the error
