### ISSUE TITLE
Dont load ProtocolLib

### ISSUE THREAD

**Issue by SantaGitHub** [dmulloy2/ProtocolLib#447]
https://pastebin.com/F1KfeWgQ
I'm writing a new server core (Bukkit + Forge). Tried to put your plugin, but it crashes

**Comment by SantaGitHub** [comment]
https://pastebin.com/xA4NLmeA
Crash in ProtocolLib 4.1

**Comment by MiniDigger** [comment]
You could try version 4.3 from the CI. But generally, when you modified anything about how Minecraft handles packets, there is really not much protocollib can do to get around the issues introduced by you.

**Comment by SantaGitHub** [comment]
https://hastebin.com/ariwayewel.swift
Crash in ProtocolLib 4.3

**Comment by dmulloy2** [comment]
ProtocolLib depends heavily on the standard NMS code. It's highly unlikely it'll work with a "new core"
