### ISSUE TITLE
 [Server thread/ERROR]: [ViaVersion]

### ISSUE THREAD

**Issue by Mel0w** [dmulloy2/ProtocolLib#448]
[Server thread/ERROR]: [ViaVersion]

ViaVersion is already loaded, we're going to kick all the players... because otherwise we'll crash because of ProtocolLib.

Helpme please

**Comment by MiniDigger** [comment]
Please provide a pastebin link with your server log.

**Comment by dmulloy2** [comment]
Any more information on this?

**Comment by Mel0w** [comment]
Basically when I do

/ reload

MineCraft Multiplayer Displays:

Can not connect to server

On the host: BoxToPlay in the health part of the server shows this:

[21:24:10] [Server thread / ERROR]: [ViaVersion] ViaVersion is already loaded, we're going to kick all players ... because otherwise we'll crash because of ProtocolLib.

In this pasteBin link I send you the / reload logs

https://pastebin.com/8n6Xq6Zs

Thank you for your help..

**Comment by MiniDigger** [comment]
The combination of via version and protocollib is incompatible with the reload command.
So don't use the reload command and instead properly restart your server.
