### ISSUE TITLE
Protocol Lib disconnecting players

### ISSUE THREAD

**Issue by timothykeyes** [dmulloy2/ProtocolLib#449]
I am using the latest version of paper spigot snapshot version 1.12.2 release 1337 and whenever i start the server me or other players will join the server run around for about 15-30 seconds and then be kicked due to keepalive timeout. I've experienced the issue myself the client screen freezes and java is not responding. But if i use plugman to disable protocol lib or load the server without it (i stopped then started it i did not use /reload) then players can play just fine. I am also using a resourcepack, i think that is the issue, as a plugin called nocheatplus uses protocol lib to check for extra packets to detect hackers before they start hacking(mostly for xray hackers using custom resourcepacks). But if you disable that in their config.yml then it doesn't disconnect anyone. Im not sure if this is an issue with protocol lib sending too many packets with custom resourcepacks or an issue with nocheatplus but if anyone else is having this issue its not protocol lib directly(you need protocollib for alot of plugins to work correctly) its a config.yml setting in nocheatplus. Im also going to post this issue over there.

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by timothykeyes** [comment]
https://pastebin.com/FQh9fWKJ

I apologize if this isn't a problem with protocol lib ive been working with nocheatplus and it seems like it is more likely to be their problem but here is the dump anyways.

**Comment by dmulloy2** [comment]
Keep alive timeout would definitely point to an issue on NCP's part. Bring this up with them.
