### ISSUE TITLE
ProtocolLib 4.3.0 crashing server :(

### ISSUE THREAD

**Issue by EthanTG** [dmulloy2/ProtocolLib#451]
Debug paste link: https://pastebin.com/QcYbS3XF
(edited because I added a few potentially relevant lines at the bottom lol)

Description and relevant errors: 
I joined the server and then the server just stopped responding. Nothing worked and then I was kicked for timing out about 1 minute later. 

ProtocolLib is 4.3.0, I downloaded from the Spigot "Download Now" button, if that's relevant.

I'm a good template follower :)

**Comment by MiniDigger** [comment]
Please don't copy paste log out of multicraft. It removes lines. Crap the cradhog from your file system.

**Comment by EthanTG** [comment]
@MiniDigger 

what does that mean in english :o

**Comment by MiniDigger** [comment]
Wtf did gboard do to that message, lol. The last sentence was meant to be: grab your crash log from the file system.

**Comment by SlimeDog** [comment]
Confefe!

**Comment by dmulloy2** [comment]
Any more information on this?

**Comment by EthanTG** [comment]
No, sorry ;(
