### ISSUE TITLE
Latest Development Build Console Error Spam

### ISSUE THREAD

**Issue by Reversiya** [dmulloy2/ProtocolLib#452]
I have a
> [17:29:37 INFO]: Glora lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
Error, I'm trying to track the cause of this, most likely something to do with ViaVersion and ViaRewind, disconnecting my server from the bungeecord, connecting to it on 1.7 + 1.12 and reconnecting it, however, this has not happened before, but now I am getting ProtocolLib Errors. These are the logs I am getting.

https://pastebin.com/uGVjJNdL

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by dmulloy2** [comment]
bump
