### ISSUE TITLE
Serverlisping

### ISSUE THREAD

**Issue by mormoon** [dmulloy2/ProtocolLib#453]
http://wiki.vg/Server_List_Ping

I'm not sure I'm knocking on the right door, but if not I hope you may point me to the right direction. I'll try my best to explain the issue. 

I'm using a standalone server running on spigot (not older than a few weeks at most) with the latest build of protocolLib and PremiumVanish. Since I did a drop in replacement to paper-spigot, I noticed that the vanisched players are not entirely hidden anymore. They show up, when hovering over the playerlist. (And it is causing problems on my website, because I use an API to fetch the players.)

![image](https://user-images.githubusercontent.com/7835585/37864326-2bc6e2c2-2f6d-11e8-881b-6ccaf88cc8f1.png)

The user "dutcholdskool" is in fact hidden. The number of players is indeed the "correct" number, that is totalplayers - vanished players. 

After some more digging I found out that Running PaperSpigot-1.12-b1157, works, whilst running PaperSpigot-1.12-b1159 failes. I've tested this on a fresh install. I think this has something to do with commit; https://ci.destroystokyo.com/job/Paper/1158/changes

After some [chat](https://www.spigotmc.org/threads/premiumvanish-stay-hidden-bungee-support-paid.102401/page-55#post-2939014) with the author of PremiumVanish he stated that he could probably fix this, but the best place to fix this would be ProtocolLib or Paper. 

I hope you can shed some light on this, because at this moment, I can't fully understand why that particular commit on paper was done in the first place. And why it isn't working. Thank you for your time.

**Comment by MiniDigger** [comment]
paper provides an api to allow changing the player list, plugins should use that instead of hacking into the protocol directly.
you are also 200 builds behind on paper, does this still occur on the latest version?

**Comment by mormoon** [comment]
Yes, I'm actually using build 1350. Sorry I wasn't clear on that. I'll search for the API documentation, tnx.

**Comment by Minecrell** [comment]
Looks more like https://github.com/PaperMC/Paper/issues/884, fixed in Paper 1368+.

**Comment by mormoon** [comment]
Wow, that was....unexpected. It seems that fixes my error, sweet.
