### ISSUE TITLE
Chunk mapping handled incorrectly?

### ISSUE THREAD

**Issue by SlimeDog** [dmulloy2/ProtocolLib#456]
Spigot 1.12.2
ProtocolLib 4.4.0-bb390
Wormholes 2.4.3p

In addition to portal transportation, [Wormholes](https://www.spigotmc.org/resources/wormholes-portals-you-can-see-through.43188/) projects views of blocks and entities at the "other end" through a pair of portals. The portals may be in different Multiverse worlds. With the configuration above, blocks are not projected through the portals, but entities are. With ProtocolLib 4.3.0 blocks are projected, but only because of the following.

A Wormholes dev claims that ProtocolLib does not properly manage chunk mapping. He worked around it for ProtocolLib 4.3.0, and will probably do so again once ProtocolLib 4.4.0 is formally released. I asked him to post this ticket, but he declined. He says:
> ProtocolLib as i have found out actually has a lot of incorrect wrappers (according to wiki vg) and i know wikivg is correct because following that works fine.
> Wormholes Remaps 4 packets to actually fix them so those packets can be used without either failing or crashing clients
> Because of protocollibs incorrect wrappers 4.4.0 has additional changes, wormholes cant fix 4.4.0 if it can only fix 4.3.0
> Long story short, dont use protocollib for future plugins, it isnt accurate according to the games protocol

and again
> I already explained why it doesnt work
> technically 4.3 doesnt work either
> i just spent the time to fix all of the incorrect protocol wrappers in it to make wormholes work.

I am posting in hopes that you will investigate and decide if there is an issue to be addressed (or not). I certainly don't want to get into the middle of a finger-pointing match. I'm not sure that there is anything more I can contribute.

Please accept my apologies if this is viewed as impolitic; that is not my intent. I thought it important to get the issue registered.

**Comment by SlimeDog** [comment]
Same with Wormholes 2.4.4p

**Comment by dmulloy2** [comment]
Instead of complaining about it without specifics, maybe he could bring the issue up here

**Comment by SlimeDog** [comment]
He declines to do so. :(

**Comment by dmulloy2** [comment]
Then I'm sorry but there's not much I can do to help

**Comment by SlimeDog** [comment]
I'm sorry too. I was hoping the ^^^ might be sufficient to point you in the right direction. Arrogance is it's own reward, I guess.

**Comment by dmulloy2** [comment]
I would need to know which wrappers are actually broken to fix them. I'll do some general tests this weekend before releasing 4.4.0 though

**Comment by SlimeDog** [comment]
I will try to get him to respond.
