### ISSUE TITLE
Ghost players in tab.

### ISSUE THREAD

**Issue by fred112f** [dmulloy2/ProtocolLib#459]
Description and relevant errors:
 As seen in the picture below, players that are not online (offline players) are shown in the tab. Only non-op people can see this. 

https://gyazo.com/918fac005bb28770d7b740713a53fa8a

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by fred112f** [comment]
https://pastebin.com/qKyJTeL2

**Comment by dmulloy2** [comment]
This is caused by super vanish. If there's an issue ProtocolLib side, have the author report it here.
