### ISSUE TITLE
Provide a list of permissions

### ISSUE THREAD

**Issue by Dan9er** [dmulloy2/ProtocolLib#463]
So I'm using LuckPerms and I need a list of the permission nodes ProtocolLib uses and what each of them does. Can you add it to the wiki?

**Comment by MiniDigger** [comment]
See here https://github.com/dmulloy2/ProtocolLib/blob/master/modules/ProtocolLib/src/main/resources/plugin.yml
There is nothing you should give to your users. You can give protocol.* to devs or admins.
