### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by crizip** [dmulloy2/ProtocolLib#466]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [V] You're using the latest build for your server version
- [V] This isn't an issue caused by another plugin
- [V] You've checked for duplicate issues
- [V] You didn't use `/reload`

Debug paste :

 https://pastebin.com/C1GA2CjT

**Comment by MiniDigger** [comment]
Whatever server software you are using seems to be incompatible with protocollib.
Protocollib doesn't seem to like forge.
