### ISSUE TITLE
Question about StructureModifier

### ISSUE THREAD

**Issue by ItsHarry** [dmulloy2/ProtocolLib#47]
I have a question about getSpecificModifier(UUID.class) using the 1.7/1.8 version of ProtocolLib. I don't know whether this is specific to the 1.7/1.8 version I'm using, but whenever I do the following:

```java
ProtocolManager.createPacket(PacketType.Play.Server.NAMED_ENTITY_SPAWN).getSpecificModifier(UUID.class).write(0, player.getUUID());
```

I get the error:
```java
com.comphenix.protocol.reflect.FieldAccessException: Field index must be within 0 - count at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:300) ~[ProtocolLib-Spigot-3.6.0-SNAPSHOT.jar:?]
```

Clearly this means that StructureModifier.data is empty for some reason. Any suggestion how to fix this?

**Comment by dmulloy2** [comment]
Are you using the protocol hack or the official 1.8?

**Comment by ItsHarry** [comment]
I am using the protocol hack

**Comment by ItsHarry** [comment]
Is the error specific to the protocol hack version I'm using? If so, is there any way I can fix it?

**Comment by dmulloy2** [comment]
The error here is that there isn't a field with the type UUID in the named entity spawn packet.

The fields can be found here: https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/PacketPlayOutNamedEntitySpawn.java

**Comment by ItsHarry** [comment]
According to wiki.vg though, 1.8 clients need a UUID for that packet. Since I'm using the protocol hack, how do I send UUID?

**Comment by dmulloy2** [comment]
I believe the UUID is stored in the GameProfile variable in the packet class.

**Comment by ItsHarry** [comment]
Yes, I get that, but in 1.8 it was changed that PacketPlayOutNamedEntitySpawn requires a UUID instead of a GameProfile.

When I send this packet with GameProfile instead of UUID, the spawned player is invisible to 1.8 clients. It's only visible to 1.7 clients

**Comment by dmulloy2** [comment]
The protocol hack is still technically 1.7.  The only fields you can modify are the ones that exist in the class.
