### ISSUE TITLE
NPE on USE_ENTITY Interact

### ISSUE THREAD

**Issue by jonahseguin** [dmulloy2/ProtocolLib#470]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/X3U4Z5Vt

Description and relevant errors:

The error is caused by the USE_ENTITY packet.  It only happens when the EntityUseAction is INTERACT (no error is fired with attack).  Caused when right clicking any entity.

Running ProtocolLib v3.7.0 (& same version for API in my plugin) w/ Spigot Version (Paper) 1.7.10
'git-PaperSpigot-cb7702a (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)'

The packet is `PacketType.Play.Client.USE_ENTITY`

Source code that causes the error:

```
final Player player = event.getPlayer();
        if (manager.isSniffing(player, getSniffType())) {
            // final PapayaProfile profile = Papaya.getInstance().getProfileCache().get(player);
            final TickManager tM = Papaya.getInstance().getTickManager();
            final StructureModifier<EnumWrappers.EntityUseAction> actions = event.getPacket().getEntityUseActions();
            if (actions.size() == 1) {
                final String action = actions.read(0).toString();
                final int entityID = event.getPacket().getIntegers().readSafely(0);

                final String msg = PapayaLang.SNIFF_SERVERBOUND_USE_ENTITY.format(tM.getTotalTick(), tM.getRelativeTick(), player.getName(), entityID, action);
                manager.sniffMessage(msg);
            }
        }

```

If I catch the error and suppress it, it causes the packet to be cancelled

If you need any more information let me know.  This is a breaking error for my project.

**Comment by dmulloy2** [comment]
The packet that is sent has a null field: `action=<null>`. What I would do is add a null check, something to the effect of `if (event.getPacket().getModifier().readSafely(1) != null)`

**Comment by jonahseguin** [comment]
@dmulloy2 Thanks, I will try that.
I also found that this error occurs only on 1.8 clients (server being 1.7.10 supporting 1.8 clients)
On 1.7.10 clients this error does not occur.

**Comment by dmulloy2** [comment]
getModifier accesses all objects in the packet. So it should be index 1.

**Comment by jonahseguin** [comment]
Fixed my issue.  Thank you
