### ISSUE TITLE
Maven repository not resolving

### ISSUE THREAD

**Issue by dextonanderson** [dmulloy2/ProtocolLib#472]
When using the instructions in the readme, the maven repo does not properly resolve.

` Failed to read artifact descriptor for com.comphenix.protocol:ProtocolLib-API:jar:${minorVersion}: Could not transfer artifact com.comphenix.protocol:ProtocolLib-API:pom:${minorVersion} from/to dmulloy2-repo (http://repo.dmulloy2.net/content/groups/public/): Failed to transfer file: http://repo.dmulloy2.net/content/groups/public/com/comphenix/protocol/ProtocolLib-API/$%7BminorVersion%7D/ProtocolLib-API-$%7BminorVersion%7D.pom. Return code is: 400 , ReasonPhrase:Invalid repository path.`

My pom.xml:
https://github.com/Ruinscraft/CHIP/blob/master/pom.xml

**Comment by dmulloy2** [comment]
Try using 4.4.0

**Comment by dextonanderson** [comment]
Same result with 4.4.0

**Comment by dmulloy2** [comment]
It's definitely there: http://repo.dmulloy2.net/nexus/#browse/search=keyword%3Dprotocollib:c60bc6b9612f47d352464aaa20101261

**Comment by dextonanderson** [comment]
What repo url should I be using? `http://repo.dmulloy2.net/content/groups/public/` always returns an error.

**Comment by dextonanderson** [comment]
Also, FYI, this repo url has worked before in the past.

**Comment by MiniDigger** [comment]
The repo url is http://repo.dmulloy2.net/nexus/repository/public/

**Comment by dextonanderson** [comment]
Having issues with `http://repo.dmulloy2.net/nexus/repository/public/` as well. Same issue as before. Also, when loading it in a browser:

`This maven2 group repository is not directly browseable at this URL.`

**Comment by dextonanderson** [comment]
My apologies, I was using the legacy ProtocolLib artifact and not ProtocolLib-API. The documentation works fine.
