### ISSUE TITLE
protocollib doesnt let players join

### ISSUE THREAD

**Issue by UnlimitedNinjas** [dmulloy2/ProtocolLib#475]
protocolLibs doesnt let players join, im 100% sure its protocolLibs. I need this plugin for AAC please fix heres console error when player tries to join:
https://pastebin.com/d9e9BmTi

**Comment by MiniDigger** [comment]
What makes you think that this is a protocol lib issue? 
Anyways, you should enable the debug log level so we can see the full error

**Comment by UnlimitedNinjas** [comment]
I removed the plugin because no one can join, also as you wrote in the error it says your package.

**Comment by UnlimitedNinjas** [comment]
hello?

**Comment by dmulloy2** [comment]
> Anyways, you should enable the debug log level so we can see the full error

**Comment by UnlimitedNinjas** [comment]
I cant play on the server with the plugin, thats why its removed. So i cant enable it

**Comment by MiniDigger** [comment]
we can't help you without the log. you need to readd the plugin, enable the debug logging with this log4j config:
https://hasteb.in/acitefik.xml
(enable it using this command line parameter, put it before -jar paper.jar or whatever 
-Dlog4j.configurationFile=/path/to/log4jconfig.xml)

then provide us the full log so we can take a look an potentially solve the issue if there is smth to solve for protocollib.

**Comment by UnlimitedNinjas** [comment]
enabled now pls fix quicly cuz no one can join

**Comment by dmulloy2** [comment]
...it's not magic, you have to give us the debug log. also, the problem's likely on your end.

**Comment by xion87** [comment]
i got the same issue on 1.8.8 server wich AAC and "suggested" protocollib (dev 403) i upgraded it from a old version that i dont remember. Basically the player crashed, but the console work, and player still here (ghost) and no one can join the server and no errors, i shoul use protocollib dump when it happen?

**Comment by UnlimitedNinjas** [comment]
The server shutdown but i think the issue is still present, if anyone else has more info please do reply!
