### ISSUE TITLE
MAP_CHUNK doesn't include NBT data for spawn chunk on first spawn

### ISSUE THREAD

**Issue by dordsor21** [dmulloy2/ProtocolLib#476]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/Jr8jKfMY

No NBT data is sent with the chunk a player spawns into on first login after a server restart. If relogging (without restarting the server) then the NBT data is sent.

I cannot for the life of me work out why this is, and am unsure as to whether or not I am doing something wrong and/or need to listen for a different Packet.

Source: https://gitlab.com/dordsor21/AdvSwearBlock/blob/master/src/main/java/me/dordsor21/AdvSwearBlock/listener/PlayerSignPacketListener.java

**Comment by dmulloy2** [comment]
Looks like the server has the option of sending the data later with update tile entity: http://wiki.vg/Protocol#Chunk_Data

**Comment by dordsor21** [comment]
I assumed that this was the MAP_CHUNK packet. Is that not the case?

**Comment by dordsor21** [comment]
It seems that by registering the listener via TinyProtocol, I'm able to get the packet with the Sign NBT:

`    private TinyProtocol tinyProt;
    private Reflection.FieldAccessor<List<NBTTagCompound>> thing = Reflection.getField("{nms}.PacketPlayOutMapChunk", (Class) List.class, 0);

    public PlayerSignPacketListener(Main pl, ProtocolManager pM) {

        tinyProt = new TinyProtocol(pl) {

            @Override
            public Object onPacketOutAsync(Player p, Channel channel, Object packet) {
                if (thing.hasField(packet))
                    pl.getLogger().info(thing.get(packet).toString());
                return super.onPacketOutAsync(p, channel, packet);
            }

        };
    }`

**Comment by dordsor21** [comment]
I think the issue is that the first chunk (on the first login) is sent before a lot of permissions/metadata/etc has been applied to the player (i.e. before the actual login event is fired)
