### ISSUE TITLE
Error while adding ProtocolLib-API as a maven dependency

### ISSUE THREAD

**Issue by Nova41** [dmulloy2/ProtocolLib#477]
<version>4.4.0</version> should be <version>4.4.0-SNAPSHOT</version> in readme as there's no artifact with version 4.4.0 in the nexus repo...

**Comment by dmulloy2** [comment]
Okay. It's not really worth changing now though since 4.4.0 will be released soon(TM) with 1.13

**Comment by Nova41** [comment]
Thank you for your response!! :)
