### ISSUE TITLE
Error in console not working with any plugins.

### ISSUE THREAD

**Issue by CyrusMusic101** [dmulloy2/ProtocolLib#478]
https://pastebin.com/xHWFiKB3 (this is an example with uniquemotd)
https://pastebin.com/kvKSx1VV (this is an example with server list plus)

I'm using 1.8 spigot and I keep getting that error in console with every single frickin plugin that uses protocollib. I have tried different versions protocollib and the plugins. I get that same error in console for every single plugin that uses it just the plugin name is different.

**Comment by Tiippex** [comment]
Im using 1.12 and I have the same problem:
![](https://tiippex.de/pics/j/7zyo9qzpq6.png)

**Comment by dmulloy2** [comment]
IIRC this is an issue specific to earlier versions of 1.8, but not 1.8.9. Is there anything preventing you from upgrading to 1.8.9?
