### ISSUE TITLE
Add getHandle() for PacketEvent

### ISSUE THREAD

**Issue by NewbieOrange** [dmulloy2/ProtocolLib#48]
Add a getHandle method in packetevent that returns the NetworkManager object will be great. :)

**Comment by dmulloy2** [comment]
This isn't really possible, as there isn't always a network manager involved.  It wouldn't be terribly difficult to grab the network manager based on the player though.

**Comment by NewbieOrange** [comment]
But sometimes their isn't a player (status packets, for example).
