### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by FedericoGB25** [dmulloy2/ProtocolLib#480]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://pastebin.com/AkwjB16x

Description and relevant errors:

**Comment by dmulloy2** [comment]
Make sure you don't have duplicate jars. Maybe `ProtocolLib (1).jar` or something to that effect.

**Comment by FedericoGB25** [comment]
Hi, I don't have duplicated ProcolLib

**Comment by FedericoGB25** [comment]
Solved, my bad dx
Thanks
