### ISSUE TITLE
Unhandled exception occurred in onPacketSending (PacketEvent)

### ISSUE THREAD

**Issue by Tiippex** [dmulloy2/ProtocolLib#481]
Debug paste link:
https://hastebin.com/gaculuniho.java

Description and relevant errors:
![](https://tiippex.de/pics/j/7zyo9qzpq6.png)

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues #478 is the same exception but not the same error
- [X] You didn't use `/reload`

**Comment by dmulloy2** [comment]
Issue is with the GPS plugin, contact the author of it.
