### ISSUE TITLE
LinkageError

### ISSUE THREAD

**Issue by AlexDelpier02** [dmulloy2/ProtocolLib#482]
Debug paste link: https://hastebin.com/egagesevuq.java

Description and relevant errors: https://hastebin.com/mefapedupa.md

Plugin list available if needed

**Comment by dmulloy2** [comment]
Do you have duplicate plugin jars in your plugin folder?

**Comment by AlexDelpier02** [comment]
No, I found out that ProtocolSupportLegacySupport's BossBar module was the cause. I just recompiled it by removing bossbar support for < 1.9 versions and now it doesn't print anymore those errors.

**Comment by dmulloy2** [comment]
alright cool
