### ISSUE TITLE
MinecraftReflection.getMinecraftItemStack() returns null for CraftItemStacks with Material.AIR

### ISSUE THREAD

**Issue by Alvin-LB** [dmulloy2/ProtocolLib#483]
Make sure you've done the following:
- [x] You're using the latest build for your server version (PL 4.3.0)
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Description and relevant errors:

The [`MinecraftReflection.getMinecraftItemStack(ItemStack)`](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java#L1929) method returns null for CraftItemStacks with `Material.AIR`. Note that it only happens if the ItemStack is a CraftItemStack (IE it has come from an inventory or somewhere else in the minecraft internals), regular ItemStacks are not affected.

This is because the `BukkitUnwrapper#unwrapItem()` call on [line 1946](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java#L1946) fetches the `handle` field in the CraftItemStack, but this field is set to null if the material is `Material.AIR`.

This is the shortest way I could find to reproduce the problem:
```java
// This will print null, even though it shouldn't!
System.out.println(MinecraftReflection.getMinecraftItemStack(CraftItemStack.asCraftCopy(new ItemStack(Material.AIR))));
```

**Comment by MiniDigger** [comment]
Since you identified the cause of this issue already, would you be able to PR a fix? Should be as a easy as a simple null check.

**Comment by Alvin-LB** [comment]
Alright, just did.
