### ISSUE TITLE
PacketContainer.write() throwing errors

### ISSUE THREAD

**Issue by MuffinScript** [dmulloy2/ProtocolLib#49]
I've been using a class to force a sign gui to pop up for the player and record input. However, after the update to 1.8 this stopped working. I narrowed it down to writing integers to the BLOCK_CHANGE packet. I can create the packet and use getIntegers() but cannot perform .write() to that. I haven't tested much further so I don't know if it's limited to the BLOCK_CHANGE packet. I'm doing all this using PacketContainer.getIntegers().write(int, int);

**Comment by dmulloy2** [comment]
Id's were replaced by BlockData in 1.8.  There is a wrapper for BlockData in ProtocolLib, WrappedBlockData, which you can access with PacketContainer.getBlockData()

**Comment by MuffinScript** [comment]
Okay, that works, but what do I use to put a string array in a sign block? I'm using the UPDATE_SIGN packet and it won't let me write to getStringArrays(). Was that replaced too?

**Comment by dmulloy2** [comment]
In 1.8, sign lines were replaced by chat component arrays, which can be accessed via ````java PacketContainer.getChatComponentArrays()````

**Comment by MuffinScript** [comment]
Sorry for bothering you.. It's just a lot has changed since 1.7... Right now all of my packets are being created perfectly but it won't let me use the UPDATE_SIGN packet anymore. After sending the BLOCK_CHANGE packet to create a SIGN_POST block I send the UPDATE _SIGN packet and it responds by saying it cannot find a sign at the given location. The same logic worked before 1.8 so I can only assume this is another change I'm not aware of.
