### ISSUE TITLE
Offline Players in tab

### ISSUE THREAD

**Issue by fred112f** [dmulloy2/ProtocolLib#491]
Debug paste link:

https://pastebin.com/ZaJX4qu5

Description and relevant errors:

Players that are offline and been on the server are showing in the tab. Picture of that: https://gyazo.com/5511822b10f4d5667af4c7a5b82dd3d8

**Comment by dmulloy2** [comment]
That's odd. None of your installed plugins seem to modify the packet, and there isn't anything PL does itself. Maybe it's another plugin that uses another library?

**Comment by fred112f** [comment]
I tried removing protocollib and the offline players did not appear... Would a full plugin list help?

**Comment by fred112f** [comment]
Another thing I am wondering about is the following: with OP I am unable to view offline players like this. What perm is required to make everyone not see the offline players and would it give them perms they should not have?

**Comment by fred112f** [comment]
I have been waiting for a fix for this for like a half year. Please find the issue

**Comment by dmulloy2** [comment]
I don't know what to tell you. I sincerely doubt this is something on ProtocolLib's end, or it would have come up before. Seems to me like some other plugins aren't getting along somewhere
