### ISSUE TITLE
Protocolib instantly kicking players once they join

### ISSUE THREAD

**Issue by OmgItsNik** [dmulloy2/ProtocolLib#493]
Hello, I've recently went through this problem where protocolib would kick everyone giving them the error in the attached image
![screenshot_30](https://user-images.githubusercontent.com/35317103/42974158-c1da4422-8bbe-11e8-98fa-dd11fc33669e.png)

My version of protocolib is 4.3.0, the latest release in the spigot page, I've also tried to use the recommended dev build for 1.12.2 but still the same and after some time I decided to use the very latest dev build, the jenkins server was down. I wanted to report this and I will provide as much information as needed.
My spigot version is 1.12.2, I've tried to update it but still the same.
Also no error logs have been printed in the console but I can confirm 100% that this problem was coming from protocolib as when I unloaded it would let me join normally.

**Comment by Fejm** [comment]
Plugins list?

**Comment by OmgItsNik** [comment]
Nevermind, it was a plugin called EzProtector, it had a certain feature that made this to happen, thanks!
