### ISSUE TITLE
Cannot clone Optional.empty() - No cloner is suitable.

### ISSUE THREAD

**Issue by libraryaddict** [dmulloy2/ProtocolLib#498]
Debug paste link: https://pastebin.com/QYDjRhkQ

Description and relevant errors: Optional.empty() is unable to be cloned, this is attempting to deepClone a packet before having done any modifications.

**Comment by MrPowerGamerBR** [comment]
Can confirm, this also happens to me while deep cloning a entity metadata packet.

This issue didn't happen in 1.12.2.

Stacktrace: https://gist.github.com/MrPowerGamerBR/7209b2b24f538ab860822072af9a6a53
