### ISSUE TITLE
PacketType.Play.Server.BLOCK_CHANGE does not update the block

### ISSUE THREAD

**Issue by MuffinScript** [dmulloy2/ProtocolLib#50]
After setting the location of the packet with:
PacketContainer.getBlockPositionModifier().write(0, BlockPosition)
and setting the block type with:
PacketContainer.getBlockData().write(0, WrappedBlockData.createData(Material));
nothing happens. The packet is successfully sent however the block does not register a change. In game the block appears to be air and further sent packets cannot identify the block. For example a SIGN_UPDATE packet responds that it could not find a sign at the location.

**Comment by Rocknest** [comment]
This is works fine: .getBlockData().write(0, WrappedBlockData.createData(Material.WALL_SIGN));
