### ISSUE TITLE
Can't work on 1.10.2 version Bukkit+Forge server

### ISSUE THREAD

**Issue by Luohuayu** [dmulloy2/ProtocolLib#500]
Can't work on 1.10.2 version Bukkit+Forge server (https://github.com/Luohuayu/CatServer)

**Comment by MiniDigger** [comment]
Protocollib was build for craftbukkit based servers and as such will only run on craftbukkit based servers. Opening it up to mcp based servers would be a huge endeavour and I don't think that will happen any time soon.
