### ISSUE TITLE
PacketType.Play.Server.PLAYER_INFO

### ISSUE THREAD

**Issue by molor** [dmulloy2/ProtocolLib#503]
Is it possible to get the original version of PacketContainer? If there are several players on server, then when changing the data of this packet for the player event.getPlayer().getName().equals("Test"), all other players will be sent the same packet with same changes. How can I change the data for only one player or several, but send it to everyone else without changes?

**Comment by dmulloy2** [comment]
You can clone packets and set the one that will be sent if that's what you're after

**Comment by molor** [comment]
If I clone original packet and use event.setPacket() with it, then at next onPacketSending() call event.getPacket() will return the cloned packet..
