### ISSUE TITLE
Connection Issues 

### ISSUE THREAD

**Issue by Andrew909** [dmulloy2/ProtocolLib#505]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:

Description and relevant errors:
Hey there, we recently added ProtocolLib To our server, we require this plugin for a lot of our plugins to run smoothly, we had to remove our anti-cheat when we removed the plugin, once we add the plugin it becomes almost impossible to join and all our players including opped players find it impossible to join before saying disconnected, Console does not state an error message so I am lost, we have added and removed the plugin many times, I have disabled all plugins but it and it still makes it impossible to join if you can offer any help on this I would appreciate it, as we do need this plugin for a lot of ur plugins to work. Such as SuperVanish and HolographicDisplays 

Thanks

**Comment by dmulloy2** [comment]
Which anti cheat do you use?

**Comment by Andrew909** [comment]
Currently non we were using [https://www.spigotmc.org/resources/phoenix-anti-cheat.6207/](url)

The connection issues still happened after we removed the anti-cheat and tried again. 

All we get is Loading terrain then "Disconnected" but if we remove ProtocolLib it fixes the issue and people can re-connect without any issues.

**Comment by dmulloy2** [comment]
Can you run `/protocol dump` and paste it on pastebin?

**Comment by Andrew909** [comment]
https://prnt.sc/knzgim

The server just crashes over and over if I even add ProtocolLib, As you can see it suggests that it does not support 1.12.
