### ISSUE TITLE
ProtocolLib-API 4.3.0 is broken in the dmulloy2-repo

### ISSUE THREAD

**Issue by DmitryRendov** [dmulloy2/ProtocolLib#506]
it has version not set <version>${minorVersion}</version> and I'm getting:

`Could not resolve dependencies for project XXXX: Failed to collect dependencies at com.comphenix.protocol:ProtocolLib:jar:4.3.0 -> com.comphenix.protocol:ProtocolLib-API:jar:${minorVersion}: Failed to read artifact descriptor for com.comphenix.protocol:ProtocolLib-API:jar:${minorVersion}: Could not transfer artifact com.comphenix.protocol:ProtocolLib-API:pom:${minorVersion} from/to dmulloy2-repo (http://repo.dmulloy2.net/nexus/repository/public/): Failed to transfer file: http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib-API/$%7BminorVersion%7D/ProtocolLib-API-$%7BminorVersion%7D.pom. Return code is: 400 , ReasonPhrase:Invalid repository path. ->`

Downloaded here - http://repo.dmulloy2.net/nexus/repository/public/com/comphenix/protocol/ProtocolLib/4.3.0/ProtocolLib-4.3.0.jar

**Comment by osipxd** [comment]
Have same problem with v4.3.x, but v4.4.x resolved fine
