### ISSUE TITLE
UPDATE_SIGN packet does not recognize signs unless placed prior to the packet

### ISSUE THREAD

**Issue by MuffinScript** [dmulloy2/ProtocolLib#51]
When calling the PacketType.Play.Server.UPDATE_SIGN packet and assigning a location with:
PacketContainer.getBlockPositionModifier().write(0, BlockPosition);
and the text with:
PacketContainer.getChatComponentArrays().wirte(0, WrappedChatComponent[]);
I will receive a message stating that there was no sign at that location if the packet to change the block had been sent just prior to the sign update. I tested this by changing the block through basic bukkit functions also with Block.setType(); The sign update will only recognize the sign if it was placed significantly before the packet was sent. This was not the case in 1.7

**Comment by dmulloy2** [comment]
I can't vouch for this, but if this is an issue, it's a limitation with Minecraft itself, not ProtocolLib.
