### ISSUE TITLE
Cannot clone net.minecraft.server.ParticleType: No cloner is suitable.

### ISSUE THREAD

**Issue by libraryaddict** [dmulloy2/ProtocolLib#513]
Debug paste link: https://pastebin.com/j3gnmC1y

Description and relevant errors: Occurs when trying to deep clone a packet.

It's worth noting that it extends ParticleParam

**Comment by dmulloy2** [comment]
Should be fixed in latest dev build

**Comment by libraryaddict** [comment]
The cloner works for particles that don't require options, but ParticleParamBlock fails.

ParticleParamItem and ParticleParamRedstone were not tested, but should fail as well as they use the same field.

Caused by: java.lang.IllegalArgumentException: Cannot clone net.minecraft.server.v1_13_R2.Particle@586728e8 ( class net.minecraft.server.v1_13_R2.Particle): No cloner is suitable.

https://gist.githubusercontent.com/libraryaddict/9c496668c765cd5a56221bcb974df29f/raw/cf763c49210341ba23cbba7edd61539c4b966d87/2018-09-19_15-04-00.txt

**Comment by libraryaddict** [comment]
Fixed :)
