### ISSUE TITLE
ProtocolLib wont load!!

### ISSUE THREAD

**Issue by UncleM0** [dmulloy2/ProtocolLib#514]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
4.3.0

- [ ] This isn't an issue caused by another plugin
ProtocolLib wont load, and i have no idea. Not what i can see.

- [ ] You've checked for duplicate issues
no problem there.

- [ ] You didn't use `/reload`
Nope, Fresh restart.

Debug paste link:
https://pastebin.com/VU8Gs5Ag

Description and relevant errors:
Please help me, Allot of the plugins im running needs protocol lib, I haven o idea what to do.

**Comment by UncleM0** [comment]
Im sorry for the rush. It was another plugin that was making it not work.

**Comment by TimHarrio** [comment]
which plugin ?
