### ISSUE TITLE
WorldParticlesModule issues

### ISSUE THREAD

**Issue by cdmvirt** [dmulloy2/ProtocolLib#515]
Make sure you've done the following:
- [X ] You're using the latest build for your server version
- [X ] This isn't an issue caused by another plugin
- [ X] You've checked for duplicate issues
- [X ] You didn't use `/reload`

Debug paste link:

[PremiumVanish] The WorldParticlesModule does not work because of a currently unfixed error in ProtocolLib's 1.13 support (NPE in WORLD_PARTICLES/packet.getNewParticles().read(0)

**Comment by MiniDigger** [comment]
this report is useless.
please include: 
* the protocollib version
* the spigot version
* the code that throws the exception
* the exception
* a debug paste

**Comment by cdmvirt** [comment]
its the latest version of protocollibb spigot 1.13., the warning is posted above even if Protocollibb didn't throw any exception

**Comment by MiniDigger** [comment]
get the author of premium vanish to properly report bugs, else we can't do anything here...
