### ISSUE TITLE
Illegal State Exception on startup, related to modules

### ISSUE THREAD

**Issue by TimHarrio** [dmulloy2/ProtocolLib#518]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ x ] You're using the latest build for your server version
- [ x ] This isn't an issue caused by another plugin
- [ x ] You've checked for duplicate issues
- [ x ] You didn't use `/reload`

My logs:
https://pastebin.com/7zBNhA01

If I do /protocol dump:
https://pastebin.com/SS3EvMdb

Description and relevant errors:
I use the last version of PaperSpigot and this plugin doesn't work..
It blocks some of my plugin wich need ProtocolLib.
It is displayed as off in the /plugins.

**Comment by Andre601** [comment]
I can reproduce this issue on a 1.13.1 Spigot server (Build `git-Spigot-500ff5d-1cead62`)
On startup, this error here shows up: https://pastebin.com/ecTWzEBg

Here's a screenshot of this error, if that's easier:
![](https://i.imgur.com/NBAOTmZ.png)

**Additional info**:
I use the latest dev-build of ProtocolLib (Build [#415](http://ci.dmulloy2.net/job/ProtocolLib/415/)

**Comment by SevenX159** [comment]
It come from MineWebBridge, disble it and use RCON junction, and it will work =)

**Comment by Andre601** [comment]
> It come from MineWebBridge, disble it and use RCON junction, and it will work =)

Nope. There's no MineWebBridge plugin in my case.

**Comment by SevenX159** [comment]
So it's another plugins, try disabling there one by one and restarting each time so you will see wich one do that

**Comment by Andre601** [comment]
Most likely my own plugin, because I have a plugin using ProtocolLib...

**Comment by dmulloy2** [comment]
i think this is caused by naughty plugins, but i'm working on a protocollib-side fix in 4.5.x

**Comment by themeowest** [comment]
I get this error when starting up and it never ran before

https://pastebin.com/tSgef7Kg

im trying to run oreobfuscator
