### ISSUE TITLE
Can you help me with sending packets?

### ISSUE THREAD

**Issue by CodBreakr00** [dmulloy2/ProtocolLib#520]
Hello, I need help with packets, because I'm making a TrollPlugin and I want to create a TrollSkyChange, but I can't, I don't know why not, but before I could do it with NMS but now I can not and I want to learn to use the ProtocolLib API ... Well basically what I want is to change the color of a player's sky, I know that this is a GAME_STAT_CHANGE but I do not know how to change it

**Comment by dmulloy2** [comment]
Check wiki.vg for the packet, then take a look at the NMS source code (generated when spigot builds) for the appropriate fields. You could also use PacketWrapper, which will provide getters and setters for you

**Comment by CodBreakr00** [comment]
ok, thanks
