### ISSUE TITLE
ProtocolLib responds with "plugin reloaders aren't supported"-message, even if you start the server like normal

### ISSUE THREAD

**Issue by Andre601** [dmulloy2/ProtocolLib#524]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
Not available, due to ProtocolLib not being enabled.

Description and relevant errors:
When starting the server (Spigot 1.13.1 with API method 1.13.1-R0.1-SNAPSHOT), ProtocolLib gives the message, that plugin-reloaders aren't supported, even tho the server was started like normal without any reloads, nor restarts.

This issue *could* be related to #518 and #523 since it also produces an error on startup, that could cause this message.

Screenshot of the Message:
![image](https://user-images.githubusercontent.com/11576465/45628903-660fb900-ba95-11e8-9909-02772f03ce5e.png)

Textversion of it:
```
[16:05:01] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0-SNAPSHOT-b417
[16:05:01] [Server thread/ERROR]: ******************************************************
[16:05:01] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[16:05:01] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[16:05:01] [Server thread/ERROR]: ******************************************************
[16:05:01] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.4.0-SNAPSHOT-b417
```

**Comment by dmulloy2** [comment]
This _probably_ isn't related to those other issues. Do you maybe have multiple versions of ProtocolLib running? Not sure how else something like this could happen.

**Comment by dmulloy2** [comment]
Does the plugin include ProtocolLib inside of itself? Check for com/comphenix/protocol in your jar

**Comment by Andre601** [comment]
My plugin uses ProtocolLib as a dependencies.
I don't know what I have to change in my code, to actually fix this problem...
My code is [here](https://github.com/Andre601/PingNachricht) and I use methods of ProtocolLib [here](https://github.com/Andre601/PingNachricht/blob/master/src/main/java/com/andre601/pingnachricht/manager/HoverMessage.java) and [here](https://github.com/Andre601/PingNachricht/blob/master/src/main/java/com/andre601/pingnachricht/manager/PlayerCount.java)

**Comment by JarvisCraft** [comment]
@Andre601, add `<scope>provided</scope>` to your ProtocolLib-Api dependency. This is not ProtocolLib's issue but yours as your plugin is copying PLibs classes to its jar.

**Comment by Andre601** [comment]
> @Andre601, add <scope>provided</scope> to your ProtocolLib dependency. This is not ProtocolLib's issue but yours as your plugin is copying PLibs classes to its jar.

It was clear for me, that my plugin causes the issues since, when I remove it does ProtocolLib work like normal.
I will try what you suggest and will respond later.

**Comment by Andre601** [comment]
Looks like that finally fixed it. Thanks!

**Comment by Andre601** [comment]
ok so uhm......
I get this error here, when refreshing the serverlist to test the hovermessage:
https://hastebin.com/nokoliloxe.pl

As far as I understand it, should I override the onPacketSending?
This is the code for the hovermessage: https://hastebin.com/egufawagip.java
