### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by EmperorPvP** [dmulloy2/ProtocolLib#528]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._Error when loading plugin

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link: https://pastebin.com/7BVudjaQ

Description and relevant errors:

**Comment by BitCashMC** [comment]
I am having the exact same error.. Please Help!
