### ISSUE TITLE
Protocol libs error

### ISSUE THREAD

**Issue by Fluzzer** [dmulloy2/ProtocolLib#54]
Im using version 1.8 of spigot and i got lots of errors when i get in my server
http://pastebin.com/9vd3YA3a

**Comment by dmulloy2** [comment]
Those errors are from LibsDisguises, not ProtocolLib.  I believe there is an updated version available on the Spigot resource page.

**Comment by Fluzzer** [comment]
Can u send me the link plz?

**Comment by dmulloy2** [comment]
http://www.spigotmc.org/resources/libs-disguises.81/

**Comment by Fluzzer** [comment]
i download the recent one and still the same, i think i did, can u send me the jar download link plz

**Comment by dmulloy2** [comment]
The LibsDisguises version for 1.8 can be found on md_5's jenkins: http://ci.md-5.net/job/LibsDisguises/
