### ISSUE TITLE
Suggestion: integrate with Maven Central

### ISSUE THREAD

**Issue by JarvisCraft** [dmulloy2/ProtocolLib#540]
Deploying to Maven Central would have positive impact on this project as it would let it be added as a dependency without specifying dmulloy2-repo.
Also the TravisCI may be used instead / parallel with the current CI for Central deployment purposes.

**Comment by dmulloy2** [comment]
You can only deploy releases to maven central, which would mean bleeding edge API methods wouldn't be available. Now there's definitely an argument to be made that that's not necessarily a bad thing. As for travis I do use it to run the test suite, but I don't see how it would replace the Jenkins.

**Comment by JarvisCraft** [comment]
As for snapshot builds they will simply stay at [Sonatype's snapshot repo](https://oss.sonatype.org/content/repositories/snapshots) (which, of course, does not prohibit you from keeeping them in `dmullloy2-repo` too) which would be a nice place for bleeding edge APIs. Yet this might give positive affect on the whole development process forcing you to make a decision when to remove `-SNAPSHOT` and when to keep the version in beta.
As for Travis CI, it's just my personal opinion that it seems more clear for contributors when they see the whole Continuos Integration configuration keeping the whole project 100% OpenSource.

**Comment by JarvisCraft** [comment]
@dmulloy2, any updates on it? It still may be a positive feature for the API
