### ISSUE TITLE
Prevent asnyc api usage of non-asnyc-safe api

### ISSUE THREAD

**Issue by Janmm14** [dmulloy2/ProtocolLib#543]
Basically async usage of protocollib to to send packets is suspected by me and reflex developer to cause packets with zero length to be emitted sometimes(not even a packet id), causing disconnects when bungeecord sits inbetween.

**Comment by dmulloy2** [comment]
Do you have anything more specific than that?

**Comment by dmulloy2** [comment]
I have seen something similar come up when modifying server ping packets sync instead of async. If this is the same kind of thing, the listener just needs the async option set. I could also force that lib-side, but I'd need the specific packet type.

**Comment by PsychoLynx** [comment]
Hello @dmulloy2 - I have a server that currently has players disconnect randomly due to allegedly empty packets being sent to Bungee. I would be more than happy to try and debug what is causing this, but I'm not sure what kind of info you would need and how to track it. Cheers!

**Comment by Janmm14** [comment]
@dmulloy2 I'm really wondering what could be wrong if empty packets aka a single 0x00000000 being emitted occurr based on the listener being executed async or sync.
