### ISSUE TITLE
Startup Errors

### ISSUE THREAD

**Issue by BloodshotPico** [dmulloy2/ProtocolLib#544]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [Unsure] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [X] You didn't use `/reload`

Using this dev build: http://ci.dmulloy2.net/job/ProtocolLib/422/

Debug paste link:
  Console Spam:
      https://pastebin.com/PB9i76t6
   Dump Log:
      https://pastebin.com/uXkZD1bY

Description and relevant errors:

Errors loading upon the server, not sure if they're caused by other plugins, I have no idea what I'm looking at honestly I have too many errors spamming console and I can't see what is causing what right now, I'm just reporting what I'm seeing.

~Blood

**Comment by MiniDigger** [comment]
strange, I ran Protocollib under openjdk10/11/12 just fine

**Comment by BloodshotPico** [comment]
I don't believe I'm running Java 9
