### ISSUE TITLE
Protocollib error

### ISSUE THREAD

**Issue by pjindras** [dmulloy2/ProtocolLib#545]
Hello, i am using Orebfuscator3 lastest for version 1.8.8 and protocollib 4.4.0 (lastest) . 
I have these errors and i dont know how to fix it, can you help me please?

`21:28:00 [SEVERE] [Orebfuscator3] Unhandled exception occured in onPacketReceiving(PacketEvent) for Orebfuscator3
21:28:00 com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_8_R3.PacketPlayInBlockDig$EnumPlayerDigType exists in class PacketPlayInPositionLook.
21:28:00     at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.4.0-b421]
21:28:00     at main.java.com.lishid.orebfuscator.hook.ProtocolLibHook$2.onPacketReceiving(ProtocolLibHook.java:56) ~[Orebfuscator%20(2).jar:?]
21:28:00     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:509) [ProtocolLib.jar:4.4.0-b421]
21:28:00     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:00     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
21:28:01 [SEVERE] Parameters:
21:28:01   net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook@39bfe683[
21:28:01     x=8.5
21:28:01     y=65.0
21:28:01     z=8.5
21:28:01     yaw=-30.0
21:28:01     pitch=0.0
21:28:01     f=false
21:28:01     hasPos=true
21:28:01     hasLook=true
21:28:01   ]
21:28:01 [SEVERE] [Orebfuscator3] Unhandled exception occured in onPacketReceiving(PacketEvent) for Orebfuscator3
21:28:01 com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_8_R3.PacketPlayInBlockDig$EnumPlayerDigType exists in class PacketPlayInPositionLook.
21:28:01     at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.4.0-b421]
21:28:01     at main.java.com.lishid.orebfuscator.hook.ProtocolLibHook$2.onPacketReceiving(ProtocolLibHook.java:56) ~[Orebfuscator%20(2).jar:?]
21:28:01     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:509) [ProtocolLib.jar:4.4.0-b421]
21:28:01     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:01     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib.jar:4.4.0-b421]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
21:28:02     at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
21:28:02 [SEVERE] Parameters:
21:28:02   net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook@7e032430[
21:28:02     x=8.5
21:28:02     y=64.90199999809265
21:28:02     z=8.5
21:28:02     yaw=-60.0
21:28:02     pitch=0.0
21:28:02     f=false
21:28:02     hasPos=true
21:28:02     hasLook=true
21:28:02   ]`

Is there some way how to fix it or can you make support of your plugin for 1.8.8 spigot servers too?

Thanks :)

**Comment by dmulloy2** [comment]
```No field with type net.minecraft.server.v1_8_R3.PacketPlayInBlockDig$EnumPlayerDigType exists in class PacketPlayInPositionLook```

This is an issue with Orebfuscator's use of our API, there isn't really anything I can do about it
