### ISSUE TITLE
java.lang.IllegalArgumentException: No serializer found for Optional<class net.minecraft.server.v1_13_R2.ItemStack>

### ISSUE THREAD

**Issue by Ghost-chu** [dmulloy2/ProtocolLib#546]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://paste.ubuntu.com/p/c8HtgxtYjv/
Description and relevant errors:
java.lang.IllegalArgumentException: No serializer found for Optional<class net.minecraft.server.v1_13_R2.ItemStack>
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:966) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.getItemStackSerializer(WrappedDataWatcher.java:1057) ~[?:?]

**Comment by dmulloy2** [comment]
Can you provide the code you're using?
