### ISSUE TITLE
Error on player login

### ISSUE THREAD

**Issue by KleinDevDE** [dmulloy2/ProtocolLib#555]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version     --> at another test, with the same result
- [ ] This isn't an issue caused by another plugin     --> don't know
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link: https://pastebin.com/wZ05s2vA

Description and relevant errors: 
This message appears in the console, as well as with the admins inGame.
It appears from time to time when someone joins the server.
Tested with PaperMC 456 and the latest papermc version, same result.

Dump: https://pastebin.com/gmDeQuS5

**Comment by Vyrgax** [comment]
Try using java 8 - hotspot, I had a similar problem. Please make sure you make a back-up.
