### ISSUE TITLE
Issue with 1.13.2

### ISSUE THREAD

**Issue by GeekzGamingz** [dmulloy2/ProtocolLib#556]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version - Check
- [x] This isn't an issue caused by another plugin - Check
- [x] You've checked for duplicate issues - Check
- [x] You didn't use `/reload` - Check

Debug paste link:
https://pastebin.com/C1ZkZ8en

Description and relevant errors:
There seems to be an issue with ProtocolLib that prevents the current version of LibsDisguises from loading. Already brought this issue to LibsDisguises dev and pointed me in the direction of ProtocolLib.

**Comment by Vyrgax** [comment]
Try using java 8 - hotspot, I had the same problem with LibsDisguises.
