### ISSUE TITLE
PlayerJoinEvent Error

### ISSUE THREAD

**Issue by milothedalmador** [dmulloy2/ProtocolLib#558]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
![unknown](https://user-images.githubusercontent.com/46726096/51205868-c527f200-18fe-11e9-92ef-44f2c2585398.png)

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:

Description and relevant errors:
Errors coming up in the console (see image) for PlayerJoinEvent and PlayerLoginEvent - Uninstalled SuperVanish and Announcer plugins as they were chucking up errors too but still having errors from ProtocolLib. There are a few others on the spigot page having the same issue too. Thanks.

**Comment by milothedalmador** [comment]
![image](https://user-images.githubusercontent.com/46726096/51208311-3074c280-1905-11e9-803b-eb69327b0441.png)

Just tried powering on the server and same errors are occurring when player joins/leaves.

**Comment by Tezcati** [comment]
https://pastebin.com/7WhT4u30

I have this error when players join the server, and the minecraft version is 1.13.2 (spigot)

**Comment by milothedalmador** [comment]
> what a crappy server provider, lol. open your log file please and give use the proper server log of the error.
> 
> then also make sure you use '/protocol dump' and pastbin use the output so we can further look into your issue.
> 
> currently there is nothing we can do.

What a crappy human, to make assumptions. 
1. The server isn't yet open
2. The server owner is a friend of mine - he is in another part of the world and therefore went to bed, so I offered to try and find out what was happening (with my very limited knowledge of plugins, the console etc) and therefore, ended up here
3. If you have nothing helpful or constructive to say, move along.

**Comment by MiniDigger** [comment]
Not sure where I made assumptions, I was just commenting on the fact that whatever crappy web panel your hosting provider uses make a terrible job at displaying logs as it completely hid the error, making this report useless. All I then asked for was to fill out the issue template with the required info to help you, since you gave us nothing to work with.
But since I am such a crappy human you prolly don't want me to look into your issue.

**Comment by milothedalmador** [comment]
You were not very polite to begin with @MiniDigger - maybe you should take that into consideration when commenting on things, as not everyone is going to be as knowledgeable as yourself/developers etc. I apologise for calling you a crappy human, but I don't think your initial comment was helpful or very polite.

**Comment by milothedalmador** [comment]
@MiniDigger entirely my fault for misreading your comment - so I apologise. I'm not sure where to find that info in the console, as I mentioned before I was trying to help out a friend so I'm not great with the "behind the scenes" stuff. The plugin was uninstalled and reinstalled and the issue seems to have stopped - although I'm not sure whether that means anything was done on the plugin side of things, so if it was then thanks.

**Comment by TreeMC** [comment]
I'm not really sure where to put this. This ticket seems to be the same problem that I have and the template asks to check for duplicate issues. I hope this information will assist in finding the bug for the both of us. (sorry for reposting, I thought this may have been the wrong place to post this)

Debug paste link: https://pastebin.com/LDehUuf4

Description and relevant errors: 
The plugin was fine before but it randomly started behaving like this. Player join event error for protocollib while all the plugins dependent on protocollib have errors from temporary player handling. Libsdisguises also worked before this error started happening a day ago, but now it disables on start up.

Dump: https://pastebin.com/ixuqRxiC

**Comment by TeAm6AZLIK** [comment]
Got the same error, using paperspigiot 1.13.2 and ProtocolLib 4.4.0

**Comment by Pendragon1111** [comment]
Getting the same error on player's joining. 
https://pastebin.com/gMhtzFNS

Using version 4.4.0, spigot 1.13.2

This also occurs on player quit: https://pastebin.com/pFpjp035

**Comment by dmulloy2** [comment]
Use the latest dev build found here: http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
