### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by Skyfighter1** [dmulloy2/ProtocolLib#559]
Description and relevant errors:

16.01 17:25:43 [Disconnect] User _Supreme_Hero_ has disconnected, reason: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.12.11 at 00:53:05 MSK, buildhost: build.true-games.org, buildnumber: 324)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.protocol.utils.authlib.GameProfile(onlineMode: true, originalname: _Supreme_Hero_, originaluuid: d0718a75-4d66-4e92-b31f-f47914f143b4, name: _Supreme_Hero_, uuid: d0718a75-4d66-4e92-b31f-f47914f143b4, properties: {textures=[protocolsupport.api.utils.ProfileProperty(name: textures, value: eyJ0aW1lc3RhbXAiOjE1NDc2NTU2MTQ4MTcsInByb2ZpbGVJZCI6ImQwNzE4YTc1NGQ2NjRlOTJiMzFmZjQ3OTE0ZjE0M2I0IiwicHJvZmlsZU5hbWUiOiJfU3VwcmVtZV9IZXJvXyIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMzRhYTMwYmEwMTc1MDdlN2E0MDEzMTA1ZDBlM2Y3MTE5MTRmYWIwZjViN2ZkZDI0ZmIwMjRjNDM1OTdlYTgwIiwibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn19fX0=, signature: kkzybi3zSedaBs8SnYMwYTb6Hojbs1Ybm0098Yz0BVrSmXfK1YInjyJahjQwW26qpVmnBziGwIY7jr8RkdYUnrZaZk81k0XZM+1Dxyy6EKffw2U6AX8L9eJUG6baRVULzM6j72Gnl/dC+6BYXKs0t4ioOcJf4k4iChgrN0bfHMud0PA3nVCyUb1QGFy2Z2vXSevnaEVLYAvJUuKd9EzDObt1dMpG70twBy4EEVe8bXf4ybeAkg07vsHBCaQmsq/Rn5sKzSbD4ax5j4CT+v5CaqkcZYFppqWn3II1raCkrSi+Xpz0Do3Rkvyurc/apfRYbY3EBC/VzpMK8sgIWIOfR+1JKQpsp3V6Za2COhRhYxcnMaBhOTSJjmvQLPSt3IrcE3f6ZmnJIzFoMqpIe77Q3pMj6+/allCXFXyrSYs2ArBexdWUOpa1set4IyyAXdcO3TZJo5zicAgRl3RLUp5mzKcIEycovJk/90Ajah4sI8gxRtY2DwfsQOP18USCP3qZ2YdbzUWg3pXdO4ZM1MFfMNcIy/fEqTVh8EzocwQS9SIebqv+dbePjbR7yphdfks7BOVJr85hBXHn8neTRLKEHccUIRUCwG9gJ3b8QzYs9aS/bUdxgNMo20YhyYHthxiRJfhbbqLroTMw1zcyXbReFrSaHw1YgoZZYODhYf4ps78=)]}), player: CraftPlayer{name=_Supreme_Hero_}, address: /185.22.142.92:50219, rawaddress: /185.22.142.92:50219, version: MINECRAFT_1_12_2, metadata: {}))

**Comment by dmulloy2** [comment]
ProtocolLib != ProtocolSupport
