### ISSUE TITLE
Class Not Found Exception: net.minecraft.server.v1_8_R2.AttributeSnapshot

### ISSUE THREAD

**Issue by NavidK0** [dmulloy2/ProtocolLib#56]
AttributeSnapshot is no longer a class in Minecraft/Spigot 1.8.3, therefore PacketContainer.getAttributeCollectionModifier() no longer functions at all.

There doesn't appear to be any replacement for AttributeSnapshot, so I'm not quite sure what could replace it.

**Comment by Rocknest** [comment]
net.minecraft.server.PacketPlayOutUpdateAttributes.AttributeSnapshot

**Comment by dmulloy2** [comment]
This is an interesting issue with the 1.8.3 update, some classes were moved inside others. It's a relatively simple fix, but I don't know exactly which classes were moved.
