### ISSUE TITLE
Sudden PlayerJoinEvent bug

### ISSUE THREAD

**Issue by Vyrgax** [dmulloy2/ProtocolLib#563]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/vqXiXHgn

Description and relevant errors:
Used to work fine some time ago, as well as LibsDisguises, but not anymore.

**Comment by Samfrog** [comment]
I'm having an issue that might be the same as well
https://pastebin.com/ujXSBkpy

PlayerJoinEvent errors, and then I get a huge amount of errors from other plugins that use protocollib saying they cant pass things to it

**Comment by Samfrog** [comment]
Also just a warning rather than error, but "? protocollib" in console produced this:
https://pastebin.com/DU3WrjL4

**Comment by Samfrog** [comment]
So I have no idea why this worked, but this host allows you to switch java versions, and switching from Java8 openj9 to Java8 hotspot edition fixed the errors. @Vyrgax just pinging you so you can try this as well, might help you too since your error looked very similar to mine.

**Comment by Vyrgax** [comment]
Yes, that indeed did the trick! Thank for your fast reply and the fix, much appreciated. ;)
There are more people with this issue, I guess we should notify them as well. 
Thanks again!

**Comment by Samfrog** [comment]
You should probably keep this open though, shouldnt you? While it's true that random thing I tried seems to solve the issue, it seems to me like it's a bandaid/workaround. If we close this the devs probably won't see it and won't apply an actual fix, and as you say it's possible this is affecting many others. 

To clear up any potential misunderstanding, I'm just a random person who came here with the same issue and happened to find a way to fix it, but I don't believe an actual fix has been applied.

**Comment by krustymk** [comment]
https://pastebin.com/YiqPma7v
Same i think, if its not fixed why was this closed?
