### ISSUE TITLE
Player join serious issue

### ISSUE THREAD

**Issue by Sckaletz** [dmulloy2/ProtocolLib#564]
Debug paste link: https://pastebin.com/aSkWV0dS

Description and relevant errors: Sometimes when players joins the server it almost crashes due to this error. It creates terrible lag and is apparently associated with some memory problem. I even had to edit the "memory=" parameter in the log file to be able to paste the error. It had about 320.000 zeros in that line.

We're using the latest Spigot 1.13.2.

**Comment by Vyrgax** [comment]
Java version?

**Comment by Sckaletz** [comment]
![java](https://user-images.githubusercontent.com/6684408/51543561-1fc0d100-1e5e-11e9-9d19-4ebb4420f243.PNG)

**Comment by Sckaletz** [comment]
Still no solution to this? It still happens on all my servers.
