### ISSUE TITLE
WrappedDataWatcher crash

### ISSUE THREAD

**Issue by BestMark** [dmulloy2/ProtocolLib#566]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/Ba7ZG86t

Description and relevant errors: when I disguise into some mobs in LibsDisguises plugin I get the crash in my console connected with ProtocolLib.
Software: Paper 1.12.2, LibsDisguises 9.5.2 (latest for 1.12.2), ProtocolLib version: 4.4.0-b421.

**Comment by libraryaddict** [comment]
This is a Lib's Disguises bug, if you're using 9.5.2 the recommended build is ProtocolLib 4.3.0

https://www.spigotmc.org/resources/protocollib.1997/download?version=165553
