### ISSUE TITLE
Players kick when 2 players trying to be online at the same time.

### ISSUE THREAD

**Issue by maxlehot1234** [dmulloy2/ProtocolLib#568]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
https://hastebin.com/oqicayiruw.cs

Description and relevant errors:
If a player was online and a new player join the server, all players are kick. The server was still up and we can join it again, but crash if 2 players are online.

I also have latest paperspigot version: Paper-1.13.2-f238f3a-20190126-0011
Latest Protocolib: Build 425 

Thanks again for your help

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).
