### ISSUE TITLE
Error during the Loading of the plugin

### ISSUE THREAD

**Issue by LoceK** [dmulloy2/ProtocolLib#571]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

https://pastebin.com/rb1fAdAT

Description and relevant errors:

**Comment by dmulloy2** [comment]
Working on a fix for this in 4.5.0
