### ISSUE TITLE
PlayerJoin Error comes.

### ISSUE THREAD

**Issue by gaRt3n** [dmulloy2/ProtocolLib#575]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ X] You're using the latest build for your server version
- [ X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
https://paste.md-5.net/ludahozeqe.sql
Description and relevant errors:
Well it happens when someone joins the Server.

**Comment by dmulloy2** [comment]
Update to the latest dev build
