### ISSUE TITLE
Kettle Server Compatibility

### ISSUE THREAD

**Issue by razorrider7** [dmulloy2/ProtocolLib#576]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/vmjDUXxC

Description and relevant errors:
There is a new "Cauldron like" software that was just made public, which I have been waiting for for ages. [Kettle](https://github.com/KettleFoundation/Kettle) is for 1.12.2, but ProtocolLib isn't loading... I get these error messages when starting the server. Is there any chance ProtocolLib could be made compatible with Kettle? If there is nothing you can do, and it is on their end, then I'm sorry for wasting your time with this.

**Comment by MiniDigger** [comment]
if the creators of whatever kettle is feel like this is something they want, they should PR a solution to protocollib. protocollib itself only supports craftbukkit servers, not forge based servers (which kettle seems to be).

**Comment by razorrider7** [comment]
Kettle is a Forge AND Spigot server, much like cauldron, but with added compatibility between the two. I have gotten many other plugins working on it, but need ProtocolLib in order to run Hydra and Orebfuscator.

**Comment by MiniDigger** [comment]
it doesn't matter what apis it supports. protocollib only works with craftbukkit mappings, not the  mcp/forge mappings kettle uses. so unless the authors of kettle or somebody else looks into providing support for that you are out of luck.

**Comment by razorrider7** [comment]
Ok, thanks anyways... I remember there being a build that worked with cauldron for 1.7.10, but if you don’t think it’ll work, then I’ll ask the kettle devs when they have time. Thanks again!
