### ISSUE TITLE
JSON Reading

### ISSUE THREAD

**Issue by GamemodeSurvival** [dmulloy2/ProtocolLib#578]
{"extra":[{"text":"[translate]JOIN-MESSAGE[/translate]"}],"text":""}

How would I get [translate]JOIN-MESSAGE[/translate] from this json string above.

**Comment by MiniDigger** [comment]
you have some json object, you then get the extra element, which is an array of json objects, you then get the first element of that array, and the string you want is the text element of that element. 
any json parser will help you.

**Comment by GamemodeSurvival** [comment]
thanks
