### ISSUE TITLE
1.13.2 Trident > representing air cannot store NMS information

### ISSUE THREAD

**Issue by Lix3nn53** [dmulloy2/ProtocolLib#587]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/hE66tt1q

Description and relevant errors: 
this is my line which throws error: NbtCompound tag = (NbtCompound) NbtFactory.fromItemTag(MinecraftReflection.getBukkitItemStack(item));

When this "item"'s material is Trident (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#TRIDENT) I get this error. 

protocol-lib version: 4.4.0-b425
I made sure my item type is Trident and MinecraftReflection.getBukkitItemStack(item) returns Trident type item

**Comment by osipxd** [comment]
I have same problem. For some reason `stack.getType() == Material.AIR` is true when stack's material is Trident.
But when I've copied `NbtFactory.fromItemTag` to own class, problem disappear. Also problem disappear when I recompile ProtocolLib. So strange.
