### ISSUE TITLE
1.8.3 Update: Class Not Found

### ISSUE THREAD

**Issue by Cnly** [dmulloy2/ProtocolLib#59]
I've seen #55 before so this seems to be another class which was moved.

```
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.PlayerInfoData
```

**Comment by Rocknest** [comment]
It was moved to net.minecraft.server.PacketPlayOutPlayerInfo.PlayerInfoData

**Comment by Cnly** [comment]
@Rocknest 
Could you tell me how did you find that out?

**Comment by Rocknest** [comment]
@Cnly I used the source code of 1.8.3 to find this class.

**Comment by Cnly** [comment]
@Rocknest But I couldn't find that in Spigot-Server 1.8.3. Did you use code of Minecraft 1.8.3?

**Comment by Rocknest** [comment]
@Cnly Vanilla 1.8.3

**Comment by Cnly** [comment]
@Rocknest Okay, thanks. I'll try that later.
