### ISSUE TITLE
[IllegalAccessException] When using Advancement Packet Wrapper!

### ISSUE THREAD

**Issue by riflowth** [dmulloy2/ProtocolLib#593]
_Follow this template except for feature requests. Use Pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ /] You're using the latest build for your server version
- [ /] This isn't an issue caused by another plugin
- [ /] You've checked for duplicate issues
- [ /] You didn't use `/reload`

Debug paste link: https://pastebin.com/885bqi2E

Description and relevant errors: **First sorry for my bad English**. I try to use your packet wrapper (https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerAdvancements.java) but I get this stack trace error.

**Comment by riflowth** [comment]
And I try to read packet with your wrapper. I get it too (StackTrace: https://pastebin.com/Zu28H1QD)

**Comment by CommanderTvis** [comment]
I have this problem too!
https://gist.github.com/d24d4783c6405ee7692e7ecc7850645e

**Comment by LeonTheo02** [comment]
This issue is still happening to us aswell when we are trying to use the AdvancementPacketWrapper, exact same error. Any hopes for a fix? @dmulloy2
