### ISSUE TITLE
1.14 Entity Spawning

### ISSUE THREAD

**Issue by Ste3et** [dmulloy2/ProtocolLib#602]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: 
   ServerDebug: https://hastebin.com/ricidudiwa.log
   ClientDebug: https://hastebin.com/enuqogesic.rb

Description and relevant errors:
In the 1.14 the Client Crash after Entity Spawning nothing has been changeing about the spawning Packets https://wiki.vg/Entity_metadata#ArmorStand

**Comment by dmulloy2** [comment]
All metadata after index 6 was shifted by 1 since Mojang added pose to all of them. See here: https://wiki.vg/Pre-release_protocol#Entity_Metadata

**Comment by Ste3et** [comment]
Ok jesus i didn't see it i look on the main side of the EntityMetadata https://wiki.vg/Entity_metadata thank you

**Comment by Ste3et** [comment]
Thank you @dmulloy2  every thing works great :D

**Comment by MiniDigger** [comment]
@Ste3et just fyi, protocol changes for major versions live on the prerelease page until both the protocol and the implementation are considered stable.

**Comment by Ste3et** [comment]
Ah ok, thank you for the Information @MiniDigger 👍, 
I should have seen it myself, because there were no foxes 🤔 on the main side
