### ISSUE TITLE
Illegal reflective access with spigot 1.14

### ISSUE THREAD

**Issue by mirolm** [dmulloy2/ProtocolLib#603]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

``WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/home/ieti/minecraft/plugins/ProtocolLib.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
``

Description and relevant errors:

This warning appears with latest 4.5 snapshot from gradle jenkins.

**Comment by dmulloy2** [comment]
ProtocolLib currently does not support Java versions above Java 8 and won't until Mojang and Spigot decide to update.

**Comment by Tencryn** [comment]
Paper will be updating to Java 11 when MC 1.17 is released, and throws a fat warning if < 11. May be worth considering fixing this warning within the coming months.
