### ISSUE TITLE
ProtocolLib /Filter overrides my /Filter Toggle Plugin.

### ISSUE THREAD

**Issue by Jxpen** [dmulloy2/ProtocolLib#604]
Hey, so the ProtocolLib /Filter command over rides my /Filter Toggle plugin which allows players to get access to filter items they don't want. How do I disable the /Filter command on the ProtocolLib? I'm using Version 1.8.8 and the latest version of ProtocolLib. 

How do I disable the Filter command or fix this so that my Filter Plugin works or over rides this?

**Comment by Beepaa** [comment]
I have the same problem. @Jxpen Did you find a fix?

**Comment by MiniDigger** [comment]
/myplugin:filter and /protocollib:filter
You can use bukkits commands.yml to alias /filter to /myplugin:filter

**Comment by Beepaa** [comment]
@MiniDigger tried that still doesn't allow me to use the /filter command

  filter:
  - myplugin:filter
  filter:
  - protocollib:filter

**Comment by MiniDigger** [comment]
Just have one definition, not both. Remove the line about protocollib.

**Comment by Beepaa** [comment]
Nope still doesn't work gives me the same 

 /filter add;remove name [ID start]-[ID stop]
