### ISSUE TITLE
Could not pass event PlayerLoginEvent/PlayerQuitEvent

### ISSUE THREAD

**Issue by DevJorgeMCS** [dmulloy2/ProtocolLib#606]
- [x] You're using the latest build for your server version (1.13.2 from BuildTools, ProtocolLib 4.4.0)
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues (Some issues similars but not resolved yet)
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/4hrDMR10

Description and relevant errors:
https://pastebin.com/9AfMQq3m

**Comment by krustymk** [comment]
Same? https://pastebin.com/YiqPma7v

**Comment by Xosmuits** [comment]
Same for me.
