### ISSUE TITLE
[Request] Compatibility with Java 10+

### ISSUE THREAD

**Issue by The-Unnamed-Engineer** [dmulloy2/ProtocolLib#611]
First, I would like to mention that I do realize this would be a huge change to the core of the entire plugin, With the release of either Java 10 or 11 Reflections were deprecated.
I am currently looking into setting up my server to run on Java 12 due to the massive performance gains I have experienced with running the client on Java 12 and would like to see more plugins start updating in order to be compatible. 
I have already tested Spigot plugin free with no issues whatsoever on Java 12.

If anyone has any questions about this I will do my best to answer them.

**Comment by MiniDigger** [comment]
mmmh? protocollib runs on java 12 with no issues whatsoever. thats only that lil warning, but you can even suppress that if you want. I don't believe that there is a need to change anything here, as oracle hasn't announced any timeline for stricter enforcing module boundaries. even big frameworks like spring still rely on cross module reflection calls and this is not changing anytime soon.

**Comment by The-Unnamed-Engineer** [comment]
I have run into one issue on Java 12, For whatever reason protocollib detects regular players as temporary players, which leads to a multitude of plugins throwing errors about getuniqueid
