### ISSUE TITLE
Errors on login and item issues

### ISSUE THREAD

**Issue by Xosmuits** [dmulloy2/ProtocolLib#612]
I'm having these errors on login.
https://hastebin.com/oxugohinej.bash

-

Also items become invisible when taken to the inventory on 1.12.2 with ProtocolSupport (idk if this issue is about protocollib or protocolsupport but it only occurs when i load Protocollib)

-

Versions: http://prntscr.com/norac2
Plugins: http://prntscr.com/norahs

**Comment by Xosmuits** [comment]
No one knows the solve i guess :c

**Comment by dmulloy2** [comment]
Update to one of the dev builds
