### ISSUE TITLE
Javadoc is down

### ISSUE THREAD

**Issue by Rossmall** [dmulloy2/ProtocolLib#614]
Hello, I can't access [the Javadoc](http://ci.dmulloy2.net/job/ProtocolLib/javadoc/) since several days, there is a stack trace instead.
Thank you.

**Comment by ishland** [comment]
Same issue

**Comment by CDFN** [comment]
Same issue, posted issue too

**Comment by dmulloy2** [comment]
Hopefully it's back up now. Sorry for the interruption.

**Comment by Rossmall** [comment]
It is, thank you ! :)
