### ISSUE TITLE
IllegalArgumentException thrown on reading PlayerDigType on packet Play.Client.BLOCK_DIG

### ISSUE THREAD

**Issue by Tibo442** [dmulloy2/ProtocolLib#62]
Unhandled exception occured in onPacketReceiving(PacketEvent)

java.lang.IllegalArgumentException: No enum constant com.comphenix.protocol.wrappers.EnumWrappers.PlayerDigType.DOWN

When calling e.getPacket().getPlayerDigTypes().read(0).

e.getPacket().getModifier().read(2) returns the correct but not wrapped object.

**Comment by dmulloy2** [comment]
Can you provide the full stack trace?

**Comment by Tibo442** [comment]
http://pastebin.com/LBuyUYKM

-- Groetjes van Tibo

2015-03-21 17:01 GMT+01:00 Dan Mulloy <notifications@github.com>:
