### ISSUE TITLE
Error randomly occured

### ISSUE THREAD

**Issue by maxlehot1234** [dmulloy2/ProtocolLib#623]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
https://gist.github.com/maxlehot1234/16c7991186eee20fb8a8a8176078ea97

EDIT: This is the ./protocol dump :
https://gist.github.com/maxlehot1234/f56fe99fbf45f943f88a338534787c61

Description and relevant errors:
EDIT: Occured when a player logout and login again in few seconds.

**Comment by maxlehot1234** [comment]
Occured when a player logout and login again...

A fix would be really great ;)

**Comment by MiniDigger** [comment]
thats not a debug past link...
please run  '/protocol dump' as instructed and post that to gist.

**Comment by maxlehot1234** [comment]
ooops:
Here it is:
https://gist.github.com/maxlehot1234/f56fe99fbf45f943f88a338534787c61 @MiniDigger

**Comment by MiniDigger** [comment]
try removing the vanish plugin, its the only plugin that touches that packet.

**Comment by maxlehot1234** [comment]
@MiniDigger 
I remove PremiumVanish, restart the server and problem still occured

I disconnect and reconnect and all other players are kick

This is the error in the console when this occured:
https://gist.github.com/maxlehot1234/6419e4ba124c637150c35613d3eb9877

**Comment by Eth3rn3l** [comment]
I have the same problem , like yesterday a error appeared like and my server crash instantly !
https://pastebin.com/ff4zT5f1

**Comment by MiniDigger** [comment]
@Eth3rn3l your server was stopped via rcon. it did not crash.

**Comment by Eth3rn3l** [comment]
it crash

**Comment by Eth3rn3l** [comment]
Idk why but the server crash after 1 or 2 sec

**Comment by Eth3rn3l** [comment]
I just retart the server and it still crash !
https://pastebin.com/SvU0rwLz

**Comment by MiniDigger** [comment]
again, its rcon. please don't pollute this issue
```
[14:59:01] [Server thread/INFO]: [Rcon: Saved the game]
[14:59:01] [Server thread/INFO]: [Rcon: Stopping the server]
[14:59:01] [Server thread/INFO]: Stopping server
```

**Comment by Eth3rn3l** [comment]
And how can i block the rcon !

**Comment by maxlehot1234** [comment]
Anything for this?
@MiniDigger

**Comment by maxlehot1234** [comment]
Anything on this @dmulloy2 

A fix would be nice ;)

**Comment by maxlehot1234** [comment]
Anything for this?

**Comment by dmulloy2** [comment]
Try downgrading to this build: http://ci.dmulloy2.net/job/ProtocolLib/425/

**Comment by maxlehot1234** [comment]
Already have this build @dmulloy2

**Comment by dmulloy2** [comment]
Your dump file says 4.5.0-snapshot, that build is 4.4.0

**Comment by maxlehot1234** [comment]
Already try that and I got the same issue :(
So I try with 1.14 version to see if it fix the issue and no
