### ISSUE TITLE
Has errors and will not run. 

### ISSUE THREAD

**Issue by FunkyJamma** [dmulloy2/ProtocolLib#624]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

https://gist.github.com/FunkyJamma/419624f18f297491d29a8f4e991f710a

Description and relevant errors:

Whenever I load in tot he server I get console errors and the plugin doesn't run.

**Comment by MiniDigger** [comment]
please provide the console errors...

**Comment by dmulloy2** [comment]
I can't help you without the errors
