### ISSUE TITLE
Misnamed packets

### ISSUE THREAD

**Issue by lorissikora** [dmulloy2/ProtocolLib#625]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
-

Description and relevant errors:

The names or IDs of the two packets `USE_ITEM` and `BLOCK_PLACE` seem to be swapped (see [PacketType.java](https://github.com/dmulloy2/ProtocolLib/blob/490b1dadcbbef126c1ec262072f3d3a90ad614e2/src/main/java/com/comphenix/protocol/PacketType.java#L332-L333)). When opening a Work bench for example a listener will detect `USE_ITEM` containing the payload of a `BLOCK_PLACE` packet. This is further supported by the [Protocol Specification](https://wiki.vg/Protocol#Player_Block_Placement) where it's visible, that the IDs don't seem to match up with the ones provided by ProtocolLib.

**Comment by dmulloy2** [comment]
Yeah this has been a problem for a while, but it just kind of is what it is. Just keep that in mind when writing listeners for it.

**Comment by lorissikora** [comment]
Then at least it would be good if it would be noted somewhere. Had I known this prior I could have saved myself a lot of head scratching and hours of debugging. But thanks anyway!
