### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by patchtv** [dmulloy2/ProtocolLib#628]
I did ctrl+f the open and closed issues with the basic error fingerprint and it couldn't find it.

Debug paste link:
https://hasteb.in/upujiley.kotlin

Description and relevant errors:
I've gotten the following error on a disconnection and it kicked all my players off the server and lagged it out completely.

the only plugin using protocollib right now is iControlU, no one performed any icu commands before or after the error.

**Comment by patchtv** [comment]
I just found out TrollCommands++ also makes use of ProtocolLib, disabled all ProtocolLib-related plugins temporarily until I can be sure of a fix 👍

**Comment by dmulloy2** [comment]
If you're using 1.14, use one of these dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
If you're on 1.13, use one of these: http://ci.dmulloy2.net/job/ProtocolLib/
