### ISSUE TITLE
ProtocolLib 1.14 Console Spam

### ISSUE THREAD

**Issue by AccioAce** [dmulloy2/ProtocolLib#631]
Hello, 
It seems like 1.14 latest version for protocolLib have console spams: https://gyazo.com/891186249f3c19032010b7785553df5d

**Comment by dmulloy2** [comment]
Are you using the 4.5.0 dev builds?

**Comment by AccioAce** [comment]
I believe I am using 1.14.2 latest version.

**Comment by MiniDigger** [comment]
please create a /protocol dump and attach it here, like the template suggested. We don't like to believe stuff, we like to know stuff ^^

**Comment by xd-Color** [comment]
Having the same problem. Here is my ProtocolLib dump if this can help out. Using 1.14.3. https://pastebin.com/JAgfJMCU
