### ISSUE TITLE
Hey what's the ProtocolLib packet for essentials balance on a scoreboard?

### ISSUE THREAD

**Issue by mcjojo3** [dmulloy2/ProtocolLib#634]
like the title says

**Comment by mcjojo3** [comment]
like ex %player_balance% idk

**Comment by dmulloy2** [comment]
I'm not sure what you're asking. There isn't a packet for the essentials balance. Maybe you're looking for Placeholder API?

**Comment by BigBadE** [comment]
That's not a packet

Do you mean the balance set on a scoreboard? If so you can probably edit it by using Essentials as a dependency
