### ISSUE TITLE
"Plugin is disabled" and files don't generate

### ISSUE THREAD

**Issue by Yronusa2000** [dmulloy2/ProtocolLib#635]
Description and relevant errors:

Hi, ProtocolLib "don't works". I don't know what is happening and what is going wrong, but no commands are working. According to the console, the "plugin is disabled". Moreover, there is no files "ProtocolLib"  generated in the server after the restart.
Spigot version used: 1.12.2 
I didn't /reload, I /restarted my server, I downloaded the last version
I took the plugin's latest release on Spigot.

Pastebin error : https://pastebin.com/ZPfwNGjH

Debug paste link:
No debug, /protocol dump don't work ("An internal error occured while attempting to perform this command").

Thanks you in advance!

**Comment by dmulloy2** [comment]
Are there errors on start up?

**Comment by Yronusa2000** [comment]
Yes. But, on startup, this error appear in the console :

https://pastebin.com/d10Eqdh5

And I also found this: https://pastebin.com/LinybE8D

**Comment by dmulloy2** [comment]
Try one of the 4.5.0 dev builds here: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/

**Comment by Yronusa2000** [comment]
Same than with the other version, with the same errors.

**Comment by dmulloy2** [comment]
Can you post the errors from the new version?

**Comment by Yronusa2000** [comment]
https://pastebin.com/HtFV3SpB < on server restart, I'm not using /reload or PlugMan.

https://pastebin.com/HAvVWrv7 < On /protocol.

**Comment by Yronusa2000** [comment]
Okay I don't think this is an issue for ProtocolLib. That's the same with ChatControl... I'm going to find where this is from, sorry for your time...

**Comment by Yronusa2000** [comment]
That was because of "Mineweb bridge" (a plugin for linking web site with your server). You should add that issue in the FAQ or the wiki ^^ https://docs.mineweb.org/#liaison-un-serveur-par-d-faut
