### ISSUE TITLE
Support for 1.14.3-pre4

### ISSUE THREAD

**Issue by YourCoalAlt** [dmulloy2/ProtocolLib#636]
Even though this is expected, just wanting to make sure you're aware. :)

Debug paste link: https://pastebin.com/m4zStESF

Description and relevant errors: Spams console and said report it

**Comment by klugemonkey** [comment]
MinecraftVersion.java should probably have the VERSION_PATTERN changed..

private static final Pattern VERSION_PATTERN = Pattern.compile(".*\\(.*MC.\\s*([a-zA-Z0-9\\-\\.]+)\\s.*\\)");
