### ISSUE TITLE
Failing to clone entity metadata packets in 1.14, 1.14.1, 1.4.2. Latest ProtocolLib dev version.

### ISSUE THREAD

**Issue by Niall7459** [dmulloy2/ProtocolLib#637]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
Multiple:
https://pastebin.com/M5zqwUkd
https://pastebin.com/PAt8MCjU
https://pastebin.com/cDfU1rwc

Description and relevant errors:

Issue cloning PacketPlayOutEntityMetadata. I'm pretty sure this isn't an issue on my side. Any information for anything that needs changing for 1.14 would be great. Thank you.

Packet Event Listener:
```java
    @Override
    public void onPacketSending(PacketEvent event) {
        PacketContainer packet = event.getPacket();

        if (packet.getType() != PacketType.Play.Server.ENTITY_METADATA) {
            return;
        }

        WrapperPlayServerEntityMetadata entityMetadataPacket = new WrapperPlayServerEntityMetadata(packet.deepClone());
        List<WrappedWatchableObject> dataWatcherValues = entityMetadataPacket.getEntityMetadata();

        for (WrappedWatchableObject watchableObject : dataWatcherValues) {
            if (watchableObject.getIndex() == 2) {
                if (replacePlaceholders(watchableObject, event.getPlayer())) {
                    event.setPacket(entityMetadataPacket.getHandle());
                }
                return;
            }
        }
    }
```

**Comment by dmulloy2** [comment]
Multicraft is cutting out the useful part of the stack:
```08.06 00:04:44 [Multicraft] Skipped 76 lines due to rate limit (30/s)```

Can you get a complete one?

**Comment by HexedHero** [comment]
https://cdn.hexedhero.com/u/bUz5Nh1kJF.log

**Comment by Brokkonaut** [comment]
I have something similar: https://pastebin.com/raw/hBcMJd1t

**Comment by dmulloy2** [comment]
Thanks! I'll fix those when I get the chance, hopefully soon-ish

**Comment by Niall7459** [comment]
Hey, just wondering if there’s any progress on this or when we can see the fix implemented?

Regards

**Comment by TheRealWulf** [comment]
Spams this error multiple times in console.
https://pastebin.com/rXijkPSx
Only happens when players interact with HDs.

**Comment by HexedHero** [comment]
Please fix?

**Comment by dmulloy2** [comment]
Sorry, was really busy the last few months. Working on it now.

**Comment by HexedHero** [comment]
> Sorry, was really busy the last few months. Working on it now.

Finally, thank the lord !

**Comment by successed** [comment]
WHY CLOSED İSSUE ?

http://bin.shortbin.eu:8080/QggbCzj5hk

**Comment by HexedHero** [comment]
> WHY CLOSED İSSUE ?
> 
> http://bin.shortbin.eu:8080/QggbCzj5hk

It's literally fixed, go update.

**Comment by TheRealWulf** [comment]
I am updated with everything and the issue still persists.
https://pastebin.com/LM1xdpR0
