### ISSUE TITLE
Getting this error on the newer versions. Build #21 works.

### ISSUE THREAD

**Issue by filoghost** [dmulloy2/ProtocolLib#64]
Hi, I'm currently getting this error: http://hastebin.com/goniwocuza.avrasm it doesn't occour on the build #21.
The line that is causing the error: https://github.com/filoghost/HolographicDisplays/blob/master/HolographicDisplays/Plugin/com/gmail/filoghost/holographicdisplays/bridge/protocollib/ProtocolLibHook.java#L153

I don't understand if this error is my fault, I'm not very familiar with Protocol Lib.

**Comment by NavidK0** [comment]
I'm getting this error as well, it's likely got to do with the recent class changes.
