### ISSUE TITLE
Use bed packet in 1.14?

### ISSUE THREAD

**Issue by STEngineer** [dmulloy2/ProtocolLib#642]
I want to use `USE_BED` packet in 1.14, but it was removed

**Comment by MiniDigger** [comment]
well, its has been removed, you can't use it.
sleeping is now part of the entity metadate as part of a new pose field (varint enum) with the values 
0: STANDING, 1: FALL_FLYING, 2: SLEEPING, 3: SWIMMING, 4: SPIN_ATTACK, 5: SNEAKING, 6: DYING
so depending on what you want to do, you can just update the metadata of the player.

**Comment by STEngineer** [comment]
Thank you

**Comment by STEngineer** [comment]
Actually, I didn't understand how do I do it, so I need help
