### ISSUE TITLE
NoSuchAsMethodException but PacketPlayOutPlayerInfo$PlayerInfoData shouldn't have PacketPlayOutPlayerInfo inside the constructer (1.8R3)

### ISSUE THREAD

**Issue by LeeGodSRC** [dmulloy2/ProtocolLib#644]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [yes ] You're using the latest build for your server version
- [yes ] This isn't an issue caused by another plugin
- [yes ] You've checked for duplicate issues
- [yes ] You didn't use `/reload`

Debug paste link:
https://pastebin.com/qe32XJd1

Description and relevant errors:
java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutPlayerInfo$PlayerInfoData.<init>(net.minecraft.server.v1_8_R3.PacketPlayOutPlayerInfo, com.mojang.authlib.GameProfile, int, net.minecraft.server.v1_8_R3.WorldSettings$EnumGamemode, net.minecraft.server.v1_8_R3.IChatBaseComponent)

i have searched a lot of codes from other spigot with 1.8R3 (like paper, taco and md 5 releases),
but all of them deleted PacketPlayOutPlayerInfo from the constructer,
i think it's an issue for Protocollib, please tell me if i write something wrong and thanks for great lib plugin < 3

**Comment by dmulloy2** [comment]
Can you share your code? And run `/protocol dump` and post that on pastebin?
