### ISSUE TITLE
Empty packets on Tab_Complete

### ISSUE THREAD

**Issue by baticag** [dmulloy2/ProtocolLib#645]
This is only happening when using BungeeCord and ProtocolLib on back-end server.
Player connects on back-end server using BungeeCord proxy. He tries typing command which should suggest him more suggestions than the limit. Players connection with that current back-end server gets closed because of empty packet for suggestion and he is kicked to BungeeCords fallback server. 

This error is thrown in BungeeCord console: https://pastebin.com/dXpWgGfr

The expected behavior is that this message is shown to the player and he is not kicked from back-end server: https://i.imgur.com/9VQvoSR.png

This is only happening with ProtocolLib inside plugins of back-end server and when using BungeeCord in combination. Using latest ProcotolLib from dev builds (tried also older versions), BungeeCord 1416 and PaperSpigot 636 (1.13.2)

Can you please look into this?

**Comment by Darcion** [comment]
one of our player got this too (sometimes) when he switched servers. Every plugin BungeeCord, Spigot and protcollib is latest build (#14).

**Comment by dmulloy2** [comment]
Can you run /protocol debug and paste the results on pastebin?

**Comment by DefinitlyEvil** [comment]
I got this issue too!
