### ISSUE TITLE
IllegalArgumentException: Unrecognized raw ID 12

### ISSUE THREAD

**Issue by fvoichick** [dmulloy2/ProtocolLib#648]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link: https://pastebin.com/29u9CtEQ

Description and relevant errors:

I added ProtocolLib to my plugins folder, with no other plugins installed. Then, I started the server and ran the command: `/packet add play server map_chunk true`. I then logged into the server. In the console, I received this error message: https://pastebin.com/KgdTbcqq

**Comment by dmulloy2** [comment]
Looks like we don't currently support Long Array NBT tags. Should (hopefully, fingers crossed) be a simple fix
