### ISSUE TITLE
Unable to find method scanPlayers ([]) in class net.minecraft.server.v1_14_R1.EntityTrackerEntry.

### ISSUE THREAD

**Issue by YourPalJake** [dmulloy2/ProtocolLib#651]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/yZDK2wgP
Description and relevant errors: When scanning for players to show the vanished player again, it throws that ```ProtocolLibrary.getProtocolManager().updateEntity(vanishedPlayer, Collections.singletonList(receiver));````

This wasn't on my end

**Comment by dmulloy2** [comment]
What version of ProtocolLib are you using?

**Comment by YourPalJake** [comment]
Snapshot 4.5.0 build #9
