### ISSUE TITLE
ProtocolLib 1.14.4 + HolographicDisplays

### ISSUE THREAD

**Issue by Darkweasam** [dmulloy2/ProtocolLib#653]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x ] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin (I believe)
- [x ] You've checked for duplicate issues
- [x ] You didn't use `/reload`

Debug paste link:
https://pastebin.com/fPYRVAzj

Description and relevant errors:
Holographicsdisplays doesnt work on 1.14.4, It worked fine on 1.14.3. I believe it might be a protocollib issue (Sorry if its not)
https://pastebin.com/Rz6nNeB5

**Comment by magmiy** [comment]
I have the same issue.

**Comment by bundabrg** [comment]
References: https://github.com/filoghost/HolographicDisplays/issues/135
