### ISSUE TITLE
Issue with my plugin which supports ProtocolLib

### ISSUE THREAD

**Issue by Ifriedmonkey** [dmulloy2/ProtocolLib#654]
- [ ] Version: Spigot 1.7.10 (need it for my plugins to work)

I am using a plugin which needs ProtocolLib to work, the plugin works, but when the game ends it stops working I get this error in the console any ideas on what to do? It used to work so does the plugin need upgrading/downgrading? 

Log: 
https://pastebin.com/uKhKjw9J

**Comment by Brokkonaut** [comment]
It is a problem with TagAPI. Maybe incorrect version or something.
