### ISSUE TITLE
Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by Ghost-chu** [dmulloy2/ProtocolLib#655]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://paste.ubuntu.com/p/dgZph6ZdTM/
Description and relevant errors:

**Comment by TwerkRekt** [comment]
same error

**Comment by rocky143** [comment]
Having the same issue. 
This error also freezes the console for me.
