### ISSUE TITLE
ERRORs

### ISSUE THREAD

**Issue by BlackRebbel** [dmulloy2/ProtocolLib#656]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
https://pastebin.com/yDWYfu4M
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

Description and relevant errors:

**Comment by Machine-Maker** [comment]
Couple things,
1. Make sure you have ProtocolLib in your plugins directory
2. Make sure your plugin.yml has `depend: [ProtocolLib]` in it

**Comment by MiniDigger** [comment]
where is the debug paste link?
how are we supposed to help you without that? 

it looks like your current build of PL isn't compatible with latest spigot (another mapping change maybe, idk, didnt touch 1.14 yet)
> Unable to find findStatistic in net.minecraft.server.v1_14_R1.StatisticList
