### ISSUE TITLE
Packet "Acknowledge_Player_Digging" is not available

### ISSUE THREAD

**Issue by Brokkonaut** [dmulloy2/ProtocolLib#657]
The new packet "Acknowledge_Player_Digging" is not available in protocollib.
https://wiki.vg/Pre-release_protocol#Acknowledge_Player_Digging

**Comment by dmulloy2** [comment]
Ok, I'll go ahead and add it

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/62e8d82e1664eeb286c57fedefe1a7213acc5d31
