### ISSUE TITLE
Feature request: include build number in dev builds

### ISSUE THREAD

**Issue by SlimeDog** [dmulloy2/ProtocolLib#658]
Please include build numbers in dev builds. It would be very useful if
> /version ProtocolLib

returned
> 4.5.0-SNAPSHOT-b9

instead of just 
> 4.5.0-SNAPSHOT

which is ambiguous as to which of the nine snapshots one is running.

**Comment by dmulloy2** [comment]
Strange. It _should_ be configured to do that now, but maybe I gradled it wrong.

**Comment by SlimeDog** [comment]
Confirmed that it does work that way now. I don't remember when it changed. Thank you.
