### ISSUE TITLE
Server not turning on for some players

### ISSUE THREAD

**Issue by ItsVinnyX** [dmulloy2/ProtocolLib#659]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X ] You're using the latest build for your server version
- [ X] This isn't an issue caused by another plugin
- [ X] You've checked for duplicate issues
- [ X] You didn't use `/reload`

Debug paste link:
https://pastebin.com/Ax2gHC61

Description and relevant errors:
Doesn't allow players to connect in the server menu causes crazy lag. 1.14 DEV Build

**Comment by MiniDigger** [comment]
OldCombatMechanics seems to write invalid data, make sure its up to date with 1.14.4

also, thats not a debug paste link...

**Comment by ItzVinex** [comment]
@MiniDigger I'll provide that later... Anyway, it seems to be alright with the DEV version 4.5.0 for 1.14.4. The current DEV version I was using seems like it wasn't working. I would check into that.

**Comment by ItzVinex** [comment]
Continues to do it with and without, OldCombatMechanics
