### ISSUE TITLE
Not all information in WrappedBlockData is cloned

### ISSUE THREAD

**Issue by fvoichick** [dmulloy2/ProtocolLib#661]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link: https://pastebin.com/BJpqXneX

Description and relevant errors:

I ran only this code in a plugin:

    String dataString = "minecraft:redstone_wire[north=side,south=side]";
    BlockData data = getServer().createBlockData(dataString);
    WrappedBlockData wrapped = WrappedBlockData.createData(data);
    Logger logger = getLogger();
    logger.info("Original: " + wrapped.toString());
    logger.info("Cloned: " + wrapped.deepClone().toString());

The output is the following:

    Original: WrappedBlockData[handle=Block{minecraft:redstone_wire}[east=none,north=side,power=0,south=side,west=none]]
    Cloned: WrappedBlockData[handle=Block{minecraft:redstone_wire}[east=none,north=none,power=0,south=none,west=none]]

Thus, the "clone" is not really a clone.

**Comment by dmulloy2** [comment]
Interesting. I'll look into a better cloning strategy (best guess right now would be to use to/from string)

**Comment by fvoichick** [comment]
#662 might be the fix, but I'm not sure why it's failing the checks

**Comment by dmulloy2** [comment]
Travis is having a weird issue. The builds on the CI server are running fine
