### ISSUE TITLE
ProtocolManager#updateEntity ghost a player when they are in different worlds

### ISSUE THREAD

**Issue by 0ddlyoko** [dmulloy2/ProtocolLib#668]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
https://pastebin.com/r9Gjuduy

Description and relevant errors:
I have a plugin that vanish players in a zone and unvanish him when he quits his zone.
To unvanish him, I just call ProtocolManager#updateEntity(Entity, List<Player>) to update all packets.
When I call this method, all works, but if both players are in different worlds, it create a kind of "ghost".

![image](https://user-images.githubusercontent.com/11074473/62837994-8f6da080-bc76-11e9-9640-f903bda60f52.png)

As you can see in above image, the player on the top see a ghost of the other player event if the other player isn't in the same dimension.
If you want the code, he is [here](https://github.com/0ddlyoko/Invest/blob/5822b29fa8556f7234e16d3dcaffe10b29339953/src/main/java/me/oddlyoko/invest/ProtocolLibManager.java#L191)
I can fix that just by checking if players are in different worlds [like here](https://github.com/0ddlyoko/Invest/blob/0722ec42427daaca455e6b7d759509d303531422/src/main/java/me/oddlyoko/invest/ProtocolLibManager.java#L194) but I'm pretty sure it's a bug from ProtocolLib

**Comment by dmulloy2** [comment]
I'm not so sure that's a ProtocolLib bug, seems like a Minecraft bug. Is there a problem with checking if they're in different worlds?

**Comment by 0ddlyoko** [comment]
That was fastly fixed (I just checked the world) but this bug is strange. If you think it's a Minecraft bug, I'll close this ticket
