### ISSUE TITLE
Error while disguising Zombie Villager

### ISSUE THREAD

**Issue by eric2788** [dmulloy2/ProtocolLib#670]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/SARp6C7j

Description and relevant errors:
When this error has spammed, players who are watching the disgusing player are all been kicked.
I'm using 1.14.4 latest spigot version.

**Comment by dmulloy2** [comment]
Which disguise plugin are you using?

**Comment by eric2788** [comment]
Lib's disguise, seems fixed at the latest development build, i think this can close now
