### ISSUE TITLE
java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by fahlur** [dmulloy2/ProtocolLib#673]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://pastebin.com/fiZHDyuv

Description and relevant errors:
Error shows while on spigot mc 1.14.4
it doesn't seem to break the plugin in any way, more or less cosmetic. But despite the unable to retrieve error. The stack trace that follows doesn't seem right and i'm reporting as such.

**Comment by 100petr** [comment]
> _Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
> 
> Make sure you've done the following:
> 
> * [x]  You're using the latest build for your server version
> * [x]  This isn't an issue caused by another plugin
> * [x]  You've checked for duplicate issues
> * [x]  You didn't use `/reload`
> 
> Debug paste link:
> https://pastebin.com/fiZHDyuv
> 
> Description and relevant errors:
> Error shows while on spigot mc 1.14.4
> it doesn't seem to break the plugin in any way, more or less cosmetic. But despite the unable to retrieve error. The stack trace that follows doesn't seem right and i'm reporting as such.

The player tried to connect and protocollib gave error (It does not always, only occasionally)

**Comment by dmulloy2** [comment]
Looks like there's something wrong in your config.yml, try renaming it to `config.yml.bak` and letting ProtocolLib generate a new one.

**Comment by fahlur** [comment]
seems to have solved the issue, thanks much
