### ISSUE TITLE
Error - player join

### ISSUE THREAD

**Issue by 100petr** [dmulloy2/ProtocolLib#675]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Debug paste link:
https://pastebin.com/zMQXz4XH
Description and relevant errors:
https://pastebin.com/GGkWt60K
The player tried to connect and protocollib gave error (It does not always, only occasionally).

**Comment by dmulloy2** [comment]
Try using a dev build: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/

**Comment by 100petr** [comment]
I use 1.13.2 and on github is version 1.14.
