### ISSUE TITLE
1.12.2 version no comprende 

### ISSUE THREAD

**Issue by MacWhinny** [dmulloy2/ProtocolLib#676]
Hi, so i've installed this on my server, when i go into the server and type /plugins it shows as red. No folder is created (If one does) Tried a few other versions too. Even the latest build that says it supports 1.12 too, but narda 

Wondered if you had any ideas why.

**Comment by MiniDigger** [comment]
please attach the log

**Comment by MacWhinny** [comment]
https://hasteb.in/eweyizaf.md
https://hasteb.in/macijago.md

**Comment by MiniDigger** [comment]
uuuh, forge. I am not sure if protocollib supports that right now. 
Protocollib can't find some internals it needs to work, which might be caused by you using forge. Not sure tho, never tried one of those forge + bukkit hacks. 
you will need to wait till somebody else can take a look. in the mean time you should provide more details about your setup. I saw that you use FTB, what kind of server software in which version do you use?

**Comment by MacWhinny** [comment]
Thanks that's fine. 

Not showing forge in the the servers main directory. I'm running Kettle to run Plugins. Kettle basically being a Bukkit alternative. By moving over to Magma as the main Kettle dev took his code and left and started Magma. Further along than Kettle. Hope that makes sense :P 

I'm running MC V 1.12.2
Unsure about the software as it's hosted by Nitrous Networks
 
If there's anything else you want to know just let me know :)

**Comment by MiniDigger** [comment]
> Minecraft Forge Hybrid server implementing the Spigot/Bukkit API, formerly known as Contigo/Thermos/Cauldron/MCPC+

ah ok, so kettle and magma are just the last iteration of the messy forge + bukkit hacks :D

**Comment by MacWhinny** [comment]
Yeah. Though Magma has a the lead dev that started Kettle. He left as he was fed up with the staff not contributing to the coding. So he started Magma and took his code with him. 

Or so i'm told. 

But the plan is to fix the issues Bukkit had and for it to work as seamlessly as possible.

**Comment by dmulloy2** [comment]
There currently aren't plans to support Forge primarily because there hasn't been a single main Bukkit+Forge solution since Cauldron died. It doesn't make much sense to try and support all the alternatives

**Comment by MacWhinny** [comment]
Magma is the best one out there as of right now and considering a lot of plugins need your plugin to work. It means a lot of use can't use it.

**Comment by dmulloy2** [comment]
Can you point me to their website? If they have decent usage numbers it could be worth it

**Comment by MacWhinny** [comment]
https://github.com/magmafoundation/Magma
