### ISSUE TITLE
Version 1.13.2 has not yet been tested

### ISSUE THREAD

**Issue by Nety01** [dmulloy2/ProtocolLib#680]
Server version: Paper 1.13.2
Plugin version: 4.4.0

Get this on server start:
[17:38:11 WARN]: [ProtocolLib] Version (MC: 1.13.2) has not yet been tested! Proceed with caution.

Anyway it has been tested, no?

**Comment by joshaprior** [comment]
it is don't worry about that message

**Comment by Nety01** [comment]
Okay, thanks for fast reply

**Comment by dmulloy2** [comment]
Sometimes I forget to change the variables that trigger that message, but as long as everything works fine you can safely ignore it.
