### ISSUE TITLE
Having an issue with the dev build #16

### ISSUE THREAD

**Issue by TechieBlort** [dmulloy2/ProtocolLib#682]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [using a dev build # 16] You're using the latest build for your server version
- [ Not sure only spamming on my build server] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
I would add the /protocol dump but I can't run the command I just get kicked from the server cause of this issue.

Description and relevant errors:
https://pastebin.com/6uAqSYxe all I get spammed in console upon a player join :(

**Comment by joshaprior** [comment]
Check if you're not using multiple server instances (first line) i had the same issue because i was using multiple server instances.

**Comment by TechieBlort** [comment]
How do I check for that when it's not acting up on my SMP server (different IP's)?

**Comment by TechieBlort** [comment]
Side note: this issue only relates to Dev Build 16. Tried to use the one from my local drive instead of the server (also the dev build) it still broke. Using the Latest release on Spigot it fixed it.

**Comment by dmulloy2** [comment]
I haven't done server building in a while at this point but basically anywhere you share plugin jars/directories between different servers that are running is a problem
