### ISSUE TITLE
Can I use protocollib to stop brewing stands emitting smoke particles?

### ISSUE THREAD

**Issue by Capri205** [dmulloy2/ProtocolLib#686]
Hi. On our build server we are using the brewing stand for various models - based on the combination of water bottles, however I haven't found a way to stop the smoke particles being emitted. Is this possible with protocollib?

Cheers.

**Comment by dmulloy2** [comment]
Probably? If you could, it would be cancelling the particle packet from brewing stands. It also might be handled client side in which case you're out of luck.
