### ISSUE TITLE
Feature Request: Sync support for TinyProtocol

### ISSUE THREAD

**Issue by iso2013** [dmulloy2/ProtocolLib#687]
Hello! So I'm currently using ProtocolLib, and I'd like to switch to TinyProtocol; however, I've noticed that TinyProtocol does not support running the listeners synchronously.

It'd be awesome if there was a version that did! If anyone could point me to the right area to figure out how this would be done, I'd be happy to implement and PR it. I've tried to implement it by re-sending any async packets on the main thread, (the way ProtocolLib seems to do it) but I always run into errors with invalid packet IDs.

**Comment by dmulloy2** [comment]
You're certainly welcome to PR it. I haven't done much work with TinyProtocol though, so I'm not that familiar with how it actually works.
