### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by Killance** [dmulloy2/ProtocolLib#689]
Hello,

I'm using PaperMC 1.14.4 build 187 (the latest build) and I encounter a problem with the loading of the plugin: https://pastebin.com/CaARVHXf . I've tested the plugin on another server that runs an older version of PaperMC 1.14.4 (build 137) and I work fine.

Best regards,

Killance

**Comment by dmulloy2** [comment]
DId paper make some kind of breaking change recently?
