### ISSUE TITLE
Players stay in tablist after disconnect

### ISSUE THREAD

**Issue by freakyy85** [dmulloy2/ProtocolLib#69]
After disconnect some players stay in tablist. It doesn't happen often. I don't get any error.

**Comment by Rocknest** [comment]
Are you using BungeeCord?

**Comment by freakyy85** [comment]
no I'm not.

**Comment by Rocknest** [comment]
Probably it isn't caused by ProtocolLib. Recently had this problem and the reason was a broken plugin. Try to check your plugins one by one.

**Comment by freakyy85** [comment]
it happens since i installed protocollib

**Comment by dmulloy2** [comment]
Can you provide some more information, like what versions of ProtocolLib and Spigot you're using, as well as which of your plugins use ProtocolLib?

**Comment by freakyy85** [comment]
3.6.3-snapshot-b111 (protocollib)
spigot git-Spigot-dbe012b-61ef214
the only plugin i know which uses protocollib is disguisecraft.
i have over 60 plugins installed. but recently the bug doesnt occur anymore.
ill write something in here if it happens again. because i cant be of any more help now.
