### ISSUE TITLE
Error protocollib

### ISSUE THREAD

**Issue by KCookie16** [dmulloy2/ProtocolLib#691]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:
https://pastebin.com/YtauXnVw

Description and relevant errors:
What can cause this error in ProtocolLib?

**Comment by Janmm14** [comment]
player left the server
