### ISSUE TITLE
Latest 1.13.2 dev build of ProtocolLib (425) causing error in NoBlackSky plugin

### ISSUE THREAD

**Issue by axemwa** [dmulloy2/ProtocolLib#692]
![image](https://user-images.githubusercontent.com/37608633/65001176-a797a600-d92d-11e9-9123-0225c9a7b86b.png)
Latest 1.13.2 dev build of ProtocolLib (425) causing error in [NoBlackSky](https://www.spigotmc.org/resources/no-black-sky-1-7-1-14-for-void-worlds.25337/) plugin

Description and relevant errors:
https://pastebin.com/wGvF4zKe

Author of NoBlackSky claims it to be caused be protocollib but is unsure what it is specifically.

**Comment by MiniDigger** [comment]
"The method getWorld is not supported for temporary players"
this is an error in the plugin, he tried to access the world at a time when the player didn't yet join a world or already left the world. 
Nothing wrong with protocollib.

**Comment by axemwa** [comment]
ok thanx for replying :)
