### ISSUE TITLE
IndexOutOfBoundsException in 1.13.2 version/b425

### ISSUE THREAD

**Issue by Phoenix616** [dmulloy2/ProtocolLib#693]
Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin (doesn't look caused by it in the stacktrace but it happens since PacketLimiter got installed which listens for all packets)
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://gist.github.com/b79fa863721a039726fd012f1e303da9

Description and relevant errors:
https://gist.github.com/008dce91562946d744448fc623374000, the first line is spammed a bunch of times. Happens since the [PacketLimiter](https://www.spigotmc.org/resources/packet-limiter.70217/) plugin is installed which basically filters all packets which is probably why this has only been noticed now. The server is [Origami](https://github.com/Minebench/Origami/), my own Paper fork with very slight modifications which should not touch anything packet related at all.

**Comment by dmulloy2** [comment]
Does this happen with only PacketLimiter installed? And I assume it doesn't happen when it's not installed?
