### ISSUE TITLE
ProtocolLib issue

### ISSUE THREAD

**Issue by Deitooo** [dmulloy2/ProtocolLib#694]
Hi, i have a issue with ProtocolLib.
I just installed the plugin, i do anything and the plugin is disabled, i try in the past ProtocolLib and it never work, maybe a plugin cause this issue.

- [x] You're using the latest build for your server version
-( Don't know) This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
https://pastebin.com/LrurJj75

Thanks

**Comment by dmulloy2** [comment]
What build are you using?
