### ISSUE TITLE
Bungeecord error with transaction

### ISSUE THREAD

**Issue by Nort721** [dmulloy2/ProtocolLib#695]
detailed info about the error can be found here: https://www.spigotmc.org/threads/bungeecord-transaction-packet-error.396917/

**Comment by dmulloy2** [comment]
Is there a problem with sending it sync?

**Comment by Nort721** [comment]
Hey I've already figured it out, seems like the issue won't happen if I send the packets sync, I hope it won't cause any future issues sending the packet sync and not async
But anyway thanks for your time!
