### ISSUE TITLE
TinyProtocol throws IllegalArgumentException

### ISSUE THREAD

**Issue by aJoKer96** [dmulloy2/ProtocolLib#697]
Hello there,
i have problems running the ExamplePlugin of the TinyProtocol.
As you can see in the console output log the problem lays in the class Reflection.
I'm running the latest Spigot 1.12.2 on Java 8 Update 211, the plugin was compiled with eclipse.
The ExamplePlugin is the only plugin on the server and as you can see the error occures right at startup, so i dont used '/reload'.

I hope you can tell me whats the error or what i did wrong.

Console output paste link:
https://pastebin.com/40Zb13tx

**Comment by dmulloy2** [comment]
The TinyProtocol example plugin hasn't been updated in a while. The error there is that the field in chat packets was changed from String to ChatComponent.

**Comment by aJoKer96** [comment]
I think that is unlikely.

Since i just coppie-pasted it to see if it works, the line numbering is the same as here in github.
I tried to replace line 21
`private FieldAccessor<String> CHAT_MESSAGE  = Reflection.getField("{nms}.PacketPlayInChat", String.class, 0);`
with
`private FieldAccessor<ChatBaseComponent> CHAT_MESSAGE = Reflection.getField("{nms}.PacketPlayInChat", ChatBaseComponent.class, 0);`
and now the thrown error is at that line, i changed:
https://pastebin.com/nWkkMfTj

That let me belive, since the error befor those changes was on line 24 that there is a problem with the explosion packet
