### ISSUE TITLE
Error with dependant spigot plugin

### ISSUE THREAD

**Issue by topthat177** [dmulloy2/ProtocolLib#699]
Hi,

If this is not your problem or you don't deal with it because it relates to an interaction with another plugin let me know.

This is a problem with another Spigot Plugin dependent on ProtocolLib. I have reported the Issue to the dev and apparently its not on their side. They suggested it might be caused by this dependency. 

The issue is with Gadgets Menu and their Morph Disguise Cosmetic feature. 

When selecting a morph and selecting to view your character as the disguised mob, the following NPE appears in console. You also only see your player instead of the morphed mob and after a while of moving around you go invisible. 

To Reproduce

  - Install GadgetsMenu
  - Turn on Self View
  - Select any morph
  - See Error in console and that it doesn't display the morph to the player
  - Move around for a while and notice you become invisible.

Further Information (please complete the following information):

    Server Version: Paper 1.14.4
    GadgetsMenu Version: 4.3.24
    Console: https://pastebin.com/uL8FVK4Q

![2019-10-01_15 46 52](https://user-images.githubusercontent.com/29544476/66134480-becbd880-e63b-11e9-88cd-10c2b605efde.png)
![2019-10-01_15 48 24](https://user-images.githubusercontent.com/29544476/66134497-c25f5f80-e63b-11e9-8287-096fa85d5aee.png)
![2019-10-01_15 48 41](https://user-images.githubusercontent.com/29544476/66134509-c7241380-e63b-11e9-8ce6-6a13f08160b6.png)
![2019-10-01_15 55 11](https://user-images.githubusercontent.com/29544476/66134513-c9866d80-e63b-11e9-9dd0-d8d322c0d8cb.png)

Desktop (not sure if you need this, server not locally hosted)
 - OS: Windows 10
 - Browser Firefox
 - Version 69.0.1

**Comment by dmulloy2** [comment]
This looks like an error with Libs Disguises:

```
26.09 05:27:21 [Server] WARN java.lang.NullPointerException
26.09 05:27:21 [Server] WARN at me.libraryaddict.disguise.utilities.DisguiseUtilities.removeSelfDisguise(DisguiseUtilities.java:1263)
```

**Comment by topthat177** [comment]
Ok I'll forward it onto them. 3rd time lucky they say :)
