### ISSUE TITLE
Problem with particle spawning

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [dmulloy2/ProtocolLib#701]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
I want to spawn particles, but it gives an [LightUpdate error](https://pastebin.com/DDe1Gw1a).

**API method(s) used**
In code

**Expected behavior**
Spawn particles

**Code**
https://pastebin.com/32QndUc1

**Additional context**
None

**Comment by MiniDigger** [comment]
heh, thats interesting.
I bet you use an outdated version of minecraft, right?
one where packet 0x23 is update light, not world particles.
can you try using createPacket with the numerical id instead of the packet?

**Comment by Kryniowesegryderiusz** [comment]
Thats interesting, cause im using 1.14.4 latest (209) build paperspigot

**Comment by MiniDigger** [comment]
uuuhm, thats even more interesting. what I though is that protocollib didn't properly remap the packet id.
again, even on 1.14, can you try calling createPacket(0x23), not via the PacketType?

**Comment by Kryniowesegryderiusz** [comment]
I cant set ther 0x23, so I just set 23 and got https://pastebin.com/yWPxYd17

**Comment by MiniDigger** [comment]
yeah, 23 is yet another packet :D
0x23 is hexadecimal, that would be 35 in decimal (2*16+3), so please use that

**Comment by Kryniowesegryderiusz** [comment]
Still not :c No field with type float exists in class PacketPlayOutLogin
