### ISSUE TITLE
1.14.4 sending packet throw an error

### ISSUE THREAD

**Issue by Shyrogan** [dmulloy2/ProtocolLib#702]
**Describe the bug**
Sending a message using packets on Paper on 1.14.4 throw an error
I'm using the latest build of ProtocolLib

**To Reproduce**
Send a Play.Server.Chat packet with a WrappedChatComponent inside on a 1.14.4 server

**Expected behavior**
Sending a WrappedChatComponent using the `fromJson` message throw the error in the screen below
Json text:
`["",{"text":"Super text!","color":"red"}]`

Code:
https://i.ibb.co/n1D6FDZ/Annotation-2019-10-05-181555.png

**Screenshots**
Error:
https://i.ibb.co/JkkDNgf/Annotation-2019-10-05-181231.png

**Comment by Shyrogan** [comment]
Nevermind I uploaded the wrong file into the plugin list, still get an error for a message that can be sent correctly using the `/tellraw` command, same code.
![image](https://user-images.githubusercontent.com/24733746/66479443-cefd1100-ea9c-11e9-9f1b-73645d807701.png)

**Comment by dmulloy2** [comment]
Does this happen in earlier versions of 1.14 / 1.13?

**Comment by Shyrogan** [comment]
> Does this happen in earlier versions of 1.14 / 1.13?

It used to work with the same code in 1.13
