### ISSUE TITLE
Consider making the repository JitPack-compatible.

### ISSUE THREAD

**Issue by RezzedUp** [dmulloy2/ProtocolLib#705]
With ProtocolLib's maven repository recently being down (see #703 and #704), I would prefer to use a service like JitPack to receive ProtocolLib as a dependency for my projects. However, recent changes have caused JitPack's builds to fail ([4.4.0's build log](https://jitpack.io/com/github/dmulloy2/ProtocolLib/4.4.0/build.log) and the [gradle branch's build log](https://jitpack.io/com/github/dmulloy2/ProtocolLib/gradle-1.5.0-gb5cff49-1156/build.log) -- both were unable to be built).

Please make the repository JitPack-compatible. Thank you!

**Comment by sgdc3** [comment]
JitPack should be used as a last resort, it actually changes the pom deployed with the artifact. That caused me a lot of issues in the past.

**Comment by dmulloy2** [comment]
Plan going forward is to try to use GitHub's package manager

**Comment by RezzedUp** [comment]
@sgdc3 For public projects, I'd definitely use official repositories, but for personal projects, I'd rather use the easiest option with as few repositories in my POM as possible. Really all I'm asking for is an alternative way to depend on ProtocolLib, which @dmulloy2 seems to have a better solution for than JitPack anyway. I guess this issue is resolved. 😛 Thank you!
