### ISSUE TITLE
Server is spamming on console, about ExceptionInInitializerError

### ISSUE THREAD

**Issue by MassiveLag** [dmulloy2/ProtocolLib#707]
**Describe the bug**
When the server is starting it works fine. when i join and walk around it starts throwing warnings about that the plugin already is running in another instance, while it's clearly not.

**To Reproduce**
1. Go to 'Start the server'
2. Join the server
3. Walk around.
4. See error https://paste.helpch.at/ovofunazen.md

**Expected behavior**
Hopefully just someone can help me out, or fix this issue.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/22543334/67132988-2755b080-f20b-11e9-80c6-5803a21069bb.png)

**Comment by MiniDigger** [comment]
Sadly the interesting part of the error is cut off, but in suspect a plugin doesn't properly deal with the outdated nature of your server.
Do you know about any plugins that do stuff with villagers? Could you remove them and try again?

**Comment by dmulloy2** [comment]
Update on this?

**Comment by JoelDeadMach** [comment]
Still happening on hub3 server



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
