### ISSUE TITLE
Can't load ProtocolLib

### ISSUE THREAD

**Issue by WarnDangerous** [dmulloy2/ProtocolLib#708]
Hello,

I have been used ProtocolLib for a while but now I have a weird issue with it, it can't load, I tried to change my spigort version ( I'm using spigot 1.12.2 but I tried many spigot 1.12.2 jar ), I also tried different protocolLib versions ( latest on spigot : ProtocolLib 4.4.0 , latest dev build for 1.12.2 : ProtocolLib 4.4.0, etc )

But there is a weird problem, it detects that protocollib is loaded manually but I RESTART the server, not reloading them. And also protocollib seems to load twice in the logs, strange ^^

Here are the logs when loading : 
https://pastebin.com/xKfKHgU5

Here are the messages caused by ProtocolLib in the logs : 
https://pastebin.com/XNdrfwi4

**Comment by WarnDangerous** [comment]
No help ? :c

**Comment by dmulloy2** [comment]
Try the latest dev build: http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by dmulloy2** [comment]
Update on this?

**Comment by WarnDangerous** [comment]
Hello, sorry for the late answer, the problem was mineweb (which cause sometimes bugs with protocolLib, but there's a fixed version of protocollib on their website, it fixed my issue
