### ISSUE TITLE
Exception wrapping causing problems with Via

### ISSUE THREAD

**Issue by KennyTV** [dmulloy2/ProtocolLib#711]
To cancel incoming and outgoing packets, ViaVersion (a plugin to support clients with versions different to the server version) throws an exception (similar to what Vanilla does to cancel packets iirc) to escape netty's writing process. Since cancelling happens quite frequently, the exception is cached and is also extending netty's En-/DecoderException to avoid **[wrapping and stacktrace creation in netty](https://github.com/netty/netty/blob/e745ef0645cc63e017d0a6599610a59af22842f8/codec/src/main/java/io/netty/handler/codec/MessageToByteEncoder.java#L122-L123)** (instead of what would be done else, 2 lines below that).

[ProtocolLib's reflection utils wrap any invocationtargetexceptions](https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/reflect/accessors/DefaultMethodAccessor.java#L20) with a newly created RuntimeException, which in our case makes for 2 extra exceptions with generated stacktraces. This wouldn't be a problem normally, but does cause a considerable overhead in combination with ViaVersion's handling in a place that is easy to be avoided.

Now to the actual question: Could you **either throw the underlying exception without wrapping** (similar to what **[we do here](https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/us/myles/ViaVersion/bukkit/handlers/BukkitEncodeHandler.java#L53)**), **or do exactly that only in the 3 cases of calling netty's encode and decode method (found in your ChannelInjector class)**?
It's still an extra wrapping (ReflectionEx), but the 2 layers less would still do a lot in such a hot spot 👀

**Comment by dmulloy2** [comment]
Sure, that seems reasonable enough.

**Comment by dmulloy2** [comment]
@KennyTV can you try the latest dev build (http://ci.dmulloy2.net/job/ProtocolLib/) and see if the issue is fixed?

**Comment by KennyTV** [comment]
Here's the last case that needs to be checked https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/injector/netty/ChannelInjector.java#L472 - after doing that locally, all netty wrapping was gone 👏

**Comment by KennyTV** [comment]
Awesome, thank you!
