### ISSUE TITLE
1.14.4 not working at all

### ISSUE THREAD

**Issue by FendiTony777** [dmulloy2/ProtocolLib#712]
**Describe the bug**
1.13 client can't join with Protocol Lib and Spigot 1.14.4#207

**To Reproduce**
Paper1.14.4 #207 
ProtocolLib #429 

**Expected behavior**
I expected to join

**Additional context**

**Comment by dmulloy2** [comment]
can you provide a stack trace or anything?

**Comment by FendiTony777** [comment]
Sorry im idiot i posted issue on wrong page.
