### ISSUE TITLE
Stone block as Head and Item

### ISSUE THREAD

**Issue by Blazingshadow17** [dmulloy2/ProtocolLib#714]
**Describe the bug**
I use mythic mobs to make custom mobs, and libs disguises and skinner to disguise them. Libs disguises and skinner both require protocol lib. In 1.13.2 I made mobs with custom skins and they worked perfectly fine, with no issues through this exact same way. recently I updated to 1.14.4 and now all the mobs with custom skins spawn with there skin correctly except they have a stone block and their head and item, which sometimes turns to normal after a while. I sent this error to the developer of libs disguises and he said it was a bug in protocol lib.

**To Reproduce**
1. You need to download Mythic Mobs, libsdiguises, skinner, skinner lib, and protocol lib.
2. Create a skin for a mob and upload it to https://mineskin.org/
3. Plug the correct information into libs disguises custom skin folder and the skinner config, then apply the skin in Mythic Mobs on your created mob and spawn it in.
4. Then your mob will have a stone head and item (even if not given an item), and will crash the server when it attacks a player.

**Expected behavior**
It should spawn normally without a stone head or item, and not crash the server when attacking the players.

**Screenshots**
![Showcase](https://user-images.githubusercontent.com/45347492/68694704-3fd19600-053f-11ea-85cf-56c41a299b2a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Build #429

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
(This a the bug that I got once):
 https://pastebin.com/0SQdf9YZ

**Comment by MiniDigger** [comment]
if the author says this is a bug in protocollib, he should open a proper issue with easy and minimal reproduction steps (aka a couple lines of code)

this in itself isn't super helpful as you run 5 plugins that could interfere here, half of them are not even open source, so this is really not actionable. 
please get the author to do a proper bug report.

**Comment by dmulloy2** [comment]
Can you run `/protocol dump` and paste the output with pastebin? That might narrow it down a little.

It would also be helpful if @libraryaddict could provide some more info here.

**Comment by Blazingshadow17** [comment]
Here is the protocol dump: https://pastebin.com/eE0whbRr

**Comment by dmulloy2** [comment]
Yeah, I still don't really know what's going on there. It's probably some interaction between all 3 of those plugins which could be happening anywhere. We need a proper bug report from the libs disguises author

**Comment by libraryaddict** [comment]
Sorry for the lack of replies, I misread the bug report and likely isn't a PL bug.
The attribute thing is what I had been looking at, where the items is likely LD itself.
