### ISSUE TITLE
Got kick and very long error ~~"

### ISSUE THREAD

**Issue by CaoTrongThang** [dmulloy2/ProtocolLib#719]
First of all, sorry about my bad English ~~"

Im using protocolLib for spigot 1.12.2 and i got this error when log in to my server with minecraft 1.13.2 ~~", this is my log

[latest.log](https://github.com/dmulloy2/ProtocolLib/files/3881176/latest.log)

**Comment by dmulloy2** [comment]
Is this a problem when you log in with 1.12.2?

My guess is this is an interaction between ProtocolLib and ViaVersion

**Comment by CaoTrongThang** [comment]
Yes this is the problem when i log in with 1.12.2 ~~"
