### ISSUE TITLE
[ChatControl] Unhandled exception

### ISSUE THREAD

**Issue by Dasco** [dmulloy2/ProtocolLib#72]
Upon executing commands, I'm getting this error: [Server thread/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl

Server running git-Spigot-2f787db-501372f (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

The problem seems to be that the plugin chatcontrol and ProtocolLib aren't working together.(http://www.spigotmc.org/resources/chatcontrol.271/)

chatcontrol version: v5.0.8b
ProtocolLib version: 3.6.3-SNAPSHOT

Pastebin: http://pastebin.com/GKd6ebjf

**Comment by Dasco** [comment]
I tried earlier versions and found out that the ERROR starts in ProtocolLib version v5.0.0.
Atm I'm using ProtocolLib v4.5.7 for my spigot 1.8.3 server and it seems to work fine.
If you found/know what the problem is please let me know!

**Comment by dmulloy2** [comment]
You're using an outdated version of ProtocolLib. Grab the latest one here: http://ci.shadowvolt.com/job/ProtocolLib/
