### ISSUE TITLE
1.15 login issue / error (I know, I know!)

### ISSUE THREAD

**Issue by AeSix** [dmulloy2/ProtocolLib#723]
**Describe the bug**
With ProtocolLib installed (using the 4.5 candidate from Oct 30th, and previous builds) when attempting to connect to a 1.15 server, the client is given a message:
```
Exception Connecting:QuietException : Unexpected packet received during server login provess!
1b8f017b227472616e763c617465223a
```

**To Reproduce**
Create a Spigot 1.15 server
install ProtocolLib
attempt to join

**Expected behavior**
To be able to join the server I guess?

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://termbin.com/45a3
(I apologize for it not being pastebin, but termbin is so much simpler to use from command line)

**Additional context**
I know ProtocolLib isn't updated for 1.15 yet, but wanted to give the info to help with the process :)

To clarify, I was posting this issue primarily so others would see that they're not the only ones having an issue, and also to let dmulloy2 know there is indeed need for an update, and the info he may need.

**Comment by Jocke155** [comment]
Might be the same bug but I get this error when I try to login:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException`

**Comment by dmulloy2** [comment]
http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Please create new issues (or reopen this one) as necessary
