### ISSUE TITLE
1.15 issues

### ISSUE THREAD

**Issue by jiangdashao** [dmulloy2/ProtocolLib#726]
**Describe the bug**
There are some issues in 1.15:
1. #725 
 
2. PacketPlayInPlayerAction.EnumPlayerAction:
`START_SNEAKING` changed to `PRESS_SHIFT_KEY`
`STOP_SNEAKING` changed to `RELEASE_SHIFT_KEY`

3. PacketPlayOutEntityMetadata: Cannot write to watchable objects, but the class is same as 1.14
![image](https://user-images.githubusercontent.com/21152113/70677995-b93ddf00-1ccb-11ea-820a-bddcbfc9011b.png)

**Comment by tomijange** [comment]
I'll have a look at it

**Comment by dmulloy2** [comment]
#3 will require plugins to update, data watchers are no longer present in packets. it’s all handled by the metadata packet.
