### ISSUE TITLE
When will the 1.15 version be released?

### ISSUE THREAD

**Issue by Shesper** [dmulloy2/ProtocolLib#727]
I would like to know the progress.

**Comment by MiniDigger** [comment]
its open source, if you want progress, why dont you do it yourself? ;)

**Comment by dmulloy2** [comment]
should be out by tomorrow. it’s almost done, just working on a nbt issue

**Comment by dmulloy2** [comment]
code is ready, just dealing with more repository issues

**Comment by dmulloy2** [comment]
http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Please create new issues as necessary
