### ISSUE TITLE
protocollib for 1.15 plugin backwards compatibility

### ISSUE THREAD

**Issue by Janmm14** [dmulloy2/ProtocolLib#731]
This change does not fix compatibility with plugins build against older protocollib versions.

https://github.com/dmulloy2/ProtocolLib/commit/c893a3f11e4cfef21f1f924b464683139022aa97#diff-13f44211e209bf5790585f62157c932dR163-R165

I'd suggest to swap the name of the sneaking enums with their alias, so the pre-1.15 name is the Enum name.

**Comment by dmulloy2** [comment]
ah yeah that’ll do it. i’ll swap them

**Comment by dmulloy2** [comment]
should be fixed in https://github.com/dmulloy2/ProtocolLib/commit/e915fd0f9a1dfa446831aff6fd4e2e7a1cb10baa
