### ISSUE TITLE
InterceptInputBuffer error in chat?

### ISSUE THREAD

**Issue by yooniks** [dmulloy2/ProtocolLib#734]
Hey! Since I use: ListenerOptions.INTERCEPT_INPUT_BUFFER in my class that extends PacketAdapter I get this errors in the chat (and why is that displayed in the chat?)
error - https://user-images.githubusercontent.com/30025818/69365484-bd5e7a00-0c94-11ea-952f-0cfe877f665b.png
And the log: https://pastebin.com/raw/uXMHjcJx
I need it to be fixed ASAP.

**Comment by dmulloy2** [comment]
tracking this in #724
