### ISSUE TITLE
Problem 1.15.1

### ISSUE THREAD

**Issue by demon57730** [dmulloy2/ProtocolLib#740]
spigot 1.15.1
ProtocolLib v4.5.0 (new version)

the plugin does not work

log: https://textup.fr/391743yk

**Comment by bundabrg** [comment]
Did you use the dev build from: https://ci.dmulloy2.net/job/ProtocolLib

**Comment by demon57730** [comment]
yes
https://ci.dmulloy2.net/job/ProtocolLib/440/

**Comment by dmulloy2** [comment]
Try the newest build: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Should hopefully fix that error

**Comment by demon57730** [comment]
https://textup.fr/391952ep

the plugin does not work

**Comment by dmulloy2** [comment]
Figured it out. One of your plugins is including part of ProtocolLib in its own jar. Can you provide a list of plugins that use it?

**Comment by demon57730** [comment]
I will try to see which plugin is causing this problem

**Comment by demon57730** [comment]
problem solved it came from the cms plugin (mineweb) I had read the doc badly and said if error with ProtocolLib give another version

https://docs.mineweb.org/#liaison-un-serveur-par-d-faut
