### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by musicjaxx** [dmulloy2/ProtocolLib#741]
Hi, I keep getting this error when loading:

[ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!

I have no idea what this means, and it keeps spamming thousands of errors through the console.

**Comment by musicjaxx** [comment]
Nevermind, all fixed.

**Comment by dmulloy2** [comment]
@musicjaxx i am curious though, what was the issue?
