### ISSUE TITLE
play_server_open_sign_editor packet doesn't work anymore on 4.5.0

### ISSUE THREAD

**Issue by GovindasOM** [dmulloy2/ProtocolLib#743]
**Describe the bug**
play_server_open_sign_editor packet doesn't work anymore on 4.5.0, it does completely nothing and doesn't fire under normal conditions. it works right on 4.4.0.
**To Reproduce**
I think I cannot provide them, as I found this bug while using ProtocolLib in Skript, not a normal plugin. but just listen to this packet when placing a sign, it won't fire, also editing it does nothing.

**Expected behavior**

**Screenshots**

**Version Info**
ProtocolLib Version: ProtocolLib v4.5.0
Bukkit Version: 1.12.2-R0.1-SNAPSHOT
Server Version: git-Paper-1618 (MC: 1.12.2)
Java Version: 1.8.0_232

**Comment by Govindass** [comment]
still a problem in 4.5.1
