### ISSUE TITLE
NoSuchMethod 

### ISSUE THREAD

**Issue by PaulusDevelopus** [dmulloy2/ProtocolLib#744]
**Describe the bug**
The following exception occurs if I start the server: http://prntscr.com/qi91n1

**To Reproduce**
I dont know how to reproduce: the error occured suddenly

**Expected behavior**
I dont know exactly how the error occurs

**Screenshots**
http://prntscr.com/qi91n1

**Version Info**
/protocol wont work anymore, because of the error :/

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger
