### ISSUE TITLE
It says there's a new version ready for next reboot, I never gave permission for this

### ISSUE THREAD

**Issue by mrfloris** [dmulloy2/ProtocolLib#746]
Why is it telling me there's a new version ready to update on next restart, if i never gave permission for this?

```
global:
  # Settings for the automatic version updater
  auto updater:
    notify: false
    download: false
    
    # Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
 
  metrics: false
```

**Comment by MiniDigger** [comment]
Please post all relevant log lines.

**Comment by mrfloris** [comment]
```
[08:18:17] [Server thread/INFO]: [ProtocolLib] The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.
```

**Comment by MiniDigger** [comment]
Protocollib is using an ancient spigot update api
https://github.com/dmulloy2/ProtocolLib/blob/22c2a4abcc08f4069fe974737665e919112aa33a/src/main/java/com/comphenix/protocol/updater/SpigotUpdater.java#L93
https://www.spigotmc.org/threads/update-checking.264850/

it needs to be updated @dmulloy2

**Comment by dmulloy2** [comment]
Will get on that tonight, thanks.

Is there a better API to use?

**Comment by mrfloris** [comment]
> Will get on that tonight, thanks.
> 
> Is there a better API to use?

https://www.spigotmc.org/threads/update-checking.264850/ has more information about this topic

**Comment by dmulloy2** [comment]
so just that new url?

**Comment by MiniDigger** [comment]
Yes, new url, and it's just a get, not a post.

**Comment by mrfloris** [comment]
Thank you. It seems to work fine again.
