### ISSUE TITLE
Dropped items won't destroy on player clients when they stack.

### ISSUE THREAD

**Issue by YourPalJake** [dmulloy2/ProtocolLib#756]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
How can I possibly fix this bug, where if you drop items fast and throw them arround you it leaves an ghost entity on player clients, but when you drop them slowely it wont't

**API method(s) used**
The PacketAdapter onPacketSending

**Expected behavior**
Everytime an dropped item stacks it should destroy the old one.

**Code**
[https://github.com/AzortisCode/ProtocolVanish/blob/master/src/main/java/com/azortis/protocolvanish/visibility/packetlisteners/GeneralEntityPacketListener.java](https://github.com/AzortisCode/ProtocolVanish/blob/master/src/main/java/com/azortis/protocolvanish/visibility/packetlisteners/GeneralEntityPacketListener.java)

**Additional context**
[Here](https://www.youtube.com/watch?v=rd0aakfEqBk) a youtube video where the bug is shown.

**Comment by YourPalJake** [comment]
Somehow it does work with latest v4.5.1

**Comment by camohax** [comment]
I am having the same issue on my server as well.

**Comment by dmulloy2** [comment]
@camohax did you try it on 4.5.1?

**Comment by camohax** [comment]
@dmulloy2 Where do I get 4.5.1? I don’t see it on the GitHub

**Comment by dmulloy2** [comment]
@camohax https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by YourPalJake** [comment]
@dmulloy2 How do you think it got fixed actually?

**Comment by dmulloy2** [comment]
@YourPalJake honestly couldn’t tell ya. but if it works it works haha

**Comment by camohax** [comment]
Using latest build and this issue is still happening...

**Comment by YourPalJake** [comment]
That is disturbing dmulloy can you look into it?

**Comment by YourPalJake** [comment]
Its also currently doing this with EXP somehow it just doesn't wanna destroy entities

**Comment by alexis-evelyn** [comment]
this issue affects mobs/items/xp. Here's a video I made of the issue before I went to single out the plugin causing the issue. https://www.youtube.com/watch?v=r9KyM5cDe0o&feature=emb_title

**Comment by alexis-evelyn** [comment]
So, it turns out ProtocolVanish is what causes the issue. It just appears to be ProtocolLib as ProtocolVanish doesn't cause the bug when it's missing a dependency.
