### ISSUE TITLE
Error after reloading

### ISSUE THREAD

**Issue by Jeroenimoo0** [dmulloy2/ProtocolLib#76]
20.04 14:45:25 [Server] INFO git-Spigot-c3c767f-33d5de3 (MC: 1.8)
20.04 14:45:25 [Server] INFO Server:
20.04 14:45:25 [Server] INFO ProtocolLib v3.6.3-SNAPSHOT
20.04 14:45:25 [Server] INFO Version:
20.04 14:45:25 [Server] INFO ]
20.04 14:45:25 [Server] INFO added=false
20.04 14:45:25 [Server] INFO first=false
20.04 14:45:25 [Server] INFO decodeWasNull=false
20.04 14:45:25 [Server] INFO singleDecode=false
20.04 14:45:25 [Server] INFO cumulation=<null>
20.04 14:45:25 [Server] INFO closed=false
20.04 14:45:25 [Server] INFO injected=false
20.04 14:45:25 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@44e99eb0
20.04 14:45:25 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.NettyProtocolInjector@3c6ce9bc
20.04 14:45:25 [Server] INFO finishQueue=[]
20.04 14:45:25 [Server] INFO finishHandler=com.comphenix.protocol.injector.netty.ChannelInjector$4@b641222
20.04 14:45:25 [Server] INFO protocolEncoder=com.comphenix.protocol.injector.netty.ChannelInjector$3@2e5dba16
20.04 14:45:25 [Server] INFO vanillaEncoder=net.minecraft.server.v1_8_R1.PacketEncoder@7178bf65
20.04 14:45:25 [Server] INFO vanillaDecoder=net.minecraft.server.v1_8_R1.PacketDecoder@6cb547bc
20.04 14:45:25 [Server] INFO scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@42d4019a
20.04 14:45:25 [Server] INFO finalEvent=<null>
20.04 14:45:25 [Server] INFO currentEvent=<null>
20.04 14:45:25 [Server] INFO packetMarker={}
20.04 14:45:25 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=private io.netty.channel.Channel net.minecraft.server.v1_8_R1.NetworkManager.i], container=net.minecraft.server.v1_8_R1.NetworkManager@2e78d124, previous=null, current=null, previousLoaded=false, currentSet=false, forceAccess=true]
20.04 14:45:25 [Server] INFO originalChannel=[id: 0x1988b87d, /92.222.21.50:35089 => /94.23.40.218:25580]
20.04 14:45:25 [Server] INFO networkManager=net.minecraft.server.v1_8_R1.NetworkManager@2e78d124
20.04 14:45:25 [Server] INFO playerConnection=<null>
20.04 14:45:25 [Server] INFO playerName=<null>
20.04 14:45:25 [Server] INFO updated=<null>
20.04 14:45:25 [Server] INFO player=CraftPlayer{name=Jeroenimoo0}
20.04 14:45:25 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@610f3944
20.04 14:45:25 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@bc3c264[
20.04 14:45:25 [Server] INFO Sender:
20.04 14:45:25 [Server] INFO ]
20.04 14:45:25 [Server] INFO debug=false
20.04 14:45:25 [Server] INFO loginPackets=com.comphenix.protocol.injector.LoginPackets@7a75fa81
20.04 14:45:25 [Server] INFO minecraftVersion=(MC: 1.8.0)
20.04 14:45:25 [Server] INFO hasRecycleDistance=true
20.04 14:45:25 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3a97611d
20.04 14:45:25 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector@3c6ce9bc
20.04 14:45:25 [Server] INFO spigotInjector=<null>
20.04 14:45:25 [Server] INFO packetCreation=false
20.04 14:45:25 [Server] INFO phasePlayingCount=2
20.04 14:45:25 [Server] INFO phaseLoginCount=0
20.04 14:45:25 [Server] INFO knowsClientPackets=true
20.04 14:45:25 [Server] INFO knowsServerPackets=true
20.04 14:45:25 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4684c24c
20.04 14:45:25 [Server] INFO library=ProtocolLib v3.6.3-SNAPSHOT
20.04 14:45:25 [Server] INFO server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-c3c767f-33d5de3,minecraftVersion=1.8}
20.04 14:45:25 [Server] INFO reporter=com.comphenix.protocol.ProtocolLibrary$1@61e940fe
20.04 14:45:25 [Server] INFO classLoader=org.bukkit.plugin.java.PluginClassLoader@76726fa
20.04 14:45:25 [Server] INFO hasClosed=false
20.04 14:45:25 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@389d87e9
20.04 14:45:25 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@662f8080
20.04 14:45:25 [Server] INFO inputBufferedPackets=[]
20.04 14:45:25 [Server] INFO interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@467c8d0e
20.04 14:45:25 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.NettyProtocolInjector$4@19635a11
20.04 14:45:25 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector$5@3b083b26
20.04 14:45:25 [Server] INFO packetListeners=[PacketAdapter[plugin=TostiCore, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutSpawnEntityLiving[15, legacy: 24], PacketPlayOutPlayerInfo[56, legacy: 201], PacketPlayOutNamedEntitySpawn[12, legacy: 20], PacketPlayOutNamedSoundEffect[41, legacy: 62]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=TostiCore, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutUpdateSign[51, legacy: 130]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
20.04 14:45:25 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@61a89758
20.04 14:45:25 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@633ba855[
20.04 14:45:25 [Server] INFO manager:
20.04 14:45:25 [Server] INFO Dump:
20.04 14:45:25 [Server] INFO at java.lang.Thread.run(Thread.java:745)
20.04 14:45:25 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
20.04 14:45:25 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
20.04 14:45:25 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
20.04 14:45:25 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$9.run(ChannelInjector.java:809)
20.04 14:45:25 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.run(ChannelInjector.java:194)
20.04 14:45:25 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:252)
20.04 14:45:25 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
20.04 14:45:25 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
20.04 14:45:25 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
20.04 14:45:25 [Server] INFO java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
20.04 14:45:25 [Server] INFO Stack Trace:

Some other info, I use a custom class loader, it may have to do with this.
In my onDisable I use "ProtocolLibrary.getProtocolManager().removePacketListeners(this);"
I'll supply more info if i find something.

**Comment by dmulloy2** [comment]
You're using a fairly outdated version of ProtocolLib, grab the latest one here: http://ci.shadowvolt.com/job/ProtocolLib/

Regardless, it's generally a bad idea to reload because it causes errors like this.
