### ISSUE TITLE
NPE while creating a WrappedBlockData

### ISSUE THREAD

**Issue by TomCapelle** [dmulloy2/ProtocolLib#762]
**Describe the bug**
When i try to create a WrappedBlockData in order to make a MultiBlockChangeInfo, i get an unexpected NPE: http://p.tomcraft.fr/c10d11f.txt

**To Reproduce**
Just try a code like this: http://p.tomcraft.fr/520f3.png

**Expected behavior**
No NPE (This code used to work before (2 month ago, at most))

**Version Info**
https://pastebin.com/DzFhfQdm
I removed some private informations from the paste.

**Comment by dmulloy2** [comment]
Can you try this with an older version (like 4.4.0) and see if it still happens?

**Comment by TomCapelle** [comment]
I tired with version 4.4.0, and it didn't worked: https://i.helliotk.fr/cjpWM4G
