### ISSUE TITLE
Error + crash

### ISSUE THREAD

**Issue by MrValioBg** [dmulloy2/ProtocolLib#765]
**Describe the bug**
Server is starting and there is an error

**To Reproduce**
Sometimes server crashes and then the errors appears

**Expected behavior**
 i need u to fix it

**Screenshots**
https://pastebin.com/xR0s03gV

**Version Info**
https://pastebin.com/11dPCx5B

**Additional context**

**Comment by brnxx** [comment]
**I have the same problem as at com.comphenix.protocol.injector.netty**

Dev build: 4.5.1-SNAPSHOT-b445
Paperspigot 1.15.2

https://pastebin.com/ewKdTT9b

**Comment by dmulloy2** [comment]
@MrValioBg and/or @brnxx can you run `/protocol dump`  and paste the output on pastebin?
