### ISSUE TITLE
Connection to the server is lost

### ISSUE THREAD

**Issue by RandalZ15** [dmulloy2/ProtocolLib#766]
(I am Russian, I use a translator)

Hello, sometimes there is a problem on my server, about this happens once every 1-2 weeks. 

- Problem description:
The server is running, players are playing, nothing special, and suddenly the server kicks about 10% of all players from the server, and at the same time the connection to the server disappears.

- How do I usually solve it:
1. I turn off the server, and the "stop" command does not help, I just have to close the "Ctrl + C" screen and start a new one.
2. /task manager reload Photoclub, that is, restarting the plugin via AutoSaveWorld, helps for exactly 3-4 minutes, then the connection is lost again.

What's my question:
I use version Protocolib v4.4.0-SNAPSHOT-b390, server PaperSpigot 1.12.2 (version 1596) you may have already fixed it in new versions, I would like to ask only because of this, there is simply no information on the Internet at all about the problem, no matter how I search.

P.S. Sorry in advance, if incorrectly designed the theme.

**Comment by RandalZ15** [comment]
UPD: сегодня утром обновился до Protoclolib 4.5.0, проблема повторилась.
Что делать, как наконец решить её?

**Comment by dmulloy2** [comment]
Can you run `/protocol dump` and paste the output using pastebin?

**Comment by RandalZ15** [comment]
Да, извините, что не скинул сразу:
https://pastebin.com/VvbpBn9v

**Comment by RandalZ15** [comment]
> Вы можете запустить `/protocol dump`и вставить выходные данные с помощью pastebin?

Да, извини, что я не бросил его сразу 
https://pastebin.com/VvbpBn9v

**Comment by RandalZ15** [comment]
Прошу

> Вы можете запустить `/protocol dump`и вставить выходные данные с помощью pastebin?

Excuse me? The problem still torments me

> Can you run `/protocol dump` and paste the output using pastebin?

Excuse me? The problem still torments me
