### ISSUE TITLE
Error in Console with Kick

### ISSUE THREAD

**Issue by JamesBach93** [dmulloy2/ProtocolLib#768]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I dont know why i get the Error. But after delete ProtocolLib it works.
But after installing, i get some Errors when someone get kickt from this.

**Screenshots**
I dont have an Screenshot for this. But i put my Log with the Error here.
https://pastebin.com/CV0quEw8

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
- Minecraft Version: PaperSpigot 1.15.2 (84)
- ProtocolLib-4.5.1-20200111.185530-5

**Additional context**
The Error shows an Netty Epoll error. But after deinstall ProtocolLib, the Error dont happend.
But without this Plugin i cant run an Tabplugin. :/

**Comment by dmulloy2** [comment]
Does the error occur before or after someone gets kicked?

Also, can you run `/protocol dump` and paste that output on pastebin?

**Comment by JamesBach93** [comment]
Sometimes someone from my Users have this issue and when he is on the Server, he cant do anything. After maybe 1 Minute he get Kicked with the Kick Information (was kicked due to keepalive timeout!) And then the Console get Spamed with alot of Errors. 

Here is the Dumb: https://pastebin.com/8MqpM5cq

After deinstall it doesnt happend anymore. 
I test it for few days without ProtocolLib and it runs perfectly.
But i need for some Plugins. :/

**Comment by JamesBach93** [comment]
I get the Error today again.
Dump: https://pastebin.com/QGf2mif9
Error: https://pastebin.com/WpCE23xR

Greetings
