### ISSUE TITLE
Scoreboard team mode field is different.

### ISSUE THREAD

**Issue by VytskaLT** [dmulloy2/ProtocolLib#769]
**Describe the bug**
The scoreboard team packet mode field is different (on 1.8 it's integer 1 and on other versions, it's 0)

**To Reproduce**
1. Create a simple team with Bukkit API
2. Create a Play.Server.SCOREBOARD_TEAM PacketContainer
3. Write the integer 0 to 3 (which is to add a player)
4. Write string 0 to the team name
5. Write collection 0 to a list with the players' name
6. Send the packet to a player on 1.8 (it won't work)
7. Send the packet to a player on a newer version (it will work)
8. Change it so it sets the integer 1 instead of 0 to 3
9. Send the packet to a player on 1.8 (it will work)
10. Send the packet to a player on a newer version (it won't work)

**Expected behavior**
ProtocolLib should change the field based on the players' version before sending the packet

**Screenshots**
The code that works on 1.8: https://imgur.com/a/PYSie5Z
The code that works on newer versions: https://imgur.com/a/vrmOLRp

**Version Info**
https://pastebin.com/RyhBj6kk

**Comment by MiniDigger** [comment]
well, duh, the protocol changes between versions.
its not protocollibs task to accommodate for those changes, protocollib knows nothing about those changes. it just allows you to modify whatever packet classes are present at runtime. to find the right fields and values is your task as a developer.
