### ISSUE TITLE
FieldAccessException thrown on non-existing field but it should exist

### ISSUE THREAD

**Issue by comniemeer** [dmulloy2/ProtocolLib#77]
I think you fixed this until it was broken: https://github.com/dmulloy2/ProtocolLib/commit/bfb0683b1ff40654cc203606e2433d73338d2a0a#diff-8fde7c3f842bc4fb99b5e8f0843cf477R196
I want to get the name of the player in this packet:

    final ProtocolManager protocolManager = ProtocolLibrary.getProtocolManager();
    
    protocolManager.addPacketListener(new PacketAdapter(hgl, PacketType.Play.Server.PLAYER_INFO) {
        @Override
        public void onPacketSending(PacketEvent event) {
            String name = event.getPacket().getStrings().read(0);
        }
    });
But it simply throws an error in the console until a player joins the server: http://pastebin.com/zXgfn232
Line 30 in my plugin mentioned in the stacktrace is:

    String name = event.getPacket().getStrings().read(0);
Hope you get fixed that soon again!
Thanks in advance!

**Comment by dmulloy2** [comment]
This isn't an error on ProtocolLib's part. There isn't a string in the player info packet, it was replaced by PlayerInfoData, which can be accessed with ````packet.getPlayerInfoData()````

**Comment by comniemeer** [comment]
Okay, thank you and sorry for the inconvenience.
