### ISSUE TITLE
LinkageError

### ISSUE THREAD

**Issue by Longehh** [dmulloy2/ProtocolLib#777]
**Describe the bug**
When restarting or starting the server, 2/5 restarts produce a LinkageError.

`> [10:37:32 WARN]: at java.lang.Thread.run(Thread.java:748)
> [10:37:32 WARN]: [ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!
> [10:37:32 WARN]: [ProtocolLib] If you're getting this error for other reasons, please report it!
> [10:37:32 WARN]: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
> [10:37:32 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:193)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:142)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:999)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:313)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:291)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:204)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:909)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:840)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:759)
> [10:37:32 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:660)
> [10:37:32 WARN]: at java.lang.Thread.run(Thread.java:748) `

**To Reproduce**
1. Restart or Start your server.
2. Join the server, and you'll be kicked, and console will spam with the stack trace above.

**Expected behavior**
To be able start and join the server without being kicked and the LinkageError happening.

**Version Info**
ProtocolLib Version: ProtocolLib v4.5.0
Bukkit Version: 1.8.8-R0.2-SNAPSHOT

**Comment by dmulloy2** [comment]
Try this: https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger

**Comment by Longehh** [comment]
I've looked through all plugins, and nowhere has any protocolib files shaded in, and the ones that implement it use the correct way as specified by the API Documentation.
