### ISSUE TITLE
Is it safe to remove all the ASM related code?

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [dmulloy2/ProtocolLib#778]
I am trying to port this plugin to a java implementation that does not support ASM, so I need to remove all the code related to ASM.
I found these two places using ASM using github search:

# TileEntityAccessor
https://github.com/dmulloy2/ProtocolLib/blob/4baa4aa7243e7a682963590d43b6e616d43bd853/src/main/java/com/comphenix/protocol/wrappers/nbt/TileEntityAccessor.java#L68

I think it is safe to remove findMethodsUsingASM() and use findMethodUsingCGLib() instead.

# StructureCache
https://github.com/dmulloy2/ProtocolLib/blob/4baa4aa7243e7a682963590d43b6e616d43bd853/src/main/java/com/comphenix/protocol/injector/StructureCache.java#L127

Not to compile the structure modifier seems to be safe, but I'm not sure

**Comment by dmulloy2** [comment]
You should be good. Performance and backwards compatibility will suffer, but it should still function. I am curious though why removing ASM is necessary/desirable?
