### ISSUE TITLE
Can't use protocol lib

### ISSUE THREAD

**Issue by KidCanada7** [dmulloy2/ProtocolLib#785]
I just installed protocol lib again for the matrix anti-cheat but I can't do /matrix related commands, I have the latest version and I'm sure this is caused by protocol lib because 
matrix is giving no errors but protocol lib is going crazy In the CMD. Here are the logs. 
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/4288890/latest.log)

**Comment by biglou36** [comment]
Follow the report format.

**Comment by MiniDigger** [comment]
matrix doesnt work because you dont use paper, check the log...
you cant use craftbukkit, nor should you, its not meant to be used anymore.
