### ISSUE TITLE
LinkageError with Mohist

### ISSUE THREAD

**Issue by PinkFloyd1213** [dmulloy2/ProtocolLib#787]
**Describe the bug**
When I launch my server, which is running on Mohist, this error message is displayed repeatedly. If a player attempts to connect, he is kicked instantly.

**To Reproduce**
1. Install a Mohist Server (https://mohist.red/)
2. Install various plugin and Protocolib
3. Start the server and connect a player on it
4. Look at the console and enjoy ! 

**Screenshots**
![unknown](https://user-images.githubusercontent.com/31860086/76254310-8b295600-624c-11ea-8007-377c7381eb6b.png)

**Version Info**
https://pastebin.com/1uH5hKWk

**Comment by MiniDigger** [comment]
Protocollib is written for craftbukkit servers.
you cant just throw it on a forget server and expect it to work without issues.

can you try reproducing this without GadgetsMenu, LibsDisguises, SuperVanish, HolographicDisplays  and TrollCommandsPlusPlus (or any combination of those?)
