### ISSUE TITLE
Error enabling plugin ProtocolLib

### ISSUE THREAD

**Issue by Jackiedk100** [dmulloy2/ProtocolLib#79]
Hi, I have a bungeecord server, and other servers, but I want to run ServerListPlus, on my bungeecord server, and ServerListPlus can be enabled, but ProtocolLib can't be enabled on my bungeecord server, I got this error:

Error enabling plugin ProtocolLib

Here is my bungeecord log

http://pastebin.com/uxGfdmju

**Comment by dmulloy2** [comment]
ProtocolLib is a Bukkit plugin.  Bukkit plugins can't run on BungeeCord.

**Comment by Jackiedk100** [comment]
But what will this so said?
http://www.spigotmc.org/resources/serverlistplus.241/

NOTE: You need the LATEST DEVELOPMENT BUILD of ProtocolLib for it to work on Spigot, download it here: http://ci.shadowvolt.com/job/ProtocolLib/
