### ISSUE TITLE
Error filtering reports

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#790]
Using the following:
Paper (1.12.2) Build 1618
Protocollib: 4.4.0 Build 403

Recently caught this in console:
https://pastebin.com/raw/z5z8hBvs

**Comment by dmulloy2** [comment]
Try 4.5.0, I think this was fixed

**Comment by andrewkm** [comment]
Thanks :)
It is indeed fixed, didn't think the newer versions worked on 1.12.2.
