### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by ELMATT33** [dmulloy2/ProtocolLib#795]
hi, i have this error in my console, with the last version.
![e3](https://user-images.githubusercontent.com/48900320/77324449-0f80dc00-6d17-11ea-8350-2fba0a9dc5dc.PNG)

**Comment by MiniDigger** [comment]
please fill out the issue template...

what protocollib version? what java version?

**Comment by ELMATT33** [comment]
version 4.5.0 and Java 8

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger
