### ISSUE TITLE
Can't reload

### ISSUE THREAD

**Issue by hugo4715** [dmulloy2/ProtocolLib#798]
After reloading my server, when a player leave there is an error and players can't reconnect/ping.
Error Log: https://pastebin.com/uP69yr8a
Dump: https://pastebin.com/jh8B9eWs

**Comment by MiniDigger** [comment]
you cant reload protocollib. you should reload invidivual plugins or just restart your server like any sane admin.

**Comment by hugo4715** [comment]
I am creating my own plugins and restarting my server is slowing my tests. 
Your advice yould be to use something like plugman and reload only my plugin?

**Comment by hugo4715** [comment]
After researching a little more i found a fix using ProtocolLib Reload Fixer 
https://www.spigotmc.org/resources/protocollib-reload-fixer.66860/

Maybe it could be added officially (｡◕‿◕｡) 
Thanks for helping

**Comment by MiniDigger** [comment]
No.
The reload command is bad and shouldnt be used.
For dev purposes, you should look into hotswapping but ye, alternatively plugman is kinda acceptable.

**Comment by dmulloy2** [comment]
I'm intrigued that someone made that reload fixer plugin. But yeah reloading is not currently supported and will never be recommended
