### ISSUE TITLE
"" Could not load 'plugins/ProtocolLib.jar' in folder 'plugins' ""

### ISSUE THREAD

**Issue by Slumzy** [dmulloy2/ProtocolLib#806]
**Describe the bug**
ProtocolLib.jar fails to start as a plugin, I get the following error on console.

I just downloaded MarkElf's NoCheatPlus and needed this to go with it. NoCheatPlus downloaded fine.

**To Reproduce**
Got the .jar from [https://github.com/dmulloy2/ProtocolLib/releases/download/4.5.0/ProtocolLib.jar](url)
Copied it into my plugins folder
Started server
Chucked out an error (pasted below)

**Expected behavior**
For it to install without any further complications.

**Evidence**
https://pastebin.com/embed_iframe/QrvGR5dM OR:

> -02.04 02:23:06 [Server] ERROR Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'
02.04 02:23:06 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
02.04 02:23:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:167) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
02.04 02:23:06 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
02.04 02:23:06 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_191]
02.04 02:23:06 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_191]
02.04 02:23:06 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_191]
02.04 02:23:06 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_191]
02.04 02:23:06 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_191]
02.04 02:23:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:155) ~[patched_1.15.2.jar:git-Paper-155]
02.04 02:23:06 [Server] INFO ... 5 more

**Comment by MiniDigger** [comment]
delete the jar and download it again, its corrupted
