### ISSUE TITLE
Protocol plugin wont start

### ISSUE THREAD

**Issue by Arwindd** [dmulloy2/ProtocolLib#808]
**Describe the bug**
Plugin wont start

**Expected behavior**
https://pastebin.com/jmHQtMBe

**Version Info**
ProtocolLib v4.5.0

**Comment by dmulloy2** [comment]
Try this? https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger

**Comment by seangaon** [comment]
i did try the latest version of the dev build and still same problem

**Comment by dmulloy2** [comment]
Did you try looking through your plugins and seeing if any were including ProtocolLib?

**Comment by seangaon** [comment]
![image](https://user-images.githubusercontent.com/31382102/79119990-44d39380-7dc4-11ea-83e6-2262ca14eca5.png)

**Comment by seangaon** [comment]
How can i fix it?

**Comment by seangaon** [comment]
Hello??

**Comment by moritzruth** [comment]
@seangaon Have you done what @dmulloy2 suggested?

> One of your plugins is misbehaving and including part of ProtocolLib in its own jar. Your best bet is to go through the largest jars in your plugins folder as it will contain a lot more classes than it should. Search for com/comphenix/protocol folders in the jars using a tool like 7-zip, WinRar, or Vim.

[source](https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger)
