### ISSUE TITLE
ProtocolLib fails to load 

### ISSUE THREAD

**Issue by DBCooper123** [dmulloy2/ProtocolLib#816]
**Describe the bug**
Plugin is failed to load upon installing.

**To Reproduce**
Normal installation procedures.

**Expected behavior**
For the plugin to load correctly.

**Screenshots**
N/A

**Version Info**
https://pastebin.com/V3rjUMJ0

**Additional context**
Ask below.

**Comment by MiniDigger** [comment]
your version is ancient, please update and test again.
