### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by BakiDance** [dmulloy2/ProtocolLib#819]
**Describe the bug**
Possible duplicate of #813, but this is happening under different conditions. I'm having players who, upon attempting to join the server, are disconnection with a "timed out" message. While this occurs, my in-game chat is flooded with ProtocolLib warnings. This doesn't happen to everyone.

**To Reproduce**
1. Player attempts to join the server.

**Expected behaviour**
Player is able to join the server successfully, not connect and time out upon logging in.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/43658058/80055728-00dd3e80-84e8-11ea-812c-b720ab916e69.png)
Message logged in-game when this user attempts to join.

**Version Info**
https://pastebin.com/ZA4k6zcB Dump

**Additional context**
https://pastebin.com/mz9UkmAZ latest.log output when this occurs

**Comment by MiniDigger** [comment]
is it just that single player?

make a backup of his player data and delete it and see if he can join again.
I think he has an invalid item in his inv.
