### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Ninjablader9** [dmulloy2/ProtocolLib#82]
Using Build #118

ProtocolLib Plugins: Player Count Message, HD Displays

Recieving these two errors: 

An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.nio.channels.ClosedChannelException

**Comment by dmulloy2** [comment]
Those errors wouldn't stop you from connecting to the server.  If there is an error, it's probably hidden. Set ````debug=true```` in the server.properties and paste the stacktrace with pastebin.

**Comment by Ninjablader9** [comment]
I updated Java to Java 8 and can connect to my server now, but the message is still being spamemd across the console and I recieved: http://pastebin.com/2VLyuMfw when I joined.

**Comment by dmulloy2** [comment]
That's an issue with HolographicDisplays.  You should use the latest one from [here](http://dev.bukkit.org/bukkit-plugins/holographic-displays/) and remove the patch.
