### ISSUE TITLE
Kicking Player while commandspamming -> ConcurrentModificationExeption 

### ISSUE THREAD

**Issue by Nononitas** [dmulloy2/ProtocolLib#821]
I programmend a plugin which edits players PacketPlayOutTabComplete with ProtocolLib. On spigot.jar its working fine and won't kick me. If I use paper instead it will kick me. Paper said that it was not a mistake on their part and it was probably due to ProtocolLib
My question is now if I did something wrong and why does the error occur.

**API method(s) used**
TAB_COMPLETE Listener

**Expected behavior**
Editing the tabcomplete

**Code**
https://pastebin.com/R4MmPxtB

**Additional context**
What behaviour is observed:

If you spam a command in example "/gd claim extend" it will kick you with the following exception:
https://pastebin.com/Mzi9abav
Steps/models to reproduce:

Spam "/gd claim extend" you need the permission griefdefender.*
Plugin list:

ProtocolLib 4-5.1-SNAPSHOT-b447, PL-Hide-Pro (code part is given above), griefdefender-1.2.5c, Luckperms

**Comment by dmulloy2** [comment]
Your code looks fine. It may be worth trying to make your listener async (setting ListenerOptions.ASYNC) and seeing if that helps. I know chat messages are handled async

**Comment by Nononitas** [comment]
> 
> 
> Your code looks fine. It may be worth trying to make your listener async (setting ListenerOptions.ASYNC) and seeing if that helps. I know chat messages are handled async

Thanks its working now
