### ISSUE TITLE
Error using IScoreboardCriteria with scoreboard objectives.

### ISSUE THREAD

**Issue by ofirtim** [dmulloy2/ProtocolLib#822]
Hi, I've been having an issue I am struggling with for the past day and so, tried to find a solution to this error and see if there's anything I can do about it.
I am trying to create a custom scoreboard system, but for some weird reason I am getting the same error over and over again, tried playing with the versions between protocol lib from the newest to the oldest that functions with 1.8, and tried switching versions for the version 1.8.R3 a few times (spigot used btw), Is there any way by mistake that my code 

Error console:
https://pastebin.com/bYAT4F3v

Line used:
https://pastebin.com/PyEJDxVg

Error caused by:
packet.getChatComponents().write(0, WrappedChatComponent.fromText(displayName));

**Comment by dmulloy2** [comment]
Try just using the displayName instead of wrapping it in a chat component?

(Additionally you would use packet.getStrings().write)

**Comment by ofirtim** [comment]
The old and nice weird error of DecoderException...
![download](https://user-images.githubusercontent.com/5520619/80852827-5629f600-8c34-11ea-9d81-1c1e313203c8.png)
