### ISSUE TITLE
Only allow one version to join...?

### ISSUE THREAD

**Issue by Xp10d3** [dmulloy2/ProtocolLib#823]
Hey, this isn't a problem, but rather a question. So basically when I have ProtocolLib running on my server, it allows all versions to join, which can be a problem since blocks don't show up as the actual textures itself. Ex. Honey Blocks in 1.14.4 look like slime blocks or path blocks, and slime blocks look like path blocks or grass blocks in 1.13.2, etc. I don't want that to happen. Since LibsDisguises requires ProtocolLib, but I only want 1.15.2. clients to join my server, how do I disable allowing ALL versions to join? Thanks!
(Yes I am running the latest build of ProtocolLib)
-Eltik/Xp10d3

**Comment by iso2013** [comment]
ProtocolLib does not allow other versions to join. This functionality would be from another plugin

**Comment by dmulloy2** [comment]
It sounds like you're using something like ViaVersion in addition to ProtocolLib. The solution is to remove one of those

**Comment by Xp10d3** [comment]
Oops! My bad. I see. Thanks for the help!
