### ISSUE TITLE
Server 'hangs' on a player login (sometimes)

### ISSUE THREAD

**Issue by Bonista** [dmulloy2/ProtocolLib#826]
**Describe the bug**
Sometimes when a player logins, server doesn't allow a login and times out with this spamming in console:
https://pastebin.com/padLkiRR

**To Reproduce**
Not very reproducible :/ It is very random, in my case occurring on a player login (maybe a relog).

**Expected behavior**
To allow players to join, and not time out on login.

**Version Info**
https://pastebin.com/NVJWDW1H

**Additional context**
Looking around to see whether this bug is known, I found this issue: https://github.com/dmulloy2/ProtocolLib/issues/724

Although the error that I am getting is not the same error as the original issue creator's, it is almost identical to the ones posted by others on that issue (java.lang.IllegalArgumentException: java.lang.ClassCastException) which seems to be triggered by a login. From looking at the other stacktraces, it seems to be present on every version of Spigot (1.8.8 in one case, 1.15.1 in another), ViaVersion or not.

**Comment by Bonista** [comment]
Seems like this is the same issue:
https://github.com/dmulloy2/ProtocolLib/issues/791

**Comment by Bonista** [comment]
@dmulloy2 Could this be a concurrency issue? I'm not familiar with netty but I don't see how DECODE_BUFFER.invoke(vanillaDecoder, ctx, byteBuffer, packets) would have an illegal argument randomly.

**Comment by Bonista** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/724#issuecomment-627948182

This is how you replicate this

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/b04fca83243272e828608c7f9423ef52b75a8bd2
