### ISSUE TITLE
Placeholder problem with glow

### ISSUE THREAD

**Issue by Alv5ro** [dmulloy2/ProtocolLib#829]
**Describe the bug**
When using the glow plugin, The placeholder %player_name% won't work when the colours move onto it.

**To Reproduce**
1. Go to 'Animations.yml'
2. paste in https://pastebin.com/fMUYA8zx
3. Try it out

**Expected behavior**
The playername stays loaded as the PAPI placeholder rather than literally %player_name%.

**Screenshots**
![Minecraft Screenshot 2020 05 06 - 11 11 08 00](https://user-images.githubusercontent.com/57922931/81165702-5a367a80-8f8a-11ea-9010-8c76a76566fc.png)

![Minecraft Screenshot 2020 05 06 - 11 13 12 99](https://user-images.githubusercontent.com/57922931/81165839-99fd6200-8f8a-11ea-97f2-9266188e9496.png)

**Version Info**
ProtocolLib Version: ProtocolLib v4.5.0
Bukkit Version: 1.15.2-R0.1-SNAPSHOT
Server Version: git-Paper-143 (MC: 1.15.2)
Java Version: 1.8.0_181
HEXT version: 1.10.9

**Additional context**

**Comment by dmulloy2** [comment]
Sir this is ~~an arby's~~ ProtocolLib, not PlaceholderAPI
