### ISSUE TITLE
2 hours and I give up - Installation

### ISSUE THREAD

**Issue by rhapidfyre** [dmulloy2/ProtocolLib#83]
I am using MythicMobs, which uses LibsDisguise, which uses ProtocolLib.
I have updated everything, including the latest Spigot.

This is the problem I am having, and it's not allowing disguses to work:
http://pastebin.com/mTRupJYx

I do not have a plugin.yml to add the "depend:" line, as Spigot 1.8.3 doesn't have a plugin.yml file.

I added it as a regular plugin, uploading it to the /plugins/ folder, and it shows up and I can run commands, but LibsDisguse says "null" for each of the /slash options, and the disguses don't work. The error above traces back to this plugin.

**Comment by dmulloy2** [comment]
You're using the wrong version of ProtocolLib. Grab the latest one here: http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by rhapidfyre** [comment]
That worked perfectly. I guess I had been using bad links. Thanks!
