### ISSUE TITLE
Protocollib causing disconnects moving me back to my bungee lobby

### ISSUE THREAD

**Issue by MaveTheCorgi** [dmulloy2/ProtocolLib#832]
**Describe the bug**
I am running a bungee server and have a 1.13.2 server that I try to connect to. I get through and join the 1.13 server but after a few minutes I get "kicked" by getting the message that the server went down (which isn't the case). When I remove protocollib it works.

**To Reproduce**
1. Connect to any server through proxy that has protocollib installed

**Expected behavior**
I want to be able to log in and not get kicked after a few minutes.

**Screenshots**

**Version Info**
https://pastebin.com/BQT5mavu

**Additional context**
I tested this by removing all plugins and adding it 1 by 1, when I added protocollib it started happening again.

**Comment by MaveTheCorgi** [comment]
Please let me know if you want me to change anything to my issue if something is wrong with it. Please help me as this is the only place I can get support.

**Comment by dmulloy2** [comment]
Try removing these plugins 1 by 1, but leave ProtocolLib installed:

```LibsDisguises by [libraryaddict, Byteflux, Navid K.]
ChatControl by [kangarko]
Boss by [kangarko]
VotingPlugin by [Ben12345rocks]
SuperVanish by [MyzelYam]
LiteBans by [Ruan]
React by [cyberpwn, Puretie, PsychopathNextdoor]
BKCommonLib by [bergerkiller, lenis0012, timstans, bubba1234119, KamikazePlatypus, mg_1999, Friwi]```
