### ISSUE TITLE
Updater misinforms and seemingly cannot auto update

### ISSUE THREAD

**Issue by libraryaddict** [dmulloy2/ProtocolLib#835]
**Describe the bug**
The updater successfully checks for an update, after which it informs the user that the update has been downloaded and will be processed when the server restarts.

This is false on two levels.
The first is that there was no download, the second is that the update option is false in config.

**To Reproduce**
Start server and wait a second

**Expected behavior**
An update to either be downloaded, or a better message to be informed

**Additional context**
I also don't believe the update system works either.

You can fetch and download updates from Github itself, you can see how I implemented it in my own project here. This shouldn't be much of an issue as you've already done some releases on Github.

Github should be used, especially as you may hit SpigotMC's Cloudflare protection.

https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/utilities/updates/LDGithub.java#L51

If using Bukkit's update system to replace jars, then it's worth noting that the downloaded jar must be placed in "plugins/updates/" folder, and have the same name as the jar it will be replacing.

**Comment by MiniDigger** [comment]
this may has been caused by a downtime at spigots side, does it still occur?

**Comment by libraryaddict** [comment]
No like, I don't even see code to download the jar.

**Comment by MiniDigger** [comment]
https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/updater/BukkitUpdater.java#L153

**Comment by libraryaddict** [comment]
Even then it doesn't look like it exposes the download itself, and I'm concerned about issues with cloudflare

**Comment by MiniDigger** [comment]
thats why I said no downloading. the current spigot updater already doesnt download, so no real regression for most of the users.

**Comment by dmulloy2** [comment]
The Spigot updater can't do automatic downloads by design. I'll go change the message to reflect that.
