### ISSUE TITLE
PacketPlayOutTabComplete error

### ISSUE THREAD

**Issue by lackoSK** [dmulloy2/ProtocolLib#836]
**Describe the bug**
Our client is getting an error with PacketPlayOutTabComplete

**To Reproduce**
It's hard to reproduce, it happens only sometimes. Got this when trying to tab-complete the /gamemode... command.

**Expected behavior**
I think it's pretty clear. It should complete. 

**Version Info**
Running ProtocolLib 4.5.0

**Additional context**
Here's the error: https://pastebin.com/tZ44S5Nj

**Comment by MiniDigger** [comment]
update paper, you are using an ancient version...
also update chatcontrol, its most likely not compatible with your minecraft version or smth

**Comment by lackoSK** [comment]
Hey!

ChatControl is compatible with 1.15.2
I'll get back to you when I will know something more around the server version

Thanks

**Comment by lackoSK** [comment]
Okay, our client is getting the error in the **latest** version of the paper

**Comment by games647** [comment]
[Minecraft 1.13](https://github.com/dmulloy2/PacketWrapper/commit/84d4c3d9f12a21f9bbe5dc88889d66be6208fe5a#diff-30f52613d0e9bb5694bc9b2f74392c37) changed this packet to no [longer contain an array of strings](https://wiki.vg/Protocol#Tab-Complete_.28clientbound.29). The developer of ChatControl needs to adopt to this change.

**Comment by lackoSK** [comment]
Thanks
