### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by Frostfire25** [dmulloy2/ProtocolLib#837]
https://pastebin.com/pRkrf6A3
Jar- Hyperion Cannoning Jar 1.8.8
Version - Latest

**Comment by Bonista** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/724#issuecomment-627948182

**Comment by Zacary00** [comment]
Did you solved?

**Comment by dmulloy2** [comment]
Tracking this in #724
