### ISSUE TITLE
protocolLib crash

### ISSUE THREAD

**Issue by eNAWAF** [dmulloy2/ProtocolLib#838]
Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_252
  Server:
    git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[04:32:39] [Netty Epoll Server IO #3/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: java.lang.ClassCastException@1ee4e0c) occured in com.comphenix.protocol.injector.netty.ChannelInjector@5ac4b0d6.[m
[04:32:39] [Netty Epoll Server IO #3/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: java.lang.ClassCastException@1ee4e0c

**Comment by eNAWAF** [comment]
hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@138fb0b8
        reporter=com.comphenix.protocol.ProtocolLib$1@742b5784
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-"4c7641d",minecraftVersion=1.8.8}
        library=ProtocolLib v4.5.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4598dc34
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=25
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@23c20f26
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4a483dfa
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@421646e4
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@68fc1b6f[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@11b5d3c7
      player=com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$499756d7@71cfa428
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_8_R3.NetworkManager@79204543
      originalChannel=[id: 0x2f427ec7, /127.0.0.1:33204 :> /127.0.0.1:612]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_8_R3.NetworkManager.channel], container=net.minecraft.server.v1_8_R3.NetworkManager@79204543, previous=[id: 0x2f427ec7, /127.0.0.1:33204 :> /127.0.0.1:612], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@56dffb44, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=java.lang.ThreadLocal$SuppliedThreadLocal@5a3dfb53
      vanillaDecoder=us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler@21cca70a
      vanillaEncoder=us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler@7ac37321
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@23c20f26
      processor=com.comphenix.protocol.injector.NetworkProcessor@663d3cbb
      injected=true
      closed=false
      cumulation=<null>
      singleDecode=false
      decodeWasNull=false
      first=false
      added=true
    ]
  Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_252
  Server:
    git-PaperSpigot-"4c7641d" (MC: 1.8.8)

come again and again and again

**Comment by Zacary00** [comment]
Did you solved?

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/b04fca83243272e828608c7f9423ef52b75a8bd2
