### ISSUE TITLE
ProtocolLib Crash my Server

### ISSUE THREAD

**Issue by Zacary00** [dmulloy2/ProtocolLib#839]
[16:49:07] [Netty Epoll Server IO #3/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: java.lang.ClassCastException@78777bd3) occured in com.comphenix.protocol.injector.netty.ChannelInjector@6c9ac9cd.[m
[16:49:07] [Netty Epoll Server IO #3/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: java.lang.ClassCastException@78777bd3
  	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:304)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:206)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
  	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
  	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
  	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
  Parameters: 
    io.netty.buffer.UnpooledHeapByteBuf@41cc0a73[
      alloc=UnpooledByteBufAllocator(directByDefault: true)
      array={0,47,-64,9,109,99,46,122,97,114,108,97,110,100,46,101,115,0,49,55,57,46,54,46,53,54,46,54,57,0,56,48,54,57,97,53,53,54,53,52,57,102,51,102,56,98,56,48,102,98,54,102,99,52,57,56,101,54,53,52,51,56,0,91,123,34,110,97,109,101,34,58,34,116,101,120,116,117,114,101,115,34,44,34,118,97,108,117,101,34,58,34,101,119,111,103,73,67,74,48,97,87,49,108,99,51,82,104,98,88,65,105,73,68,111,103,77,84,85,52,79,84,89,48,77,122,73,53,79,68,89,122,79,67,119,75,73,67,65,105,99,72,74,118,90,109,108,115,90,85,108,107,73,105,65,54,73,67,73,53,89,122,65,51,78,50,85,51,90,87,69,49,89,109,77,48,89,122,65,50,89,106,73,120,90,106,86,106,78,68,108,109,79,68,65,51,77,122,86,106,78,67,73,115,67,105,65,103,73,110,66,121,98,50,90,112,98,71,86,79,89,87,49,108,73,105,65,54,73,67,74,85,97,71,86,69,89,87,70,121,97,87,78,114,77,106,103,105,76,65,111,103,73,67,74,122,97,87,100,117,89,88,82,49,99,109,86,83,90,88,70,49,97,88,74,108,90,67,73,103,79,105,66,48,99,110,86,108,76,65,111,103,73,67,74,48,90,88,104,48,100,88,74,108,99,121,73,103,79,105,66,55,67,105,65,103,73,67,65,105,85,48,116,74,84,105,73,103,79,105,66,55,67,105,65,103,73,67,65,103,73,67,74,49,99,109,119,105,73,68,111,103,73,109,104,48,100,72,65,54,76,121,57,48,90,88,104,48,100,88,74,108,99,121,53,116,97,87,53,108,89,51,74,104,90,110,81,117,98,109,86,48,76,51,82,108,101,72,82,49,99,109,85,118,78,106,73,50,90,109,81,49,77,122,107,119,90,68,99,119,77,68,69,122,89,122,65,53,77,122,65,51,79,87,73,53,77,109,78,105,78,122,107,122,79,71,77,53,77,122,74,108,79,87,89,122,89,84,103,48,90,106,73,122,78,50,69,51,78,122,108,107,79,68,107,51,89,106,78,108,79,71,77,120,78,50,70,108,77,67,73,75,73,67,65,103,73,72,48,75,73,67,66,57,67,110,48,92,117,48,48,51,100,34,44,34,115,105,103,110,97,116,117,114,101,34,58,34,121,66,118,65,112,75,115,79,79,43,111,75,120,118,81,85,109,98,90,72,51,101,78,82,104,72,106,112,82,71,66,75,103,55,119,114,116,97,84,116,83,121,67,71,97,122,80,81,88,117,73,74,87,52,56,83,106,67,84,102,72,106,105,80,69,81,53,70,109,120,97,50,109,79,117,71,77,70,89,106,79,114,65,99,71,72,120,89,50,68,118,103,121,78,108,89,47,56,109,114,114,109,74,47,112,70,122,120,114,48,85,55,50,74,113,69,50,80,111,74,99,68,101,98,99,57,107,72,81,72,66,117,48,68,104,77,90,115,51,102,55,49,102,55,55,115,47,89,49,78,84,107,52,78,43,71,118,98,43,80,121,121,102,74,54,102,114,101,67,114,74,117,106,50,115,103,76,102,78,54,109,75,82,112,57,106,68,104,122,110,55,71,103,66,68,71,48,82,49,101,88,43,100,72,71,75,121,111,113,110,110,66,71,106,103,115,89,121,83,85,51,106,112,80,114,79,99,50,43,77,75,115,119,109,78,74,76,65,90,71,117,56,84,111,55,83,115,90,80,104,74,47,111,71,113,67,110,75,98,47,105,88,83,75,71,105,98,83,114,53,49,80,65,118,88,81,85,102,103,82,54,49,81,51,81,65,120,110,53,66,83,120,43,71,122,87,52,68,56,118,57,71,119,89,52,109,119,104,101,50,114,98,112,43,48,107,79,65,83,109,103,97,105,55,84,65,89,101,53,50,103,85,99,53,56,106,102,114,110,82,117,80,111,51,54,68,116,66,99,48,114,70,109,81,114,99,112,75,111,43,109,80,79,118,73,48,52,90,112,120,54,72,76,68,43,69,116,79,56,80,69,54,120,117,70,57,71,69,82,51,99,52,108,103,78,70,117,119,80,119,114,51,54,78,122,52,121,67,101,106,69,111,80,83,114,119,55,53,82,75,79,81,79,108,83,110,70,120,74,101,88,85,112,109,89,121,68,51,115,107,90,87,53,51,119,99,68,88,110,122,54,56,87,111,70,69,74,57,84,79,57,72,57,48,122,83,101,98,43,102,47,86,50,73,65,100,77,118,50,48,81,108,51,90,121,85,86,114,90,49,51,90,71,120,85,87,87,87,89,104,82,116,84,109,120,66,84,109,111,107,88,108,54,47,115,101,111,104,111,85,104,82,90,119,120,100,57,118,72,120,68,107,79,75,69,117,52,122,109,116,74,57,116,88,69,119,49,72,66,77,85,103,107,88,55,118,49,52,115,90,121,89,104,69,55,54,112,57,83,108,72,115,119,76,72,109,54,65,87,86,66,76,49,52,49,74,105,111,83,66,100,74,86,117,55,103,83,69,67,51,67,71,110,113,67,89,107,51,67,103,85,52,72,89,119,85,85,90,88,115,75,82,68,117,69,109,80,100,70,78,118,82,80,53,114,56,89,48,106,119,54,55,97,101,74,88,103,72,114,72,114,65,70,104,99,49,81,51,43,82,83,114,43,104,51,99,84,73,80,119,76,80,119,100,83,55,98,77,118,98,47,99,85,92,117,48,48,51,100,34,125,93,99,-35,2,0,14,77,97,114,105,111,112,114,111,49,48,49,56,121,116,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
      tmpNioBuf=<null>
      refCnt=1
      readerIndex=0
      writerIndex=1239
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
      swappedBuf=<null>
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2fd0ca9f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1bf0bb0a
        packetListeners=[PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=3], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PlaceholderAPI, sending=ListeningWhitelist[priority=HIGHEST, packets=[CHAT[class=PacketPlayOutChat, id=15]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=45]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=45], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=42], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=8], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=41], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=38], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], TRANSACTION[class=PacketPlayInTransaction, id=7], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], SETTINGS[class=PacketPlayInSettings, id=5], CHAT[class=PacketPlayInChat, id=3], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=35], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=31], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], ABILITIES[class=PacketPlayInAbilities, id=25], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@66cea1e9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7a5f317e
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@53f29898
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4dc44107
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5e1670bf
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@794f934e
        reporter=com.comphenix.protocol.ProtocolLib$1@5dc17ec2
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-"4c7641d",minecraftVersion=1.8.8}
        library=ProtocolLib v4.5.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7593ad92
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=true
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3c6c1526
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@49b4bfbc
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@60847d6e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@6c9ac9cd[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@360472d5
      player=com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$6f8cb7b5@35802965
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_8_R3.NetworkManager@143e3234
      originalChannel=[id: 0x76555d70, /127.0.0.1:60201 :> /127.0.0.1:26200]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_8_R3.NetworkManager.channel], container=net.minecraft.server.v1_8_R3.NetworkManager@143e3234, previous=[id: 0x76555d70, /127.0.0.1:60201 :> /127.0.0.1:26200], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5e8f1a91, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=java.lang.ThreadLocal$SuppliedThreadLocal@6af0db24
      vanillaDecoder=us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler@f3afbdc
      vanillaEncoder=us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler@60afeb21
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@3c6c1526
      processor=com.comphenix.protocol.injector.NetworkProcessor@2a97f432
      injected=true
      closed=false
      cumulation=UnpooledHeapByteBuf(ridx: 0, widx: 1239, cap: 2048)
      singleDecode=false
      decodeWasNull=false
      first=false
      added=true
    ]
  Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_252
  Server:
    git-PaperSpigot-"4c7641d" (MC: 1.8.8)

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/commit/b04fca83243272e828608c7f9423ef52b75a8bd2
