### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by SlimaKCoder** [dmulloy2/ProtocolLib#84]
http://ci.shadowvolt.com/ is offline and i can't download latest build.

**Comment by dmulloy2** [comment]
Oh, it's actually down this time. Unfortunately I'm on mobile so I can't fix it, but for the time being you can download the latest build from the repo: http://repo.dmulloy2.net/content/groups/public/com/comphenix/protocol/ProtocolLib/3.6.3-SNAPSHOT/ProtocolLib-3.6.3-20150520.234247-2.jar

**Comment by SlimaKCoder** [comment]
I can't compile ProtocolLib O.o
```
Failed to execute goal on project ProtocolLib: Could not resolve dependencies for project com.comphenix.protocol:ProtocolLib:jar:3.6.3-SNAPSHOT: Failure to find org.spigotmc:spigot:jar:1.8.3-R0.1-SNAPSHOT in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
```

**Comment by dmulloy2** [comment]
You have to have Spigot installed to your local repo in order to compile ProtocolLib.

**Comment by dmulloy2** [comment]
Website is back up.
