### ISSUE TITLE
lost connection: Internal Exception: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by Yoloman0013** [dmulloy2/ProtocolLib#841]
**Describe the bug**
When user joins 1.8.8 server with 1.15.2 version (only with 1.15 and 1.8 has been tested) and tries to hit mob user will get kicked out with reason lost connection: Internal Exception: java.io.IOException: Broken pipe
**To Reproduce**
1. Go to '1.15.2 version in 1.8.8 server'
hit mob and you will get kicked with reason lost connection: Internal Exception: java.io.IOException: Broken pipe there isnt any other errors

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/3WHWveC6

**Additional context**
Server version 1.8.8, taco spigot fork - atomspigot

**Comment by dmulloy2** [comment]
Try using ProtocolLib 3.6.5 from here: https://www.spigotmc.org/resources/protocollib.1997/history

and let me know if it still happens
