### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by Zezzin** [dmulloy2/ProtocolLib#842]
![Image 5-19-20 at 5 20 PM](https://user-images.githubusercontent.com/65634460/82391111-7ae0e480-9a0e-11ea-875e-23dce4dbb686.jpg)
The plugin is cause an issue where it should an X over the connection bars... but players can still join.. I removed all other plugins I was using and pin pointed it to this one.. not sure what the issue could be

**Comment by MiniDigger** [comment]
share your code? fill out the issue template?

**Comment by Zezzin** [comment]
This?
`global:
  # Settings for the automatic version updater
  auto updater:
    notify: true
    download: false
    
    # Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
 
  metrics: true
  
  # Automatically compile structure modifiers 
  background compiler: true
  
  # Disable version checking for the given Minecraft version. Backup your world first!
  ignore version check: 
  
  # Override the starting injecting method
  injection method: 
  
  # Whether or not to enable the filter command
  debug: false
  
  # Whether or not to print a stack trace for every warning
  detailed error: false
  
  # The engine used by the filter command
  script engine: JavaScript
  
  suppressed reports:'

**Comment by Zezzin** [comment]
Sorry, I'm new to this, is this what you mean?
`global:
  # Settings for the automatic version updater
  auto updater:
    notify: true
    download: false
    
    # Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
 
  metrics: true
  
  # Automatically compile structure modifiers 
  background compiler: true
  
  # Disable version checking for the given Minecraft version. Backup your world first!
  ignore version check: 
  
  # Override the starting injecting method
  injection method: 
  
  # Whether or not to enable the filter command
  debug: false
  
  # Whether or not to print a stack trace for every warning
  detailed error: false
  
  # The engine used by the filter command
  script engine: JavaScript
  
  suppressed reports:`

**Comment by Zezzin** [comment]
`global:
  Settings for the automatic version updater
  auto updater:
    notify: true
    download: false
    
     Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
 
  metrics: true
  
   Automatically compile structure modifiers 
  background compiler: true
  
   Disable version checking for the given Minecraft version. Backup your world first!
  ignore version check: 
  
   Override the starting injecting method
  injection method: 
  
   Whether or not to enable the filter command
  debug: false
  
   Whether or not to print a stack trace for every warning
  detailed error: false
  
   The engine used by the filter command
  script engine: JavaScript
  
  suppressed reports:`

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by Zezzin** [comment]
https://pastebin.com/9YwjgBwL

**Comment by holyaurora21** [comment]
im also having this same issue? 
https://pastebin.com/8AZ7gGW9
https://ibb.co/k4Wv4zT

**Comment by dmulloy2** [comment]
@Zezzin try removing these plugins (not ProtocolLib) one by one:

```
WorldGuardExtraFlags by [isokissa3]
LibsDisguises by [libraryaddict, Byteflux, Navid K.]
VotingPlugin by [Ben12345rocks]
Negativity by [[Elikill58, RedNesto]]
SuperVanish by [MyzelYam]
HolographicDisplays by []
MythicMobs by [Xikage AKA Ashijin]
CoreArena by [kangarko]
GCore by [GuillaumeVDN]
```

**Comment by Zezzin** [comment]
Ok :/ I'll have to wait until I the all my players log off... if its one the plugins clashing with ProtocolLib what would I do then? Also @holyaurora21 do you have any of the same plugins?

**Comment by holyaurora21** [comment]
@Zezzin we got some that are the same. ArmorStandTools, ChatManager, Citizens, ClearLag, CoreProtect, CraftingStore, Essentials, EssentialsChat, EssentialsSpawn, HeadsPlus, Holograms, LibsDisguises, Multiverse-Core, Negativity, PermissionsEx*, PlotSquared, ProtocolLib, Vault, VoxelSniper, WorldEdit, WorldGuard
version:git-Paper-77 (MC: 1.15.2)

**Comment by Zezzin** [comment]
So coreprotect, libs, negativity, essentials, clearlag, armor standtools, and essentials... I confirmed its not LibsDisguises.. so it must be another one of those

**Comment by holyaurora21** [comment]
@zezzin we added negativity recently.

**Comment by Zezzin** [comment]
@holyaurora21 could you try removing that to see if its the issue? or I can try it a bit later if you can't

**Comment by holyaurora21** [comment]
@zezzin we updated paper to latest, LibsDisquises also had a update also (i got paid version tho)
removed negativity. Added https://github.com/Updated-NoCheatPlus/NoCheatPlus/releases instead as a replacement. 
No connection is now solved for us.

**Comment by holyaurora21** [comment]
not sure if the update to libsdisquises solved the issue or the replacment of negativity or the update of paper. I did it all at once sorry

**Comment by Zezzin** [comment]
Oh awesome! Im using paper so that shouldn't be the issue, and I removed lib disguises entirely so that shouldn't be it either.. I guess it was negativity... so weird.. thanks for the help!

**Comment by Zezzin** [comment]
Are you sure why this would cause this issue? @dmulloy2

**Comment by holyaurora21** [comment]
@Zezzin glad its working for us both :) i have no clue why its negativity, they do however have a discord server (the negativity one) might be wize to tell them also about this issue....
it maybe something they also need to sort

**Comment by holyaurora21** [comment]
https://www.spigotmc.org/resources/ac-negativity-spigot-1-7-1-15-sponge-bungeecord-velocity.48399/ 
it says on the page 'KNOWN ISSUE: Error COULD appear with ProtocolSupport plugin !'
https://discord.gg/KHRVTX2

**Comment by Zezzin** [comment]
Hmm so I guess they're aware of it.. odd.. seems like such a random combo of plugins to cause an issue like that

**Comment by holyaurora21** [comment]
@Zezzin just have to keep a eye on the page and hope they update, use another anticheat for now and hope shiz works :D 
https://www.spigotmc.org/wiki/anti-cheat-list-bukkit-and-spigot-1-15-x/

**Comment by Elikill58** [comment]
Hello,
I'm here because this issue correspond exactly to my problem.
I'm the owner and main dev of Negativity, and i don't know why but the problem of No connection appear only with Negativity & ProtocolLib.
This is the code that i'm using, to know what i'm doing wrong: https://github.com/Elikill58/Negativity/blob/master/src/com/elikill58/negativity/spigot/packets/protocollib/ProtocollibPacketManager.java

**Comment by Elikill58** [comment]
I finally find the problem. I just fix it, it will be include in next version ! (It's because i was loading Handshake packets)
I think you can close this because it appear because of my plugin.

**Comment by Elikill58** [comment]
I update the plugin, which fix the problem.
