### ISSUE TITLE
Bad packets 

### ISSUE THREAD

**Issue by Krazytrain** [dmulloy2/ProtocolLib#844]
Trying to get an updated anit cheat for our bungee server and we hit a problem, i opened a test server added all the plugins there an removed protocollib and people could connect again to it. Please could you have a look into it as anti cheat plugin is kind of a must when you own a bungee server. 

17:10:34
[SC4R] <-> ServerConnector [Lobby] has connected
WARNING 17:10:34
[SC4R] <-> ServerConnector [Lobby] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Kick 0 Protocol LOGIN Direction TOCLIENT
INFO 17:10:34
[SC4R] disconnected with: Exception Connecting:DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Kick 0 Protocol LOGIN Direction TOCLIENT @ io.netty.handler.codec.MessageToMessageDecoder:98
[SC4R] -> UpstreamBridge has disconnected
[SC4R_] <-> ServerConnector [Lobby] has disconnected

**Comment by dmulloy2** [comment]
So is the anticheat Spigot/Paper side or Bungee side?

**Comment by Krazytrain** [comment]
The anti cheat plugin goes on bungee server for the messages to ping though out an on the spigot server too to catch them.

**Comment by Krazytrain** [comment]
Btw forgot to say this before but i joined with optifine then i turned it off an still got kicked with out anything.

**Comment by Krazytrain** [comment]
Any info one what this is an why its happening? Because of of right now we have no anti cheat as when we have it installed it dont let anyone on the server.

**Comment by Krazytrain** [comment]
Any more info going to be shared about this as it still dont work
