### ISSUE TITLE
ProtocolLib i can't use playerpipeline in my own plugin (add-before method)

### ISSUE THREAD

**Issue by JavaInteger** [dmulloy2/ProtocolLib#847]
I am the developer of an anticrash, i can't add my own decoder before spigot's decoder cause of protocollib, when i try this protocollib or my plugin isnt working.

**Comment by MiniDigger** [comment]
well, others manage to do that, so its not an general issue. whats your code?

**Comment by JavaInteger** [comment]
i just add a decoder before the mc decoder (in players pipeline)

**Comment by dmulloy2** [comment]
Best I can do is point you to where we do our injecting: https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/injector/netty/ChannelInjector.java#L265
