### ISSUE TITLE
EncoderException when sending packet

### ISSUE THREAD

**Issue by IM-IgniteDEV** [dmulloy2/ProtocolLib#849]
**Describe the question**
Alright, so i use ProtocolLIB + PacketWrapper and when I send a packet to player it kick him with error " Internal Exception: Io.netty.handler.codec.EncoderException: java.lang.NullPointerException", 
in the console all i can see is 
[17:30:17 ERROR]: java.lang.NullPointerException
[17:30:17 INFO]: IgniteDEV lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

Version of minecraft: 1.13.2

**Expected behavior**
I want to send metadata with item to itemframe.

**Code**
![image](https://user-images.githubusercontent.com/31209154/82919991-08748500-9f77-11ea-8f5e-0ca1d3c5cc3e.png)

**Comment by dmulloy2** [comment]
You're going to want to use the data watcher [registry](https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/wrappers/WrappedDataWatcher.Registry.html#getItemStackSerializer-boolean-) along with a [data watcher object](https://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/wrappers/WrappedDataWatcher.WrappedDataWatcherObject.html). The item stack will also probably have to be wrapped in an optional (I forget exactly when they made that change, it might have been 1.13)

**Comment by IM-IgniteDEV** [comment]
Yea, but how can i do that if the Serializer is not going to take it?

**Comment by IM-IgniteDEV** [comment]
![image](https://user-images.githubusercontent.com/31209154/82991311-c5a9c000-9ffd-11ea-8206-6de346d9d340.png)


I had code like that before, but this is old screen, i change serializer to Integer and made another Serializer for Itemstack and i got exception about unknown datatype for serializer.
