### ISSUE TITLE
Could not find entity trackers for CraftPlayer (IllegalArgumentException)

### ISSUE THREAD

**Issue by xtomyserrax** [dmulloy2/ProtocolLib#856]
Hey, Im getting this error when a player joins and I try to getEntityTrackers but this is only happening to me on Paper and not on Spigot. Is there a problem in my code? (the other day you just saved my life). This is the error: https://pastebin.com/1aGeFnqt

For this testings I used: latest ProtocolLib version (4.5.1), latest paper version and latest spigot version.

This is line 131:
```java
if (ProtocolLibrary.getProtocolManager().getEntityTrackers((Entity) playerhidden).contains(playersonline))
```

And this is the entire method:

```java
	public static void hidePlayerPacketLevel(Player playersonline, Player playerhidden) {

		if (playersonline == null || playerhidden == null)
			return;
		try {
			if (ProtocolLibrary.getProtocolManager().getEntityTrackers((Entity) playerhidden).contains(playersonline))
				ProtocolLibrary.getProtocolManager().updateEntity((Entity) playerhidden, Collections.singletonList(playersonline));
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
```

I mean player is just joining the server so yeah maybe could be that an entity id still doesnt exist? But why in spigot its working fine? Sorry if Im doing something horrible, if you know how I can fix it please let me know!

Thanks!!

**Comment by dmulloy2** [comment]
Does this only happen when they’re first logging in?

**Comment by xtomyserrax** [comment]
Just when player joins the server. Then, that code is executed and works perfectly

**Comment by dmulloy2** [comment]
Talked to the Paper guys, they think the tracker is not supposed to contain the player in the join event. So I'm not really sure what the right solution is, but this is expected behavior (TM)

**Comment by xtomyserrax** [comment]
Oh :(
Well according to them they try to mantain support for spigot plugins and by this behaviour they are breaking it. They say Paper supports all spigot plugins with the exception of devs trying to break this support, Im 100% not trying to break it :/
I wanted to be sure that it wasnt a bug I made and a bug from ProtocolLib.
Thank you and thanks for contacting them! Ill have to remove this feature for paper servers but will mantain it for spigot ones then

**Comment by electronicboy** [comment]
as discussed on the paper discord;

Entities are not in the world tracker until after the join event, that should apply to spigot too, the only real behavioral difference with that event is that on CB/Spigot, if you do teleport in there, you'll be added to the world earlier, causing the tracker to be set before it really should be, causing that leak; That specifically is not an issue on paper, which is likely what has changed to cause your issue; There is no /real/ workaround here given that this is only really a side-effect from an issue created by CB

**Comment by electronicboy** [comment]
This isn't an area of plugins at all, this is internal implementation detail, and CB leaking the tracker early *was* causing other issues

**Comment by xtomyserrax** [comment]
Hey ty for the response. Any tip of how I could workaround it? Because my actual problem is that I actually need to do some stuff when player joins, I could delay setting the player on vanish then ¿?
