### ISSUE TITLE
Unable to intercept client packet

### ISSUE THREAD

**Issue by CenturaPVP** [dmulloy2/ProtocolLib#857]
When I connect to a bungeecord server a massive error in my console,  java.lang.IllegalArgumentException: java.lang.ClassCastException@69d485c8
04.06 21:47:57 [Server] INFO at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
04.06 21:47:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.06 21:47:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
04.06 21:47:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:510)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
04.06 21:47:57 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
04.06 21:47:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
04.06 21:47:57 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
04.06 21:47:57 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
04.06 21:47:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
04.06 21:47:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
04.06 21:47:57 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
04.06 21:47:57 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
04.06 21:47:57 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
04.06 21:47:57 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
04.06 21:47:57 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
04.06 21:47:57 [Server] INFO at java.lang.Thread.run(Thread.java:748)
04.06 21:47:57 [Server] INFO Dump:
04.06 21:47:57 [Server] INFO Parameters:
04.06 21:47:57 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@3503431c[
04.06 21:47:57 [Server] INFO memoryAddress=139866896125968
04.06 21:47:57 [Server] INFO recyclerHandle=io.netty.util.Recycler$DefaultHandle@326651e9
04.06 21:47:57 [Server] INFO chunk=Chunk(666703c7: 1%, 49152/16777216)
04.06 21:47:57 [Server] INFO handle=4611686018427389953
04.06 21:47:57 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
04.06 21:47:57 [Server] INFO offset=8192
04.06 21:47:57 [Server] INFO length=2048
04.06 21:47:57 [Server] INFO maxLength=2048
04.06 21:47:57 [Server] INFO cache=io.netty.buffer.PoolThreadCache@2068e9f0
04.06 21:47:57 [Server] INFO tmpNioBuf=<null>
04.06 21:47:57 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
04.06 21:47:57 [Server] INFO refCnt=1
04.06 21:47:57 [Server] INFO readerIndex=0
04.06 21:47:57 [Server] INFO writerIndex=1238
04.06 21:47:57 [Server] INFO markedReaderIndex=0
04.06 21:47:57 [Server] INFO markedWriterIndex=0
04.06 21:47:57 [Server] INFO maxCapacity=2147483647
04.06 21:47:57 [Server] INFO ]
04.06 21:47:57 [Server] INFO manager:
04.06 21:47:57 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@373a9017[
04.06 21:47:57 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@34e60c6a
04.06 21:47:57 [Server] INFO packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=3]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], FLYING[class=PacketPlayInFlying, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=82]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]]]
04.06 21:47:57 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@56e4cd67
04.06 21:47:57 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@50bcd5e6
04.06 21:47:57 [Server] INFO interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@33e54dce
04.06 21:47:57 [Server] INFO inputBufferedPackets=[]
04.06 21:47:57 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@37648284
04.06 21:47:57 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@471beefa
04.06 21:47:57 [Server] INFO hasClosed=false
04.06 21:47:57 [Server] INFO classLoader=org.bukkit.plugin.java.PluginClassLoader@6406c4bf
04.06 21:47:57 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@71be101a
04.06 21:47:57 [Server] INFO server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-79a30d7-acbc348,minecraftVersion=1.12.2}
04.06 21:47:57 [Server] INFO library=ProtocolLib v4.5.0
04.06 21:47:57 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7b4f67ed
04.06 21:47:57 [Server] INFO knowsServerPackets=true
04.06 21:47:57 [Server] INFO knowsClientPackets=true
04.06 21:47:57 [Server] INFO phaseLoginCount=0
04.06 21:47:57 [Server] INFO phasePlayingCount=7
04.06 21:47:57 [Server] INFO packetCreation=false
04.06 21:47:57 [Server] INFO spigotInjector=<null>
04.06 21:47:57 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6f138435
04.06 21:47:57 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@55405abd
04.06 21:47:57 [Server] INFO hasRecycleDistance=true

**To Reproduce**
1. Go on server selector
2. Click on kitpvp
3. See error

This only happens when you're on a version that the server isn't on, but I have all the via plugins.

I am using the latest version of protocollib

**Comment by dmulloy2** [comment]
Update to 4.5.1

**Comment by CenturaPVP** [comment]
ok thank you
