### ISSUE TITLE
Plugin using Protocollib breaks vanilla and custom damages from other items

### ISSUE THREAD

**Issue by Kubson6969** [dmulloy2/ProtocolLib#867]
I'm having a very serious problem with protocollib it, disables damage from vanilla weapons and for custom weapons like MMoitems/QuantumRPG. Today it was working completely fine then I restarted my server and protocololib didn't show any error but error I mentioned started.

My server: Paper 1.15.2 _(We alsto tried using spigot 1.15.2)_

My plugin list in case you ask:
![githubplugin](https://user-images.githubusercontent.com/62093469/84621996-a1752c80-aea1-11ea-8adb-4822e58057c5.png)

_How do I know it's protocollib?_  
- Well I had to download all my plugins and use a local server to test and start deleting one by one (delete one start server and see if the problem remains if not repeat with another plugin) until I deleted protocollib. I tried **4.4.0**, **4.5.0** and **4.5.1** none of them worked. We also tried deleting some other plugins that could cause any incompatibility, but it still doesn't make sense because yesterday it was working and today till afternoon, the only thing we changed was our Anti-bot plugin we update it, then we tried to confirm without the bot plugin to see if was causing any incompatibility. But the problem persisted until I decided to get here.

It was working fine, and as I say, it doesn't make sense that by restarting the server with no changes  this problem appears with Protcollib, wooden swords for example only do 1 damage the same with the others like diamond sword doing 2 damage and the critic particles no longer come out. Then if I delete the plugin everything comes. We have been using Protocollib since we started the server and it is the first time that we have this problem.

**Comment by dmulloy2** [comment]
it’s probably your anti bot plugin

**Comment by Kubson6969** [comment]
> it’s probably your anti bot plugin

it's not, we tried without it too
