### ISSUE TITLE
Add Enum EntityPose.CROUCHING

### ISSUE THREAD

**Issue by TheCalypso** [dmulloy2/ProtocolLib#871]
**Is your feature request related to a problem? Please describe.**
Can you add this enum: EntityPose.CROUCHING | net.minecraft.server.v1_15_R1.EntityPose in EnumWrappers because Mojang added this in 1.14 and it allows to have the position of the player

**Comment by moritzruth** [comment]
I tried to add a new wrapper for it, but I couldn't make it :(

**Comment by lewysDavies** [comment]
Please see my comment on this issue:
https://github.com/dmulloy2/ProtocolLib/issues/871
