### ISSUE TITLE
Kicking players out from server

### ISSUE THREAD

**Issue by Slaand** [dmulloy2/ProtocolLib#88]
With last spigot, some players can get random kick from server.
Its an error http://pastebin.com/dVruXNRu

**Comment by dmulloy2** [comment]
I can't seem to reproduce this. Can you provide some more information on the environment and circumstances?

**Comment by Slaand** [comment]
This problem has appeared in last spigot 1.8.7, and I have no idea what is the source of the problem.

**Comment by Slaand** [comment]
Stop, maybe It's not a protocollib's problem.
Last time I see errors from my chat plugin, called MineverseChat. Its an error from bungeecord http://gyazo.com/f5a0f39629f8d3811be9c4c026eade7f

**Comment by dmulloy2** [comment]
ProtocolLib isn't a Bungee plugin. Do you still get ProtocolLib errors in your Spigot console?

**Comment by dmulloy2** [comment]
If this is an issue with ProtocolLib, I'd like to get this fixed for the 3.6.4 release.
