### ISSUE TITLE
V4.5.1 warning that 1.15.2 hasn't been tested, even though it has support

### ISSUE THREAD

**Issue by HandyHat** [dmulloy2/ProtocolLib#883]
**Describe the bug**
On server start up, ProtocolLib warns that MC version 1.15.2 hasn't been tested.
```
[18:34:05] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.1
[18:34:05] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.15.2) has not yet been tested! Proceed with caution.
```

**To Reproduce**
Start-up 1.15.2 server with ProtocolLib V4.5.1

**Expected behaviour**
No warning to be shown because V4.5.1 has support for 1.15.2

**Screenshots**
N/A

**Version Info**
https://pastebin.com/EU3aAaKG

**Additional context**
N/A

**Comment by dmulloy2** [comment]
You can safely ignore that warning.

(it's fixed in https://github.com/dmulloy2/ProtocolLib/commit/658da31d46f3573b69b9d9d7fef5ec990dd987c9, but don't update to that unless you're using 1.16)
