### ISSUE TITLE
plz update to 1.16.1

### ISSUE THREAD

**Issue by Stoniasawsome** [dmulloy2/ProtocolLib#885]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 plz update to 1.16.1

**Comment by ClientKitty** [comment]
This is a duplicate

**Comment by Wumfie** [comment]
[https://github.com/dmulloy2/ProtocolLib/issues/880](url)
