### ISSUE TITLE
IndexOutOfBounds Exception that soft bans players when using new nether movement mobs/enchants/items.

### ISSUE THREAD

**Issue by tkn0** [dmulloy2/ProtocolLib#890]
**Describe the bug**
An IndexOutOfBounds Error kicks players when they use the new nether items I believe.
**To Reproduce**
1. Install protocol lib onto the latest spigot for 1.16.1.
2. Use a strider or soul speed.
3. After some time you should be soft banned by the exception.
**Expected behavior**
Nothing, all nether movement items function as normal.

**Screenshots**
https://www.youtube.com/watch?v=6QJOvf2WqNg&t=1s

**Version Info**
Latest dev build #467
**Additional context**
I was testing on an anti-cheat testing server, but the dev of the anti-cheat was in close communication and told me that this bug was with protocol lib.

**Comment by tkn0** [comment]
This seems to occur when you just walk on soul soil also

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by tkn0** [comment]
I will contact the ac dev to have him look into it as I don't believe I have permissions.
