### ISSUE TITLE
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_16_R1.DimensionManager exists in class PacketPlayOutRespawn.

### ISSUE THREAD

**Issue by MrKorvic** [dmulloy2/ProtocolLib#893]
**Describe the bug**
When attempting to play the respawn packet to a player, ProtocolLib fails to find the v1_16_R1 DimensionManager field.

**To Reproduce**
1. Get ProtocolManager
2. Create a PacketContainer with PacketType.Play.Server.RESPAWN
3. Write data to the packet's dimensions using packet#getDimensions#write. This can even be done using the player's current WorldEnvironment ID and a fieldIndex of 0.
4. Observe FieldAccessException in the console.

**Expected behavior**
Should set the packet's dimension to the one provided.

**Screenshots**
https://i.imgur.com/M4JcJdP.png
https://i.imgur.com/VaqqBlJ.png

**Version Info**
https://pastebin.com/8xJL2Ctd

**Comment by dmulloy2** [comment]
It got wrapped in a resource key. Looking into a good way to handle those.

**Comment by mirolm** [comment]
As i looked into [here ](https://wiki.vg/Protocol#Respawn)it seems that in 1.16.1 packet id of the respawn packet changed to 0x3B.

![image](https://user-images.githubusercontent.com/9135358/86782923-57c6ce80-c068-11ea-8514-6ad44469719c.png)
