### ISSUE TITLE
Messed up inventories

### ISSUE THREAD

**Issue by NinjaSplat** [dmulloy2/ProtocolLib#90]
Whenever I'm using ProtocolLib, items in players' inventories look as if they were cleared, but when clicking on a random slot in the inventory, a random item from their inventory comes up, yet everything disappears again. Can you fix this?

**Comment by dmulloy2** [comment]
Errors like these are generally not ProtocolLib's fault. It's likely that this is an issue with another plugin, more specifically a plugin that is using ProtocolLib. Try doing a binary search with plugins using ProtocolLib and see if that fixes the issue.

**Comment by dmulloy2** [comment]
If this is an issue with ProtocolLib, I'd like to get this fixed for the 3.6.4 release.

**Comment by dmulloy2** [comment]
Closed due to lack of information and reproducibility.
