### ISSUE TITLE
Problems with CombatLogX

### ISSUE THREAD

**Issue by NanoxGG** [dmulloy2/ProtocolLib#902]
I contacted the CombatLogX dev to report a bug that happens when I hit a player, and yes it was part of CombatLogX, but also on the log shows WARNs from ProtocolLib, the dev of CLX told me to report this bug, so here I am, here you have the log:
https://mcpaste.io/7824bee52448bfda

**Comment by MiniDigger** [comment]
this is not a protocollib issue, its an issue in interactivechat
