### ISSUE TITLE
Invalid plugin.yml Paper 1.16.1

### ISSUE THREAD

**Issue by marvinej** [dmulloy2/ProtocolLib#904]
**Describe the bug**
The plugin.yml is invalid so the plugin will not load.

**To Reproduce**
Install Build 472 on paper 1.16.1

**Expected behavior**
Plugin should load

**Screenshots**
http://hastebin.net/evolasepew.sql

**Version Info**
Build 472 - unable to provide output from command as plugin will not load

This server is running Paper version git-Paper-82 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by DeJayDev** [comment]
`Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)` 

It appears that you downloaded (or uploaded) an invalid jar file. Can you try to re download from an official source?

**Comment by marvinej** [comment]
i downloaded it from your build server for 1.16

**Comment by MiniDigger** [comment]
just delete and try again

**Comment by marvinej** [comment]
did that. Using build 472 from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Still getting this: http://hastebin.net/ayawopakuq.sql

**Comment by marvinej** [comment]
Same thing for build 467.

**Comment by DeJayDev** [comment]
Where are you uploading to/what are you uploading with? I'm pretty sure if you're using Pterodactyl panel the files getting corrupted in transit.

**Comment by marvinej** [comment]
Ok the issue does seem to be with the WinSCP client upload which is strange because it worked fine with other plugins i uploaded. This is using AMP from cubecoders. I used wget to update it from the back end for now. I'll contact cubecoders to figure out what the deal is with this.
