### ISSUE TITLE
LinkageError on CatServer with OpenJ9

### ISSUE THREAD

**Issue by f0rb1d** [dmulloy2/ProtocolLib#908]
**Describe the bug**
CatServer on OpenJ9 spams LinkageError in console.

**To Reproduce**
1. Install openjdk 8 with OpenJ9 JVM.
2. Grab the latest CatServer release from [here](https://github.com/Luohuayu/CatServer/releases/tag/20.07.06).
3. Install ProtocolLib v4.5.1.
4. Being flooded by error messages.

**Expected behavior**
Server operates normally without any error messages.

**Screenshots**
https://hastebin.com/wifosacijo.md

**Version Info**
`openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
`
https://hastebin.com/cuvotiwiru.java

**Additional context**
N/A.

**Comment by nacjm** [comment]
Same issue on mohsit with openj9, just FYI

**Comment by dmulloy2** [comment]
Does this happen in the 4.6.x branch? (latest dev builds)

Can't seem to reproduce it locally
