### ISSUE TITLE
why？

### ISSUE THREAD

**Issue by sktom1314** [dmulloy2/ProtocolLib#909]
[latest.log](https://github.com/dmulloy2/ProtocolLib/files/4908579/latest.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by MiniDigger** [comment]
pls properly fill out the template...
