### ISSUE TITLE
Calling outdated Bukkit functions

### ISSUE THREAD

**Issue by Darknuju** [dmulloy2/ProtocolLib#91]
When calling  MinecraftReflection.getBukkitItemStack(stack); 
I get this error which appears to be calling functions from an older version of Bukkit

http://pastebin.com/uXsACp0s

**Comment by dmulloy2** [comment]
This is not an error with ProtocolLib, but with your plugin. Can you provide the code in which you call the method?

**Comment by Darknuju** [comment]
this.stack = MinecraftReflection.getBukkitItemStack(stack);

**Comment by dmulloy2** [comment]
Try the latest build, it should be fixed.

**Comment by Darknuju** [comment]
I both compiled with the latest version (from the 28th) and now I get this error which leads to the exact same line of code as before

http://pastebin.com/BxVCHZNb

**Comment by Darknuju** [comment]
Ok I was able to fix it by cloning the item thrown in the arguments I will close this now

**Comment by Darknuju** [comment]
this.stack = MinecraftReflection.getBukkitItemStack(stack.clone());

**Comment by Darknuju** [comment]
Also the fix worked using the latest version

**Comment by Darknuju** [comment]
But not with the older versions
