### ISSUE TITLE
Problem with UltraCustomizer

### ISSUE THREAD

**Issue by arturek1666** [dmulloy2/ProtocolLib#911]
**Describe the bug**
Everytime someone writes on chat gives a massive spam:
https://gist.github.com/arturek1666/1aaafb3bf971eaf4329d2dbb5b3366b7
**To Reproduce**
1. Go to server (Ultra Customizer has to be installed)
2. Write in chat any messsage
3. On console you will then see this error (Error can be find in **Describe the bug**)

**Expected behavior**
No error in console when players write a message in chat

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://gist.github.com/arturek1666/3fee0dc9c53052a1d296bda1db6c24ff

**Comment by MiniDigger** [comment]
thats not a protocollib bug, talk to the author.

**Comment by arturek1666** [comment]
I did talk he replayed: It's protocollib issue xD

**Comment by games647** [comment]
Try it with Paper build number 90+. This could be a bug in Bungee chat included in Spigot.

**Comment by arturek1666** [comment]
I can confirm issue was resolved. Closing :)
