### ISSUE TITLE
Bug report :( urgent 

### ISSUE THREAD

**Issue by ImWinds** [dmulloy2/ProtocolLib#912]
**Describe the bug**
14.07 12:10:13 [Server] Craft Scheduler Thread - 1/ERROR [PunishControl] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for PunishControl
14.07 12:10:13 [Server] INFO java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:316) ~[ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib%20(1).jar:4.5.1]
14.07 12:10:13 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib%20(1).jar:4.5.1]
 
- Not sure if this is what you meant, but here's a description as well. I currently installed a plugin called PunishControl which is an Admin tool for banning, muting etc. and whenever I now try to do /plugins, I get spammed with these errors in my console and can also not see any of the plugins that are supposed to show up, Almost like the command doesn't work at all.

**To Reproduce**
3. Scroll down to '....'                                     N/A

**Expected behavior**
N/A
**Screenshots**
N/A

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/DypZK4cs

**Additional context**
N/A

**Comment by patrick-mc** [comment]
My guess is that the author of the plugin didn't add a overriding method on onPacketSending method.
I think you could just ignore it, or ask the author to add the following lines simply.
```java
	@Override
	public void onPacketSending(PacketEvent event) {}
```

I guess this would work
