### ISSUE TITLE
Maven builds are different from Jenkins / Source code and are missing important classes.

### ISSUE THREAD

**Issue by GBroad** [dmulloy2/ProtocolLib#915]
**Describe the bug**
Maven builds acquired from the repo seem to be missing classes. See below.

**To Reproduce**
1. Go to https://github.com/dmulloy2/ProtocolLib/blob/8c51b175c4681f200130ef01622ad97972967528/src/main/java/com/comphenix/protocol/wrappers/EnumWrappers.java#L371
Take note that EntityPose exists as an enum here.
2. Decompile any maven release. (Tested latest 4.5.x release and 4.6.0-SNAPSHOT)
3. Locate the same file, search for EntityPose.
4. The code does not exist. I had to recompile from the source to get this class to appear.

**Expected behavior**
Latest code in the project should be compiled and put onto the maven repository.

**Comment by patrick-mc** [comment]
my guess: the line 371 was added by #873, which was after the final shapshot release on nexus (june 30th, i remember)
So if you really need that class, i think you should get the latest jenkins build. see #880

**Comment by GBroad** [comment]
> my guess: the line 371 was added by #873, which was after the final shapshot release on nexus (june 30th, i remember)
> So if you really need that class, i think you should get the latest jenkins build. see #880

Ah, EntityPose has been around a short while, so I assumed it dated back farther than that. I ended up compiling myself.
