### ISSUE TITLE
Colored Scoreboard Teams 1.16

### ISSUE THREAD

**Issue by janLindner** [dmulloy2/ProtocolLib#917]
*Describe the question*
The `ChatColor` Enum has been replaced by a standard class. Previously you were able to write and read the team color as a ChatColor. Is there currently any alternative to color teams with packets ? 

*Previously used Code*

```java
    public ChatColor getColor() {
        return getPacket().getEnumModifier(ChatColor.class, MinecraftReflection.getMinecraftClass("EnumChatFormat"))
            .read(0);
    }
   
    public void setColor(@NotNull final ChatColor value) {
        getPacket().getEnumModifier(ChatColor.class, MinecraftReflection.getMinecraftClass("EnumChatFormat"))
            .write(0, value);
    }
```

**Comment by janLindner** [comment]
Relates to #735

**Comment by PainOchoco** [comment]
Bump! Is there a solution for this issue? ChatColor has been deprecated by Paper.
