### ISSUE TITLE
Red Plugin

### ISSUE THREAD

**Issue by saxojam** [dmulloy2/ProtocolLib#92]
After installing the plugin, the plugin shows up in the /plugins list as red, and fails to work correctly with other plugins, please help me fix this as soon as possible!

**Comment by dmulloy2** [comment]
Generally when a plugin is red, that means it errored on startup. Can you provide the startup log?

**Comment by dmulloy2** [comment]
If this is an issue in the latest builds, I'd like to get this fixed for the 3.6.4 release.

**Comment by saxojam** [comment]
I have resolved the issue, sorry for bothering you.
