### ISSUE TITLE
Bug report for 1.16.1 ProtocoLib

### ISSUE THREAD

**Issue by LittleHed** [dmulloy2/ProtocolLib#920]
**Describe the bug**
When I install this plugin on my server,my player can't play!They will be kicked quickly by Timed out

**To Reproduce**
1.Use 1.16.1 spigot
2.Install ProtocoLib

**Expected behavior**
When I join the server,I can't do anything such as destroy blocks!After a while,I was kicked by server

**Screenshots**
![MYR_{~08KFCGGC 66GK`_)D](https://user-images.githubusercontent.com/58099834/88035445-be71df00-cb74-11ea-8d30-f15a6b0a66bb.png)

**Version Info**
[dump-2020-07-21_20.13.24.txt](https://github.com/dmulloy2/ProtocolLib/files/4953389/dump-2020-07-21_20.13.24.txt)

**Additional context**
It don't show any error when starting server

**Comment by MiniDigger** [comment]
try without fixfreecam

**Comment by LittleHed** [comment]
Still the same

**Comment by MiniDigger** [comment]
are you sure your server isnt juch lagging? can you provide a timings report?

**Comment by LittleHed** [comment]
Umm let me test for a while.If it is no any problems,I will close the issue
