### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.   If this problem hasn't already been reported, please open a ticket   at *** with the following data

### ISSUE THREAD

**Issue by xiao-peng-you** [dmulloy2/ProtocolLib#931]
Problems still exist after the upgrade,Thanks to answer[
[bug.txt](https://github.com/dmulloy2/ProtocolLib/files/5045781/bug.txt)
](url)

**Comment by dmulloy2** [comment]
Update to 4.5.1 or 4.6.0
