### ISSUE TITLE
Fix backward compatibility of StructureModifier.withType

### ISSUE THREAD

**Issue by osipxd** [dmulloy2/ProtocolLib#935]
**Describe the bug**
Signature of method `withType` has been changed:
https://github.com/dmulloy2/ProtocolLib/blob/8c51b175c4681f200130ef01622ad97972967528/src/main/java/com/comphenix/protocol/reflect/StructureModifier.java#L470
https://github.com/dmulloy2/ProtocolLib/blob/05122150077fc54ae986fa250ae00f4284db5858/src/main/java/com/comphenix/protocol/reflect/StructureModifier.java#L481
Now I get:
```
java.lang.NoSuchMethodError: com.comphenix.protocol.reflect.StructureModifier.withType(Ljava/lang/Class;Lcom/comphenix/protocol/reflect/EquivalentConverter;)Lcom/comphenix/protocol/reflect/StructureModifier;
```
Sure I can recompile my plugin but then it will not work with older versions of ProtocolLib.
Can you provide a method with the old signature for compatibility?

**Version Info**
b474+

**Comment by dmulloy2** [comment]
Shoot. I thought that might happen, but I hoped Java would just gloss over the varargs there.

I'll add the old signature back tomorrow.

**Comment by osipxd** [comment]
There is a nice tool to prevent such cases:
https://lvc.github.io/japi-compliance-checker/
