### ISSUE TITLE
Unable to download dev version. Link is broken.

### ISSUE THREAD

**Issue by Jonah75** [dmulloy2/ProtocolLib#938]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
"Server Unavailable"

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by daniel11420** [comment]
Same here.

**Comment by dmulloy2** [comment]
Duplicate of #937
