### ISSUE TITLE
Invicible when morphong

### ISSUE THREAD

**Issue by zacraft** [dmulloy2/ProtocolLib#939]
**Describe the bug**
When I try to morph in a mob, I turn invicible. The TNT sound is still playing without any problem. 

**To Reproduce**
1. Typ /morph
2. Click on the mob you want to morph into
3. You turn invisible

**Expected behavior**
turn into the mob

**Screenshots**

**Version Info**
Protocol 4.5.1, minecraft version 1.16.1

**Comment by MiniDigger** [comment]
that sounds like a  problem with your morph plugin, not protocollib
