### ISSUE TITLE
Protocollib doesn't want to work

### ISSUE THREAD

**Issue by Ashelyn** [dmulloy2/ProtocolLib#94]
I'm currently trying to get Protocollib to work, for usage with CraftBook and the footprints feature. I get an error when it's loading up, and it ends up loading, but not working.
Log: http://pastebin.com/VfnamqZ2

I have already tried both the latest dev build, as well as the 1.8 version of ProtocolLib.
Edit: CraftBook spams console from time to time saying "Footprints do not work without ProtocolLib"

**Comment by dmulloy2** [comment]
ProtocolLib appears to be enabling properly. CraftBook handled footprints poorly in previous versions (empty catch-all), but blamed it on ProtocolLib. They removed the ProtocolLib dependency in more recent builds, so I'd try those.

**Comment by Ashelyn** [comment]
Thanks a lot, super nice to finally get it working :)
