### ISSUE TITLE
Error Message upon going to dev builds

### ISSUE THREAD

**Issue by SulphurSlap** [dmulloy2/ProtocolLib#940]
**Describe the bug**
Every time I try to go to https://ci.dmulloy2.net/job/ProtocolLib/, I get this error: https://prnt.sc/u0nl0s
**To Reproduce**
1. Go to 'https://www.spigotmc.org/resources/protocollib.1997/'
2. Click on 'https://prnt.sc/u0nkuf'
3. See error https://prnt.sc/u0nl0s

**Expected behavior**
I expected to go to the dev builds website, but instead I ended up with an error.

**Screenshots**
https://prnt.sc/u0nl0s

**Version Info**
N/A

**Comment by Eutherin** [comment]
Same

**Comment by titidelaff** [comment]
same

**Comment by Scarlet2031** [comment]
true mint

**Comment by dmulloy2** [comment]
Duplicate of #937
