### ISSUE TITLE
Unable to find MultiBlockChangeInfo (1.16.2)

### ISSUE THREAD

**Issue by joehot200** [dmulloy2/ProtocolLib#952]
**Describe the bug**
It is not possible to create a new com.comphenix.protocol.wrappers.MultiBlockChangeInfo.

**To Reproduce**
Create a new MultiBlockChangeInfo, such as:
`MultiBlockChangeInfo info = new MultiBlockChangeInfo(
								new Location(w, x, y, z), data);`
or:
`MultiBlockChangeInfo info = new MultiBlockChangeInfo(state.getLocation(), data);
`

**Error**
https://pastebin.com/vp43JM41

**Version Info**
Spigot version:
`[12:25:01] [Server thread/INFO]: This server is running CraftBukkit version git-
Spigot-b5a13e6-0491200 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSH
OT)
[12:25:01] [Server thread/INFO]: Checking version, please wait...
[12:25:01] [Thread-54/INFO]: You are running the latest version`
ProtocolLib version:
Snapshot b478: https://pastebin.com/2UGHs9As

**Comment by dmulloy2** [comment]
MultiBlockChangeInfo was removed in 1.16.2, see here for the new format: https://github.com/dmulloy2/ProtocolLib/issues/949
