### ISSUE TITLE
ExceptionInInitializerError MultiBlockChangeInfo

### ISSUE THREAD

**Issue by ChickenSaysBak** [dmulloy2/ProtocolLib#954]
**Describe the bug**
When trying to use MultiBlockChangeInfo on ProtocolLib's API, I receive a ExceptionInInitializerError and then all errors after that are NoClassDefFoundError. This was working fine before 1.16.2.

**To Reproduce**
1. Create code that uses MultiBlockChangeInfo on the latest ProtocolLib.
2. Run it on a 1.16.2 server.
3. There should be an error in console.

**Expected behavior**
I expected the code to run as it did in 1.16.1.

**Version Info**
https://pastebin.com/e5QpBRid

**Additional context**
Here are the 2 errors I received: https://pastebin.com/GhyE3X1G
Here is my code: https://pastebin.com/KKGZbEUK

**Comment by joehot200** [comment]
It was removed :(. Quote from dmulloy2:

> MultiBlockChangeInfo was removed in 1.16.2, see here for the new format: #949

**Comment by ChickenSaysBak** [comment]
> It was removed in 1.16.2. Quote from dmulloy2:
> 
> > MultiBlockChangeInfo was removed in 1.16.2, see here for the new format: #949

If it was removed, why does the IDE say it exists when I use the latest ProtocolLib jar?

**Comment by joehot200** [comment]
I wrote a guide for 1.16.2 multi block change on Spigot, I hope it helps. https://www.spigotmc.org/threads/new-1-16-2-multiblockchange-protocollib.461832/
