### ISSUE TITLE
CI Snapshots are not built

### ISSUE THREAD

**Issue by MeFisto94** [dmulloy2/ProtocolLib#957]
**Describe the bug**
The last CI Commit is from Jun 29/30th, which unfortunately lacks f19bfc613e589ead899891e4100b77de2100f76e required for ProtocolWrappers etc

**To Reproduce**
Check https://repo.dmulloy2.net/nexus/service/rest/repository/browse/public/com/comphenix/protocol/ProtocolLib/4.6.0-SNAPSHOT/4.6.0-20200630.003851-7/ 's timestamps (or the parent folder)

**Expected behavior**
Active snapshots and maybe a version once 1.16.2 is "stable"

**Comment by patrick-mc** [comment]
Agreed.
Its better to have nexus build rather than Jenkins build only.
Hope 4.6.0 release comes asap
