### ISSUE TITLE
Dev Build

### ISSUE THREAD

**Issue by Katzatrophe** [dmulloy2/ProtocolLib#962]
Hey, can you please send me the last dev build without holograms by the beacons?

**Comment by Katzatrophe** [comment]
Why you habe clone the Issue?

**Comment by dmulloy2** [comment]
Went through and closed all the old issues. I have no idea what you're asking though

**Comment by Katzatrophe** [comment]
It's already taken care of, the beacon had a hologram on the side with the latest dev build.
