### ISSUE TITLE
[Feature request] Add version/build number to JAR filename

### ISSUE THREAD

**Issue by Kopo942** [dmulloy2/ProtocolLib#967]
Title pretty much explains it all. Adding a version number to release JARs (or a short commit hash to dev build JARs) would make update checking, file management, etc. much easier IMO. Most major plugins already do this (WE, WG, EssX, LP etc.), so just a QOL improvement.

**Comment by Kopo942** [comment]
Why was this closed, is the feature not going to be implemented?

**Comment by dmulloy2** [comment]
Went through and nuked a bunch of old issues, but yeah I don't want to version the jar file
