### ISSUE TITLE
[ProtocolLib] Version (MC: 1.16.2) has not yet been tested! Proceed with caution.

### ISSUE THREAD

**Issue by uLyPANNN** [dmulloy2/ProtocolLib#969]
[10:06:36] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.16.2) has not yet been tested! Proceed with caution.
 
you can remove this, it appears every time in the console.

**Comment by ShioDEV** [comment]
Shouldn't be removed, because there are still some issues. I've just created one.
