### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by srnyx** [dmulloy2/ProtocolLib#979]
**Describe the bug**
The server keeps crashing over and over again

**To Reproduce**
1. Use the latest ProtocolLib version

**Expected behavior**
No crashing

**Version Info**
v4.5.1, [dump-2020-09-21_01.23.14.txt](https://github.com/dmulloy2/ProtocolLib/files/5253083/dump-2020-09-21_01.23.14.txt)

**Additional context**
Doesn't crash right away, only after a few minutes of the server being online

**Comment by patrick-mc** [comment]
ProtocolLib v4.5.1 does not support 1.16.x.
Instead, use the latest build from dmulloy2's CI/CD server
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by srnyx** [comment]
> ProtocolLib v4.5.1 does not support 1.16.x.
> Instead, use the latest build from dmulloy2's CI/CD server
> https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Did that and now getting this error (and the server is still randomly crashing):
`23.09 00:15:09 [Server] ERROR Encountered an unexpected exception
23.09 00:15:09 [Server] INFO java.lang.IllegalArgumentException: No suitable constructor could be found.
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:163) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.createChatPackets(ChatExtensions.java:143) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.sendMessageSilently(ChatExtensions.java:90) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.broadcastMessageSilently(ChatExtensions.java:163) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.CommandPacket.broadcastMessageSilently(CommandPacket.java:146) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.ProtocolLib$2.publish(ProtocolLib.java:323) ~[?:?]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.log(Logger.java:876) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:478) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.09 00:15:09 [Server] INFO Caused by: java.lang.NullPointerException
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.wrappers.BukkitConverters.lambda$asUnwrapper$0(BukkitConverters.java:1058) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:127) ~[?:?]
23.09 00:15:09 [Server] INFO 	... 15 more
23.09 00:15:09 [Server] ERROR Cause of unexpected exception was
23.09 00:15:09 [Server] INFO java.lang.NullPointerException: null
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.wrappers.BukkitConverters.lambda$asUnwrapper$0(BukkitConverters.java:1058) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:127) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.createChatPackets(ChatExtensions.java:143) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.sendMessageSilently(ChatExtensions.java:90) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.utility.ChatExtensions.broadcastMessageSilently(ChatExtensions.java:163) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.CommandPacket.broadcastMessageSilently(CommandPacket.java:146) ~[?:?]
23.09 00:15:09 [Server] INFO 	at com.comphenix.protocol.ProtocolLib$2.publish(ProtocolLib.java:323) ~[?:?]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at java.util.logging.Logger.log(Logger.java:876) ~[?:1.8.0_211]
23.09 00:15:09 [Server] INFO 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:478) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-168]
23.09 00:15:09 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.09 00:15:09 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2020-09-23_00.15.09-server.txt`

**Comment by srnyx** [comment]
This issue still persists, please help!

**Comment by patrick-mc** [comment]
> This issue still persists, please help!

```
java.lang.IllegalArgumentException: No suitable constructor could be found.
```

This error occurs when the use of packet is invalid.
![image](https://user-images.githubusercontent.com/32794309/94389181-1b4bd000-018a-11eb-8e00-7c8e768399d5.png)
The chat packet has changed since v1_16_R1, maybe this could be the reason.
If not, please present the code, or contact the plugin creator.
Thanks.

**Comment by srnyx** [comment]
> > This issue still persists, please help!
> 
> ```
> java.lang.IllegalArgumentException: No suitable constructor could be found.
> ```
> 
> This error occurs when the use of packet is invalid.
> ![image](https://user-images.githubusercontent.com/32794309/94389181-1b4bd000-018a-11eb-8e00-7c8e768399d5.png)
> The chat packet has changed since v1_16_R1, maybe this could be the reason.
> If not, please present the code, or contact the plugin creator.
> Thanks.

So it's being caused by something with my chat plugin?

**Comment by patrick-mc** [comment]
> > > This issue still persists, please help!
> > 
> > 
> > ```
> > java.lang.IllegalArgumentException: No suitable constructor could be found.
> > ```
> > 
> > 
> > This error occurs when the use of packet is invalid.
> > ![image](https://user-images.githubusercontent.com/32794309/94389181-1b4bd000-018a-11eb-8e00-7c8e768399d5.png)
> > The chat packet has changed since v1_16_R1, maybe this could be the reason.
> > If not, please present the code, or contact the plugin creator.
> > Thanks.
> 
> So it's being caused by something with my chat plugin?

Most likely, yes, based on your dumped information,.but i'm not really sure.
