### ISSUE TITLE
Error every time on server reload and SOMETIMES random by server running

### ISSUE THREAD

**Issue by Dariusztmt** [dmulloy2/ProtocolLib#982]
**Describe the bug**
When I reload server every time when someone tries join got kicked and in console prints error:
Internal Exception: java.io.IOException: Error while write(...): Connection reset by peer

And some times when player changes server possible to get this error, I have no idea why, but random by a lot of times changing server possible.

**To Reproduce**
1. Full error that I got: https://pastebin.com/8ywDNuLa

**Version Info**
Link to dump: https://pastebin.com/RceD5fJ6

**Additional context**
And this problem comes from yours plugin, because when I remove it errors too will be removed.
So all what I can say, I believe you will fix problem otherwise I need for all time remove plugin.

**Comment by patrick-mc** [comment]
Reload is not really recommended action to use when using ProtocolLib. I think there is no way to fix this problem, AFAIK.

**Comment by Dariusztmt** [comment]
And now I see that on 4.2.0 version of Protocolib is no error by using Spigot 1.8.8.
So something is wrong in plugin that above 4.2.0 version gives that.

With Spigot 1.16.3 and this own new build all good.

So I don't know or creator of plugin will try fix this or no. Because this is legit from his plugin newer versions.

**Comment by Dariusztmt** [comment]
And now I see that on 4.2.0 version of Protocolib is no error by using Spigot 1.8.8.
So something is wrong in plugin that above 4.2.0 version gives that.

With Spigot 1.16.3 and this own new build all good.

So I don't know or creator of plugin will try fix this or no. Because this is legit from his plugin newer versions.

Sorry for tag, because this is old thread...
Tags: @patrick-mc

**Comment by dmulloy2** [comment]
There aren't any plans to fix reloading
