### ISSUE TITLE
Multiverse problem big problem

### ISSUE THREAD

**Issue by christianjosias** [dmulloy2/ProtocolLib#985]
hi i'm having a problem with protocollib kicking me when i'm joining a multiverse world

**Comment by dmulloy2** [comment]
can you post a stack trace or anything

**Comment by christianjosias** [comment]
i have a waterfall (bungeecord) network

waterfall(bungeecord):
plugins:
luckperms-bungee-5.0.130.jar
bungeecordpartyandfriends-1.0.80.jar
craftingstore.jar
advancedban-2.1.9-release.jar
viaversion-3.1.1.jar
viarewind-1.5.1.jar
hubcommand.jar
viabackwards-3.1.1.jar

server2(the server i use multiverse on):
plugins:
worldguard-bukkit-6.2.2.jar
nofalldamage.jar
luckperms-bukkit-5.0.130.jar
antiforceop.jar
essentialsx-2.17.2.0.jar
nocheatplus.jar
protocollib-4.5.1.jar
multiverse-core-2.5.0.jar
simplescore-3.3.2.jar
worldedit-bukkit-6.1.9.jar
voidgenerator-1.6.2.jar
essentialsxchat-2.17.2.0.jar
nocollide-1.9-4.jar
essentialsxspawn-2.17.2.0.jar
supervanish-6.1.8.jar
nohunger.jar
craftingstore.jar
citizens-2.0.24.jar
tntrun_reloaded-6.8.3.jar
vault-1.7.2.jar
spawn.jar
placeholderapi-2.10.6.jar
norainreloaded.jar
mycommand-5.6.7.jar
holographicdisplays-2.4.3.jar
holographicextension-1.10.9.jar
citizensserverselector-0.3.3.jar

**Comment by TheFlagCourier** [comment]
> can you post a stack trace or anything

@christianjosias, it may be more helpful to dmulloy2 for you to give a [Timings](https://www.youtube.com/watch?v=T4J0A9l7bfQ) report for 'server2', and a [pastebin](https://paste.ubuntu.com) of your `/logs/latest.log` file ,after you've been kicked.
