### ISSUE TITLE
An illegal reflective access operation has occurred 

### ISSUE THREAD

**Issue by GertVerhoek** [dmulloy2/ProtocolLib#986]
**Describe the bug**
Got a warning in my server console sometime after a restart, only plugin that I run that uses ProtocolLib is SuperVanish as far as I know.
Not sure how much of an issue this is, doesn't seem to affect the server negatively atm.

**The warning:**
>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.comphenix.net.sf.cglib.core.ReflectUtils$1 (file:/home/container/plugins/ProtocolLib-4.6.0-SNAPSHOT.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.comphenix.net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**To Reproduce**
Warning did appear after a restart but I don't know how much time it took after the restart as the console didn't report a time.
No players were online at that moment.

**Version Info**
https://pastebin.com/tAvjfkir

**Comment by patrick-mc** [comment]
Since Java 9, accessing to internal JDK methods throws warning on console, afaik.
CGLib has no plan to fix this issue, and #984 might fix this warning from this plugin in the future.

Protocollib suggests users to use Java 8, instead of Java 9 or later.
#603

**Comment by SirCraftypants** [comment]
Like many others I'm getting the reflective issue too, switching back to Java 8 is not an option for me and 2 of my premium plugins require libs disguises that require protocollib, sorry to reopen this but i need to put it out somewhere and thought i'd put it here instead of creating an entirely new issue.

**Comment by SirCraftypants** [comment]
https://paste.helpch.at/mexarigefu.sql

Line 2 just appeared out of nowhere, seems like the problem is getting worse.

**Comment by SirCraftypants** [comment]
https://paste.helpch.at/apetebejot.md

Restarted my server and something else has appeared.
