### ISSUE TITLE
FieldAccessException: No field with type java.util.List exists in class PacketPlayOutWorldParticles.

### ISSUE THREAD

**Issue by IITFA** [dmulloy2/ProtocolLib#987]
**Describe the bug**
Console spammed with the following error when a player is roaming around.
https://pastebin.com/raw/9xYzGmMx

**To Reproduce**
??

**Expected behavior**
Probably shouldn't be spamming the console and obviously something isn't working right.

**Screenshots**

**Version Info**
https://pastebin.com/raw/rnEyxksE

**Additional context**

**Comment by dmulloy2** [comment]
This is an issue with orebfuscator
