### ISSUE TITLE
Possible chunk issues

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#99]
Reported by @Kainzo on the forums.

Pictures:
http://i.imgur.com/RCSsGXc.png
http://i.imgur.com/W1i9Yp6.png

I'm pretty sure it's caused by a plugin using ProtocolLib, but I'm not totally sure which one. I've added ````/protocol dump```` to help.

**Comment by dmulloy2** [comment]
Closing due to lack of information and inability to reproduce.

**Comment by Rocknest** [comment]
Possibly it's related
http://pastebin.com/Whnj2U0g

**Comment by dmulloy2** [comment]
@Rocknest That doesn't seem to directly involve ProtocolLib, the ProtocolLib elements are just passing on the packet.
