### ISSUE TITLE
Server Internal Error Issue

### ISSUE THREAD

**Issue by DebuffPvP** [dmulloy2/ProtocolLib#997]
**Describe the bug**
in console i get this

[21:48:12 WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.nio.channels.ClosedChannelException

also get a connection lost error and won't let me join

**To Reproduce**
I don't really know it's a complex error that states broken pipe when i try and log in or connection lost and shows this messages in the console and i asked around a buncha developers and they all said it's most likely related to protocollib so here i am

**Expected behavior**

**Version Info**
dump info:  https://pastebin.com/Ghx9G6Sw

**Comment by iSilviu-debug** [comment]
Same error here #993 
The main problem is JAVA 15
