### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by Blocksnmore** [dmulloy2/ProtocolLib#998]
**Describe the bug**

**To Reproduce**
1. Download protocollib
2. Run it on a 1.16.3 server
3. Attempt to join
4. You will be kicked for "Internal server error" and in console it says "Failed to handle packet"

**Expected behavior**
You should just join the server no issue
**Screenshots**
https://blocksnmore.is-inside.me/7V6AoCLH.png
**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/RzyX9x1x
**Additional context**
Ive seen similar reports about this issue on the tracker

**Comment by iSilviu-debug** [comment]
Same error here #993
The main problem is JAVA 15

**Comment by Blocksnmore** [comment]
Ima close this, i resolved it by downgrading java 8
