### ISSUE TITLE
ResourceKey reflection

### ISSUE THREAD

**Issue by Peng1104** [dmulloy2/ProtocolLib#999]
**Is your feature request related to a problem? Please describe.**
I am trying to create the Respawn packet for the 1.16_R1 / 1.16_R2 but there is a huge change in this version, the DimensionManager is on the 1.16_R1 a ResourceKey the same for the new filed in the packet the ResourceKey for the world. [Spigot Post](https://www.spigotmc.org/threads/protocollib-create-a-packetplayoutrespawn.469718/)

**Describe the solution you'd like**
I need a class that is equivalent to the ResourceKey of the minecraft server something like the MinecraftKey class, a way that I can create or modify it (I am lost with it)

![Respawn Packet on the 1.16_R1](https://user-images.githubusercontent.com/12024658/97499168-2b52fd00-194c-11eb-94be-162221683224.png)

**Comment by games647** [comment]
`ResourceKey<World>` => new StructureModifier #906

`ResourceKey<DimensionManager` => updated ProtocolLib code - same API: #893

**Comment by Peng1104** [comment]
@games647 Ok i got for the capture of a ResourceKey for a given World, but how can I manipulate / create it using reflections?

**Comment by games647** [comment]
You don't need reflection to modify it. There is a fixed modifier for it: https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/events/PacketContainer.java#L998-L1001
